Repository yunionio/cloudpods, pull requests merged in 2019-09, with the labels that each got.

#2673 fix: provides policies info in auth token response
  docs/schemas/auth.yaml
  docs/schemas/roleassignments.yaml
  pkg/apis/compute/nat.go
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/token3.go
Labels: approved, area/keystone, lgtm, size/L

#2674 Automated cherry pick of #2673: fix: provides policies info in auth token response
  docs/schemas/auth.yaml
  docs/schemas/roleassignments.yaml
  pkg/apis/compute/nat.go
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/token3.go
Labels: approved, lgtm, size/L

#2675 Automated cherry pick of #2673: fix: provides policies info in auth token response
  docs/schemas/auth.yaml
  docs/schemas/roleassignments.yaml
  pkg/apis/compute/nat.go
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/token3.go
Labels: approved, lgtm, size/L

#2656 fix: allow column search in array
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/region, lgtm, size/S

#2657 Automated cherry pick of #2656: fix: allow column search in array
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm

#2658 Automated cherry pick of #2656: fix: allow column search in array
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/S

#2661 Automated cherry pick of #2659: fix: huawei fail to import image
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/storagecache.go
Labels: approved, lgtm, size/M

#2659 fix: huawei fail to import image
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/storagecache.go
Labels: approved, area/region, lgtm, size/M

#2660 Automated cherry pick of #2659: fix: huawei fail to import image
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/storagecache.go
Labels: approved, lgtm, size/M

#2662 fix: qcloud fail to set object acl
  pkg/multicloud/qcloud/object.go
Labels: approved, area/region, lgtm, size/XS

#2664 Automated cherry pick of #2662: fix: qcloud fail to set object acl
  pkg/multicloud/qcloud/object.go
Labels: approved, lgtm, size/XS

#2665 fix: 1. glance/keystone version handler fix 2. allow run glance as normal user
  pkg/image/service/handlers.go
  pkg/image/service/service.go
  pkg/keystone/service/handlers.go
Labels: approved, area/keystone, lgtm, size/S

#2666 Automated cherry pick of #2665: fix: 1. glance/keystone version handler fix 2. allow run glance as normal user
  pkg/image/service/handlers.go
  pkg/image/service/service.go
  pkg/keystone/service/handlers.go
Labels: approved, lgtm, size/S

#2663 Automated cherry pick of #2662: fix: qcloud fail to set object acl
  pkg/multicloud/qcloud/object.go
Labels: approved, lgtm, size/XS

#2668 Automated cherry pick of #2665: fix: 1. glance/keystone version handler fix 2. allow run glance as normal user
  pkg/image/service/handlers.go
  pkg/image/service/service.go
  pkg/keystone/service/handlers.go
Labels: approved, lgtm, size/S

#2667 Automated cherry pick of #2665: fix: 1. glance/keystone version handler fix 2. allow run glance as normal user
  pkg/image/service/handlers.go
  pkg/image/service/service.go
  pkg/keystone/service/handlers.go
Labels: approved, lgtm, size/S

#2676 baremetal: auto prepare when pxe boot
  pkg/baremetal/handler/handlers.go
  pkg/compute/tasks/baremetal_unconvert_hypervisor_task.go
Labels: approved, area/baremetal, lgtm, size/S

#2677 Automated cherry pick of #2676: baremetal: auto prepare when pxe boot
  pkg/baremetal/handler/handlers.go
  pkg/compute/tasks/baremetal_unconvert_hypervisor_task.go
Labels: approved, lgtm, size/S

#2683 bugfix: fix glance update mindisk
  pkg/image/models/images.go
Labels: approved, area/image, lgtm, size/XS

#2678 Automated cherry pick of #2676: baremetal: auto prepare when pxe boot
  pkg/baremetal/handler/handlers.go
  pkg/compute/tasks/baremetal_unconvert_hypervisor_task.go
Labels: approved, lgtm, size/S

#2679 Automated cherry pick of #2676: baremetal: auto prepare when pxe boot
  pkg/baremetal/handler/handlers.go
  pkg/compute/tasks/baremetal_unconvert_hypervisor_task.go
Labels: approved, lgtm, size/S

#2684 Automated cherry pick of #2683: fix glance update mindisk
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#2686 Automated cherry pick of #2683: fix glance update mindisk
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#2685 Automated cherry pick of #2683: fix glance update mindisk
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#2698 README: fix docs not found link
  README-CN.md
  README.md
Labels: approved, area/util, lgtm, size/XS

#2680 fix: azure create bucket failure due to empty storageClass
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_storage.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/objectstore/shell.go
Labels: approved, area/region, lgtm, size/M

#2681 Automated cherry pick of #2680: fix: azure create bucket failure due to empty storageClass
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_storage.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/objectstore/shell.go
Labels: approved, lgtm, size/M

#2682 Automated cherry pick of #2680: fix: azure create bucket failure due to empty storageClass
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_storage.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/objectstore/shell.go
Labels: approved, lgtm, size/M

#2690 fix: no quota check when making directory
  pkg/compute/models/buckets.go
Labels: approved, area/region, lgtm, size/S

#2691 Automated cherry pick of #2690: fix: no quota check when making directory
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/S

#2692 Automated cherry pick of #2690: fix: no quota check when making directory
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/S

#2689 fix: 避免裸金属服务器转宿主机任务失败
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_undeploy_task.go
Labels: approved, area/region, lgtm, size/S

#2693 Automated cherry pick of #2689: fix: 避免裸金属服务器转宿主机任务失败
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_undeploy_task.go
Labels: approved, lgtm, size/S

#2695 Automated cherry pick of #2689: fix: 避免裸金属服务器转宿主机任务失败
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_undeploy_task.go
Labels: approved, lgtm, size/S

#2694 Automated cherry pick of #2689: fix: 避免裸金属服务器转宿主机任务失败
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_undeploy_task.go
Labels: approved, lgtm, size/S

#2699 fix: 忽略裸金属器删除条件
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XS

#2700 Automated cherry pick of #2699: fix: 忽略裸金属器删除条件
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#2701 Automated cherry pick of #2699: fix: 忽略裸金属器删除条件
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#2702 Automated cherry pick of #2699: fix: 忽略裸金属器删除条件
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#2707 scheduler: fix reserved resource out of limit bug
  pkg/scheduler/cache/candidate/hosts.go
Labels: approved, area/scheduler, lgtm, size/S

#2708 Automated cherry pick of #2707: scheduler: fix reserved resource out of limit bug
  pkg/scheduler/cache/candidate/hosts.go
Labels: approved, lgtm, size/S

#2709 Automated cherry pick of #2707: scheduler: fix reserved resource out of limit bug
  pkg/scheduler/cache/candidate/hosts.go
Labels: approved, lgtm, size/S

#2710 Automated cherry pick of #2707: scheduler: fix reserved resource out of limit bug
  pkg/scheduler/cache/candidate/hosts.go
Labels: approved, lgtm, size/S

#2703 fix: guest get host nil pointer panic
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XS

#2704 Automated cherry pick of #2703: fix: guest get host nil pointer panic
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#2705 Automated cherry pick of #2703: fix: guest get host nil pointer panic
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#2706 Automated cherry pick of #2703: fix: guest get host nil pointer panic
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#2717 fix: bucket list access accessUrl nil pointer panic
  pkg/compute/models/buckets.go
Labels: approved, area/region, lgtm, size/M

#2718 Automated cherry pick of #2717: fix: bucket list access accessUrl nil pointer panic
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/M

#2719 Automated cherry pick of #2717: fix: bucket list access accessUrl nil pointer panic
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/M

#2720 Bugfix: nat
  pkg/compute/models/purge.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/multicloud/aliyun/natdtable.go
  pkg/multicloud/aliyun/natstable.go
Labels: approved, lgtm, needs-area, size/M

#2722 Automated cherry pick of #2720: add OnBindIPCompleteFailed and fix aliyun Refresh for snat and dnat
  pkg/compute/models/purge.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/multicloud/aliyun/natdtable.go
  pkg/multicloud/aliyun/natstable.go
Labels: approved, lgtm, size/M

#2721 Automated cherry pick of #2720: add OnBindIPCompleteFailed and fix aliyun Refresh for snat and dnat
  pkg/compute/models/purge.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/multicloud/aliyun/natdtable.go
  pkg/multicloud/aliyun/natstable.go
Labels: approved, lgtm, size/M

#2711 bugfix: snapshotpolicy
  pkg/compute/service/handlers.go
Labels: approved, area/region, lgtm, size/XS

#2713 Automated cherry pick of #2711: hanler snapshotpolicy cache
  pkg/compute/service/handlers.go
Labels: approved, lgtm, size/XS

#2712 Automated cherry pick of #2711: hanler snapshotpolicy cache
  pkg/compute/service/handlers.go
Labels: approved, lgtm, size/XS

#2714 bugfix : fix auto snapshot check quota, name, owner
  pkg/compute/models/disks.go
  pkg/compute/models/snapshots.go
  pkg/compute/service/service.go
Labels: approved, area/region, lgtm, size/M

#2715 Automated cherry pick of #2714: fix auto snapshot check quota, name, owner
  pkg/compute/models/disks.go
  pkg/compute/models/snapshots.go
  pkg/compute/service/service.go
Labels: approved, lgtm, size/M

#2716 Automated cherry pick of #2714: fix auto snapshot check quota, name, owner
  pkg/compute/models/disks.go
  pkg/compute/models/snapshots.go
  pkg/compute/service/service.go
Labels: approved, lgtm, size/M

#2726 Automated cherry pick of #2723: region: fix create params cdrom missing
  pkg/compute/models/guests.go
Labels: size/XS

#2725 Automated cherry pick of #2723: region: fix create params cdrom missing
  pkg/compute/models/guests.go
Labels: size/XS

#2724 Automated cherry pick of #2723: region: fix create params cdrom missing
  pkg/compute/models/guests.go
Labels: size/XS

#2723 region: fix create params cdrom missing
  pkg/compute/models/guests.go
Labels: area/region, size/XS

#2730 fix: s3cli enable debug trace
  pkg/multicloud/objectstore/objectstore.go
Labels: approved, area/util, lgtm, size/XS

#2731 Automated cherry pick of #2730: fix: s3cli enable debug trace
  pkg/multicloud/objectstore/objectstore.go
Labels: approved, lgtm, size/XS

#2732 Automated cherry pick of #2730: fix: s3cli enable debug trace
  pkg/multicloud/objectstore/objectstore.go
Labels: approved, lgtm, size/XS

#2736 fix: for backward compatility, only check account id consistency for non-empty account id
  pkg/compute/models/cloudaccounts.go
Labels: approved, area/region, lgtm, size/XS

#2737 Automated cherry pick of #2736: fix: for backward compatility, only check account id consistency for non-empty account id
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/XS

#2738 Automated cherry pick of #2736: fix: for backward compatility, only check account id consistency for non-empty account id
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/XS

#2740 Automated cherry pick of #2727: fix snapshot policy filter
  pkg/apis/compute/snapshot_const.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/M

#2727 bugfix : fix snapshot policy filter
  pkg/apis/compute/snapshot_const.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/compute/models/disks.go
Labels: approved, area/region, lgtm, size/M

#2739 Automated cherry pick of #2727: fix snapshot policy filter
  pkg/apis/compute/snapshot_const.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/M

#2754 Automated cherry pick of #2744: qcloud sunday
  pkg/compute/models/snapshotpolicycache.go
  pkg/compute/models/snapshotpolicydisks.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/snapshotpolicy_disk_task.go
  pkg/multicloud/qcloud/snapshot_policy.go
Labels: approved, lgtm, size/M

#2744 bugfix: snapshot policy
  pkg/compute/models/snapshotpolicycache.go
  pkg/compute/models/snapshotpolicydisks.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/snapshotpolicy_disk_task.go
  pkg/multicloud/qcloud/snapshot_policy.go
Labels: approved, area/region, lgtm, size/M

#2755 Automated cherry pick of #2744: qcloud sunday
  pkg/compute/models/snapshotpolicycache.go
  pkg/compute/models/snapshotpolicydisks.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/snapshotpolicy_disk_task.go
  pkg/multicloud/qcloud/snapshot_policy.go
Labels: approved, lgtm, size/M

#2750 lbagent: 重用会话token
  pkg/lbagent/api.go
  pkg/lbagent/models/haproxy.go
Labels: approved, area/util, lgtm, size/S

#2751 Automated cherry pick of #2750: lbagent: reuse mcclient client session
  pkg/lbagent/api.go
  pkg/lbagent/models/haproxy.go
Labels: approved, area/util, lgtm, size/S

#2752 Automated cherry pick of #2750: lbagent: reuse mcclient client session
  pkg/lbagent/api.go
  pkg/lbagent/models/haproxy.go
Labels: approved, lgtm, size/S

#2753 Automated cherry pick of #2750: lbagent: reuse mcclient client session
  pkg/lbagent/api.go
  pkg/lbagent/models/haproxy.go
Labels: approved, lgtm, size/S

#2734 Automated cherry pick of #2733: fix: optimize logger query time
  cmd/climc/shell/actions.go
  cmd/climc/shell/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/paging.go
  pkg/mcclient/modules/base.go
  pkg/mcclient/options/base.go
  pkg/util/printutils/printjson.go
Labels: approved, lgtm, size/L

#2733 fix: optimize logger query time
  cmd/climc/shell/actions.go
  cmd/climc/shell/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/paging.go
  pkg/mcclient/modules/base.go
  pkg/mcclient/options/base.go
  pkg/util/printutils/printjson.go
Labels: approved, area/region, lgtm, size/L

#2735 Automated cherry pick of #2733: fix: optimize logger query time
  cmd/climc/shell/actions.go
  cmd/climc/shell/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/paging.go
  pkg/mcclient/modules/base.go
  pkg/mcclient/options/base.go
  pkg/util/printutils/printjson.go
Labels: approved, lgtm, size/L

#2766 fix: 不能无限制追加 application/json
  pkg/util/httputils/httputils.go
Labels: approved, area/region, lgtm, size/XS

#2767 Automated cherry pick of #2766: fix: 不能无限制追加 application/json
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/XS

#2758 bugfix: fix vnc connect, filter qmp event, save image status
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/tasks/guest_save_image_task.go
  pkg/hostman/monitor/qmp.go
Labels: approved, area/host, area/region, lgtm, size/S

#2760 Automated cherry pick of #2758: fix vnc connect, filter qmp event
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/tasks/guest_save_image_task.go
  pkg/hostman/monitor/qmp.go
Labels: approved, lgtm, size/S

#2759 Automated cherry pick of #2758: fix vnc connect, filter qmp event
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/tasks/guest_save_image_task.go
  pkg/hostman/monitor/qmp.go
Labels: approved, lgtm, size/S

#2761 Automated cherry pick of #2758: fix vnc connect, filter qmp event
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/tasks/guest_save_image_task.go
  pkg/hostman/monitor/qmp.go
Labels: approved, lgtm, size/S

#2762 lbagents: deploy: 检查服务账号有效性
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, area/region, lgtm, size/S

#2764 Automated cherry pick of #2762: lbagents: deploy: 检查服务账号有效性
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, lgtm, size/S

#2765 Automated cherry pick of #2762: lbagents: deploy: 检查服务账号有效性
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, lgtm, size/S

#2763 Automated cherry pick of #2762: lbagents: deploy: 检查服务账号有效性
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, lgtm, size/S

#2768 Automated cherry pick of #2766: fix: 不能无限制追加 application/json
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/XS

#2769 Automated cherry pick of #2766: fix: 不能无限制追加 application/json
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/XS

#2749 Automated cherry pick of #2747: fix: networkinterfaces belong system resource
  pkg/cloudcommon/policy/resources.go
Labels: approved, lgtm, size/XS

#2747 fix: networkinterfaces belong system resource
  pkg/cloudcommon/policy/resources.go
Labels: approved, area/region, lgtm, size/XS

#2748 Automated cherry pick of #2747: fix: networkinterfaces belong system resource
  pkg/cloudcommon/policy/resources.go
Labels: approved, lgtm, size/XS

#2772 fix: allow set object acl in batch
  cmd/climc/shell/buckets.go
  pkg/cloudcommon/db/paging.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
Labels: approved, area/region, lgtm, size/M

#2771 Automated cherry pick of #2733: fix: optimize logger query time
  cmd/climc/shell/actions.go
  cmd/climc/shell/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/paging.go
  pkg/mcclient/modules/base.go
  pkg/mcclient/options/base.go
  pkg/util/printutils/printjson.go
Labels: approved, lgtm, size/L

#2773 Automated cherry pick of #2772: fix: allow set object acl in batch
  cmd/climc/shell/buckets.go
  pkg/cloudcommon/db/paging.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/M

#2774 Automated cherry pick of #2772: fix: allow set object acl in batch
  cmd/climc/shell/buckets.go
  pkg/cloudcommon/db/paging.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/M

#2781 Automated cherry pick of #2780: snapshotpolicy and disk should have same domain and project in snapshotpolicydisks
  docs/schemas/snapshotpolicy.yaml
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/service/handlers.go
Labels: approved, lgtm, size/S

#2782 Automated cherry pick of #2780: snapshotpolicy and disk should have same domain and project in snapshotpolicydisks
  docs/schemas/snapshotpolicy.yaml
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/service/handlers.go
Labels: approved, lgtm, size/S

#2780 Bugfix: snapshotpolicy
  docs/schemas/snapshotpolicy.yaml
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/service/handlers.go
Labels: approved, area/region, lgtm, size/S

#2775 fix: 1. nil pointer panic error when accessing resource pool and
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/L

#2776 Automated cherry pick of #2775: fix: 1. nil pointer panic error when accessing resource pool and storagecache 2. support multiple disk format
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/util/esxi/vdisk.go
  pkg/util/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#2777 Automated cherry pick of #2775: fix: 1. nil pointer panic error when accessing resource pool and storagecache 2. support multiple disk format
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#2778 Automated cherry pick of #2775: fix: 1. nil pointer panic error when accessing resource pool and storagecache 2. support multiple disk format
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#2795 Bugfix and feature add: nat
  cmd/climc/shell/natgateways.go
  docs/index.yaml
  docs/natgateway/dnat-eips.yaml
  docs/natgateway/snat-eips.yaml
  docs/schemas/natgateway.yaml
  pkg/cloudcommon/policy/resources.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
Labels: approved, area/region, lgtm, size/L

#2783 fix: 避免重装系统后同步信息导致磁盘类型都为系统盘
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/S

#2784 Automated cherry pick of #2783: fix: 避免重装系统后同步信息导致磁盘类型都为系统盘
  pkg/util/esxi/virtualmachine.go
Labels: approved, lgtm, size/S

#2786 Automated cherry pick of #2783: fix: 避免重装系统后同步信息导致磁盘类型都为系统盘
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/S

#2756 Automated cherry pick of #2741: io throttle add log event
  pkg/apis/compute/guest_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdisks.go
  pkg/compute/tasks/guest_block_io_throttle_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qmp.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/M

#2741 bugfix: io throttle add log event
  pkg/apis/compute/guest_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdisks.go
  pkg/compute/tasks/guest_block_io_throttle_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qmp.go
  pkg/util/logclient/consts.go
Labels: approved, area/region, lgtm, size/M

#2757 Automated cherry pick of #2741: io throttle add log event
  pkg/apis/compute/guest_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdisks.go
  pkg/compute/tasks/guest_block_io_throttle_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qmp.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/M

#2796 Automated cherry pick of #2795: add interface fetch resources of snats and dnats
  cmd/climc/shell/natgateways.go
  docs/index.yaml
  docs/natgateway/dnat-eips.yaml
  docs/natgateway/snat-eips.yaml
  docs/schemas/natgateway.yaml
  pkg/cloudcommon/policy/resources.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
Labels: approved, lgtm, size/L

#2785 Automated cherry pick of #2783: fix: 避免重装系统后同步信息导致磁盘类型都为系统盘
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/S

#2789 Automated cherry pick of #2787: fix guest manager server struct
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: approved, lgtm, size/L

#2788 Automated cherry pick of #2787: fix guest manager server struct
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: approved, lgtm, size/L

#2787 bugfix: guest manager servers use sync.Map
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: approved, area/host, lgtm, size/L

#2797 Automated cherry pick of #2795: add interface fetch resources of snats and dnats
  cmd/climc/shell/natgateways.go
  docs/index.yaml
  docs/natgateway/dnat-eips.yaml
  docs/natgateway/snat-eips.yaml
  docs/schemas/natgateway.yaml
  pkg/cloudcommon/policy/resources.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
Labels: approved, lgtm, size/L

#2770 feature: keystone support CAS SSO authentication
  cmd/climc/shell/identityproviders.go
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/cas.go
  pkg/apis/identity/consts.go
  pkg/appsrv/send.go
  pkg/compute/regiondrivers/base.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/cas/cas_test.go
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/cas/test/casfe.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/sync.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/mcclient/cas.go
  pkg/mcclient/input.go
  pkg/mcclient/mcclient.go
  pkg/util/httputils/httputils.go
Labels: approved, area/keystone, lgtm, size/XXL

#2792 Automated cherry pick of #2770: feature: keystone support CAS SSO authentication
  cmd/climc/shell/identityproviders.go
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/cas.go
  pkg/apis/identity/consts.go
  pkg/appsrv/send.go
  pkg/compute/regiondrivers/base.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/cas/cas_test.go
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/cas/test/casfe.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/sync.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/mcclient/cas.go
  pkg/mcclient/input.go
  pkg/mcclient/mcclient.go
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/XXL

#2793 Automated cherry pick of #2770: feature: keystone support CAS SSO authentication
  cmd/climc/shell/identityproviders.go
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/cas.go
  pkg/apis/identity/consts.go
  pkg/appsrv/send.go
  pkg/compute/regiondrivers/base.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/cas/cas_test.go
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/cas/test/casfe.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/sync.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/mcclient/cas.go
  pkg/mcclient/input.go
  pkg/mcclient/mcclient.go
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/XXL

#2798 Automated cherry pick of #2787: fix guest manager server struct
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: approved, lgtm, size/L

#2801 fix: api gateway logout handler error and fix go fmt issues
  cmd/climc/shell/natgateways.go
  pkg/apigateway/handler/auth.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/keystone/driver/cas/test/casfe.go
Labels: approved, area/apigateway, lgtm, size/S

#2802 Automated cherry pick of #2801: fix: api gateway logout handler error and fix go fmt issues
  cmd/climc/shell/natgateways.go
  pkg/apigateway/handler/auth.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/keystone/driver/cas/test/casfe.go
Labels: approved, lgtm, size/L

#2803 Automated cherry pick of #2801: fix: api gateway logout handler error and fix go fmt issues
  cmd/climc/shell/natgateways.go
  pkg/apigateway/handler/auth.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/keystone/driver/cas/test/casfe.go
Labels: approved, lgtm, size/L

#2804 fix: 避免解绑EIP后释放EIP任务失败
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, area/region, lgtm, size/S

#2806 Automated cherry pick of #2804: fix: 避免解绑EIP后释放EIP任务失败
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/S

#2805 Automated cherry pick of #2804: fix: 避免解绑EIP后释放EIP任务失败
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/S

#2807 Automated cherry pick of #2804: fix: 避免解绑EIP后释放EIP任务失败
  pkg/util/qcloud/qcloud.go
Labels: approved, lgtm, size/S

#2813 fix: fail to find host ip in virtual console vnic
  pkg/multicloud/esxi/host.go
Labels: approved, area/region, lgtm, size/S

#2814 Automated cherry pick of #2813: fix: fail to find host ip in virtual console vnic
  pkg/util/esxi/host.go
Labels: approved, lgtm, size/S

#2815 Automated cherry pick of #2813: fix: fail to find host ip in virtual console vnic
  pkg/multicloud/esxi/host.go
Labels: approved, lgtm, size/S

#2817 Automated cherry pick of #2813: fix: fail to find host ip in virtual console vnic
  pkg/multicloud/esxi/host.go
Labels: approved, lgtm, size/S

#2810 Automated cherry pick of #2808: fix: yunionapi nil pointer panic after failed login
  pkg/apigateway/handler/auth.go
Labels: approved, lgtm, size/XS

#2808 fix: yunionapi nil pointer panic after failed login
  pkg/apigateway/handler/auth.go
  pkg/appsrv/dispatcher/handlers.go
Labels: approved, area/apigateway, lgtm, size/XS

#2811 Automated cherry pick of #2808: fix: yunionapi nil pointer panic after failed login
  pkg/apigateway/handler/auth.go
  pkg/appsrv/dispatcher/handlers.go
Labels: approved, lgtm, size/XS

#2816 Automated cherry pick of #2809: build: 将check与构建部分解耦
  .circleci/config.yml
  Makefile
  pkg/keystone/driver/cas/doc.go
  pkg/multicloud/aliyun/doc.go
  pkg/multicloud/aliyun/provider/doc.go
  pkg/multicloud/aliyun/shell/doc.go
  pkg/multicloud/aws/doc.go
  pkg/multicloud/aws/provider/doc.go
  pkg/multicloud/aws/shell/doc.go
  pkg/multicloud/azure/concurrent/doc.go
  pkg/multicloud/azure/doc.go
  pkg/multicloud/azure/progress/doc.go
  pkg/multicloud/azure/provider/doc.go
  pkg/multicloud/azure/shell/doc.go
  pkg/multicloud/doc.go
  pkg/multicloud/esxi/doc.go
  pkg/multicloud/esxi/provider/doc.go
  pkg/multicloud/esxi/shell/doc.go
  pkg/multicloud/huawei/client/auth/credentials/doc.go
  pkg/multicloud/huawei/client/auth/doc.go
  pkg/multicloud/huawei/client/auth/signers/doc.go
  pkg/multicloud/huawei/client/doc.go
  pkg/multicloud/huawei/client/manager/doc.go
  pkg/multicloud/huawei/client/modules/doc.go
  pkg/multicloud/huawei/client/requests/doc.go
  pkg/multicloud/huawei/client/responses/doc.go
  pkg/multicloud/huawei/doc.go
  pkg/multicloud/huawei/obs/doc.go
  pkg/multicloud/huawei/provider/doc.go
  pkg/multicloud/huawei/shell/doc.go
  pkg/multicloud/loader/doc.go
  pkg/multicloud/objectstore/ceph/doc.go
  pkg/multicloud/objectstore/ceph/provider/doc.go
  pkg/multicloud/objectstore/doc.go
  pkg/multicloud/objectstore/provider/doc.go
  pkg/multicloud/objectstore/shell/doc.go
  pkg/multicloud/openstack/doc.go
  pkg/multicloud/openstack/provider/doc.go
  pkg/multicloud/openstack/shell/doc.go
  pkg/multicloud/qcloud/doc.go
  pkg/multicloud/qcloud/provider/doc.go
  pkg/multicloud/qcloud/shell/doc.go
  pkg/multicloud/ucloud/doc.go
  pkg/multicloud/ucloud/provider/doc.go
  pkg/multicloud/ucloud/shell/doc.go
  pkg/multicloud/zstack/doc.go
  pkg/multicloud/zstack/provider/doc.go
  pkg/multicloud/zstack/shell/doc.go
  pkg/s3gateway/handlers/doc.go
  pkg/s3gateway/models/doc.go
  pkg/s3gateway/session/doc.go
  pkg/util/s3auth/doc.go
  pkg/util/validate/doc.go
Labels: size/L

#2818 Automated cherry pick of #2809: build: 将check与构建部分解耦
  .circleci/config.yml
  Makefile
Labels: size/M

#2827 .circleci: fix requires
  .circleci/config.yml
  Makefile
Labels: area/util, size/S

#2828 Automated cherry pick of #2827: .circleci: fix requires
  .circleci/config.yml
  Makefile
Labels: size/S

#2829 Automated cherry pick of #2827: .circleci: fix requires
  .circleci/config.yml
  Makefile
Labels: size/S

#2830 Automated cherry pick of #2827: .circleci: fix requires
  .circleci/config.yml
  Makefile
Labels: size/S

#2819 fix: 避免数据盘顺序也被颠倒
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/XS

#2821 Automated cherry pick of #2819: fix: 避免数据盘顺序也被颠倒
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/XS

#2820 Automated cherry pick of #2819: fix: 避免数据盘顺序也被颠倒
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/XS

#2822 Automated cherry pick of #2819: fix: 避免数据盘顺序也被颠倒
  pkg/util/esxi/virtualmachine.go
Labels: approved, lgtm, size/XS

#2824 Automated cherry pick of #2823: fix: 修复安全组关联数量校验不正确问题
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS
