Repository yunionio/cloudpods, pull requests merged in 2019-04, with the labels that each got.

#75 腾讯云使用shell格式userdata,避免和cloud-init冲突导致绑定秘钥失败
  pkg/cloudprovider/instance.go
  pkg/compute/models/guests.go
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
Labels: needs-backport

#11 guest import from libvirt
  Gopkg.lock
  Gopkg.toml
  cmd/climc/shell/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guest_import_api.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/host_import_libvirt_servers_task.go
  pkg/hostman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/storageman/diskutils.go
  pkg/mcclient/modules/base.go
  pkg/mcclient/modules/resource.go
  pkg/util/logclient/logclient.go
  pkg/util/printutils/printjson.go
  vendor/github.com/libvirt/libvirt-go-xml/.gitignore
  vendor/github.com/libvirt/libvirt-go-xml/.gitmodules
  vendor/github.com/libvirt/libvirt-go-xml/.gitpublish
  vendor/github.com/libvirt/libvirt-go-xml/.travis.yml
  vendor/github.com/libvirt/libvirt-go-xml/LICENSE
  vendor/github.com/libvirt/libvirt-go-xml/README.md
  vendor/github.com/libvirt/libvirt-go-xml/capabilities.go
  vendor/github.com/libvirt/libvirt-go-xml/doc.go
  vendor/github.com/libvirt/libvirt-go-xml/document.go
  vendor/github.com/libvirt/libvirt-go-xml/domain.go
  vendor/github.com/libvirt/libvirt-go-xml/domain_capabilities.go
  vendor/github.com/libvirt/libvirt-go-xml/domain_snapshot.go
  vendor/github.com/libvirt/libvirt-go-xml/interface.go
  vendor/github.com/libvirt/libvirt-go-xml/network.go
  vendor/github.com/libvirt/libvirt-go-xml/node_device.go
  vendor/github.com/libvirt/libvirt-go-xml/nwfilter.go
  vendor/github.com/libvirt/libvirt-go-xml/secret.go
  vendor/github.com/libvirt/libvirt-go-xml/storage_encryption.go
  vendor/github.com/libvirt/libvirt-go-xml/storage_pool.go
  vendor/github.com/libvirt/libvirt-go-xml/storage_vol.go
  vendor/github.com/libvirt/libvirt-go-xml/xmlutil.go
Labels: feature

#155 bugfix: guest desc and guest create backup
  cmd/climc/shell/hostwires.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_backup_tasks.go
Labels: bug

#165 手动同步时默认是深度全量同步
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
Labels: needs-backport

#161 避免腾讯云cache镜像失败
  pkg/util/qcloud/host.go
  pkg/util/qcloud/image.go
  pkg/util/qcloud/storagecache.go
Labels: needs-backport

#170 忽略因镜像问题导致初始化失败
  pkg/util/azure/azure.go
  pkg/util/azure/classic_instance.go
  pkg/util/azure/instance.go
Labels: needs-backport

#173 climc: use default webconsole server url
  cmd/climc/shell/webconsole.go
Labels: feature, needs-backport

#171 gpu: find gpu iommu group devs and bind all dev to driver vfio-pci
  pkg/hostman/isolated_device/isolated_device.go
Labels: bug

#167 region: save server create params into metadata
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: needs-work

#172 bugs fix
  pkg/compute/models/guest_actions.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/util/logclient/logclient.go
Labels: bug, needs-backport

#206 add OWNERS to support CI robot
  OWNERS
Labels: size/S

#201 补充缺失的allowempty tag
  pkg/util/azure/azure.go
  pkg/util/azure/instance.go
Labels: approved, lgtm, size/XS

#207 Automated cherry pick of #206: add OWNERS to support CI robot
  OWNERS
Labels: size/S

#208 Automated cherry pick of #206: add OWNERS to support CI robot
  OWNERS
Labels: size/S

#209 Automated cherry pick of #206: add OWNERS to support CI robot
  OWNERS
Labels: size/S

#204 Automated cherry pick of #201: 补充缺失的al
  pkg/util/azure/azure.go
  pkg/util/azure/instance.go
Labels: approved, lgtm

#205 Automated cherry pick of #193: improve server-list performance
  Gopkg.lock
  pkg/appsrv/appsrv.go
  pkg/appsrv/workers.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guestjoints.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/managedresource.go
  pkg/mcclient/options/base.go
  pkg/util/stringutils2/sortedstrings.go
  pkg/util/stringutils2/sortedstrings_test.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, lgtm, size/XXL

#193 improve server-list performance
  Gopkg.lock
  pkg/appsrv/appsrv.go
  pkg/appsrv/workers.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guestjoints.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/managedresource.go
  pkg/mcclient/options/base.go
  pkg/util/stringutils2/sortedstrings.go
  pkg/util/stringutils2/sortedstrings_test.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, lgtm, size/XXL

#211 feature: add option to specify resources allowing name synchronization
  pkg/compute/models/guests.go
  pkg/compute/options/namesync.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: approved, lgtm, size/M

#212 Automated cherry pick of #211: feature: add option NameSyncResources to specify resources
  pkg/compute/models/guests.go
  pkg/compute/options/namesync.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: approved, lgtm, size/M

#197 增加错误重试,增加任务成功率
  pkg/util/qcloud/qcloud.go
Labels: approved, lgtm

#198 Automated cherry pick of #197: 增加错误重
  pkg/util/qcloud/qcloud.go
Labels: approved, lgtm

#200 Automated cherry pick of #197: 增加错误重
  pkg/util/qcloud/qcloud.go
Labels: approved, lgtm

#199 Automated cherry pick of #197: 增加错误重
  pkg/util/qcloud/qcloud.go
Labels: approved, lgtm

#202 Automated cherry pick of #201: 补充缺失的al
  pkg/util/azure/azure.go
  pkg/util/azure/instance.go
Labels: approved, lgtm

#203 Automated cherry pick of #201: 补充缺失的al
  pkg/util/azure/azure.go
  pkg/util/azure/instance.go
Labels: approved, lgtm

#214 fix: mark synced removed server with @lost<date> suffix
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#215 Automated cherry pick of #214: fix: mark synced removed server with @lost<date> suffix
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#218 Automated cherry pick of #216: 添加缺失的cl
  pkg/mcclient/options/schedule.go
Labels: approved, lgtm, size/XS

#216 添加缺失的climc参数选项
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/XS

#217 Automated cherry pick of #216: 添加缺失的cl
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/XS

#219 Automated cherry pick of #216: 添加缺失的cl
  pkg/mcclient/options/schedule.go
Labels: approved, lgtm, size/XS

#210 同步镜像最小要求系统盘大小
  pkg/compute/guestdrivers/azure.go
  pkg/util/azure/azure.go
  pkg/util/azure/image.go
  pkg/util/azure/shell/image.go
Labels: approved, lgtm, size/M

#220 Automated cherry pick of #210: 同步镜像最
  pkg/compute/guestdrivers/azure.go
  pkg/util/azure/azure.go
  pkg/util/azure/image.go
  pkg/util/azure/shell/image.go
Labels: approved, lgtm, size/M

#221 Automated cherry pick of #210: 同步镜像最
  pkg/compute/guestdrivers/azure.go
  pkg/util/azure/azure.go
  pkg/util/azure/image.go
  pkg/util/azure/shell/image.go
Labels: approved, lgtm, size/M

#222 Automated cherry pick of #210: 同步镜像最
  pkg/compute/guestdrivers/azure.go
  pkg/util/azure/azure.go
  pkg/util/azure/image.go
  pkg/util/azure/shell/image.go
Labels: approved, lgtm, size/M

#228 Automated cherry pick of #226: implement hijacker
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
Labels: approved, lgtm, size/S

#226 feature: appsrv implement hijacker
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
Labels: approved, lgtm, size/S

#229 Automated cherry pick of #226: implement hijacker
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
Labels: approved, lgtm, size/S

#227 Automated cherry pick of #226: implement hijacker
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
Labels: approved, lgtm, size/S

#232 cherry_pick_pull: 兼容python3
  scripts/cherry_pick_pull.sh
Labels: approved, enhancement, lgtm, size/XS

#225 fix: GetJointModule2 无法找到 compute_v2 的 endpoint
  pkg/mcclient/modules/modules.go
Labels: approved, bug, lgtm, size/XS

#231 Automated cherry pick of #225: fix: GetJointModule2 无法
  pkg/mcclient/modules/modules.go
Labels: approved, lgtm, size/XS

#235 Bugfix/yousong use xxxln
  Gopkg.lock
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/baremetal_server_reset_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/aliyun/instance.go
  pkg/util/aws/image.go
  pkg/util/aws/instance.go
  pkg/util/aws/keypair_test.go
  pkg/util/aws/securitygroup.go
  pkg/util/azure/debug.go
  pkg/util/huawei/client/modules/manager_base.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/image.go
  pkg/util/huawei/instance.go
  pkg/util/qemuimg/qemuimg_test.go
  pkg/util/ucloud/disk.go
  pkg/util/ucloud/instance.go
  pkg/util/ucloud/securitygroup.go
  vendor/yunion.io/x/log/log.go
Labels: approved, lgtm, size/L

#241 fix: baremetal convert to host missing cpu and memory params
  pkg/compute/hostdrivers/base.go
Labels: approved, lgtm, size/XS

#242 Automated cherry pick of #241: fix: baremetal convert to host missing cpu and memory params
  pkg/compute/hostdrivers/base.go
Labels: approved, lgtm, size/XS

#224 feature: action log send to ws service
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/tasks/guest_create_task.go
  pkg/logger/models/actionlog.go
  pkg/logger/service/service.go
  pkg/util/logclient/logclient.go
Labels: approved, lgtm, size/M

#246 Automated cherry pick of #224: action log send to ws service
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/tasks/guest_create_task.go
  pkg/logger/models/actionlog.go
  pkg/logger/service/service.go
  pkg/util/logclient/logclient.go
Labels: approved, lgtm, size/M

#248 Automated cherry pick of #224: action log send to ws service
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/tasks/guest_create_task.go
  pkg/logger/models/actionlog.go
  pkg/logger/service/service.go
  pkg/util/logclient/logclient.go
Labels: approved, lgtm, size/L

#233 fix: move vm's metadata sync into deep sync cycle
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/util/aws/instance.go
Labels: approved, lgtm, size/M

#234 Automated cherry pick of #233: fix: move vm's metadata sync into deep sync cycle
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/util/aws/instance.go
Labels: approved, lgtm, size/M

#249 Automated cherry pick of #236: 优化扩容已
  pkg/util/openstack/disk.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/M

#251 Automated cherry pick of #236: 优化扩容已
  pkg/util/openstack/disk.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/M

#236 优化扩容已挂载磁盘失败问题
  pkg/util/openstack/disk.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/M

#250 Automated cherry pick of #236: 优化扩容已
  pkg/util/openstack/disk.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/M

#247 Automated cherry pick of #224: action log send to ws service
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/tasks/guest_create_task.go
  pkg/logger/models/actionlog.go
  pkg/logger/service/service.go
  pkg/util/logclient/logclient.go
Labels: approved, lgtm, size/M

#238 Automated cherry pick of #235: dep: update yunion.io/x/log
  Gopkg.lock
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/baremetal_server_reset_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/aliyun/instance.go
  pkg/util/aws/image.go
  pkg/util/aws/instance.go
  pkg/util/aws/keypair_test.go
  pkg/util/aws/securitygroup.go
  pkg/util/azure/debug.go
  pkg/util/huawei/client/modules/manager_base.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/image.go
  pkg/util/huawei/instance.go
  pkg/util/qemuimg/qemuimg_test.go
  pkg/util/ucloud/disk.go
  pkg/util/ucloud/instance.go
  pkg/util/ucloud/securitygroup.go
  vendor/yunion.io/x/log/log.go
Labels: approved, lgtm, size/L

#239 Automated cherry pick of #238: dep: update yunion.io/x/log
  Gopkg.lock
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/baremetal_server_reset_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/aliyun/instance.go
  pkg/util/aws/image.go
  pkg/util/aws/instance.go
  pkg/util/aws/keypair_test.go
  pkg/util/aws/securitygroup.go
  pkg/util/azure/debug.go
  pkg/util/huawei/client/modules/manager_base.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/image.go
  pkg/util/huawei/instance.go
  pkg/util/qemuimg/qemuimg_test.go
  vendor/yunion.io/x/log/log.go
Labels: approved, lgtm, size/L

#240 Automated cherry pick of #239: dep: update yunion.io/x/log
  Gopkg.lock
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/baremetal_server_reset_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/aliyun/instance.go
  pkg/util/aws/image.go
  pkg/util/aws/instance.go
  pkg/util/aws/keypair_test.go
  pkg/util/aws/securitygroup.go
  pkg/util/azure/debug.go
  pkg/util/huawei/client/modules/manager_base.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/image.go
  pkg/util/huawei/instance.go
  pkg/util/qemuimg/qemuimg_test.go
  vendor/yunion.io/x/log/log.go
Labels: approved, lgtm, size/L

#243 bugfix: climc server-deploy
  pkg/apis/compute/api.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/S

#244 Automated cherry pick of #243: fix climc server-deploy
  pkg/apis/compute/api.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/S

#223 region: storage support set schedtags
  cmd/climc/shell/hosts.go
  cmd/climc/shell/schedtaghosts.go
  cmd/climc/shell/storages.go
  pkg/compute/models/hosts.go
  pkg/compute/models/schedtagjoint.go
  pkg/compute/models/schedtags.go
  pkg/compute/models/storages.go
  pkg/mcclient/options/schedtags.go
Labels: approved, lgtm, size/L

#237 Automated cherry pick of #223: region: storage support set schedtags
  cmd/climc/shell/hosts.go
  cmd/climc/shell/schedtaghosts.go
  cmd/climc/shell/storages.go
  pkg/compute/models/hosts.go
  pkg/compute/models/schedtagjoint.go
  pkg/compute/models/schedtags.go
  pkg/compute/models/storages.go
  pkg/mcclient/options/schedtags.go
Labels: approved, lgtm, size/L

#254 Bugfix duplicate init dbapp
  pkg/logger/service/service.go
Labels: approved, lgtm, size/XS

#255 fix duplicate init db app
  pkg/logger/service/service.go
Labels: approved, lgtm, size/XS

#257 Automated cherry pick of #256: fix: region list empty or occupied hosts not work
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#256 fix: region list empty or occupied hosts not work
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#273 fix: running guest count incorrect if containers running on host
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#274 Automated cherry pick of #273: fix: running guest count incorrect if containers running on
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#276 Automated cherry pick of #273: fix: running guest count incorrect if containers running on
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#275 Automated cherry pick of #273: fix: running guest count incorrect if containers running on
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#271 fix: scheduler input incompatibility
  pkg/cloudcommon/cmdline/helper.go
Labels: approved, lgtm, size/XS

#272 Automated cherry pick of #271: fix: scheduler input incompatibility
  pkg/cloudcommon/cmdline/helper.go
Labels: approved, lgtm, size/XS

#12 Automated cherry pick of #11: import servers from libvirt
  Gopkg.lock
  Gopkg.toml
  cmd/climc/shell/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guest_import_api.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/host_import_libvirt_servers_task.go
  pkg/hostman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/storageman/diskutils.go
  pkg/mcclient/modules/base.go
  pkg/mcclient/modules/resource.go
  pkg/util/logclient/logclient.go
  pkg/util/printutils/printjson.go
  vendor/github.com/libvirt/libvirt-go-xml/.gitignore
  vendor/github.com/libvirt/libvirt-go-xml/.gitmodules
  vendor/github.com/libvirt/libvirt-go-xml/.gitpublish
  vendor/github.com/libvirt/libvirt-go-xml/.travis.yml
  vendor/github.com/libvirt/libvirt-go-xml/LICENSE
  vendor/github.com/libvirt/libvirt-go-xml/README.md
  vendor/github.com/libvirt/libvirt-go-xml/capabilities.go
  vendor/github.com/libvirt/libvirt-go-xml/doc.go
  vendor/github.com/libvirt/libvirt-go-xml/document.go
  vendor/github.com/libvirt/libvirt-go-xml/domain.go
  vendor/github.com/libvirt/libvirt-go-xml/domain_capabilities.go
  vendor/github.com/libvirt/libvirt-go-xml/domain_snapshot.go
  vendor/github.com/libvirt/libvirt-go-xml/interface.go
  vendor/github.com/libvirt/libvirt-go-xml/network.go
  vendor/github.com/libvirt/libvirt-go-xml/node_device.go
  vendor/github.com/libvirt/libvirt-go-xml/nwfilter.go
  vendor/github.com/libvirt/libvirt-go-xml/secret.go
  vendor/github.com/libvirt/libvirt-go-xml/storage_encryption.go
  vendor/github.com/libvirt/libvirt-go-xml/storage_pool.go
  vendor/github.com/libvirt/libvirt-go-xml/storage_vol.go
  vendor/github.com/libvirt/libvirt-go-xml/xmlutil.go
Labels: approved, lgtm, size/XXL

#258 修复:通过镜像创建的磁盘只能使用镜像ID参数
  pkg/util/azure/disk.go
  pkg/util/azure/image.go
Labels: approved, lgtm, needs-backport, size/S

#259 Automated cherry pick of #258: 修复:通过镜
  pkg/util/azure/disk.go
  pkg/util/azure/image.go
Labels: approved, lgtm, size/S

#260 Automated cherry pick of #258: 修复:通过镜
  pkg/util/azure/disk.go
  pkg/util/azure/image.go
Labels: approved, lgtm, size/S

#261 Automated cherry pick of #258: 修复:通过镜
  pkg/util/azure/disk.go
  pkg/util/azure/image.go
Labels: approved, lgtm, size/S

#262 migrate: fix task complete
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: approved, lgtm, size/XS

#263 Automated cherry pick of #262: fix task complete
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: approved, lgtm, size/XS

#264 Automated cherry pick of #262: fix task complete
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: approved, lgtm, size/XS

#265 Automated cherry pick of #262: fix task complete
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: approved, lgtm, size/XS

#269 Automated cherry pick of #266: 修复选择endpoint
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/XS

#267 Automated cherry pick of #266: 修复选择endpoint
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/XS

#266 修复选择endpoint type异常错误
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/XS

#268 Automated cherry pick of #266: 修复选择endpoint
  pkg/util/openstack/openstack.go
Labels: approved, lgtm, size/XS

#252 Feature: allow delete cloud-account with resources
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/cloud_account_delete_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/compute/tasks/vpc_delete_task.go
  pkg/util/aws/region.go
  pkg/util/aws/shell/s3.go
  pkg/util/aws/storagecache.go
  pkg/util/esxi/shell/host.go
Labels: approved, lgtm, size/XXL

#253 Automated cherry pick of #252: Feature: allow delete cloud-account with resources
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/cloud_account_delete_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/compute/tasks/vpc_delete_task.go
  pkg/util/aws/region.go
  pkg/util/aws/shell/s3.go
  pkg/util/aws/storagecache.go
  pkg/util/esxi/shell/host.go
Labels: approved, lgtm, size/XXL

#270 region: enhance server clone releated apis
  cmd/climc/shell/hosts.go
  cmd/climc/shell/servers.go
  cmd/climc/shell/specs.go
  pkg/appsrv/appsrv.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/specs.go
  pkg/compute/specs/handler.go
Labels: approved, lgtm, size/L

#278 Automated cherry pick of #277: fix: scheduler schedtag filters execute when candidates
  pkg/scheduler/algorithm/predicates/aggregate_predicate.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/core/context.go
Labels: approved, lgtm, size/M

#277 fix: scheduler schedtag filters execute when candidates specified
  pkg/scheduler/algorithm/predicates/aggregate_predicate.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/core/context.go
Labels: approved, lgtm, size/M

#282 Automated cherry pick of #281: fix: host 内存规
  cmd/climc/shell/specs.go
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#281 fix: host 内存规格信息直接为 MB
  cmd/climc/shell/specs.go
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/S

#279 fix: scheduler network predicate not set capability when host filtered
  pkg/scheduler/algorithm/predicates/baremetal/network_predicate.go
  pkg/scheduler/algorithm/predicates/guest/network_predicate.go
Labels: approved, lgtm, size/XS

#280 Automated cherry pick of #279: fix: scheduler network predicate not set capability when host
  pkg/scheduler/algorithm/predicates/baremetal/network_predicate.go
  pkg/scheduler/algorithm/predicates/guest/network_predicate.go
Labels: approved, lgtm, size/XS

#245 华为云主机创建及重装系统等问题修复
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/models/guests.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/host.go
  pkg/util/huawei/instance.go
  pkg/util/huawei/storage.go
Labels: approved, lgtm, size/M

#284 Automated cherry pick of #245: huawei test bugfix
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/models/guests.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/host.go
  pkg/util/huawei/instance.go
  pkg/util/huawei/storage.go
Labels: approved, lgtm, size/M

#285 Automated cherry pick of #245: huawei test bugfix
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/models/guests.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/host.go
  pkg/util/huawei/instance.go
  pkg/util/huawei/storage.go
Labels: approved, lgtm, size/M

#286 Automated cherry pick of #245: huawei test bugfix
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/models/guests.go
  pkg/util/huawei/disk.go
  pkg/util/huawei/host.go
  pkg/util/huawei/instance.go
  pkg/util/huawei/storage.go
Labels: approved, lgtm, size/M

#288 Automated cherry pick of #74: vm clone #167: region: save server create params into metadata #270: region: enhance server clone releated apis
  cmd/climc/shell/hosts.go
  cmd/climc/shell/servers.go
  cmd/climc/shell/specs.go
  pkg/apis/compute/api.go
  pkg/appsrv/appsrv.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/specs.go
  pkg/compute/specs/handler.go
  pkg/compute/tasks/guest_clone_task.go
  pkg/compute/tasks/schedule.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/L

#294 fix: scheduler disk schedtag filter host type not convert to guest hy…
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: approved, lgtm, size/XS

#290 避免未setstorageinfo之前连接ceph集群
  pkg/hostman/storageman/storagehandler.go
Labels: approved, lgtm, size/XS

#291 Automated cherry pick of #290: 避免未setstorageinfo
  pkg/hostman/storageman/storagehandler.go
Labels: approved, lgtm, size/XS

#292 Automated cherry pick of #290: 避免未setstorageinfo
  pkg/hostman/storageman/storagehandler.go
Labels: approved, lgtm, size/XS

#293 Automated cherry pick of #290: 避免未setstorageinfo
  pkg/hostman/storageman/storagehandler.go
Labels: approved, lgtm, size/XS

#298 fix: server clone 参数处理扩容情况
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#300 baremetal-agent: fix host undo convert duplicate access_mac error
  pkg/baremetal/pxe/dhcp.go
Labels: approved, lgtm, size/XS

#287 Automated cherry pick of #283: fix: make cloud account&provider enable status more
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/cloud_account_delete_task.go
  pkg/util/aws/disk.go
  pkg/util/huawei/client/modules/manager_base.go
  pkg/util/huawei/disk.go
Labels: approved, lgtm, size/L

#303 lblistener: 检查更新参数时默认使用已绑定acl
  pkg/compute/models/loadbalancerlisteners.go
Labels: approved, lgtm, size/XS

#296 避免guest状态出现中间情况
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/tasks/disk_resize_task.go
Labels: approved, lgtm, size/M

#307 baremetal misc bugfixes
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/util/tftp/tftp.go
Labels: approved, lgtm, size/L

#316 Automated cherry pick of #307: fix: 1. baremetal always boot from pxe 2. baremetal prepare
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/util/tftp/tftp.go
Labels: approved, lgtm, size/L

#317 Automated cherry pick of #307: fix: 1. baremetal always boot from pxe 2. baremetal prepare
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/util/tftp/tftp.go
Labels: approved, lgtm, size/L

#318 fix: add server create-params region and zone info
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#320 bugfix: region server-change-config
  cmd/climc/shell/servers.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/M

#322 fix: limit baremetal tftp MaxBlockSize to 512
  pkg/baremetal/pxe/tftp.go
Labels: approved, lgtm, size/XS

#328 fix: create disk input need storage_id in JSON object
  pkg/apis/compute/api.go
Labels: approved, lgtm, size/XS

#330 fix: server-deploy fail to set password if reset_password not set
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#332 Automated cherry pick of #330: fix: server-deploy fail to set password if reset_password not
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#333 Automated cherry pick of #330: fix: server-deploy fail to set password if reset_password not
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#331 Automated cherry pick of #330: fix: server-deploy fail to set password if reset_password not
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#334 fix: fail to fetch private image as admin role
  pkg/cloudcommon/db/fetch.go
Labels: approved, lgtm, size/XS

#335 fix: esxi ignore check file failure in host.getIStoragecache
  pkg/util/esxi/host.go
Labels: approved, lgtm, size/S

#336 fix: webconsole vmrc protocol not support
  pkg/webconsole/handlers.go
  pkg/webconsole/session/remote_console.go
Labels: approved, area/webconsole, lgtm, size/S

#344 fix: baremetal support options for tftp timeout retry times and block size
  pkg/baremetal/options/options.go
  pkg/baremetal/pxe/tftp.go
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/XS

#349 fix: baremetal scheduler forecast fail
  pkg/scheduler/cache/candidate/baremetals.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/handler/forecast_helper.go
Labels: approved, area/scheduler, lgtm, size/XS

#350 避免eip未找到时,未设置server状态为fail
  pkg/compute/tasks/eip_associate_task.go
Labels: approved, lgtm, size/S

#352 增加判断subtask准确度
  pkg/cloudcommon/db/taskman/tasks.go
Labels: approved, lgtm, size/XS

#359 移除重复代码
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/tasks/disk_resize_task.go
Labels: approved, lgtm, size/S

#364 fix: fail to delete removed cloud resources
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/L

#326 huawei disk delete error fix
  pkg/util/huawei/instance.go
  pkg/util/huawei/storage.go
Labels: approved, lgtm, size/XS

#370 Bugfix/yousong lb delete
  pkg/compute/models/loadbalancer_common.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/loadbalancer_backendgroup_delete_task.go
  pkg/compute/tasks/loadbalancer_delete_task.go
  pkg/compute/tasks/loadbalancer_listener_delete_task.go
Labels: approved, lgtm, size/M

#373 lb: 改正预删listener时未预删listener rule
  pkg/compute/models/loadbalancerlisteners.go
Labels: approved, lgtm, size/XS

#375 Bugfix/yousong lb delete 270
  pkg/compute/models/loadbalancer_common.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/tasks/loadbalancer_backendgroup_delete_task.go
  pkg/compute/tasks/loadbalancer_delete_task.go
  pkg/compute/tasks/loadbalancer_listener_delete_task.go
Labels: approved, lgtm, size/M

#376 Bugfix/yousong lb delete 260
  pkg/compute/models/loadbalancer_common.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/tasks/loadbalancer_backendgroup_delete_task.go
  pkg/compute/tasks/loadbalancer_delete_task.go
  pkg/compute/tasks/loadbalancer_listener_delete_task.go
Labels: approved, lgtm, size/M

#378 lb: https: allow change certificate
  pkg/compute/models/loadbalancerlisteners.go
Labels: approved, lgtm, size/XS

#365 为 climc 增加 update-perform --cmp-only 选项，只升级计算节点
  cmd/climc/shell/updates.go
Labels: approved, lgtm, size/S

#368 Hotfix/qx cloudprovider info
  pkg/compute/models/cloudregionresource.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/zoneresource.go
Labels: approved, lgtm, size/L

#380 fix: scheduler sku cache stale when region sync sku finished
  cmd/climc/shell/schedulers.go
  pkg/compute/models/cloudsync.go
  pkg/mcclient/modules/mod_scheduler.go
  pkg/scheduler/data_manager/sku/sku.go
  pkg/scheduler/handler/handler.go
Labels: approved, lgtm, size/M

#385 磁盘大小向上取整
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#327 Hotfix/qx lb manager
  pkg/apis/compute/loadbalancer_const.go
  pkg/cloudprovider/loadbalancer.go
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/models/loadbalancers.go
  pkg/mcclient/modules/mod_loadbalancerlisteners.go
  pkg/mcclient/modules/mod_loadbalancers.go
  pkg/mcclient/options/loadbalanceracls.go
  pkg/mcclient/options/loadbalancercertificates.go
  pkg/mcclient/options/loadbalancerlisteners.go
  pkg/mcclient/options/loadbalancers.go
  pkg/util/aliyun/loadbalancer.go
  pkg/util/aliyun/loadbalancerhttplistener.go
  pkg/util/aliyun/loadbalancerhttpslistener.go
  pkg/util/aliyun/loadbalancertcplistener.go
  pkg/util/aliyun/loadbalancerudplistener.go
  pkg/util/aliyun/region.go
  pkg/util/qcloud/loadbalancer.go
  pkg/util/qcloud/loadbalancer_listener.go
Labels: approved, lgtm, size/L

#384 Bugfix/tb sku fix
  pkg/compute/models/skus.go
  pkg/util/aws/securitygroup.go
  pkg/util/aws/vpc.go
Labels: approved, lgtm, size/M

#377 fix: server create params isolated device config no vendor and device…
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#379 region: add one random config if user input net config is empty when …
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XS

#395 Automated cherry pick of #327: 设置lb manager_id
  pkg/cloudprovider/loadbalancer.go
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/cloudprovider/resources.go
  pkg/compute/consts/loadbalancer_const.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/models/loadbalancers.go
  pkg/mcclient/modules/mod_loadbalancerlisteners.go
  pkg/mcclient/modules/mod_loadbalancers.go
  pkg/mcclient/options/loadbalanceracls.go
  pkg/mcclient/options/loadbalancercertificates.go
  pkg/mcclient/options/loadbalancerlisteners.go
  pkg/mcclient/options/loadbalancers.go
  pkg/util/aliyun/loadbalancer.go
  pkg/util/aliyun/loadbalancerhttplistener.go
  pkg/util/aliyun/loadbalancerhttpslistener.go
  pkg/util/aliyun/loadbalancertcplistener.go
  pkg/util/aliyun/loadbalancerudplistener.go
  pkg/util/aliyun/region.go
  pkg/util/qcloud/loadbalancer.go
  pkg/util/qcloud/loadbalancer_listener.go
Labels: approved, lgtm, size/L

#396 Automated cherry pick of #327: 设置lb manager_id
  pkg/cloudprovider/loadbalancer.go
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/cloudprovider/resources.go
  pkg/compute/consts/loadbalancer_const.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/models/loadbalancers.go
  pkg/mcclient/modules/mod_loadbalancerlisteners.go
  pkg/mcclient/modules/mod_loadbalancers.go
  pkg/mcclient/options/loadbalanceracls.go
  pkg/mcclient/options/loadbalancercertificates.go
  pkg/mcclient/options/loadbalancerlisteners.go
  pkg/mcclient/options/loadbalancers.go
  pkg/util/aliyun/loadbalancer.go
  pkg/util/aliyun/loadbalancerhttplistener.go
  pkg/util/aliyun/loadbalancerhttpslistener.go
  pkg/util/aliyun/loadbalancertcplistener.go
  pkg/util/aliyun/loadbalancerudplistener.go
  pkg/util/aliyun/region.go
  pkg/util/qcloud/loadbalancer.go
  pkg/util/qcloud/loadbalancer_listener.go
Labels: approved, lgtm, size/L

#399 fix: scheduler forecast backup server not work
  pkg/apis/scheduler/api.go
  pkg/scheduler/algorithm/predicates/aggregate_predicate.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/core/context.go
  pkg/scheduler/handler/backup_helper.go
  pkg/scheduler/handler/forecast_helper.go
  pkg/scheduler/handler/handler.go
Labels: approved, area/scheduler, lgtm, size/L

#398 Websockets 不再拉取 ActionLog 的消息
  pkg/logger/models/actionlog.go
Labels: approved, lgtm, size/S

#397 Automated cherry pick of #168: 优化scheduler缓存 #380: fix: scheduler sku cache stale when region sync sku finished
  cmd/climc/shell/schedulers.go
  pkg/compute/models/cloudsync.go
  pkg/mcclient/modules/mod_scheduler.go
  pkg/scheduler/data_manager/sku/sku.go
  pkg/scheduler/handler/handler.go
Labels: approved, area/scheduler, lgtm, size/M

#401 避免创建不受支持的loadbalancer
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/openstack.go
Labels: approved, lgtm, size/M
