Repository yunionio/cloudpods, pull requests merged in 2019-07, with the labels that each got.

#1440 feature: 1. esxi vm add resource pool metadata 2. esxicli support
  cmd/azurecli/main.go
  cmd/climc/shell/cloudproviders.go
  cmd/huaweicli/main.go
  cmd/qcloudcli/main.go
  cmd/ucloudcli/main.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/syncutils.go
  pkg/util/aliyun/aliyun.go
  pkg/util/aliyun/provider/provider.go
  pkg/util/aws/aws.go
  pkg/util/aws/provider/provider.go
  pkg/util/azure/azure.go
  pkg/util/azure/provider/provider.go
  pkg/util/esxi/datacenter.go
  pkg/util/esxi/manager.go
  pkg/util/esxi/network.go
  pkg/util/esxi/provider/provider.go
  pkg/util/esxi/resourcepool.go
  pkg/util/esxi/shell/network.go
  pkg/util/esxi/virtualmachine.go
  pkg/util/huawei/huawei.go
  pkg/util/huawei/provider/provider.go
  pkg/util/openstack/provider/provider.go
  pkg/util/pinyinutils/doc.go
  pkg/util/qcloud/provider/provider.go
  pkg/util/qcloud/qcloud.go
  pkg/util/ucloud/provider/provider.go
  pkg/util/ucloud/ucloud.go
  pkg/util/zstack/provider/provider.go
Labels: approved, area/climc, area/region, lgtm, size/XL

#1441 feature: capability add brands
  pkg/apis/compute/guest_const.go
  pkg/compute/models/capabilities.go
Labels: approved, area/region, lgtm, size/M

#1444 Automated cherry pick of #1441: feature: capability add brands
  pkg/apis/compute/guest_const.go
  pkg/compute/models/capabilities.go
Labels: approved, lgtm, size/M

#1445 Automated cherry pick of #1440: feature: 1. esxi vm add resource pool metadata 2. esxicli support network-list 3. add cloud-provider-clirc command to generate rc for each cloud-cli
  cmd/azurecli/main.go
  cmd/climc/shell/cloudproviders.go
  cmd/huaweicli/main.go
  cmd/qcloudcli/main.go
  cmd/ucloudcli/main.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/syncutils.go
  pkg/util/aliyun/aliyun.go
  pkg/util/aliyun/provider/provider.go
  pkg/util/aws/aws.go
  pkg/util/aws/provider/provider.go
  pkg/util/azure/azure.go
  pkg/util/azure/provider/provider.go
  pkg/util/esxi/datacenter.go
  pkg/util/esxi/manager.go
  pkg/util/esxi/network.go
  pkg/util/esxi/provider/provider.go
  pkg/util/esxi/resourcepool.go
  pkg/util/esxi/shell/network.go
  pkg/util/esxi/virtualmachine.go
  pkg/util/huawei/huawei.go
  pkg/util/huawei/provider/provider.go
  pkg/util/openstack/provider/provider.go
  pkg/util/pinyinutils/doc.go
  pkg/util/qcloud/provider/provider.go
  pkg/util/qcloud/qcloud.go
  pkg/util/ucloud/provider/provider.go
  pkg/util/ucloud/ucloud.go
  pkg/util/zstack/provider/provider.go
Labels: approved, lgtm, size/XL

#1443 Automated cherry pick of #1442: fix: usage query support brands
  cmd/climc/shell/usages.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/networks.go
  pkg/compute/models/quotas.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storages.go
  pkg/compute/models/usage.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: approved, lgtm, size/XL

#1442 fix: usage query support brands
  cmd/climc/shell/usages.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/networks.go
  pkg/compute/models/quotas.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storages.go
  pkg/compute/models/usage.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: approved, area/region, lgtm, size/XL

#1447 Automated cherry pick of #1420: remove keypair info if rebuild-root net set keypair
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#1446 Automated cherry pick of #1420: remove keypair info if rebuild-root net set keypair
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#1420 remove keypair info if rebuild-root not set keypair
  pkg/compute/models/guest_actions.go
Labels: approved, area/region, lgtm, size/XS

#1448 Automated cherry pick of #1420: remove keypair info if rebuild-root net set keypair
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#1449 fix nil pointer dereference error
  pkg/compute/models/capabilities.go
Labels: approved, area/region, lgtm, size/XS

#1450 Automated cherry pick of #1449: fix nil pointer dereference error
  pkg/compute/models/capabilities.go
Labels: approved, lgtm, size/XS

#1451 fix format
  pkg/cloudcommon/db/metadata.go
  pkg/compute/models/syncutils.go
Labels: approved, area/region, lgtm, size/XS

#1452 Automated cherry pick of #1451: fix format
  pkg/cloudcommon/db/metadata.go
  pkg/compute/models/syncutils.go
Labels: approved, lgtm, size/XS

#1453 Automated cherry pick of #1415: zone添加GetIVMById,GetIDiskById方法
  pkg/cloudprovider/resources.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/util/aliyun/region.go
  pkg/util/aws/region.go
  pkg/util/azure/region.go
  pkg/util/esxi/fakeregion.go
  pkg/util/huawei/region.go
  pkg/util/openstack/region.go
  pkg/util/qcloud/region.go
  pkg/util/ucloud/region.go
  pkg/util/zstack/region.go
Labels: approved, lgtm, size/L

#1415 避免虚拟机或磁盘漂移同步后名称后lost后缀
  pkg/cloudprovider/resources.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/util/aliyun/region.go
  pkg/util/aws/region.go
  pkg/util/azure/region.go
  pkg/util/esxi/fakeregion.go
  pkg/util/huawei/region.go
  pkg/util/openstack/region.go
  pkg/util/qcloud/region.go
  pkg/util/ucloud/region.go
  pkg/util/zstack/region.go
Labels: approved, area/region, lgtm, size/L

#1457 Automated cherry pick of #1456: fix attach disk not effect
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, lgtm, size/M

#1456 fix attach disk not effect
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, area/region, lgtm, size/M

#1454 bugfix: fix dhcp build on OSX
  pkg/util/dhcp/conn.go
  pkg/util/dhcp/conn_linux.go
  pkg/util/dhcp/conn_unsupported.go
  pkg/util/dhcp/server.go
Labels: approved, area/host, lgtm, size/L

#1455 Automated cherry pick of #1454: fix dhcp build on OSX
  pkg/util/dhcp/conn.go
  pkg/util/dhcp/conn_linux.go
  pkg/util/dhcp/conn_unsupported.go
  pkg/util/dhcp/server.go
Labels: approved, lgtm, size/L

#1458 fix: 1. idp sync fail to sync group domainId 2. idp delete fail
  pkg/cloudcommon/db/namevalidator.go
  pkg/compute/models/networks.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/identity_provider.go
Labels: approved, area/keystone, lgtm, size/S

#1459 Automated cherry pick of #1458: fix: 1. idp sync fail to sync group domainId 2. idp delete fail
  pkg/cloudcommon/db/namevalidator.go
  pkg/compute/models/networks.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/identity_provider.go
Labels: approved, lgtm, size/S

#1461 Automated cherry pick of #1460: fix: 1. quota add API 2. tenant cache refresh 3. domain quota not initialize
  cmd/climc/shell/quotas.go
  docs/README.md
  docs/swagger.yaml
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/db/keystonecache.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/usageworker.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/cloudcommon/options/options.go
  pkg/keystone/tokens/handlers.go
  pkg/mcclient/catalog.go
  pkg/mcclient/mcclient.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
  pkg/mcclient/tokensimple.go
Labels: approved, lgtm, size/XL

#1464 update mod
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/update.go
Labels: approved, area/region, lgtm, size/S

#1465 Automated cherry pick of #1464: update mod
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/update.go
Labels: approved, lgtm, size/S

#1466 Automated cherry pick of #1464: update mod
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/update.go
Labels: approved, lgtm, size/S

#1468 Automated cherry pick of #1467: fix create disk scheduler failed
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/XS

#1467 fix create disk scheduler failed
  pkg/compute/models/disks.go
Labels: approved, area/region, lgtm, size/XS

#1469 Automated cherry pick of #1467: fix create disk scheduler failed
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/XS

#1470 Automated cherry pick of #1467: fix create disk scheduler failed
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/XS

#1471 bugfix: fix export data, set no limit; expand timeout
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlerinfo.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/S

#1472 Automated cherry pick of #1471: fix export data, set no limit; expand timeout
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlerinfo.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#1473 Automated cherry pick of #1471: fix export data, set no limit; expand timeout
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlerinfo.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#1477 Automated cherry pick of #1471: fix export data, set no limit; expand timeout
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlerinfo.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#1478 Automated cherry pick of #1471: fix export data, set no limit; expand timeout
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlerinfo.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#1475 Automated cherry pick of #1474: fix: service catalog nil pointer
  pkg/keystone/models/identity_provider.go
  pkg/keystone/options/options.go
  pkg/mcclient/session.go
Labels: approved, lgtm, size/XS

#1476 Automated cherry pick of #1474: fix: service catalog nil pointer
  pkg/keystone/models/identity_provider.go
  pkg/keystone/options/options.go
  pkg/mcclient/session.go
Labels: approved, lgtm, size/XS

#1474 fix: service catalog nil pointer
  pkg/keystone/models/identity_provider.go
  pkg/keystone/options/options.go
  pkg/mcclient/session.go
Labels: approved, area/climc, lgtm, size/XS

#1191 Feature/qx private cloud sku
  cmd/climc/shell/skus.go
  docs/index.yaml
  docs/network/networks.yaml
  docs/parameters/common.yaml
  docs/parameters/network.yaml
  docs/parameters/serversku.yaml
  docs/schemas/common.yaml
  docs/schemas/loadbalancer.yaml
  docs/schemas/serversku.yaml
  docs/serversku/disable.yaml
  docs/serversku/enable.yaml
  docs/serversku/serversku.yaml
  docs/serversku/serverskus.yaml
  pkg/apis/compute/sku_const.go
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/serversku.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skustools.go
  pkg/compute/tasks/server_sku_create_task.go
  pkg/compute/tasks/server_sku_delete_task.go
  pkg/multicloud/region_base.go
  pkg/multicloud/serversku_base.go
  pkg/util/aliyun/region.go
  pkg/util/aws/region.go
  pkg/util/azure/region.go
  pkg/util/esxi/fakeregion.go
  pkg/util/huawei/region.go
  pkg/util/openstack/flavor.go
  pkg/util/openstack/region.go
  pkg/util/qcloud/region.go
  pkg/util/zstack/offering.go
  pkg/util/zstack/region.go
  pkg/util/zstack/shell/instance_offering.go
Labels: approved, area/region, lgtm, size/XXL

#1463 Automated cherry pick of #1191: 私有云套餐操作支持
  cmd/climc/shell/skus.go
  docs/index.yaml
  docs/network/networks.yaml
  docs/parameters/common.yaml
  docs/parameters/network.yaml
  docs/parameters/serversku.yaml
  docs/schemas/common.yaml
  docs/schemas/loadbalancer.yaml
  docs/schemas/serversku.yaml
  docs/serversku/disable.yaml
  docs/serversku/enable.yaml
  docs/serversku/serversku.yaml
  docs/serversku/serverskus.yaml
  pkg/apis/compute/sku_const.go
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/serversku.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skustools.go
  pkg/compute/tasks/server_sku_create_task.go
  pkg/compute/tasks/server_sku_delete_task.go
  pkg/multicloud/region_base.go
  pkg/multicloud/serversku_base.go
  pkg/util/aliyun/region.go
  pkg/util/aws/region.go
  pkg/util/azure/region.go
  pkg/util/esxi/fakeregion.go
  pkg/util/huawei/region.go
  pkg/util/openstack/flavor.go
  pkg/util/openstack/region.go
  pkg/util/qcloud/region.go
  pkg/util/zstack/offering.go
  pkg/util/zstack/region.go
  pkg/util/zstack/shell/instance_offering.go
Labels: approved, lgtm, size/XXL

#1484 scheduler: fix network schedtag not set capacity
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
Labels: approved, area/scheduler, lgtm, size/XS

#1485 Automated cherry pick of #1484: scheduler: fix network schedtag not set capacity
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
Labels: approved, lgtm, size/XS

#1495 fix export data
  pkg/appsrv/handlerinfo.go
Labels: approved, area/region, lgtm, size/XS

#1496 Automated cherry pick of #1495: fix export data
  pkg/appsrv/handlerinfo.go
Labels: approved, lgtm, size/XS

#1497 Automated cherry pick of #1495: fix export data
  pkg/appsrv/handlerinfo.go
Labels: approved, lgtm, size/XS

#1498 Automated cherry pick of #1495: fix export data
  pkg/appsrv/handlerinfo.go
Labels: approved, lgtm, size/XS

#1499 Automated cherry pick of #1495: fix export data
  pkg/appsrv/handlerinfo.go
Labels: approved, lgtm, size/XS

#1500 build: mod: 兼容bsd sed
  Makefile
Labels: approved, area/region, lgtm, size/XS

#1501 Automated cherry pick of #1500: build: mod: 兼容bsd sed
  Makefile
Labels: approved, lgtm, size/XS

#1502 Automated cherry pick of #1500: build: mod: 兼容bsd sed
  Makefile
Labels: approved, lgtm, size/XS

#1486 fix azure set secgroup error
  pkg/util/azure/instance.go
  pkg/util/azure/securitygroup.go
  pkg/util/azure/shell/instance.go
Labels: approved, area/region, lgtm, size/S

#1491 Automated cherry pick of #1486: fix azure set secgroup error
  pkg/util/azure/instance.go
  pkg/util/azure/securitygroup.go
  pkg/util/azure/shell/instance.go
Labels: approved, lgtm, size/S

#1492 Automated cherry pick of #1486: fix azure set secgroup error
  pkg/util/azure/instance.go
  pkg/util/azure/securitygroup.go
  pkg/util/azure/shell/instance.go
Labels: approved, lgtm, size/S

#1494 Automated cherry pick of #1486: fix azure set secgroup error
  pkg/util/azure/instance.go
  pkg/util/azure/securitygroup.go
  pkg/util/azure/shell/instance.go
Labels: approved, lgtm, size/S

#1493 Automated cherry pick of #1486: fix azure set secgroup error
  pkg/util/azure/instance.go
  pkg/util/azure/securitygroup.go
  pkg/util/azure/shell/instance.go
Labels: approved, lgtm, size/S

#1479 fix sync openstack hoststorages issue
  pkg/util/openstack/host.go
  pkg/util/openstack/zone.go
Labels: approved, area/region, lgtm, size/M

#1480 Automated cherry pick of #1479: fix sync openstack hoststorages issue
  pkg/util/openstack/host.go
  pkg/util/openstack/zone.go
Labels: approved, lgtm, size/M

#1481 Automated cherry pick of #1479: fix sync openstack hoststorages issue
  pkg/util/openstack/host.go
  pkg/util/openstack/zone.go
Labels: approved, lgtm, size/M

#1482 Automated cherry pick of #1479: fix sync openstack hoststorages issue
  pkg/util/openstack/host.go
  pkg/util/openstack/zone.go
Labels: approved, lgtm, size/M

#1483 Automated cherry pick of #1479: fix sync openstack hoststorages issue
  pkg/util/openstack/host.go
  pkg/util/openstack/zone.go
Labels: approved, lgtm, size/M

#1503 fix cloud-init lock root login issue
  pkg/util/cloudinit/cloudconfig.go
Labels: approved, area/region, lgtm, size/XS

#1504 Automated cherry pick of #1503: fix cloud-init lock root login issue
  pkg/util/cloudinit/cloudconfig.go
Labels: approved, lgtm, size/XS

#1505 Automated cherry pick of #1503: fix cloud-init lock root login issue
  pkg/util/cloudinit/cloudconfig.go
Labels: approved, lgtm, size/XS

#1512 fix image download timeout
  pkg/image/tasks/image_copy_from_url_task.go
  pkg/util/zstack/image.go
Labels: approved, lgtm, needs-area, size/XS

#1514 Automated cherry pick of #1512: fix image download timout
  pkg/image/tasks/image_copy_from_url_task.go
  pkg/util/zstack/image.go
Labels: approved, lgtm, size/XS

#1513 Automated cherry pick of #1512: fix image download timout
  pkg/image/tasks/image_copy_from_url_task.go
  pkg/util/zstack/image.go
Labels: approved, lgtm, size/XS

#1515 cherrypick: fix image request timeout
  pkg/image/tasks/image_copy_from_url_task.go
Labels: approved, lgtm, size/XS

#1516 cherrypick : fix request image timeout
  pkg/image/tasks/image_copy_from_url_task.go
Labels: approved, lgtm, size/XS

#1509 pkg: ansible: 改正文件内容写入路径
  pkg/util/ansible/playbook.go
Labels: approved, lgtm, needs-area, size/XS

#1511 Automated cherry pick of #1509: pkg: ansible: 改正文件内容写入路径
  pkg/util/ansible/playbook.go
Labels: approved, lgtm, size/XS

#1510 Automated cherry pick of #1509: pkg: ansible: 改正文件内容写入路径
  pkg/util/ansible/playbook.go
Labels: approved, lgtm, size/XS

#1520 zstack using shell to init image password
  pkg/compute/guestdrivers/zstack.go
Labels: approved, area/region, lgtm, size/XS

#1521 Automated cherry pick of #1520: zstack using shell to init image password
  pkg/compute/guestdrivers/zstack.go
Labels: approved, lgtm, size/XS

#1522 Automated cherry pick of #1520: zstack using shell to init image password
  pkg/compute/guestdrivers/zstack.go
Labels: approved, lgtm, size/XS

#1523 climc: deploy k8s cluster on kinds of hypervisor
  cmd/climc/shell/images.go
  pkg/mcclient/modules/k8s/machine.go
  pkg/mcclient/options/k8s/cluster.go
  pkg/mcclient/options/k8s/machine.go
  pkg/mcclient/options/servers.go
Labels: approved, area/climc, lgtm, size/M

#1525 Automated cherry pick of #1524: fix azure reserved ips
  pkg/util/azure/classic_network.go
  pkg/util/azure/network.go
Labels: approved, lgtm, size/S

#1524 fix azure reserved ips
  pkg/util/azure/classic_network.go
  pkg/util/azure/network.go
Labels: approved, area/region, lgtm, size/S

#1526 Automated cherry pick of #1524: fix azure reserved ips
  pkg/util/azure/classic_network.go
  pkg/util/azure/network.go
Labels: approved, lgtm, size/S

#1528 Automated cherry pick of #1524: fix azure reserved ips
  pkg/util/azure/classic_network.go
  pkg/util/azure/network.go
Labels: approved, lgtm, size/S

#1527 Automated cherry pick of #1524: fix azure reserved ips
  pkg/util/azure/classic_network.go
  pkg/util/azure/network.go
Labels: approved, lgtm, size/S

#1529 fix create image with userCred issue
  pkg/compute/models/disks.go
Labels: approved, area/region, lgtm, size/S

#1530 Automated cherry pick of #1529: fix create image with userCred issue
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/S

#1532 Automated cherry pick of #1529: fix create image with userCred issue
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/S

#1533 Automated cherry pick of #1529: fix create image with userCred issue
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/S

#1531 Automated cherry pick of #1529: fix create image with userCred issue
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/S

#1534 fix: 1. token add projects when no project specified 2.
  cmd/climc/climc.go
  docs/schemas/auth.yaml
  pkg/apis/compute/snapshot.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/project_resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/keystone/models/projects.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
Labels: approved, area/keystone, area/region, lgtm, size/L

#1536 Automated cherry pick of #1534: fix: 1. token add projects when no project specified 2. IVirtualResourceManager add GetResourceCount() method 3. domainId not initialized occasionally
  cmd/climc/climc.go
  docs/schemas/auth.yaml
  pkg/apis/compute/snapshot.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/project_resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/keystone/models/projects.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
Labels: approved, lgtm, size/L

#1535 Automated cherry pick of #1534: fix: 1. token add projects when no project specified 2. IVirtualResourceManager add GetResourceCount() method 3. domainId not initialized occasionally
  cmd/climc/climc.go
  pkg/apis/compute/snapshot.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/project_resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/keystone/models/projects.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
Labels: approved, lgtm, size/L

#1537 add ldapcli rpm
  build/ldapcli/vars
Labels: approved, area/climc, lgtm, size/XS

#1538 Automated cherry pick of #1537: add ldapcli rpm
  build/ldapcli/vars
Labels: approved, lgtm, size/XS

#1539 Automated cherry pick of #1537: add ldapcli rpm
  build/ldapcli/vars
Labels: approved, lgtm, size/XS

#1517 .circleci: save go cache
  .circleci/config.yml
  Makefile
  scripts/coverage.sh
Labels: approved, area/region, lgtm, size/M

#1518 Automated cherry pick of #1517: .circleci: save go cache
  .circleci/config.yml
  Makefile
  scripts/coverage.sh
Labels: approved, lgtm, size/M

#1519 Automated cherry pick of #1517: .circleci: save go cache
  .circleci/config.yml
  Makefile
  scripts/coverage.sh
Labels: approved, lgtm, size/M

#1507 fix sku filter by usable
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/S

#1506 fix idc sku filter at 2.10.0
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/XS

#1508 Automated cherry pick of #1507: fix sku filter by usable
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#1547 add azure disk reset func
  pkg/util/azure/azure.go
  pkg/util/azure/disk.go
  pkg/util/azure/shell/disk.go
Labels: approved, area/region, lgtm, size/M

#1548 Automated cherry pick of #1547: add azure disk reset func
  pkg/util/azure/azure.go
  pkg/util/azure/disk.go
  pkg/util/azure/shell/disk.go
Labels: approved, lgtm, size/M

#1549 Automated cherry pick of #1547: add azure disk reset func
  pkg/util/azure/azure.go
  pkg/util/azure/disk.go
  pkg/util/azure/shell/disk.go
Labels: approved, lgtm, size/M

#1540 fix: user filter by role
  cmd/climc/shell/users.go
  pkg/keystone/models/users.go
Labels: approved, area/keystone, lgtm, size/S

#1541 Automated cherry pick of #1540: fix: user filter by role
  cmd/climc/shell/users.go
  pkg/keystone/models/users.go
Labels: approved, lgtm, size/S

#1542 Automated cherry pick of #1540: fix: user filter by role
  cmd/climc/shell/users.go
  pkg/keystone/models/users.go
Labels: approved, lgtm, size/S

#1552 1. allow replace set quota when action=replace
  cmd/climc/shell/quotas.go
  docs/parameters/quota.yaml
  pkg/cloudcommon/db/quotas/handler.go
  pkg/keystone/models/project_resources.go
  pkg/keystone/models/projects.go
Labels: approved, area/keystone, area/region, lgtm

#1554 Automated cherry pick of #1552: 1. allow replace set quota when action=replace 2. show when the project external resource was fetched
  cmd/climc/shell/quotas.go
  docs/parameters/quota.yaml
  pkg/cloudcommon/db/quotas/handler.go
  pkg/keystone/models/project_resources.go
  pkg/keystone/models/projects.go
Labels: approved, lgtm, size/M

#1553 Automated cherry pick of #1552: 1. allow replace set quota when action=replace 2. show when the project external resource was fetched
  cmd/climc/shell/quotas.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/keystone/models/project_resources.go
  pkg/keystone/models/projects.go
Labels: approved, lgtm, size/M

#1544 fix: add disk usage for domain and project
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/usages/handler.go
Labels: approved, area/region, lgtm, size/L

#1546 Automated cherry pick of #1544: fix: add disk usage for domain and project
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/usages/handler.go
Labels: approved, lgtm, size/L

#1545 Automated cherry pick of #1544: fix: add disk usage for domain and project
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/usages/handler.go
Labels: approved, lgtm, size/L

#1550 fix purge aliyun account error by lbbg
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, area/region, lgtm, size/L

#1555 Automated cherry pick of #1550: fix purge aliyun account error by lbbg
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#1557 Automated cherry pick of #1550: fix purge aliyun account error by lbbg
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#1556 Automated cherry pick of #1550: fix purge aliyun account error by lbbg
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#1558 Automated cherry pick of #1550: fix purge aliyun account error by lbbg
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#1561 Automated cherry pick of #1543: fix not set guest status after attach or detach disk
  pkg/apis/compute/guest_const.go
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/util/openstack/shell/instance.go
Labels: approved, lgtm, size/L

#1543 修复并发请求挂载卸载磁盘异常问题
  pkg/apis/compute/guest_const.go
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/util/openstack/shell/instance.go
Labels: approved, area/region, lgtm, size/L

#1562 Automated cherry pick of #1543: fix not set guest status after attach or detach disk
  pkg/apis/compute/guest_const.go
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/util/openstack/shell/instance.go
Labels: approved, lgtm, size/L

#1563 add deploy failed action log
  pkg/compute/tasks/guest_deploy_task.go
Labels: approved, area/region, lgtm, size/XS

#1564 Automated cherry pick of #1563: add deploy failed action log
  pkg/compute/tasks/guest_deploy_task.go
Labels: approved, lgtm, size/XS

#1565 Automated cherry pick of #1563: add deploy failed action log
  pkg/compute/tasks/guest_deploy_task.go
Labels: approved, lgtm, size/XS

#1566 Automated cherry pick of #1563: add deploy failed action log
  pkg/compute/tasks/guest_deploy_task.go
Labels: approved, lgtm, size/XS

#1567 Automated cherry pick of #1563: add deploy failed action log
  pkg/compute/tasks/guest_deploy_task.go
Labels: approved, lgtm, size/XS

#1559 Automated cherry pick of #1551: add without_user_meta filter
  go.mod
  go.sum
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/mcclient/options/metadata.go
  pkg/mcclient/options/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: approved, lgtm, size/M

#1551 Hotfix/qx metadata filter
  go.mod
  go.sum
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/mcclient/options/metadata.go
  pkg/mcclient/options/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: approved, area/region, lgtm, size/M

#1560 Automated cherry pick of #1551: add without_user_meta filter
  go.mod
  go.sum
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/mcclient/options/metadata.go
  pkg/mcclient/options/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: approved, lgtm, size/M

#1573 add usable filter for network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#1570 fix: quota encode json allowing zero value
  pkg/cloudcommon/db/quotas/handler.go
  pkg/compute/models/quotas.go
  pkg/image/models/quotas.go
Labels: area/region, size/M

#1571 Automated cherry pick of #1570: fix: quota encode json allowing zero value
  pkg/cloudcommon/db/quotas/handler.go
  pkg/compute/models/quotas.go
  pkg/image/models/quotas.go
Labels: size/M

#1576 Automated cherry pick of #1573: add usable filter for network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#1574 Automated cherry pick of #1573: add usable filter for network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#1575 Automated cherry pick of #1573: add usable filter for network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#1572 Automated cherry pick of #1570: fix: quota encode json allowing zero value
  pkg/cloudcommon/db/quotas/handler.go
  pkg/compute/models/quotas.go
  pkg/image/models/quotas.go
Labels: size/M

#1577 Automated cherry pick of #1573: add usable filter for network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#1583 fix: ignore queryField panic
  pkg/cloudcommon/db/jointbase.go
Labels: area/region, size/S

#1584 fix create server sku not found error
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
  pkg/compute/models/skustools.go
Labels: approved, area/region, lgtm, size/M

#1590 Automated cherry pick of #1584: fix create server sku not found error
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
  pkg/compute/models/skustools.go
Labels: approved, lgtm, size/M

#1589 Automated cherry pick of #1584: fix create server sku not found error
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
  pkg/compute/models/skustools.go
Labels: approved, lgtm, size/M

#1568 fix cache domain tenants
  pkg/cloudcommon/db/tenantcache.go
  pkg/compute/models/cloudaccounts.go
Labels: approved, area/region, lgtm, needs-backport, size/M

#1591 Automated cherry pick of #1568: fix cache domain tenants
  pkg/cloudcommon/db/tenantcache.go
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm

#1592 Automated cherry pick of #1568: fix cache domain tenants
  pkg/cloudcommon/db/tenantcache.go
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/M

#1593 fix: image quota rpc support action and cascade params
  pkg/mcclient/modules/mod_quotas.go
Labels: approved, area/climc, size/XS

#1594 Automated cherry pick of #1593: fix: image quota rpc support action and cascade params
  pkg/mcclient/modules/mod_quotas.go
Labels: approved, size/XS

#1595 Automated cherry pick of #1593: fix: image quota rpc support action and cascade params
  pkg/mcclient/modules/mod_quotas.go
Labels: approved, size/XS

#1598 Automated cherry pick of #1596: 私有云或公有云镜像windows默认用户名都是Administrator
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/zstack.go
Labels: approved, lgtm, size/S

#1596 私有云或公有云镜像windows默认用户名都是Administrator
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/zstack.go
Labels: approved, area/region, lgtm, size/S

#1597 Automated cherry pick of #1596: 私有云或公有云镜像windows默认用户名都是Administrator
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/zstack.go
Labels: approved, lgtm, size/S

#1599 fix max session login issue
  pkg/compute/models/storagecachedimages.go
  pkg/util/zstack/image.go
  pkg/util/zstack/zstack.go
Labels: approved, area/region, lgtm, size/M

#1600 Automated cherry pick of #1599: fix max session login issue
  pkg/compute/models/storagecachedimages.go
  pkg/util/zstack/image.go
  pkg/util/zstack/zstack.go
Labels: approved, lgtm, size/M

#1601 Automated cherry pick of #1599: fix max session login issue
  pkg/compute/models/storagecachedimages.go
  pkg/util/zstack/image.go
  pkg/util/zstack/zstack.go
Labels: approved, lgtm, size/M

#1616 + zstack build desc file
  build/zstackcli/vars
Labels: approved, area/climc, lgtm, size/XS
