Repository yunionio/cloudpods, pull requests merged in 2019-11, with the labels that each got.

#3426 Feature: Rpm Notify
  build/notify/vars
Labels: approved, area/notify, lgtm, size/XS

#3427 Automated cherry pick of #3426: feature: add support for rpm build of notify
  build/notify/vars
Labels: approved, lgtm, size/XS

#3437 fix: missing action log for baremetal create and prepare events
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/cdrom.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/ipmiprobe.go
  pkg/baremetal/tasks/maintenance.go
  pkg/baremetal/tasks/prepare.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
  pkg/baremetal/tasks/resetbmc.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/stop.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/compute/tasks/baremetal_create_task.go
  pkg/util/logclient/consts.go
Labels: approved, area/baremetal, area/region, lgtm, size/L

#3438 Automated cherry pick of #3437: fix: missing action log for baremetal create and prepare events
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/cdrom.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/ipmiprobe.go
  pkg/baremetal/tasks/maintenance.go
  pkg/baremetal/tasks/prepare.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
  pkg/baremetal/tasks/resetbmc.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/stop.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/compute/tasks/baremetal_create_task.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/L

#3441 Automated cherry pick of #3440: feature: add api to get all allocated addresses of a network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/L

#3440 feature: add api to get all allocated addresses of a network
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/L

#3434 fix: bucket invalid status due to disabled cloud provider
  pkg/compute/models/buckets.go
  pkg/compute/models/cloudproviders.go
Labels: approved, area/region, lgtm, size/M

#3435 Automated cherry pick of #3434: fix: bucket invalid status due to disabled cloud provider
  pkg/compute/models/buckets.go
  pkg/compute/models/cloudproviders.go
Labels: approved, lgtm

#3436 Automated cherry pick of #3434: fix: bucket invalid status due to disabled cloud provider
  pkg/compute/models/buckets.go
  pkg/compute/models/cloudproviders.go
Labels: approved, lgtm

#3439 elb bugfix & aws client init bugfix
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: approved, area/region, lgtm, size/XXL

#3442 Automated cherry pick of #3439: elb bugfix & aws client init bugfix
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: approved, lgtm, size/XXL

#3443 Automated cherry pick of #3439: elb bugfix & aws client init bugfix
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: approved, lgtm, size/XXL

#3449 Automated cherry pick of #3429: fix: 梳理磁盘reset条件
  pkg/compute/hostdrivers/aliyun.go
  pkg/compute/hostdrivers/aws.go
  pkg/compute/hostdrivers/azure.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/ucloud.go
  pkg/compute/hostdrivers/zstack.go
  pkg/compute/models/disks.go
  pkg/compute/models/hostdrivers.go
Labels: approved, lgtm, size/L

#3429 fix: 梳理磁盘reset条件
  pkg/compute/hostdrivers/aliyun.go
  pkg/compute/hostdrivers/aws.go
  pkg/compute/hostdrivers/azure.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/ucloud.go
  pkg/compute/hostdrivers/zstack.go
  pkg/compute/models/disks.go
  pkg/compute/models/hostdrivers.go
Labels: approved, area/region, lgtm, size/L

#3448 Automated cherry pick of #3429: fix: 梳理磁盘reset条件
  pkg/compute/hostdrivers/aliyun.go
  pkg/compute/hostdrivers/aws.go
  pkg/compute/hostdrivers/azure.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/ucloud.go
  pkg/compute/hostdrivers/zstack.go
  pkg/compute/models/disks.go
  pkg/compute/models/hostdrivers.go
Labels: approved, lgtm, size/L

#3447 Automated cherry pick of #3429: fix: 梳理磁盘reset条件
  pkg/compute/hostdrivers/aliyun.go
  pkg/compute/hostdrivers/aws.go
  pkg/compute/hostdrivers/azure.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/ucloud.go
  pkg/compute/hostdrivers/zstack.go
  pkg/compute/models/disks.go
  pkg/compute/models/hostdrivers.go
Labels: approved, lgtm, size/L

#3430 fix: 标准镜像version
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/zstack/image.go
Labels: approved, area/region, lgtm, needs-backport, size/S

#3452 Automated cherry pick of #3430: fix: 标准镜像version
  pkg/util/aliyun/image.go
  pkg/util/huawei/image.go
  pkg/util/qcloud/image.go
  pkg/util/zstack/image.go
Labels: approved, lgtm

#3451 Automated cherry pick of #3430: fix: 标准镜像version
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/zstack/image.go
Labels: approved, lgtm, size/S

#3450 Automated cherry pick of #3430: fix: 标准镜像version
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/zstack/image.go
Labels: approved, lgtm, size/S

#3457 build: show diffs made by checks
  Makefile
Labels: approved, area/util, lgtm, size/XS

#3460 Automated cherry pick of #3457: build: show diffs made by checks
  Makefile
Labels: approved, lgtm, size/XS

#3459 Automated cherry pick of #3457: build: show diffs made by checks
  Makefile
Labels: approved, lgtm, size/XS

#3458 Automated cherry pick of #3457: build: show diffs made by checks
  Makefile
Labels: approved, lgtm, size/XS

#3413 Fix: Keystone Policy
  pkg/util/rbacutils/rbac.go
  pkg/util/rbacutils/reduce.go
  pkg/util/rbacutils/reduce_test.go
Labels: approved, area/keystone, lgtm, size/L

#3453 Automated cherry pick of #3413: fix: cancel the merge in service level and resource level of Keystone Policy.
  pkg/util/rbacutils/rbac.go
  pkg/util/rbacutils/reduce.go
  pkg/util/rbacutils/reduce_test.go
Labels: approved, lgtm, size/L

#3422 fix: 添加华为云Rds privilege校验
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstance_databases.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_database_create_task.go
  pkg/multicloud/huawei/dbinstance.go
Labels: approved, area/region, lgtm, size/L

#3424 Automated cherry pick of #3422: fix: 添加华为云Rds privilege校验
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstance_databases.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_database_create_task.go
  pkg/multicloud/huawei/dbinstance.go
Labels: approved, lgtm, size/L

#3428 fix: 避免创建vmware磁盘快照
  pkg/apis/compute/snapshot.go
  pkg/compute/models/disks.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagedrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: approved, area/region, lgtm, size/L

#3432 fix: user details add password expiration info
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/usrext.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: approved, area/keystone, lgtm, size/M

#3445 Automated cherry pick of #3428: fix: 避免创建vmware磁盘快照
  pkg/apis/compute/snapshot.go
  pkg/compute/models/disks.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagedrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: approved, lgtm, size/L

#3433 Automated cherry pick of #3432: fix: user details add password expiration info
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/usrext.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: approved, lgtm, size/M

#3446 Automated cherry pick of #3428: fix: 避免创建vmware磁盘快照
  pkg/apis/compute/snapshot.go
  pkg/compute/models/disks.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagedrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: approved, lgtm, size/L

#3454 fix: aliyun eip associate instance ignores IncorrectInstanceStatus error
  pkg/multicloud/aliyun/eip.go
Labels: approved, area/region, lgtm, size/S

#3455 Automated cherry pick of #3454: fix: aliyun eip associate instance ignores IncorrectInstanceStatus error
  pkg/multicloud/aliyun/eip.go
Labels: approved, lgtm, size/S

#3456 Automated cherry pick of #3454: fix: aliyun eip associate instance ignores IncorrectInstanceStatus error
  pkg/multicloud/aliyun/eip.go
Labels: approved, lgtm, size/S

#3462 fix: approve scripts imporvements, alllow approve_all PRs
  scripts/approve.sh
  scripts/approve_all.sh
Labels: approved, area/util, lgtm, size/M

#3444 Automated cherry pick of #3428: fix: 避免创建vmware磁盘快照
  pkg/apis/compute/snapshot.go
  pkg/compute/models/disks.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagedrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: approved, lgtm, size/L

#3461 hotfix: 参数校验使用结构体传参
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/zstack/provider/provider.go
Labels: approved, area/region, lgtm, size/L

#3463 elb sync fix
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/eip_associate_task.go
  pkg/multicloud/aws/aws.go
Labels: approved, area/region, lgtm, size/L

#3464 Automated cherry pick of #3463: elb sync fix
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/eip_associate_task.go
  pkg/multicloud/aws/aws.go
Labels: approved, lgtm, size/L

#3465 Automated cherry pick of #3463: elb sync fix
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/eip_associate_task.go
  pkg/multicloud/aws/aws.go
Labels: approved, lgtm, size/L

#3466 redis sku sync
  pkg/compute/models/cloudsync.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/skustools.go
  pkg/compute/service/service.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_skus.go
Labels: approved, area/region, lgtm, size/XL

#3467 Automated cherry pick of #3466: redis sku sync
  pkg/compute/models/cloudsync.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/skustools.go
  pkg/compute/service/service.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_skus.go
Labels: approved, lgtm, size/XL

#3468 Bugfix/yousong tmpfile
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/azure/storagecache.go
  pkg/util/fileutils2/seeker.go
  pkg/util/fileutils2/sparse.go
  pkg/util/fileutils2/sparse_test.go
  pkg/util/seclib2/certfile.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/pty_session.go
Labels: approved, area/region, lgtm, size/L

#3471 Automated cherry pick of #3468: azure: fix tmp image file handling
  pkg/util/aliyun/storagecache.go
  pkg/util/azure/storagecache.go
  pkg/util/fileutils2/sparse.go
  pkg/util/fileutils2/sparse_test.go
  pkg/util/seclib2/certfile.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/pty_session.go
Labels: approved, lgtm, size/L

#3470 Automated cherry pick of #3468: azure: fix tmp image file handling
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/azure/storagecache.go
  pkg/util/fileutils2/seeker.go
  pkg/util/fileutils2/sparse.go
  pkg/util/fileutils2/sparse_test.go
  pkg/util/seclib2/certfile.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/pty_session.go
Labels: approved, lgtm, size/L

#3469 Automated cherry pick of #3468: azure: fix tmp image file handling
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/azure/storagecache.go
  pkg/util/fileutils2/seeker.go
  pkg/util/fileutils2/sparse.go
  pkg/util/fileutils2/sparse_test.go
  pkg/util/seclib2/certfile.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/pty_session.go
Labels: approved, lgtm, size/L

#3473 fix: baremetal-prepare report admin ip using ssh client host
  pkg/baremetal/tasks/baseprepare.go
  pkg/compute/models/netinterfaces.go
  pkg/util/ssh/ssh.go
Labels: approved, area/baremetal, area/region, lgtm, size/S

#3474 Automated cherry pick of #3473: fix: baremetal-prepare report admin ip using ssh client host
  pkg/baremetal/tasks/baseprepare.go
  pkg/compute/models/netinterfaces.go
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/S

#3476 fix: baremetal-event-list support since/until filter
  cmd/climc/shell/baremetalevents.go
  pkg/logger/models/baremetalevents.go
Labels: approved, area/region, lgtm, size/M

#3477 Automated cherry pick of #3476: fix: baremetal-event-list support since/until filter
  cmd/climc/shell/baremetalevents.go
  pkg/logger/models/baremetalevents.go
Labels: approved, lgtm, size/M

#3481 Automated cherry pick of #3431: feat & fix: Add batch operator and fix some bugs for instance group
  cmd/climc/shell/groups.go
  cmd/climc/shell/instance_group.go
  cmd/climc/shell/servers.go
  docs/index.yaml
  docs/instance/bind-groups.yaml
  docs/instance/instance.yaml
  docs/instance/instances.yaml
  docs/instance/unbind-groups.yaml
  docs/instancegroup/bind-guest.yaml
  docs/instancegroup/instancegroup.yaml
  docs/instancegroup/instancegroups.yaml
  docs/instancegroup/unbind-guest.yaml
  docs/parameters/instance.yaml
  docs/parameters/instancegroup.yaml
  docs/schemas/instance.yaml
  docs/schemas/instancegroup.yaml
  pkg/compute/models/groupguests.go
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/mcclient/modules/mod_groupguest.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/XL

#3431 Feature & Bugfix: Instance Group
  cmd/climc/shell/groups.go
  cmd/climc/shell/instance_group.go
  cmd/climc/shell/servers.go
  docs/index.yaml
  docs/instance/bind-groups.yaml
  docs/instance/instance.yaml
  docs/instance/instances.yaml
  docs/instance/unbind-groups.yaml
  docs/instancegroup/bind-guest.yaml
  docs/instancegroup/instancegroup.yaml
  docs/instancegroup/instancegroups.yaml
  docs/instancegroup/unbind-guest.yaml
  docs/parameters/instance.yaml
  docs/parameters/instancegroup.yaml
  docs/schemas/instance.yaml
  docs/schemas/instancegroup.yaml
  pkg/compute/models/groupguests.go
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/mcclient/modules/mod_groupguest.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  pkg/util/logclient/consts.go
Labels: approved, area/region, lgtm, size/XL

#3472 Bugfix: Guest Image
  cmd/climc/shell/servers.go
  pkg/apis/image/consts.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_save_instance_image_task.go
  pkg/image/models/images.go
  pkg/image/tasks/guest_image_update_task.go
  pkg/mcclient/options/servers.go
Labels: approved, area/image, area/region, lgtm, size/M

#3482 Automated cherry pick of #3472: fix: Add operational restrictions and fix some bugs for guest image
  cmd/climc/shell/servers.go
  pkg/apis/image/consts.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_save_instance_image_task.go
  pkg/image/models/images.go
  pkg/image/tasks/guest_image_update_task.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/M

#3489 Automated cherry pick of #3487: fix: nil pointer panic when auth decode body failed
  pkg/keystone/tokens/handlers.go
Labels: approved, lgtm, size/XS

#3490 Automated cherry pick of #3487: fix: nil pointer panic when auth decode body failed
  pkg/keystone/tokens/handlers.go
Labels: approved, lgtm, size/XS

#3487 fix: nil pointer panic when auth decode body failed
  pkg/keystone/tokens/handlers.go
Labels: approved, area/keystone, lgtm, size/XS

#3488 Automated cherry pick of #3487: fix: nil pointer panic when auth decode body failed
  pkg/keystone/tokens/handlers.go
Labels: approved, lgtm, size/XS

#3494 fix: skip esxi vm with nil config
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/S

#3495 Automated cherry pick of #3494: fix: skip esxi vm with nil config
  pkg/util/esxi/datacenter.go
  pkg/util/esxi/virtualmachine.go
Labels: approved, lgtm, size/S

#3496 Automated cherry pick of #3494: fix: skip esxi vm with nil config
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/S

#3478 region sync fix
  pkg/apis/compute/cloudaccount_const.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: approved, area/region, lgtm, size/M

#3483 Automated cherry pick of #3478: region sync fix
  pkg/apis/compute/cloudaccount_const.go
  pkg/util/aws/aws.go
  pkg/util/aws/provider/provider.go
  pkg/util/azure/azure.go
  pkg/util/azure/provider/provider.go
  pkg/util/azure/region.go
  pkg/util/huawei/huawei.go
  pkg/util/huawei/region.go
Labels: approved, lgtm, size/M

#3484 Automated cherry pick of #3478: region sync fix
  pkg/apis/compute/cloudaccount_const.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: approved, lgtm, size/M

#3485 Automated cherry pick of #3478: region sync fix
  pkg/apis/compute/cloudaccount_const.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: approved, lgtm, size/M

#3497 Automated cherry pick of #3494: fix: skip esxi vm with nil config
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/S

#3502 Fix: Instance Group
  go.mod
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: approved, area/region, lgtm, size/L

#3491 Feature: Snapshot Policy Cache
  pkg/apis/compute/snapshot_const.go
  pkg/compute/models/snapshotpolicycache.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/snapshot_policy_cache_delete_task.go
Labels: approved, area/region, lgtm, size/L

#3507 Bugfix: Guest Image
  pkg/compute/models/guest_actions.go
Labels: approved, area/region, lgtm, size/XS

#3508 Automated cherry pick of #3507: fix(region): Pass 'auto_start' parameter to GuestSaveGuestImageTask if have
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3504 Automated cherry pick of #3491: feat(region): Add list and delelte apis for snapshot policy cache
  pkg/apis/compute/snapshot_const.go
  pkg/compute/models/snapshotpolicycache.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/snapshot_policy_cache_delete_task.go
Labels: approved, lgtm, size/L

#3493 region: gpu&instance_snapshot bugfix
  pkg/apis/compute/storage_const.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
Labels: area/region, size/L

#3509 Automated cherry pick of #3493: fix isolated device attach
  pkg/apis/compute/storage_const.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
Labels: size/L

#3506 Automated cherry pick of #3502: fix: Fix that fail to create vm with unforced instance group
  go.mod
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: size/L

#3510 fix: 避免删除安全组失败
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
Labels: approved, area/region, lgtm, size/XS

#3511 Automated cherry pick of #3510: fix: 避免删除安全组失败
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
Labels: approved, lgtm, size/XS

#3500 fix: 避免dbinstance created_at为空
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, area/region, lgtm, size/XS

#3514 Automated cherry pick of #3500: fix: 避免dbinstance created_at为空
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/XS

#3492 fix: 避免version输出不正确
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: approved, area/region, lgtm, size/M

#3516 Automated cherry pick of #3492: fix: 避免version输出不正确
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: approved, lgtm, size/M

#3517 Automated cherry pick of #3492: fix: 避免version输出不正确
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: approved, lgtm, size/M

#3515 Automated cherry pick of #3492: fix: 避免version输出不正确
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: approved, lgtm, size/M

#3521 fix: baremetal failed to register due to duplicate storagecache
  pkg/cloudcommon/agent/agent.go
Labels: approved, area/baremetal, lgtm, size/S

#3522 Automated cherry pick of #3521: fix: baremetal failed to register due to duplicate storagecache
  pkg/cloudcommon/agent/agent.go
Labels: approved, lgtm, size/S

#3518 fix: 虚拟机漂移后设置新的hostId
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/multicloud/zstack/region.go
Labels: approved, area/region, lgtm, size/M

#3519 Automated cherry pick of #3505: fix: 避免因backup删除失败导致删除rds无限失败
  cmd/climc/shell/dbinstances.go
  docs/dbinstance/dbinstance.yaml
  docs/parameters/dbinstance.yaml
  pkg/compute/models/dbinstances.go
  pkg/compute/models/purge.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/tasks/dbinstance_delete_task.go
Labels: approved, lgtm, size/L

#3505 fix: 避免因backup删除失败导致删除rds无限失败
  cmd/climc/shell/dbinstances.go
  docs/dbinstance/dbinstance.yaml
  docs/parameters/dbinstance.yaml
  pkg/compute/models/dbinstances.go
  pkg/compute/models/purge.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/tasks/dbinstance_delete_task.go
Labels: approved, lgtm, size/L

#3527 Automated cherry pick of #3518: fix: 虚拟机漂移后设置新的hostId
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/util/zstack/region.go
Labels: approved, lgtm, size/M

#3525 Automated cherry pick of #3518: fix: 虚拟机漂移后设置新的hostId
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/multicloud/zstack/region.go
Labels: approved, lgtm, size/M

#3526 Automated cherry pick of #3518: fix: 虚拟机漂移后设置新的hostId
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/multicloud/zstack/region.go
Labels: approved, lgtm, size/M

#3498 fix: reserve probed ipaddr
  cmd/climc/shell/networks.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/reservedip.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/storages.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/modules/mod_reservedips.go
Labels: approved, area/region, lgtm, size/L

#3528 webconsole: fix baremetal ipmitool sol payload active on another session
  pkg/webconsole/command/ipmi_command.go
Labels: approved, area/webconsole, lgtm, size/S

#3531 Automated cherry pick of #3528: webconsole: fix baremetal ipmitool sol payload active on another session
  pkg/webconsole/command/ipmi_command.go
Labels: approved, lgtm, size/S

#3530 Automated cherry pick of #3528: webconsole: fix baremetal ipmitool sol payload active on another session
  pkg/webconsole/command/ipmi_command.go
Labels: approved, lgtm, size/S

#3529 Automated cherry pick of #3528: webconsole: fix baremetal ipmitool sol payload active on another session
  pkg/webconsole/command/ipmi_command.go
Labels: approved, lgtm, size/S

#3499 Automated cherry pick of #3498: fix: reserve probed ipaddr
  cmd/climc/shell/networks.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/reservedip.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/storages.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/modules/mod_reservedips.go
Labels: size/L

#3534 action: fix apt 404 not found
  .github/workflows/docker.yml
Labels: needs-area

#3486 fix: 从aliyun对象存储上面同步dbinstance sku信息
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/skus_tools.go
  pkg/mcclient/modules/managers.go
Labels: approved, area/region, lgtm, size/L

#3520 Automated cherry pick of #3486: fix: 从aliyun对象存储上面同步dbinstance sku信息
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/skus_tools.go
  pkg/mcclient/modules/managers.go
Labels: approved, lgtm, size/L

#3423 Feature/tb add project create rpc
  pkg/mcclient/modules/mod_projects.go
  pkg/mcclient/modules/mod_users.go
Labels: approved, lgtm, size/L

#3503 Automated cherry pick of #3423: add rpc createuser & createproject
  pkg/mcclient/modules/mod_projects.go
  pkg/mcclient/modules/mod_users.go
Labels: approved, lgtm, size/L

#3524 aws elb bugfix
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/options/loadbalancercertificates.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: approved, area/region, lgtm, size/L

#3533 Automated cherry pick of #3524: 1.elb certificate usable fix 2.aws tcp&udp backendgroup create bugfix 3.aws backendgroup create bugfix 4.aws create listener bugfix 5.aws delete loadbalancer bugfix 6.aws backendgroup cache query fix 7.aws delete loadbalancer listener fix 8.aws create backendgroup fix 9.aws delete backend fix 10.loadbalancer listener rule add is_default column 11.huawei elb backendgroup sync fix 12.aws https listener sync fix
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/options/loadbalancercertificates.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: approved, lgtm, size/L

#3532 Automated cherry pick of #3524: 1.elb certificate usable fix 2.aws tcp&udp backendgroup create bugfix 3.aws backendgroup create bugfix 4.aws create listener bugfix 5.aws delete loadbalancer bugfix 6.aws backendgroup cache query fix 7.aws delete loadbalancer listener fix 8.aws create backendgroup fix 9.aws delete backend fix 10.loadbalancer listener rule add is_default column 11.huawei elb backendgroup sync fix 12.aws https listener sync fix
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/options/loadbalancercertificates.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: approved, lgtm, size/L

#3536 fix: approve.sh fail to find check success record for some pr
  scripts/approve.sh
Labels: approved, area/util, lgtm, size/M

#3542 fix: server-list details report nil pointer panic
  pkg/compute/guestdrivers/baremetals.go
Labels: approved, area/region, lgtm, size/XS

#3543 Automated cherry pick of #3542: fix: server-list details report nil pointer panic
  pkg/compute/guestdrivers/baremetals.go
Labels: approved, lgtm, size/XS

#3546 fix: unify network used address query
  pkg/compute/models/networks.go
  pkg/compute/models/reservedips.go
Labels: approved, area/region, lgtm, size/L

#3547 Automated cherry pick of #3546: fix: unify network used address query
  pkg/compute/models/networks.go
  pkg/compute/models/reservedips.go
Labels: approved, lgtm, size/L

#3548 fix: normalize baremetal sysinfo manufacture
  pkg/baremetal/manager.go
  pkg/baremetal/profiles/profiles.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/ipmiprobe.go
  pkg/baremetal/utils/ipmitool/ipmitool.go
  pkg/baremetal/utils/ipmitool/ipmitool_test.go
  pkg/cloudcommon/types/types.go
  pkg/compute/tasks/baremetal_ipmi_probe_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/util/logclient/consts.go
  pkg/util/sysutils/sysutils.go
  pkg/util/sysutils/sysutils_test.go
Labels: approved, area/baremetal, lgtm, size/L

#3549 Automated cherry pick of #3548: fix: normalize baremetal sysinfo manufacture
  pkg/baremetal/manager.go
  pkg/baremetal/profiles/profiles.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/ipmiprobe.go
  pkg/baremetal/utils/ipmitool/ipmitool.go
  pkg/baremetal/utils/ipmitool/ipmitool_test.go
  pkg/cloudcommon/types/types.go
  pkg/compute/tasks/baremetal_ipmi_probe_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/util/logclient/consts.go
  pkg/util/sysutils/sysutils.go
  pkg/util/sysutils/sysutils_test.go
Labels: approved, lgtm, size/L

#3550 fix: simplify object delete-fail-reason message
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/hosts.go
  pkg/util/httputils/httputils.go
Labels: approved, area/region, lgtm, size/S

#3551 Automated cherry pick of #3550: fix: simplify object delete-fail-reason message
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/hosts.go
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/S

#3565 Automated cherry pick of #3564: fix: cleanup host/baremetal status code
  pkg/apis/compute/host_const.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/host_maintenance_task.go
Labels: approved, lgtm, size/S

#3564 fix: cleanup host/baremetal status code
  pkg/apis/compute/host_const.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/host_maintenance_task.go
Labels: approved, area/region, lgtm, size/S

#3545 fix(image): Change the update process of guest image
  pkg/cloudcommon/db/opslog.go
  pkg/image/models/image_guest.go
  pkg/image/tasks/guest_image_update_task.go
  pkg/util/logclient/consts.go
Labels: approved, area/image, lgtm, size/L

#3567 Automated cherry pick of #3545: fix(image): Change the update process of guest image
  pkg/cloudcommon/db/opslog.go
  pkg/image/models/image_guest.go
  pkg/image/tasks/guest_image_update_task.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/L

#3557 redis sync fix
  cmd/climc/shell/notification.go
  pkg/apis/compute/elasticcache_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/skus_tools.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/elasticcache_account_create_task.go
  pkg/compute/tasks/elasticcache_account_delete_task.go
  pkg/compute/tasks/elasticcache_account_reset_password_task.go
  pkg/compute/tasks/elasticcache_acl_create_task.go
  pkg/compute/tasks/elasticcache_acl_delete_task.go
  pkg/compute/tasks/elasticcache_acl_update_task.go
  pkg/compute/tasks/elasticcache_allocate_public_connection_task.go
  pkg/compute/tasks/elasticcache_backup_create_task.go
  pkg/compute/tasks/elasticcache_backup_restore_instance_task.go
  pkg/compute/tasks/elasticcache_change_spec_task.go
  pkg/compute/tasks/elasticcache_create_task.go
  pkg/compute/tasks/elasticcache_delete_task.go
  pkg/compute/tasks/elasticcache_flush_instance.go
  pkg/compute/tasks/elasticcache_parameter_update_task.go
  pkg/compute/tasks/elasticcache_restart_task.go
  pkg/compute/tasks/elasticcache_set_maintain_time_task.go
  pkg/compute/tasks/elasticcache_sync_task.go
  pkg/compute/tasks/elasticcache_update_auth_mode_task.go
  pkg/compute/tasks/elasticcache_update_backup_policy_task.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/elasticcache_instance.go
  pkg/util/logclient/consts.go
Labels: approved, area/region, lgtm, size/L

#3560 Automated cherry pick of #3557: redis sync fix
  cmd/climc/shell/notification.go
  pkg/apis/compute/elasticcache_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/skus_tools.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/elasticcache_account_create_task.go
  pkg/compute/tasks/elasticcache_account_delete_task.go
  pkg/compute/tasks/elasticcache_account_reset_password_task.go
  pkg/compute/tasks/elasticcache_acl_create_task.go
  pkg/compute/tasks/elasticcache_acl_delete_task.go
  pkg/compute/tasks/elasticcache_acl_update_task.go
  pkg/compute/tasks/elasticcache_allocate_public_connection_task.go
  pkg/compute/tasks/elasticcache_backup_create_task.go
  pkg/compute/tasks/elasticcache_backup_restore_instance_task.go
  pkg/compute/tasks/elasticcache_change_spec_task.go
  pkg/compute/tasks/elasticcache_create_task.go
  pkg/compute/tasks/elasticcache_delete_task.go
  pkg/compute/tasks/elasticcache_flush_instance.go
  pkg/compute/tasks/elasticcache_parameter_update_task.go
  pkg/compute/tasks/elasticcache_restart_task.go
  pkg/compute/tasks/elasticcache_set_maintain_time_task.go
  pkg/compute/tasks/elasticcache_sync_task.go
  pkg/compute/tasks/elasticcache_update_auth_mode_task.go
  pkg/compute/tasks/elasticcache_update_backup_policy_task.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/elasticcache_instance.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/L

#3535 fix: remove private cloud server sku brand and provider attribute
  cmd/climc/shell/skus.go
  docs/index.yaml
  docs/parameters/serversku.yaml
  docs/schemas/serversku.yaml
  docs/serversku/cache-sku.yaml
  docs/serversku/serversku.yaml
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/tasks/server_sku_cache_task.go
  pkg/compute/tasks/server_sku_delete_task.go
  pkg/multicloud/esxi/fakeregion.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/region_base.go
  pkg/multicloud/zstack/offering.go
  pkg/multicloud/zstack/region.go
Labels: approved, area/region, lgtm, size/L

#3544 Automated cherry pick of #3535: fix: remove private cloud server sku brand and provider attribute
  cmd/climc/shell/skus.go
  docs/index.yaml
  docs/parameters/serversku.yaml
  docs/schemas/serversku.yaml
  docs/serversku/cache-sku.yaml
  docs/serversku/serversku.yaml
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/tasks/server_sku_cache_task.go
  pkg/compute/tasks/server_sku_delete_task.go
  pkg/multicloud/esxi/fakeregion.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/region_base.go
  pkg/multicloud/zstack/offering.go
  pkg/multicloud/zstack/region.go
Labels: approved, lgtm, size/L

#3563 Automated cherry pick of #3558: huawei disk attach bugfix
  pkg/multicloud/huawei/instance.go
Labels: approved, lgtm, size/M

#3558 huawei disk attach bugfix
  pkg/multicloud/huawei/instance.go
Labels: approved, area/region, lgtm, size/M

#3562 Automated cherry pick of #3558: huawei disk attach bugfix
  pkg/multicloud/huawei/instance.go
Labels: approved, lgtm, size/M

#3561 Automated cherry pick of #3558: huawei disk attach bugfix
  pkg/util/huawei/instance.go
Labels: approved, lgtm, size/M

#3566 region: bugfix instance-snapshot create
  pkg/baremetal/tasks/bm_register.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/qmp.go
  pkg/mcclient/modules/mod_servers.go
Labels: approved, area/region, lgtm, size/L

#3568 Automated cherry pick of #3566: fix instance-snapshot create
  pkg/baremetal/tasks/bm_register.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/qmp.go
  pkg/mcclient/modules/mod_servers.go
Labels: approved, lgtm, size/L

#3571 fix: 赋予rds账号权限失败后进行重试
  pkg/multicloud/aliyun/aliyun.go
Labels: approved, area/region, lgtm, size/XS

#3572 Automated cherry pick of #3571: fix: 赋予rds账号权限失败后进行重试
  pkg/multicloud/aliyun/aliyun.go
Labels: approved, lgtm, size/XS

#3537 fix: 添加rds zone返回信息
  pkg/compute/models/dbinstances.go
Labels: approved, area/region, lgtm, size/M

#3538 Automated cherry pick of #3537: fix: 添加rds zone返回信息
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/M

#3576 fix(region): Check if group and guest belong to same project
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
Labels: area/region, lgtm, size/S

#3587 Automated cherry pick of #3576: fix(region): Check if group and guest belong to same project
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#3588 Automated cherry pick of #3576: fix(region): Check if group and guest belong to same project
  pkg/compute/models/groups.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#3583 Automated cherry pick of #3582: fix: 避免Openstack越过存储检查
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3585 Automated cherry pick of #3582: fix: 避免Openstack越过存储检查
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3586 Automated cherry pick of #3582: fix: 避免Openstack越过存储检查
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3582 fix: 避免Openstack越过存储检查
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
Labels: approved, area/region, lgtm, size/XS

#3584 Automated cherry pick of #3582: fix: 避免Openstack越过存储检查
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3570 feature: approve.sh check whether all assigned reviews lgtm the PR
  scripts/README.md
  scripts/advchecks.py
  scripts/approve.sh
  scripts/approve_all.sh
  scripts/label.sh
  scripts/lgtm.sh
Labels: area/util, lgtm, size/L

#3604 Automated cherry pick of #3603: fix: create baremetal server with iso, baremetal register support redfish
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
  pkg/cloudcommon/app/mergeconf.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/util/influxdb/metrics.go
Labels: approved, lgtm, size/L

#3605 Automated cherry pick of #3603: fix: create baremetal server with iso, baremetal register support redfish
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
  pkg/cloudcommon/app/mergeconf.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/util/influxdb/metrics.go
Labels: approved, lgtm, size/L

#3603 fix: create baremetal server with iso, baremetal register support redfishApi
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
  pkg/cloudcommon/app/mergeconf.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/util/influxdb/metrics.go
Labels: approved, area/baremetal, lgtm, size/L

#3581 Automated cherry pick of #3501: 云上操作日志同步
  cmd/cloudevent/main.go
  pkg/apis/cloudevent/cloudevent_const.go
  pkg/apis/cloudevent/doc.go
  pkg/cloudevent/models/cloudevents.go
  pkg/cloudevent/models/cloudproviders.go
  pkg/cloudevent/models/doc.go
  pkg/cloudevent/models/initdb.go
  pkg/cloudevent/options/doc.go
  pkg/cloudevent/options/options.go
  pkg/cloudevent/service/doc.go
  pkg/cloudevent/service/handlers.go
  pkg/cloudevent/service/service.go
  pkg/cloudevent/tasks/cloudevent_sync_task.go
  pkg/cloudevent/tasks/doc.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/events.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aliyun/shell/events.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/event.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/shell/event.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_traces.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/shell/events.go
  pkg/multicloud/huawei/traces.go
  pkg/multicloud/qcloud/events.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/events.go
  pkg/multicloud/region_base.go
Labels: approved, lgtm, size/XXL

#3501 云上操作日志同步
  cmd/cloudevent/main.go
  pkg/apis/cloudevent/cloudevent_const.go
  pkg/apis/cloudevent/doc.go
  pkg/cloudevent/models/cloudevents.go
  pkg/cloudevent/models/cloudproviders.go
  pkg/cloudevent/models/doc.go
  pkg/cloudevent/models/initdb.go
  pkg/cloudevent/options/doc.go
  pkg/cloudevent/options/options.go
  pkg/cloudevent/service/doc.go
  pkg/cloudevent/service/handlers.go
  pkg/cloudevent/service/service.go
  pkg/cloudevent/tasks/cloudevent_sync_task.go
  pkg/cloudevent/tasks/doc.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/events.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aliyun/shell/events.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/event.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/shell/event.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_traces.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/shell/events.go
  pkg/multicloud/huawei/traces.go
  pkg/multicloud/qcloud/events.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/events.go
  pkg/multicloud/region_base.go
Labels: approved, area/cloudevent, lgtm, size/XXL

#3569 fix: avolid duplicate secgroup name error when create secgroup
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/resources.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aliyun/shell/secgroup.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/shell/secgroup.go
  pkg/multicloud/azure/vpc.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/secgroup.go
  pkg/multicloud/huawei/vpc.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/openstack/vpc.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/qcloud/vpc.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/ucloud/shell/secgroup.go
  pkg/multicloud/ucloud/vpc.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/shell/securitygroup.go
  pkg/multicloud/zstack/vpc.go
Labels: approved, area/region, lgtm, size/L

#3575 Automated cherry pick of #3569: fix: avolid duplicate secgroup name error when create secgroup
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/resources.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aliyun/shell/secgroup.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/shell/secgroup.go
  pkg/multicloud/azure/vpc.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/secgroup.go
  pkg/multicloud/huawei/vpc.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/openstack/vpc.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/qcloud/vpc.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/ucloud/shell/secgroup.go
  pkg/multicloud/ucloud/vpc.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/shell/securitygroup.go
  pkg/multicloud/zstack/vpc.go
Labels: approved, lgtm, size/L

#3574 Automated cherry pick of #3569: fix: avolid duplicate secgroup name error when create secgroup
  pkg/cloudprovider/fakeregion.go
  pkg/cloudprovider/resources.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aliyun/shell/secgroup.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/shell/secgroup.go
  pkg/multicloud/azure/vpc.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/secgroup.go
  pkg/multicloud/huawei/vpc.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/openstack/vpc.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/qcloud/vpc.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/ucloud/shell/secgroup.go
  pkg/multicloud/ucloud/vpc.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/shell/securitygroup.go
  pkg/multicloud/zstack/vpc.go
Labels: approved, lgtm, size/L
