Repository yunionio/cloudpods, pull requests merged in 2019-10, with the labels that each got.

#3086 feature: 支持名称重复数据
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshotpolicy.go
Labels: approved, area/region, lgtm, size/M

#3103 Automated cherry pick of #3086: feature: 支持名称重复数据
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshotpolicy.go
Labels: approved, lgtm, size/M

#3096 fix: 添加vpc usable过滤参数,过滤cloudprovider异常的networks
  cmd/climc/shell/vpcs.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: approved, area/region, lgtm, size/M

#3104 Automated cherry pick of #3096: fix: 添加vpc usable过滤参数,过滤cloudprovider异常的networks
  cmd/climc/shell/vpcs.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/M

#3111 fix: snapshot realdelete nil pointer panic
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/guest_sync_task.go
Labels: approved, lgtm

#3112 Automated cherry pick of #3111: fix: snapsho realdelete nil pointer panic
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/guest_sync_task.go
Labels: approved, lgtm

#3113 Automated cherry pick of #3111: fix: snapsho realdelete nil pointer panic
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/guest_sync_task.go
Labels: approved, lgtm, size/M

#3114 Automated cherry pick of #3111: fix: snapsho realdelete nil pointer panic
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/guest_sync_task.go
Labels: approved, lgtm, size/M

#3119 Automated cherry pick of #3117: scheduler: set random network filter default scope domain
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, lgtm, size/XS

#3117 scheduler: set random network filter default scope domain
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, area/scheduler, lgtm, size/XS

#3118 Automated cherry pick of #3117: scheduler: set random network filter default scope domain
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, lgtm, size/XS

#3120 Automated cherry pick of #3117: scheduler: set random network filter default scope domain
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, lgtm, size/XS

#3121 scheduler: fix random network domain not matched
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, area/scheduler, lgtm, size/XS

#3122 Automated cherry pick of #3121: scheduler: fix random network domain not matched
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, lgtm, size/XS

#3123 Automated cherry pick of #3121: scheduler: fix random network domain not matched
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, lgtm, size/XS

#3124 Automated cherry pick of #3121: scheduler: fix random network domain not matched
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, lgtm, size/XS

#3125 Automated cherry pick of #3026: nat_docs fix
  docs/index.yaml
  docs/natgateway/dnat-resources.yaml
  docs/natgateway/snat-resources.yaml
  docs/schemas/natgateway.yaml
Labels: size/S

#3126 Automated cherry pick of #3026: nat_docs fix
  docs/index.yaml
  docs/natgateway/dnat-resources.yaml
  docs/natgateway/snat-resources.yaml
  docs/schemas/natgateway.yaml
Labels: size/S

#3110 Bugfix/tb bugfix 0928
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/purge.go
  pkg/compute/models/skus.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: approved, area/region, lgtm, size/XXL

#3130 Automated cherry pick of #3110: loadbalancer bugfix
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/purge.go
  pkg/compute/models/skus.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: approved, lgtm, size/XXL

#3097 bugfix: fix host image memory leak and optimize open blk device
  cmd/climc/shell/pprof.go
  pkg/hostimage/host_image_service.go
  pkg/hostimage/image.go
  pkg/mcclient/mcclient.go
  pkg/mcclient/modules/pprof.go
Labels: approved, area/host, lgtm, size/L

#3131 Automated cherry pick of #3110: loadbalancer bugfix
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/purge.go
  pkg/compute/models/skus.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: approved, lgtm, size/XXL

#3065 Automated cherry pick of #3064: add: 支持创建安全组时同时创建规则
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/L

#3066 Automated cherry pick of #3064: add: 支持创建安全组时同时创建规则
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/L

#3064 add: 支持创建安全组时同时创建规则
  docs/schemas/secgroup.yaml
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
Labels: approved, area/region, lgtm, size/L

#3132 Scheduler Feature
  cmd/climc/shell/instance_group.go
  cmd/climc/shell/servers.go
  pkg/apis/compute/api.go
  pkg/compute/models/groupguests.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/mcclient/modules/mod_groupguest.go
  pkg/mcclient/modules/mod_instance_group.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/handler/handler.go
  pkg/scheduler/models/pending_usage.go
Labels: approved, area/region, area/scheduler, lgtm, size/XL

#3141 fix: scheduler specfied network no errors
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: area/scheduler

#3142 Automated cherry pick of #3141: fix: scheduler specfied network no errors
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: size/XS

#3143 Automated cherry pick of #3141: fix: scheduler specfied network no errors
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: size/XS

#3144 Automated cherry pick of #3141: fix: scheduler specfied network no errors
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: size/XS

#3145 scheduler: fix not setSchedPendingUsage condition
  pkg/scheduler/handler/handler.go
Labels: area/scheduler, size/XS

#3140 Automated cherry pick of #3132: guest persion
  cmd/climc/shell/instance_group.go
  cmd/climc/shell/servers.go
  pkg/apis/compute/api.go
  pkg/compute/models/groupguests.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/mcclient/modules/mod_groupguest.go
  pkg/mcclient/modules/mod_instance_group.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/handler/handler.go
  pkg/scheduler/models/pending_usage.go
Labels: size/XL

#3150 hostman: ovs: implement PersistentMAC()
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: approved, area/host, lgtm, size/S

#3151 Automated cherry pick of #3150: hostman: ovs: implement PersistentMAC()
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: approved, lgtm, size/S

#3152 Automated cherry pick of #3150: hostman: ovs: implement PersistentMAC()
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: approved, lgtm, size/S

#3153 Automated cherry pick of #3150: hostman: ovs: implement PersistentMAC()
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: approved, lgtm, size/S

#3139 Automated cherry pick of #3136: fix: guest create eip quota check use owner quota
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3102 fix: network支持多个zone过滤
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/M

#3138 Automated cherry pick of #3136: fix: guest create eip quota check use owner quota
  pkg/compute/models/guest_actions.go
Labels: approved, lgtm, size/XS

#3105 Automated cherry pick of #3102: fix: network支持多个zone过滤
  cmd/climc/shell/networks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#3165 fix: skip services without project resources when fetching project resources
  pkg/keystone/cronjobs/project_resources.go
Labels: approved, area/keystone, lgtm, size/M

#3166 Automated cherry pick of #3165: fix: skip services without project resources when fetching project resources
  pkg/keystone/cronjobs/project_resources.go
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/M

#3167 Automated cherry pick of #3165: fix: skip services without project resources when fetching project resources
  pkg/keystone/cronjobs/project_resources.go
Labels: approved, lgtm, size/M

#3168 Automated cherry pick of #3165: fix: skip services without project resources when fetching project resources
  pkg/keystone/cronjobs/project_resources.go
Labels: approved, lgtm, size/M

#3162 fix: show delele fail reason if cannot delete a resource
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/region, lgtm, size/XS

#3163 Automated cherry pick of #3162: fix: show delele fail reason if cannot delete a resource
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm

#3164 Automated cherry pick of #3162: fix: show delele fail reason if cannot delete a resource
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#3172 Automated cherry pick of #3169: fix: string2scope ignore user scope
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/util/rbacutils/rbac.go
Labels: approved, lgtm, size/S

#3171 Automated cherry pick of #3169: fix: string2scope ignore user scope
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/util/rbacutils/rbac.go
Labels: approved, lgtm, size/S

#3173 Bugfix/yousong ovs no autostart
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/system_service/servicemanager.go
  pkg/hostman/system_service/system_service.go
  pkg/hostman/system_service/systemd.go
  pkg/hostman/system_service/systemd_test.go
  pkg/hostman/system_service/sysv.go
Labels: approved, area/host, lgtm, size/M

#3174 Automated cherry pick of #3173: hostman: system_service: add IsEnabled() support
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/system_service/servicemanager.go
  pkg/hostman/system_service/system_service.go
  pkg/hostman/system_service/systemd.go
  pkg/hostman/system_service/systemd_test.go
  pkg/hostman/system_service/sysv.go
Labels: approved, lgtm, size/M

#3175 Automated cherry pick of #3173: hostman: system_service: add IsEnabled() support
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/system_service/servicemanager.go
  pkg/hostman/system_service/system_service.go
  pkg/hostman/system_service/systemd.go
  pkg/hostman/system_service/systemd_test.go
  pkg/hostman/system_service/sysv.go
Labels: approved, lgtm, size/M

#3176 Automated cherry pick of #3173: hostman: system_service: add IsEnabled() support
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/system_service/servicemanager.go
  pkg/hostman/system_service/system_service.go
  pkg/hostman/system_service/systemd.go
  pkg/hostman/system_service/systemd_test.go
  pkg/hostman/system_service/sysv.go
Labels: approved, lgtm, size/M

#3154 ansibleserver: enable tenant/user cache manager
  pkg/ansibleserver/service/handlers.go
Labels: approved, area/ansible, lgtm, size/XS

#3155 Automated cherry pick of #3154: ansibleserver: enable tenant/user cache manager
  pkg/ansibleserver/service/handlers.go
Labels: approved, lgtm, size/XS

#3170 Automated cherry pick of #3169: fix: string2scope ignore user scope
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/util/rbacutils/rbac.go
Labels: approved, lgtm, size/S

#3169 fix: string2scope ignore user scope
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/util/rbacutils/rbac.go
Labels: approved, area/region, lgtm, size/S

#3157 Automated cherry pick of #3154: ansibleserver: enable tenant/user cache manager
  pkg/ansibleserver/service/handlers.go
Labels: approved, lgtm, size/XS

#3156 Automated cherry pick of #3154: ansibleserver: enable tenant/user cache manager
  pkg/ansibleserver/service/handlers.go
Labels: approved, lgtm, size/XS

#3148 region: support list wire by host
  cmd/climc/shell/wires.go
  pkg/compute/models/wires.go
Labels: approved, area/region, lgtm, needs-area, size/S

#3149 Automated cherry pick of #3148: region: support list wire by host
  cmd/climc/shell/wires.go
  pkg/compute/models/wires.go
Labels: approved, lgtm, size/S

#3147 region features:
  pkg/cloudcommon/db/project.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/secgroups.go
  pkg/compute/service/service.go
Labels: approved, area/region, lgtm, size/L

#3159 Automated cherry pick of #3147: feature:
  pkg/cloudcommon/db/project.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/secgroups.go
  pkg/compute/service/service.go
Labels: approved, lgtm, size/L

#3184 keystone: endpoint list by service
  pkg/keystone/models/endpoints.go
Labels: area/keystone, size/S

#3185 Automated cherry pick of #3184: keystone: endpoint list by service
  pkg/keystone/models/endpoints.go
Labels: size/S

#3186 Automated cherry pick of #3184: keystone: endpoint list by service
  pkg/keystone/models/endpoints.go
Labels: size/S

#3160 Automated cherry pick of #3147: feature:
  pkg/cloudcommon/db/project.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/models/secgroups.go
  pkg/compute/service/service.go
Labels: lgtm, size/L

#3188 misc bugfix:
  cmd/climc/shell/servers.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/project.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/compute/models/buckets.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/keypairs.go
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/disk_create_task.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/image/models/images.go
  pkg/image/tasks/image_probe_task.go
Labels: approved, area/host, area/region, lgtm, size/L

#3194 Automated cherry pick of #3188: fix dirty server start, disk format empty
  cmd/climc/shell/servers.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/project.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/compute/models/buckets.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/keypairs.go
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/disk_create_task.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/image/models/images.go
  pkg/image/tasks/image_probe_task.go
Labels: approved, lgtm, size/L

#3196 Automated cherry pick of #3188: fix dirty server start, disk format empty
  cmd/climc/shell/servers.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/project.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/compute/models/buckets.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/keypairs.go
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/disk_create_task.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/image/models/images.go
  pkg/image/tasks/image_probe_task.go
Labels: approved, lgtm, size/L

#3180 fix: 避免公有云账号统计虚拟的host数量
  pkg/compute/models/cloudaccounts.go
Labels: approved, area/region, lgtm, size/XS

#3182 Automated cherry pick of #3180: fix: 避免公有云账号统计虚拟的host数量
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/XS

#3181 Automated cherry pick of #3180: fix: 避免公有云账号统计虚拟的host数量
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/XS

#3183 Automated cherry pick of #3180: fix: 避免公有云账号统计虚拟的host数量
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/XS

#3190 fix: 创建相同配置时返回正确的eip信息
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XS

#3193 Automated cherry pick of #3190: fix: 创建相同配置时返回正确的eip信息
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#3191 Automated cherry pick of #3190: fix: 创建相同配置时返回正确的eip信息
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#3192 Automated cherry pick of #3190: fix: 创建相同配置时返回正确的eip信息
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#3200 huawei & aws bugfix
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostdrivers.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/instance.go
Labels: approved, area/region, lgtm, size/L

#3202 Automated cherry pick of #3200: huawei & aws bugfix
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostdrivers.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/instance.go
Labels: approved, lgtm, size/L

#3201 Automated cherry pick of #3200: huawei & aws bugfix
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostdrivers.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/instance.go
Labels: approved, lgtm, size/L

#3204 Automated cherry pick of #3200: huawei & aws bugfix
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostdrivers.go
  pkg/util/aws/vpc.go
  pkg/util/huawei/image.go
  pkg/util/huawei/instance.go
Labels: approved, lgtm, size/L

#3161 loadbalancer cache create api
  cmd/climc/shell/loadbalancercachedacls.go
  cmd/climc/shell/loadbalancercachedcertificates.go
  docs/index.yaml
  docs/loadbalancer/loadbalancercachedacls.yaml
  docs/loadbalancer/loadbalancercachedcertificate.yaml
  docs/loadbalancer/loadbalancercachedcertificates.yaml
  docs/schemas/loadbalancer.yaml
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, area/region, lgtm, size/L

#3177 Automated cherry pick of #3161: loadbalancer cache create api
  cmd/climc/shell/loadbalancercachedacls.go
  cmd/climc/shell/loadbalancercachedcertificates.go
  docs/index.yaml
  docs/loadbalancer/loadbalancercachedacls.yaml
  docs/loadbalancer/loadbalancercachedcertificate.yaml
  docs/loadbalancer/loadbalancercachedcertificates.yaml
  docs/schemas/loadbalancer.yaml
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#3178 Automated cherry pick of #3161: loadbalancer cache create api
  cmd/climc/shell/loadbalancercachedacls.go
  cmd/climc/shell/loadbalancercachedcertificates.go
  docs/index.yaml
  docs/loadbalancer/loadbalancercachedacls.yaml
  docs/loadbalancer/loadbalancercachedcertificate.yaml
  docs/loadbalancer/loadbalancercachedcertificates.yaml
  docs/schemas/loadbalancer.yaml
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#3197 Automated cherry pick of #3195: fix: 避免部分套餐无法列出
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#3198 Automated cherry pick of #3195: fix: 避免部分套餐无法列出
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#3195 fix: 避免部分套餐无法列出
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/S

#3127 Bugfix and feature add : snapshotpolicy
  cmd/climc/shell/disks.go
  cmd/climc/shell/snapshot_policy.go
  docs/index.yaml
  docs/parameters/disk.yaml
  docs/schemas/snapshotpolicy.yaml
  docs/snapshotpolicy/cache.yaml
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/compute/tasks/snapshotpolicy_disk_task.go
  pkg/multicloud/qcloud/snapshot.go
  pkg/util/logclient/consts.go
Labels: approved, area/region, lgtm, size/L

#3208 Automated cherry pick of #3127: fix
  cmd/climc/shell/disks.go
  cmd/climc/shell/snapshot_policy.go
  docs/index.yaml
  docs/parameters/disk.yaml
  docs/schemas/snapshotpolicy.yaml
  docs/snapshotpolicy/cache.yaml
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/compute/tasks/snapshotpolicy_disk_task.go
  pkg/multicloud/qcloud/snapshot.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/L

#3209 Automated cherry pick of #3127: fix
  cmd/climc/shell/disks.go
  cmd/climc/shell/snapshot_policy.go
  docs/index.yaml
  docs/parameters/disk.yaml
  docs/schemas/snapshotpolicy.yaml
  docs/snapshotpolicy/cache.yaml
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/compute/tasks/snapshotpolicy_disk_task.go
  pkg/multicloud/qcloud/snapshot.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/L

#3206 Automated cherry pick of #3205: fix: 返回网卡所在的网络名称信息
  docs/schemas/networkinterfacenetwork.yaml
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkinterfaces.go
Labels: approved, lgtm, size/M

#3207 Automated cherry pick of #3205: fix: 返回网卡所在的网络名称信息
  docs/schemas/networkinterfacenetwork.yaml
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkinterfaces.go
Labels: approved, lgtm, size/M

#3205 fix: 返回网卡所在的网络名称信息
  docs/schemas/networkinterfacenetwork.yaml
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkinterfaces.go
Labels: approved, area/region, lgtm, size/M

#3210 fix: azure blob storage empty blob error
  pkg/multicloud/azure/storageaccount.go
Labels: approved, area/region, lgtm, size/M

#3211 Automated cherry pick of #3210: fix: azure blob storage empty blob error
  pkg/multicloud/azure/storageaccount.go
Labels: approved, lgtm, size/M

#3212 Automated cherry pick of #3210: fix: azure blob storage empty blob error
  pkg/multicloud/azure/storageaccount.go
Labels: approved, lgtm, size/M

#3213 fix: aliyun bucket sync cancel local limit
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/xsky/bucket.go
Labels: approved, area/region, lgtm, size/M

#3214 Automated cherry pick of #3213: fix: aliyun bucket sync cancel local limit
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/xsky/bucket.go
Labels: approved, lgtm, size/M

#3215 Automated cherry pick of #3213: fix: aliyun bucket sync cancel local limit
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/xsky/bucket.go
Labels: approved, lgtm, size/M

#3216 fix: recover can_update field and add update_fail_reason field
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/util, lgtm, size/XS

#3217 Automated cherry pick of #3216: fix: recover can_update field and add update_fail_reason field
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm

#3218 Automated cherry pick of #3216: fix: recover can_update field and add update_fail_reason field
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#3226 Automated cherry pick of #3224: fix: Should not leave groups in SGuest.RealDelete; SGuest.LeaveAllGroups will be call in purge and guest_delete_task.
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#3224 Bugfix: instance_group
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/S

#3219 fix: allow docker_push by non-root user
  scripts/docker_push.sh
Labels: approved, area/util, lgtm, size/XS

#3223 Automated cherry pick of #2983: - instance snapshot
  cmd/climc/shell/instance_snapshots.go
  cmd/climc/shell/servers.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/snapshot_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshot_joint.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/disk_reset_task.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/instance_snapshot_delete_task.go
  pkg/compute/tasks/instance_snapshot_reset_task.go
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/modules/mod_instance_snapshots.go
  pkg/mcclient/options/servers.go
  pkg/util/logclient/consts.go
  pkg/util/qemuimg/qemuimg.go
Labels: approved, lgtm, size/XXL

#2983 feature: instance snapshot
  cmd/climc/shell/instance_snapshots.go
  cmd/climc/shell/servers.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/snapshot_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshot_joint.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/disk_reset_task.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/instance_snapshot_delete_task.go
  pkg/compute/tasks/instance_snapshot_reset_task.go
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/modules/mod_instance_snapshots.go
  pkg/mcclient/options/servers.go
  pkg/util/logclient/consts.go
  pkg/util/qemuimg/qemuimg.go
Labels: approved, area/region, lgtm, size/XXL

#3228 Automated cherry pick of #3189: fix: openstack上传镜像时也指定os_type及额外信息
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/shell/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, lgtm, size/M

#3189 fix: openstack上传镜像时也指定os_type及额外信息
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/shell/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, area/region, lgtm, size/M

#3227 Automated cherry pick of #3189: fix: openstack上传镜像时也指定os_type及额外信息
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/shell/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, lgtm, size/M

#3229 Automated cherry pick of #3189: fix: openstack上传镜像时也指定os_type及额外信息
  pkg/util/openstack/image.go
  pkg/util/openstack/shell/image.go
  pkg/util/openstack/storagecache.go
Labels: approved, lgtm, size/M

#3220 fix: azure ListObject should skip current folder
  pkg/multicloud/azure/storageaccount.go
Labels: approved, area/region, lgtm, size/XS

#3222 Automated cherry pick of #3220: fix: azure ListObject should skip current folder
  pkg/multicloud/azure/storageaccount.go
Labels: approved, lgtm, size/XS

#3221 Automated cherry pick of #3220: fix: azure ListObject should skip current folder
  pkg/multicloud/azure/storageaccount.go
Labels: approved, lgtm, size/XS

#3236 scheduler: adjust skip network filter condition
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: area/scheduler, size/XS

#3237 Automated cherry pick of #3236: scheduler: adjust skip network filter condition
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: size/XS

#3239 Automated cherry pick of #3236: scheduler: adjust skip network filter condition
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: size/XS

#3241 Bugfux: snapshotpolicy for qcloud
  pkg/compute/models/snapshotpolicy.go
  pkg/multicloud/qcloud/snapshot_policy.go
Labels: approved, area/region, lgtm, size/XS

#3242 Automated cherry pick of #3241: fix: the input parameters is wrong when create snapshotpolicy with repeatweekday Sunday for qcloud.
  pkg/compute/models/snapshotpolicy.go
  pkg/multicloud/qcloud/snapshot_policy.go
Labels: approved, lgtm, size/XS

#3230 feature :gpu mutil attach by model type, bugfix: splited off network set hint name
  pkg/compute/models/guest_actions.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/networks.go
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: approved, area/region, lgtm, size/M

#3233 Automated cherry pick of #3231: fix: 避免删除azure失败
  pkg/multicloud/azure/eip.go
Labels: approved, lgtm

#3234 Automated cherry pick of #3231: fix: 避免删除azure失败
  pkg/util/azure/eip.go
Labels: approved, lgtm, size/XS

#3247 Automated cherry pick of #3230: gpu mutil attach by model type, fix network hint name
  pkg/compute/models/guest_actions.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/networks.go
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: approved, lgtm, size/M

#3249 Automated cherry pick of #3240: qcloud elb bugfix
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
Labels: approved, lgtm, size/L

#3240 qcloud elb bugfix
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
Labels: approved, area/region, lgtm, size/L

#3243 Automated cherry pick of #3241: fix: the input parameters is wrong when create snapshotpolicy with repeatweekday Sunday for qcloud.
  pkg/compute/models/snapshotpolicy.go
  pkg/multicloud/qcloud/snapshot_policy.go
Labels: approved, lgtm, size/XS

#3231 fix: 避免删除azure eip失败
  pkg/multicloud/azure/eip.go
Labels: approved, area/region, lgtm, size/XS

#3248 Automated cherry pick of #3240: qcloud elb bugfix
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
Labels: approved, lgtm, size/L

#3232 Automated cherry pick of #3231: fix: 避免删除azure失败
  pkg/multicloud/azure/eip.go
Labels: approved, lgtm, size/XS

#3187 fix: 创建云账号时指定tenant生效
  docs/schemas/cloudaccount.yaml
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/zstack/provider/provider.go
Labels: approved, area/region, lgtm, size/L

#3251 Automated cherry pick of #3187: fix: 创建云账号时指定tenant生效
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/zstack/provider/provider.go
Labels: approved, lgtm, size/L

#3250 Automated cherry pick of #3187: fix: 创建云账号时指定tenant生效
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/zstack/provider/provider.go
Labels: approved, lgtm

#3253 baremetal: fix stop task hang
  pkg/baremetal/tasks/stop.go
Labels: area/baremetal, size/S

#3254 Automated cherry pick of #3253: baremetal: fix stop task hang
  pkg/baremetal/tasks/stop.go
Labels: size/S

#3256 Automated cherry pick of #3253: baremetal: fix stop task hang
  pkg/baremetal/tasks/stop.go
Labels: size/S

#3255 Automated cherry pick of #3253: baremetal: fix stop task hang
  pkg/baremetal/tasks/stop.go
Labels: size/S

#3252 fix: [github scripts] make sure label exists after send comment
  scripts/approve.sh
Labels: area/util, size/M

#3264 fix: 避免返回nil, nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/region, lgtm, size/XS

#3266 Automated cherry pick of #3264: fix: 避免返回nil, nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#3267 Automated cherry pick of #3264: fix: 避免返回nil, nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm

#3265 Automated cherry pick of #3264: fix: 避免返回nil, nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#3271 region: capability public network count filter by host type
  pkg/compute/models/capabilities.go
Labels: area/region, size/S

#3272 Automated cherry pick of #3271: region: capability public network count filter by host type
  pkg/compute/models/capabilities.go
Labels: size/S

#3273 Automated cherry pick of #3271: region: capability public network count filter by host type
  pkg/compute/models/capabilities.go
Labels: size/S

#3235 Feature: Unforced Instance Group
  cmd/climc/shell/instance_group.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/mcclient/modules/mod_instance_group.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/core/context.go
  pkg/scheduler/core/generic_scheduler.go
Labels: area/region, area/scheduler, size/L

#3274 Automated cherry pick of #3235: Feature: Unforced Group which prioritize scheduling guest to host with enough resources of InstanceGroup and then to host even if this hosts has no enough resources. Add groups desc in SGuest.ToSchedDesc. The backup guest also occupies InstanceGroup resources now.
  cmd/climc/shell/instance_group.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/mcclient/modules/mod_instance_group.go
  pkg/scheduler/algorithm/predicates/instance_group_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/core/context.go
  pkg/scheduler/core/generic_scheduler.go
Labels: size/L

#3280 Automated cherry pick of #3278: region: fix get disk detail panic
  pkg/compute/models/disks.go
Labels: size/XS

#3279 Automated cherry pick of #3278: region: fix get disk detail panic
  pkg/compute/models/disks.go
Labels: size/XS

#3270 bugfix: fix reserved memory is zero
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: approved, area/host, lgtm, size/XS
