Repository yunionio/cloudpods, pull requests merged in 2019-03, with the labels that each got.

#16 ucloud add method GetSecurityGroupIds
  pkg/compute/models/skus.go
  pkg/util/ucloud/instance.go
Labels: bug, feature

#18 server list order by host name
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: feature

#39 remove guest secgroup rule detail
  pkg/compute/models/secgroups.go
Labels: needs-backport

#40 fixed an issue where waiting times were too long due to a lack of ref…
  pkg/compute/guestdrivers/managedvirtual.go
Labels: needs-backport

#44 fixed security group name duplication that prevented instance from fi…
  pkg/compute/models/guests.go
Labels: needs-work

#52 cloud provider update status should clear scheduler cache
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/guests.go
Labels: needs-backport

#74 vm clone
  cmd/climc/shell/servers.go
  pkg/apis/compute/api.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_clone_task.go
  pkg/compute/tasks/schedule.go
  pkg/mcclient/options/servers.go
Labels: feature

#76 避免绑定秘钥失败后机器还关联着秘钥
  pkg/compute/tasks/guest_deploy_task.go
Labels: needs-backport

#103 fix guests.go format error on master
  pkg/compute/models/guests.go
Labels: bug

#89 避免续费时未刷新虚拟机状态
  pkg/apis/compute/guest_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_renew_task.go
  pkg/util/logclient/logclient.go
Labels: needs-backport

#108 fix storage commit rate
  pkg/compute/models/hosts.go
Labels: bug
