Repository yunionio/cloudpods, pull requests merged in 2019-12, with the labels that each got.

#3979 feat(region): Add suspend feature for vmware guest
  pkg/compute/guestdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/M

#3981 Automated cherry pick of #3979: feat(region): Add suspend feature for vmware guest
  pkg/compute/guestdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#3983 Automated cherry pick of #3979: feat(region): Add suspend feature for vmware guest
  pkg/compute/guestdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#3980 Automated cherry pick of #3979: feat(region): Add suspend feature for vmware guest
  pkg/compute/guestdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#3989 fix: avoid index out of range
  pkg/compute/models/disks.go
Labels: approved, area/region, lgtm, size/XS

#3991 Automated cherry pick of #3989: fix: avoid index out of range
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/XS

#3990 Automated cherry pick of #3989: fix: avoid index out of range
  pkg/compute/models/disks.go
Labels: approved, lgtm, size/XS

#3978 cloudnet: fix router rules
  pkg/cloudnet/models/routes.go
  pkg/cloudnet/models/rules.go
  pkg/mcclient/options/cloudnet/rules.go
Labels: approved, area/region, lgtm, size/S

#3984 Automated cherry pick of #3978: cloudnet: fix validating "action"
  pkg/cloudnet/models/routes.go
  pkg/cloudnet/models/rules.go
  pkg/mcclient/options/cloudnet/rules.go
Labels: approved, lgtm, size/S

#4004 fix: 忽略名称条件，只要cpu,mem一致就不再同步
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/XS

#4006 Automated cherry pick of #4004: fix: 忽略名称条件，只要cpu,mem一致就不再同步
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#4009 fix: 未设置密码时，使用随机密码
  pkg/compute/models/dbinstance_accounts.go
Labels: approved, area/region, lgtm, size/XS

#4011 Automated cherry pick of #4009: fix: 未设置密码时，使用随机密码
  pkg/compute/models/dbinstance_accounts.go
Labels: approved, lgtm, size/XS

#3994 fix: 避免每次重启region同步rds sku, 避免新加公有云账号未能及时同步sku问题
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
Labels: approved, area/region, lgtm, size/S

#3996 Automated cherry pick of #3994: fix: 避免每次重启region同步rds sku, 避免新加公有云账号未能及时同步sku问题
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
Labels: approved, lgtm, size/S

#4013 fix: network-addresses add created_at column
  pkg/apis/compute/network_const.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#4014 Automated cherry pick of #4013: fix: network-addresses add created_at column
  pkg/apis/compute/network_const.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#3982 Automated cherry pick of #3978: cloudnet: fix validating "action"
  pkg/cloudnet/models/routes.go
  pkg/cloudnet/models/rules.go
  pkg/mcclient/options/cloudnet/rules.go
Labels: approved, lgtm, size/S

#3995 Automated cherry pick of #3994: fix: 避免每次重启region同步rds sku, 避免新加公有云账号未能及时同步sku问题
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
Labels: approved, lgtm, size/S

#4005 Automated cherry pick of #4004: fix: 忽略名称条件，只要cpu,mem一致就不再同步
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#4010 Automated cherry pick of #4009: fix: 未设置密码时，使用随机密码
  pkg/compute/models/dbinstance_accounts.go
Labels: approved, lgtm, size/XS

#4007 更改获取监控信息的参数单位
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/huawei/client/modules/mod_ces.go
Labels: approved, area/climc, lgtm, size/XS

#4012 Automated cherry pick of #4007: 更改aliyun和huawei的获取监控信息的参数单位：微秒=>毫秒
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/huawei/client/modules/mod_ces.go
Labels: approved, lgtm, size/XS

#4015 Automated cherry pick of #4013: fix: network-addresses add created_at column
  pkg/apis/compute/network_const.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4020 Automated cherry pick of #4016: hostman: hostinfo: turn off report_ignored_msrs
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#4016 hostman: hostinfo: turn off report_ignored_msrs
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, area/host, lgtm, size/XS

#4018 Automated cherry pick of #4016: hostman: hostinfo: turn off report_ignored_msrs
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#4019 Automated cherry pick of #4016: hostman: hostinfo: turn off report_ignored_msrs
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#4017 Automated cherry pick of #4016: hostman: hostinfo: turn off report_ignored_msrs
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#3999 Bugfix/tb bugfix 120201
  pkg/compute/models/cloudregions.go
  pkg/compute/models/skus_tools.go
  pkg/multicloud/huawei/disk.go
Labels: approved, area/region, lgtm, size/M

#4001 Automated cherry pick of #3999: cloudregion cities filter
  pkg/compute/models/cloudregions.go
  pkg/compute/models/skus_tools.go
  pkg/multicloud/huawei/disk.go
Labels: approved, lgtm, size/M

#4000 Automated cherry pick of #3999: cloudregion cities filter
  pkg/compute/models/cloudregions.go
  pkg/compute/models/skus_tools.go
  pkg/multicloud/huawei/disk.go
Labels: approved, lgtm, size/M

#4021 bugfix: add socket check of deploy server
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, area/host, lgtm, size/XS

#4025 Automated cherry pick of #4021: add socket used check of deploy server
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/XS

#4023 Automated cherry pick of #4021: add socket used check of deploy server
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/XS

#4024 Automated cherry pick of #4021: add socket used check of deploy server
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/XS

#3992 fix: 标签添加排序,不统计回收站的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, area/region, lgtm, size/XS

#3993 Automated cherry pick of #3992: fix: 标签添加排序,不统计回收站的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, lgtm, size/XS

#4022 Automated cherry pick of #4021: add socket used check of deploy server
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/XS

#3988 fix: 结构化network create list 参数
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/network.go
  pkg/apis/compute/schedtag.go
  pkg/apis/modelbase.go
  pkg/apis/parameters.go
  pkg/apis/sharablevirtualresource.go
  pkg/apis/standaloneresource.go
  pkg/apis/virtualresource.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/schedtags.go
  pkg/compute/models/vpcs.go
Labels: approved, area/region, lgtm, size/XXL

#4002 fix(region): The param of list instancegroup filter by Guest is 'server'
  cmd/climc/shell/instance_group.go
  pkg/apis/compute/instance_group.go
  pkg/compute/models/groups.go
Labels: approved, area/region, lgtm, size/XS

#4031 Automated cherry pick of #3988: fix: 结构化network create list 参数
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/network.go
  pkg/apis/compute/schedtag.go
  pkg/apis/modelbase.go
  pkg/apis/parameters.go
  pkg/apis/sharablevirtualresource.go
  pkg/apis/standaloneresource.go
  pkg/apis/virtualresource.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/schedtags.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/XXL

#4003 Automated cherry pick of #4002: fix(region): The param of list instancegroup filter by Guest is 'server'
  cmd/climc/shell/instance_group.go
  pkg/apis/compute/instance_group.go
  pkg/compute/models/groups.go
Labels: approved, lgtm, size/XS

#4028 Feature/tb redis 1203
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/elasticcache_account_create_task.go
  pkg/compute/tasks/elasticcache_acl_create_task.go
  pkg/compute/tasks/elasticcache_acl_delete_task.go
  pkg/compute/tasks/elasticcache_acl_update_task.go
  pkg/compute/tasks/elasticcache_backup_create_task.go
  pkg/compute/tasks/elasticcache_parameter_update_task.go
  pkg/multicloud/huawei/elasticcache_acl.go
Labels: approved, area/region, lgtm, size/L

#4029 Automated cherry pick of #4028: huawei reset password bugfix
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/elasticcache_account_create_task.go
  pkg/compute/tasks/elasticcache_acl_create_task.go
  pkg/compute/tasks/elasticcache_acl_delete_task.go
  pkg/compute/tasks/elasticcache_acl_update_task.go
  pkg/compute/tasks/elasticcache_backup_create_task.go
  pkg/compute/tasks/elasticcache_parameter_update_task.go
  pkg/multicloud/huawei/elasticcache_acl.go
Labels: approved, lgtm, size/L

#4032 image upload bugfix
  pkg/multicloud/aws/image.go
Labels: approved, area/region, lgtm, size/M

#4034 Automated cherry pick of #4032: image upload bugfix
  pkg/multicloud/aws/image.go
Labels: approved, lgtm, size/M

#4033 Automated cherry pick of #4032: image upload bugfix
  pkg/multicloud/aws/image.go
Labels: approved, lgtm, size/M

#4030 Automated cherry pick of #4028: huawei reset password bugfix
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/elasticcache_account_create_task.go
  pkg/compute/tasks/elasticcache_acl_create_task.go
  pkg/compute/tasks/elasticcache_acl_delete_task.go
  pkg/compute/tasks/elasticcache_acl_update_task.go
  pkg/compute/tasks/elasticcache_backup_create_task.go
  pkg/compute/tasks/elasticcache_parameter_update_task.go
  pkg/multicloud/huawei/elasticcache_acl.go
Labels: size/L

#4035 fix: 避免普通用户添加规则到系统安全组
  pkg/compute/models/secgrouprules.go
Labels: approved, area/region, lgtm, size/M

#4038 Automated cherry pick of #4035: fix: 避免普通用户添加规则到系统安全组
  pkg/compute/models/secgrouprules.go
Labels: approved, lgtm, size/M

#4037 Automated cherry pick of #4035: fix: 避免普通用户添加规则到系统安全组
  pkg/compute/models/secgrouprules.go
Labels: approved, lgtm, size/M

#4047 region misc bugfix
  pkg/compute/guestdrivers/base.go
  pkg/compute/models/capabilities.go
  pkg/compute/tasks/guest_reset_task.go
  pkg/compute/tasks/guest_start_task.go
Labels: approved, area/region, lgtm, size/L

#4049 Automated cherry pick of #4047: region misc bugfix
  pkg/compute/guestdrivers/base.go
  pkg/compute/tasks/guest_reset_task.go
  pkg/compute/tasks/guest_start_task.go
Labels: approved, lgtm, size/XS

#4040 fix: 返回region external_id
  pkg/compute/models/cloudregionresource.go
Labels: approved, area/region, lgtm, size/XS

#4043 Automated cherry pick of #4040: fix: 返回region external_id
  pkg/compute/models/cloudregionresource.go
Labels: approved, lgtm, size/XS

#4042 Automated cherry pick of #4040: fix: 返回region external_id
  pkg/compute/models/cloudregionresource.go
Labels: approved, lgtm, size/XS

#4048 Automated cherry pick of #4047: region misc bugfix
  pkg/compute/guestdrivers/base.go
  pkg/compute/models/capabilities.go
  pkg/compute/tasks/guest_reset_task.go
  pkg/compute/tasks/guest_start_task.go
Labels: approved, lgtm, size/L

#4036 Automated cherry pick of #4035: fix: 避免普通用户添加规则到系统安全组
  pkg/compute/models/secgrouprules.go
Labels: approved, lgtm, size/M

#4057 fix: 避免在初始化model时设置rds sku handler
  pkg/compute/models/dbinstance_skus.go
Labels: approved, area/region, lgtm, size/XS

#4059 Automated cherry pick of #4057: fix: 避免在初始化model时设置rds skuhandler
  pkg/compute/models/dbinstance_skus.go
Labels: approved, lgtm, size/XS

#3997 feature: host container deployment
  build/executor-server/root/usr/lib/systemd/system/yunion-executor.service
  build/executor-server/vars
  cmd/climc/shell/pprof.go
  cmd/executor-server/main.go
  go.mod
  go.sum
  pkg/baremetal/manager.go
  pkg/baremetal/utils/ipmitool/ipmitool.go
  pkg/cloudcommon/service/services.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/fsutils.go
  pkg/hostman/diskutils/lvmutils.go
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/localfs.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/options.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostbridge/linux_bridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/system_service/system_service.go
  pkg/hostman/system_service/systemd.go
  pkg/hostman/system_service/sysv.go
  pkg/util/cgrouputils/cgrouputils.go
  pkg/util/fileutils2/blkid.go
  pkg/util/fileutils2/fileutils.go
  pkg/util/fuseutils/fuseutils.go
  pkg/util/netutils2/netutils.go
  pkg/util/ovsutils/ovsutils.go
  pkg/util/procutils/executor.go
  pkg/util/procutils/procutils.go
  pkg/util/qemuimg/init.go
  pkg/util/qemuimg/qemuimg.go
  pkg/util/sysutils/hostname.go
  pkg/util/sysutils/kvm.go
  pkg/util/tarutils/tarutils.go
  pkg/util/timeutils2/timeutils.go
  pkg/util/winutils/winutils.go
  vendor/modules.txt
  vendor/yunion.io/x/executor/apis/executor.pb.go
  vendor/yunion.io/x/executor/apis/executor.proto
  vendor/yunion.io/x/executor/client/client.go
  vendor/yunion.io/x/executor/server/server.go
Labels: area/host, lgtm, size/XXL

#4045 feat(region): Support for resuming vm suspended in vmware
  cmd/climc/shell/servers.go
  pkg/apis/compute/guest_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_resume_task.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/L

#3805 feature: Guest Template & Service Catalog
  cmd/climc/shell/guest_template.go
  cmd/climc/shell/service_catalog.go
  pkg/apis/compute/guesttemplate.go
  pkg/apis/compute/service_compute.go
  pkg/apis/compute/zz_generated.model.go
  pkg/cloudprovider/images.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/guests.go
  pkg/compute/models/service_catalog.go
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/mod_guesttemplate.go
  pkg/mcclient/modules/mod_servicecatalog.go
  pkg/mcclient/options/servers.go
Labels: area/region, size/XXL

#4061 Automated cherry pick of #3805: feat(region): Add Guest Template & Service Catalog
  cmd/climc/shell/guest_template.go
  cmd/climc/shell/service_catalog.go
  pkg/apis/compute/guesttemplate.go
  pkg/apis/compute/service_compute.go
  pkg/apis/compute/zz_generated.model.go
  pkg/cloudprovider/images.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/guests.go
  pkg/compute/models/service_catalog.go
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/mod_guesttemplate.go
  pkg/mcclient/modules/mod_servicecatalog.go
  pkg/mcclient/options/servers.go
Labels: size/XXL

#4046 Automated cherry pick of #4045: feat(region): Support for resuming vm suspended in vmware
  cmd/climc/shell/servers.go
  pkg/apis/compute/guest_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_resume_task.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#4058 Automated cherry pick of #4057: fix: 避免在初始化model时设置rds skuhandler
  pkg/compute/models/dbinstance_skus.go
Labels: approved, lgtm, size/XS

#4008 fix: 安全组同步优化,避免规则不同的安全组可以合并
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: area/region, lgtm, size/L

#4060 Automated cherry pick of #4008: fix: 安全组同步优化,避免规则不同的安全组可以合并
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/L

#3998 feature: add bundle libraries script for build host image
  build/docker/Dockerfile.host
  build/docker/Dockerfile.host-deployer
  scripts/bundle-libraries.sh
  scripts/docker_push.sh
Labels: size/L

#4062 bugfix: fix docker push script component name
  scripts/docker_push.sh
Labels: needs-area, size/XS

#4064 fix: host-cache-image might not work
  pkg/compute/models/hosts.go
Labels: area/region, size/S

#4077 Automated cherry pick of #4064: fix: host-cache-image might not work
  pkg/compute/models/hosts.go
Labels: size/S

#4078 Automated cherry pick of #4067: fix(region): Guest template & Service catalog
  pkg/apis/compute/guesttemplate.go
  pkg/apis/compute/service_catalog.go
  pkg/apis/sharablevirtualresource.go
  pkg/apis/standaloneresource.go
  pkg/apis/virtualresource.go
  pkg/compute/models/guest_template.go
Labels: size/M

#4067 fix(region): Guest template & Service catalog
  pkg/apis/compute/guesttemplate.go
  pkg/apis/compute/service_catalog.go
  pkg/apis/sharablevirtualresource.go
  pkg/apis/standaloneresource.go
  pkg/apis/virtualresource.go
  pkg/compute/models/guest_template.go
Labels: area/region, size/M

#4079 fix(region): Fix the list bug of Guest Template
  pkg/apis/compute/guesttemplate.go
  pkg/compute/models/guest_template.go
Labels: needs-area, size/S

#4081 fix: Fix the unexpected json field coverage after GetCustomizeColumns
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/groups.go
Labels: area/region, size/XS

#4082 Automated cherry pick of #4081: fix: Fix the unexpected json field coverage after GetCustomizeColumns
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/groups.go
Labels: size/XS

#4069 Automated cherry pick of #4068: fix: 子订阅更改项目时也同步更新external project项目信息
  pkg/compute/models/external_projects.go
Labels: size/XS

#4070 Automated cherry pick of #4068: fix: 子订阅更改项目时也同步更新external project项目信息
  pkg/compute/models/external_projects.go
Labels: size/XS

#4084 httputils, aliyun: respects env proxy settings
  go.mod
  go.sum
  pkg/multicloud/aliyun/aliyun.go
  pkg/util/httputils/httputils.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/auth.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/bucket.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conf.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conn.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/const.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/download.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/error.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/limit_reader_1_6.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/limit_reader_1_7.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/livechannel.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/mime.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/model.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/multicopy.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/multipart.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/option.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/progress.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/select_object.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/select_object_type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/transport_1_6.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/transport_1_7.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/upload.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/utils.go
  vendor/modules.txt
Labels: area/region, size/XXL

#4085 Automated cherry pick of #4084: httputils: use http.ProxyFromEnvironment by default
  go.mod
  go.sum
  pkg/multicloud/aliyun/aliyun.go
  pkg/util/httputils/httputils.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/auth.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/bucket.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conf.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conn.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/const.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/download.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/error.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/limit_reader_1_6.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/limit_reader_1_7.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/livechannel.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/mime.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/model.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/multicopy.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/multipart.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/option.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/progress.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/select_object.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/select_object_type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/transport_1_6.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/transport_1_7.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/upload.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/utils.go
  vendor/modules.txt
Labels: size/XXL

#4086 Automated cherry pick of #4084: httputils: use http.ProxyFromEnvironment by default
  go.mod
  go.sum
  pkg/multicloud/aliyun/aliyun.go
  pkg/util/httputils/httputils.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/auth.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/bucket.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/client.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conf.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/conn.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/const.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/download.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/error.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/limit_reader_1_6.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/limit_reader_1_7.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/livechannel.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/mime.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/model.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/multicopy.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/multipart.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/option.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/progress.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/select_object.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/select_object_type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/transport_1_6.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/transport_1_7.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/type.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/upload.go
  vendor/github.com/aliyun/aliyun-oss-go-sdk/oss/utils.go
  vendor/modules.txt
Labels: size/XXL

#4053 sync server skus from offline data
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_test.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/skustools.go
  pkg/compute/service/service.go
Labels: area/region, size/XL

#4066 Automated cherry pick of #4053: sync server skus from offline data
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_test.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/skustools.go
  pkg/compute/service/service.go
Labels: size/XL

#4065 fix: 兼容以前的参数
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/network.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
Labels: area/region, size/L

#4071 Automated cherry pick of #4065: fix: 兼容以前的参数
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/network.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
Labels: size/L

#4054 fix: 兼容参数过滤
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
Labels: area/region, size/XS

#4055 Automated cherry pick of #4054: fix: 兼容参数过滤
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
Labels: size/XS

#4088 fix: add hostinfo to storage cached image details
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecaches.go
Labels: approved, lgtm

#4089 Automated cherry pick of #4088: fix: add hostinfo to storage cached image details
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecaches.go
Labels: approved, lgtm

#4072 fix: 导出用户标签不加user:前缀
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XS

#4075 Automated cherry pick of #4072: fix: 导出用户标签不加user:前缀
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#4074 Automated cherry pick of #4072: fix: 导出用户标签不加user:前缀
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#4076 Automated cherry pick of #4072: fix: 导出用户标签不加user:前缀
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#4073 Automated cherry pick of #4072: fix: 导出用户标签不加user:前缀
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#4092 loadbalancerbackends: janitor: move to InitializeData
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerbackends_stales.go
Labels: approved, area/region, lgtm, size/XS

#4096 Automated cherry pick of #4092: loadbalancerbackends: janitor: move to InitializeData
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerbackends_stales.go
Labels: approved, lgtm, size/XS

#4094 Automated cherry pick of #4092: loadbalancerbackends: janitor: move to InitializeData
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerbackends_stales.go
Labels: approved, lgtm, size/XS

#4095 Automated cherry pick of #4092: loadbalancerbackends: janitor: move to InitializeData
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerbackends_stales.go
Labels: approved, lgtm, size/XS

#4104 bugfix: fix image upload log event
  pkg/image/models/images.go
Labels: approved, area/image, lgtm, size/XS

#4107 Automated cherry pick of #4104: fix image upload log event
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#4106 Automated cherry pick of #4104: fix image upload log event
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#4093 Automated cherry pick of #4092: loadbalancerbackends: janitor: move to InitializeData
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerbackends_stales.go
Labels: approved, lgtm, size/XS

#4105 Automated cherry pick of #4104: fix image upload log event
  pkg/image/models/images.go
Labels: approved, lgtm, size/XS

#4097 fix: 避免zstack参数含有中文,未编码导致请求失败
  pkg/multicloud/zstack/cluster.go
  pkg/multicloud/zstack/configuration.go
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/disk_offering.go
  pkg/multicloud/zstack/eip.go
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/image_server.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/network.go
  pkg/multicloud/zstack/network_service.go
  pkg/multicloud/zstack/offering.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/snapshot.go
  pkg/multicloud/zstack/storage.go
  pkg/multicloud/zstack/storage_local.go
  pkg/multicloud/zstack/systag.go
  pkg/multicloud/zstack/vip.go
  pkg/multicloud/zstack/wire.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, area/region, lgtm, size/L

#4101 Automated cherry pick of #4097: fix: 避免zstack参数含有中文,未编码导致请求失败
  pkg/util/zstack/cluster.go
  pkg/util/zstack/configuration.go
  pkg/util/zstack/disk.go
  pkg/util/zstack/disk_offering.go
  pkg/util/zstack/eip.go
  pkg/util/zstack/host.go
  pkg/util/zstack/image.go
  pkg/util/zstack/image_server.go
  pkg/util/zstack/instance.go
  pkg/util/zstack/network.go
  pkg/util/zstack/network_service.go
  pkg/util/zstack/offering.go
  pkg/util/zstack/region.go
  pkg/util/zstack/securitygroup.go
  pkg/util/zstack/snapshot.go
  pkg/util/zstack/storage.go
  pkg/util/zstack/storage_local.go
  pkg/util/zstack/systag.go
  pkg/util/zstack/vip.go
  pkg/util/zstack/wire.go
  pkg/util/zstack/zstack.go
Labels: approved, lgtm, size/L

#4100 Automated cherry pick of #4097: fix: 避免zstack参数含有中文,未编码导致请求失败
  pkg/multicloud/zstack/cluster.go
  pkg/multicloud/zstack/configuration.go
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/disk_offering.go
  pkg/multicloud/zstack/eip.go
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/image_server.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/network.go
  pkg/multicloud/zstack/network_service.go
  pkg/multicloud/zstack/offering.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/snapshot.go
  pkg/multicloud/zstack/storage.go
  pkg/multicloud/zstack/storage_local.go
  pkg/multicloud/zstack/systag.go
  pkg/multicloud/zstack/vip.go
  pkg/multicloud/zstack/wire.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/L

#4099 Automated cherry pick of #4097: fix: 避免zstack参数含有中文,未编码导致请求失败
  pkg/multicloud/zstack/cluster.go
  pkg/multicloud/zstack/configuration.go
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/disk_offering.go
  pkg/multicloud/zstack/eip.go
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/image_server.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/network.go
  pkg/multicloud/zstack/network_service.go
  pkg/multicloud/zstack/offering.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/snapshot.go
  pkg/multicloud/zstack/storage.go
  pkg/multicloud/zstack/storage_local.go
  pkg/multicloud/zstack/systag.go
  pkg/multicloud/zstack/vip.go
  pkg/multicloud/zstack/wire.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/L

#4098 Automated cherry pick of #4097: fix: 避免zstack参数含有中文,未编码导致请求失败
  pkg/multicloud/zstack/cluster.go
  pkg/multicloud/zstack/configuration.go
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/disk_offering.go
  pkg/multicloud/zstack/eip.go
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/image_server.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/network.go
  pkg/multicloud/zstack/network_service.go
  pkg/multicloud/zstack/offering.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
  pkg/multicloud/zstack/snapshot.go
  pkg/multicloud/zstack/storage.go
  pkg/multicloud/zstack/storage_local.go
  pkg/multicloud/zstack/systag.go
  pkg/multicloud/zstack/vip.go
  pkg/multicloud/zstack/wire.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/L

#4109 add associated_bills & modify meter version
  cmd/climc/shell/associated_bills.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_associated_bills.go
Labels: approved, area/climc, lgtm, size/M

#4110 Automated cherry pick of #4109: add associated_bills & modify meter version
  cmd/climc/shell/associated_bills.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_associated_bills.go
Labels: approved, lgtm, size/M

#4111 Automated cherry pick of #4109: add associated_bills & modify meter version
  cmd/climc/shell/associated_bills.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_associated_bills.go
Labels: approved, lgtm, size/M

#4113 delete duplicate param brand
  cmd/climc/shell/associated_bills.go
Labels: approved, lgtm, needs-area, size/XS

#4114 Automated cherry pick of #4113: delete duplicate param brand
  cmd/climc/shell/associated_bills.go
Labels: approved, lgtm, size/XS

#4115 Automated cherry pick of #4113: delete duplicate param brand
  cmd/climc/shell/associated_bills.go
Labels: approved, lgtm, size/XS

#4119 fix: 1. image-quota-list 404 not found 2. usage nil pointer panic
  cmd/climc/shell/quotas.go
  pkg/compute/models/filters.go
  pkg/compute/usages/handler.go
  pkg/mcclient/modules/mod_quotas.go
Labels: approved, area/region, lgtm, size/M

#4120 Automated cherry pick of #4119: fix: 1. image-quota-list 404 not found 2. usage nil pointer panic
  cmd/climc/shell/quotas.go
  pkg/compute/models/filters.go
  pkg/compute/usages/handler.go
  pkg/mcclient/modules/mod_quotas.go
Labels: approved, lgtm, size/M

#4116 bugfix:fix baremetal register get service url
  pkg/compute/models/hosts.go
  pkg/mcclient/auth/auth.go
Labels: approved, area/region, lgtm, size/XS

#4121 fix: 避免污染cloud_env参数
  pkg/compute/models/cloudregions.go
Labels: approved, area/region, lgtm, size/XS

#4122 Automated cherry pick of #4121: fix: 避免污染cloud_env参数
  pkg/compute/models/cloudregions.go
Labels: approved, lgtm, size/XS

#4129 fix: 避免插入时出现duplicate primary key error
  pkg/cloudcommon/db/tenantcache.go
Labels: approved, area/region, lgtm, size/XS

#4133 Automated cherry pick of #4129: fix: 避免插入时出现duplicate primary key error
  pkg/cloudcommon/db/tenantcache.go
Labels: approved, lgtm, size/XS

#4131 Automated cherry pick of #4129: fix: 避免插入时出现duplicate primary key error
  pkg/cloudcommon/db/tenantcache.go
Labels: approved, lgtm, size/XS

#4132 Automated cherry pick of #4129: fix: 避免插入时出现duplicate primary key error
  pkg/cloudcommon/db/tenantcache.go
Labels: approved, lgtm, size/XS

#4130 Automated cherry pick of #4129: fix: 避免插入时出现duplicate primary key error
  pkg/cloudcommon/db/tenantcache.go
Labels: approved, lgtm, size/XS

#4123 guestnetworks: check ifname uniqueness across different networks
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/M

#4127 Automated cherry pick of #4123: guestnetworks: check ifname uniqueness across different networks
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#4125 Automated cherry pick of #4123: guestnetworks: check ifname uniqueness across different networks
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#4126 Automated cherry pick of #4123: guestnetworks: check ifname uniqueness across different networks
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#4124 Automated cherry pick of #4123: guestnetworks: check ifname uniqueness across different networks
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#4134 fix: misc esxi bugfix 20191213
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: approved, area/region, lgtm, size/S

#4136 Automated cherry pick of #4134: fix: misc bugfix for esxi 20191213
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/S

#4137 Automated cherry pick of #4134: fix: misc bugfix for esxi 20191213
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/S

#4135 Automated cherry pick of #4134: fix: misc bugfix for esxi 20191213
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/S

#4138 Automated cherry pick of #4134: fix: misc bugfix for esxi 20191213
  pkg/util/esxi/datacenter.go
  pkg/util/esxi/host.go
  pkg/util/esxi/manager.go
Labels: approved, lgtm, size/S

#4140 Automated cherry pick of #4139: fix: init quota with negative value and negative quota means unlimited
  pkg/cloudcommon/db/quotas/utils.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
  pkg/image/models/quotas.go
Labels: approved, lgtm, size/L

#4139 fix: init quota with negative value and negative quota means unlimited
  pkg/cloudcommon/db/quotas/utils.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
  pkg/image/models/quotas.go
Labels: approved, area/region, lgtm, size/L

#4146 region: fix schedule input project and domain missing
  pkg/apis/compute/api.go
  pkg/cloudcommon/cmdline/helper.go
Labels: approved, area/region, lgtm, size/S

#4147 Automated cherry pick of #4146: region: fix schedule input project and domain missing
  pkg/apis/compute/api.go
  pkg/cloudcommon/cmdline/helper.go
Labels: approved, lgtm, size/S

#4150 hotfix: update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: approved, area/region, lgtm, size/S

#4151 Automated cherry pick of #4150: hotfix: update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: approved, lgtm, size/S

#4148 fix: image quota key type mismatch
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: approved, area/image, lgtm, size/S

#4149 Automated cherry pick of #4148: fix: image quota key type mismatch
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: approved, lgtm, size/S

#4159 fix: 增强host-list --usable限制
  pkg/compute/models/hosts.go
Labels: approved, area/region, lgtm, size/XS

#4161 Automated cherry pick of #4159: fix: 增强host-list --usable限制
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/XS

#4160 Automated cherry pick of #4159: fix: 增强host-list --usable限制
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/XS

#4141 huawei sync instance offset bugfix
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/utils.go
Labels: approved, area/region, lgtm, size/S

#4145 Automated cherry pick of #4141: huawei sync instance offset bugfix
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/utils.go
Labels: approved, lgtm, size/S

#4143 Automated cherry pick of #4141: huawei sync instance offset bugfix
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/utils.go
Labels: approved, lgtm, size/S
