Repository yunionio/cloudpods, pull requests merged in 2019-08, with the labels that each got.

#2057 fix: server-list add is_prepaid_recycle field
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/S

#2058 Automated cherry pick of #2057: fix: server-list add is_prepaid_recycle field
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#2059 Automated cherry pick of #2057: fix: server-list add is_prepaid_recycle field
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#2072 bugfix: remove host rpm require
  build/host/vars
Labels: approved, area/host, lgtm, size/XS

#2073 Automated cherry pick of #2072: remove host rpm requre
  build/host/vars
Labels: approved, lgtm, size/XS

#2074 Automated cherry pick of #2072: remove host rpm requre
  build/host/vars
Labels: approved, lgtm, size/XS

#2051 fix: 1. project quota-list not include domain quota 2. do not check
  pkg/cloudcommon/db/quotas/handler.go
  pkg/keystone/models/policies.go
Labels: approved, area/keystone, lgtm, size/L

#2053 Automated cherry pick of #2051: fix: 1. project quota-list not include domain quota 2. do not check conformance between project and domain quota
  pkg/cloudcommon/db/quotas/handler.go
  pkg/keystone/models/policies.go
Labels: approved, lgtm, size/L

#2055 Automated cherry pick of #2051: fix: 1. project quota-list not include domain quota 2. do not check conformance between project and domain quota
  pkg/cloudcommon/db/quotas/handler.go
  pkg/keystone/models/policies.go
Labels: approved, lgtm, size/L

#2048 fix: openstack glance image-list not list all images
  pkg/multicloud/openstack/disk.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/network.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/vpc.go
Labels: approved, area/region, lgtm, size/L

#2052 Automated cherry pick of #2048: fix: openstack glance image-list not list all images
  pkg/util/openstack/disk.go
  pkg/util/openstack/flavor.go
  pkg/util/openstack/image.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/network.go
  pkg/util/openstack/openstack.go
  pkg/util/openstack/port.go
  pkg/util/openstack/securitygroup.go
  pkg/util/openstack/vpc.go
Labels: approved, lgtm, size/L

#2049 Automated cherry pick of #2048: fix: openstack glance image-list not list all images
  pkg/multicloud/openstack/disk.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/network.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/vpc.go
Labels: approved, lgtm, size/L

#2050 Automated cherry pick of #2048: fix: openstack glance image-list not list all images
  pkg/util/openstack/disk.go
  pkg/util/openstack/eip.go
  pkg/util/openstack/flavor.go
  pkg/util/openstack/image.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/network.go
  pkg/util/openstack/openstack.go
  pkg/util/openstack/port.go
  pkg/util/openstack/securitygroup.go
  pkg/util/openstack/vpc.go
Labels: approved, lgtm, size/L

#2054 Automated cherry pick of #2048: fix: openstack glance image-list not list all images
  pkg/util/openstack/disk.go
  pkg/util/openstack/flavor.go
  pkg/util/openstack/image.go
  pkg/util/openstack/instance.go
  pkg/util/openstack/network.go
  pkg/util/openstack/openstack.go
  pkg/util/openstack/securitygroup.go
  pkg/util/openstack/vpc.go
Labels: approved, lgtm, size/L

#2063 Automated cherry pick of #2056: add: add brand field for server-sku-list
  docs/schemas/serversku.yaml
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#2056 add: add brand field for server-sku-list
  docs/schemas/serversku.yaml
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/S

#2065 Automated cherry pick of #2064: hotfix: change params from order_by_cache=asc|desc to order_by=cache & order=asc|desc
  cmd/climc/shell/secgroups.go
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/M

#2064 hotfix: change params from order_by_cache=asc|desc to order_by=cache …
  cmd/climc/shell/secgroups.go
  pkg/compute/models/secgroups.go
Labels: approved, area/region, lgtm, size/M

#2066 Automated cherry pick of #2064: hotfix: change params from order_by_cache=asc|desc to order_by=cache & order=asc|desc
  cmd/climc/shell/secgroups.go
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/M

#2067 fix: zstack create tcp udp secgroup rule error
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, area/region, lgtm, size/XS

#2068 Automated cherry pick of #2067: fix: zstack create tcp udp secgroup rule error
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#2069 Automated cherry pick of #2067: fix: zstack create tcp udp secgroup rule error
  pkg/util/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#2076 add: cloudaccount api docs
  docs/cloudaccount/change-project.yaml
  docs/cloudaccount/cloudaccount.yaml
  docs/cloudaccount/cloudaccounts.yaml
  docs/cloudaccount/disable-auto-sync.yaml
  docs/cloudaccount/disable.yaml
  docs/cloudaccount/enable-auto-sync.yaml
  docs/cloudaccount/enable.yaml
  docs/cloudaccount/private.yaml
  docs/cloudaccount/public.yaml
  docs/cloudaccount/sync.yaml
  docs/cloudaccount/update-credential.yaml
  docs/image/image.yaml
  docs/index.yaml
  docs/parameters/cloudaccount.yaml
  docs/schemas/cloudaccount.yaml
  docs/schemas/common.yaml
Labels: approved, area/docs, lgtm, size/XL

#2080 Automated cherry pick of #2079: fix: cloudaccount and cloudprovider not in same domain
  pkg/compute/models/cloudproviders.go
Labels: approved, lgtm, size/S

#2079 fix: cloudaccount and cloudprovider not in same domain
  pkg/compute/models/cloudproviders.go
Labels: approved, area/region, lgtm, size/S

#2081 Automated cherry pick of #2079: fix: cloudaccount and cloudprovider not in same domain
  pkg/compute/models/cloudproviders.go
Labels: approved, lgtm, size/S

#2060 feature: support get model distinct field
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/vpcs.go
Labels: approved, area/region, lgtm, size/L

#2077 Automated cherry pick of #2060: support get model distinct field
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/L

#2078 Automated cherry pick of #2060: support get model distinct field
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/L

#2089 ansibleserver: 操作宿主机时默认使用用户root
  pkg/ansibleserver/models/ansibleplaybooks_validator.go
Labels: approved, area/region, lgtm, size/XS

#2090 Automated cherry pick of #2089: ansibleserver: 操作宿主机时默认使用用户root
  pkg/ansibleserver/models/ansibleplaybooks_validator.go
Labels: approved, lgtm, size/XS

#2091 Automated cherry pick of #2089: ansibleserver: 操作宿主机时默认使用用户root
  pkg/ansibleserver/models/ansibleplaybooks_validator.go
Labels: approved, lgtm, size/XS

#2083 Automated cherry pick of #2082: fix: get openstack all customize storage type
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/M

#2084 Automated cherry pick of #2082: fix: get openstack all customize storage type
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/M

#2085 Automated cherry pick of #2082: fix: get openstack all customize storage type
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/M

#2082 fix: get openstack all customize storage type
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/storages.go
Labels: approved, area/region, lgtm, size/M

#2086 Automated cherry pick of #2082: fix: get openstack all customize storage type
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/M

#2092 hotfix: add networkinterface docs
  cmd/climc/shell/networkinterfacenetworks.go
  docs/index.yaml
  docs/network/networkinterface.yaml
  docs/networkinterface/networkinterface.yaml
  docs/networkinterface/networkinterfaces.yaml
  docs/networkinterface/networks.yaml
  docs/networkinterfacenetwork/networkinterfacenetworks.yaml
  docs/parameters/networkinterface.yaml
  docs/schemas/networkinterface.yaml
  docs/schemas/networkinterfacenetwork.yaml
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/mod_networkinterfacenetworks.go
Labels: approved, area/docs, area/region, lgtm, size/L

#2093 Automated cherry pick of #2092: hotfix: add networkinterface docs
  cmd/climc/shell/networkinterfacenetworks.go
  docs/index.yaml
  docs/network/networkinterface.yaml
  docs/networkinterface/networkinterface.yaml
  docs/networkinterface/networkinterfaces.yaml
  docs/networkinterface/networks.yaml
  docs/networkinterfacenetwork/networkinterfacenetworks.yaml
  docs/parameters/networkinterface.yaml
  docs/schemas/networkinterface.yaml
  docs/schemas/networkinterfacenetwork.yaml
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/mod_networkinterfacenetworks.go
Labels: approved, lgtm, size/L

#2095 Automated cherry pick of #2094: hotfix: change order_by=guest -> order_by=guest_cnt
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/XS

#2096 Automated cherry pick of #2094: hotfix: change order_by=guest -> order_by=guest_cnt
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/XS

#2094 hotfix: change order_by=guest -> order_by=guest_cnt
  pkg/compute/models/secgroups.go
Labels: approved, area/region, lgtm, size/XS

#2098 Automated cherry pick of #2097: secgroups get distinct tenant
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#2097 feature: secgroups get distinct tenant
  pkg/compute/models/secgroups.go
Labels: approved, area/region, lgtm, size/S

#2099 Automated cherry pick of #2097: secgroups get distinct tenant
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#2100 huawei & elb bugfix
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/ucloud/securitygroup.go
Labels: approved, area/region, lgtm, size/M

#2101 Automated cherry pick of #2100: huawei & elb bugfix
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/aws.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/ucloud/securitygroup.go
Labels: approved, area/region, lgtm, size/M

#2075 nat create delete restful api finished
  cmd/climc/shell/natdtable.go
  cmd/climc/shell/natdtables.go
  cmd/climc/shell/natgateways.go
  cmd/climc/shell/natstable.go
  cmd/climc/shell/natstables.go
  docs/index.yaml
  docs/natgateway/dnatentries.yaml
  docs/natgateway/dnatentry.yaml
  docs/natgateway/dtable.yaml
  docs/natgateway/dtables.yaml
  docs/natgateway/natgateway.yaml
  docs/natgateway/natgateways.yaml
  docs/natgateway/snatentries.yaml
  docs/natgateway/snatentry.yaml
  docs/natgateway/stable.yaml
  docs/natgateway/stables.yaml
  docs/parameters/natgateway.yaml
  docs/schemas/natgateway.yaml
  go.sum
  pkg/apis/compute/natgateway.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/mcclient/modules/mod_natdtables.go
  pkg/mcclient/modules/mod_natstables.go
  pkg/mcclient/options/natgateways.go
Labels: approved, area/region, lgtm, size/XXL

#2113 Automated cherry pick of #2075: nat create delete restful api finished
  cmd/climc/shell/natdtable.go
  cmd/climc/shell/natdtables.go
  cmd/climc/shell/natgateways.go
  cmd/climc/shell/natstable.go
  cmd/climc/shell/natstables.go
  docs/index.yaml
  docs/natgateway/dnatentries.yaml
  docs/natgateway/dnatentry.yaml
  docs/natgateway/dtable.yaml
  docs/natgateway/dtables.yaml
  docs/natgateway/natgateway.yaml
  docs/natgateway/natgateways.yaml
  docs/natgateway/snatentries.yaml
  docs/natgateway/snatentry.yaml
  docs/natgateway/stable.yaml
  docs/natgateway/stables.yaml
  docs/parameters/natgateway.yaml
  docs/schemas/natgateway.yaml
  go.sum
  pkg/apis/compute/natgateway.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/mcclient/modules/mod_natdtables.go
  pkg/mcclient/modules/mod_natstables.go
  pkg/mcclient/options/natgateways.go
Labels: approved, lgtm, size/XXL

#2088 Automated cherry pick of #2087: aliyun&huawei redis sync support
  pkg/apis/compute/elasticcache_const.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/cloudsyncelasticcache.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticcache_parameters.go
  pkg/compute/models/purge.go
  pkg/compute/models/skus.go
  pkg/compute/service/handlers.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/elasticcache_account.go
  pkg/multicloud/aliyun/elasticcache_acl.go
  pkg/multicloud/aliyun/elasticcache_backup.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/elasticcache_parameter.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/elasticcache.go
  pkg/multicloud/aliyun/utils.go
  pkg/multicloud/elasticcache_base.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_elasticcache.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/elasticcache_backup.go
  pkg/multicloud/huawei/elasticcache_instance.go
  pkg/multicloud/huawei/elasticcache_parameter.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/elasticcache.go
  pkg/multicloud/region_base.go
Labels: approved, lgtm, size/XXL

#2110 Automated cherry pick of #2109: lbclusters: 创建时仅允许指定OneCloud Zone
  pkg/compute/models/loadbalancerclusters.go
Labels: approved, lgtm, size/XS

#2111 Automated cherry pick of #2109: lbclusters: 创建时仅允许指定OneCloud Zone
  pkg/compute/models/loadbalancerclusters.go
Labels: approved, lgtm, size/XS

#2109 lbclusters: 创建时仅允许指定OneCloud Zone
  pkg/compute/models/loadbalancerclusters.go
Labels: approved, area/region, lgtm, size/XS

#2105 fix: adjust default policies for system resources
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/policy/defaults.go
  pkg/httperrors/httperrors.go
Labels: approved, area/region, lgtm, size/M

#2106 Automated cherry pick of #2105: fix: adjust default policies for system resources
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/policy/defaults.go
  pkg/httperrors/httperrors.go
Labels: approved, lgtm, size/M

#2107 Automated cherry pick of #2105: fix: adjust default policies for system resources
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/policy/defaults.go
  pkg/httperrors/httperrors.go
Labels: approved, lgtm, size/M

#2116 huawei & aws & ucloud fix
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/util/aws/disk.go
  pkg/util/huawei/image.go
  pkg/util/ucloud/securitygroup.go
Labels: approved, lgtm, size/M

#2128 kvm elb fix
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/kvm.go
Labels: approved, area/region, lgtm, size/M

#2129 Automated cherry pick of #2128: kvm elb fix
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/kvm.go
Labels: approved, lgtm, size/M

#2114 misc bugfix
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/system_service/systemd.go
  pkg/image/models/images.go
  pkg/util/fstabutils/fstabutils.go
Labels: approved, area/host, area/region, lgtm, size/M

#2120 Automated cherry pick of #2114: misc bugfix
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/system_service/systemd.go
  pkg/image/models/images.go
  pkg/util/fstabutils/fstabutils.go
Labels: approved, lgtm, size/M

#2121 Automated cherry pick of #2114: misc bugfix
  pkg/cloudcommon/db/opslog.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/routetables.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/system_service/systemd.go
  pkg/image/models/images.go
  pkg/util/fstabutils/fstabutils.go
Labels: approved, lgtm, size/M

#2115 Automated cherry pick of #2104: wires: 添加mtu属性
  cmd/climc/shell/wires.go
  pkg/cloudcommon/types/nic.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/wires.go
  pkg/compute/options/options.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/M

#2104 wires: 添加mtu属性
  cmd/climc/shell/wires.go
  pkg/cloudcommon/types/nic.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/wires.go
  pkg/compute/options/options.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, area/host, area/region, lgtm, size/M

#2117 lbclusters: 改正删除操作
  cmd/climc/shell/loadbalanceragents.go
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/mcclient/options/loadbalanceragents.go
  pkg/mcclient/options/loadbalancers.go
Labels: approved, area/region, lgtm, size/L

#2118 Automated cherry pick of #2117: lbclusters: 改正删除操作
  cmd/climc/shell/loadbalanceragents.go
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/mcclient/options/loadbalanceragents.go
  pkg/mcclient/options/loadbalancers.go
Labels: approved, lgtm, size/L

#2119 Automated cherry pick of #2117: lbclusters: 改正删除操作
  cmd/climc/shell/loadbalanceragents.go
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/mcclient/options/loadbalanceragents.go
  pkg/mcclient/options/loadbalancers.go
Labels: approved, lgtm, size/L

#2134 docs: 添加lbagent-undeploy接口描述
  docs/index.yaml
  docs/loadbalancer/loadbalanceragent-undeploy.yaml
Labels: approved, area/docs, lgtm, size/S

#2124 hotfix: deprecated password auth
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/storagecache.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, area/region, lgtm, size/S

#2126 Automated cherry pick of #2124: hotfix: deprecated password auth
  pkg/util/zstack/host.go
  pkg/util/zstack/storagecache.go
  pkg/util/zstack/zstack.go
Labels: approved, lgtm, size/S

#2122 fix: 避免从高版本降级到2.10.0后因provider字段改变导致操作不兼容
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/XS

#2125 Automated cherry pick of #2124: hotfix: deprecated password auth
  pkg/multicloud/zstack/host.go
  pkg/multicloud/zstack/storagecache.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/S

#2141 Automated cherry pick of #2140: fix: auth through disconnected ldap IDP
  pkg/keystone/models/projects.go
  pkg/keystone/tokens/auth.go
Labels: approved, lgtm, size/S

#2142 Automated cherry pick of #2140: fix: auth through disconnected ldap IDP
  pkg/keystone/models/projects.go
  pkg/keystone/tokens/auth.go
Labels: approved, lgtm, size/S

#2140 fix: auth through disconnected ldap IDP
  pkg/keystone/models/projects.go
  pkg/keystone/tokens/auth.go
Labels: approved, area/keystone, lgtm, size/S

#2131 新增 climc notify-broadcast 接口,用于向所有在线用户发 websocket 通知
  cmd/climc/shell/notification.go
  pkg/mcclient/modules/notify/mod_notification.go
Labels: area/websocket, lgtm, size/S

#2132 Automated cherry pick of #2131: 新增 climc notify-broadcast 接口,用于向所有在线用户发 websocket 通知
  cmd/climc/shell/notification.go
  pkg/mcclient/modules/notify/mod_notification.go
Labels: lgtm, size/S

#2133 Automated cherry pick of #2131: 新增 climc notify-broadcast 接口,用于向所有在线用户发 websocket 通知
  cmd/climc/shell/notification.go
  pkg/mcclient/modules/notify/mod_notification.go
Labels: lgtm, size/S

#2135 hotfix: essd PerformanceLevel sync
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/hostdrivers/aliyun.go
  pkg/multicloud/aliyun/disk.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/storage.go
  pkg/multicloud/aliyun/zone.go
Labels: approved, area/region, lgtm, needs-backport, size/M

#2147 Automated cherry pick of #2135: hotfix: essd PerformanceLevel sync
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/hostdrivers/aliyun.go
  pkg/multicloud/aliyun/disk.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/storage.go
  pkg/multicloud/aliyun/zone.go
Labels: approved, lgtm

#2143 model & model manager mismatch fix
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/elasticcache_parameters.go
  pkg/hostimage/host_image_service.go
Labels: approved, area/region, lgtm, size/S

#2144 Automated cherry pick of #2143: model & model manager mismatch fix
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/elasticcache_parameters.go
  pkg/hostimage/host_image_service.go
Labels: approved, lgtm, size/S

#2148 Automated cherry pick of #2135: hotfix: essd PerformanceLevel sync
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/hostdrivers/aliyun.go
  pkg/util/aliyun/disk.go
  pkg/util/aliyun/instance.go
  pkg/util/aliyun/storage.go
  pkg/util/aliyun/zone.go
Labels: approved, lgtm

#2136 bugfix: fix guest cannot delete
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, area/region, lgtm, size/S

#2138 Automated cherry pick of #2136: fix guest cannot delete
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, lgtm, size/S

#2137 Automated cherry pick of #2136: fix guest cannot delete
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, lgtm, size/S

#2150 Automated cherry pick of #2149: fix: not sync zstack deleted disk or instance & secgroup rule sync fix
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/M

#2149 fix: not sync zstack deleted disk or instance & secgroup rule sync fix
  pkg/multicloud/zstack/disk.go
  pkg/multicloud/zstack/instance.go
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, area/region, lgtm, size/M

#2151 Automated cherry pick of #2149: fix: not sync zstack deleted disk or instance & secgroup rule sync fix
  pkg/util/zstack/disk.go
  pkg/util/zstack/instance.go
  pkg/util/zstack/securitygroup.go
Labels: approved, lgtm, size/M

#2123 fix: get keypair info fail after rebuild-root
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/utils.go
Labels: approved, area/region, lgtm, needs-backport, size/S

#2156 Automated cherry pick of #2123: fix: get keypair info fail after rebuild-root
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/utils.go
Labels: approved, lgtm, size/S

#2155 Automated cherry pick of #2123: fix: get keypair info fail after rebuild-root
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/utils.go
Labels: approved, lgtm, size/S

#2108 feature: add huawei rds sync
  pkg/apis/compute/dbinstance_const.go
  pkg/compute/models/cloudregions.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_dbinstance.go
  pkg/multicloud/huawei/client/modules/mod_dbinstance_backup.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/dbinstance_account.go
  pkg/multicloud/huawei/dbinstance_backup.go
  pkg/multicloud/huawei/dbinstance_database.go
  pkg/multicloud/huawei/dbinstance_parameter.go
  pkg/multicloud/huawei/dbinstance_privilege.go
  pkg/multicloud/huawei/shell/dbinstance.go
  pkg/multicloud/huawei/utils.go
Labels: approved, area/region, lgtm, needs-backport, size/XL

#2145 Automated cherry pick of #2108: feature: add huawei rds sync
  pkg/apis/compute/dbinstance_const.go
  pkg/compute/models/cloudregions.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_dbinstance.go
  pkg/multicloud/huawei/client/modules/mod_dbinstance_backup.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/dbinstance_account.go
  pkg/multicloud/huawei/dbinstance_backup.go
  pkg/multicloud/huawei/dbinstance_database.go
  pkg/multicloud/huawei/dbinstance_parameter.go
  pkg/multicloud/huawei/dbinstance_privilege.go
  pkg/multicloud/huawei/shell/dbinstance.go
  pkg/multicloud/huawei/utils.go
Labels: approved, lgtm, size/XL

#2152 Bugfix/yousong lbagent log lines
  pkg/lbagent/api.go
  pkg/lbagent/models/agentparams.go
Labels: approved, area/region, lgtm

#2153 Automated cherry pick of #2152: lbagent: 改正unicast vrrp日志记录
  pkg/lbagent/api.go
  pkg/lbagent/models/agentparams.go
Labels: approved, lgtm, size/XS

#2154 Automated cherry pick of #2152: lbagent: 改正unicast vrrp日志记录
  pkg/lbagent/api.go
  pkg/lbagent/models/agentparams.go
Labels: approved, lgtm, size/XS

#2157 feature: bucket usage and quota check
  cmd/climc/shell/buckets.go
  pkg/cloudcommon/db/project_resources.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/compute/models/quotas.go
  pkg/compute/options/options.go
  pkg/compute/usages/handler.go
  pkg/multicloud/objectstore/buckets.go
Labels: size/L

#2158 Automated cherry pick of #2157: feature: bucket usage and quota check
  cmd/climc/shell/buckets.go
  pkg/cloudcommon/db/project_resources.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/compute/models/quotas.go
  pkg/compute/options/options.go
  pkg/compute/usages/handler.go
  pkg/multicloud/objectstore/buckets.go
Labels: size/L

#2146 climc: add --output-format support
  cmd/climc/climc.go
  cmd/climc/shell/utils.go
Labels: approved, area/climc, lgtm

#2167 Automated cherry pick of #2146: climc: add --output-format support
  cmd/climc/climc.go
  cmd/climc/shell/utils.go
Labels: approved, lgtm

#2168 Automated cherry pick of #2146: climc: add --output-format support
  cmd/climc/climc.go
  cmd/climc/shell/utils.go
Labels: approved, lgtm

#2162 feature: server migrate to different mountpoint storage
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/storage_cache_image_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
Labels: approved, lgtm

#2163 Automated cherry pick of #2162: server migrate to different mountpoint storage
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/storage_cache_image_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
Labels: approved, lgtm

#2164 Automated cherry pick of #2162: server migrate to different mountpoint storage
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/storage_cache_image_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
Labels: approved, lgtm

#2176 hotfix: 将 websocket 的 broadcast 接口里 topic 这个必选变量设为位置参数; 其他参数给了默认值,非必填
  cmd/climc/shell/notification.go
Labels: approved, area/websocket, lgtm, size/S

#2177 Automated cherry pick of #2176: hotfix: 将 websocket 的 broadcast 接口里 topic 这个必选变量设为位置参数; 其他参数给了默认值,非必填
  cmd/climc/shell/notification.go
Labels: approved, lgtm, size/S

#2178 Automated cherry pick of #2176: hotfix: 将 websocket 的 broadcast 接口里 topic 这个必选变量设为位置参数; 其他参数给了默认值,非必填
  cmd/climc/shell/notification.go
Labels: approved, lgtm, size/S

#2161 hotfix: sync openstack cup and memory cmtbound
  pkg/cloudprovider/resources.go
  pkg/compute/models/hosts.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/azure/classic_host.go
  pkg/multicloud/azure/host.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/host_base.go
  pkg/multicloud/huawei/host.go
  pkg/multicloud/openstack/host.go
  pkg/multicloud/openstack/shell/host.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/ucloud/host.go
  pkg/multicloud/zstack/host.go
Labels: approved, area/region, lgtm

#2172 Automated cherry pick of #2161: hotfix: sync openstack cup and memory cmtbound
  pkg/cloudprovider/resources.go
  pkg/compute/models/hosts.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/azure/classic_host.go
  pkg/multicloud/azure/host.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/host_base.go
  pkg/multicloud/huawei/host.go
  pkg/multicloud/openstack/host.go
  pkg/multicloud/openstack/shell/host.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/ucloud/host.go
  pkg/multicloud/zstack/host.go
Labels: approved, lgtm

#2173 Automated cherry pick of #2161: hotfix: sync openstack cup and memory cmtbound
  pkg/cloudprovider/resources.go
  pkg/compute/models/hosts.go
  pkg/multicloud/host_base.go
  pkg/util/aliyun/host.go
  pkg/util/aws/host.go
  pkg/util/azure/classic_host.go
  pkg/util/azure/host.go
  pkg/util/esxi/host.go
  pkg/util/huawei/host.go
  pkg/util/openstack/host.go
  pkg/util/openstack/shell/host.go
  pkg/util/qcloud/host.go
  pkg/util/ucloud/host.go
  pkg/util/zstack/host.go
Labels: approved, lgtm

#2174 fix: influxdb write support
  pkg/util/influxdb/influxdb.go
Labels: approved, area/region, lgtm, size/M

#2175 Automated cherry pick of #2174: fix: influxdb write support
  pkg/util/influxdb/influxdb.go
Labels: approved, lgtm, size/M

#2181 cpu core bugfix
  pkg/multicloud/aws/instance.go
Labels: approved, area/region, lgtm, size/XS

#2183 Automated cherry pick of #2181: cpu core bugfix
  pkg/util/aws/instance.go
Labels: approved, lgtm, size/XS

#2184 Automated cherry pick of #2181: cpu core bugfix
  pkg/util/aws/instance.go
Labels: approved, lgtm, size/XS

#2185 Automated cherry pick of #2181: cpu core bugfix
  pkg/util/aws/instance.go
Labels: approved, lgtm, size/XS

#2182 Automated cherry pick of #2181: cpu core bugfix
  pkg/multicloud/aws/instance.go
Labels: approved, lgtm, size/XS

#2179 fix: 1. get object acl not found 2. distinguish primary url for bucket
  docs/identity/auth_v3.yaml
  docs/index.yaml
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/buckets.go
  pkg/multicloud/qcloud/bucket.go
  pkg/multicloud/ucloud/ufile.go
Labels: approved, area/region, lgtm, size/S

#2180 Automated cherry pick of #2179: fix: 1. get object acl not found 2. distinguish primary url for bucket
  docs/identity/auth_v3.yaml
  docs/index.yaml
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/buckets.go
  pkg/multicloud/qcloud/bucket.go
  pkg/multicloud/ucloud/ufile.go
Labels: approved, lgtm, size/S

#2186 fix: lb purge error
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/purge.go
Labels: approved, area/region, lgtm, size/S

#2188 Automated cherry pick of #2186: fix: lb purge error
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/purge.go
Labels: approved, lgtm, size/S

#2187 Automated cherry pick of #2186: fix: lb purge error
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/purge.go
Labels: approved, lgtm, size/S

#2189 Automated cherry pick of #2186: fix: lb purge error
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/purge.go
Labels: approved, lgtm, size/S

#2190 Automated cherry pick of #2186: fix: lb purge error
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/purge.go
Labels: approved, lgtm, size/S

#2159 elb bugfix
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/utils.go
Labels: approved, lgtm, size/L

#2160 Automated cherry pick of #2159: elb bugfix
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/utils.go
Labels: approved, lgtm, size/L

#2191 fix: qcloud/aws temp url not working
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: approved, area/region, lgtm, size/M

#2192 Automated cherry pick of #2191: fix: qcloud/aws temp url not working
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: approved, lgtm, size/M

#2193 fix: imported esxi VM fail to rebuild root
  pkg/compute/guestdrivers/esxi.go
Labels: approved, area/region, lgtm, size/XS

#2194 Automated cherry pick of #2193: fix: imported esxi VM fail to rebuild root
  pkg/compute/guestdrivers/esxi.go
Labels: approved, lgtm, size/XS

#2195 Automated cherry pick of #2193: fix: imported esxi VM fail to rebuild root
  pkg/compute/guestdrivers/esxi.go
Labels: approved, lgtm, size/XS

#2199 Bugfix/yousong choices hint
  cmd/climc/shell/contacts.go
  cmd/climc/shell/elasticips.go
  cmd/climc/shell/itsm_tasks.go
  cmd/climc/shell/keypairs.go
  cmd/climc/shell/notification.go
  cmd/climc/shell/storages.go
  cmd/climc/shell/usages.go
  go.mod
  go.sum
  pkg/apis/identity/config.go
  pkg/mcclient/options/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/structarg/stringdist.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: approved, area/climc, lgtm, size/L

#2200 Automated cherry pick of #2199: vendor: update structarg
  cmd/climc/shell/contacts.go
  cmd/climc/shell/elasticips.go
  cmd/climc/shell/itsm_tasks.go
  cmd/climc/shell/keypairs.go
  cmd/climc/shell/notification.go
  cmd/climc/shell/storages.go
  cmd/climc/shell/usages.go
  go.mod
  go.sum
  pkg/apis/identity/config.go
  pkg/mcclient/options/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/structarg/stringdist.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: approved, lgtm, size/L

#2201 Automated cherry pick of #2199: vendor: update structarg
  cmd/climc/shell/contacts.go
  cmd/climc/shell/elasticips.go
  cmd/climc/shell/itsm_tasks.go
  cmd/climc/shell/keypairs.go
  cmd/climc/shell/notification.go
  cmd/climc/shell/storages.go
  cmd/climc/shell/usages.go
  go.mod
  go.sum
  pkg/apis/identity/config.go
  pkg/mcclient/options/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/structarg/stringdist.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: approved, lgtm, size/L

#2127 添加各个组件制作成 docker 镜像的 Dockerfile
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.glance
  build/docker/Dockerfile.keystone
  build/docker/Dockerfile.logger
  build/docker/Dockerfile.region
  build/docker/Dockerfile.region-dns
  build/docker/Dockerfile.scheduler
  build/docker/Dockerfile.webconsole
  build/docker/Dockerfile.yunionconf
  pkg/keystone/models/users.go
  pkg/logger/service/service.go
  pkg/mcclient/input.go
  pkg/mcclient/mcclient.go
  pkg/webconsole/service/service.go
  scripts/docker_push.sh
Labels: approved, area/util, lgtm, size/L

#2216 circleci: coverage.sh: 改善内存消耗
  scripts/coverage.sh
Labels: approved, area/util, lgtm, size/S

#2217 Automated cherry pick of #2216: circleci: coverage.sh: 改善内存消耗
  scripts/coverage.sh
Labels: approved, lgtm, size/S

#2218 Automated cherry pick of #2216: circleci: coverage.sh: 改善内存消耗
  scripts/coverage.sh
Labels: approved, lgtm, size/S

#2211 lbcluster: 添加wire亲和性质
  cmd/climc/shell/loadbalancerclusters.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/regiondrivers/kvm.go
  pkg/mcclient/modules/mod_loadbalancerclusters.go
  pkg/mcclient/options/loadbalancerclusters.go
Labels: approved, area/region, lgtm, size/L

#2213 Automated cherry pick of #2211: lbcluster: 添加wire亲和性质
  cmd/climc/shell/loadbalancerclusters.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/models/loadbalancers.go
  pkg/mcclient/modules/mod_loadbalancerclusters.go
  pkg/mcclient/options/loadbalancerclusters.go
Labels: approved, lgtm, size/L

#2212 Automated cherry pick of #2211: lbcluster: 添加wire亲和性质
  cmd/climc/shell/loadbalancerclusters.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/regiondrivers/kvm.go
  pkg/mcclient/modules/mod_loadbalancerclusters.go
  pkg/mcclient/options/loadbalancerclusters.go
Labels: approved, lgtm, size/L

#2221 Automated cherry pick of #2219: quota-set 新增 secgroup 字段
  cmd/climc/shell/quotas.go
Labels: approved, lgtm, size/XS

#2210 Automated cherry pick of #2209: wires: 改正mtu校验
  pkg/compute/models/wires.go
Labels: approved, lgtm, size/M

#2209 wires: 改正mtu校验
  pkg/compute/models/wires.go
Labels: approved, area/region, lgtm, size/M

#2220 Automated cherry pick of #2219: quota-set 新增 secgroup 字段
  cmd/climc/shell/quotas.go
Labels: approved, lgtm, size/XS

#2214 lb: 改正update参数校验
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/qcloud.go
Labels: approved, area/region, lgtm, size/L

#2215 Automated cherry pick of #2214: lb: 改正update参数校验
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/qcloud.go
Labels: approved, lgtm, size/L

#2219 quota-set 新增 secgroup 字段
  cmd/climc/shell/quotas.go
Labels: approved, area/climc, lgtm, size/XS

#2226 Automated cherry pick of #2225: feature: s3upload support multipart upload
  cmd/climc/shell/images.go
  docs/bucket/uploadobject.yaml
  docs/parameters/bucket.yaml
  docs/schemas/bucket.yaml
  go.mod
  go.sum
  pkg/apis/compute/bucket.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/image/models/images.go
  pkg/mcclient/modules/mod_images.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aliyun/objects.go
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/aws/s3object.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/azure/blobobject.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/azure/storagecache.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/huawei/object.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/objectstore/buckets.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/openstack/storagecache.go
  pkg/multicloud/qcloud/bucket.go
  pkg/multicloud/qcloud/object.go
  pkg/multicloud/qcloud/storagecache.go
  pkg/multicloud/ucloud/storagecache.go
  pkg/multicloud/ucloud/ufile.go
  pkg/multicloud/zstack/storagecache.go
  pkg/util/fileutils2/seeker.go
  pkg/util/fileutils2/seeker_test.go
  pkg/util/httputils/httputils.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/batch.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/bucket_region.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/doc.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/download.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
  vendor/modules.txt
  vendor/yunion.io/x/s3cli/README.md
  vendor/yunion.io/x/s3cli/api-compose-object.go
  vendor/yunion.io/x/s3cli/api-put-object-common.go
  vendor/yunion.io/x/s3cli/api-put-object-multipart.go
  vendor/yunion.io/x/s3cli/api-put-object-streaming.go
  vendor/yunion.io/x/s3cli/api-put-object.go
  vendor/yunion.io/x/s3cli/api-remove.go
  vendor/yunion.io/x/s3cli/api-s3-datatypes.go
  vendor/yunion.io/x/s3cli/core.go
Labels: approved, lgtm, size/XXL
