Repository yunionio/cloudpods, pull requests merged in 2020-04, with the labels that each got.

#5640 fix: changes to request_work_count cause apigateway restart
  pkg/apigateway/service/service.go
Labels: area/util, size/XS

#5641 Automated cherry pick of #5640: fix: changes to request_work_count cause apigateway restart
  pkg/apigateway/service/service.go
Labels: size/XS

#5642 Automated cherry pick of #5640: fix: changes to request_work_count cause apigateway restart
  pkg/apigateway/service/service.go
Labels: size/XS

#5643 Automated cherry pick of #5640: fix: changes to request_work_count cause apigateway restart
  pkg/apigateway/service/service.go
Labels: size/XS

#5634 cloudcommon: proxysetting: make it infra resource
  pkg/apis/cloudcommon/proxy/proxy.go
  pkg/cloudcommon/db/proxy/proxysetting.go
Labels: area/region, lgtm, size/M

#5638 Feature/yousong multicloud proxyfunc 3.1
  pkg/apis/cloudcommon/proxy/proxy.go
  pkg/cloudcommon/db/proxy/proxysetting.go
Labels: area/region, lgtm, size/XXL

#5644 monitor: add paused api
  cmd/climc/shell/monitor/alert.go
  pkg/apis/monitor/alert.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/options/monitor/alert.go
  pkg/monitor/models/alert.go
Labels: area/monitor, size/L

#5645 Automated cherry pick of #5644: monitor: add paused api
  cmd/climc/shell/monitor/alert.go
  pkg/apis/monitor/alert.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/options/monitor/alert.go
  pkg/monitor/models/alert.go
Labels: size/L

#5646 修复: 默认存在的bucket状态为ready
  pkg/multicloud/bucket_base.go
Labels: area/region, size/XS

#5647 Automated cherry pick of #5646: 修复: 默认存在的bucket状态为ready
  pkg/multicloud/bucket_base.go
Labels: size/XS

#5648 fix: cancel pending usage might not need to update usage
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/compute/models/buckets.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_base_task.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_base_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: area/image, area/region, lgtm, size/L

#5649 Automated cherry pick of #5648: fix: cancel pending usage might not need to update usage
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/compute/models/buckets.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_base_task.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_base_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: size/L

#5650 Automated cherry pick of #5648: fix: cancel pending usage might not need to update usage
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/compute/models/buckets.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_base_task.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_base_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: size/L

#5651 Automated cherry pick of #5648: fix: cancel pending usage might not need to update usage
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/compute/models/buckets.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_base_task.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_base_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: size/L

#5653 fix: allow list cloudprovider by default
  pkg/compute/policy/defaults.go
Labels: area/region, size/M

#5654 Automated cherry pick of #5653: fix: allow list cloudprovider by default
  pkg/cloudcommon/policy/defaults.go
Labels: size/M

#5655 Automated cherry pick of #5653: fix: allow list cloudprovider by default
  pkg/cloudcommon/policy/defaults.go
Labels: size/M

#5656 Automated cherry pick of #5653: fix: allow list cloudprovider by default
  pkg/cloudcommon/policy/defaults.go
Labels: size/M

#5659 host session use internal endpoint
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/auth/auth.go
Labels: area/host, size/S

#5660 Automated cherry pick of #5659: host session use internal endpoint
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/auth/auth.go
Labels: size/S

#5661 Automated cherry pick of #5659: host session use internal endpoint
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/auth/auth.go
Labels: size/S

#5652 Bugfix/yousong multicloud proxyfunc
  pkg/apis/cloudcommon/proxy/proxy.go
  pkg/apis/cloudcommon/proxy/setting.go
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/proxy/proxysetting.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: area/region, lgtm, size/L

#5657 Automated cherry pick of #5652: proxysetting: forbid deletion of DIRECT setting
  pkg/apis/cloudcommon/proxy/proxy.go
  pkg/apis/cloudcommon/proxy/setting.go
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/proxy/proxysetting.go
  pkg/compute/models/cloudaccounts.go
Labels: size/L

#5658 feature: keystone lock user returns ErrTooManyAttempts
  pkg/apigateway/handler/auth.go
  pkg/httperrors/consts.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/users.go
  pkg/keystone/tokens/handlers.go
Labels: area/keystone, size/S

#5662 fix: disk/nics usage should exclude those pending_deleted
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: area/region, size/M

#5663 Automated cherry pick of #5662: fix: disk/nics usage should exclude those pending_deleted
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: size/M

#5664 Automated cherry pick of #5662: fix: disk/nics usage should exclude those pending_deleted
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: size/M

#5665 Automated cherry pick of #5662: fix: disk/nics usage should exclude those pending_deleted
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: size/M

#5631 elb bugfix
  pkg/apis/compute/elasticips_const.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/loadbalancerbackend.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackend.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackend.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: area/region, lgtm, size/L

#5636 Automated cherry pick of #5631: elb bugfix
  pkg/apis/compute/elasticips_const.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/loadbalancerbackend.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackend.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackend.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/L

#5637 Automated cherry pick of #5631: elb bugfix
  pkg/apis/compute/elasticips_const.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/loadbalancerbackend.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackend.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackend.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/L

#5639 Automated cherry pick of #5631: elb bugfix
  pkg/apis/compute/elasticips_const.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/loadbalancerbackend.go
  pkg/multicloud/aliyun/loadbalancerbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackend.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackend.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/huawei/loadbalancer_backendgroup.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
  pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/L

#5669 climc: k8s remove registrysecret create command
  cmd/climc/shell/k8s/secret.go
  pkg/mcclient/modules/k8s/secret.go
  pkg/mcclient/options/k8s/secret.go
Labels: approved, area/climc, lgtm, size/M

#5670 Automated cherry pick of #5669: climc: k8s remove registrysecret create command
  cmd/climc/shell/k8s/secret.go
  pkg/mcclient/modules/k8s/secret.go
  pkg/mcclient/options/k8s/secret.go
Labels: approved, lgtm, size/M

#5667 fix: 修复更新qcloud sdk引出的不兼容问题
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, area/region, lgtm, size/XS

#5668 Automated cherry pick of #5667: fix: 修复更新qcloud sdk引出的不兼容问题
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/XS

#5679 fix: typo
  cmd/climc/shell/cloudaccounts.go
Labels: approved, area/climc, lgtm, size/XS

#5680 Automated cherry pick of #5679: fix: typo
  cmd/climc/shell/cloudaccounts.go
Labels: approved, lgtm, size/XS

#5676 host do not set hostname
  pkg/hostman/hostinfo/hostinfo.go
Labels: area/host, lgtm, size/XS

#5677 Automated cherry pick of #5676: host do not set hostname
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#5678 Automated cherry pick of #5676: host do not set hostname
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#5681 [3.1] cloudaccounts: update: make proxy_setting optional
  pkg/compute/models/cloudaccounts.go
Labels: approved, area/region, lgtm, size/XS

#5683 Automated cherry pick of #5682: fix: typo
  pkg/apis/compute/zone.go
Labels: size/XS

#5682 fix: typo
  pkg/apis/compute/zone.go
Labels: area/region, size/XS

#5685 feature: identity provider improvements
  cmd/climc/shell/events.go
  cmd/climc/shell/identityproviders.go
  pkg/apis/identity/config.go
  pkg/keystone/models/configs.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/services.go
Labels: area/keystone, size/M

#5586 feature: copy esxi guest to kvm
  build/docker/Dockerfile.host-deployer
  cmd/climc/shell/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guest_import_api.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/compute/hostdrivers/esxi.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/esxi/handler/handlers.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestman/esxi.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostdeployer/Readme.md
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/deployclient/deployclient.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_agent.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/hostman/storageman/storage_agent.go
  pkg/mcclient/options/servers.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/vcenter/doc.go
  pkg/multicloud/esxi/vcenter/vcenter.go
  pkg/util/logclient/consts.go
Labels: area/host, area/region, size/XXL

#5671 fix: 华为云rds使用自身的存储类型
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/huawei/dbinstance.go
Labels: area/region, size/S

#5672 Automated cherry pick of #5671: fix: 华为云rds使用自身的存储类型
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/huawei/dbinstance.go
Labels: size/S

#5673 Automated cherry pick of #5671: fix: 华为云rds使用自身的存储类型
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/huawei/dbinstance.go
Labels: size/S

#5674 Automated cherry pick of #5671: fix: 华为云rds使用自身的存储类型
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/huawei/dbinstance.go
Labels: size/S

#5675 Automated cherry pick of #5671: fix: 华为云rds使用自身的存储类型
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/huawei/dbinstance.go
Labels: size/S

#5686 fix: 修复重装系统时未能更换指定image问题
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: area/region, size/S

#5687 Automated cherry pick of #5686: fix: 修复重装系统时未能更换指定image问题
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/S

#5688 Automated cherry pick of #5686: fix: 修复重装系统时未能更换指定image问题
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/S

#5689 Automated cherry pick of #5686: fix: 修复重装系统时未能更换指定image问题
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/S

#5690 Automated cherry pick of #5686: fix: 修复重装系统时未能更换指定image问题
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/S

#5684 feature: domain resource quota
  cmd/climc/shell/domains.go
  cmd/climc/shell/projects.go
  cmd/climc/shell/quotas.go
  pkg/apis/identity/domain.go
  pkg/apis/identity/input.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/models.go
  pkg/cloudcommon/db/quotas/quotakeys.go
  pkg/cloudcommon/db/quotas/quotakeys_test.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/ctyun.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/domainquota.go
  pkg/compute/models/globalvpcs.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/infrasquota.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/quotas_doc.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/zonequota.go
  pkg/compute/options/options.go
  pkg/compute/policy/defaults.go
  pkg/compute/service/handlers.go
  pkg/compute/service/service.go
  pkg/compute/usages/handler.go
  pkg/image/models/images.go
  pkg/image/models/quotas.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/identityquota.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/roles.go
  pkg/keystone/models/users.go
  pkg/keystone/options/options.go
  pkg/keystone/service/handlers.go
  pkg/keystone/service/service.go
  pkg/mcclient/modules/mod_domains.go
  pkg/mcclient/modules/mod_projects.go
  pkg/mcclient/modules/mod_quotas.go
Labels: area/keystone, area/region, lgtm, size/XXL

#5691 fix(region): Fix some question of CheckAndSetCacheImage.
  pkg/compute/hostdrivers/esxi.go
Labels: area/region, size/S

#5694 fix: misc bugs in usage data
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/image/models/quotas.go
  pkg/image/usages/handler.go
  pkg/mcclient/modules/mod_images.go
Labels: area/image, area/region, size/L

#5695 Automated cherry pick of #5694: fix: misc bugs in usage data
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/image/models/quotas.go
  pkg/image/usages/handler.go
  pkg/mcclient/modules/mod_images.go
Labels: size/L

#5696 Automated cherry pick of #5694: fix: misc bugs in usage data
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/image/models/quotas.go
  pkg/image/usages/handler.go
  pkg/mcclient/modules/mod_images.go
Labels: size/L

#5697 Automated cherry pick of #5694: fix: misc bugs in usage data
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/image/models/quotas.go
  pkg/image/usages/handler.go
  pkg/mcclient/modules/mod_images.go
Labels: size/L

#5692 Automated cherry pick of #5691: fix(esxi): Fix some question of CheckAndSetCacheImage.
  pkg/compute/hostdrivers/esxi.go
Labels: size/S

#5693 Automated cherry pick of #5691: fix(esxi): Fix some question of CheckAndSetCacheImage.
  pkg/compute/hostdrivers/esxi.go
Labels: size/S

#5666 Feature/auto scaling
  cmd/climc/shell/scaling_activity.go
  cmd/climc/shell/scaling_group.go
  cmd/climc/shell/scaling_policy.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/guesttemplate.go
  pkg/apis/compute/input.go
  pkg/apis/compute/scaling_activity.go
  pkg/apis/compute/scaling_const.go
  pkg/apis/compute/scaling_group.go
  pkg/apis/compute/scaling_policy.go
  pkg/apis/compute/scaling_trigger.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/monitor/notification.go
  pkg/compute/models/groupguests.go
  pkg/compute/models/groupresource.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/guests.go
  pkg/compute/models/guesttemplate_resource.go
  pkg/compute/models/scaling_activity.go
  pkg/compute/models/scaling_group.go
  pkg/compute/models/scaling_group_resource.go
  pkg/compute/models/scaling_policy.go
  pkg/compute/models/scaling_trigger.go
  pkg/compute/models/scalinggroup_guest.go
  pkg/compute/models/scalinggroup_network.go
  pkg/compute/options/options.go
  pkg/compute/service/handlers.go
  pkg/compute/service/service.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/compute/tasks/guest_detach_scalinggroup.go
  pkg/compute/tasks/scaling_group_delete_task.go
  pkg/controller/autoscaling/controller.go
  pkg/controller/autoscaling/doc.go
  pkg/controller/autoscaling/errors.go
  pkg/controller/autoscaling/health_check.go
  pkg/controller/autoscaling/timer.go
  pkg/mcclient/modulebase/resource.go
  pkg/mcclient/modules/mod_scaling.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/options/servers.go
  pkg/monitor/alerting/notifiers/auto_scaling.go
  pkg/monitor/models/notification.go
  pkg/util/logclient/consts.go
Labels: area/region, size/XXL

#5704 fix migrate cache cdrom
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: area/region, lgtm, size/XS

#5705 Automated cherry pick of #5704: fix migrate cache cdrom
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: size/XS

#5707 Automated cherry pick of #5704: fix migrate cache cdrom
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: size/XS

#5703 fix: add domain-level compute resource usage
  pkg/compute/models/storages.go
  pkg/compute/usages/handler.go
Labels: area/region, size/L

#5702 fix: remove obsolete policy definitions
  pkg/cloudcommon/policy/defaults.go
  pkg/cloudcommon/policy/resources.go
Labels: area/util, size/M

#5698 fix: service config changes not effective
  pkg/apigateway/options/options.go
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/compute/options/options.go
  pkg/image/options/options.go
  pkg/keystone/options/options.go
  pkg/notify/options/options.go
  pkg/webconsole/options/options.go
Labels: area/image, area/keystone, size/M

#5699 Automated cherry pick of #5698: fix: service config changes not effective
  pkg/apigateway/options/options.go
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/compute/options/options.go
  pkg/image/options/options.go
  pkg/keystone/options/options.go
  pkg/notify/options/options.go
Labels: size/M

#5700 Automated cherry pick of #5698: fix: service config changes not effective
  pkg/apigateway/options/options.go
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/compute/options/options.go
  pkg/image/options/options.go
  pkg/keystone/options/options.go
  pkg/notify/options/options.go
Labels: size/M

#5701 Automated cherry pick of #5698: fix: service config changes not effective
  pkg/apigateway/options/options.go
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/compute/options/options.go
  pkg/image/options/options.go
  pkg/keystone/options/options.go
  pkg/notify/options/options.go
Labels: size/M

#5708 fix: default value of is_domain field is not consistent between projects and domains
  pkg/keystone/models/domains.go
Labels: area/keystone, size/XS

#5713 fix: 1. parameter duplicate error due to missing name filter 2.infras_quota setKeys error
  pkg/apis/yunionconf/input.go
  pkg/compute/models/infrasquota.go
  pkg/yunionconf/models/parameters.go
Labels: area/region, size/S

#5709 feature: add API to retrieve resource's change owner candidate domains
  cmd/climc/shell/hosts.go
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/managedresource.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/projects.go
Labels: area/region, size/M

#5710 build: fix "mod" target on darwin
  Makefile
Labels: area/util, lgtm, size/XS

#5714 fix: decouple getUserInfo at apigateway from capabilities call
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/S

#5716 Automated cherry pick of #5714: fix: decouple getUserInfo at apigateway from capabilities call
  pkg/apigateway/handler/auth.go
Labels: size/S

#5717 Automated cherry pick of #5714: fix: decouple getUserInfo at apigateway from capabilities call
  pkg/apigateway/handler/auth.go
Labels: size/S

#5718 fix: role/policy missing FilterByOwner implementation
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: area/keystone, size/XS

#5721 model api gen
  pkg/apis/cloudcommon/proxy/zz_generated.model.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/cloudcommon/db/quotas/quotakeys.go
Labels: area/util, size/S

#5724 db_dispatcher: default action log for create & update
  cmd/climc/shell/cloudnet/routes.go
  cmd/climc/shell/networks.go
  cmd/climc/shell/proxysettings.go
  pkg/apis/cloudcommon/proxy/setting.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/proxy/proxysetting.go
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/mcclient/options/proxysettings.go
Labels: area/climc, area/region, lgtm, size/L

#5725 Automated cherry pick of #5724: lbagents: deploy: deploy public type auth_url
  cmd/climc/shell/cloudnet/routes.go
  cmd/climc/shell/networks.go
  cmd/climc/shell/proxysettings.go
  pkg/apis/cloudcommon/proxy/setting.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/proxy/proxysetting.go
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/mcclient/options/proxysettings.go
Labels: size/L

#5723 fix: shared resource list details missing shared projects/domains attributes
  pkg/cloudcommon/db/sharablebase.go
Labels: area/region, size/M

#5732 fix: service-config-show shows service's own config
  pkg/cloudcommon/options/options.go
  pkg/keystone/models/configs.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/services.go
  pkg/keystone/models/syncworker.go
  pkg/keystone/tokens/auth.go
Labels: area/keystone, size/M

#5733 fix: idp log connected/disconnected event
  cmd/climc/shell/policies.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/syncworker.go
Labels: area/keystone, size/M

#5734 Automated cherry pick of #5733: fix: idp log connected/disconnected event
  cmd/climc/shell/policies.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/syncworker.go
Labels: size/M

#5735 Automated cherry pick of #5733: fix: idp log connected/disconnected event
  cmd/climc/shell/policies.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/syncworker.go
Labels: size/M

#5736 Automated cherry pick of #5733: fix: idp log connected/disconnected event
  cmd/climc/shell/policies.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/syncworker.go
Labels: size/M

#5731 optimize capabilities
  pkg/compute/models/capabilities.go
  pkg/compute/models/scaling_group.go
  pkg/mcclient/mcclient.go
Labels: area/region, lgtm, size/L

#5726 huawei&qcloud&huawei elb bugfix
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/multicloud/huawei/region.go
Labels: size/M

#5727 Automated cherry pick of #5726: huawei&qcloud&huawei elb bugfix
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/multicloud/huawei/region.go
Labels: size/M

#5728 Automated cherry pick of #5726: huawei&qcloud&huawei elb bugfix
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/multicloud/huawei/region.go
Labels: size/M

#5730 Automated cherry pick of #5726: huawei&qcloud&huawei elb bugfix
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/multicloud/huawei/region.go
Labels: size/M

#5738 fix deployer sigtrap funciton
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, area/host, lgtm, size/XS

#5737 fix(region): Fix problems about Auto Scaling
  pkg/compute/models/scaling_activity.go
  pkg/compute/models/scaling_group.go
  pkg/compute/models/scaling_trigger.go
  pkg/controller/autoscaling/controller.go
  pkg/controller/autoscaling/timer.go
Labels: area/region, size/M

#5739 deployer: os.exit replace return on sigtrap
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: area/host, size/S

#5720 fix(region): Fix some display params about guest template
  pkg/apis/compute/guesttemplate.go
  pkg/compute/models/guest_template.go
Labels: approved, area/region, lgtm

#5744 fix: 简化公有云存储信息返回
  pkg/compute/models/capabilities.go
Labels: approved, area/region, lgtm, size/XS

#5740 region: lbagents: fix returning error when glob has no match
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, area/region, lgtm, size/XS

#5742 Automated cherry pick of #5740: region: lbagents: fix returning error when glob has no match
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, lgtm, size/XS

#5743 Automated cherry pick of #5740: region: lbagents: fix returning error when glob has no match
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, lgtm, size/XS

#5741 Automated cherry pick of #5740: region: lbagents: fix returning error when glob has no match
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: approved, lgtm, size/XS

#5751 fix(glance): Fix the return value after creating guest image
  pkg/image/models/image_guest.go
Labels: approved, area/region, lgtm, size/XS

#5760 is public add create optional tag
  pkg/cloudcommon/db/quotas/register.go
  pkg/cloudcommon/db/sharablebase.go
Labels: approved, area/region, lgtm, size/XS

#5752 fix(region): Fix some problem about auto scaling
  pkg/apis/compute/scaling_const.go
  pkg/compute/models/scaling_group.go
  pkg/compute/models/scaling_policy.go
  pkg/compute/models/scaling_trigger.go
  pkg/compute/models/scaling_trigger_test.go
  pkg/compute/tasks/guest_detach_scalinggroup.go
  pkg/controller/autoscaling/timer.go
Labels: area/region, size/L

#5750 fix: 优化region-capability速度
  pkg/compute/models/cloudregions.go
  pkg/mcclient/modules/mod_cloudregions.go
  pkg/multicloud/google/region.go
Labels: area/region, size/S

#5748 fix: storage-list 返回关联的host信息
  pkg/apis/compute/storage.go
  pkg/compute/models/storages.go
Labels: area/region, size/M

#5722 fix: 不再统计已删除资源的标签数量
  pkg/cloudcommon/db/metadata.go
Labels: area/region, size/S

#5772 fix: keystone username duplicate error should return 409
  pkg/keystone/tokens/handlers.go
Labels: area/keystone, size/XS

#5765 region: lbagent: vrrp.advert_int must be the same inside cluster
  pkg/compute/models/loadbalanceragents.go
Labels: area/region, lgtm, size/XS

#5768 Automated cherry pick of #5765: region: lbagent: vrrp.advert_int must be the same inside cluster
  pkg/compute/models/loadbalanceragents.go
Labels: size/XS

#5767 Automated cherry pick of #5765: region: lbagent: vrrp.advert_int must be the same inside cluster
  pkg/compute/models/loadbalanceragents.go
Labels: size/XS

#5766 Automated cherry pick of #5765: region: lbagent: vrrp.advert_int must be the same inside cluster
  pkg/compute/models/loadbalanceragents.go
Labels: size/XS

#5746 proxysetting: add class level test action
  pkg/apis/cloudcommon/proxy/proxy.go
  pkg/cloudcommon/db/proxy/proxysetting.go
Labels: area/region, size/M

#5747 Automated cherry pick of #5746: proxysetting: add class level test action
  pkg/apis/cloudcommon/proxy/proxy.go
  pkg/cloudcommon/db/proxy/proxysetting.go
Labels: size/M

#5774 fix: azure重装系统删除不必要的参数
  pkg/multicloud/azure/instance.go
Labels: approved, area/region, lgtm, size/XS

#5778 Automated cherry pick of #5774: fix: azure重装系统删除不必要的参数
  pkg/multicloud/azure/instance.go
Labels: approved, lgtm, size/XS

#5777 Automated cherry pick of #5774: fix: azure重装系统删除不必要的参数
  pkg/multicloud/azure/instance.go
Labels: approved, lgtm, size/XS

#5775 Automated cherry pick of #5774: fix: azure重装系统删除不必要的参数
  pkg/multicloud/azure/instance.go
Labels: approved, lgtm, size/XS

#5776 Automated cherry pick of #5774: fix: azure重装系统删除不必要的参数
  pkg/multicloud/azure/instance.go
Labels: approved, lgtm

#5780 fix: host jnlp request fail for idrac9
  pkg/baremetal/handler/handlers.go
  pkg/cloudcommon/db/domainresource.go
  pkg/compute/models/hosts.go
Labels: area/baremetal, area/region, size/M

#5781 Automated cherry pick of #5780: fix: host jnlp request fail for idrac9
  pkg/baremetal/handler/handlers.go
  pkg/compute/models/hosts.go
Labels: size/M

#5782 Automated cherry pick of #5780: fix: host jnlp request fail for idrac9
  pkg/baremetal/handler/handlers.go
  pkg/compute/models/hosts.go
Labels: size/M

#5783 Automated cherry pick of #5780: fix: host jnlp request fail for idrac9
  pkg/baremetal/handler/handlers.go
  pkg/compute/models/hosts.go
Labels: size/M

#5758 fix: 允许删除有预留ip的network
  pkg/compute/models/networks.go
Labels: area/region, lgtm, size/M

#5749 fix: support azure policy
  cmd/climc/shell/policy_assignment.go
  cmd/climc/shell/policy_definition.go
  pkg/apis/compute/policy_assignment.go
  pkg/apis/compute/policy_definition.go
  pkg/apis/compute/zz_generated.model.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/guests.go
  pkg/compute/models/policy_assignment.go
  pkg/compute/models/policy_definition.go
  pkg/compute/models/policy_definition_resource.go
  pkg/compute/models/purge.go
  pkg/compute/policy/resources.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/cloud_provider_sync_info_task.go
  pkg/compute/tasks/policy_definition_sync_status_task.go
  pkg/httperrors/consts.go
  pkg/httperrors/errors.go
  pkg/mcclient/modules/mod_policy_assignments.go
  pkg/mcclient/modules/mod_policy_definitions.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/policy.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/shell/policy.go
Labels: lgtm, size/XXL

#5773 feat(notify): Add TNotifyChannel 'feishu'
  pkg/cloudcommon/notifyclient/notify.go
  pkg/mcclient/modules/notify/consts.go
Labels: area/notify, size/XS

#5784 fix: Fix problems about health check in auto scaling
  pkg/compute/tasks/guest_detach_scalinggroup.go
  pkg/controller/autoscaling/health_check.go
Labels: area/region, size/XS

#5759 aws elb bugfix
  pkg/compute/regiondrivers/aws.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
Labels: area/region, lgtm, size/M

#5761 Automated cherry pick of #5759: aws elb bugfix
  pkg/compute/regiondrivers/aws.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
Labels: size/M

#5762 Automated cherry pick of #5759: aws elb bugfix
  pkg/compute/regiondrivers/aws.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
Labels: size/M

#5763 Automated cherry pick of #5759: aws elb bugfix
  pkg/compute/regiondrivers/aws.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
Labels: size/M

#5769 fix host init generate network config
  pkg/hostman/hostinfo/hostinfo.go
Labels: area/host, lgtm, size/M

#5771 Automated cherry pick of #5769: fix host init generate network config
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/M

#5770 Automated cherry pick of #5769: fix host init generate network config
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/M

#5756 fix: 1. allow share proxysetting 2. claim proxsetting as domain resource
  cmd/climc/shell/proxysettings.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/policy/resources.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/proxysettings.go
Labels: approved, area/region, lgtm, size/M

#5792 feature: cas user auto join designated project
  pkg/apis/identity/cas.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/cas/cas_test.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/projects_test.go
  pkg/keystone/models/roles.go
  pkg/keystone/models/users.go
Labels: area/keystone, size/L

#5785 fix: 避免aliyun access key不可用时返回NotFoundError错误
  pkg/multicloud/aliyun/aliyun.go
Labels: area/region, size/XS

#5786 Automated cherry pick of #5785: fix: 避免aliyun access key不可用时返回NotFoundError错误
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS

#5787 Automated cherry pick of #5785: fix: 避免aliyun access key不可用时返回NotFoundError错误
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS

#5788 Automated cherry pick of #5785: fix: 避免aliyun access key不可用时返回NotFoundError错误
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS

#5789 proxysetting: fix validating delete condition
  pkg/cloudcommon/db/proxy/proxysetting.go
Labels: lgtm

#5793 feature: cas user auto join designated project
  pkg/apis/identity/cas.go
  pkg/apis/identity/identityprovider.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/driver.go
  pkg/keystone/driver/ldap/class.go
  pkg/keystone/driver/sql/class.go
  pkg/keystone/models/identity_provider.go
Labels: area/keystone, size/L

#5796 feature: cas user auto join designated project
  pkg/apis/identity/cas.go
  pkg/apis/identity/config.go
  pkg/apis/identity/identityprovider.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/cas/cas_test.go
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/driver.go
  pkg/keystone/driver/ldap/class.go
  pkg/keystone/driver/sql/class.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/projects_test.go
  pkg/keystone/models/roles.go
  pkg/keystone/models/users.go
Labels: area/keystone, size/L

#5798 climc: support k8s service v3.2
  cmd/climc/shell/k8s/event.go
  cmd/climc/shell/k8s/k8s.go
  pkg/apigateway/handler/resource.go
  pkg/mcclient/modulebase/modules.go
  pkg/mcclient/modulebase/resource.go
  pkg/mcclient/modules/k8s/base.go
  pkg/mcclient/modules/k8s/event.go
Labels: area/climc, size/L

#5794 fix(region): Fix the snapshotpolicy info in DiskDetails
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
Labels: area/region, lgtm, size/XS

#5795 Automated cherry pick of #5794: fix(region): Fix the snapshotpolicy info in DiskDetails
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
Labels: size/XS
