Repository yunionio/cloudpods, pull requests merged in 2020-12, with the labels that each got.

#9096 Bugfix/yousong informer
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/models/secgrouprules.go
Labels: area/region, lgtm, size/XS

#9097 Automated cherry pick of #9096: Bugfix/yousong informer
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#9098 Automated cherry pick of #9096: Bugfix/yousong informer
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#9102 fix(region): code gen api error
  pkg/apis/compute/network.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/apis/zz_generated.model.go
  pkg/cloudcommon/db/archs.go
  pkg/compute/models/networks.go
Labels: area/region, size/L

#9103 Automated cherry pick of #9102: fix(region): code gen api error
  pkg/apis/compute/network.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/apis/zz_generated.model.go
  pkg/cloudcommon/db/archs.go
  pkg/compute/models/networks.go
Labels: lgtm, size/L

#9100 Bugfix/yousong qcloud nic
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/instancenic.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/types.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
Labels: approved, area/region, lgtm, size/XXL

#9101 Automated cherry pick of #9100: Bugfix/yousong qcloud nic
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/instancenic.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/types.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#9116 fix(region): delete guest without 'purge' in GuestDetachScalingGroupTask
  pkg/compute/tasks/guest_detach_scalinggroup.go
Labels: approved, area/region, lgtm, size/XS

#9117 Automated cherry pick of #9116: fix(region): delete guest without 'purge' in GuestDetachScalingGroupTask
  pkg/compute/tasks/guest_detach_scalinggroup.go
Labels: size/XS

#9118 Automated cherry pick of #9116: fix(region): delete guest without 'purge' in GuestDetachScalingGroupTask
  pkg/compute/tasks/guest_detach_scalinggroup.go
Labels: size/XS

#9119 Automated cherry pick of #9116: fix(region): delete guest without 'purge' in GuestDetachScalingGroupTask
  pkg/compute/tasks/guest_detach_scalinggroup.go
Labels: size/XS

#9109 fix(host): make sure it won't match vpc guests by accident
  pkg/hostman/guestman/qemu-kvm.go
Labels: area/host, size/XS

#9110 Automated cherry pick of #9109: fix(host): make sure it won't match vpc guests by accident
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#9111 Automated cherry pick of #9109: fix(host): make sure it won't match vpc guests by accident
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#9112 Automated cherry pick of #9109: fix(host): make sure it won't match vpc guests by accident
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#9113 Automated cherry pick of #9109: fix(host): make sure it won't match vpc guests by accident
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#9114 Automated cherry pick of #9109: fix(host): make sure it won't match vpc guests by accident
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#9104 fix(notify): return the result of the second attempt to execute the rpc call
  pkg/notify/rpc/send.go
Labels: area/notify, size/XS

#9105 Automated cherry pick of #9104: fix(notify): return the result of the second attempt to execute the rpc call
  pkg/notify/rpc/send.go
Labels: size/XS

#9106 Automated cherry pick of #9104: fix(notify): return the result of the second attempt to execute the rpc call
  pkg/notify/rpc/send.go
Labels: size/XS

#9107 Automated cherry pick of #9104: fix(notify): return the result of the second attempt to execute the rpc call
  pkg/notify/rpc/send.go
Labels: size/XS

#9123 fix(region): allow delete resource which status is unknown
  pkg/compute/models/buckets.go
  pkg/compute/models/vpcs.go
Labels: area/region, lgtm, size/S

#9124 Automated cherry pick of #9123: fix(region): allow delete resource which status is unknown
  pkg/compute/models/buckets.go
  pkg/compute/models/vpcs.go
Labels: lgtm, size/S

#9125 Automated cherry pick of #9123: fix(region): allow delete resource which status is unknown
  pkg/compute/models/buckets.go
  pkg/compute/models/vpcs.go
Labels: lgtm, size/S

#9092 Automated cherry pick of #9091: fix(region): reserved name checking while create redis account
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/M

#9091 fix(region): reserved name checking while create redis account
  pkg/compute/regiondrivers/managedvirtual.go
Labels: area/region, lgtm, size/M

#9131 fix(cloudid): sync qcloud collaborators user
  pkg/multicloud/qcloud/cam_collaborator.go
  pkg/multicloud/qcloud/cam_user.go
  pkg/multicloud/qcloud/shell/cam_user.go
Labels: area/cloudid, size/M

#9132 Automated cherry pick of #9131: fix(cloudid): sync qcloud collaborators user
  pkg/multicloud/qcloud/cam_collaborator.go
  pkg/multicloud/qcloud/cam_user.go
  pkg/multicloud/qcloud/shell/cam_user.go
Labels: size/M

#9133 Automated cherry pick of #9131: fix(cloudid): sync qcloud collaborators user
  pkg/multicloud/qcloud/cam_collaborator.go
  pkg/multicloud/qcloud/cam_user.go
  pkg/multicloud/qcloud/shell/cam_user.go
Labels: lgtm, size/M

#9061 fix(monitor): delete suggestConfig auto Initialized data
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/models/suggestsysruleconfig.go
Labels: area/monitor, size/M

#9062 Automated cherry pick of #9061: fix(monitor): delete suggestConfig auto init data
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/models/suggestsysruleconfig.go
Labels: lgtm, size/M

#9140 fix(keystone): not allow to disable sql driver
  pkg/keystone/models/identity_provider.go
Labels: area/keystone, size/XS

#9141 Automated cherry pick of #9140: fix(keystone): not allow to disable sql driver
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#9142 Automated cherry pick of #9140: fix(keystone): not allow to disable sql driver
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#9143 Automated cherry pick of #9140: fix(keystone): not allow to disable sql driver
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#9150 fix(region): avoid qcloud sync local disk error
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/localstorage.go
Labels: area/region, size/S

#9151 Automated cherry pick of #9150: fix(region): avoid qcloud sync local disk error
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/localstorage.go
Labels: size/S

#9153 Automated cherry pick of #9150: fix(region): avoid qcloud sync local disk error
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/localstorage.go
Labels: size/S

#9155 Automated cherry pick of #9154: feat(region): add list filter server type
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
Labels: size/S

#9156 Automated cherry pick of #9154: feat(region): add list filter server type
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
Labels: size/S

#9157 Automated cherry pick of #9154: feat(region): add list filter server type
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
Labels: size/S

#9134 fix(region): azure win os defualt user
  pkg/compute/guestdrivers/azure.go
Labels: area/region, size/XS

#9138 fix(monitor): modify influxdbSuggestDriver query err
  pkg/apis/monitor/suggestsysalert.go
  pkg/apis/monitor/suggestsysrule.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/monitor/alerting/conditions/suggestquery.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: area/monitor, size/L

#9139 Automated cherry pick of #9138: fix(monitor): modify influxdbSuggestDriver query err
  pkg/apis/monitor/suggestsysalert.go
  pkg/apis/monitor/suggestsysrule.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/monitor/alerting/conditions/suggestquery.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#9167 Automated cherry pick of #9138: fix(monitor): modify influxdbSuggestDriver query err
  pkg/apis/monitor/suggestsysrule.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/monitor/alerting/conditions/suggestquery.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#9168 Automated cherry pick of #9138: fix(monitor): modify influxdbSuggestDriver query err
  pkg/apis/monitor/suggestsysrule.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/monitor/alerting/conditions/suggestquery.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#9163 bugfix(region): fix list by srever type normal
  pkg/compute/models/guests.go
Labels: area/region, size/XS

#9164 Automated cherry pick of #9163: bugfix(region): fix list by srever type normal
  pkg/compute/models/guests.go
Labels: size/XS

#9165 Automated cherry pick of #9163: bugfix(region): fix list by srever type normal
  pkg/compute/models/guests.go
Labels: size/XS

#9166 Automated cherry pick of #9163: bugfix(region): fix list by srever type normal
  pkg/compute/models/guests.go
Labels: size/XS

#9161 feat(region): huawei recovery new rds
  pkg/cloudprovider/dbinstance.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/dbinstance_backup.go
Labels: area/region, size/M

#9162 Automated cherry pick of #9161: feat(region): huawei recovery new rds
  pkg/cloudprovider/dbinstance.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/huawei/dbinstance_backup.go
Labels: size/M

#9135 feat(cloudid): notify clouduser created
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/content@cn/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/content@en/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/title@cn/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/title@en/CLOUD_USER_CREATED
  pkg/apis/cloudid/clouduser.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/clouduser.go
  pkg/mcclient/options/cloudid/clouduser.go
Labels: area/cloudid, size/M

#9136 Automated cherry pick of #9135: feat(cloudid): notify clouduser created
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/content@cn/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/content@en/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/title@cn/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/title@en/CLOUD_USER_CREATED
  pkg/apis/cloudid/clouduser.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/clouduser.go
  pkg/mcclient/options/cloudid/clouduser.go
Labels: size/M

#9137 Automated cherry pick of #9135: feat(cloudid): notify clouduser created
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/content@cn/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/content@en/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/title@cn/CLOUD_USER_CREATED
  build/cloudid/root/opt/yunion/share/notify_templates/cloudid/title@en/CLOUD_USER_CREATED
  pkg/apis/cloudid/clouduser.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/clouduser.go
  pkg/mcclient/options/cloudid/clouduser.go
Labels: size/M

#9174 Automated cherry pick of #8483: fix: climc vpc-create missing cloudregion_id
  pkg/mcclient/options/vpc.go
Labels: size/S

#9147 feat(region): 多云 bucket website.cors,referer 配置
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/aliyun/shell/cdn.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: area/region, lgtm, size/XL

#9169 Automated cherry pick of #9147: feat(region): 多云 bucket website.cors,referer 配置
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/aliyun/shell/cdn.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: lgtm, size/XL

#9176 fix(scheduler): select resource unordered
  pkg/scheduler/algorithm/predicates/predicates.go
Labels: area/scheduler, size/S

#9177 Automated cherry pick of #9176: fix(scheduler): select resource unordered
  pkg/scheduler/algorithm/predicates/predicates.go
Labels: size/S

#9178 Automated cherry pick of #9176: fix(scheduler): select resource unordered
  pkg/scheduler/algorithm/predicates/predicates.go
Labels: size/S

#9179 Automated cherry pick of #9176: fix(scheduler): select resource unordered
  pkg/scheduler/algorithm/predicates/predicates.go
Labels: size/S

#9184 Hotfix/scheduler tag nil
  pkg/scheduler/algorithm/predicates/predicates.go
Labels: area/scheduler, lgtm, size/XS

#9187 Automated cherry pick of #9184: Hotfix/scheduler tag nil
  pkg/scheduler/algorithm/predicates/predicates.go
Labels: size/XS

#9192 fix(apigateway): allow logout by get method
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/XS

#9193 Automated cherry pick of #9192: fix(apigateway): allow logout by get method
  pkg/apigateway/handler/auth.go
Labels: size/XS

#9194 Automated cherry pick of #9192: fix(apigateway): allow logout by get method
  pkg/apigateway/handler/auth.go
Labels: size/XS

#9180 Bugfix/tb bugfix 1203
  pkg/apis/webconsole/consts.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/multicloud/huawei/instance.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/remote_console.go
Labels: area/region, size/S

#9182 Automated cherry pick of #9180: Bugfix/tb bugfix 1203
  pkg/apis/webconsole/consts.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/multicloud/huawei/instance.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/remote_console.go
Labels: size/S

#9183 fix(region): inspect invalid guest template
  pkg/compute/models/guest_template.go
Labels: area/region, size/XS

#9185 Automated cherry pick of #9183: fix(region): inspect invalid guest template
  pkg/compute/models/guest_template.go
Labels: size/XS

#9186 Automated cherry pick of #9183: fix(region): inspect invalid guest template
  pkg/compute/models/guest_template.go
Labels: size/XS

#9188 Automated cherry pick of #9183: fix(region): inspect invalid guest template
  pkg/compute/models/guest_template.go
Labels: size/XS

#9144 Feature/yousong vpc md
  pkg/appsrv/appsrv.go
  pkg/hostman/host_services.go
  pkg/hostman/metadata/metadatahandler.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/mac/mac.go
Labels: area/host, area/vpcagent, lgtm, size/L

#9145 Automated cherry pick of #9144: Feature/yousong vpc md
  pkg/appsrv/appsrv.go
  pkg/hostman/host_services.go
  pkg/hostman/metadata/metadatahandler.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/mac/mac.go
Labels: size/L

#9083 feat(climc): print json object support array
  pkg/util/printutils/printjson.go
Labels: lgtm, size/M

#9173 Automated cherry pick of #9134: fix(region): azure win os defualt user
  pkg/compute/guestdrivers/azure.go
Labels: size/XS

#9189 fix(region): remove default value of diskConfig.Medium
  pkg/cloudcommon/cmdline/helper_test.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
Labels: area/region, size/XS

#9190 Automated cherry pick of #9189: fix(region): remove default value of diskConfig.Medium
  pkg/cloudcommon/cmdline/helper_test.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
Labels: size/XS

#9191 Automated cherry pick of #9189: fix(region): remove default value of diskConfig.Medium
  pkg/cloudcommon/cmdline/helper_test.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
Labels: size/XS

#9052 feat(region): optimized public image sync
  pkg/cloudprovider/images.go
  pkg/cloudprovider/resources.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/hostdrivers/esxi.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/cloudimages.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/purge.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/storagecaches.go
  pkg/compute/options/options.go
  pkg/compute/service/handlers.go
  pkg/compute/service/service.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/storagecache.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/imageowners.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/azure/image.go
  pkg/multicloud/azure/shell/image.go
  pkg/multicloud/azure/storagecache.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/ctyun/storagecache.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/image.go
  pkg/multicloud/esxi/shell/store.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/template.go
  pkg/multicloud/google/image.go
  pkg/multicloud/google/storagecache.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/storagecache.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/qcloud/storagecache.go
  pkg/multicloud/test/readonly.go
  pkg/multicloud/ucloud/image.go
  pkg/multicloud/ucloud/storagecache.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/storagecache.go
  pkg/scheduler/algorithm/predicates/guest/image_predicate.go
Labels: area/region, size/XL

#9066 feat(region): add wire level for preparing network
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: area/region, lgtm, size/XL

#9067 Automated cherry pick of #9066: feat(region): add wire level for preparing network
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: size/XL

#9198 Automated cherry pick of #9066: feat(region): add wire level for preparing network
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: size/XL

#9196 feat(region): add bucket cloud tags support
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: area/region, lgtm, size/L

#9199 Automated cherry pick of #9196: feat(region): add bucket cloud tags support
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#9200 Automated cherry pick of #9196: feat(region): add bucket cloud tags support
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#9213 refactor(scheduler): remove unused k8s predicates code
  pkg/scheduler/algorithm/predicates/k8s/doc.go
  pkg/scheduler/algorithm/predicates/k8s/host_status_predicate.go
  pkg/scheduler/algorithm/predicates/k8s/k8s.go
  pkg/scheduler/algorithm/predicates/k8s/network_predicate.go
  pkg/scheduler/algorithm/predicates/k8s/volume_predicate.go
Labels: area/scheduler, size/L

#9210 fix(region): azure metric request path
  pkg/multicloud/azure/monitor.go
Labels: area/region, size/XS

#9211 Automated cherry pick of #9210: fix(region): azure metric request path
  pkg/multicloud/azure/monitor.go
Labels: size/XS

#9212 Automated cherry pick of #9210: fix(region): azure metric request path
  pkg/multicloud/azure/monitor.go
Labels: size/XS

#9214 Automated cherry pick of #9213: refactor(scheduler): remove unused k8s predicates code
  pkg/scheduler/algorithm/predicates/k8s/doc.go
  pkg/scheduler/algorithm/predicates/k8s/host_status_predicate.go
  pkg/scheduler/algorithm/predicates/k8s/k8s.go
  pkg/scheduler/algorithm/predicates/k8s/network_predicate.go
  pkg/scheduler/algorithm/predicates/k8s/volume_predicate.go
Labels: size/L

#9215 chore(monitor): delete suggestion files
  pkg/apis/const.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_suggestsysrule.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/monitor/dbinit/suggestrule_dbinit.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/suggestsysruleconfig.go
  pkg/monitor/models/suggestsysruledrivers.go
  pkg/monitor/service/handlers.go
  pkg/monitor/service/service.go
  pkg/monitor/suggestsysdrivers/base.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/doc.go
  pkg/monitor/suggestsysdrivers/driverconfig.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/suggestsysdrivers/osssecacl.go
  pkg/monitor/suggestsysdrivers/ossunreasonable.go
  pkg/monitor/suggestsysdrivers/rdsunreasonable.go
  pkg/monitor/suggestsysdrivers/redisunreasonable.go
  pkg/monitor/suggestsysdrivers/scaledown.go
  pkg/monitor/suggestsysdrivers/secgroupruleinserver.go
  pkg/monitor/suggestsysdrivers/snapshot_unused.go
  pkg/monitor/tasks/resolve_bucket_acl_task.go
  pkg/monitor/tasks/resolve_unused_task.go
Labels: approved, area/monitor, lgtm, size/XXL

#9216 Automated cherry pick of #9215: chore(monitor): delete suggestion files
  pkg/apis/const.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/mod_suggestsysrule.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/monitor/dbinit/suggestrule_dbinit.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/suggestsysruleconfig.go
  pkg/monitor/models/suggestsysruledrivers.go
  pkg/monitor/service/handlers.go
  pkg/monitor/service/service.go
  pkg/monitor/suggestsysdrivers/base.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/doc.go
  pkg/monitor/suggestsysdrivers/driverconfig.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/suggestsysdrivers/osssecacl.go
  pkg/monitor/suggestsysdrivers/ossunreasonable.go
  pkg/monitor/suggestsysdrivers/rdsunreasonable.go
  pkg/monitor/suggestsysdrivers/redisunreasonable.go
  pkg/monitor/suggestsysdrivers/scaledown.go
  pkg/monitor/suggestsysdrivers/secgroupruleinserver.go
  pkg/monitor/suggestsysdrivers/snapshot_unused.go
  pkg/monitor/tasks/resolve_bucket_acl_task.go
  pkg/monitor/tasks/resolve_unused_task.go
Labels: size/XXL

#9217 fix(region): optimized qcloud secgroup sync, only redis need secgroup be in same project
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
Labels: area/region, size/M

#9218 Automated cherry pick of #9217: fix(region): optimized qcloud secgroup sync, only redis need secgroup be in same project
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
Labels: size/M

#9219 Automated cherry pick of #9217: fix(region): optimized qcloud secgroup sync, only redis need secgroup be in same project
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
Labels: size/M

#9202 Bugfix/tb bugfix 1204
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: area/region, size/M

#9203 Automated cherry pick of #9202: Bugfix/tb bugfix 1204
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: size/M

#9206 Automated cherry pick of #9202: Bugfix/tb bugfix 1204
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: size/M

#9205 fix(region): validate invalid character for password
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/cloudid/models/clouduser.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/httperrors/errors.go
  pkg/util/seclib2/seclib.go
  pkg/util/seclib2/seclib_test.go
Labels: area/region, size/XXL

#9208 Automated cherry pick of #9205: fix(region): validate invalid character for password
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/cloudid/models/clouduser.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/httperrors/errors.go
  pkg/util/seclib2/seclib.go
  pkg/util/seclib2/seclib_test.go
Labels: size/XXL

#9209 Automated cherry pick of #9205: fix(region): validate invalid character for password
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/cloudid/models/clouduser.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/httperrors/errors.go
  pkg/util/seclib2/seclib.go
  pkg/util/seclib2/seclib_test.go
Labels: size/XXL

#9237 feat(notify): add webconsole in enabled contact types
  pkg/notify/models/config.go
  pkg/notify/models/receiver.go
Labels: area/notify, size/S

#9238 Automated cherry pick of #9237: feat(notify): add webconsole in enabled contact types
  pkg/notify/models/config.go
  pkg/notify/models/receiver.go
Labels: size/S

#9232 Automated cherry pick of #9231: fix(host): update telegraf conf adapter to container environment
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#9227 fix(region): avoid resize azure disk error
  pkg/multicloud/azure/data_disk.go
  pkg/multicloud/azure/disk.go
  pkg/multicloud/azure/os_disk.go
Labels: approved, area/region, lgtm, size/S

#9228 Automated cherry pick of #9227: fix(region): avoid resize azure disk error
  pkg/multicloud/azure/data_disk.go
  pkg/multicloud/azure/disk.go
  pkg/multicloud/azure/os_disk.go
Labels: size/XS

#9229 Automated cherry pick of #9227: fix(region): avoid resize azure disk error
  pkg/multicloud/azure/data_disk.go
  pkg/multicloud/azure/disk.go
  pkg/multicloud/azure/os_disk.go
Labels: size/S

#9220 fix(region): region qcloud secgroup project id
  pkg/multicloud/qcloud/securitygroup.go
Labels: area/region, size/XS

#9221 Automated cherry pick of #9220: fix(region): region qcloud secgroup project id
  pkg/multicloud/qcloud/securitygroup.go
Labels: size/XS

#9222 Automated cherry pick of #9220: fix(region): region qcloud secgroup project id
  pkg/multicloud/qcloud/securitygroup.go
Labels: size/XS

#9224 Bugfix/tb bugfix 1207
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/loadbalancer.go
Labels: area/region, size/M

#9225 Automated cherry pick of #9224: Bugfix/tb bugfix 1207
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/loadbalancer.go
Labels: size/M

#9226 Automated cherry pick of #9224: Bugfix/tb bugfix 1207
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/loadbalancer.go
Labels: lgtm, size/M

#9240 fix(region): avoid timeout for waiting azure async task
  pkg/multicloud/azure/azure.go
Labels: area/region, size/S

#9241 Automated cherry pick of #9240: fix(region): avoid timeout for waiting azure async task
  pkg/multicloud/azure/azure.go
Labels: size/S

#9242 Automated cherry pick of #9240: fix(region): avoid timeout for waiting azure async task
  pkg/multicloud/azure/azure.go
Labels: size/S

#9243 fix(region): azure reset windows os password
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/shell/instance.go
Labels: area/region, size/M

#9244 Automated cherry pick of #9243: fix(region): azure reset windows os password
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/shell/instance.go
Labels: size/M

#9245 Automated cherry pick of #9243: fix(region): azure reset windows os password
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/shell/instance.go
Labels: size/M

#9248 fix(keystone): oidc driver turn on debug mode if log-level is debug
  pkg/keystone/driver/oidc/oidc.go
Labels: area/keystone, size/XS

#9249 Automated cherry pick of #9248: fix(keystone): oidc driver turn on debug mode if log-level is debug
  pkg/keystone/driver/oidc/oidc.go
Labels: size/XS

#9250 Automated cherry pick of #9248: fix(keystone): oidc driver turn on debug mode if log-level is debug
  pkg/keystone/driver/oidc/oidc.go
Labels: size/XS

#9251 fix(keystone): rolepolicies list panic if filter by domain scope
  pkg/keystone/models/rolepolicies.go
Labels: area/keystone, size/XS

#9252 Automated cherry pick of #9251: fix(keystone): rolepolicies list panic if filter by domain scope
  pkg/keystone/models/rolepolicies.go
Labels: size/XS

#9246 fix(region): fix backup server start task
  pkg/compute/tasks/ha_guest_start_task.go
Labels: size/XS

#9247 Automated cherry pick of #9246: fix(region): fix backup server start task
  pkg/compute/tasks/ha_guest_start_task.go
Labels: size/XS

#9146 fix(keystone): allow refresh scope resource
  cmd/climc/shell/identity/keystone.go
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modules/mod_scope_resource.go
Labels: area/keystone, lgtm, size/L

#9148 Automated cherry pick of #9146: fix(keystone): allow refresh scope resource
  cmd/climc/shell/identity/keystone.go
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modules/mod_scope_resource.go
Labels: size/L

#9149 Automated cherry pick of #9146: fix(keystone): allow refresh scope resource
  cmd/climc/shell/identity/keystone.go
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modules/mod_scope_resource.go
Labels: size/L

#9230 fix(git,make): 修正 gitbranch 变量的获取方式，解决自动升级版本 tag 不统一的问题
  Makefile
  scripts/docker_push.sh
Labels: size/XS

#9256 Automated cherry pick of #9230: fix(git,make): 修正 gitbranch 变量的获取方式，解决自动升级版本 tag 不统一的问题
  Makefile
Labels: size/XS

#9257 Automated cherry pick of #9230: fix(git,make): 修正 gitbranch 变量的获取方式，解决自动升级版本 tag 不统一的问题
  Makefile
Labels: size/XS

#9258 Automated cherry pick of #9230: fix(git,make): 修正 gitbranch 变量的获取方式，解决自动升级版本 tag 不统一的问题
  Makefile
  scripts/docker_push.sh
Labels: size/XS

#9269 Automated cherry pick of #9268: fix(git,make): git branch 获取方式优化
  Makefile
Labels: size/XS

#9270 Automated cherry pick of #9268: fix(git,make): git branch 获取方式优化
  Makefile
Labels: size/XS

#9271 Automated cherry pick of #9268: fix(git,make): git branch 获取方式优化
  Makefile
Labels: size/XS

#9272 fix(host-deployer): cancel rename centos vgname
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/M

#9273 Automated cherry pick of #9272: fix(host-deployer): cancel rename centos vgname
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/M

#9275 Automated cherry pick of #9272: fix(host-deployer): cancel rename centos vgname
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/M

#9274 Automated cherry pick of #9272: fix(host-deployer): cancel rename centos vgname
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/M

#9288 fix(git,make): 更新获取 git branch 的规则
  Makefile
Labels: size/XS

#9290 Automated cherry pick of #9288: fix(git,make): 更新获取 git branch 的规则
  Makefile
Labels: size/XS

#9291 Automated cherry pick of #9288: fix(git,make): 更新获取 git branch 的规则
  Makefile
Labels: size/XS

#9285 fix(region): sync account id
  pkg/compute/models/cloudaccounts.go
Labels: area/region, size/XS

#9286 Automated cherry pick of #9285: fix(region): sync account id
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#9287 Automated cherry pick of #9285: fix(region): sync account id
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#9282 fix(region): restore password validate condition
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/httperrors/errors.go
  pkg/util/seclib2/seclib.go
  pkg/util/seclib2/seclib_test.go
Labels: area/region, size/XXL

#9283 Automated cherry pick of #9282: fix(region): restore password validate condition
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/httperrors/errors.go
  pkg/util/seclib2/seclib.go
  pkg/util/seclib2/seclib_test.go
Labels: size/XXL
