Repository yunionio/cloudpods, pull requests merged in 2020-05, with the labels that each got.

#6166 Automated cherry pick of #6150: fix update input
  pkg/apis/compute/host.go
  pkg/apis/compute/wire.go
Labels: size/S

#6158 bugfix mem paginate
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/region, area/util, lgtm, size/XS

#6162 Automated cherry pick of #6158: bugfix mem paginate
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#6161 Automated cherry pick of #6158: bugfix mem paginate
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#6160 Automated cherry pick of #6158: bugfix mem paginate
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#6159 Automated cherry pick of #6158: bugfix mem paginate
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#6174 fix: fail to fetch real client ip from httprequest
  pkg/util/netutils2/http.go
  pkg/util/netutils2/http_test.go
Labels: area/apigateway, size/M

#6175 Automated cherry pick of #6174: fix: fail to fetch real client ip from httprequest
  pkg/util/netutils2/http.go
  pkg/util/netutils2/http_test.go
Labels: size/M

#6176 Automated cherry pick of #6174: fix: fail to fetch real client ip from httprequest
  pkg/util/netutils2/http.go
  pkg/util/netutils2/http_test.go
Labels: size/M

#6177 Automated cherry pick of #6174: fix: fail to fetch real client ip from httprequest
  pkg/util/netutils2/http.go
  pkg/util/netutils2/http_test.go
Labels: size/M

#6178 Automated cherry pick of #6174: fix: fail to fetch real client ip from httprequest
  pkg/util/netutils2/http.go
  pkg/util/netutils2/http_test.go
Labels: size/M

#6179 fix: shared resource should not be deletable
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablebase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/compute/models/vpcs.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: area/keystone, area/region, lgtm, size/M

#6168 dnsrecords: allow updating only description …
  pkg/compute/models/dnsrecords.go
Labels: area/region, size/M

#6169 Automated cherry pick of #6168: dnsrecords: note that DnsRecordManager is a IAdminSharableVirtualModelManager
  pkg/compute/models/dnsrecords.go
Labels: size/M

#6170 Automated cherry pick of #6168: dnsrecords: note that DnsRecordManager is a IAdminSharableVirtualModelManager
  pkg/compute/models/dnsrecords.go
Labels: size/M

#6171 Automated cherry pick of #6168: dnsrecords: note that DnsRecordManager is a IAdminSharableVirtualModelManager
  pkg/compute/models/dnsrecords.go
Labels: size/M

#6172 Automated cherry pick of #6168: dnsrecords: note that DnsRecordManager is a IAdminSharableVirtualModelManager
  pkg/compute/models/dnsrecords.go
Labels: size/M

#6180 Automated cherry pick of #6179: fix: shared resource should not be deletable
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablebase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/compute/models/vpcs.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
Labels: size/M

#6167 feature: decouple metadata resource and standalone resource
  cmd/climc/shell/projects.go
  cmd/climc/shell/servers.go
  pkg/apis/list.go
  pkg/apis/output.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/cloudcommon/db/standalone.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/servers.go
Labels: area/util, size/L

#6181 fix: shared cloudprovider not accessible
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/S

#6182 Automated cherry pick of #6181: fix: shared cloudprovider not accessible
  pkg/compute/models/cloudproviders.go
Labels: size/S

#6173 mcclient: support custom service url
  pkg/mcclient/mcclient.go
  pkg/mcclient/session.go
Labels: area/util, size/S

#6183 fix: missing perform public/private actionlog
  pkg/cloudcommon/db/sharablebase.go
Labels: area/util, size/XS

#6184 Automated cherry pick of #6183: fix: missing perform public/private actionlog
  pkg/cloudcommon/db/sharablebase.go
Labels: size/XS

#6165 Automated cherry pick of #6164: bugfix mem paginate
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/monitor/models/suggestsysrule.go
Labels: approved, lgtm, size/S

#6191 Automated cherry pick of #5863: 优化邮件格式
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/alerting/notifiers/templates/template.go
  pkg/monitor/alerting/notifiers/templates/util.go
Labels: size/M

#6185 修复谷歌监控无法获取的问题
  pkg/multicloud/google/google.go
  pkg/multicloud/google/monitor.go
Labels: size/S

#6186 Automated cherry pick of #6185: 修复谷歌监控无法获取的问题
  pkg/multicloud/google/google.go
  pkg/multicloud/google/monitor.go
Labels: size/S

#6187 Automated cherry pick of #6185: 修复谷歌监控无法获取的问题
  pkg/multicloud/google/google.go
  pkg/multicloud/google/monitor.go
Labels: size/S

#6188 Automated cherry pick of #6185: 修复谷歌监控无法获取的问题
  pkg/multicloud/google/google.go
  pkg/multicloud/google/monitor.go
Labels: size/S

#6189 Automated cherry pick of #6185: 修复谷歌监控无法获取的问题
  pkg/multicloud/google/google.go
  pkg/multicloud/google/monitor.go
Labels: size/S

#6196 fix: api doc(guests -> servers)
  pkg/compute/models/guests.go
  pkg/monitor/models/notification.go
Labels: area/docs, size/XS

#6194 bugfix: set host list scope system
  pkg/hostman/hostinfo/hostinfo.go
Labels: area/host, size/XS

#6195 Automated cherry pick of #6194: set host list scope system
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#6198 fix: fail to sync share state for on-premise storages
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: area/region, size/S

#6199 Automated cherry pick of #6198: fix: fail to sync share state for on-premise storages
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#6190 apigateway-yunionauth-domain-setting
  pkg/apigateway/handler/auth.go
  pkg/apigateway/options/options.go
Labels: area/apigateway, lgtm, size/S

#6201 Automated cherry pick of #6190: apigateway-yunionauth-domain-setting
  pkg/apigateway/handler/auth.go
  pkg/apigateway/options/options.go
Labels: size/S

#6204 set cookie domain
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/XS

#6193 baremetal: find baremetal add scope system
  pkg/baremetal/pxe/dhcp.go
Labels: area/baremetal, size/XS

#6208 Automated cherry pick of #6193: baremetal: find baremetal add scope system
  pkg/baremetal/pxe/dhcp.go
Labels: size/XS

#6225 apigateway: handlers: register cloudnet modules
  pkg/apigateway/handler/init.go
Labels: area/apigateway, size/S

#6226 Automated cherry pick of #6225: apigateway: handlers: register cloudnet modules
  pkg/apigateway/handler/init.go
Labels: size/S

#6227 Automated cherry pick of #6225: apigateway: handlers: register cloudnet modules
  pkg/apigateway/handler/init.go
Labels: size/S

#6228 Automated cherry pick of #6225: apigateway: handlers: register cloudnet modules
  pkg/apigateway/handler/init.go
Labels: size/S

#6229 Automated cherry pick of #6225: apigateway: handlers: register cloudnet modules
  pkg/apigateway/handler/init.go
Labels: size/S

#6202 Feat/ansible playbook
  build/docker/Dockerfile.ansibleserver-base
  cmd/climc/shell/ansible/ansibleplaybooks_v2.go
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
  pkg/util/ansiblev2/playbook.go
  pkg/util/ansiblev2/playbook_test.go
  pkg/util/ansiblev2/requirements.go
  pkg/util/ansiblev2/requirements_test.go
  pkg/util/ansiblev2/session.go
Labels: area/ansible, lgtm, size/L

#6206 bugfix: bm register use client token
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
  pkg/baremetal/tasks/interface.go
Labels: area/baremetal, size/M

#6207 Automated cherry pick of #6206: bm register use domain token
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
  pkg/baremetal/tasks/interface.go
Labels: size/M

#6211 vpcagent: models: ignore possible external guests
  pkg/vpcagent/models/modelset.go
Labels: area/vpcagent, lgtm, size/XS

#6212 Automated cherry pick of #6211: vpcagent: models: ignore possible external guests
  pkg/vpcagent/models/modelset.go
Labels: size/XS

#6213 vpcagent: ovn: explicitly include gateway route in classless routes
  pkg/vpcagent/ovn/keeper.go
Labels: area/vpcagent, size/XS

#6214 Automated cherry pick of #6213: vpcagent: ovn: explicitly include gateway route in classless routes
  pkg/vpcagent/ovn/keeper.go
Labels: size/XS

#6215 Automated cherry pick of #6213: vpcagent: ovn: explicitly include gateway route in classless routes
  pkg/vpcagent/ovn/keeper.go
Labels: size/XS

#6216 fix: export missing keys && export panic
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storages.go
Labels: area/region, size/M

#6217 Automated cherry pick of #6216: fix: export missing keys && export panic
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancerclusters.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storages.go
Labels: size/M

#6209 fix: missing methods for SDomainRegionalCloudResourceKeys
  pkg/cloudcommon/db/quotas/quotakeys.go
Labels: area/region, size/M

#6210 Automated cherry pick of #6209: fix: missing methods for SDomainRegionalCloudResourceKeys
  pkg/cloudcommon/db/quotas/quotakeys.go
Labels: size/M

#6222 Automated cherry pick of #6221: cloudprovider: add methods for getting http client
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/google/google.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/loader/proxyfunc_test.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/zstack.go
Labels: size/M

#6223 Automated cherry pick of #6221: cloudprovider: add methods for getting http client
  pkg/cloudprovider/cloudprovider.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/google/google.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/loader/proxyfunc_test.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/zstack.go
Labels: size/M

#6240 Automated cherry pick of #6237: fix: guestsecgroup-list panic
  cmd/climc/shell/serversecgroups.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/secgroup.go
  pkg/cloudcommon/db/project.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guestsecgroups.go
  pkg/mcclient/modules/mod_serversecgroups.go
Labels: approved, lgtm, size/L

#6242 disks: reword error message on bad DiskConfig struct
  pkg/compute/models/disks.go
Labels: area/region, size/XS

#6243 Automated cherry pick of #6242: disks: reword error message on bad DiskConfig struct
  pkg/compute/models/disks.go
Labels: size/XS

#6244 Automated cherry pick of #6242: disks: reword error message on bad DiskConfig struct
  pkg/compute/models/disks.go
Labels: size/XS

#6245 Automated cherry pick of #6242: disks: reword error message on bad DiskConfig struct
  pkg/compute/models/disks.go
Labels: size/XS

#6246 Automated cherry pick of #6242: disks: reword error message on bad DiskConfig struct
  pkg/compute/models/disks.go
Labels: size/XS

#6200 Hotfix/qj recode cloud sync public scope
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/share.go
  pkg/apis/share_test.go
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/compute/models/buckets.go
Labels: area/region, size/XL

#6218 Automated cherry pick of #6200: fix: recode sync public_src of cloud resources
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/share.go
  pkg/apis/share_test.go
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/compute/models/buckets.go
Labels: size/XL

#6233 Automated cherry pick of #6232: huawei network id fix
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/huawei/loadbalancer.go
Labels: size/S

#6232 huawei network id fix
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/huawei/loadbalancer.go
Labels: area/region, size/S

#6234 Automated cherry pick of #6232: huawei network id fix
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/huawei/loadbalancer.go
Labels: size/S

#6236 Automated cherry pick of #6232: huawei network id fix
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/huawei/loadbalancer.go
Labels: size/S

#6247 bugfix: fix import from libvirt
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guests.go
Labels: area/climc, area/region, size/M

#6248 Automated cherry pick of #6247: fix import from libvirt
  cmd/climc/shell/servers.go
  pkg/compute/models/guests.go
Labels: size/M

#6249 Automated cherry pick of #6247: fix import from libvirt
  cmd/climc/shell/servers.go
  pkg/compute/models/guests.go
Labels: size/M

#6251 Automated cherry pick of #6247: fix import from libvirt
  cmd/climc/shell/servers.go
  pkg/compute/models/guests.go
Labels: size/M

#6237 fix: guestsecgroup-list panic
  cmd/climc/shell/compute/serversecgroups.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/secgroup.go
  pkg/cloudcommon/db/project.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guestsecgroups.go
  pkg/mcclient/modules/mod_serversecgroups.go
Labels: approved, area/region, lgtm, size/L

#6230 Bugfix/tb bugfix 0508
  pkg/apis/compute/cachedloadbalanceracl.go
  pkg/compute/models/loadbalanceraclresource.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
Labels: approved, area/region, lgtm, size/L

#6231 Automated cherry pick of #6230: lb acl cache add acl filter
  pkg/apis/compute/cachedloadbalanceracl.go
  pkg/compute/models/loadbalanceraclresource.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
Labels: approved, lgtm, size/L

#6252 fix: panic when disk has no valid storage_id
  pkg/compute/models/disks.go
Labels: area/region, size/M

#6256 Automated cherry pick of #6252: fix: panic when disk has no valid storage_id
  pkg/compute/models/disks.go
Labels: size/M

#6253 Automated cherry pick of #6252: fix: panic when disk has no valid storage_id
  pkg/compute/models/disks.go
Labels: size/M

#6254 Automated cherry pick of #6252: fix: panic when disk has no valid storage_id
  pkg/compute/models/disks.go
Labels: size/M

#6255 Automated cherry pick of #6252: fix: panic when disk has no valid storage_id
  pkg/compute/models/disks.go
Labels: size/M

#6220 Automated cherry pick of #6219: fix: 1. vpc, cloudprovider should not violate the sharing limit of cloud account 2. sharing mode of host and attached local storage should be consistent. 3. cannot change owner of shared resource
  cmd/climc/shell/cloudaccounts.go
  cmd/climc/shell/cloudproviders.go
  cmd/climc/shell/globalvpcs.go
  cmd/climc/shell/storages.go
  cmd/climc/shell/vpcs.go
  pkg/cloudcommon/db/domainresource.go
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/storages.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/mcclient/modules/mod_vpcs.go
Labels: size/L

#6219 fix: 1. vpc, cloudprovider should not violate the sharing limit of cl…
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/compute/cloudproviders.go
  cmd/climc/shell/compute/globalvpcs.go
  cmd/climc/shell/compute/storages.go
  cmd/climc/shell/compute/vpcs.go
  pkg/cloudcommon/db/domainresource.go
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/storages.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/mcclient/modules/mod_vpcs.go
Labels: area/region, size/L

#6258 fix: 避免aliyun磁盘计费类型多次转换
  pkg/multicloud/aliyun/charge.go
Labels: area/region, lgtm, size/XS

#6262 Automated cherry pick of #6258: fix: 避免aliyun磁盘计费类型多次转换
  pkg/multicloud/aliyun/charge.go
Labels: size/XS

#6259 Automated cherry pick of #6258: fix: 避免aliyun磁盘计费类型多次转换
  pkg/multicloud/aliyun/charge.go
Labels: size/XS

#6260 Automated cherry pick of #6258: fix: 避免aliyun磁盘计费类型多次转换
  pkg/multicloud/aliyun/charge.go
Labels: size/XS

#6261 Automated cherry pick of #6258: fix: 避免aliyun磁盘计费类型多次转换
  pkg/multicloud/aliyun/charge.go
Labels: size/XS

#6269 Automated cherry pick of #6268: fix: gcp rds 默认不使用vpc网络
  pkg/multicloud/google/dbinstance.go
Labels: size/XS

#6268 fix: gcp rds 默认不使用vpc网络
  pkg/multicloud/google/dbinstance.go
Labels: area/region, size/XS

#6257 fix: create cloudaccount with disabled state
  pkg/apis/input.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: area/region, size/M

#6275 fix: isolated_devices domain filter not working
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
Labels: area/region, size/XS

#6276 Automated cherry pick of #6275: fix: isolated_devices domain filter not working
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
Labels: size/XS

#6270 scheduler: get region nil panic
  pkg/scheduler/data_manager/candidate_manager.go
Labels: area/scheduler, size/XS

#6271 Automated cherry pick of #6270: scheduler: get region nil panic
  pkg/scheduler/data_manager/candidate_manager.go
Labels: size/XS

#6272 Automated cherry pick of #6270: scheduler: get region nil panic
  pkg/scheduler/data_manager/candidate_manager.go
Labels: size/XS

#6273 Automated cherry pick of #6270: scheduler: get region nil panic
  pkg/scheduler/data_manager/candidate_manager.go
Labels: size/XS

#6274 Automated cherry pick of #6270: scheduler: get region nil panic
  pkg/scheduler/data_manager/candidate_manager.go
Labels: size/XS

#6265 fix: 避免卸载完已删除的磁盘后，磁盘状态为ready
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: area/region, size/XS

#6266 Automated cherry pick of #6265: fix: 避免卸载完已删除的磁盘后，磁盘状态为ready
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: size/XS

#6263 fix: globalvpc count vpc
  pkg/apis/compute/globalvpc.go
  pkg/compute/models/globalvpcs.go
Labels: area/region, size/S

#6264 Automated cherry pick of #6263: fix: globalvpc count vpc
  pkg/apis/compute/globalvpc.go
  pkg/compute/models/globalvpcs.go
Labels: size/S

#6282 region: lbagents: fix deleting pending_deleted objects
  pkg/compute/models/loadbalanceragents.go
Labels: area/region, size/S

#6283 Automated cherry pick of #6282: region: lbagents: fix deleting pending_deleted objects
  pkg/compute/models/loadbalanceragents.go
Labels: size/S

#6284 Automated cherry pick of #6282: region: lbagents: fix deleting pending_deleted objects
  pkg/compute/models/loadbalanceragents.go
Labels: size/S

#6285 Automated cherry pick of #6282: region: lbagents: fix deleting pending_deleted objects
  pkg/compute/models/loadbalanceragents.go
Labels: size/S

#6286 Automated cherry pick of #6282: region: lbagents: fix deleting pending_deleted objects
  pkg/compute/models/loadbalanceragents.go
Labels: size/S

#6287 region: lbagent: undeploy: make it idempotent
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: area/region, size/XS

#6288 Automated cherry pick of #6287: region: lbagent: undeploy: make it idempotent
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: size/XS

#6289 Automated cherry pick of #6287: region: lbagent: undeploy: make it idempotent
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: size/XS

#6290 Automated cherry pick of #6287: region: lbagent: undeploy: make it idempotent
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: size/XS

#6291 Automated cherry pick of #6287: region: lbagent: undeploy: make it idempotent
  pkg/compute/models/loadbalanceragents_deploy.go
Labels: size/XS

#6224 feature: guest set login account
  pkg/apis/compute/api.go
  pkg/baremetal/manager.go
  pkg/compute/models/guests.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/mcclient/options/servers.go
Labels: lgtm, size/L

#6277 fix: 支持访问其他服务的标签列表
  pkg/mcclient/modules/mod_metadatas.go
  pkg/mcclient/options/metadata.go
Labels: area/region, size/M

#6278 Automated cherry pick of #6277: fix: 支持访问其他服务的标签列表
  pkg/mcclient/modules/mod_metadatas.go
  pkg/mcclient/options/metadata.go
Labels: size/M

#6280 cloudcommon: elect: notifyOne on subscribe
  pkg/cloudcommon/elect/elect.go
Labels: area/region, area/util, size/M

#6281 Automated cherry pick of #6280: cloudcommon: elect: notifyOne on subscribe
  pkg/cloudcommon/elect/elect.go
Labels: size/M

#6292 fix: 优化openstack错误处理
  pkg/multicloud/openstack/host.go
Labels: area/region, size/M

#6293 Automated cherry pick of #6292: fix: 优化openstack错误处理
  pkg/multicloud/openstack/host.go
Labels: size/M

#6294 Automated cherry pick of #6292: fix: 优化openstack错误处理
  pkg/multicloud/openstack/host.go
Labels: size/M

#6295 Automated cherry pick of #6292: fix: 优化openstack错误处理
  pkg/multicloud/openstack/host.go
Labels: size/M

#6296 Automated cherry pick of #6292: fix: 优化openstack错误处理
  pkg/multicloud/openstack/host.go
Labels: size/M

#6317 fix: reserved ip owner filter
  pkg/compute/models/reservedips.go
Labels: area/region, size/S

#6318 Automated cherry pick of #6317: fix: reserved ip owner filter
  pkg/compute/models/reservedips.go
Labels: size/S

#6315 fix: i-ps -> ips
  pkg/mcclient/modules/mod_reservedips.go
Labels: needs-area, size/XS

#6316 Automated cherry pick of #6315: fix: i-ps -> ips
  pkg/mcclient/modules/mod_reservedips.go
Labels: size/XS

#6306 fix: openstack 安全组规则同步
  pkg/multicloud/openstack/securitygroup.go
Labels: area/region, size/S

#6309 Automated cherry pick of #6306: fix: openstack 安全组规则同步
  pkg/multicloud/openstack/securitygroup.go
Labels: size/S

#6310 Automated cherry pick of #6306: fix: openstack 安全组规则同步
  pkg/multicloud/openstack/securitygroup.go
Labels: size/S

#6311 Automated cherry pick of #6306: fix: openstack 安全组规则同步
  pkg/multicloud/openstack/securitygroup.go
Labels: size/S

#6312 Automated cherry pick of #6306: fix: openstack 安全组规则同步
  pkg/multicloud/openstack/securitygroup.go
Labels: size/S

#6313 Automated cherry pick of #6306: fix: openstack 安全组规则同步
  pkg/multicloud/openstack/securitygroup.go
Labels: size/S

#6300 fix: 避免provider错乱返回
  pkg/compute/models/hostresource.go
  pkg/compute/models/managedresource.go
Labels: area/region, size/S

#6241 feature: user login into project with highest privilege automatically
  pkg/apigateway/handler/auth.go
  pkg/mcclient/catalog.go
  pkg/mcclient/token.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
Labels: area/apigateway, size/L

#6279 Automated cherry pick of #6241: feature: user login into project with highest privilege automatically
  pkg/apigateway/handler/auth.go
  pkg/mcclient/catalog.go
  pkg/mcclient/token.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
Labels: size/L

#6297 fix: cloud-provider-list support filter by cloudregion
  cmd/climc/shell/compute/cloudproviders.go
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/S

#6298 Automated cherry pick of #6297: fix: cloud-provider-list support filter by cloudregion
  cmd/climc/shell/cloudproviders.go
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#6301 Automated cherry pick of #6300: fix: 避免provider错乱返回
  pkg/compute/models/hostresource.go
  pkg/compute/models/managedresource.go
Labels: size/S

#6302 vpcagent: ignore possible external subnets
  pkg/vpcagent/models/modelset.go
Labels: area/vpcagent, size/XS

#6303 Automated cherry pick of #6302: vpcagent: ignore possible external subnets
  pkg/vpcagent/models/modelset.go
Labels: size/XS

#6304 Automated cherry pick of #6302: vpcagent: ignore possible external subnets
  pkg/vpcagent/models/modelset.go
Labels: size/XS

#6305 fix: change-owner-candidate-domains not implemented for some resources
  cmd/climc/shell/compute/disks.go
  cmd/climc/shell/compute/loadbalancers.go
  cmd/climc/shell/compute/servers.go
  pkg/cloudcommon/db/sharablebase.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstanceresource.go
  pkg/compute/models/diskresource.go
  pkg/compute/models/elasticcacheresource.go
  pkg/compute/models/guestresource.go
  pkg/compute/models/hostresource.go
  pkg/compute/models/loadbalancerresource.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/natgatewayresource.go
  pkg/compute/models/networkresource.go
  pkg/compute/models/storageresource.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/wireresource.go
Labels: area/region, size/L

#6314 Automated cherry pick of #6305: fix: change-owner-candidate-domains not implemented for some resources
  cmd/climc/shell/disks.go
  cmd/climc/shell/loadbalancers.go
  cmd/climc/shell/servers.go
  pkg/cloudcommon/db/sharablebase.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstanceresource.go
  pkg/compute/models/diskresource.go
  pkg/compute/models/elasticcacheresource.go
  pkg/compute/models/guestresource.go
  pkg/compute/models/hostresource.go
  pkg/compute/models/loadbalancerresource.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/natgatewayresource.go
  pkg/compute/models/networkresource.go
  pkg/compute/models/storageresource.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/wireresource.go
Labels: size/L

#6319 bugfix: do not close appsrv worker chan
  pkg/appsrv/workers.go
Labels: approved, area/util, lgtm, size/XS

#6323 Automated cherry pick of #6319: do not close worker chan
  pkg/appsrv/workers.go
Labels: approved, lgtm, size/XS

#6322 Automated cherry pick of #6319: do not close worker chan
  pkg/appsrv/workers.go
Labels: approved, lgtm, size/XS

#6320 Automated cherry pick of #6319: do not close worker chan
  pkg/appsrv/workers.go
Labels: approved, lgtm, size/XS
