Repository yunionio/cloudpods, pull requests merged in 2020-08, with the labels that each got.

#7438 fix: sync share mode between vpc and wire
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/wires.go
Labels: area/region, size/M

#7439 Automated cherry pick of #7438: fix: sync share mode between vpc and wire
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/wires.go
Labels: size/M

#7440 Automated cherry pick of #7438: fix: sync share mode between vpc and wire
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/wires.go
Labels: size/M

#7435 Bugfix/tb bugfix 0730
  pkg/compute/regiondrivers/aws.go
  pkg/compute/tasks/elasticcache_account_reset_password_task.go
Labels: area/region, size/S

#7436 Automated cherry pick of #7435: loadblancer listener modify name fix
  pkg/compute/regiondrivers/aws.go
  pkg/compute/tasks/elasticcache_account_reset_password_task.go
Labels: size/S

#7437 Automated cherry pick of #7435: loadblancer listener modify name fix
  pkg/compute/regiondrivers/aws.go
  pkg/compute/tasks/elasticcache_account_reset_password_task.go
Labels: size/S

#7421 Automated cherry pick of #7416: fix(region): Don't allow address conflicts under vpc
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S

#7416 fix(region): Don't allow address conflicts under vpc
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: area/region, size/S

#7419 Automated cherry pick of #7416: fix(region): Don't allow address conflicts under vpc
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S

#7424 Automated cherry pick of #7416: fix(region): Don't allow address conflicts under vpc
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S

#7452 fix: elasticcache_account_reset_password_task.go cherry pick build fail
  pkg/compute/tasks/elasticcache_account_reset_password_task.go
Labels: area/region, size/XS

#7459 bugfix: fix cache non lvm disks
  pkg/hostman/diskutils/diskutils.go
Labels: approved, area/host, lgtm, size/XS

#7463 Automated cherry pick of #7459: fix cache non lvm disks
  pkg/hostman/diskutils/diskutils.go
Labels: approved, lgtm, size/XS

#7464 Automated cherry pick of #7459: fix cache non lvm disks
  pkg/hostman/diskutils/diskutils.go
Labels: approved, lgtm, size/XS

#7462 Automated cherry pick of #7459: fix cache non lvm disks
  pkg/hostman/diskutils/diskutils.go
Labels: approved, lgtm, size/XS

#7461 Automated cherry pick of #7459: fix cache non lvm disks
  pkg/hostman/diskutils/diskutils.go
Labels: approved, lgtm

#7460 Automated cherry pick of #7459: fix cache non lvm disks
  pkg/hostman/diskutils/diskutils.go
Labels: approved, lgtm

#7457 Automated cherry pick of #7456: fix reauth condition on influxdb not found
  pkg/compute/service/influxdb.go
Labels: approved, lgtm, size/XS

#7458 Automated cherry pick of #7456: fix reauth condition on influxdb not found
  pkg/compute/service/influxdb.go
Labels: approved, lgtm, size/XS

#7456 bugfix: fix reauth condition on influxdb not found
  pkg/compute/service/influxdb.go
Labels: approved, area/region, lgtm, size/XS

#7465 fix: avoid host globalid change
  pkg/multicloud/google/host.go
Labels: approved, area/region, lgtm, size/XS

#7467 Automated cherry pick of #7465: fix: avoid host globalid change
  pkg/multicloud/google/host.go
Labels: approved, lgtm, size/XS

#7466 Automated cherry pick of #7465: fix: avoid host globalid change
  pkg/multicloud/google/host.go
Labels: approved, lgtm, size/XS

#7455 fix: avoid generated codes having duplicate PerformSetScope methods
  pkg/apis/compute/zz_generated.model.go
  pkg/cloudcommon/db/scoperesource.go
  pkg/compute/models/schedtags.go
  pkg/monitor/models/commonalert.go
Labels: area/monitor, area/region, size/S

#7454 Automated cherry pick of #7453: opt(scheduler): better sort for hosts when selectHost
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/manager/instancegroup_select.go
Labels: size/M

#7453 opt(scheduler): better sort for hosts when selectHost
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/manager/instancegroup_select.go
Labels: area/scheduler, size/M

#7448 Automated cherry pick of #7447: aws elb listener&rule name too long fix
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
Labels: size/XS

#7447 aws elb listener&rule name too long fix
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
Labels: area/region, size/XS

#7449 Automated cherry pick of #7447: aws elb listener&rule name too long fix
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
Labels: size/XS

#7450 Automated cherry pick of #7447: aws elb listener&rule name too long fix
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
Labels: size/XS

#7451 Automated cherry pick of #7447: aws elb listener&rule name too long fix
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
Labels: size/XS

#7468 Automated cherry pick of #7455: fix: avoid generated codes having duplicate PerformSetScope methods
  pkg/apis/compute/zz_generated.model.go
  pkg/cloudcommon/db/scoperesource.go
  pkg/compute/models/schedtags.go
  pkg/monitor/models/commonalert.go
Labels: size/S

#7469 update apis generate model
  pkg/apis/cloudid/zz_generated.model.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/apis/zz_generated.model.go
Labels: size/L

#7471 Automated cherry pick of #7470: fix: ignore bucket-set-acl not implemented error
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#7470 fix: ignore bucket-set-acl not implemented error
  pkg/multicloud/objectstore/objectstore.go
Labels: approved, area/region, lgtm, size/XS

#7472 Automated cherry pick of #7470: fix: ignore bucket-set-acl not implemented error
  pkg/multicloud/objectstore/objectstore.go
Labels: size/XS

#7473 feature: add is_auto_alloc flag to networks
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/cloudcommon/agent/agent.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/wires.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/modules/mod_networks.go
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: approved, area/region, lgtm, size/M

#7478 Automated cherry pick of #7477: fix: filter public network count by zone and region
  pkg/compute/models/capabilities.go
Labels: size/M

#7477 fix: filter public network count by zone and region
  pkg/compute/models/capabilities.go
Labels: approved, area/region, lgtm, size/M

#7474 fix: typo
  pkg/compute/regiondrivers/aliyun.go
Labels: area/region, size/XS

#7475 Automated cherry pick of #7474: fix: typo
  pkg/compute/regiondrivers/aliyun.go
Labels: size/XS

#7476 Automated cherry pick of #7474: fix: typo
  pkg/compute/regiondrivers/aliyun.go
Labels: size/XS

#7479 fix: typo running_geusts => running_guests
  pkg/apis/compute/host.go
Labels: area/region, size/XS

#7480 Automated cherry pick of #7479: fix: typo running_geusts => running_guests
  pkg/apis/compute/host.go
Labels: size/XS

#7481 Automated cherry pick of #7479: fix: typo running_geusts => running_guests
  pkg/apis/compute/host.go
Labels: size/XS

#7482 fix: unlink-user illegal mix of collations
  pkg/keystone/models/users.go
Labels: approved, area/keystone, lgtm, size/XS

#7483 fix: capabilities get auto alloc network count
  pkg/compute/models/capabilities.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/zones.go
Labels: approved, area/region, lgtm, size/M

#7446 feature: OpenID Connect provider support
  cmd/climc/shell/identity/credentials.go
  pkg/apigateway/clientman/authtoken.go
  pkg/apigateway/clientman/authtoken_test.go
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/middleware.go
  pkg/apigateway/handler/oidc.go
  pkg/apis/identity/aksk.go
  pkg/keystone/driver/oidc/oidc.go
  pkg/keystone/models/credentials.go
  pkg/mcclient/modules/mod_credentials.go
  pkg/util/oidcutils/client/client.go
  pkg/util/oidcutils/types.go
Labels: approved, area/apigateway, area/keystone, lgtm, size/XL

#7484 fix host info get sshkey
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, area/host, lgtm, size/XS

#7485 Automated cherry pick of #7484: fix host info get sshkey
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#7486 Automated cherry pick of #7484: fix host info get sshkey
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#7488 fix: idp validate config not complete
  pkg/apis/identity/identityprovider.go
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/driver.go
  pkg/keystone/driver/ldap/class.go
  pkg/keystone/driver/oauth2/alipay/factory.go
  pkg/keystone/driver/oauth2/class.go
  pkg/keystone/driver/oauth2/dingtalk/factory.go
  pkg/keystone/driver/oauth2/feishu/factory.go
  pkg/keystone/driver/oauth2/qywechat/factory.go
  pkg/keystone/driver/oauth2/qywechat/qywechat.go
  pkg/keystone/driver/oauth2/types.go
  pkg/keystone/driver/oauth2/wechat/factory.go
  pkg/keystone/driver/oidc/class.go
  pkg/keystone/driver/saml/class.go
  pkg/keystone/driver/sql/class.go
  pkg/keystone/models/identity_provider.go
Labels: approved, area/keystone, lgtm, size/L

#7495 fix: do not search response key if empty json returned
  pkg/util/httputils/httputils.go
Labels: approved, area/util, lgtm, size/XS

#7491 fix: support AzureAD oidc in china area
  pkg/apis/identity/oidc.go
  pkg/keystone/driver/oidc/oidc.go
Labels: area/keystone, size/S

#7492 fix: 增加openstack兼容性
  pkg/multicloud/openstack/hypervisor.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/zone.go
Labels: approved, area/region, lgtm, size/S

#7493 Automated cherry pick of #7492: fix: 增加openstack兼容性
  pkg/multicloud/openstack/hypervisor.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/zone.go
Labels: approved, lgtm, size/S

#7494 Automated cherry pick of #7492: fix: 增加openstack兼容性
  pkg/multicloud/openstack/hypervisor.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/zone.go
Labels: approved, lgtm, size/S

#7490 fix: OpenID Connect provider support improvements
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/oidc.go
  pkg/apigateway/options/options.go
  pkg/util/oidcutils/client/client.go
Labels: approved, area/apigateway, lgtm, size/M

#7505 feat: Add BatchSendMessage for feishu SDK
  pkg/monitor/notifydrivers/feishu/client.go
  pkg/monitor/notifydrivers/feishu/types.go
Labels: area/monitor, size/M

#7501 fix: 提高zstack认证兼容性
  pkg/multicloud/zstack/zstack.go
Labels: area/region, size/XS

#7502 Automated cherry pick of #7501: fix: 提高zstack认证兼容性
  pkg/multicloud/zstack/zstack.go
Labels: size/XS

#7503 Automated cherry pick of #7501: fix: 提高zstack认证兼容性
  pkg/multicloud/zstack/zstack.go
Labels: size/XS

#7498 fix: 隐藏auzre经典类型存储
  pkg/multicloud/azure/classic_storage.go
Labels: area/region, size/XS

#7499 Automated cherry pick of #7498: fix: 隐藏auzre经典类型存储
  pkg/multicloud/azure/classic_storage.go
Labels: size/XS

#7500 Automated cherry pick of #7498: fix: 隐藏auzre经典类型存储
  pkg/multicloud/azure/classic_storage.go
Labels: size/XS

#7504 fix: backport fix
  pkg/compute/models/cloudaccounts.go
Labels: area/region, size/XS

#7506 fix: preserve state while doing sso redirect
  pkg/apigateway/handler/idp.go
  pkg/keystone/models/identity_provider.go
Labels: area/apigateway, size/S

#7511 Hotfix/qj password login wrong idp
  pkg/apigateway/clientman/authtoken.go
  pkg/apis/identity/usrext.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/id_mappings.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/users.go
  pkg/keystone/tokens/auth.go
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: approved, area/keystone, lgtm, size/L

#7514 add image upload& s3 upload api
  pkg/apigateway/handler/imageutils.go
  pkg/apigateway/handler/misc.go
Labels: approved, area/apigateway, lgtm, size/L

#7515 Automated cherry pick of #7514: add image upload& s3 upload api
  pkg/apigateway/handler/imageutils.go
  pkg/apigateway/handler/misc.go
Labels: approved, lgtm

#7513 fix: incorrect project user/group count
  pkg/keystone/models/assignments.go
  pkg/keystone/policy/resources.go
Labels: approved, area/keystone, lgtm, size/S

#7509 Automated cherry pick of #7508: fix: avoid nil pointer
  pkg/multicloud/openstack/openstack.go
Labels: size/XS

#7508 fix: avoid nil pointer
  pkg/multicloud/openstack/openstack.go
Labels: approved, area/region, lgtm, size/XS

#7489 modify telegraf reporting tag
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: approved, lgtm, size/M

#7516 Automated cherry pick of #7512: nodealert bugfix：
  pkg/monitor/models/nodealert.go
Labels: size/XS

#7512 nodealert bugfix：
  pkg/monitor/models/nodealert.go
Labels: approved, area/monitor, lgtm, size/XS

#7496 fix: 修复安全组合并导致重复计算虚拟机绑定安全组数量&优化安全组操作
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/secgroup.go
  pkg/apis/compute/secgroup_const.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/guestsecgroups.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/secgroups.go
  pkg/compute/tasks/security_group_delete_task.go
  pkg/mcclient/options/servers.go
Labels: approved, area/region, lgtm, size/XL

#7517 bugfix: set disk status on disk detached
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, area/region, lgtm, size/XS

#7518 Automated cherry pick of #7517: set disk status on disk detached
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, lgtm, size/XS

#7519 Automated cherry pick of #7517: set disk status on disk detached
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: approved, lgtm, size/XS

#7521 Automated cherry pick of #7520: fix: optimized huawei security group get and create operation
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/vpc.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, lgtm, size/M

#7520 fix: optimized huawei security group get and create operation
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/vpc.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, area/region, lgtm, size/M

#7522 Automated cherry pick of #7520: fix: optimized huawei security group get and create operation
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/huawei/shell/vpc.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, lgtm, size/M

#7523 fix: compatible for macOS
  scripts/docker_push.sh
Labels: size/XS

#7525 feature: usage report reserved memory
  pkg/compute/models/hosts.go
  pkg/compute/usages/handler.go
Labels: approved, area/region, lgtm, size/S

#7526 fix: update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/string.go
  vendor/yunion.io/x/jsonutils/utils.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: approved, area/region, lgtm, size/M

#7524 cloudcommon: remove unnecessary joint interface
  pkg/cloudcommon/db/db_joint_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/jointbase.go
  pkg/cloudcommon/db/rbac.go
  pkg/cloudcommon/db/tablespec.go
  pkg/cloudcommon/db/virtualjointbase.go
  pkg/cloudid/models/cloudgroup_policies.go
  pkg/cloudid/models/cloudgroup_users.go
  pkg/cloudid/models/clouduser_policies.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/groupguests.go
  pkg/compute/models/groupnetworks.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/hostnetworks.go
  pkg/compute/models/hostschedtags.go
  pkg/compute/models/hoststorages.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkschedtags.go
  pkg/compute/models/scalinggroup_guest.go
  pkg/compute/models/schedtagjoint.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storages.go
  pkg/compute/models/storageschedtags.go
  pkg/monitor/models/alertnotification.go
Labels: approved, area/region, area/util, lgtm, size/L

#7527 bugfix: fix usage get storage capability
  pkg/compute/models/storages.go
Labels: approved, area/region, lgtm, size/XS

#7529 Automated cherry pick of #7527: fix usage get storage capbility
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/XS

#7528 Automated cherry pick of #7527: fix usage get storage capbility
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/XS

#7530 bugfix: mount xfs lock uuid
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/utils.go
Labels: area/host, size/M

#7536 Automated cherry pick of #7530: fix mount xfs
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/utils.go
Labels: size/M

#7537 Automated cherry pick of #7530: fix mount xfs
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/utils.go
Labels: size/M

#7540 Automated cherry pick of #7530: fix mount xfs
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/utils.go
Labels: size/M

#7539 Automated cherry pick of #7530: fix mount xfs
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/utils.go
Labels: size/M

#7538 Automated cherry pick of #7530: fix mount xfs
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestfs/utils.go
Labels: size/M

#7546 fix: change publicNetworkCount to autoAllocNetworkCount in Capability response
  pkg/compute/models/capabilities.go
Labels: approved, area/region, lgtm, size/S

#7550 scheduler: fix network auto alloc logic
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
Labels: area/scheduler, size/S

#7541 fix: separete enabled and status field
  pkg/multicloud/openstack/hypervisor.go
Labels: area/region, size/S

#7542 Automated cherry pick of #7541: fix: separete enabled and status field
  pkg/multicloud/openstack/hypervisor.go
Labels: size/S

#7543 Automated cherry pick of #7541: fix: separete enabled and status field
  pkg/multicloud/openstack/hypervisor.go
Labels: size/S

#7548 Automated cherry pick of #7547: support diable usb kbd
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/image/images.go
  pkg/apis/compute/api.go
  pkg/apis/image/consts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#7547 feautre: support diable usb kbd
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/image/images.go
  pkg/apis/compute/api.go
  pkg/apis/image/consts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: area/climc, area/host, area/region, size/M

#7551 cloudcommon: remove query for fetchitem when not GET
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/region, lgtm, size/S

#7544 fix: recode user project role list to include group info
  pkg/mcclient/modules/mod_roleassignments.go
Labels: approved, area/apigateway, lgtm, size/M

#7545 fix: oidc auth callback url not complete
  pkg/apigateway/handler/oidc.go
Labels: approved, area/apigateway, lgtm, size/XS

#7552 fix: user with sso idp fail to login with password
  pkg/apigateway/handler/idp.go
  pkg/apigateway/options/options.go
  pkg/apis/identity/usrext.go
  pkg/keystone/models/users.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/token.go
Labels: approved, area/apigateway, area/keystone, lgtm, size/L

#7559 region: validate network auto alloc update data
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/XS

#7553 scheduler: refactor network predicate
  pkg/compute/models/networks.go
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/cache/candidate/base.go
Labels: approved, area/scheduler, lgtm, size/L

#7497 add:openstack loadbalancer
  pkg/apis/compute/loadbalancer_const.go
  pkg/cloudprovider/loadbalancerlistener.go
  pkg/compute/models/cloudsyncelb.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalanceropenstackcachedlbb.go
  pkg/compute/models/loadbalanceropenstackcachedlbbg.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/loadbalancer_backendgroup_create_task.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
  pkg/compute/tasks/loadbalancer_listener_rule_create_task.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/loadbalabcerpool.go
  pkg/multicloud/openstack/loadbalanceracl.go
  pkg/multicloud/openstack/loadbalancerl7policy.go
  pkg/multicloud/openstack/loadbalancerl7rule.go
  pkg/multicloud/openstack/loadbalancerlistener.go
  pkg/multicloud/openstack/loadbalancermember.go
  pkg/multicloud/openstack/loadbalbacer.go
  pkg/multicloud/openstack/loadbalbancerhealthmonitor.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/shell/loadbalancer.go
  pkg/multicloud/openstack/vpc.go
Labels: approved, area/region, lgtm, size/XXL

#7555 Automated cherry pick of #7554: fix: network port count stat recode
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#7556 Automated cherry pick of #7554: fix: network port count stat recode
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#7554 fix: network port count stat recode
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#7558 Automated cherry pick of #7557: fix: Merge the host network correctly when preparenet
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
Labels: approved, lgtm

#7557 fix: Merge the host network correctly when preparenet
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
Labels: approved, area/region, lgtm, size/S

#7561 Automated cherry pick of #7560: fix: avoid virtual resource project id is empty when cloudaccount with no project
  pkg/compute/models/cloudsync.go
Labels: approved, lgtm, size/XS

#7562 Automated cherry pick of #7560: fix: avoid virtual resource project id is empty when cloudaccount with no project
  pkg/compute/models/cloudsync.go
Labels: approved, lgtm, size/XS

#7560 fix: avoid virtual resource project id is empty when cloudaccount wit…
  pkg/compute/models/cloudsync.go
Labels: approved, area/region, lgtm, size/XS

#7567 Automated cherry pick of #7566: fix: init wire domain_id for local vpc
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/XS

#7569 Automated cherry pick of #7566: fix: init wire domain_id for local vpc
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/L

#7566 fix: init wire domain_id for local vpc
  pkg/compute/models/vpcs.go
Labels: approved, area/region, lgtm, size/XS

#7568 bugfix : fix usage reserved memory not set prefix
  pkg/compute/usages/handler.go
Labels: approved, area/region, lgtm, size/XS

#7563 Bugfix/yousong hostman routes
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/iproute2/route.go
  pkg/util/netutils2/netutils_linux.go
Labels: approved, lgtm, size/M

#7573 Automated cherry pick of #7572: fix: aovid duplicate sku name
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#7574 Automated cherry pick of #7572: fix: aovid duplicate sku name
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#7572 fix: aovid duplicate sku name
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/XS

#7585 Bugfix/yousong vpc ext
  pkg/apis/compute/vpcs_ovn.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/names.go
Labels: approved, area/vpcagent, lgtm, size/L

#7576 Automated cherry pick of #7575: fix: GetIImages correctly without 'image_cache' dir
  pkg/multicloud/esxi/storagecache.go
Labels: size/M

#7586 Automated cherry pick of #7585: apis: vpcs_ovn: alloc for interconnects
  pkg/apis/compute/vpcs_ovn.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/names.go
Labels: approved, lgtm, size/L

#7577 Automated cherry pick of #7575: fix: GetIImages correctly without 'image_cache' dir
  pkg/multicloud/esxi/storagecache.go
Labels: size/M

#7578 Automated cherry pick of #7575: fix: GetIImages correctly without 'image_cache' dir
  pkg/multicloud/esxi/storagecache.go
Labels: size/M

#7581 Automated cherry pick of #7580: fix: allow delete shared role and policy
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: size/S

#7582 Automated cherry pick of #7580: fix: allow delete shared role and policy
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: size/S

#7580 fix: allow delete shared role and policy
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: area/keystone, size/S

#7575 fix: GetIImages correctly without 'image_cache' dir
  pkg/multicloud/esxi/storagecache.go
Labels: approved, lgtm, size/M

#7584 feature: do uniqueness check when create/update idp configs
  pkg/keystone/driver/cas/class.go
  pkg/keystone/driver/driver.go
  pkg/keystone/driver/errors.go
  pkg/keystone/driver/ldap/class.go
  pkg/keystone/driver/oauth2/class.go
  pkg/keystone/driver/oidc/class.go
  pkg/keystone/driver/saml/class.go
  pkg/keystone/driver/sql/class.go
  pkg/keystone/models/configs.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/sync.go
Labels: approved, area/keystone, lgtm, size/L

#7588 fix: dns record create ignore is_public field
  pkg/apis/compute/dnsrecord.go
  pkg/apis/input.go
  pkg/cloudcommon/db/adminsharablevirtual.go
  pkg/compute/models/dnsrecords.go
Labels: area/region, size/M

#7589 Automated cherry pick of #7588: fix: dns record create ignore is_public field
  pkg/apis/compute/dnsrecord.go
  pkg/apis/input.go
  pkg/cloudcommon/db/adminsharablevirtual.go
  pkg/compute/models/dnsrecords.go
Labels: approved, lgtm, size/M

#7590 Automated cherry pick of #7588: fix: dns record create ignore is_public field
  pkg/apis/compute/dnsrecord.go
  pkg/apis/input.go
  pkg/cloudcommon/db/adminsharablevirtual.go
  pkg/compute/models/dnsrecords.go
Labels: approved, lgtm

#7591 fix: 修复cloudid用户同步及权限同步
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroupcaches.go
  pkg/cloudid/models/cloudprovider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/cloudpolicy.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/shell/cloudpolicy.go
  pkg/multicloud/google/dbinstance.go
  pkg/multicloud/google/google.go
  pkg/multicloud/qcloud/cam_user.go
Labels: area/cloudid, size/L

#7592 [informer] only notify watched resource
  cmd/climc/shell/watch.go
  pkg/cloudcommon/etcd/etcd.go
  pkg/cloudcommon/etcd/models/base/basemanager.go
  pkg/cloudcommon/etcd/models/base/interface.go
  pkg/cloudcommon/informer/etcd.go
  pkg/cloudcommon/informer/etcd_client.go
  pkg/cloudcommon/informer/handler.go
  pkg/cloudcommon/informer/informer.go
  pkg/compute/models/host_health.go
  pkg/mcclient/informer/watcher.go
Labels: approved, area/util, lgtm, size/L

#7594 climc: add cmd helper to reduce duplicate code
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/helper.go
  cmd/climc/shell/monitor/alert.go
  pkg/mcclient/modulebase/modules.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/monitor/alert.go
  pkg/mcclient/options/servers.go
Labels: area/climc, lgtm, size/XXL

#7593 bugfix : alter table guestcdrom_tbl modify column size bigint
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestcdrom.go
  pkg/compute/tasks/guest_insert_iso_task.go
Labels: approved, area/region, lgtm, size/XS

#7595 fix: option for metadata path
  pkg/cloudid/options/options.go
Labels: approved, area/cloudid, lgtm, size/XS

#7597 fix: member user only can get user & domain resource
  pkg/cloudcommon/db/rbac.go
Labels: approved, area/region, lgtm, size/XS

#7598 Automated cherry pick of #7597: fix: member user only can get user & domain resource
  pkg/cloudcommon/db/rbac.go
Labels: approved, lgtm, size/XS

#7599 fix: 1. remove Azure OIDC extra user scope 2. yunionauth cookie missing
  pkg/apigateway/handler/idp.go
  pkg/keystone/driver/oidc/oidc.go
  pkg/keystone/driver/oidc/template.go
  pkg/util/oidcutils/types.go
Labels: approved, area/apigateway, area/keystone, lgtm, size/M

#7600 fix: opslog filter by owner_project_ids and owner_domain_ids
  cmd/climc/shell/events/events.go
  pkg/cloudcommon/db/opslog.go
Labels: approved, area/util, lgtm, size/M

#7602 Automated cherry pick of #7600: fix: opslog filter by owner_project_ids and owner_domain_ids
  cmd/climc/shell/events.go
  pkg/cloudcommon/db/opslog.go
Labels: approved, lgtm

#7601 Automated cherry pick of #7600: fix: opslog filter by owner_project_ids and owner_domain_ids
  cmd/climc/shell/events/events.go
  pkg/cloudcommon/db/opslog.go
Labels: approved, lgtm
