Repository yunionio/cloudpods, pull requests merged in 2020-01, with the labels that each got.

#4459 fix: openstack image: vmdk -> qcow2
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, area/region, lgtm, size/XS

#4463 Automated cherry pick of #4459: fix: openstack image: vmdk -> qcow2
  pkg/util/openstack/image.go
  pkg/util/openstack/storagecache.go
Labels: approved, lgtm, size/XS

#4461 Automated cherry pick of #4459: fix: openstack image: vmdk -> qcow2
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, lgtm, size/XS

#4462 Automated cherry pick of #4459: fix: openstack image: vmdk -> qcow2
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, lgtm, size/XS

#4460 Automated cherry pick of #4459: fix: openstack image: vmdk -> qcow2
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/storagecache.go
Labels: approved, lgtm, size/XS

#4464 networks: 确保外部network也有ifname_hint
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#4468 Automated cherry pick of #4464: networks: 确保外部network也有ifname_hint
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4466 Automated cherry pick of #4464: networks: 确保外部network也有ifname_hint
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4467 Automated cherry pick of #4464: networks: 确保外部network也有ifname_hint
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4465 Automated cherry pick of #4464: networks: 确保外部network也有ifname_hint
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4469 bundle_libraries.sh: unsetenv LD_PRELOAD
  scripts/bundle_libraries.sh
Labels: approved, area/util, lgtm, size/XS

#4338 腾讯云监控信息获取
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, area/region, lgtm, size/M

#4339 Automated cherry pick of #4338: qcloud监控信息
  go.sum
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/L

#4470 fix: move loadblancer quota from zone to region
  cmd/climc/shell/quotas.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
Labels: approved, area/region, lgtm, size/M

#4471 Automated cherry pick of #4470: fix: move loadblancer quota from zone to region
  cmd/climc/shell/quotas.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
Labels: approved, lgtm, size/M

#4411 host misc fix
  pkg/hostman/hostinfo/hostinfo.go
Labels: area/host, size/S

#4473 Automated cherry pick of #4411: host misc fix
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#4474 fix(region): Add support for suspend when syncing status of guest
  pkg/compute/guestdrivers/managedvirtual.go
Labels: area/region, lgtm, size/XS

#4475 Automated cherry pick of #4474: fix(region): Add support for suspend when syncing status of guest
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#4476 Automated cherry pick of #4474: fix(region): Add support for suspend when syncing status of guest
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#4477 Automated cherry pick of #4474: fix(region): Add support for suspend when syncing status of guest
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#4478 fix: bucket list object may skip first matched object
  pkg/cloudprovider/objectstore.go
Labels: area/region, size/S

#4479 Automated cherry pick of #4478: fix: bucket list object may skip first matched object
  pkg/cloudprovider/objectstore.go
Labels: size/S

#4480 Automated cherry pick of #4478: fix: bucket list object may skip first matched object
  pkg/cloudprovider/objectstore.go
Labels: size/S

#4481 Automated cherry pick of #4478: fix: bucket list object may skip first matched object
  pkg/cloudprovider/objectstore.go
Labels: size/S

#4482 Automated cherry pick of #4478: fix: bucket list object may skip first matched object
  pkg/cloudprovider/objectstore.go
Labels: size/S

#4483 fix(notify): Always update websocket config
  pkg/notify/models/mod_config.go
Labels: area/notify, size/XS

#4484 Automated cherry pick of #4483: fix(notify): Always update websocket config
  pkg/notify/models/mod_config.go
Labels: size/XS

#4485 Automated cherry pick of #4483: fix(notify): Always update websocket config
  pkg/notify/models/mod_config.go
Labels: size/XS

#4486 Automated cherry pick of #4483: fix(notify): Always update websocket config
  pkg/notify/models/mod_config.go
Labels: size/XS

#4487 Automated cherry pick of #4483: fix(notify): Always update websocket config
  pkg/notify/models/mod_config.go
Labels: size/XS

#4488 Hotfix/qj scheduler quota support
  cmd/climc/shell/quotas.go
  pkg/apis/scheduler/api.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/cloudcommon/db/usages.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/compute/tasks/schedule.go
  pkg/image/models/quotas.go
  pkg/mcclient/modulebase/resource.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
Labels: area/region, area/scheduler, lgtm, size/XL

#4491 Automated cherry pick of #4488: scheduler schedule according to quota limit
  cmd/climc/shell/quotas.go
  pkg/apis/scheduler/api.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/cloudcommon/db/usages.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/compute/tasks/schedule.go
  pkg/image/models/quotas.go
  pkg/mcclient/modulebase/resource.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
Labels: size/XL

#4490 Automated cherry pick of #4488: scheduler schedule according to quota limit
  cmd/climc/shell/quotas.go
  pkg/apis/scheduler/api.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/cloudcommon/db/usages.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/compute/tasks/schedule.go
  pkg/image/models/quotas.go
  pkg/mcclient/modulebase/resource.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
Labels: size/XL

#4489 Automated cherry pick of #4488: scheduler schedule according to quota limit
  cmd/climc/shell/quotas.go
  pkg/apis/scheduler/api.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/quotas/context.go
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/cloudcommon/db/quotas/register.go
  pkg/cloudcommon/db/usages.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/zonequota.go
  pkg/compute/service/service.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/pending_usage.go
  pkg/compute/tasks/schedule.go
  pkg/image/models/quotas.go
  pkg/mcclient/modulebase/resource.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
Labels: size/XL

#4492 fix: 修复provider为空的套餐
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/XS

#4496 Automated cherry pick of #4492: fix: 修复provider为空的套餐
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#4495 Automated cherry pick of #4492: fix: 修复provider为空的套餐
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#4493 Automated cherry pick of #4492: fix: 修复provider为空的套餐
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#4494 Automated cherry pick of #4492: fix: 修复provider为空的套餐
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/XS

#4497 fix(huawei): Add 'X-Project-Id' header for huawei nat reuqest
  pkg/multicloud/huawei/client/modules/mod_dnat_rules.go
  pkg/multicloud/huawei/client/modules/mod_natgateway.go
  pkg/multicloud/huawei/client/modules/mod_snat_rules.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, area/region, lgtm, size/M

#4505 Automated cherry pick of #4497: fix(huawei): Add 'X-Project-ID' header for huawei nat reuqest
  pkg/multicloud/huawei/client/modules/mod_dnat_rules.go
  pkg/multicloud/huawei/client/modules/mod_natgateway.go
  pkg/multicloud/huawei/client/modules/mod_snat_rules.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, lgtm, size/M

#4506 Automated cherry pick of #4497: fix(huawei): Add 'X-Project-ID' header for huawei nat reuqest
  pkg/multicloud/huawei/client/modules/mod_dnat_rules.go
  pkg/multicloud/huawei/client/modules/mod_natgateway.go
  pkg/multicloud/huawei/client/modules/mod_snat_rules.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, lgtm, size/M

#4504 Automated cherry pick of #4497: fix(huawei): Add 'X-Project-ID' header for huawei nat reuqest
  pkg/multicloud/huawei/client/modules/mod_dnat_rules.go
  pkg/multicloud/huawei/client/modules/mod_natgateway.go
  pkg/multicloud/huawei/client/modules/mod_snat_rules.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, lgtm, size/M

#4498 fix: allow delete cloudaccount with auto-sync enabled
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/S

#4503 Automated cherry pick of #4497: fix(huawei): Add 'X-Project-ID' header for huawei nat reuqest
  pkg/multicloud/huawei/client/modules/mod_dnat_rules.go
  pkg/multicloud/huawei/client/modules/mod_natgateway.go
  pkg/multicloud/huawei/client/modules/mod_snat_rules.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/huawei/vpc.go
Labels: approved, lgtm, size/M

#4502 Automated cherry pick of #4498: fix: allow delete cloudaccount with auto-sync enabled
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#4499 Automated cherry pick of #4498: fix: allow delete cloudaccount with auto-sync enabled
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#4500 Automated cherry pick of #4498: fix: allow delete cloudaccount with auto-sync enabled
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#4501 Automated cherry pick of #4498: fix: allow delete cloudaccount with auto-sync enabled
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#4513 fix: 腾讯云不支持描述字段参数
  pkg/multicloud/qcloud/instance.go
Labels: area/region, lgtm, size/XS

#4514 Automated cherry pick of #4513: fix: 腾讯云不支持描述字段参数
  pkg/multicloud/qcloud/instance.go
Labels: approved, lgtm, size/XS

#4515 Automated cherry pick of #4513: fix: 腾讯云不支持描述字段参数
  pkg/multicloud/qcloud/instance.go
Labels: approved, lgtm, size/XS

#4516 Automated cherry pick of #4513: fix: 腾讯云不支持描述字段参数
  pkg/multicloud/qcloud/instance.go
Labels: approved, lgtm, size/XS

#4517 Automated cherry pick of #4513: fix: 腾讯云不支持描述字段参数
  pkg/multicloud/qcloud/instance.go
Labels: approved, lgtm, size/XS

#4518 Automated cherry pick of #4513: fix: 腾讯云不支持描述字段参数
  pkg/multicloud/qcloud/instance.go
Labels: approved, lgtm, size/XS

#4519 Automated cherry pick of #4513: fix: 腾讯云不支持描述字段参数
  pkg/util/qcloud/instance.go
Labels: approved, lgtm, size/XS

#4520 baremetal: fix megaraid check jbod always disabled
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: approved, area/baremetal, lgtm, size/XS

#4521 Automated cherry pick of #4520: baremetal: fix megaraid check jbod always disabled
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#4526 Automated cherry pick of #4520: baremetal: fix megaraid check jbod always disabled
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#4523 Automated cherry pick of #4520: baremetal: fix megaraid check jbod always disabled
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#4522 Automated cherry pick of #4520: baremetal: fix megaraid check jbod always disabled
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#4524 Automated cherry pick of #4520: baremetal: fix megaraid check jbod always disabled
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#4512 Automated cherry pick of #4509: account create bugfix
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/tasks/network_create_task.go
  pkg/compute/tasks/network_delete_task.go
  pkg/multicloud/huawei/obs/conf.go
Labels: approved, lgtm, size/M

#4509 Bugfix/tb bugfix 0102
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/tasks/network_create_task.go
  pkg/compute/tasks/network_delete_task.go
  pkg/multicloud/huawei/obs/conf.go
Labels: approved, area/region, lgtm, size/M

#4510 Automated cherry pick of #4509: account create bugfix
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/tasks/network_create_task.go
  pkg/compute/tasks/network_delete_task.go
  pkg/multicloud/huawei/obs/conf.go
Labels: approved, lgtm, size/M

#4511 Automated cherry pick of #4509: account create bugfix
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/tasks/network_create_task.go
  pkg/compute/tasks/network_delete_task.go
  pkg/multicloud/huawei/obs/conf.go
Labels: approved, lgtm, size/M

#4533 devtool: use public influxdb endpoint
  pkg/devtool/models/actions.go
Labels: area/ansible, lgtm, size/XS

#4534 Automated cherry pick of #4533: devtool: use public influxdb endpoint
  pkg/devtool/models/actions.go
Labels: size/XS

#4539 fix: add cloudprovider capabilities
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/region.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/objectstore/interface.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: area/region, size/L

#4542 Automated cherry pick of #4539: fix: add cloudprovider capabilities
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/region.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/objectstore/interface.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#4543 Automated cherry pick of #4539: fix: add cloudprovider capabilities
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/provider/provider.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/region.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/objectstore/interface.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/provider/provider.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/provider/provider.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/provider/provider.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/provider/provider.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#4535 bugfix: disk list filter guest, add recover on guest shotdown
  pkg/compute/models/disks.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/hostman/guestman/guestman.go
Labels: approved, area/host, area/region, lgtm, size/S

#4538 Automated cherry pick of #4535: fix disk filter by guest
  pkg/compute/models/disks.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/hostman/guestman/guestman.go
Labels: approved, lgtm, size/S

#4536 Automated cherry pick of #4535: fix disk filter by guest
  pkg/compute/models/disks.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/hostman/guestman/guestman.go
Labels: approved, lgtm, size/S

#4537 Automated cherry pick of #4535: fix disk filter by guest
  pkg/compute/models/disks.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/hostman/guestman/guestman.go
Labels: approved, lgtm, size/S

#4553 Bugfix/tb bugfix 0104
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalancers.go
  pkg/mcclient/modules/mod_elasticcache.go
  pkg/mcclient/modules/mod_hosts.go
Labels: approved, area/region, lgtm, size/M

#4556 Automated cherry pick of #4553: elastic account add random password
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalancers.go
  pkg/mcclient/modules/mod_elasticcache.go
  pkg/mcclient/modules/mod_hosts.go
Labels: approved, lgtm, size/M

#4554 Automated cherry pick of #4553: elastic account add random password
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalancers.go
  pkg/mcclient/modules/mod_elasticcache.go
  pkg/mcclient/modules/mod_hosts.go
Labels: approved, lgtm, size/M

#4555 Automated cherry pick of #4553: elastic account add random password
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalancers.go
  pkg/mcclient/modules/mod_elasticcache.go
  pkg/mcclient/modules/mod_hosts.go
Labels: approved, lgtm, size/M

#4579 dockerfile: component use base image
  build/docker/Dockerfile.ansibleserver
  build/docker/Dockerfile.ansibleserver-base
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
  build/docker/Dockerfile.webconsole
  build/docker/Dockerfile.webconsole-base
Labels: area/util, size/M

#4558 fix: openstack eip dissociate optimized
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/shell/port.go
Labels: approved, area/region, lgtm, size/M

#4549 fix: domain quota-list include domain's own quota
  cmd/climc/shell/quotas.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/mcclient/modules/mod_quotas.go
Labels: area/region, size/M

#4550 Automated cherry pick of #4549: fix: domain quota-list include domain's own quota
  cmd/climc/shell/quotas.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/mcclient/modules/mod_quotas.go
Labels: size/M

#4551 Automated cherry pick of #4549: fix: domain quota-list include domain's own quota
  cmd/climc/shell/quotas.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/mcclient/modules/mod_quotas.go
Labels: size/M

#4552 Automated cherry pick of #4549: fix: domain quota-list include domain's own quota
  cmd/climc/shell/quotas.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/quotas.go
  pkg/mcclient/modules/mod_quotas.go
Labels: size/M

#4564 Hotfix/qj minio fail set object metadata
  pkg/multicloud/objectstore/buckets.go
Labels: area/region, size/XS

#4565 Automated cherry pick of #4564: fix: minio fail to set object metadata
  pkg/multicloud/objectstore/buckets.go
Labels: size/XS

#4566 Automated cherry pick of #4564: fix: minio fail to set object metadata
  pkg/multicloud/objectstore/buckets.go
Labels: size/XS

#4567 Automated cherry pick of #4564: fix: minio fail to set object metadata
  pkg/multicloud/objectstore/buckets.go
Labels: size/XS

#4568 Automated cherry pick of #4564: fix: minio fail to set object metadata
  pkg/multicloud/objectstore/buckets.go
Labels: size/XS

#4569 Automated cherry pick of #4564: fix: minio fail to set object metadata
  pkg/multicloud/objectstore/buckets.go
Labels: size/XS

#4563 Automated cherry pick of #4558: fix: openstack eip dissociate optimized
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/shell/port.go
Labels: approved, lgtm, size/M

#4562 Automated cherry pick of #4558: fix: openstack eip dissociate optimized
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/shell/port.go
Labels: approved, lgtm, size/M

#4561 Automated cherry pick of #4558: fix: openstack eip dissociate optimized
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/shell/port.go
Labels: approved, lgtm, size/M

#4560 Automated cherry pick of #4558: fix: openstack eip dissociate optimized
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/shell/port.go
Labels: approved, lgtm, size/M

#4559 Automated cherry pick of #4558: fix: openstack eip dissociate optimized
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/openstack/port.go
  pkg/multicloud/openstack/shell/port.go
Labels: approved, lgtm, size/M

#4581 fix: 修复zstack安全组创建失败问题
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, area/region, lgtm, size/XS

#4582 Automated cherry pick of #4581: fix: 修复zstack安全组创建失败问题
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#4583 Automated cherry pick of #4581: fix: 修复zstack安全组创建失败问题
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#4587 Automated cherry pick of #4581: fix: 修复zstack安全组创建失败问题
  pkg/util/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#4586 Automated cherry pick of #4581: fix: 修复zstack安全组创建失败问题
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#4585 Automated cherry pick of #4581: fix: 修复zstack安全组创建失败问题
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#4584 Automated cherry pick of #4581: fix: 修复zstack安全组创建失败问题
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, lgtm, size/XS

#4557 add cloud account create&update options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, area/climc, lgtm, size/M

#4572 Automated cherry pick of #4557: add cloud account create&update options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#4570 Automated cherry pick of #4557: add cloud account create&update options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#4571 Automated cherry pick of #4557: add cloud account create&update options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#4574 fix: 子网删除忽略弹性网卡
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#4578 Automated cherry pick of #4574: fix: 子网删除忽略弹性网卡
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4577 Automated cherry pick of #4574: fix: 子网删除忽略弹性网卡
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4576 Automated cherry pick of #4574: fix: 子网删除忽略弹性网卡
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#4527 fix: httpclient timeout value cleanup, use notimeout client for oss
  pkg/mcclient/mcclient.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/objectstore/ceph/adminapi.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/xsky/adminapi.go
  pkg/multicloud/ucloud/ufile.go
  pkg/util/httputils/delegate.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
  pkg/util/netutils2/netutils.go
Labels: area/util, size/L

#4528 Automated cherry pick of #4527: fix: httpclient timeout value cleanup, use notimeout client for oss
  pkg/mcclient/mcclient.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/objectstore/ceph/adminapi.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/xsky/adminapi.go
  pkg/multicloud/ucloud/ufile.go
  pkg/util/httputils/delegate.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
  pkg/util/netutils2/netutils.go
Labels: size/L

#4529 Automated cherry pick of #4527: fix: httpclient timeout value cleanup, use notimeout client for oss
  pkg/mcclient/mcclient.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/objectstore/ceph/adminapi.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/xsky/adminapi.go
  pkg/multicloud/ucloud/ufile.go
  pkg/util/httputils/delegate.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
  pkg/util/netutils2/netutils.go
Labels: size/L

#4530 Automated cherry pick of #4527: fix: httpclient timeout value cleanup, use notimeout client for oss
  pkg/mcclient/mcclient.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/objectstore/ceph/adminapi.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/xsky/adminapi.go
  pkg/multicloud/ucloud/ufile.go
  pkg/util/httputils/delegate.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
  pkg/util/netutils2/netutils.go
Labels: size/L

#4531 Automated cherry pick of #4527: fix: httpclient timeout value cleanup, use notimeout client for oss
  pkg/mcclient/mcclient.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/objectstore/ceph/adminapi.go
  pkg/multicloud/objectstore/objectstore.go
  pkg/multicloud/objectstore/xsky/adminapi.go
  pkg/multicloud/ucloud/ufile.go
  pkg/util/httputils/delegate.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
  pkg/util/netutils2/netutils.go
Labels: size/L

#4575 Automated cherry pick of #4574: fix: 子网删除忽略弹性网卡
  pkg/compute/models/networks.go
Labels: lgtm, size/S

#4419 Feature(esxi-agent): Esxi Agent Go Version
  build/docker/Dockerfile.esxi-agent
  build/esxi-agent/root/opt/yunion/share/vmware/ovf.xml
  build/esxi-agent/vars
  cmd/esxi-agent/main.go
  pkg/cloudcommon/agent/agent.go
  pkg/cloudcommon/agent/iagent/doc.go
  pkg/cloudcommon/agent/iagent/interface.go
  pkg/cloudcommon/workmanager/manager.go
  pkg/esxi/agent.go
  pkg/esxi/doc.go
  pkg/esxi/handler/doc.go
  pkg/esxi/handler/handlers.go
  pkg/esxi/options/doc.go
  pkg/esxi/options/options.go
  pkg/esxi/service/doc.go
  pkg/esxi/service/esxi_agent_service.go
  pkg/hostman/diskutils/disk.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_agent.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/imagecachemanager_rbd.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/device.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/logger.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/util/netutils2/netutils.go
  vendor/github.com/vmware/govmomi/ovf/cim.go
  vendor/github.com/vmware/govmomi/ovf/doc.go
  vendor/github.com/vmware/govmomi/ovf/env.go
  vendor/github.com/vmware/govmomi/ovf/envelope.go
  vendor/github.com/vmware/govmomi/ovf/manager.go
  vendor/github.com/vmware/govmomi/ovf/ovf.go
  vendor/modules.txt
Labels: approved, area/esxiagent, lgtm, size/XXL

#4596 Automated cherry pick of #4419: feature(esxi-agent): Esxi Agent Golang
  build/docker/Dockerfile.esxi-agent
  build/esxi-agent/root/opt/yunion/share/vmware/ovf.xml
  build/esxi-agent/vars
  cmd/esxi-agent/main.go
  pkg/cloudcommon/agent/agent.go
  pkg/cloudcommon/agent/iagent/doc.go
  pkg/cloudcommon/agent/iagent/interface.go
  pkg/cloudcommon/workmanager/manager.go
  pkg/esxi/agent.go
  pkg/esxi/doc.go
  pkg/esxi/handler/doc.go
  pkg/esxi/handler/handlers.go
  pkg/esxi/options/doc.go
  pkg/esxi/options/options.go
  pkg/esxi/service/doc.go
  pkg/esxi/service/esxi_agent_service.go
  pkg/hostman/diskutils/disk.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_agent.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/imagecachemanager_rbd.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/device.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/logger.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/util/netutils2/netutils.go
  vendor/github.com/vmware/govmomi/ovf/cim.go
  vendor/github.com/vmware/govmomi/ovf/doc.go
  vendor/github.com/vmware/govmomi/ovf/env.go
  vendor/github.com/vmware/govmomi/ovf/envelope.go
  vendor/github.com/vmware/govmomi/ovf/manager.go
  vendor/github.com/vmware/govmomi/ovf/ovf.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#4588 Bugfix & Feature: SnapshotPolicy
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
Labels: area/region, size/L

#4589 Automated cherry pick of #4588: fix(region): Set normal's snapshotpolicy's status as ready
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
Labels: size/L

#4590 Automated cherry pick of #4588: fix(region): Set normal's snapshotpolicy's status as ready
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
Labels: size/L

#4591 Automated cherry pick of #4588: fix(region): Set normal's snapshotpolicy's status as ready
  pkg/compute/models/disks.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshotpolicydisks.go
Labels: size/L

#4592 fix(region): Fix that 'Can_delete' disappears due to parameter structuring
  pkg/compute/models/groups.go
Labels: area/region, size/XS

#4593 Automated cherry pick of #4592: fix(region): Fix that 'Can_delete' disappears due to parameter structuring
  pkg/compute/models/groups.go
Labels: size/XS

#4594 Automated cherry pick of #4592: fix(region): Fix that 'Can_delete' disappears due to parameter structuring
  pkg/compute/models/groups.go
Labels: size/XS

#4595 Automated cherry pick of #4592: fix(region): Fix that 'Can_delete' disappears due to parameter structuring
  pkg/compute/models/groups.go
Labels: size/XS

#4573 Automated cherry pick of #4557: add cloud account create&update options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#4597 Bugfix/guest template password
  pkg/apis/compute/guesttemplate.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/service_catalog.go
Labels: area/region, size/S

#4598 Automated cherry pick of #4597: fix(region): Add reset_password in guest template's ConfigInfo
  pkg/apis/compute/guesttemplate.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/service_catalog.go
Labels: size/S

#4599 Automated cherry pick of #4597: fix(region): Add reset_password in guest template's ConfigInfo
  pkg/apis/compute/guesttemplate.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/service_catalog.go
Labels: size/S

#4600 Automated cherry pick of #4597: fix(region): Add reset_password in guest template's ConfigInfo
  pkg/apis/compute/guesttemplate.go
  pkg/compute/models/guest_template.go
  pkg/compute/models/service_catalog.go
Labels: size/S

#4602 fix(notify): Fix the error of filter about contact
  pkg/notify/cache/usercache.go
Labels: area/notify, size/XS

#4605 Automated cherry pick of #4602: fix(notify): Fix the error of filter about contacts
  pkg/notify/cache/usercache.go
Labels: size/XS

#4606 Automated cherry pick of #4602: fix(notify): Fix the error of filter about contacts
  pkg/notify/cache/usercache.go
Labels: size/XS

#4607 Automated cherry pick of #4602: fix(notify): Fix the error of filter about contacts
  pkg/notify/cache/usercache.go
Labels: size/XS

#4608 Automated cherry pick of #4602: fix(notify): Fix the error of filter about contacts
  pkg/notify/cache/usercache.go
Labels: size/XS

#4609 fix: 避免仅删除value时,行为演变为删除标签
  pkg/cloudcommon/db/metadata.go
Labels: area/region, size/XS

#4610 Automated cherry pick of #4609: fix: 避免仅删除value时,行为演变为删除标签
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#4612 Automated cherry pick of #4609: fix: 避免仅删除value时,行为演变为删除标签
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#4613 Automated cherry pick of #4609: fix: 避免仅删除value时,行为演变为删除标签
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#4614 Automated cherry pick of #4609: fix: 避免仅删除value时,行为演变为删除标签
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#4618 Automated cherry pick of #4616: fix: huawei uncache image fail
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/storagecache.go
Labels: size/S

#4619 Automated cherry pick of #4616: fix: huawei uncache image fail
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/storagecache.go
Labels: size/S

#4620 Automated cherry pick of #4616: fix: huawei uncache image fail
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/storagecache.go
Labels: size/S

#4621 fix: fmt error
  pkg/compute/models/service_catalog.go
Labels: area/util, size/S

#4622 Automated cherry pick of #4621: fix: fmt error
  pkg/compute/models/service_catalog.go
Labels: size/S

#4623 Automated cherry pick of #4621: fix: fmt error
  pkg/compute/models/service_catalog.go
Labels: size/S

#4624 Automated cherry pick of #4621: fix: fmt error
  pkg/compute/models/service_catalog.go
Labels: size/S
