Repository yunionio/cloudpods, pull requests merged in 2020-07, with the labels that each got.

#6982 fix: capability for cloudid
  pkg/cloudprovider/consts.go
  pkg/compute/models/capabilities.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/google/google.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/qcloud/qcloud.go
Labels: area/region, size/S

#6983 Automated cherry pick of #6982: fix: capability for cloudid
  pkg/cloudprovider/consts.go
  pkg/compute/models/capabilities.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/google/google.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#6903 fix: 修正项目映射同步
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/input.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/guests.go
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlistenerresource.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natstable.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/syncutils.go
  pkg/compute/models/wireresource.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/azure/resourcegroup.go
  pkg/multicloud/esxi/cluster.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/resourcepool.go
  pkg/multicloud/esxi/shell/cluster.go
  pkg/multicloud/esxi/shell/host.go
  pkg/multicloud/esxi/shell/resourcepool.go
  pkg/multicloud/google/project.go
  pkg/multicloud/huawei/enterpriceprojects.go
  pkg/multicloud/openstack/project.go
  pkg/multicloud/qcloud/project.go
Labels: area/region, size/XL

#6968 Automated cherry pick of #6903: fix: 修正项目映射同步
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/input.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/guests.go
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlistenerresource.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natstable.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/syncutils.go
  pkg/compute/models/wireresource.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/azure/resourcegroup.go
  pkg/multicloud/esxi/cluster.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/resourcepool.go
  pkg/multicloud/esxi/shell/cluster.go
  pkg/multicloud/esxi/shell/host.go
  pkg/multicloud/esxi/shell/resourcepool.go
  pkg/multicloud/google/project.go
  pkg/multicloud/huawei/enterpriceprojects.go
  pkg/multicloud/openstack/project.go
  pkg/multicloud/qcloud/project.go
Labels: size/XL

#6969 Automated cherry pick of #6903: fix: 修正项目映射同步
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/input.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/guests.go
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlistenerresource.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natstable.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/syncutils.go
  pkg/compute/models/wireresource.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/azure/resourcegroup.go
  pkg/multicloud/esxi/cluster.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/resourcepool.go
  pkg/multicloud/esxi/shell/cluster.go
  pkg/multicloud/esxi/shell/host.go
  pkg/multicloud/esxi/shell/resourcepool.go
  pkg/multicloud/google/project.go
  pkg/multicloud/huawei/enterpriceprojects.go
  pkg/multicloud/openstack/project.go
  pkg/multicloud/qcloud/project.go
Labels: size/XL

#6990 fix the bug introduced in #6643
  pkg/notify/models/mod_contact.go
Labels: area/notify, size/XS

#6991 Automated cherry pick of #6990: fix the bug introduced in #6643
  pkg/notify/models/mod_contact.go
Labels: size/XS

#6992 Automated cherry pick of #6990: fix the bug introduced in #6643
  pkg/notify/models/mod_contact.go
Labels: size/XS

#6993 Automated cherry pick of #6990: fix the bug introduced in #6643
  pkg/notify/models/mod_contact.go
Labels: size/XS

#6913 add: region/openstack 迁移接入
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/shell/instance.go
Labels: area/region, size/XL

#6985 Automated cherry pick of #6913: add: region/openstack 迁移接入
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/waitstatus.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/shell/instance.go
Labels: size/XL

#6996 copyright api update
  cmd/climc/shell/misc/copyright.go
Labels: area/region, size/XS

#6997 Automated cherry pick of #6996: copyright api update
  cmd/climc/shell/misc/copyright.go
Labels: size/XS

#6988 update jsonutils
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: lgtm, needs-area, size/XS

#6989 Automated cherry pick of #6988: update jsonutils
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: size/XS

#6994 fix: Override Master and Slave for scalinggroup_guest
  pkg/compute/models/scalinggroup_guest.go
Labels: area/region, size/XS

#6999 README: update architecture picture
  README-CN.md
  README.md
  docs/architecture.png
  docs/architecture.svg
Labels: area/util

#6981 monitor: support suggest rule alert config
  cmd/climc/shell/monitor/suggestsysruleconfig.go
  pkg/apigateway/handler/init.go
  pkg/apis/compute/schedtag.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/input.go
  pkg/apis/list.go
  pkg/apis/monitor/suggestsys_const.go
  pkg/apis/monitor/suggestsysrule.go
  pkg/apis/monitor/suggestsysruleconfig.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/apis/output.go
  pkg/apis/zz_generated.model.go
  pkg/cloudcommon/db/scoperesource.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/monitor/suggestsysruleconfig.go
  pkg/monitor/models/helper.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/suggestsysruleconfig.go
  pkg/monitor/models/suggestsysruledrivers.go
  pkg/monitor/options/options.go
  pkg/monitor/service/handlers.go
  pkg/monitor/service/service.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/driverconfig.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/suggestsysdrivers/scaledown.go
  pkg/monitor/suggestsysdrivers/snapshot_unused.go
Labels: area/monitor, size/XXL

#7006 bugfix : bind mount nfs storage path
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: area/host, size/L

#7008 Automated cherry pick of #7006: bind mount nfs storage path
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#7014 Automated cherry pick of #7006: bind mount nfs storage path
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#7016 Automated cherry pick of #7006: bind mount nfs storage path
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#7012 monitor: reduce subscription mysql usage
  pkg/monitor/models/commonalert.go
  pkg/monitor/service/dispatcher.go
  pkg/monitor/service/service.go
  pkg/monitor/subscriptionmodel/subcription.go
Labels: area/monitor, size/M

#7013 Automated cherry pick of #7012: monitor: reduce subscription mysql usage
  pkg/monitor/models/commonalert.go
  pkg/monitor/service/dispatcher.go
  pkg/monitor/service/service.go
  pkg/monitor/subscriptionmodel/subcription.go
Labels: size/M

#6998 fix: manager_id资源隔离获取
  pkg/cloudcommon/db/external.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/host_recycle.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/natstable.go
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkinterfaces.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/compute/models/zones.go
  pkg/compute/regiondrivers/huawei.go
Labels: size/L

#7005 Automated cherry pick of #6998: fix: manager_id资源隔离获取
  pkg/cloudcommon/db/external.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/host_recycle.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/natstable.go
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkinterfaces.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/compute/models/zones.go
  pkg/compute/regiondrivers/huawei.go
Labels: size/L

#7004 Automated cherry pick of #6998: fix: manager_id资源隔离获取
  pkg/cloudcommon/db/external.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/host_recycle.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/natstable.go
  pkg/compute/models/networkinterfacenetwork.go
  pkg/compute/models/networkinterfaces.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/compute/models/zones.go
  pkg/compute/regiondrivers/huawei.go
Labels: size/L

#7000 cluster_id required->optional
  pkg/compute/models/loadbalancerclusterresource.go
Labels: approved, lgtm

#7001 Automated cherry pick of #7000: cluster_d required->optional
  pkg/compute/models/loadbalancerclusterresource.go
Labels: approved, lgtm

#7002 Automated cherry pick of #7000: cluster_d required->optional
  pkg/compute/models/loadbalancerclusterresource.go
Labels: approved, lgtm

#7018 monitor: suggestsysalert add ignore action
  cmd/climc/shell/monitor/suggestsysalert.go
  pkg/apis/monitor/suggestsysalert.go
  pkg/cloudcommon/db/scoperesource.go
  pkg/mcclient/options/monitor/suggestsysalert.go
  pkg/monitor/models/suggestsysalert.go
Labels: area/monitor, size/L

#7017 fix: 修复cloudid同步问题
  pkg/apis/cloudid/clouduser.go
  pkg/apis/input.go
  pkg/apis/list.go
  pkg/apis/output.go
  pkg/cloudcommon/db/statusinfrasuserresource.go
  pkg/cloudcommon/db/statususerresources.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroupcaches.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/options/options.go
  pkg/cloudid/service/service.go
  pkg/cloudid/tasks/sync_cloudgroupcaches_task.go
  pkg/cloudid/tasks/sync_cloudpolicies_task.go
Labels: area/cloudid, area/region, size/XL

#7019 Automated cherry pick of #7017: fix: 修复cloudid同步问题
  pkg/apis/cloudid/clouduser.go
  pkg/apis/input.go
  pkg/apis/list.go
  pkg/apis/output.go
  pkg/cloudcommon/db/statusinfrasuserresource.go
  pkg/cloudcommon/db/statususerresources.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroupcaches.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/options/options.go
  pkg/cloudid/service/service.go
  pkg/cloudid/tasks/sync_cloudgroupcaches_task.go
  pkg/cloudid/tasks/sync_cloudpolicies_task.go
Labels: size/XL

#6961 fix: 优化sku同步逻辑
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/tasks/cloud_account_sync_skus_task.go
Labels: area/region, size/L

#7003 Automated cherry pick of #6961: fix: 优化sku同步逻辑
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/tasks/cloud_account_sync_skus_task.go
Labels: size/L

#7023 add meter modules amount_estimation&daily_bill
  cmd/climc/shell/meter/amount_estimations.go
  cmd/climc/shell/meter/daily_bills.go
  pkg/mcclient/modules/mod_amount_estimations.go
  pkg/mcclient/modules/mod_daily_bills.go
Labels: approved, area/climc, lgtm, size/L

#6986 fix: validate candiate ip for sync-fix-nics
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/M

#6987 Automated cherry pick of #6986: fix: validate candiate ip for sync-fix-nics
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#7020 fix: 优化安全组list速度，并返回rule规则信息
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
Labels: area/region, size/L

#7021 Automated cherry pick of #7020: fix: 优化安全组list速度，并发挥rule规则信息
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
Labels: size/L

#7022 Automated cherry pick of #7020: fix: 优化安全组list速度，并发挥rule规则信息
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
Labels: size/L

#7027 Update Dockerfile.ansibleserver
  build/docker/Dockerfile.ansibleserver
Labels: approved, lgtm, needs-area, size/XS

#7024 suggest cost API
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/suggestsysdrivers/common.go
Labels: area/monitor, size/L

#7028 Automated cherry pick of #7027: Update Dockerfile.ansibleserver
  build/docker/Dockerfile.ansibleserver
Labels: approved, lgtm, size/XS

#7025 Bugfix/qx cloud id fix
  cmd/climc/shell/cloudid/cloudgroup.go
  pkg/apis/cloudid/cloudgroup.go
  pkg/apis/output.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/qcloud/cloudgroup.go
  pkg/multicloud/qcloud/clouduser.go
  pkg/multicloud/qcloud/provider/provider.go
Labels: area/cloudid, size/L

#7026 Automated cherry pick of #7025: fix: clouduser can_delete always be false
  cmd/climc/shell/cloudid/cloudgroup.go
  pkg/apis/cloudid/cloudgroup.go
  pkg/apis/output.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/google/provider/provider.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/qcloud/cloudgroup.go
  pkg/multicloud/qcloud/clouduser.go
  pkg/multicloud/qcloud/provider/provider.go
Labels: size/L

#7029 fix: 避免slave zoneid异常
  pkg/compute/models/skus_tools.go
Labels: area/region, size/XS

#7030 Automated cherry pick of #7029: fix: 避免slave zoneid异常
  pkg/compute/models/skus_tools.go
Labels: size/XS

#7009 fix: 取消aliyun lb scheduler创建限制
  pkg/compute/regiondrivers/aliyun.go
Labels: area/region, size/S

#7010 Automated cherry pick of #7009: fix: 取消aliyun lb scheduler创建限制
  pkg/compute/regiondrivers/aliyun.go
Labels: size/S

#7011 Automated cherry pick of #7009: fix: 取消aliyun lb scheduler创建限制
  pkg/compute/regiondrivers/aliyun.go
Labels: size/S

#7035 add mcclient cloudaccount gcp&huawei bucket
  cmd/climc/shell/compute/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, area/climc, lgtm, size/M

#7037 Automated cherry pick of #7036: fix: cloud account sync may block
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#7034 itsm climc
  cmd/climc/shell/itsm/itsm_extra_process_instance.go
  cmd/climc/shell/itsm/itsm_extra_user.go
  go.mod
  go.sum
  pkg/mcclient/modules/mod_itsm_extra_jira.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: area/climc, needs-area, size/L

#7039 Automated cherry pick of #7036: fix: cloud account sync may block
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#7040 Automated cherry pick of #7036: fix: cloud account sync may block
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#7041 Automated cherry pick of #7036: fix: cloud account sync may block
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#7031 fix: 避免azure同步资源组异常
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/shell/subscription.go
  pkg/multicloud/azure/subscription.go
Labels: area/region, size/M

#7032 Automated cherry pick of #7031: fix: 避免azure同步资源组异常
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/shell/subscription.go
  pkg/multicloud/azure/subscription.go
Labels: size/M

#7033 Automated cherry pick of #7031: fix: 避免azure同步资源组异常
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/shell/subscription.go
  pkg/multicloud/azure/subscription.go
Labels: size/L

#7042 feature: project filter that list jointable projects for user or group
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
Labels: area/keystone, size/S

#7043 Automated cherry pick of #7042: feature: project filter that list jointable projects for user or group
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
Labels: size/S

#7044 Automated cherry pick of #7042: feature: project filter that list jointable projects for user or group
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
Labels: size/S

#7051 Automated cherry pick of #7046: 增加influxdb的tag 的一些filter
  pkg/monitor/models/datasource.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/service/dispatcher.go
Labels: size/M

#7046 增加influxdb的tag 的一些filter
  pkg/monitor/models/datasource.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/service/dispatcher.go
Labels: approved, area/monitor, lgtm, size/M

#7048 fix: cleanup auth error message return by apigateway
  pkg/apigateway/handler/middleware.go
  pkg/keystone/policy/resources.go
Labels: area/apigateway, size/S

#7066 fix: json request 支持自定义匹配err
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/clouduser.go
  pkg/multicloud/huawei/natgateway.go
  pkg/util/httputils/httputils.go
Labels: area/region, lgtm, size/L

#7061 Update docker image onecloud-base and its references
  build/docker/Dockerfile.apigateway
  build/docker/Dockerfile.cloudevent
  build/docker/Dockerfile.cloudid
  build/docker/Dockerfile.cloudnet
  build/docker/Dockerfile.devtool
  build/docker/Dockerfile.esxi-agent
  build/docker/Dockerfile.keystone
  build/docker/Dockerfile.logger
  build/docker/Dockerfile.monitor
  build/docker/Dockerfile.notify
  build/docker/Dockerfile.onecloud-base
  build/docker/Dockerfile.region
  build/docker/Dockerfile.s3gateway
  build/docker/Dockerfile.scheduler
  build/docker/Dockerfile.yunionconf
Labels: lgtm, needs-area, size/M

#7062 Automated cherry pick of #7061: Update docker image onecloud-base and its references
  build/docker/Dockerfile.apigateway
  build/docker/Dockerfile.cloudevent
  build/docker/Dockerfile.cloudid
  build/docker/Dockerfile.cloudnet
  build/docker/Dockerfile.devtool
  build/docker/Dockerfile.esxi-agent
  build/docker/Dockerfile.keystone
  build/docker/Dockerfile.logger
  build/docker/Dockerfile.monitor
  build/docker/Dockerfile.notify
  build/docker/Dockerfile.onecloud-base
  build/docker/Dockerfile.region
  build/docker/Dockerfile.s3gateway
  build/docker/Dockerfile.scheduler
  build/docker/Dockerfile.yunionconf
Labels: size/M

#7063 Automated cherry pick of #7061: Update docker image onecloud-base and its references
  build/docker/Dockerfile.apigateway
  build/docker/Dockerfile.cloudevent
  build/docker/Dockerfile.cloudnet
  build/docker/Dockerfile.devtool
  build/docker/Dockerfile.esxi-agent
  build/docker/Dockerfile.keystone
  build/docker/Dockerfile.logger
  build/docker/Dockerfile.monitor
  build/docker/Dockerfile.notify
  build/docker/Dockerfile.onecloud-base
  build/docker/Dockerfile.region
  build/docker/Dockerfile.s3gateway
  build/docker/Dockerfile.scheduler
  build/docker/Dockerfile.yunionconf
Labels: size/S

#7064 Automated cherry pick of #7061: Update docker image onecloud-base and its references
  build/docker/Dockerfile.apigateway
  build/docker/Dockerfile.cloudevent
  build/docker/Dockerfile.cloudnet
  build/docker/Dockerfile.devtool
  build/docker/Dockerfile.esxi-agent
  build/docker/Dockerfile.keystone
  build/docker/Dockerfile.logger
  build/docker/Dockerfile.monitor
  build/docker/Dockerfile.notify
  build/docker/Dockerfile.onecloud-base
  build/docker/Dockerfile.region
  build/docker/Dockerfile.s3gateway
  build/docker/Dockerfile.scheduler
  build/docker/Dockerfile.yunionconf
Labels: size/S

#7065 Automated cherry pick of #7061: Update docker image onecloud-base and its references
  build/docker/Dockerfile.apigateway
  build/docker/Dockerfile.cloudevent
  build/docker/Dockerfile.cloudnet
  build/docker/Dockerfile.devtool
  build/docker/Dockerfile.esxi-agent
  build/docker/Dockerfile.keystone
  build/docker/Dockerfile.logger
  build/docker/Dockerfile.notify
  build/docker/Dockerfile.onecloud-base
  build/docker/Dockerfile.region
  build/docker/Dockerfile.region-dns
  build/docker/Dockerfile.s3gateway
  build/docker/Dockerfile.scheduler
  build/docker/Dockerfile.yunionconf
Labels: size/S

#7056 vpcagent: ClaimVpcGuestDnsRecords: guard against pending_deleted guests
  pkg/vpcagent/models/models.go
  pkg/vpcagent/ovn/keeper.go
Labels: area/vpcagent, size/S

#7057 Automated cherry pick of #7056: vpcagent: ClaimVpcGuestDnsRecords: guard against pending_deleted guests
  pkg/vpcagent/models/models.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/S

#7067 fix: remove default host list policy
  pkg/compute/policy/defaults.go
Labels: area/region, size/XS

#7068 Automated cherry pick of #7067: fix: remove default host list policy
  pkg/compute/policy/defaults.go
Labels: size/XS

#7074 fix: 分开统计安全组关联虚拟机数量
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
Labels: area/region, size/M

#7075 Automated cherry pick of #7074: fix: 分开统计安全组关联虚拟机数量
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
Labels: size/M

#7076 Automated cherry pick of #7074: fix: 分开统计安全组关联虚拟机数量
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
Labels: size/M

#7077 fix: 修复elastic cache sku zone_id异常问题
  pkg/compute/models/elasticcache_skus.go
Labels: area/region, size/XS

#7078 Automated cherry pick of #7077: fix: 修复elastic cache sku zone_id异常问题
  pkg/compute/models/elasticcache_skus.go
Labels: size/XS

#7050 fix: google rds regional and zonal
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/google/dbinstance.go
Labels: area/region, size/S

#7052 Automated cherry pick of #7050: fix: google rds regional and zonal
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/google/dbinstance.go
Labels: size/S

#7072 Automated cherry pick of #7066: fix: json request 支持自定义匹配err
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/clouduser.go
  pkg/multicloud/huawei/natgateway.go
  pkg/util/httputils/httputils.go
Labels: size/L

#7073 Automated cherry pick of #7066: fix: json request 支持自定义匹配err
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/natgateway.go
  pkg/util/httputils/httputils.go
Labels: size/L

#7071 fix: orderedstring add performance improvements
  pkg/util/stringutils2/sortedstrings.go
  pkg/util/stringutils2/sortedstrings_test.go
Labels: area/util, size/M

#7059 fix: cloud poilcy count
  pkg/cloudid/models/cloudgroup.go
Labels: area/cloudid, size/XS

#7060 Automated cherry pick of #7059: fix: cloud poilcy count
  pkg/cloudid/models/cloudgroup.go
Labels: size/XS

#7054 fix: 避免cloudprovider同步缺失
  pkg/cloudid/models/cloudaccount.go
Labels: area/cloudid, size/M

#7055 Automated cherry pick of #7054: fix: 避免cloudprovider同步缺失
  pkg/cloudid/models/cloudaccount.go
Labels: size/M

#7069 fix: perform private on vpc will private all wires if no networks in wires
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: area/region, size/M

#7070 Automated cherry pick of #6880: feature: 1. allow enable/disable idp-synced-users 2. turn off user's MFA by default
  cmd/climc/shell/identityproviders.go
  pkg/apigateway/options/options.go
  pkg/apis/identity/config.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/ldap/info.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/users.go
Labels: size/M

#7058 suggestAlert cost:modify the request param to meter
  pkg/monitor/models/suggestsysalert.go
Labels: area/monitor, size/XS

#7084 Automated cherry pick of #7069: fix: perform private on vpc will private all wires if no networks in wires
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/M

#7088 fix: 修复azure 项目同步问题
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/azure/azure.go
Labels: area/region, size/L

#7089 Automated cherry pick of #7088: fix: 修复azure 项目同步问题
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/azure/azure.go
Labels: size/L

#7090 Automated cherry pick of #7088: fix: 修复azure 项目同步问题
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/azure/azure.go
Labels: size/L

#7079 fix: 修复腾讯云操作日志时间异常问题
  pkg/multicloud/qcloud/events.go
Labels: area/cloudevent, size/XS

#7080 Automated cherry pick of #7079: fix: 修复腾讯云操作日志时间异常问题
  pkg/multicloud/qcloud/events.go
Labels: size/XS

#7081 Automated cherry pick of #7079: fix: 修复腾讯云操作日志时间异常问题
  pkg/multicloud/qcloud/events.go
Labels: size/XS

#7085 fix: 避免请求中国区iam异常
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/region.go
Labels: area/cloudid, area/region, size/M

#7091 fix: 修复qcloud同步权限组异常问题
  pkg/multicloud/qcloud/clouduser.go
Labels: area/cloudid, size/XS

#7092 Automated cherry pick of #7091: fix: 修复qcloud同步权限组异常问题
  pkg/multicloud/qcloud/clouduser.go
Labels: size/XS

#7093 fix: 修复资源组云上同步异常问题
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/input.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/external_projects.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/aliyun/shell/project.go
  pkg/multicloud/aliyun/shell/resourcegroup.go
  pkg/multicloud/esxi/cluster.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/cluster.go
Labels: area/region, size/L

#7094 Automated cherry pick of #7093: fix: 修复资源组云上同步异常问题
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/input.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/external_projects.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/aliyun/shell/project.go
  pkg/multicloud/aliyun/shell/resourcegroup.go
  pkg/multicloud/esxi/cluster.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/cluster.go
Labels: size/L

#7095 Automated cherry pick of #7093: fix: 修复资源组云上同步异常问题
  pkg/apis/compute/externalproject.go
  pkg/apis/compute/input.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/external_projects.go
  pkg/multicloud/aliyun/project.go
  pkg/multicloud/aliyun/shell/project.go
  pkg/multicloud/aliyun/shell/resourcegroup.go
  pkg/multicloud/esxi/cluster.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/cluster.go
Labels: size/L

#7097 Automated cherry pick of #7083: fix: cloudid 异常修复
  pkg/cloudcommon/db/external.go
  pkg/cloudcommon/db/statusinfrasuserresource.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/models/clouduser_policies.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/cloudgroup.go
  pkg/multicloud/aws/cloudpolicy.go
  pkg/multicloud/aws/clouduser.go
  pkg/multicloud/aws/shell/cloudgroup.go
  pkg/multicloud/aws/shell/clouduser.go
Labels: size/XL

#7082 climc: update k8s-release-create params
  pkg/mcclient/options/k8s/release.go
Labels: area/climc, size/XS

#7083 fix: cloudid 异常修复
  pkg/cloudcommon/db/external.go
  pkg/cloudcommon/db/statusinfrasuserresource.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/models/clouduser_policies.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/cloudgroup.go
  pkg/multicloud/aws/cloudpolicy.go
  pkg/multicloud/aws/clouduser.go
  pkg/multicloud/aws/shell/cloudgroup.go
  pkg/multicloud/aws/shell/clouduser.go
Labels: area/cloudid, size/XL

#7098 fix: cloudid 权限修复
  pkg/apis/cloudid/cloudid.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/policy/defaults.go
  pkg/cloudid/policy/doc.go
  pkg/cloudid/policy/resources.go
  pkg/cloudid/service/service.go
  pkg/cloudid/tasks/clouduser_reset_password_task.go
Labels: area/cloudid, size/L

#7099 Automated cherry pick of #7098: fix: cloudid 权限修复
  pkg/apis/cloudid/cloudid.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/policy/defaults.go
  pkg/cloudid/policy/doc.go
  pkg/cloudid/policy/resources.go
  pkg/cloudid/service/service.go
  pkg/cloudid/tasks/clouduser_reset_password_task.go
Labels: size/L

#7100 fix: remove default allow policy for storages
  pkg/compute/policy/defaults.go
Labels: area/region, size/S

#7101 Automated cherry pick of #7100: fix: remove default allow policy for storages
  pkg/compute/policy/defaults.go
Labels: size/S

#7102 fix: opslog show the owners operation logs only
  pkg/cloudcommon/db/opslog.go
Labels: needs-area, size/S

#7103 Automated cherry pick of #7102: fix: opslog show the owners operation logs only
  pkg/cloudcommon/db/opslog.go
Labels: size/S

#7104 Automated cherry pick of #7102: fix: opslog show the owners operation logs only
  pkg/cloudcommon/db/opslog.go
Labels: size/S

#7096 update vendor
  go.mod
  go.sum
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/monitor/models/datasource.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/scaledown.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
  vendor/yunion.io/x/jsonutils/clone.go
  vendor/yunion.io/x/jsonutils/dict.go
  vendor/yunion.io/x/jsonutils/equals.go
  vendor/yunion.io/x/jsonutils/interface.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/querystring.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/jsonutils/write.go
  vendor/yunion.io/x/pkg/sortedmap/iterator.go
  vendor/yunion.io/x/pkg/sortedmap/sortedmap.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: area/region, lgtm, size/XL

#7105 Automated cherry pick of #7096: update vendor
  go.mod
  go.sum
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/monitor/models/datasource.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/suggestsysdrivers/scaledown.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
  vendor/yunion.io/x/jsonutils/clone.go
  vendor/yunion.io/x/jsonutils/dict.go
  vendor/yunion.io/x/jsonutils/equals.go
  vendor/yunion.io/x/jsonutils/interface.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/querystring.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/jsonutils/write.go
  vendor/yunion.io/x/pkg/sortedmap/iterator.go
  vendor/yunion.io/x/pkg/sortedmap/sortedmap.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: approved, lgtm, size/XL

#7049 add:region/esxi 迁移接口
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/L

#7087 add: region/sync_openstack_routetables
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/router.go
  pkg/multicloud/openstack/routetable.go
  pkg/multicloud/openstack/shell/router.go
  pkg/multicloud/openstack/vpc.go
Labels: approved, area/region, lgtm, size/L

#7106 bugfix: fix set storage info bind mount
  pkg/hostman/storageman/storage_base.go
Labels: area/host, size/XS

#7109 Automated cherry pick of #7106: fix set storage info bind mount
  pkg/hostman/storageman/storage_base.go
Labels: size/XS

#7110 Automated cherry pick of #7106: fix set storage info bind mount
  pkg/hostman/storageman/storage_base.go
Labels: size/XS

#7114 Automated cherry pick of #7113: fix: 避免越界访问
  pkg/multicloud/azure/storage.go
Labels: size/S

#7115 Automated cherry pick of #7113: fix: 避免越界访问
  pkg/multicloud/azure/storage.go
Labels: size/S

#7107 Automated cherry pick of #7106: fix set storage info bind mount
  pkg/hostman/storageman/storage_base.go
Labels: size/XS

#7116 fix: 修复vpc同步异常问题
  pkg/compute/models/cloudregions.go
  pkg/compute/models/vpcs.go
Labels: area/region, size/S

#7117 Automated cherry pick of #7116: fix: 修复vpc同步异常问题
  pkg/compute/models/cloudregions.go
  pkg/compute/models/vpcs.go
Labels: size/S

#7118 Automated cherry pick of #7116: fix: 修复vpc同步异常问题
  pkg/compute/models/cloudregions.go
  pkg/compute/models/vpcs.go
Labels: size/S

#7119 fix: 避免google clouduser同步权限异常
  pkg/cloudid/models/clouduser.go
Labels: area/cloudid, size/M

#7120 Automated cherry pick of #7119: fix: 避免google clouduser同步权限异常
  pkg/cloudid/models/clouduser.go
Labels: size/M

#7121 region misc fix
  pkg/apis/compute/instance_snapshot.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
Labels: area/region, size/M

#7122 Automated cherry pick of #7121: misc fix
  pkg/apis/compute/instance_snapshot.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
Labels: size/M

#7123 hotfix: vpc change owners with wire
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: area/region, size/S

#7124 Automated cherry pick of #7123: hotfix: vpc change owners with wire
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/S

#7111 fix: 支持azure创建订阅
  cmd/climc/shell/compute/cloudaccounts.go
  pkg/apis/cloudid/zz_generated.model.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/apis/zz_generated.model.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/subscription.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/enrollment_account.go
  pkg/multicloud/azure/provider/provider.go
  pkg/multicloud/azure/shell/enrollment_account.go
  pkg/multicloud/azure/shell/subscription.go
Labels: area/region, size/XL

#7134 fix: 优化azure订阅创建
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/subscription.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/azure/enrollment_account.go
Labels: area/region, size/M

#7125 bugfix: add base lockman, fix local storage cache init lock man
  pkg/cloudcommon/db/lockman/base.go
  pkg/cloudcommon/db/lockman/etcd.go
  pkg/cloudcommon/db/lockman/inmemory.go
  pkg/cloudcommon/db/lockman/lockman.go
  pkg/cloudcommon/db/lockman/noop.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: area/host, size/L

#7126 Automated cherry pick of #7125: - fix local storage init local man
  pkg/cloudcommon/db/lockman/base.go
  pkg/cloudcommon/db/lockman/etcd.go
  pkg/cloudcommon/db/lockman/inmemory.go
  pkg/cloudcommon/db/lockman/lockman.go
  pkg/cloudcommon/db/lockman/noop.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/L

#7127 Automated cherry pick of #7125: - fix local storage init local man
  pkg/cloudcommon/db/lockman/base.go
  pkg/cloudcommon/db/lockman/etcd.go
  pkg/cloudcommon/db/lockman/inmemory.go
  pkg/cloudcommon/db/lockman/lockman.go
  pkg/cloudcommon/db/lockman/noop.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/L

#7128 Manual cherry pick of #7125: fix rbd set storage info
  pkg/hostman/storageman/storage_rbd.go
Labels: size/XS

#7129 Manual cherry pick of #7125: fix rbd storage set storage info
  pkg/hostman/storageman/storage_rbd.go
Labels: size/XS

#7130 vendor update: update jsonutils
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/go.mod
  vendor/yunion.io/x/jsonutils/go.sum
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/jsonutils/values.go
Labels: needs-area, size/M

#7132 add cost alert modules
  cmd/climc/shell/meter/costalerts.go
  pkg/mcclient/modules/mod_costalerts.go
Labels: area/climc, size/L

#7133 新增优化建议
  pkg/apis/monitor/suggestsys_const.go
  pkg/apis/monitor/suggestsysalert.go
  pkg/apis/monitor/suggestsysrule.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/suggestsysalert.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/driverconfig.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/suggestsysdrivers/osssecacl.go
  pkg/monitor/suggestsysdrivers/ossunreasonable.go
  pkg/monitor/suggestsysdrivers/rdsunreasonable.go
  pkg/monitor/suggestsysdrivers/redisunreasonable.go
  pkg/monitor/suggestsysdrivers/scaledown.go
  pkg/monitor/suggestsysdrivers/secgroupruleinserver.go
  pkg/monitor/suggestsysdrivers/snapshot_unused.go
  pkg/monitor/tasks/resolve_bucket_acl_task.go
Labels: area/monitor, size/XXL

#7140 fix: 修复阿里云同步安全组规则异常问题
  go.mod
  go.sum
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/securitygroup.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/secrules/secrules.go
Labels: area/region, size/L

#7141 Automated cherry pick of #7140: fix: 修复阿里云同步安全组规则异常问题
  go.mod
  go.sum
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/securitygroup.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/secrules/secrules.go
Labels: size/L

#7142 Automated cherry pick of #7140: fix: 修复阿里云同步安全组规则异常问题
  go.mod
  go.sum
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/securitygroup.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/secrules/secrules.go
Labels: size/L

#7138 fix: 优化减少对etcd组件依赖
  pkg/mcclient/mcclient.go
  pkg/mcclient/token3.go
Labels: area/host, lgtm, size/XS

#7135 user batch register bugfix
  pkg/apigateway/handler/misc.go
Labels: area/apigateway, needs-area, size/S
