Repository yunionio/cloudpods, pull requests merged in 2020-03, with the labels that each got.

#5320 build: docker: chown _output dir to current user:group
  Makefile
  scripts/docker_push.sh
Labels: approved, lgtm, needs-area, size/XS

#5315 fix: 避免旧套餐下架zone信息未知,导致同步rds异常
  pkg/compute/models/dbinstances.go
Labels: approved, area/region, lgtm, size/XS

#5318 Automated cherry pick of #5315: fix: 避免旧套餐下架zone信息未知,导致同步rds异常
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/XS

#5319 Automated cherry pick of #5315: fix: 避免旧套餐下架zone信息未知,导致同步rds异常
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/XS

#5317 Automated cherry pick of #5315: fix: 避免旧套餐下架zone信息未知,导致同步rds异常
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/XS

#5316 Automated cherry pick of #5315: fix: 避免旧套餐下架zone信息未知,导致同步rds异常
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/XS

#5324 fix: clean up pending usage no matter whether object upload is success
  pkg/compute/models/buckets.go
Labels: area/region, size/XS

#5325 Automated cherry pick of #5324: fix: clean up pending usage no matter whether object upload is success
  pkg/compute/models/buckets.go
Labels: size/XS

#5326 Automated cherry pick of #5324: fix: clean up pending usage no matter whether object upload is success
  pkg/compute/models/buckets.go
Labels: size/XS

#5327 Automated cherry pick of #5324: fix: clean up pending usage no matter whether object upload is success
  pkg/compute/models/buckets.go
Labels: size/XS

#5329 Automated cherry pick of #5328: fix: docker_push uncomment build bin
  scripts/docker_push.sh
Labels: size/XS

#5336 fix: keystone user password history check should skip system account
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: area/keystone, size/S

#5337 Automated cherry pick of #5336: fix: keystone user password history check should skip system account
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: size/S

#5338 Automated cherry pick of #5336: fix: keystone user password history check should skip system account
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: size/S

#5339 Automated cherry pick of #5336: fix: keystone user password history check should skip system account
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: size/S

#5331 build: docker-centos-build: run as root
  .circleci/Dockerfile
  .circleci/config.yml
  Makefile
Labels: lgtm, needs-area, size/M

#5332 Automated cherry pick of #5331: build: docker-centos-build: run as root
  .circleci/Dockerfile
  .circleci/config.yml
  Makefile
Labels: size/M

#5340 alert notification use joint model
  cmd/climc/shell/monitor/alert.go
  cmd/climc/shell/monitor/notification.go
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/meteralert.go
  pkg/apis/monitor/nodealert.go
  pkg/apis/monitor/notification.go
  pkg/apis/monitor/template.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/options/monitor/alert.go
  pkg/mcclient/options/monitor/ds.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/interfaces.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/dingding.go
  pkg/monitor/alerting/notifiers/feishu.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/alerting/rule.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertjoint.go
  pkg/monitor/models/alertnotification.go
  pkg/monitor/models/meteralert.go
  pkg/monitor/models/nodealert.go
  pkg/monitor/models/notification.go
  pkg/monitor/notifydrivers/drivers.go
  pkg/monitor/service/handlers.go
Labels: approved, area/monitor, lgtm, size/XXL

#5341 Automated cherry pick of #5340: alert notification use joint model
  cmd/climc/shell/monitor/alert.go
  cmd/climc/shell/monitor/notification.go
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/meteralert.go
  pkg/apis/monitor/nodealert.go
  pkg/apis/monitor/notification.go
  pkg/apis/monitor/template.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/options/monitor/alert.go
  pkg/mcclient/options/monitor/ds.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/interfaces.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/dingding.go
  pkg/monitor/alerting/notifiers/feishu.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/alerting/rule.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertjoint.go
  pkg/monitor/models/alertnotification.go
  pkg/monitor/models/meteralert.go
  pkg/monitor/models/nodealert.go
  pkg/monitor/models/notification.go
  pkg/monitor/notifydrivers/drivers.go
  pkg/monitor/service/handlers.go
Labels: approved, lgtm, size/XXL

#5333 hostman: default ovn options from environment
  pkg/hostman/options/options.go
Labels: approved, area/host, lgtm, size/XS

#5343 fix: 支持aws rds sync
  pkg/multicloud/aws/aws.go
Labels: approved, area/region, lgtm

#5344 Automated cherry pick of #5343: fix: 支持aws rds sync
  pkg/multicloud/aws/aws.go
Labels: approved, lgtm

#5345 Automated cherry pick of #5343: fix: 支持aws rds sync
  pkg/multicloud/aws/aws.go
Labels: approved, lgtm

#5334 Automated cherry pick of #5333: hostman: default ovn options from environment
  pkg/hostman/options/options.go
Labels: approved, lgtm, size/XS

#5349 monitor: fix alert update not work
  pkg/apis/monitor/alert.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/nodealert.go
Labels: approved, area/monitor, lgtm, size/M

#5350 Automated cherry pick of #5349: monitor: fix alert update not work
  pkg/apis/monitor/alert.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/nodealert.go
Labels: approved, lgtm, size/M

#5342 fix: update auto-gent struct field json name
  pkg/apis/cloudprovider/zz_generated.model.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/zz_generated.model.go
Labels: area/util, size/M

#5346 fix: update autogen struct json field name for release/3.1
  pkg/apis/cloudprovider/zz_generated.model.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/zz_generated.model.go
Labels: area/util, size/XXL

#5348 fix: update autogen struct json fieldname for release/3.0
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/image/zz_generated.model.go
  pkg/apis/zz_generated.model.go
Labels: size/XL

#5351 fix: turn on default column filter ONLY if query variable starts with @
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/util, lgtm, size/S

#5330 feat: Add useridByMobile and accessToken cache for feishu
  pkg/monitor/notifydrivers/feishu/cache.go
  pkg/monitor/notifydrivers/feishu/cache_test.go
  pkg/monitor/notifydrivers/feishu/client.go
  pkg/monitor/notifydrivers/feishu/types.go
Labels: area/notify, size/L

#5352 Automated cherry pick of #5330: feat: Add useridByMobile and accessToken cache for feishu
  pkg/monitor/notifydrivers/feishu/cache.go
  pkg/monitor/notifydrivers/feishu/cache_test.go
  pkg/monitor/notifydrivers/feishu/client.go
  pkg/monitor/notifydrivers/feishu/types.go
Labels: size/L

#5353 feature(notify): Add query and return value for contact UPDATE interface
  cmd/climc/shell/contacts.go
  cmd/climc/shell/notification.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_contacts.go
  pkg/notify/dispatcher.go
  pkg/notify/handlers.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/worker.go
  pkg/notify/rpc/send.go
Labels: approved, area/notify, lgtm, size/L

#5355 Automated cherry pick of #5353: feature(notify): Add query and return value for contact UPDATE interface
  cmd/climc/shell/contacts.go
  cmd/climc/shell/notification.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_contacts.go
  pkg/notify/dispatcher.go
  pkg/notify/handlers.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/worker.go
  pkg/notify/rpc/send.go
Labels: approved, lgtm, size/L

#5357 Automated cherry pick of #5353: feature(notify): Add query and return value for contact UPDATE interface
  cmd/climc/shell/contacts.go
  cmd/climc/shell/notification.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_contacts.go
  pkg/notify/dispatcher.go
  pkg/notify/handlers.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/worker.go
  pkg/notify/rpc/send.go
Labels: approved, lgtm, size/L

#5356 Automated cherry pick of #5353: feature(notify): Add query and return value for contact UPDATE interface
  cmd/climc/shell/contacts.go
  cmd/climc/shell/notification.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_contacts.go
  pkg/notify/dispatcher.go
  pkg/notify/handlers.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/worker.go
  pkg/notify/rpc/send.go
Labels: approved, lgtm, size/L

#5354 Automated cherry pick of #5353: feature(notify): Add query and return value for contact UPDATE interface
  cmd/climc/shell/contacts.go
  cmd/climc/shell/notification.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_contacts.go
  pkg/notify/dispatcher.go
  pkg/notify/handlers.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/worker.go
  pkg/notify/rpc/send.go
Labels: approved, lgtm, size/L

#5359 bugfix: enable network list filter by host show vpc networks
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#5360 Automated cherry pick of #5359: enable network list filter by host show vpc networks
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#5364 Automated cherry pick of #5363: fix disk billing type on guest is postpaid
  pkg/compute/guestdrivers/managedvirtual.go
Labels: approved, lgtm, size/XS

#5363 bugfix: fix disk billing type on guest is postpaid
  pkg/compute/guestdrivers/managedvirtual.go
Labels: approved, area/region, lgtm, size/XS

#5366 fix/notify: Fix the resend mechanism
  pkg/notify/models/mod_notification.go
Labels: area/notify, size/XS

#5367 Automated cherry pick of #5366: fix/notify: Fix the resend mechanism
  pkg/notify/models/mod_notification.go
Labels: size/XS

#5368 Automated cherry pick of #5366: fix/notify: Fix the resend mechanism
  pkg/notify/models/mod_notification.go
Labels: size/XS

#5369 Automated cherry pick of #5366: fix/notify: Fix the resend mechanism
  pkg/notify/models/mod_notification.go
Labels: size/XS

#5370 Automated cherry pick of #5366: fix/notify: Fix the resend mechanism
  pkg/notify/models/mod_notification.go
Labels: size/XS

#5361 fix: allow project do user-list, group-list, returns current project user and group
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/policy/defaults.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/users.go
Labels: area/keystone, size/M

#5362 Automated cherry pick of #5361: fix: allow project do user-list, group-list, returns current project user and group
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/policy/defaults.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/users.go
Labels: size/M

#5371 Automated cherry pick of #5226: lbbackend: fix nil ref when getting details
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#5379 Bugfix/tb bugfix 0306
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/zone.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/utils.go
Labels: approved, area/region, lgtm, needs-area, size/S

#5382 Automated cherry pick of #5379: huawei reset password bugfix
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/zone.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/utils.go
Labels: approved, lgtm, size/S

#5381 Automated cherry pick of #5379: huawei reset password bugfix
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/zone.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/utils.go
Labels: approved, lgtm

#5380 Automated cherry pick of #5379: huawei reset password bugfix
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/zone.go
  pkg/multicloud/huawei/elasticcache_account.go
  pkg/multicloud/huawei/utils.go
Labels: approved, lgtm, size/S

#5372 fix: no scope shcedtag should be visible to all
  pkg/cloudcommon/db/scoperesource.go
Labels: area/region, size/S

#5373 Automated cherry pick of #5372: fix: no scope shcedtag should be visible to all
  pkg/cloudcommon/db/scoperesource.go
Labels: size/S

#5374 Automated cherry pick of #5372: fix: no scope shcedtag should be visible to all
  pkg/cloudcommon/db/scoperesource.go
Labels: size/S

#5376 Automated cherry pick of #5372: fix: no scope shcedtag should be visible to all
  pkg/cloudcommon/db/scoperesource.go
Labels: size/S

#5377 Automated cherry pick of #5372: fix: no scope shcedtag should be visible to all
  pkg/cloudcommon/db/scoperesource.go
Labels: size/S

#5378 fix: Add 'scope=system' and 'system' for Caches when querying from Keystone.
  cmd/climc/shell/groups.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_groups.go
  pkg/notify/cache/user_group_cache.go
Labels: approved, area/util, lgtm, size/M

#5386 Automated cherry pick of #5378: fix: Add 'scope=system' and 'system' for Caches when querying from Keystone.
  cmd/climc/shell/groups.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_groups.go
  pkg/notify/cache/user_group_cache.go
Labels: approved, lgtm, size/M

#5384 Automated cherry pick of #5378: fix: Add 'scope=system' and 'system' for Caches when querying from Keystone.
  cmd/climc/shell/groups.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_groups.go
  pkg/notify/cache/user_group_cache.go
Labels: approved, lgtm, size/M

#5385 Automated cherry pick of #5378: fix: Add 'scope=system' and 'system' for Caches when querying from Keystone.
  cmd/climc/shell/groups.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_groups.go
  pkg/notify/cache/user_group_cache.go
Labels: approved, lgtm, size/M

#5383 Automated cherry pick of #5378: fix: Add 'scope=system' and 'system' for Caches when querying from Keystone.
  cmd/climc/shell/groups.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/usercache.go
  pkg/mcclient/modules/mod_groups.go
  pkg/notify/cache/user_group_cache.go
Labels: approved, lgtm, size/M

#5358 fix: corrent update status logclient event type
  pkg/cloudcommon/db/statusbase.go
  pkg/util/logclient/consts.go
Labels: area/util, lgtm, size/XS

#5335 fix: 1. image header details should skip "properties" field 2.cloudprovider details nil pointer panic
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudproviders.go
  pkg/image/models/images.go
Labels: area/image, area/region, lgtm, size/M

#5388 fix: keystone prefers internal endpoint type
  pkg/mcclient/modules/managers.go
Labels: area/climc, size/XS

#5390 Automated cherry pick of #5388: fix: keystone prefers internal endpoint type
  pkg/mcclient/modules/managers.go
Labels: size/XS

#5389 Automated cherry pick of #5388: fix: keystone prefers internal endpoint type
  pkg/mcclient/modules/managers.go
Labels: size/XS

#5392 fix: scoped resource should override FetchOwnerId
  pkg/cloudcommon/db/scoperesource.go
Labels: area/region, size/XS

#5397 Automated cherry pick of #5392: fix: scoped resource should override FetchOwnerId
  pkg/cloudcommon/db/scoperesource.go
Labels: size/XS

#5396 Automated cherry pick of #5392: fix: scoped resource should override FetchOwnerId
  pkg/cloudcommon/db/scoperesource.go
Labels: size/XS

#5394 Automated cherry pick of #5392: fix: scoped resource should override FetchOwnerId
  pkg/cloudcommon/db/scoperesource.go
Labels: size/XS

#5393 Automated cherry pick of #5392: fix: scoped resource should override FetchOwnerId
  pkg/cloudcommon/db/scoperesource.go
Labels: size/XS

#5365 fix: implements details and list for monitor service
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/vpc.go
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/meteralert.go
  pkg/apis/monitor/nodealert.go
  pkg/compute/models/dbinstances.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/meteralert.go
  pkg/monitor/models/nodealert.go
Labels: area/monitor, lgtm, size/L

#5410 Automated cherry pick of #5408: feature: climc docker image add vim
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
Labels: size/XS

#5411 fix: complete keystone/glance list filter
  pkg/apis/identity/input.go
  pkg/apis/image/image.go
  pkg/apis/list.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/endpoints.go
  pkg/keystone/models/groupresource.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projectresource.go
  pkg/keystone/models/regionresource.go
  pkg/keystone/models/roleresource.go
  pkg/keystone/models/serviceresource.go
  pkg/keystone/models/services.go
  pkg/keystone/models/userresource.go
  pkg/keystone/models/users.go
Labels: size/XL

#5398 fix: not check domain quota if non_default_domain_project is off
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
Labels: area/util, size/S

#5412 fix: two default option changes: 1. do not convert vhd by default 2.sync purge server by default
  pkg/compute/options/options.go
  pkg/image/options/options.go
Labels: area/image, area/region, size/XS

#5403 fix: cloudprovider performEnable should also enable its cloudaccount
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: area/region, lgtm, size/S

#5404 Automated cherry pick of #5403: fix: cloudprovider performEnable should also enable its cloudaccount
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#5405 Automated cherry pick of #5403: fix: cloudprovider performEnable should also enable its cloudaccount
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#5406 Automated cherry pick of #5403: fix: cloudprovider performEnable should also enable its cloudaccount
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#5407 Automated cherry pick of #5403: fix: cloudprovider performEnable should also enable its cloudaccount
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#5399 Automated cherry pick of #5398: fix: not check domain quota if non_default_domain_project is off
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
Labels: size/S

#5400 Automated cherry pick of #5398: fix: not check domain quota if non_default_domain_project is off
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
Labels: size/S

#5401 Automated cherry pick of #5398: fix: not check domain quota if non_default_domain_project is off
  pkg/cloudcommon/db/quotas/interface.go
  pkg/cloudcommon/db/quotas/quotas.go
Labels: size/S

#5414 opslog: notes use text column
  pkg/cloudcommon/db/opslog.go
  pkg/mcclient/options/k8s/cluster.go
Labels: area/logger, size/M

#5416 Automated cherry pick of #5414: opslog: notes use text column
  pkg/cloudcommon/db/opslog.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S

#5417 Automated cherry pick of #5414: opslog: notes use text column
  pkg/cloudcommon/db/opslog.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/M

#5415 Automated cherry pick of #5414: opslog: notes use text column
  pkg/cloudcommon/db/opslog.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/M

#5418 Automated cherry pick of #5414: opslog: notes use text column
  pkg/cloudcommon/db/opslog.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/M

#5413 fix: rds sku 返回region name
  pkg/apis/compute/dbinstance_sku.go
  pkg/compute/models/dbinstance_skus.go
Labels: approved, lgtm, size/M

#5428 Automated cherry pick of #5424: fix(esxi): Add two account with same account name
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/M

#5424 fix(esxi): Add two account with same account name
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: approved, area/region, lgtm, size/M

#5427 Automated cherry pick of #5424: fix(esxi): Add two account with same account name
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/M

#5425 Automated cherry pick of #5424: fix(esxi): Add two account with same account name
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/M

#5426 Automated cherry pick of #5424: fix(esxi): Add two account with same account name
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/M

#5429 fix: typo for sku sync
  pkg/compute/tasks/cloud_account_sync_skus_task.go
Labels: approved, area/region, lgtm, size/XS

#5432 Automated cherry pick of #5429: fix: typo for sku sync
  pkg/compute/tasks/cloud_account_sync_skus_task.go
Labels: approved, lgtm, size/XS

#5431 Automated cherry pick of #5429: fix: typo for sku sync
  pkg/compute/tasks/cloud_account_sync_skus_task.go
Labels: approved, lgtm, size/XS

#5430 Automated cherry pick of #5429: fix: typo for sku sync
  pkg/compute/tasks/cloud_account_sync_skus_task.go
Labels: approved, lgtm, size/XS

#5419 fix: fail to find esxi admin vnic, use vnic with default IPv4 route
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/host.go
Labels: area/region, lgtm, size/M

#5420 Automated cherry pick of #5419: fix: fail to find esxi admin vnic, use vnic with default IPv4 route
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/host.go
Labels: size/M

#5423 Automated cherry pick of #5419: fix: fail to find esxi admin vnic, use vnic with default IPv4 route
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/host.go
Labels: size/M

#5433 fix: fix region list fitlers, round 1
  pkg/apis/compute/bucket.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/disk.go
  pkg/apis/compute/elasticcache_const.go
  pkg/apis/compute/elasticips_const.go
  pkg/apis/compute/geo_input.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/input.go
  pkg/apis/compute/instance_group.go
  pkg/apis/compute/sku_const.go
  pkg/apis/list.go
  pkg/cloudcommon/db/jointbase.go
  pkg/cloudcommon/db/virtualjointbase.go
  pkg/compute/models/baremetalagents.go
  pkg/compute/models/buckets.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstance_databases.go
  pkg/compute/models/dbinstance_parameters.go
  pkg/compute/models/dbinstance_privileges.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/dynamicschedtags.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticcache_parameters.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/groups.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guestjoints.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guestresource.go
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XXL

#5421 Automated cherry pick of #5419: fix: fail to find esxi admin vnic, use vnic with default IPv4 route
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/host.go
Labels: size/M

#5422 Automated cherry pick of #5419: fix: fail to find esxi admin vnic, use vnic with default IPv4 route
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/host.go
Labels: size/M

#5434 fix: resource details contains zero numbers
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm

#5436 fix: sql query errors for missing manager_id and cloudregion_id
  pkg/compute/models/cloudregions.go
  pkg/compute/models/loadbalancers.go
  pkg/lbagent/models/reflect.go
Labels: approved, area/region, lgtm, size/M

#5437 climc: add server and host ssh terminal util
  cmd/climc/shell/hosts.go
  cmd/climc/shell/servers.go
  pkg/mcclient/options/servers.go
  pkg/util/ssh/ssh.go
Labels: approved, area/climc, lgtm, size/L

#5438 Automated cherry pick of #5437: climc: add server and host ssh terminal util
  cmd/climc/shell/hosts.go
  cmd/climc/shell/servers.go
  pkg/mcclient/options/servers.go
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/L

#5435 build: github: build region, host, host-deployer images first
  .github/workflows/docker.yml
Labels: area/util, size/M

#5443 fix region list filters round 2
  pkg/apis/compute/host.go
  pkg/apis/compute/hostjoin.go
  pkg/apis/compute/hostnetwork.go
  pkg/apis/compute/hostschedtag.go
  pkg/apis/compute/hoststorage.go
  pkg/apis/compute/hostwire.go
  pkg/apis/compute/instance_snapshot.go
  pkg/apis/compute/isolated_device.go
  pkg/apis/compute/isolated_device_const.go
  pkg/apis/compute/schedtag.go
  pkg/apis/compute/snapshot.go
  pkg/apis/compute/storage_const.go
  pkg/apis/compute/storagecache.go
  pkg/apis/list.go
  pkg/cloudcommon/db/external.go
  pkg/compute/models/hostjoints.go
  pkg/compute/models/hostnetworks.go
  pkg/compute/models/hostresource.go
  pkg/compute/models/hosts.go
  pkg/compute/models/hostschedtags.go
  pkg/compute/models/hoststorages.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/schedtagjoint.go
  pkg/compute/models/storagecaches.go
Labels: area/region, size/XL

#5442 baremetal: zone_id not been updated
  pkg/compute/models/zoneresource.go
Labels: area/baremetal, size/XS

#5449 Automated cherry pick of #5447: region: host update storage set enabled
  pkg/compute/models/hosts.go
Labels: size/XS

#5450 Automated cherry pick of #5447: region: host update storage set enabled
  pkg/compute/models/hosts.go
Labels: size/XS

#5451 Automated cherry pick of #5447: region: host update storage set enabled
  pkg/compute/models/hosts.go
Labels: size/XS

#5447 region: host update storage set enabled
  pkg/compute/models/hosts.go
Labels: needs-area, size/XS

#5453 fix: Resolve format issues caused by pr#5443
  pkg/apis/compute/hostschedtag.go
  pkg/compute/models/hostjoints.go
  pkg/compute/models/hostnetworks.go
  pkg/compute/models/hostschedtags.go
  pkg/compute/models/hoststorages.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/schedtagjoint.go
Labels: approved, lgtm, needs-area, size/M

#5455 bugfix :fix structure host storage output: storagecache_id
  pkg/apis/compute/hoststorage.go
Labels: approved, area/region, lgtm, size/XS

#5456 Automated cherry pick of #5455: fix structure host storage output: storagecache_id
  pkg/apis/compute/hoststorage.go
Labels: approved, lgtm, size/XS

#5439 fix(esxi): Fix bugs when using network with vlanID
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
Labels: approved, area/region, lgtm, size/L

#5441 Automated cherry pick of #5439: fix(esxi): Fix bugs when using network with vlanID
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
Labels: approved, lgtm, size/L

#5440 Automated cherry pick of #5439: fix(esxi): Fix bugs when using network with vlanID
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
Labels: approved, lgtm, size/L

#5444 fix(esxi): UnitNumber 7 is unavailable for scsi controller
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/esxiagent, lgtm, size/S

#5446 Automated cherry pick of #5444: fix(esxi): UnitNumber 7 is unavailable for scsi controller
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/S

#5445 Automated cherry pick of #5444: fix(esxi): UnitNumber 7 is unavailable for scsi controller
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/XS

#5464 feat: Update Vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: needs-area, size/M

#5466 feat: Update Vendor for release/3.1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/go.mod
  vendor/yunion.io/x/jsonutils/go.sum
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/M

#5467 feat: Update Vendor for release/2.13
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/go.mod
  vendor/yunion.io/x/jsonutils/go.sum
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/pkg/util/reflectutils/reflectutils.go
  vendor/yunion.io/x/pkg/util/signalutils/dumpstack_others.go
  vendor/yunion.io/x/pkg/util/signalutils/dumpstack_windows.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#5468 feat: Update Vendor for release/2.12
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
  vendor/yunion.io/x/jsonutils/go.mod
  vendor/yunion.io/x/jsonutils/go.sum
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/pkg/util/netutils/errors.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/pkg/util/reflectutils/reflectutils.go
  vendor/yunion.io/x/pkg/util/signalutils/dumpstack_others.go
  vendor/yunion.io/x/pkg/util/signalutils/dumpstack_windows.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/const.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XL

#5459 add bucket connection test
  cmd/climc/shell/bucket_options.go
  pkg/mcclient/modules/mod_bucket_options.go
Labels: needs-area, size/M

#5460 Automated cherry pick of #5459: add bucket connection test
  cmd/climc/shell/bucket_options.go
  pkg/mcclient/modules/mod_bucket_options.go
Labels: size/M

#5461 Automated cherry pick of #5459: add bucket connection test
  cmd/climc/shell/bucket_options.go
  pkg/mcclient/modules/mod_bucket_options.go
Labels: size/M

#5462 Automated cherry pick of #5459: add bucket connection test
  cmd/climc/shell/bucket_options.go
  pkg/mcclient/modules/mod_bucket_options.go
Labels: size/M

#5470 region misc fix
  pkg/apis/compute/instance_snapshot.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
Labels: approved, area/region, lgtm, size/M

#5471 Automated cherry pick of #5470: region misc fix
  pkg/apis/compute/instance_snapshot.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
Labels: approved, lgtm, size/M

#5457 hotfix: 支持更新云账号密码时测试账号连通性
  cmd/climc/shell/cloudaccounts.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/models/cloudaccounts.go
Labels: approved, area/region, lgtm, size/L

#5472 修复meteralartbug
  pkg/monitor/models/meteralert.go
Labels: area/monitor, size/XS

#5480 fix(esxi): VlanID '1' is default value
  pkg/multicloud/esxi/host.go
Labels: area/esxiagent, size/S

#5481 Automated cherry pick of #5480: fix(esxi): VlanID '1' is default value
  pkg/multicloud/esxi/host.go
Labels: size/S

#5482 Automated cherry pick of #5480: fix(esxi): VlanID '1' is default value
  pkg/multicloud/esxi/host.go
Labels: size/S

#5485 Automated cherry pick of #5479: fix(scheduler): Candidater's CloudProvider maybe nil
  pkg/scheduler/data_manager/candidate_manager.go
Labels: size/XS

#5479 fix(scheduler): Candidater's CloudProvider maybe nil
  pkg/scheduler/data_manager/candidate_manager.go
Labels: area/scheduler, size/XS

#5484 bugfix：download handler set no timeout
  pkg/compute/models/guests.go
  pkg/hostman/downloader/downloadhandler.go
Labels: approved, area/host, area/region, lgtm, size/XS

#5489 Automated cherry pick of #5484: download handler set no timeout
  pkg/compute/models/guests.go
  pkg/hostman/downloader/downloadhandler.go
Labels: approved, lgtm, size/XS

#5488 Automated cherry pick of #5484: download handler set no timeout
  pkg/compute/models/guests.go
  pkg/hostman/downloader/downloadhandler.go
Labels: approved, lgtm, size/XS

#5486 Automated cherry pick of #5484: download handler set no timeout
  pkg/compute/models/guests.go
  pkg/hostman/downloader/downloadhandler.go
Labels: approved, lgtm, size/XS

#5487 Automated cherry pick of #5484: download handler set no timeout
  pkg/compute/models/guests.go
  pkg/hostman/downloader/downloadhandler.go
Labels: approved, lgtm, size/XS

#5454 fix(glance): Structured subimage info and add 'created_at' field
  pkg/apis/image/guestimage.go
  pkg/image/models/image_guest.go
Labels: approved, area/image, lgtm, size/M
