Repository yunionio/cloudpods, pull requests merged in 2020-10, with the labels that each got.

#8181 hotfix: 1. allow merge networks without continuous addresses 2. filter guest_ip_start and guest_ip_end with contains operator
  pkg/compute/models/networks.go
  pkg/mcclient/options/network.go
Labels: approved, area/region, lgtm, size/S

#8182 Automated cherry pick of #8181: hotfix: 1. allow merge networks without continuous addresses 2. filter guest_ip_start and guest_ip_end with contains operator
  pkg/compute/models/networks.go
  pkg/mcclient/options/network.go
Labels: approved, lgtm, size/S

#8178 fix: error code of external bucket not found error should be 404
  pkg/compute/models/buckets.go
Labels: approved, area/region, lgtm, size/M

#8180 Automated cherry pick of #8178: fix: error code of external bucket not found error should be 404
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/M

#8179 Automated cherry pick of #8178: fix: error code of external bucket not found error should be 404
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/M

#8176 modify suggest rule cli
  cmd/climc/shell/monitor/suggestsysrule.go
  pkg/mcclient/modules/mod_suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysrule.go
  pkg/monitor/models/suggestsysrule.go
Labels: approved, area/monitor, lgtm, size/L

#8177 Automated cherry pick of #8176: modify suggest rule cli
  cmd/climc/shell/monitor/suggestsysrule.go
  pkg/mcclient/modules/mod_suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysrule.go
  pkg/monitor/models/suggestsysrule.go
Labels: approved, lgtm, size/L

#8152 multi-arch 的镜像使用支持 arm64
  Makefile
  build/docker/multi-arch/Dockerfile.esxi-agent
  build/docker/multi-arch/Dockerfile.host
  build/docker/multi-arch/Dockerfile.torrent
  scripts/docker_push.sh
Labels: approved, lgtm, size/M

#8202 fix: server name auto index should start from 1
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, area/util, lgtm, size/XS

#8203 Automated cherry pick of #8202: fix: server name auto index should start from 1
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#8206 Automated cherry pick of #8205: fix: filter cached images with host schedtag
  cmd/climc/shell/compute/cachedimages.go
  pkg/apis/compute/input.go
  pkg/compute/models/cachedimages.go
Labels: approved, lgtm, size/S

#8205 fix: filter cached images with host schedtag
  cmd/climc/shell/compute/cachedimages.go
  pkg/apis/compute/input.go
  pkg/compute/models/cachedimages.go
Labels: approved, area/region, lgtm, size/S

#8204 Automated cherry pick of #8202: fix: server name auto index should start from 1
  pkg/cloudcommon/db/db_dispatcher.go
Labels: approved, lgtm, size/XS

#8183 vpcagent: ovn: increase dhcp lease, renew, rebind time
  pkg/vpcagent/ovn/keeper.go
Labels: approved, area/vpcagent, lgtm, size/XS

#8186 Automated cherry pick of #8183: vpcagent: ovn: increase dhcp lease, renew, rebind time
  pkg/vpcagent/ovn/keeper.go
Labels: approved, lgtm, size/XS

#8184 Automated cherry pick of #8183: vpcagent: ovn: increase dhcp lease, renew, rebind time
  pkg/vpcagent/ovn/keeper.go
Labels: approved, lgtm, size/XS

#8185 Automated cherry pick of #8183: vpcagent: ovn: increase dhcp lease, renew, rebind time
  pkg/vpcagent/ovn/keeper.go
Labels: approved, lgtm, size/XS

#8187 Automated cherry pick of #8183: vpcagent: ovn: increase dhcp lease, renew, rebind time
  pkg/vpcagent/ovn/keeper.go
Labels: approved, lgtm, size/XS

#8207 fix: qcloud set hostname for instance
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, area/region, lgtm, size/M

#8208 Automated cherry pick of #8207: fix: qcloud set hostname for instance
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/M

#8209 Automated cherry pick of #8207: fix: qcloud set hostname for instance
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/M

#8189 region: guest detail add field macs
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_queries.go
Labels: approved, area/region, lgtm, size/M

#8192 Automated cherry pick of #7621: separate guest doamin and dns
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/XS

#8200 Automated cherry pick of #8199: fix(esxi): check whether some fields of vm are nil
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/ip.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/S

#8201 Automated cherry pick of #8199: fix(esxi): check whether some fields of vm are nil
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/ip.go
  pkg/multicloud/esxi/manager.go
Labels: approved, lgtm, size/S

#8199 Fix for cloudaccount PrepareNets
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/ip.go
  pkg/multicloud/esxi/manager.go
Labels: approved, area/region, lgtm, size/S

#8211 Automated cherry pick of #8210: fix: validate secgroup purge condition
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#8219 Automated cherry pick of #8218: webconsole: ssh: each argument on its own line
  pkg/webconsole/command/ssh_command.go
Labels: approved, lgtm, size/XS

#8221 Automated cherry pick of #8218: webconsole: ssh: each argument on its own line
  pkg/webconsole/command/ssh_command.go
Labels: approved, lgtm, size/XS

#8222 Automated cherry pick of #8218: webconsole: ssh: each argument on its own line
  pkg/webconsole/command/ssh_command.go
Labels: approved, lgtm, size/XS

#8218 Bugfix/yousong webconsole ssh compat
  pkg/webconsole/command/ssh_command.go
Labels: approved, area/webconsole, lgtm, size/XS

#8220 Automated cherry pick of #8218: webconsole: ssh: each argument on its own line
  pkg/webconsole/command/ssh_command.go
Labels: approved, lgtm, size/XS

#8223 Automated cherry pick of #8222: webconsole: ssh: each argument on its own line
  pkg/webconsole/command/ssh_command.go
Labels: approved, lgtm, size/XS

#8224 Automated cherry pick of #8222: webconsole: ssh: each argument on its own line
  pkg/webconsole/command/ssh_command.go
Labels: approved, lgtm, size/XS

#8225 esxi-agent 编译方式兼容 arm64
  build/docker/multi-arch/Dockerfile.esxi-agent
  scripts/docker_push.sh
Labels: approved, lgtm, size/S

#8226 Automated cherry pick of #8213: bugfix:scoperesource FilterByOwner
  build/monitor/root/opt/yunion/share/notify_templates/alerter/content@cn/DEFAULT
  build/monitor/root/opt/yunion/share/notify_templates/alerter/content@en/DEFAULT
  pkg/cloudcommon/db/scoperesource.go
  pkg/compute/models/schedtags.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/monitorscoperesource.go
  pkg/monitor/models/suggestsysruleconfig.go
Labels: approved, lgtm

#8213 Bugfix/zxc commonalert
  build/monitor/root/opt/yunion/share/notify_templates/alerter/content@cn/DEFAULT
  build/monitor/root/opt/yunion/share/notify_templates/alerter/content@en/DEFAULT
  pkg/cloudcommon/db/scoperesource.go
  pkg/compute/models/schedtags.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/monitorscoperesource.go
  pkg/monitor/models/suggestsysruleconfig.go
Labels: approved, area/monitor, lgtm, size/L

#8214 remove aws lbbg cache metedata
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancerqcloudcachedlbbg.go
Labels: approved, area/region, lgtm, size/M

#8216 Automated cherry pick of #8214: remove aws lbbg cache metedata
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancerqcloudcachedlbbg.go
Labels: approved, lgtm, size/M

#8217 Automated cherry pick of #8214: remove aws lbbg cache metedata
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancerqcloudcachedlbbg.go
Labels: approved, lgtm, size/M

#8215 Automated cherry pick of #8214: remove aws lbbg cache metedata
  pkg/compute/models/initdb.go
  pkg/compute/models/loadbalancerawscachedlbb.go
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalancerhuaweicachedlbbg.go
  pkg/compute/models/loadbalancerqcloudcachedlbb.go
  pkg/compute/models/loadbalancerqcloudcachedlbbg.go
Labels: approved, lgtm

#8194 fix(esxi): check nil value when NewVirtualMachine
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/esxiagent, lgtm, size/M

#8198 Automated cherry pick of #8194: fix(esxi): check nil value when NewVirtualMachine
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/M

#8197 Automated cherry pick of #8194: fix(esxi): check nil value when NewVirtualMachine
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/M

#8196 Automated cherry pick of #8194: fix(esxi): check nil value when NewVirtualMachine
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/M

#8195 Automated cherry pick of #8194: fix(esxi): check nil value when NewVirtualMachine
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/M

#8240 Automated cherry pick of #8238: fix: ldap sync not update user's phone and email
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/tokens/handlers.go
Labels: approved, lgtm, size/S

#8238 fix: ldap sync not update user's phone and email
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/tokens/handlers.go
Labels: approved, area/keystone, lgtm, size/S

#8239 Automated cherry pick of #8238: fix: ldap sync not update user's phone and email
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/tokens/handlers.go
Labels: approved, lgtm, size/S

#8126 Feats for ESXi Manage
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
  pkg/esxi/options/options.go
  pkg/esxi/service/esxi_agent_service.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/ip.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/shell/ip.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/esxiagent, area/region, lgtm, size/XL

#8233 Automated cherry pick of #8126: Feats for ESXi Manage
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
  pkg/esxi/options/options.go
  pkg/esxi/service/esxi_agent_service.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/ip.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/shell/ip.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/XL

#8235 fix: not clean pending domain usage
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/dns_zones.go
Labels: approved, area/region, lgtm, size/M

#8236 Automated cherry pick of #8235: fix: not clean pending domain usage
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/dns_zones.go
Labels: approved, lgtm, size/M

#8251 Automated cherry pick of #8237: fix: format errors that block make test
  cmd/fetcherfs/main.go
  pkg/compute/tasks/baremetal_delete_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_local.go
  pkg/keystone/driver/ldap/sync.go
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysrule.go
Labels: approved, lgtm, size/M

#8237 fix: format errors that block make test
  cmd/fetcherfs/main.go
  pkg/compute/tasks/baremetal_delete_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_local.go
  pkg/keystone/driver/ldap/sync.go
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/suggestsysrule.go
Labels: approved, area/monitor, area/region, lgtm, size/M

#8252 fix: vpc peering http error params
  pkg/compute/models/vpc_peering_connections.go
Labels: approved, area/region, lgtm, size/XS

#8256 解决编译之后 output 的 owerner 问题
  Makefile
Labels: approved, lgtm, size/XS

#8257 Automated cherry pick of #8256: 解决编译之后 output 的 owerner 问题
  Makefile
Labels: approved, lgtm, size/XS

#8248 fix: qcloud instance with max bandwidth
  pkg/multicloud/qcloud/instance.go
Labels: area/region, size/XS

#8250 Automated cherry pick of #8248: fix: qcloud instance with max bandwidth
  pkg/multicloud/qcloud/instance.go
Labels: size/XS

#8249 Automated cherry pick of #8248: fix: qcloud instance with max bandwidth
  pkg/multicloud/qcloud/instance.go
Labels: size/XS

#8246 fix: project_id in resource details not correct
  pkg/apis/output.go
Labels: area/util, size/XS

#8247 Automated cherry pick of #8246: fix: project_id in resource details not correct
  pkg/apis/output.go
Labels: size/XS

#8234 feature: allow session level yunion_auth cookie
  pkg/apigateway/handler/auth.go
  pkg/apigateway/options/options.go
Labels: area/apigateway, size/S

#8212 Automated cherry pick of #8210: fix: validate secgroup purge condition
  pkg/compute/models/secgroups.go
Labels: size/S

#8210 fix: validate secgroup purge condition
  pkg/compute/models/secgroups.go
Labels: area/region, size/S

#8232 Fix for ESXi Template
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: area/esxiagent, size/L

#8259 Automated cherry pick of #8232: fix(esxi): search template from whole vCenter
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: size/L

#8261 Automated cherry pick of #8232: fix(esxi): search template from whole vCenter
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: size/L

#8262 Automated cherry pick of #8232: fix(esxi): search template from whole vCenter
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: size/L

#8260 Automated cherry pick of #8232: fix(esxi): search template from whole vCenter
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
Labels: size/L

#8242 baremetal: fix pxe filter network by guest_dhcp
  pkg/baremetal/pxe/dhcp.go
Labels: approved, area/baremetal, lgtm, size/XS

#8228 Bugfix/yousong eip opslog
  pkg/compute/models/elasticips.go
Labels: area/region, size/XS

#8229 Automated cherry pick of #8228: eip: construct a pointer type
  pkg/compute/models/elasticips.go
Labels: size/XS

#8230 Automated cherry pick of #8228: eip: construct a pointer type
  pkg/compute/models/elasticips.go
Labels: size/XS

#8245 Automated cherry pick of #8242: baremetal: fix pxe filter network by guest_dhcp
  pkg/baremetal/pxe/dhcp.go
Labels: approved, lgtm, size/XS

#8244 Automated cherry pick of #8242: baremetal: fix pxe filter network by guest_dhcp
  pkg/baremetal/pxe/dhcp.go
Labels: approved, lgtm, size/XS

#8243 Automated cherry pick of #8242: baremetal: fix pxe filter network by guest_dhcp
  pkg/baremetal/pxe/dhcp.go
Labels: approved, lgtm, size/XS

#8188 fix: avoid qcloud secgroup cache name not sync
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/qcloud/vpc.go
Labels: approved, area/region, lgtm, size/M

#8191 Automated cherry pick of #8188: fix: avoid qcloud secgroup cache name not sync
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/qcloud/vpc.go
Labels: approved, lgtm, size/M

#8273 在 docker push 脚本里创建_output 目录，以便容错
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#8274 Automated cherry pick of #8273: 在 docker push 脚本里创建_output 目录，以便容错
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#8276 在 docker push 脚本里创建_output 目录，以便容错
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#8277 Automated cherry pick of #8276: 在 docker push 脚本里创建_output 目录，以便容错
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#8279 Automated cherry pick of #8278: fix host-deployer base image
  build/docker/Dockerfile.host-deployer
Labels: approved, lgtm, size/XS

#8278 update host-deployer base image
  build/docker/Dockerfile.host-deployer
Labels: approved, lgtm

#8267 fix: trans google new region name
  pkg/multicloud/google/latitud_and_longitude.go
Labels: area/region, size/XS

#8270 fix: 支持带宽包用户
  pkg/multicloud/qcloud/instance.go
Labels: area/region, size/S

#8271 Automated cherry pick of #8270: fix: 支持带宽包用户
  pkg/multicloud/qcloud/instance.go
Labels: size/S

#8272 Automated cherry pick of #8270: fix: 支持带宽包用户
  pkg/multicloud/qcloud/instance.go
Labels: size/S

#8268 Automated cherry pick of #8267: fix: trans google new region name
  pkg/multicloud/google/latitud_and_longitude.go
Labels: size/XS

#8269 Automated cherry pick of #8267: fix: trans google new region name
  pkg/multicloud/google/latitud_and_longitude.go
Labels: size/XS

#8231 region: add interface freeze virtual resource
  cmd/climc/shell/misc/current.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/input.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/apis/zz_generated.model.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guest_actions.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: approved, area/region, lgtm, size/L

#8241 Automated cherry pick of #8231: add interface freeze virtual resource
  cmd/climc/shell/misc/current.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/input.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/apis/zz_generated.model.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guest_actions.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: approved, lgtm, size/L

#8253 fix: qcloud eip with bandwidth attr
  pkg/multicloud/qcloud/eip.go
Labels: approved, area/region, lgtm, size/S

#8255 Automated cherry pick of #8253: fix: qcloud eip with bandwidth attr
  pkg/multicloud/qcloud/eip.go
Labels: approved, lgtm, size/S

#8254 Automated cherry pick of #8253: fix: qcloud eip with bandwidth attr
  pkg/multicloud/qcloud/eip.go
Labels: approved, lgtm, size/S

#8275 fix:aliyun jsonRequest 增加i/o timeout retry
  pkg/multicloud/aliyun/aliyun.go
Labels: approved, area/region, lgtm, needs-backport, size/XS

#8264 fix: support public ip create
  pkg/apis/compute/api.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/eip.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/mcclient/options/servers.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, area/region, lgtm, size/L

#8280 Automated cherry pick of #8264: fix: support public ip create
  pkg/apis/compute/api.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/eip.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/mcclient/options/servers.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/qcloud.go
Labels: approved, lgtm, size/L

#8281 fix: sync huawei bucket project info
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/bucket.go
Labels: approved, area/region, lgtm, size/M

#8282 Automated cherry pick of #8281: fix: sync huawei bucket project info
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/bucket.go
Labels: approved, lgtm, size/M

#8283 Automated cherry pick of #8281: fix: sync huawei bucket project info
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/shell/bucket.go
Labels: approved, lgtm, size/M

#8287 fix: replace NewFloat by NewFloat64 and NewFloat32
  cmd/climc/shell/compute/hosts.go
  go.mod
  go.sum
  pkg/appsrv/stats.go
  pkg/compute/models/cloudaccounts.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/mcclient/options/base.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/multicloud/ucloud/client.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/string.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/sqlchemy/const.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, area/region, lgtm, size/L

#8288 Automated cherry pick of #8287: make mode
  cmd/climc/shell/compute/hosts.go
  go.mod
  go.sum
  pkg/appsrv/stats.go
  pkg/compute/models/cloudaccounts.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/mcclient/options/base.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/multicloud/ucloud/client.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/access.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/string.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/sqlchemy/const.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, lgtm, size/L

#8284 feature: qcloud create VM with tags
  pkg/apis/input.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/networks.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/instance.go
Labels: approved, area/region, lgtm, size/L

#8285 Automated cherry pick of #8284: feature: qcloud create VM with tags
  pkg/apis/input.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/networks.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/instance.go
Labels: approved, lgtm, size/L

#8286 Automated cherry pick of #8275: fix:aliyun jsonRequest 增加i/o timeout retry
  pkg/multicloud/aliyun/aliyun.go
Labels: approved, lgtm, size/XS

#8290 fix: 优化安全组规则同步
  pkg/cloudprovider/securitygroup.go
  pkg/compute/regiondrivers/secgroup_qcloud_test.go
Labels: approved, area/region, lgtm, size/L

#8291 Automated cherry pick of #8290: fix: 优化安全组规则同步
  pkg/cloudprovider/securitygroup.go
  pkg/compute/regiondrivers/secgroup_qcloud_test.go
Labels: approved, lgtm, size/L

#8292 Automated cherry pick of #8290: fix: 优化安全组规则同步
  pkg/cloudprovider/securitygroup.go
  pkg/compute/regiondrivers/secgroup_qcloud_test.go
Labels: approved, lgtm, size/L

#8265 sync and use of ESXi template
  pkg/apis/compute/network.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/networks.go
  pkg/hostman/storageman/storage_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/template.go
Labels: approved, lgtm, size/M

#8266 Automated cherry pick of #8265: feat(esxiagent): sync and use of ESXi template
  pkg/apis/compute/network.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/networks.go
  pkg/hostman/storageman/storage_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/template.go
Labels: approved, lgtm, size/M

#8296 Automated cherry pick of #8294: fix: use new api
  pkg/multicloud/huawei/client/modules/mod_disks.go
Labels: approved, lgtm, size/XS

#8289 fix:openstack lb 后端ip无法映射到主机的异常处理
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalanceropenstackcachedlbb.go
Labels: approved, area/region, lgtm, size/XS

#8295 Automated cherry pick of #8294: fix: use new api
  pkg/multicloud/huawei/client/modules/mod_disks.go
Labels: approved, lgtm, size/XS

#8298 Automated cherry pick of #8297: fix: filter role assignments by project domains id or name
  cmd/climc/shell/identity/role_assignments.go
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/modules/mod_roleassignments.go
Labels: approved, lgtm, size/M

#8294 fix: use new api
  pkg/multicloud/huawei/client/modules/mod_disks.go
Labels: approved, area/region, lgtm, size/XS

#8297 fix: filter role assignments by project domains id or name
  cmd/climc/shell/identity/role_assignments.go
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/modules/mod_roleassignments.go
Labels: approved, area/keystone, lgtm, size/M

#8293 Automated cherry pick of #8289: fix:openstack lb 后端ip无法映射到主机的异常处理
  pkg/compute/models/loadbalancerhuaweicachedlbb.go
  pkg/compute/models/loadbalanceropenstackcachedlbb.go
Labels: size/XS

#8299 fix: support filter rds sku by provider
  pkg/compute/models/dbinstance_skus.go
Labels: area/region, size/XS

#8300 Automated cherry pick of #8299: fix: support filter rds sku by provider
  pkg/compute/models/dbinstance_skus.go
Labels: size/XS

#8301 Automated cherry pick of #8299: fix: support filter rds sku by provider
  pkg/compute/models/dbinstance_skus.go
Labels: size/XS

#8302 fix: allwo filter resource by with-meta and with-user-meta filter
  pkg/apis/list.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/mcclient/options/servers.go
Labels: area/region, size/M

#8303 Automated cherry pick of #8302: fix: allwo filter resource by with-meta and with-user-meta filter
  pkg/apis/list.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/mcclient/options/servers.go
Labels: size/M

#8305 stringutils2: add RemoveUtf8Strings func
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/compute/models/managedresource.go
  pkg/keystone/models/identitybase.go
  pkg/util/stringutils2/i18n.go
  pkg/util/stringutils2/i18n_test.go
Labels: approved, area/util, lgtm, size/M

#8306 Automated cherry pick of #8305: stringutils2: add RemoveUtf8Strings func
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/compute/models/managedresource.go
  pkg/keystone/models/identitybase.go
  pkg/util/stringutils2/i18n.go
  pkg/util/stringutils2/i18n_test.go
Labels: approved, lgtm, size/M

#8307 Automated cherry pick of #8305: stringutils2: add RemoveUtf8Strings func
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/compute/models/managedresource.go
  pkg/keystone/models/identitybase.go
  pkg/util/stringutils2/i18n.go
  pkg/util/stringutils2/i18n_test.go
Labels: approved, lgtm, size/M

#8308 fix: 避免并发同步安全组导致规则混乱
  pkg/compute/models/syncworkers.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, area/region, lgtm, size/L

#8309 Automated cherry pick of #8308: fix: 避免并发同步安全组导致规则混乱
  pkg/compute/models/syncworkers.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#8310 Automated cherry pick of #8308: fix: 避免并发同步安全组导致规则混乱
  pkg/compute/models/syncworkers.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: approved, lgtm, size/L

#8312 feature: filter storages by image
  cmd/climc/shell/compute/storages.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
Labels: approved, area/region, lgtm, size/S

#8313 Automated cherry pick of #8312: feature: filter storages by image
  cmd/climc/shell/compute/storages.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
Labels: approved, lgtm, size/S

#8315 Automated cherry pick of #8314: feat(esxi): do not specify portkey in NewVNIC
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/network.go
Labels: approved, lgtm, size/M

#8314 feat(esxi): do not specify portkey in NewVNIC
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/network.go
Labels: approved, lgtm, size/M

#8316 Automated cherry pick of #8314: feat(esxi): do not specify portkey in NewVNIC
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/network.go
Labels: approved, lgtm, size/M

#8317 Automated cherry pick of #8314: feat(esxi): do not specify portkey in NewVNIC
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/network.go
Labels: approved, lgtm, size/M

#8318 Automated cherry pick of #8314: feat(esxi): do not specify portkey in NewVNIC
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/network.go
Labels: approved, lgtm, size/M

#8319 fix: resolve with_meta filter conflict
  pkg/apis/list.go
  pkg/cloudcommon/db/metadataresource.go
Labels: approved, area/util, lgtm, size/S

#8320 Automated cherry pick of #8319: fix: resolve with_meta filter conflict
  pkg/apis/list.go
  pkg/cloudcommon/db/metadataresource.go
Labels: approved, lgtm, size/S

#8326 fix: get images distinct field
  pkg/mcclient/modules/mod_images.go
Labels: approved, area/apigateway, area/climc, lgtm, size/XS

#8327 Automated cherry pick of #8326: fix: get images distinct field
  pkg/mcclient/modules/mod_images.go
Labels: approved, lgtm, size/XS

#8328 Automated cherry pick of #8326: fix: get images distinct field
  pkg/mcclient/modules/mod_images.go
Labels: approved, lgtm, size/XS

#8323 remove alpine build cache before make image
  Makefile
Labels: approved, lgtm, size/XS

#8324 Automated cherry pick of #8323: remove alpine build cache before make image
  Makefile
Labels: approved, lgtm, size/XS

#8330 fix: hostname for instance
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/util/stringutils2/stringutils.go
  pkg/util/stringutils2/stringutils_test.go
Labels: area/region, size/L

#8331 Automated cherry pick of #8330: fix: hostname for instance
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/util/stringutils2/stringutils.go
  pkg/util/stringutils2/stringutils_test.go
Labels: size/L

#8335 Automated cherry pick of #8334: fix(compute): filter cachedimage with health storage
  pkg/compute/models/cachedimages.go
Labels: approved, lgtm, size/XS

#8334 fix(compute): filter cachedimage with health storage
  pkg/compute/models/cachedimages.go
Labels: approved, lgtm, size/XS

#8329 Automated cherry pick of #8304: feature: qcloud create VM with tags
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudprovider/resources.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_remote_update_task.go
  pkg/mcclient/options/servers.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/shell/tags.go
  pkg/multicloud/qcloud/tags.go
Labels: approved, lgtm, size/XL
