Repository yunionio/cloudpods, pull requests merged in 2020-02, with the labels that each got.

#4999 fix: 避免私有云调整配置匹配不到sku
  pkg/compute/models/skus.go
Labels: approved, area/region, lgtm, size/S

#5002 Automated cherry pick of #4999: fix: 避免私有云调整配置匹配不到sku
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#5001 Automated cherry pick of #4999: fix: 避免私有云调整配置匹配不到sku
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#5000 Automated cherry pick of #4999: fix: 避免私有云调整配置匹配不到sku
  pkg/compute/models/skus.go
Labels: approved, lgtm, size/S

#4996 azure的主机监控信息的获取
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/monitor.go
Labels: approved, area/region, lgtm, size/L

#5004 Automated cherry pick of #4996: azure的主机监控信息的获取
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/monitor.go
Labels: approved, area/region, lgtm, size/L

#4998 Automated cherry pick of #4996: azure的主机监控信息的获取
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/monitor.go
Labels: approved, area/region, lgtm, size/L

#4997 Automated cherry pick of #4996: azure的主机监控信息的获取
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/monitor.go
Labels: approved, area/region, lgtm, size/L

#5005 hostman: skip setting up ovn chassis when env support is not ready
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostovn.go
Labels: approved, area/host, lgtm, size/S

#5006 Automated cherry pick of #5005: hostman: fix detection of ovn controller version
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostovn.go
Labels: approved, lgtm, size/S

#5008 hostman: fix hostinfo init interrupted by ovn chassis setup
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, area/host, lgtm, size/XS

#5009 Automated cherry pick of #5008: hostman: fix hostinfo init interrupted by ovn chassis setup
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm

#5010 vpcagent: ignore external stub guestnetworks
  pkg/vpcagent/models/modelset.go
Labels: approved, area/vpcagent, lgtm, size/XS

#5011 Automated cherry pick of #5010: vpcagent: ignore external stub guestnetworks
  pkg/vpcagent/models/modelset.go
Labels: approved, lgtm, size/XS

#5012 fix: network update error caused by vpc feature
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/S

#5013 Automated cherry pick of #5012: fix: network update error caused by vpc feature
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/S

#5014 fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, area/host, lgtm, size/S

#5020 Automated cherry pick of #5014: fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/S

#5019 Automated cherry pick of #5014: fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/S

#5017 Automated cherry pick of #5014: fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/S

#5018 Automated cherry pick of #5014: fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/S

#5016 Automated cherry pick of #5014: fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/S

#5015 Automated cherry pick of #5014: fix: support empty dns domain
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/S

#5021 fix: 避免因大小写导致linux未注入默认用户
  pkg/cloudprovider/instance.go
Labels: approved, area/region, lgtm, size/XS

#5025 Automated cherry pick of #5021: fix: 避免因大小写导致linux未注入默认用户
  pkg/cloudprovider/instance.go
Labels: approved, lgtm, size/XS

#5024 Automated cherry pick of #5021: fix: 避免因大小写导致linux未注入默认用户
  pkg/cloudprovider/instance.go
Labels: approved, lgtm, size/XS

#5022 Automated cherry pick of #5021: fix: 避免因大小写导致linux未注入默认用户
  pkg/cloudprovider/instance.go
Labels: approved, lgtm, size/XS

#5023 Automated cherry pick of #5021: fix: 避免因大小写导致linux未注入默认用户
  pkg/cloudprovider/instance.go
Labels: approved, lgtm, size/XS

#5029 fix: 修复gcp安全组同步问题
  pkg/multicloud/google/securitygroup.go
Labels: approved, lgtm

#5031 Automated cherry pick of #5029: fix: 修复gcp安全组同步问题
  pkg/multicloud/google/securitygroup.go
Labels: approved, lgtm, size/XS

#5037 Automated cherry pick of #5032: aws create with eip fix
  pkg/compute/guestdrivers/aws.go
Labels: approved, lgtm

#5032 aws create with eip fix
  pkg/compute/guestdrivers/aws.go
Labels: approved, area/region, lgtm, size/S

#5035 Automated cherry pick of #5032: aws create with eip fix
  pkg/compute/guestdrivers/aws.go
Labels: approved, lgtm, size/S

#5036 Automated cherry pick of #5032: aws create with eip fix
  pkg/compute/guestdrivers/aws.go
Labels: approved, lgtm

#5034 Automated cherry pick of #5032: aws create with eip fix
  pkg/compute/guestdrivers/aws.go
Labels: approved, lgtm, size/S

#5033 Automated cherry pick of #5032: aws create with eip fix
  pkg/compute/guestdrivers/aws.go
Labels: approved, lgtm, size/S

#5038 fix: 避免因tenantcache未缓存tenant导致创建云账号失败
  pkg/compute/models/cloudaccounts.go
Labels: approved, area/region, lgtm, size/S

#5041 Automated cherry pick of #5038: fix: 避免因tenantcache未缓存tenant导致创建云账号失败
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/S

#5039 Automated cherry pick of #5038: fix: 避免因tenantcache未缓存tenant导致创建云账号失败
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm, size/S

#5040 Automated cherry pick of #5038: fix: 避免因tenantcache未缓存tenant导致创建云账号失败
  pkg/compute/models/cloudaccounts.go
Labels: approved, lgtm

#5026 fix: api gateway rpc handler redundant response
  pkg/apigateway/handler/rpc.go
Labels: area/apigateway, size/S

#5027 Automated cherry pick of #5026: fix: api gateway rpc handler redudant response
  pkg/apigateway/handler/rpc.go
Labels: size/S

#5028 Automated cherry pick of #5026: fix: api gateway rpc handler redudant response
  pkg/apigateway/handler/rpc.go
Labels: size/S

#5030 Automated cherry pick of #5026: fix: api gateway rpc handler redudant response
  pkg/apigateway/handler/rpc.go
Labels: size/S

#5042 bm register support update baremetal
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
Labels: area/baremetal, lgtm, needs-backport, size/M

#5043 Automated cherry pick of #5042: bm register support update baremetal
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
Labels: size/M

#5007 feature: fix customized API documents for authenticate and quota
  Makefile
  pkg/apis/list.go
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/cloudcommon/db/quotas/handler.go
  pkg/cloudcommon/db/quotas/quotakeys.go
  pkg/cloudcommon/db/resourcebase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudcommon/db/statusstandalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/projectquota.go
  pkg/compute/models/quotas.go
  pkg/compute/models/quotas_doc.go
  pkg/compute/models/regionquota.go
  pkg/compute/models/wires.go
  pkg/image/models/quotas.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
  pkg/mcclient/input.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
  scripts/codegen.py
Labels: area/docs, area/util, size/XL

#5044 fix: guest创建兼容keypair参数
  pkg/apis/compute/api.go
Labels: approved, area/region, lgtm, size/XS

#5047 Automated cherry pick of #5044: fix: guest创建兼容keypair参数
  pkg/apis/compute/api.go
Labels: approved, lgtm, size/XS

#5046 Automated cherry pick of #5044: fix: guest创建兼容keypair参数
  pkg/apis/compute/api.go
Labels: approved, lgtm, size/XS

#5045 Automated cherry pick of #5044: fix: guest创建兼容keypair参数
  pkg/apis/compute/api.go
Labels: approved, lgtm, size/XS

#5048 fix: google e2不支持本地盘
  pkg/compute/guestdrivers/google.go
Labels: approved, area/region, lgtm, size/XS

#5049 Automated cherry pick of #5048: fix: google e2不支持本地盘
  pkg/compute/guestdrivers/google.go
Labels: approved, lgtm, size/XS

#5056 Automated cherry pick of #5054: fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5054 fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/S

#5055 Automated cherry pick of #5054: fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5058 Automated cherry pick of #5054: fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5059 Automated cherry pick of #5054: fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5060 Automated cherry pick of #5054: fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5057 Automated cherry pick of #5054: fix: createdAt should not be synced when update
  pkg/compute/models/guests.go
Labels: approved, lgtm

#5065 fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, area/host, lgtm, size/XS

#5070 Automated cherry pick of #5065: fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/XS

#5071 Automated cherry pick of #5065: fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/XS

#5052 fix: progressively update image size while uploading
  pkg/image/models/images.go
  pkg/multicloud/aws/shell/s3.go
  pkg/multicloud/objectstore/shell.go
  pkg/util/s3auth/v4.go
  pkg/util/streamutils/streamutils.go
Labels: approved, area/image, lgtm, size/M

#5069 Automated cherry pick of #5065: fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/XS

#5053 Automated cherry pick of #5052: fix: progressively update image size while uploading
  pkg/image/models/images.go
  pkg/multicloud/aws/shell/s3.go
  pkg/multicloud/objectstore/shell.go
  pkg/util/s3auth/v4.go
  pkg/util/streamutils/streamutils.go
Labels: approved, lgtm, size/M

#5067 Automated cherry pick of #5065: fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/XS

#5068 Automated cherry pick of #5065: fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/XS

#5066 Automated cherry pick of #5065: fix: allow empty domain for windows deployment
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: approved, lgtm, size/XS

#5072 fix: 忽略无权限的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, area/region, lgtm, size/XS

#5076 Automated cherry pick of #5072: fix: 忽略无权限的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, lgtm

#5074 Automated cherry pick of #5072: fix: 忽略无权限的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, lgtm, size/XS

#5075 Automated cherry pick of #5072: fix: 忽略无权限的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, lgtm, size/XS

#5073 Automated cherry pick of #5072: fix: 忽略无权限的资源标签
  pkg/cloudcommon/db/metadata.go
Labels: approved, lgtm, size/XS

#5077 fix: 修复gcp出方向规则同步问题
  pkg/multicloud/google/securitygroup.go
Labels: approved, area/region, lgtm, size/S

#5080 Automated cherry pick of #5077: fix: 修复gcp出方向规则同步问题
  pkg/multicloud/google/securitygroup.go
Labels: approved, lgtm, size/S

#5079 Automated cherry pick of #5077: fix: 修复gcp出方向规则同步问题
  pkg/multicloud/google/securitygroup.go
Labels: approved, lgtm, size/S

#5078 Automated cherry pick of #5077: fix: 修复gcp出方向规则同步问题
  pkg/multicloud/google/securitygroup.go
Labels: approved, lgtm, size/S

#5081 fix: Fix the bug introduced by pr #4921
  pkg/apis/compute/nat.go
  pkg/apis/notify/notification.go
  pkg/compute/models/natstable.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/mod_notification.go
Labels: approved, area/notify, area/region, lgtm, size/M

#5082 Automated cherry pick of #5081: fix: Fix the bug introduced by pr #4921
  pkg/apis/compute/nat.go
  pkg/apis/notify/notification.go
  pkg/compute/models/natstable.go
  pkg/notify/models/mod_contact.go
  pkg/notify/models/mod_notification.go
Labels: approved, lgtm, size/M

#5061 multicloud的vmware监控功能
  pkg/multicloud/esxi/monitor.go
  vendor/github.com/vmware/govmomi/performance/manager.go
  vendor/modules.txt
Labels: approved, area/region, lgtm, size/XL

#5064 Automated cherry pick of #5061: multicloud的vmware监控功能
  pkg/multicloud/esxi/monitor.go
  vendor/github.com/vmware/govmomi/performance/manager.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#5063 Automated cherry pick of #5061: multicloud的vmware监控功能
  pkg/multicloud/esxi/monitor.go
  vendor/github.com/vmware/govmomi/performance/manager.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#5085 webconsole: use base64 encode connect_params
  cmd/climc/shell/webconsole.go
  pkg/webconsole/handlers.go
Labels: approved, area/webconsole, lgtm, size/S

#5086 Automated cherry pick of #5085: webconsole: use base64 encode connect_params
  cmd/climc/shell/webconsole.go
  pkg/webconsole/handlers.go
Labels: approved, lgtm, size/S

#5092 update account bucket options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, area/climc, lgtm, size/M

#5095 Automated cherry pick of #5092: update account bucket options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#5096 Automated cherry pick of #5092: update account bucket options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#5094 Automated cherry pick of #5092: update account bucket options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#5093 Automated cherry pick of #5092: update account bucket options
  cmd/climc/shell/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: approved, lgtm, size/M

#5062 Automated cherry pick of #5061: multicloud的vmware监控功能
  pkg/multicloud/esxi/monitor.go
  vendor/github.com/vmware/govmomi/performance/manager.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#5083 Bugfix/tb bugfix 0211
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/tasks/eip_dissociate_task.go
  pkg/multicloud/ctyun/disk.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/ctyun/host.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ctyun/shell/instance.go
  pkg/multicloud/ctyun/shell/job.go
  pkg/multicloud/ctyun/snapshot.go
Labels: approved, area/region, lgtm, size/M

#5084 Automated cherry pick of #5083: fix ctyun os version
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/tasks/eip_dissociate_task.go
  pkg/multicloud/ctyun/disk.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/ctyun/host.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ctyun/shell/instance.go
  pkg/multicloud/ctyun/shell/job.go
  pkg/multicloud/ctyun/snapshot.go
Labels: approved, lgtm, size/M

#5087 fix(esxi): Create one if no suitable driver exists when creating disk
  pkg/compute/hostdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/region, lgtm, size/M

#5091 Automated cherry pick of #5087: fix(esxi): Create one if no suitable driver when creating disk
  pkg/compute/hostdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm

#5089 Automated cherry pick of #5087: fix(esxi): Create one if no suitable driver exists when creating disk
  pkg/compute/hostdrivers/esxi.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/M

#5111 region: server list by host sn
  cmd/climc/shell/hosts.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: approved, area/region, lgtm, size/S

#5114 Automated cherry pick of #5111: region: server list by host sn
  cmd/climc/shell/hosts.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/S

#5113 Automated cherry pick of #5111: region: server list by host sn
  cmd/climc/shell/hosts.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/S

#5112 Automated cherry pick of #5111: region: server list by host sn
  cmd/climc/shell/hosts.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: approved, lgtm, size/S

#5106 fix(notify): Set some default template
  pkg/notify/models/mod_template.go
Labels: approved, area/notify, lgtm, size/L

#5110 Automated cherry pick of #5106: fix(notify): Set some default template
  pkg/notify/models/mod_template.go
Labels: approved, lgtm, size/L

#5109 Automated cherry pick of #5106: fix(notify): Set some default template
  pkg/notify/models/mod_template.go
Labels: approved, lgtm, size/L

#5108 Automated cherry pick of #5106: fix(notify): Set some default template
  pkg/notify/models/mod_template.go
Labels: approved, lgtm, size/L

#5107 Automated cherry pick of #5106: fix(notify): Set some default template
  pkg/notify/models/mod_template.go
Labels: approved, lgtm, size/L

#5117 fix: 谷歌新加region翻译
  pkg/multicloud/google/latitud_and_longitude.go
Labels: approved, area/region, lgtm, size/XS

#5120 Automated cherry pick of #5117: fix: 谷歌新加region翻译
  pkg/multicloud/google/latitud_and_longitude.go
Labels: approved, lgtm, size/XS

#5119 Automated cherry pick of #5117: fix: 谷歌新加region翻译
  pkg/multicloud/google/latitud_and_longitude.go
Labels: approved, lgtm, size/XS

#5118 Automated cherry pick of #5117: fix: 谷歌新加region翻译
  pkg/multicloud/google/latitud_and_longitude.go
Labels: approved, lgtm, size/XS

#5121 fix(esxiagent): Delete image backup file after saving to glance instead of before
  pkg/hostman/storageman/storage_agent.go
Labels: approved, area/esxiagent, lgtm, size/XS

#5122 Automated cherry pick of #5121: fix(esxiagent): Delete image backup file after saving to glance instead of before
  pkg/hostman/storageman/storage_agent.go
Labels: approved, lgtm, size/XS

#5123 Automated cherry pick of #5121: fix(esxiagent): Delete image backup file after saving to glance instead of before
  pkg/hostman/storageman/storage_agent.go
Labels: approved, lgtm, size/XS

#5124 fix: disks_info typo
  pkg/apis/compute/guests.go
Labels: approved, area/region, lgtm, size/XS

#5125 Automated cherry pick of #5124: fix: disks_info typo
  pkg/apis/compute/guests.go
Labels: approved, lgtm

#5115 aws userdata bugfix
  pkg/apis/compute/guest_const.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/aws.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/instance.go
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
Labels: approved, area/region, lgtm, size/L

#5116 Automated cherry pick of #5115: aws userdata bugfix
  pkg/apis/compute/guest_const.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/aws.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/instance.go
  pkg/util/cloudinit/cloudconfig.go
  pkg/util/cloudinit/cloudconfig_test.go
Labels: approved, lgtm, size/L

#5126 fix: 添加host标签返回值
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: approved, area/region, lgtm, size/S

#5127 Automated cherry pick of #5126: fix: 添加host标签返回值
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: approved, lgtm

#5128 huawei userdata fix
  pkg/compute/guestdrivers/huawei.go
  pkg/multicloud/ctyun/disk.go
  pkg/multicloud/huawei/host.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/instance.go
Labels: approved, area/region, lgtm, needs-area, size/L

#5129 Automated cherry pick of #5128: huawei userdata fix
  pkg/compute/guestdrivers/huawei.go
  pkg/multicloud/ctyun/disk.go
  pkg/multicloud/huawei/host.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/instance.go
Labels: approved, lgtm, size/L

#5130 Bugfix/tb bugfix 021501
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/ctyun/storagecache.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/port.go
  pkg/multicloud/huawei/region.go
Labels: approved, area/region, lgtm, size/M

#5131 Automated cherry pick of #5130: huawei sync fix
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  pkg/multicloud/ctyun/eip.go
  pkg/multicloud/ctyun/storagecache.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/port.go
  pkg/multicloud/huawei/region.go
Labels: approved, lgtm, size/M

#5143 misc bugfix: check scsi driver on add disk
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/ha_guest_deploy_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/util/logclient/consts.go
Labels: approved, area/host, area/region, lgtm, size/M

#5144 Automated cherry pick of #5143: check scsi driver on add disk
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/ha_guest_deploy_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/util/logclient/consts.go
Labels: approved, lgtm, size/M

#5136 regiondrivers: kvm: dummy impl for RequestDeleteVpc
  pkg/compute/regiondrivers/kvm.go
Labels: approved, area/region, lgtm, size/XS

#5137 Automated cherry pick of #5136: regiondrivers: kvm: dummy impl for RequestDeleteVpc
  pkg/compute/regiondrivers/kvm.go
Labels: approved, lgtm, size/XS

#5133 Automated cherry pick of #5132: zstack监控功能
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/M

#5132 zstack监控功能
  pkg/apis/compute/routetable_const.go
  pkg/compute/tasks/ha_disk_create_task.go
  pkg/compute/tasks/ha_guest_deploy_task.go
  pkg/compute/tasks/ha_guest_start_task.go
  pkg/compute/tasks/ha_guest_stop_task.go
  pkg/multicloud/aws/route.go
  pkg/multicloud/aws/routetable.go
  pkg/multicloud/aws/shell/routetable.go
  pkg/multicloud/esxi/monitor.go
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/zstack.go
  pkg/util/iproute2/address.go
  pkg/util/iproute2/address_test.go
  pkg/util/iproute2/doc.go
  pkg/util/iproute2/link.go
  pkg/util/iproute2/link_test.go
  pkg/util/iproute2/route.go
  pkg/util/iproute2/route_test.go
  pkg/util/netutils2/netutils_linux.go
  pkg/util/netutils2/netutils_others.go
Labels: approved, area/region, lgtm, size/L

#5134 Automated cherry pick of #5132: zstack监控功能
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/M

#5135 Automated cherry pick of #5132: zstack监控功能
  pkg/multicloud/zstack/monitor.go
  pkg/multicloud/zstack/zstack.go
Labels: approved, lgtm, size/M

#5138 fix: 避免未过滤掉同一个network底下的guest
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/S

#5142 Automated cherry pick of #5138: fix: 避免未过滤掉同一个network底下的guest
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5141 Automated cherry pick of #5138: fix: 避免未过滤掉同一个network底下的guest
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5140 Automated cherry pick of #5138: fix: 避免未过滤掉同一个network底下的guest
  pkg/compute/models/guests.go
Labels: approved, lgtm

#5139 Automated cherry pick of #5138: fix: 避免未过滤掉同一个network底下的guest
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/S

#5151 fix: 1. adjust default response header timer to 30 seconds 2. set default paging limit to 20
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
Labels: area/util, lgtm, size/S

#5152 Automated cherry pick of #5151: fix: 1. adjust default response header timer to 30 seconds 2. set default paging limit to 20
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
Labels: size/S

#5153 Automated cherry pick of #5151: fix: 1. adjust default response header timer to 30 seconds 2. set default paging limit to 20
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
Labels: size/S

#5154 Automated cherry pick of #5151: fix: 1. adjust default response header timer to 30 seconds 2. set default paging limit to 20
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
Labels: size/S

#5155 Automated cherry pick of #5151: fix: 1. adjust default response header timer to 30 seconds 2. set default paging limit to 20
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/util/httputils/httputils.go
  pkg/util/httputils/httputils_test.go
Labels: size/S

#5157 Automated cherry pick of #5156: fix: add climc helper scripts into docker images
  build/climc/root/opt/yunion/scripts/rbac/domainadmin.yaml
  build/climc/root/opt/yunion/scripts/rbac/member.yaml
  build/climc/root/opt/yunion/scripts/rbac/projectowner.yaml
  build/climc/root/opt/yunion/scripts/rbac/sysadmin.yaml
  build/climc/root/opt/yunion/scripts/tools/clean_account.sh
  build/climc/root/opt/yunion/scripts/tools/clean_eip.sh
  build/climc/root/opt/yunion/scripts/tools/clean_host.sh
  build/climc/root/opt/yunion/scripts/tools/clean_loadbalancer.sh
  build/climc/root/opt/yunion/scripts/tools/clean_loadbalancer_acl.sh
  build/climc/root/opt/yunion/scripts/tools/clean_loadbalancer_certificate.sh
  build/climc/root/opt/yunion/scripts/tools/clean_provider.sh
  build/climc/root/opt/yunion/scripts/tools/clean_snapshot.sh
  build/climc/root/opt/yunion/scripts/tools/clean_storage.sh
  build/climc/root/opt/yunion/scripts/tools/clean_storagecache.sh
  build/climc/root/opt/yunion/scripts/tools/clean_vpc.sh
  build/docker/Dockerfile.climc
Labels: size/L

#5156 fix: add climc helper scripts into docker images
  build/climc/root/opt/yunion/scripts/rbac/domainadmin.yaml
  build/climc/root/opt/yunion/scripts/rbac/member.yaml
  build/climc/root/opt/yunion/scripts/rbac/projectowner.yaml
  build/climc/root/opt/yunion/scripts/rbac/sysadmin.yaml
  build/climc/root/opt/yunion/scripts/tools/clean_account.sh
  build/climc/root/opt/yunion/scripts/tools/clean_eip.sh
  build/climc/root/opt/yunion/scripts/tools/clean_host.sh
  build/climc/root/opt/yunion/scripts/tools/clean_loadbalancer.sh
  build/climc/root/opt/yunion/scripts/tools/clean_loadbalancer_acl.sh
  build/climc/root/opt/yunion/scripts/tools/clean_loadbalancer_certificate.sh
  build/climc/root/opt/yunion/scripts/tools/clean_provider.sh
  build/climc/root/opt/yunion/scripts/tools/clean_snapshot.sh
  build/climc/root/opt/yunion/scripts/tools/clean_storage.sh
  build/climc/root/opt/yunion/scripts/tools/clean_storagecache.sh
  build/climc/root/opt/yunion/scripts/tools/clean_vpc.sh
  build/docker/Dockerfile.climc
Labels: approved, area/climc, lgtm, size/L

#5159 region: lbagent: deploy: use 'public' endpoint type
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/lbagent/models/haproxy.go
Labels: approved, area/region, lgtm, size/XS

#5160 Automated cherry pick of #5159: region: lbagent: deploy: use 'public' endpoint type
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/lbagent/models/haproxy.go
Labels: approved, lgtm, size/XS

#5172 Automated cherry pick of #5159: region: lbagent: deploy: use 'public' endpoint type
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/lbagent/models/haproxy.go
Labels: approved, lgtm

#5167 fix: 避免将虚拟机ip同步到弹性网卡
  pkg/multicloud/openstack/port.go
Labels: approved, area/region, lgtm, size/S

#5171 Automated cherry pick of #5167: fix: 避免将虚拟机ip同步到弹性网卡
  pkg/multicloud/openstack/port.go
Labels: approved, lgtm, size/S

#5169 Automated cherry pick of #5167: fix: 避免将虚拟机ip同步到弹性网卡
  pkg/multicloud/openstack/port.go
Labels: approved, lgtm, size/S

#5170 Automated cherry pick of #5167: fix: 避免将虚拟机ip同步到弹性网卡
  pkg/multicloud/openstack/port.go
Labels: approved, lgtm

#5168 Automated cherry pick of #5167: fix: 避免将虚拟机ip同步到弹性网卡
  pkg/multicloud/openstack/port.go
Labels: approved, lgtm, size/S
