Repository yunionio/cloudpods, pull requests merged in 2020-09, with the labels that each got.

#7700 Automated cherry pick of #7699: fix: http error limit request body length fix: http error limit request body length
  pkg/util/httputils/httputils.go
Labels: approved, lgtm, size/S

#7696 fix: server purge may fail
  pkg/cloudcommon/db/taskman/subtasks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_delete_task.go
Labels: approved, area/region, lgtm, size/S

#7697 Automated cherry pick of #7696: fix: server purge may fail
  pkg/cloudcommon/db/taskman/subtasks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_delete_task.go
Labels: approved, lgtm, size/S

#7699 fix: http error limit request body length
  pkg/util/httputils/httputils.go
Labels: approved, area/util, lgtm, size/S

#7698 Automated cherry pick of #7696: fix: server purge may fail
  pkg/cloudcommon/db/taskman/subtasks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_delete_task.go
Labels: approved, lgtm, size/S

#7667 monitor commonalert bugfix
  cmd/climc/shell/monitor/alertdashboard.go
  cmd/climc/shell/monitor/commonalertmetric.go
  cmd/climc/shell/monitor/commonalertmetricfield.go
  pkg/apis/monitor/alertdashboard.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/mcclient/modules/mod_alert_dashboard.go
  pkg/mcclient/modules/mod_commonalert_metric_field.go
  pkg/mcclient/options/monitor/alertdashboard.go
  pkg/mcclient/options/monitor/commonalertmetric.go
  pkg/mcclient/options/monitor/commonalertmetricfield.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/metric_field.go
  pkg/monitor/models/metric_joint.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/service/handlers.go
Labels: approved, area/monitor, lgtm, size/XL

#7692 Fix for Notify
  pkg/apis/notify/config.go
  pkg/notify/models/config.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/options/options.go
Labels: approved, area/notify, lgtm, size/L

#7671 Automated cherry pick of #7667: monitor commonalert bugfix
  cmd/climc/shell/monitor/alertdashboard.go
  cmd/climc/shell/monitor/commonalertmetric.go
  cmd/climc/shell/monitor/commonalertmetricfield.go
  pkg/apis/monitor/alertdashboard.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/mcclient/modules/mod_alert_dashboard.go
  pkg/mcclient/modules/mod_commonalert_metric_field.go
  pkg/mcclient/options/monitor/alertdashboard.go
  pkg/mcclient/options/monitor/commonalertmetric.go
  pkg/mcclient/options/monitor/commonalertmetricfield.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/metric_field.go
  pkg/monitor/models/metric_joint.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/service/handlers.go
Labels: size/XL

#7680 feature: snapshot list by guest
  cmd/climc/shell/compute/snapshots.go
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: area/region, size/S

#7681 Automated cherry pick of #7680: snapshot list by guest
  cmd/climc/shell/compute/snapshots.go
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/S

#7672 Automated cherry pick of #7661: fix(host-deployer): Exit correctly after mounting
  pkg/cloudcommon/agent/agent.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/template.go
Labels: approved, lgtm, size/M

#7673 Automated cherry pick of #7661: fix(host-deployer): Exit correctly after mounting
  pkg/cloudcommon/agent/agent.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/template.go
Labels: approved, lgtm, size/M

#7661 Fix problem of esxi
  pkg/cloudcommon/agent/agent.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/esxi/template.go
Labels: approved, area/esxiagent, lgtm, size/M

#7693 Automated cherry pick of #7692: feat(notify): Support update for notify config
  pkg/apis/notify/config.go
  pkg/notify/models/config.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/options/options.go
Labels: approved, lgtm, size/L

#7694 fix: apigateway user info add is_local attribtue
  pkg/apigateway/handler/auth.go
Labels: approved, area/apigateway, lgtm, size/XS

#7695 Automated cherry pick of #7694: fix: apigateway user info add is_local attribtue
  pkg/apigateway/handler/auth.go
Labels: approved, lgtm, size/XS

#7701 feature: emualated ssd support
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
  pkg/compute/models/guestdisks.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: approved, area/host, area/region, lgtm, size/S

#7659 Automated cherry pick of #7649: fix: vmware esxi host detects vnic portgroup info
  pkg/cloudprovider/resources.go
  pkg/compute/models/hosts.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/hostnic.go
Labels: approved, lgtm, size/L

#7660 Automated cherry pick of #7649: fix: vmware esxi host detects vnic portgroup info
  pkg/cloudprovider/resources.go
  pkg/compute/models/hosts.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/hostnic.go
Labels: approved, lgtm, size/L

#7649 fix: vmware esxi host detects vnic portgroup info
  pkg/cloudprovider/resources.go
  pkg/compute/models/hosts.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/hostnic.go
Labels: approved, lgtm, size/L

#7664 fix: avoid delete aws iam user failed
  pkg/multicloud/aws/iam_user.go
Labels: approved, area/cloudid, lgtm, size/XS

#7666 Automated cherry pick of #7664: fix: avoid delete aws iam user failed
  pkg/multicloud/aws/clouduser.go
Labels: approved, lgtm

#7665 Automated cherry pick of #7664: fix: avoid delete aws iam user failed
  pkg/multicloud/aws/iam_user.go
Labels: size/XS

#7710 httperrors: use existing details if id is not present
  pkg/httperrors/httperrors.go
Labels: approved, area/apigateway, area/region, lgtm, size/M

#7711 Automated cherry pick of #7710: httperrors: use existing details if id is not present
  pkg/httperrors/httperrors.go
Labels: approved, lgtm, size/M

#7712 Bugfix/yousong i18n
  pkg/httperrors/httperrors.go
  pkg/mcclient/session.go
Labels: approved, area/region, lgtm, size/S

#7713 Automated cherry pick of #7712: httperrors: support setting lang with X-Yunion-Lang
  pkg/httperrors/httperrors.go
  pkg/mcclient/session.go
Labels: approved, lgtm, size/S

#7708 Automated cherry pick of #7706: hostinfo: try create network add is_on_premise
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#7709 Automated cherry pick of #7706: hostinfo: try create network add is_on_premise
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#7702 fix: add details for account delete
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/purge.go
Labels: approved, area/region, lgtm, size/S

#7703 Automated cherry pick of #7702: fix: add details for account delete
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/purge.go
Labels: approved, lgtm, size/S

#7706 hostinfo: try create network add is_on_premise
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, area/host, lgtm, size/XS

#7704 Automated cherry pick of #7702: fix: add details for account delete
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/purge.go
Labels: approved, lgtm, size/S

#7707 Automated cherry pick of #7706: hostinfo: try create network add is_on_premise
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, lgtm, size/XS

#7714 Feature & Fix for Notify
  cmd/climc/shell/notifyv2/config.go
  pkg/apis/notify/config.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/mcclient/modules/notify/consts.go
  pkg/notify/models/config.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
Labels: approved, area/notify, lgtm, size/L

#7715 Automated cherry pick of #7714: Feature & Fix for Notify
  cmd/climc/shell/notifyv2/config.go
  pkg/apis/notify/config.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/mcclient/modules/notify/consts.go
  pkg/notify/models/config.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
Labels: approved, lgtm, size/L

#7722 hosts: update host status to unknown on host offline
  pkg/compute/models/hosts.go
Labels: approved, area/region, lgtm, size/XS

#7724 Automated cherry pick of #7722: update host status to unknown on host offline
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/XS

#7723 Automated cherry pick of #7722: update host status to unknown on host offline
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/XS

#7720 Automated cherry pick of #7718: vmware disk support deploy lvm partition
  pkg/hostman/diskutils/disk.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/L

#7718 feature: vmware disk support deploy lvm partition
  pkg/hostman/diskutils/disk.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, area/host, lgtm, size/L

#7719 Automated cherry pick of #7718: vmware disk support deploy lvm partition
  pkg/hostman/diskutils/disk.go
  pkg/hostman/diskutils/diskutils.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: approved, lgtm, size/L

#7716 alertrecords bugfix
  pkg/monitor/models/alertrecord.go
Labels: approved, area/monitor, lgtm, size/S

#7717 Automated cherry pick of #7716: alert record bugfix
  pkg/monitor/models/alertrecord.go
Labels: approved, lgtm, size/S

#7725 create classic vpc fix
  pkg/compute/models/guests.go
  pkg/compute/models/vpcs.go
Labels: approved, area/region, lgtm, size/XS

#7726 Automated cherry pick of #7725: create classic vpc fix
  pkg/compute/models/guests.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/XS

#7728 Automated cherry pick of #7725: create classic vpc fix
  pkg/compute/models/guests.go
  pkg/compute/models/vpcs.go
Labels: approved, lgtm, size/XS

#7734 Automated cherry pick of #7733: Feature & Fix for Notify
  pkg/apis/notify/receiver.go
  pkg/mcclient/modules/mod_notify.go
  pkg/mcclient/modules/notify/consts.go
  pkg/notify/interface.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subcontact.go
  pkg/notify/rpc/send.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/subcontact_pull_task.go
Labels: approved, lgtm, size/L

#7735 fix(compute): return InputParameterError while ValidateCreateData
  pkg/compute/models/scaling_trigger.go
  pkg/compute/models/scheduled_tasks.go
Labels: area/region, lgtm, size/S

#7736 Automated cherry pick of #7735: fix(compute): return InputParameterError while ValidateCreateData
  pkg/compute/models/scaling_trigger.go
  pkg/compute/models/scheduled_tasks.go
Labels: size/S

#7737 Automated cherry pick of #7735: fix(compute): return InputParameterError while ValidateCreateData
  pkg/compute/models/scaling_trigger.go
  pkg/compute/models/scheduled_tasks.go
Labels: size/S

#7740 fix: find correct esxi host access ip
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
Labels: area/esxiagent, size/L

#7741 fix: search by chs projectname or domainname
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/keystone/models/identitybase.go
Labels: area/keystone, area/region, size/S

#7742 Automated cherry pick of #7741: fix: search by chs projectname or domainname
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/keystone/models/identitybase.go
Labels: size/S

#7743 Automated cherry pick of #7741: fix: search by chs projectname or domainname
  pkg/cloudcommon/db/domain.go
  pkg/cloudcommon/db/project.go
  pkg/keystone/models/identitybase.go
Labels: size/S

#7744 glance: check min disk size on update
  pkg/image/models/images.go
Labels: area/image, size/S

#7745 Automated cherry pick of #7744: glance: check min disk size on update
  pkg/image/models/images.go
Labels: size/S

#7746 Automated cherry pick of #7744: glance: check min disk size on update
  pkg/image/models/images.go
Labels: size/S

#7747 Automated cherry pick of #7744: glance: check min disk size on update
  pkg/image/models/images.go
Labels: size/S

#7753 fix: remove redundant auth cookie in sso login
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/oidc.go
Labels: area/apigateway, size/XS

#7754 Automated cherry pick of #7753: fix: remove redundant auth cookie in sso login
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/oidc.go
Labels: size/XS

#7757 fix: support VirtualDiskRawDiskMappingVer1BackingInfo
  pkg/multicloud/esxi/vdisk.go
Labels: size/L

#7758 Automated cherry pick of #7757: fix: support VirtualDiskRawDiskMappingVer1BackingInfo
  pkg/multicloud/esxi/vdisk.go
Labels: size/L

#7759 Automated cherry pick of #7757: fix: support VirtualDiskRawDiskMappingVer1BackingInfo
  pkg/multicloud/esxi/vdisk.go
Labels: size/L

#7755 Automated cherry pick of #7740: fix: find correct esxi host access ip
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
Labels: size/L

#7756 Automated cherry pick of #7740: fix: find correct esxi host access ip
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/shell/host.go
Labels: size/L

#7748 feat(esxi): correctly judge whether inet is nil
  pkg/multicloud/esxi/devtools.go
Labels: size/XS

#7749 Automated cherry pick of #7748: feat(esxi): correctly judge whether inet is nil
  pkg/multicloud/esxi/devtools.go
Labels: size/XS

#7751 Hotfix/qx cloudid optimized
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/statusinfrasuserresource.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/clouduser.go
Labels: area/cloudid, size/L

#7752 Automated cherry pick of #7751: fix: optimized cloudid
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/statusinfrasuserresource.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/clouduser.go
Labels: size/L

#7761 Automated cherry pick of #7760: fix: scheduler aware policy
  pkg/apis/scheduler/api.go
  pkg/compute/tasks/schedule.go
  pkg/scheduler/algorithm/predicates/domain_predicate.go
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
Labels: approved, lgtm

#7760 fix: scheduler aware policy
  pkg/apis/scheduler/api.go
  pkg/compute/tasks/schedule.go
  pkg/scheduler/algorithm/predicates/domain_predicate.go
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
Labels: approved, area/region, area/scheduler, lgtm, size/M

#7739 fix: valid update name and update dns recordset
  pkg/apis/compute/dnsrecordsets.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dns_recordsets.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/scaling_policy.go
Labels: approved, area/region, lgtm, size/M

#7763 Automated cherry pick of #7739: fix: valid update name and update dns recordset
  pkg/apis/compute/dnsrecordsets.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dns_recordsets.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/scaling_policy.go
Labels: approved, lgtm, size/M

#7765 Automated cherry pick of #7764: pex register add optional column mac_access
  pkg/apigateway/handler/misc.go
Labels: approved, lgtm, size/XS

#7766 Automated cherry pick of #7764: pex register add optional column mac_access
  pkg/apigateway/handler/misc.go
Labels: approved, lgtm, size/XS

#7764 pex register add optional column mac_access
  pkg/apigateway/handler/misc.go
Labels: approved, area/apigateway, lgtm, size/XS

#7767 fix: cloudid optimized
  pkg/apis/cloudid/cloudgroup.go
  pkg/apis/cloudid/cloudgroupcache.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/cloudgroupcaches.go
  pkg/cloudid/options/options.go
  pkg/cloudid/service/service.go
  pkg/cloudid/tasks/cloudgroup_sync_status_task.go
  pkg/cloudid/tasks/cloudgroupcache_sync_status_task.go
  pkg/multicloud/aliyun/ram_user.go
  pkg/multicloud/aliyun/shell/ram_user.go
  pkg/multicloud/aws/iam_user.go
Labels: approved, area/cloudid, lgtm, size/L

#7768 Automated cherry pick of #7767: fix: cloudid optimized
  pkg/apis/cloudid/cloudgroup.go
  pkg/apis/cloudid/cloudgroupcache.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/cloudgroupcaches.go
  pkg/cloudid/options/options.go
  pkg/cloudid/service/service.go
  pkg/cloudid/tasks/cloudgroup_sync_status_task.go
  pkg/cloudid/tasks/cloudgroupcache_sync_status_task.go
  pkg/multicloud/aliyun/ram_user.go
  pkg/multicloud/aliyun/shell/ram_user.go
  pkg/multicloud/aws/iam_user.go
Labels: approved, lgtm, size/L

#7776 climc: k8s cluster grafana componet support subpath
  pkg/mcclient/options/k8s/cluster.go
Labels: area/climc, size/M

#7777 Automated cherry pick of #7776: climc: k8s cluster grafana componet support subpath
  pkg/mcclient/options/k8s/cluster.go
Labels: size/M

#7772 fix: skup syncing lb, rds, redis instances in tasks
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancers.go
Labels: approved, lgtm

#7774 Automated cherry pick of #7772: fix: skup syncing lb, rds, redis instances in tasks
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancers.go
Labels: approved, lgtm, size/S

#7775 Automated cherry pick of #7772: fix: skup syncing lb, rds, redis instances in tasks
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancers.go
Labels: approved, lgtm, size/S

#7773 Automated cherry pick of #7772: fix: skup syncing lb, rds, redis instances in tasks
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancers.go
Labels: approved, lgtm, size/S

#7769 fix: network address list respect privilige of user
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
Labels: approved, area/region, lgtm, size/M

#7770 Automated cherry pick of #7769: fix: network address list respect privilige of user
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#7771 Automated cherry pick of #7769: fix: network address list respect privilige of user
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
Labels: approved, lgtm, size/M

#7780 fix: user idps attributes includes template name
  pkg/apis/identity/identityprovider.go
  pkg/keystone/models/expandidps.go
Labels: approved, area/keystone, lgtm, size/XS

#7782 fix(notify): Replace String() with GetString()
  pkg/cloudcommon/notifyclient/notify.go
Labels: approved, lgtm, size/XS

#7785 Automated cherry pick of #7782: fix(notify): Replace String() with GetString()
  pkg/cloudcommon/notifyclient/notify.go
Labels: approved, lgtm, size/XS

#7784 Automated cherry pick of #7782: fix(notify): Replace String() with GetString()
  pkg/cloudcommon/notifyclient/notify.go
Labels: approved, lgtm, size/XS

#7783 Automated cherry pick of #7782: fix(notify): Replace String() with GetString()
  pkg/cloudcommon/notifyclient/notify.go
Labels: approved, lgtm, size/XS

#7786 fix(scheduler): fix array out of bounds when sorting hosts
  pkg/scheduler/manager/instancegroup_select.go
Labels: approved, area/scheduler, lgtm, size/XS

#7787 Automated cherry pick of #7786: fix(scheduler): fix array out of bounds when sorting hosts
  pkg/scheduler/manager/instancegroup_select.go
Labels: approved, lgtm, size/XS

#7788 Automated cherry pick of #7786: fix(scheduler): fix array out of bounds when sorting hosts
  pkg/scheduler/manager/instancegroup_select.go
Labels: approved, lgtm, size/XS

#7812 Automated cherry pick of #7811: fix: prevent users in disabled idp from login
  pkg/keystone/tokens/auth.go
Labels: approved, lgtm, size/XS

#7794 Automated cherry pick of #7793: fix: aliyun wulanchabu region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aliyun/latitud_and_longitude.go
Labels: approved, lgtm, size/XS

#7795 Automated cherry pick of #7793: fix: aliyun wulanchabu region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aliyun/latitud_and_longitude.go
Labels: size/XS

#7813 Automated cherry pick of #7811: fix: prevent users in disabled idp from login
  pkg/keystone/tokens/auth.go
Labels: approved, lgtm, size/XS

#7793 fix: aliyun wulanchabu region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aliyun/latitud_and_longitude.go
Labels: approved, area/region, lgtm, size/XS

#7799 Automated cherry pick of #7798: guest short desc add backup host id
  pkg/compute/models/guests.go
Labels: approved, lgtm

#7811 fix: prevent users in disabled idp from login
  pkg/keystone/tokens/auth.go
Labels: approved, area/keystone, lgtm, size/XS

#7789 bugfix : fix get ubuntu version
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, area/host, lgtm, size/XS

#7792 Automated cherry pick of #7789: fix get ubuntu version
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/XS

#7791 Automated cherry pick of #7789: fix get ubuntu version
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/XS

#7815 Automated cherry pick of #7814: httperrors: add Error type
  pkg/apis/output.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/httperrors/httperrors.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/subscriptionmodel/subcription.go
Labels: approved, lgtm, size/M

#7796 fix: sync groups for user
  pkg/cloudid/tasks/clouduser_sync_groups_task.go
Labels: approved, area/cloudid, lgtm, size/XS

#7801 Automated cherry pick of #7798: guest short desc add backup host id
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#7800 Automated cherry pick of #7798: guest short desc add backup host id
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/XS

#7790 Automated cherry pick of #7789: fix get ubuntu version
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/XS

#7797 Automated cherry pick of #7796: fix: sync groups for user
  pkg/cloudid/tasks/clouduser_sync_groups_task.go
Labels: approved, lgtm, size/XS

#7798 bugfix: guest short desc add backup host id
  pkg/compute/models/guests.go
Labels: approved, area/region, lgtm, size/XS

#7804 vpcagent: guard against foul eip records
  pkg/vpcagent/models/modelset.go
Labels: approved, area/vpcagent, lgtm, size/XS

#7805 Automated cherry pick of #7804: vpcagent: guard against foul eip records
  pkg/vpcagent/models/modelset.go
Labels: approved, lgtm, size/XS

#7807 fix(notify): break down permissions of notifyconfigs
  pkg/notify/models/config.go
Labels: approved, area/notify, lgtm, size/S

#7816 Automated cherry pick of #7807: fix(notify): break down permissions of notifyconfigs
  pkg/notify/models/config.go
Labels: approved, lgtm, size/S

#7814 treewide: DeleteFailReason as an object with translated details
  pkg/apis/output.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/httperrors/httperrors.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/subscriptionmodel/subcription.go
Labels: approved, lgtm, size/M

#7817 bugfix: isolated devices info collect reenterable
  pkg/baremetal/tasks/baseprepare.go
Labels: approved, lgtm, size/M

#7818 Automated cherry pick of #7817: isolated devices info reenterable
  pkg/baremetal/tasks/baseprepare.go
Labels: approved, lgtm, size/M

#7808 fix: check assign-host previliges
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/helper.go
  pkg/compute/models/hosts.go
Labels: approved, area/region, lgtm, size/M

#7809 Automated cherry pick of #7808: fix: check assign-host previliges
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/helper.go
  pkg/compute/models/hosts.go
Labels: approved, lgtm, size/M

#7810 bugfix: fix host errors output
  pkg/hostman/diskutils/fsutils.go
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostbridge/linux_bridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/cgrouputils/cgrouputils.go
Labels: approved, area/host, lgtm, size/L

#7819 Automated cherry pick of #7810: fix host error output
  pkg/hostman/diskutils/fsutils.go
  pkg/hostman/guestfs/kvmpart.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostbridge/linux_bridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/cgrouputils/cgrouputils.go
Labels: approved, lgtm, size/L

#7806 Automated cherry pick of #7804: vpcagent: guard against foul eip records
  pkg/vpcagent/models/modelset.go
Labels: approved, lgtm, size/XS

#7762 dns access
  pkg/apis/compute/dnsrecordsets.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/dnszone.go
  pkg/cloudprovider/dnszone_test.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/dns_recordsets.go
  pkg/compute/models/dns_zonecaches.go
  pkg/compute/models/dns_zones.go
  pkg/mcclient/options/dnszone_recordsets.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/dns_domain.go
  pkg/multicloud/aliyun/dns_domain_record.go
  pkg/multicloud/aliyun/private_zone.go
  pkg/multicloud/aliyun/private_zone_record.go
  pkg/multicloud/aliyun/provider/provider.go
  pkg/multicloud/aliyun/shell/dns_domain.go
  pkg/multicloud/aliyun/shell/private_zone.go
  pkg/multicloud/aws/dnshostedzone.go
  pkg/multicloud/aws/dnsrecordset.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/shell/hostedzone.go
  pkg/multicloud/qcloud/dnspod_domain.go
  pkg/multicloud/qcloud/dnspod_record.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/shell/dnspod.go
Labels: approved, area/region, lgtm, size/XXL

#7803 Automated cherry pick of #7802: Optimization of the scheduler
  go.mod
  go.sum
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/instancegroup_select.go
  pkg/scheduler/core/result.go
  pkg/scheduler/core/result_helper.go
  pkg/scheduler/core/types.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/manager/result_helper.go
  pkg/scheduler/manager/task_queue.go
  pkg/scheduler/test/doc.go
  pkg/scheduler/test/generic_scheduler_test.go
  pkg/scheduler/test/mock/core.go
  pkg/scheduler/test/mock/doc.go
  pkg/scheduler/test/prepare.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#7802 Optimization of the scheduler
  go.mod
  go.sum
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/core/instancegroup_select.go
  pkg/scheduler/core/result.go
  pkg/scheduler/core/result_helper.go
  pkg/scheduler/core/types.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/manager/result_helper.go
  pkg/scheduler/manager/task_queue.go
  pkg/scheduler/test/doc.go
  pkg/scheduler/test/generic_scheduler_test.go
  pkg/scheduler/test/mock/core.go
  pkg/scheduler/test/mock/doc.go
  pkg/scheduler/test/prepare.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, area/scheduler, lgtm, size/XXL

#7822 Automated cherry pick of #7821: fix(esxiagent): return image extid not id
  pkg/hostman/storageman/imagecachemanager_agent.go
Labels: approved, lgtm, size/XS

#7826 Automated cherry pick of #7821: fix(esxiagent): return image extid not id
  pkg/hostman/storageman/imagecachemanager_agent.go
Labels: approved, lgtm, size/XS

#7820 fix: ignore 409 error when doing redfish power on
  pkg/baremetal/manager.go
Labels: approved, lgtm, size/S

#7823 Automated cherry pick of #7821: fix(esxiagent): return image extid not id
  pkg/hostman/storageman/imagecachemanager_agent.go
Labels: approved, lgtm, size/XS

#7821 fix(esxiagent): return image extid not id
  pkg/hostman/storageman/imagecachemanager_agent.go
Labels: approved, area/esxiagent, lgtm, size/XS

#7824 Automated cherry pick of #7820: fix: ignore 409 error when doing redfish power on
  pkg/baremetal/manager.go
Labels: approved, lgtm, size/S

#7825 Automated cherry pick of #7821: fix(esxiagent): return image extid not id
  pkg/hostman/storageman/imagecachemanager_agent.go
Labels: size/XS

#7827 Automated cherry pick of #7820: fix: ignore 409 error when doing redfish power on
  pkg/baremetal/manager.go
Labels: approved, lgtm, size/S

#7828 fix: wire usage stats incorrect
  pkg/compute/models/wires.go
Labels: approved, area/region, lgtm, size/S

#7829 Automated cherry pick of #7828: fix: wire usage stats incorrect
  pkg/compute/models/wires.go
Labels: approved, lgtm, size/S

#7830 Automated cherry pick of #7828: fix: wire usage stats incorrect
  pkg/compute/models/wires.go
Labels: approved, lgtm, size/S

#7845 Feat & Fix & Refactor for ESXi
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/hosts.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, area/esxiagent, area/region, lgtm, size/L

#7849 Automated cherry pick of #7845: Feat & Fix & Refactor for ESXi
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/hosts.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#7846 Automated cherry pick of #7845: Feat & Fix & Refactor for ESXi
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/hosts.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#7847 Automated cherry pick of #7845: Feat & Fix & Refactor for ESXi
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/hosts.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#7848 Automated cherry pick of #7845: Feat & Fix & Refactor for ESXi
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/hosts.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/datacenter.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: approved, lgtm, size/L

#7831 fix: recode project-role rpc handle to support group role assignment
  cmd/climc/shell/identity/role_assignments.go
  go.mod
  go.sum
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/modules/mod_credentials.go
  pkg/mcclient/modules/mod_roleassignments.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/route53/service.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/conditions.go
Labels: approved, area/apigateway, area/keystone, lgtm, size/XL

#7840 Automated cherry pick of #7838: commonalert bugfix:
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/commalert.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/unifiedmonitor.go
Labels: approved, lgtm, size/L

#7839 Automated cherry pick of #7831: fix: recode project-role rpc handle to support group role assignment results by user or project
  cmd/climc/shell/identity/role_assignments.go
  go.mod
  go.sum
  pkg/apis/identity/assignments.go
  pkg/keystone/models/assignments.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/modules/mod_credentials.go
  pkg/mcclient/modules/mod_roleassignments.go
  vendor/github.com/aws/aws-sdk-go/service/route53/api.go
  vendor/github.com/aws/aws-sdk-go/service/route53/errors.go
  vendor/github.com/aws/aws-sdk-go/service/route53/service.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/conditions.go
Labels: approved, lgtm, size/XL

#7841 fix: avoid create public zone failed
  pkg/compute/models/dns_zonecaches.go
  pkg/compute/models/dns_zones.go
Labels: approved, area/region, lgtm, size/XS

#7842 Automated cherry pick of #7841: fix: avoid create public zone failed
  pkg/compute/models/dns_zonecaches.go
  pkg/compute/models/dns_zones.go
Labels: approved, lgtm, size/XS

#7843 fix: optimzed clouduser
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/clouduser.go
  pkg/mcclient/options/clouduser.go
Labels: approved, area/cloudid, lgtm, size/M
