Repository yunionio/cloudpods, pull requests merged in 2020-06, with the labels that each got.

#6670 bugfix: get snapshots order by created at asc
  pkg/compute/models/snapshots.go
Labels: area/region, size/XS

#6671 Automated cherry pick of #6670: get snapshots order by created at asc
  pkg/compute/models/snapshots.go
Labels: size/XS

#6673 Automated cherry pick of #6670: get snapshots order by created at asc
  pkg/compute/models/snapshots.go
Labels: size/XS

#6675 fix: add us-west4 for google region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/google/latitud_and_longitude.go
Labels: area/region, size/XS

#6676 Automated cherry pick of #6675: fix: add us-west4 for google region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/google/latitud_and_longitude.go
Labels: size/XS

#6677 Automated cherry pick of #6675: fix: add us-west4 for google region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/google/latitud_and_longitude.go
Labels: size/XS

#6678 Automated cherry pick of #6675: fix: add us-west4 for google region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/google/latitud_and_longitude.go
Labels: size/XS

#6679 Automated cherry pick of #6675: fix: add us-west4 for google region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/google/latitud_and_longitude.go
Labels: size/XS

#6664 在优化建议资源列表中增加费用信息
  pkg/monitor/models/suggestsysalart.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/tasks/resolve_unused_task.go
Labels: area/monitor, size/M

#6665 Automated cherry pick of #6664: 在优化建议资源列表中增加费用信息
  pkg/monitor/models/suggestsysalart.go
  pkg/monitor/suggestsysdrivers/common.go
  pkg/monitor/suggestsysdrivers/diskunused.go
  pkg/monitor/suggestsysdrivers/eipunused.go
  pkg/monitor/suggestsysdrivers/lbunused.go
  pkg/monitor/tasks/resolve_unused_task.go
Labels: size/M

#6667 Automated cherry pick of #6666: fix: 安全组规则返回项目id信息
  pkg/apis/compute/dbinstance_account.go
  pkg/apis/compute/dbinstance_database.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/elasticcachebackup.go
  pkg/apis/compute/secgrouprule.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstance_databases.go
  pkg/compute/models/elasticcache_accounts.go
  pkg/compute/models/elasticcache_acls.go
  pkg/compute/models/elasticcache_backups.go
  pkg/compute/models/secgrouprules.go
Labels: size/S

#6684 fix: gcp path escape for object
  pkg/multicloud/google/bucket.go
  pkg/multicloud/google/bucketacl.go
  pkg/multicloud/google/s3object.go
Labels: area/region, size/S

#6685 Automated cherry pick of #6684: fix: gcp path escape for object
  pkg/multicloud/google/bucket.go
  pkg/multicloud/google/bucketacl.go
  pkg/multicloud/google/s3object.go
Labels: size/S

#6680 fix: sync s3 bucket status
  pkg/compute/regiondrivers/kvm.go
Labels: area/region, size/S

#6681 Automated cherry pick of #6680: fix: sync s3 bucket status
  pkg/compute/regiondrivers/kvm.go
Labels: size/S

#6688 Automated cherry pick of #6686: fix: 避免锁超时
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#6689 Automated cherry pick of #6686: fix: 避免锁超时
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#6690 Automated cherry pick of #6686: fix: 避免锁超时
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#6686 fix: 避免锁超时
  pkg/compute/models/secgroups.go
Labels: approved, area/region, lgtm, size/S

#6687 Automated cherry pick of #6686: fix: 避免锁超时
  pkg/compute/models/secgroups.go
Labels: approved, lgtm, size/S

#6697 fix: apigateway expose esxiagent service avaiability
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/S

#6698 Automated cherry pick of #6697: fix: apigateway expose esxiagent service avaiability
  pkg/apigateway/handler/auth.go
Labels: size/S

#6668 fix: class method GetPropertyXXX should support rbac
  .gitignore
  pkg/apis/input.go
  pkg/apis/list.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/modelbase.go
Labels: approved, area/util, lgtm, size/M

#6706 fix: 避免越过tenantcache过期检查
  pkg/cloudcommon/db/tenantcache.go
Labels: area/region, size/S

#6707 Automated cherry pick of #6706: fix: 避免越过tenantcache过期检查
  pkg/cloudcommon/db/tenantcache.go
Labels: size/S

#6704 fix: 允许gcp创建vpc时不指定cidr
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/vpcs.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/openstack.go
Labels: area/region, size/S

#6702 fix: gcp默认创建允许所有地址访问的用户
  pkg/multicloud/google/dbinstance.go
Labels: area/region, size/XS

#6703 Automated cherry pick of #6702: fix: gcp默认创建允许所有地址访问的用户
  pkg/multicloud/google/dbinstance.go
Labels: size/XS

#6699 feat: Logo and copyright in verify email are same with these in company info
  build/notify/root/opt/yunion/share/template/content/VERIFY.email
  pkg/notify/models/mod_template.go
  pkg/notify/models/worker.go
Labels: area/notify, size/M

#6700 Automated cherry pick of #6699: feat: Logo and copyright in verify email are same with these in company info
  build/notify/root/opt/yunion/share/template/content/VERIFY.email
  pkg/notify/models/mod_template.go
  pkg/notify/models/worker.go
Labels: size/M

#6708 fix: 转换gcp错误
  pkg/multicloud/google/dbinstance.go
  pkg/multicloud/google/google.go
Labels: area/region, size/S

#6709 Automated cherry pick of #6708: fix: 转换gcp错误
  pkg/multicloud/google/dbinstance.go
  pkg/multicloud/google/google.go
Labels: size/S

#6701 Feature/yousong lb selective redirect
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/kvm.go
  pkg/lbagent/models/haproxy.go
  pkg/mcclient/options/loadbalancerlisteners.go
Labels: area/climc, area/region, size/L

#6364 Feature/yousong eip
  build/docker/Dockerfile.host
  build/docker/Dockerfile.vpcagent
  cmd/climc/shell/compute/elasticips.go
  cmd/climc/shell/compute/networks.go
  cmd/climc/shell/compute/vpcs.go
  go.mod
  go.sum
  pkg/apis/compute/elasticip.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/vpc.go
  pkg/apis/compute/vpcs_ovn.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/eip_allocate_task.go
  pkg/compute/tasks/eip_change_bandwidth_task.go
  pkg/compute/tasks/eip_deallocate_task.go
  pkg/compute/tasks/eip_dissociate_task.go
  pkg/compute/tasks/guest_dissociate_eip_task.go
  pkg/hostman/options/options.go
  pkg/util/iproute2/errors.go
  pkg/util/iproute2/link.go
  pkg/util/iproute2/route.go
  pkg/util/iproute2/route_test.go
  pkg/vpcagent/models/models.go
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/modelsets.go
  pkg/vpcagent/options/options.go
  pkg/vpcagent/ovn/external_access.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/mac/mac.go
  pkg/vpcagent/ovn/names.go
  pkg/vpcagent/ovn/worker.go
  pkg/vpcagent/ovnutil/ovn_nbctl.go
  vendor/modules.txt
  vendor/yunion.io/x/ovsdb/schema/ovn_nb/schema.go
  vendor/yunion.io/x/ovsdb/types/ovn-nb.ovsschema
  vendor/yunion.io/x/ovsdb/types/ovn-sb.ovsschema
  vendor/yunion.io/x/ovsdb/types/schema.go
  vendor/yunion.io/x/ovsdb/types/schema_gen.go
  vendor/yunion.io/x/ovsdb/types/vswitch.ovsschema
Labels: area/region, area/vpcagent, lgtm, size/XXL

#6713 bugfix: isolated device manager:
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
Labels: area/host, size/S

#6714 Automated cherry pick of #6713: isolated device manager:
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
Labels: size/S

#6716 Automated cherry pick of #6713: isolated device manager:
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
Labels: size/S

#6715 Automated cherry pick of #6713: isolated device manager:
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
Labels: size/S

#6696 add-enterprise-info-update-climc
  cmd/climc/shell/misc/copyright.go
Labels: area/region, lgtm, size/M

#6718 Automated cherry pick of #6696: add-enterprise-info-update-climc
  cmd/climc/shell/copyright.go
Labels: size/M

#6719 Automated cherry pick of #6696: add-enterprise-info-update-climc
  cmd/climc/shell/copyright.go
Labels: size/M

#6712 Automated cherry pick of #6711: fix: 移除默认调度策略
  pkg/multicloud/azure/classic_host.go
  pkg/multicloud/azure/classic_network.go
  pkg/multicloud/azure/classic_vpc.go
Labels: size/XS

#6721 Automated cherry pick of #6720: fix: 修复gcp object编码问题
  pkg/multicloud/google/bucket.go
Labels: size/XS

#6726 fix: keystone event list fail to find user
  cmd/climc/shell/events/events.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/usercache.go
  pkg/keystone/service/override.go
  pkg/keystone/service/service.go
Labels: area/keystone, size/M

#6727 Automated cherry pick of #6726: fix: keystone event list fail to find user
  cmd/climc/shell/events.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/usercache.go
  pkg/keystone/service/override.go
  pkg/keystone/service/service.go
Labels: size/M

#6722 fix: 添加region翻译
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/huawei/latitud_and_longitude.go
  pkg/multicloud/qcloud/latitud_and_longitude.go
Labels: area/region, size/S

#6724 Automated cherry pick of #6722: fix: 添加region翻译
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/huawei/latitud_and_longitude.go
  pkg/multicloud/qcloud/latitud_and_longitude.go
Labels: size/S

#6725 Automated cherry pick of #6722: fix: 添加region翻译
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/huawei/latitud_and_longitude.go
  pkg/multicloud/qcloud/latitud_and_longitude.go
Labels: size/S

#6723 Automated cherry pick of #6722: fix: 添加region翻译
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/huawei/latitud_and_longitude.go
  pkg/multicloud/qcloud/latitud_and_longitude.go
Labels: size/S

#6728 fix: 避免openstack session==nil
  pkg/multicloud/openstack/openstack.go
Labels: area/region, size/XS

#6729 Automated cherry pick of #6728: fix: 避免openstack session==nil
  pkg/multicloud/openstack/openstack.go
Labels: size/XS

#6749 Automated cherry pick of #6173: support custom service url
  pkg/mcclient/mcclient.go
  pkg/mcclient/session.go
Labels: size/S

#6744 bugfix: bind mount local image path to container path
  pkg/hostman/host_services.go
Labels: area/host, size/M

#6745 Automated cherry pick of #6744: bind mount local image path to container path
  pkg/hostman/host_services.go
Labels: size/M

#6746 Automated cherry pick of #6744: bind mount local image path to container path
  pkg/hostman/host_services.go
Labels: size/M

#6747 Automated cherry pick of #6744: bind mount local image path to container path
  pkg/hostman/host_services.go
Labels: size/M

#6737 ctyun sync host wire fix
  pkg/multicloud/ctyun/region.go
Labels: area/region, lgtm, size/S

#6736 fix: Support 'generate_name' when saving template from guest
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_template.go
  pkg/compute/tasks/guest_save_template_task.go
Labels: area/region, size/S

#6738 Automated cherry pick of #6737: ctyun sync host wire fix
  pkg/multicloud/ctyun/region.go
Labels: size/S

#6739 Automated cherry pick of #6737: ctyun sync host wire fix
  pkg/multicloud/ctyun/region.go
Labels: size/S

#6740 fix: xsky recode using endpoint as accesskey key
  pkg/multicloud/objectstore/xsky/xsky.go
Labels: area/region, size/XS

#6741 Automated cherry pick of #6740: fix: xsky recode using endpoint as accesskey key
  pkg/multicloud/objectstore/xsky/xsky.go
Labels: size/XS

#6742 Automated cherry pick of #6740: fix: xsky recode using endpoint as accesskey key
  pkg/multicloud/objectstore/xsky/xsky.go
Labels: size/XS

#6730 Feature/yousong lbcluster
  pkg/compute/models/loadbalancers.go
  pkg/mcclient/options/loadbalancerclusters.go
  pkg/mcclient/options/loadbalancers.go
Labels: approved, area/climc, area/region, lgtm, size/M

#6752 climc:allow disable term line width
  go.mod
  go.sum
  pkg/util/printutils/printjson.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/currency.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/pkg/gotypes/gotypes.go
  vendor/yunion.io/x/pkg/prettytable/prettytable.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: approved, area/climc, lgtm, size/XL

#6754 fix: oss-upload fail to set object acl
  pkg/multicloud/aliyun/shell/oss.go
Labels: area/util, size/XS

#6734 cancel condition release
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
Labels: approved, area/region, lgtm, size/M

#6692 fix: 返回object默认acl
  pkg/multicloud/objectstore/object.go
Labels: approved, area/region, lgtm, size/XS

#6694 Automated cherry pick of #6692: fix: 返回object默认acl
  pkg/multicloud/objectstore/object.go
Labels: approved, lgtm, size/XS

#6695 Automated cherry pick of #6692: fix: 返回object默认acl
  pkg/multicloud/objectstore/object.go
Labels: approved, lgtm, size/XS

#6693 Automated cherry pick of #6692: fix: 返回object默认acl
  pkg/multicloud/objectstore/object.go
Labels: approved, lgtm, size/XS

#6757 fix: remove spaces in name
  pkg/cloudcommon/db/standalone.go
Labels: approved, area/keystone, lgtm, size/XS

#6755 Feature/yousong default params
  cmd/climc/shell/compute/loadbalanceragents.go
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/regiondrivers/kvm.go
  pkg/mcclient/options/empty.go
Labels: area/region, lgtm, size/M

#6758 Automated cherry pick of #6757: fix: remove spaces in name
  pkg/cloudcommon/db/standalone.go
Labels: approved, lgtm, size/XS

#6750 fix: base64 decode 12-bytes plain text password return nil
  pkg/apigateway/handler/auth.go
  pkg/util/stringutils2/i18n.go
  pkg/util/stringutils2/i18n_test.go
Labels: area/apigateway, size/M

#6751 Automated cherry pick of #6750: fix: base64 decode 12-bytes plain text password return nil
  pkg/apigateway/handler/auth.go
  pkg/util/stringutils2/i18n.go
  pkg/util/stringutils2/i18n_test.go
Labels: size/M

#6760 bugfix: image support generate name
  pkg/mcclient/modules/mod_images.go
Labels: approved, area/image, lgtm, size/XS

#6763 fix: explainPolicy piggyback owner's privilige
  pkg/cloudcommon/policy/policy.go
Labels: approved, area/apigateway, lgtm, size/M

#6756 fix: handler param.convert's error in caller.go
  pkg/cloudcommon/db/caller.go
Labels: approved, area/util, lgtm, size/S

#6761 Automated cherry pick of #6760: image support generate name
  pkg/mcclient/modules/mod_images.go
Labels: size/XS

#6629 统一监控接口
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/mcclient/modules/mod_unifiedmonitor.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/metricquery/doc.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/suggestsysrule.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/service/handlers.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/query.go
  pkg/monitor/validators/validators.go
Labels: approved, area/monitor, lgtm, size/XL

#6764 vendor: update yunion.io/x/sqlchemy
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/reflect.go
Labels: approved, area/util, lgtm, size/M

#6769 region: retry set influxdb policy until completed
  pkg/compute/service/influxdb.go
Labels: approved, area/region, lgtm, size/M

#6771 Automated cherry pick of #6769: region: retry set influxdb policy until completed
  pkg/compute/service/influxdb.go
Labels: approved, lgtm, size/M

#6770 Automated cherry pick of #6769: region: retry set influxdb policy until completed
  pkg/compute/service/influxdb.go
Labels: approved, lgtm, size/M

#6773 Automated cherry pick of #6772: fix: disable updating zone_id for host, storage, wire
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
  pkg/compute/models/wires.go
Labels: size/XS

#6768 mcclient: options: lb: arg rename cluster{,_id}
  pkg/mcclient/options/loadbalancers.go
Labels: area/climc, size/XS

#6777 cloudcommon: expose ITableSpec function
  pkg/cloudcommon/db/tablespec.go
Labels: area/util, size/S

#6691 Scheduledtasks/init
  cmd/climc/shell/compute/scaling_policy.go
  cmd/climc/shell/compute/scheduled_task.go
  pkg/apis/compute/scaling_group.go
  pkg/apis/compute/scaling_policy.go
  pkg/apis/compute/scaling_trigger.go
  pkg/apis/compute/scheduled_task.go
  pkg/apis/compute/scheduled_task_const.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/models/guests.go
  pkg/compute/models/initdb.go
  pkg/compute/models/scaling_policy.go
  pkg/compute/models/scaling_trigger.go
  pkg/compute/models/scaling_trigger_test.go
  pkg/compute/models/scheduled_tasks.go
  pkg/compute/models/scheduledtask_activity.go
  pkg/compute/models/scheduledtask_label.go
  pkg/compute/models/timer.go
  pkg/compute/options/options.go
  pkg/compute/service/handlers.go
  pkg/compute/service/service.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/controller/autoscaling/controller.go
  pkg/mcclient/modules/mod_scheduledtask.go
Labels: approved, area/region, lgtm, size/XXL

#6791 fix: policy-explain not working properly
  cmd/climc/shell/identity/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/mcclient/auth/auth.go
  pkg/util/rbacutils/rbac.go
Labels: area/climc, size/M

#6792 Automated cherry pick of #6791: fix: policy-explain not working properly
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/mcclient/auth/auth.go
  pkg/util/rbacutils/rbac.go
Labels: size/M

#6794 Automated cherry pick of #6791: fix: policy-explain not working properly
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/mcclient/auth/auth.go
  pkg/util/rbacutils/rbac.go
Labels: size/M

#6782 fix: Add '/version' handler for notify
  pkg/notify/handlers.go
Labels: area/notify, size/XS

#6784 Automated cherry pick of #6782: fix: Add '/version' handler for notify
  pkg/notify/handlers.go
Labels: size/XS

#6785 Automated cherry pick of #6782: fix: Add '/version' handler for notify
  pkg/notify/handlers.go
Labels: size/XS

#6783 Automated cherry pick of #6782: fix: Add '/version' handler for notify
  pkg/notify/handlers.go
Labels: size/XS

#6775 Bugfix/yousong network
  pkg/compute/models/networks.go
Labels: area/region, size/L

#6776 Automated cherry pick of #6775: networks: sep check of masklen only for start,end type creation
  pkg/compute/models/networks.go
Labels: size/L

#6779 fix: 更正华为云操作成功判断
  pkg/multicloud/huawei/traces.go
Labels: area/cloudevent, size/XS

#6780 Automated cherry pick of #6779: fix: 更正华为云操作成功判断
  pkg/multicloud/huawei/traces.go
Labels: size/XS

#6781 Automated cherry pick of #6779: fix: 更正华为云操作成功判断
  pkg/multicloud/huawei/traces.go
Labels: size/XS

#6717 Feature/yousong vpc dns
  pkg/vpcagent/models/models.go
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/modelsets.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/worker.go
Labels: area/vpcagent, size/L

#6663 fix: 优化安全组同步逻辑
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_aws_test.go
  pkg/compute/regiondrivers/secgroup_azure_test.go
  pkg/compute/regiondrivers/secgroup_ctyun_test.go
  pkg/compute/regiondrivers/secgroup_openstack_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/secgroup_base.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: approved, area/region, lgtm, size/XXL

#6766 Automated cherry pick of #6663: fix: 优化安全组同步逻辑
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_aws_test.go
  pkg/compute/regiondrivers/secgroup_azure_test.go
  pkg/compute/regiondrivers/secgroup_ctyun_test.go
  pkg/compute/regiondrivers/secgroup_openstack_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/secgroup_base.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: size/XXL

#6767 Automated cherry pick of #6663: fix: 优化安全组同步逻辑
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_aws_test.go
  pkg/compute/regiondrivers/secgroup_azure_test.go
  pkg/compute/regiondrivers/secgroup_ctyun_test.go
  pkg/compute/regiondrivers/secgroup_openstack_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/secgroup_base.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: size/XXL

#6731 Automated cherry pick of #6663: fix: 优化安全组同步逻辑
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_aws_test.go
  pkg/compute/regiondrivers/secgroup_azure_test.go
  pkg/compute/regiondrivers/secgroup_ctyun_test.go
  pkg/compute/regiondrivers/secgroup_openstack_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/secgroup_base.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: size/XXL

#6786 fix: Hanle the error of vdisk.GetIStorage in syncCloudDisk
  pkg/compute/models/disks.go
Labels: area/region, size/XS

#6787 Automated cherry pick of #6786: fix: Hanle the error of vdisk.GetIStorage in syncCloudDisk
  pkg/compute/models/disks.go
Labels: size/XS

#6788 Automated cherry pick of #6786: fix: Hanle the error of vdisk.GetIStorage in syncCloudDisk
  pkg/compute/models/disks.go
Labels: size/XS

#6789 Automated cherry pick of #6786: fix: Hanle the error of vdisk.GetIStorage in syncCloudDisk
  pkg/compute/models/disks.go
Labels: size/XS

#6790 Automated cherry pick of #6786: fix: Hanle the error of vdisk.GetIStorage in syncCloudDisk
  pkg/compute/models/disks.go
Labels: size/XS

#6732 Automated cherry pick of #6663: fix: 优化安全组同步逻辑
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_aws_test.go
  pkg/compute/regiondrivers/secgroup_azure_test.go
  pkg/compute/regiondrivers/secgroup_ctyun_test.go
  pkg/compute/regiondrivers/secgroup_openstack_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/secgroup.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/classic_vpc.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/securitygroup.go
  pkg/multicloud/ctyun/shell/secgroup.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/huawei/securitygroup.go
  pkg/multicloud/openstack/securitygroup.go
  pkg/multicloud/openstack/shell/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
  pkg/multicloud/secgroup_base.go
  pkg/multicloud/ucloud/region.go
  pkg/multicloud/ucloud/securitygroup.go
  pkg/multicloud/zstack/region.go
  pkg/multicloud/zstack/securitygroup.go
Labels: size/XXL

#6765 Feature/yousong default params
  cmd/climc/shell/compute/loadbalanceragents.go
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/regiondrivers/kvm.go
  pkg/mcclient/options/loadbalanceragents.go
  pkg/mcclient/options/loadbalancers.go
Labels: approved, area/region, lgtm, size/L

#6795 Automated cherry pick of #6791: fix: policy-explain not working properly
  cmd/climc/shell/policies.go
  pkg/cloudcommon/policy/policy.go
  pkg/util/rbacutils/rbac.go
Labels: approved, lgtm, size/M

#6797 fix host list servers filter
  pkg/hostman/guestman/guestman.go
Labels: area/host, size/XS

#6798 Automated cherry pick of #6797: fix host list servers filter
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#6801 Automated cherry pick of #6797: fix host list servers filter
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#6799 Automated cherry pick of #6797: fix host list servers filter
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#6802 fix the tag filter and result record for scheduledtask
  pkg/compute/models/scheduled_tasks.go
Labels: area/region, size/S

#6816 fix informer worker heap large usage
  cmd/climc/shell/misc/pprof.go
  pkg/cloudcommon/informer/worker.go
  pkg/mcclient/mcclient.go
  pkg/mcclient/modules/pprof.go
Labels: approved, area/util, lgtm, size/M

#6803 webconsole: fix version and others handler not handle
  pkg/webconsole/service/service.go
Labels: area/webconsole, lgtm, size/S

#6804 Automated cherry pick of #6803: webconsole: fix version and others handler not handle
  pkg/webconsole/service/service.go
Labels: size/S

#6805 Automated cherry pick of #6803: webconsole: fix version and others handler not handle
  pkg/webconsole/service/service.go
Labels: size/S

#6806 Automated cherry pick of #6803: webconsole: fix version and others handler not handle
  pkg/webconsole/service/service.go
Labels: size/S

#6807 Automated cherry pick of #6803: webconsole: fix version and others handler not handle
  pkg/webconsole/service/service.go
Labels: size/S

#6811 Scheduledtask/fix
  pkg/compute/models/scheduled_tasks.go
  pkg/compute/models/scheduledtask_label.go
Labels: area/region, size/XS

#6810 fix: 避免openstack磁盘和存储窜位
  pkg/multicloud/openstack/disk.go
Labels: area/region, size/S

#6808 fix: 避免sql erorr
  pkg/compute/models/dbinstance_skus.go
Labels: area/region, size/S

#6812 Automated cherry pick of #6810: fix: 避免openstack磁盘和存储窜位
  pkg/multicloud/openstack/disk.go
Labels: size/S

#6813 Automated cherry pick of #6810: fix: 避免openstack磁盘和存储窜位
  pkg/multicloud/openstack/disk.go
Labels: size/S

#6814 Automated cherry pick of #6810: fix: 避免openstack磁盘和存储窜位
  pkg/multicloud/openstack/disk.go
Labels: size/S

#6815 Automated cherry pick of #6810: fix: 避免openstack磁盘和存储窜位
  pkg/multicloud/openstack/disk.go
Labels: size/S

#6809 Automated cherry pick of #6808: fix: 避免sql erorr
  pkg/compute/models/dbinstance_skus.go
Labels: size/S

#6774 apigateway: expose identity/image/k8s usage rpc method
  cmd/climc/shell/compute/usages.go
  pkg/apigateway/handler/init.go
  pkg/mcclient/modules/k8s/base.go
  pkg/mcclient/modules/k8s/usage.go
  pkg/mcclient/modules/mod_usages.go
Labels: area/climc, size/L

#6819 Automated cherry pick of #6817: guestnetworks: use math/rand instead of crypto/rand
  pkg/compute/models/guestnetworks.go
Labels: size/S

#6820 Automated cherry pick of #6817: guestnetworks: use math/rand instead of crypto/rand
  pkg/compute/models/guestnetworks.go
Labels: size/S

#6821 Automated cherry pick of #6817: guestnetworks: use math/rand instead of crypto/rand
  pkg/compute/models/guestnetworks.go
Labels: size/S

#6818 Automated cherry pick of #6817: guestnetworks: use math/rand instead of crypto/rand
  pkg/compute/models/guestnetworks.go
Labels: size/S

#6817 Bugfix/yousong odds
  pkg/compute/models/guestnetworks.go
Labels: approved, area/region, lgtm, size/S

#6830 fix: 优化标签列表version问题
  pkg/mcclient/modules/mod_metadatas.go
  pkg/mcclient/session.go
Labels: area/region, lgtm, size/M

#6831 Automated cherry pick of #6830: fix: 优化标签列表version问题
  pkg/mcclient/modules/mod_metadatas.go
  pkg/mcclient/session.go
Labels: size/M

#6828 lblistener: rename filter name certificate{,_id}
  pkg/apis/compute/loadbalancer.go
  pkg/mcclient/options/loadbalancerlisteners.go
Labels: area/climc, area/region, size/XS

#6829 [3.2] Bugfix/yousong lblistener cert 32
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/mcclient/options/loadbalancerlisteners.go
Labels: area/climc, area/region, size/XS

#6778 feat: Support suggest network config before creating vmware cloud account
  cmd/climc/shell/compute/cloudaccounts.go
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
Labels: approved, area/region, lgtm, size/XL

#6832 vendor: update yunion.io/x/{jsonutils.pkg}
  go.mod
  go.sum
  pkg/cloudcommon/cmdline/helper_test.go
  pkg/multicloud/huawei/client/responses/responses_test.go
  pkg/util/sysutils/sysutils_test.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/string.go
  vendor/yunion.io/x/jsonutils/write.go
  vendor/yunion.io/x/pkg/util/reflectutils/jsonfield.go
  vendor/yunion.io/x/pkg/utils/utils.go
Labels: approved, area/keystone, area/region, lgtm, size/L

#6833 .circleci: run tests faster
  .circleci/config.yml
  pkg/multicloud/loader/proxyfunc_test.go
  scripts/coverage.sh
Labels: approved, area/util, lgtm, size/XS

#6835 scripts/coverage.sh: ignore packages without test files
  pkg/compute/guestdrivers/kvm_test.go
  scripts/coverage.sh
Labels: approved, area/util, lgtm, size/XS

#6822 fix host set reserved resource func name
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: area/region, size/S

#6824 bugfix: fix windows install regedit record
  pkg/hostman/diskutils/fsutils.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/util/procutils/procutils.go
  pkg/util/winutils/winutils.go
Labels: area/host, lgtm, size/M

#6834 CherryPick 2.13: fix windows install regedit record
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/util/winutils/winutils.go
Labels: size/M
