Repository yunionio/cloudpods, pull requests merged in 2021-06, with the labels that each got.

#11268 fix: windows resize file system
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: approved, size/XS

#11276 Automated cherry pick of #11268: fix: windows resize file system
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: approved, size/XS

#11277 Automated cherry pick of #11268: fix: windows resize file system
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: approved, size/XS

#11274 fix(region): disable public cloud ip pre allocate
  pkg/compute/options/options.go
Labels: area/region, size/XS

#11275 Automated cherry pick of #11274: fix(region): disable public cloud ip pre allocate
  pkg/compute/options/options.go
Labels: size/XS

#11279 fix(region): avoid deadlock when resize disk
  pkg/apis/compute/disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
Labels: area/region, size/M

#11281 Automated cherry pick of #11279: fix(region): avoid deadlock when resize disk
  pkg/apis/compute/disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
Labels: size/M

#11282 Automated cherry pick of #11279: fix(region): avoid deadlock when resize disk
  pkg/apis/compute/disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
Labels: size/M

#11284 fix(glance): add option of s3 image status check
  pkg/image/models/storage.go
  pkg/image/options/options.go
Labels: area/image, size/S

#11285 Automated cherry pick of #11284: fix(glance): add option of s3 image status check
  pkg/image/models/storage.go
  pkg/image/options/options.go
Labels: approved, size/S

#11289 fix(host): avoid panic when params is nil
  pkg/hostman/guestman/guestman.go
Labels: area/host, size/S

#11290 Automated cherry pick of #11289: fix(host): avoid panic when params is nil
  pkg/hostman/guestman/guestman.go
Labels: size/S

#11291 Automated cherry pick of #11289: fix(host): avoid panic when params is nil
  pkg/hostman/guestman/guestman.go
Labels: size/S

#11286 fix(region): avoid region service restart
  pkg/multicloud/aliyun/eip.go
Labels: area/region, size/XS

#11287 Automated cherry pick of #11286: fix(region): avoid region service restart
  pkg/multicloud/aliyun/eip.go
Labels: size/XS

#11305 fix: improve README
  README-CN.md
  README.md
Labels: approved, size/L

#11318 fix(region): avoid guest delete not with disks
  pkg/compute/tasks/guest_delete_task.go
Labels: area/region, size/XS

#11319 Automated cherry pick of #11318: fix(region): avoid guest delete not with disks
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#11321 Automated cherry pick of #11318: fix(region): avoid guest delete not with disks
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#11325 README.md: update icon URLs
  README-CN.md
  README.md
Labels: approved, area/docs, lgtm, size/S

#11324 fix: improve readme
  README-CN.md
  README.md
Labels: approved, area/docs, size/M

#11299 fix: hpssacli should skip empty slots
  pkg/baremetal/utils/raid/hpssactl/hpssactl.go
Labels: approved, size/S

#11300 Automated cherry pick of #11299: fix: hpssacli should skip empty slots
  pkg/baremetal/utils/raid/hpssactl/hpssactl.go
Labels: approved, size/S

#11301 Automated cherry pick of #11299: fix: hpssacli should skip empty slots
  pkg/baremetal/utils/raid/hpssactl/hpssactl.go
Labels: size/S

#11302 Automated cherry pick of #11299: fix: hpssacli should skip empty slots
  pkg/baremetal/utils/raid/hpssactl/hpssactl.go
Labels: approved, size/S

#11297 fix(region): lb local cert sync fix
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
Labels: size/M

#11298 Automated cherry pick of #11297: fix(region): lb local cert sync fix
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancercertificates.go
Labels: size/M

#11320 fix: 修复云账号和宿主机报警问题
  pkg/monitor/alerting/conditions/query.go
Labels: area/monitor, size/S

#11322 Automated cherry pick of #11320: fix: 修复云账号和宿主机报警问题
  pkg/monitor/alerting/conditions/query.go
Labels: size/S

#11323 Automated cherry pick of #11320: fix: 修复云账号和宿主机报警问题
  pkg/monitor/alerting/conditions/query.go
Labels: size/S

#11329 fix: README improvement
  CONTRIBUTING.md
  CONTRIBUTING_zh.md
  README-CN.md
  README.md
Labels: approved, size/M

#11330 fix: update README embed image
  README-CN.md
  README.md
Labels: approved, size/S

#11326 fix(region): sync tags with new guest
  pkg/compute/models/guests.go
Labels: area/region, size/XS

#11327 Automated cherry pick of #11326: fix(region): sync tags with new guest
  pkg/compute/models/guests.go
Labels: size/XS

#11331 fix: add reddit contact
  README-CN.md
  README.md
Labels: approved, size/S

#11306 fix(region): skip server migrate quota check
  pkg/scheduler/algorithm/predicates/quota_predicate.go
Labels: area/scheduler, size/XS

#11308 Automated cherry pick of #11306: fix(region): skip server migrate quota check
  pkg/scheduler/algorithm/predicates/quota_predicate.go
Labels: size/XS

#11335 fix(telegraf-raid-plugin): add image-telegraf-raid-plugin in Makefile
  Makefile
Labels: area/host, size/XS

#11336 Automated cherry pick of #11335: fix(telegraf-raid-plugin): add image-telegraf-raid-plugin in Makefile
  Makefile
Labels: size/XS

#11337 Automated cherry pick of #11335: fix(telegraf-raid-plugin): add image-telegraf-raid-plugin in Makefile
  Makefile
Labels: size/XS

#11332 fix(region): validate attached disk size and backend
  pkg/compute/models/guests.go
Labels: area/region, size/XS

#11333 Automated cherry pick of #11332: fix(region): validate attached disk size and backend
  pkg/compute/models/guests.go
Labels: size/XS

#11334 Automated cherry pick of #11332: fix(region): validate attached disk size and backend
  pkg/compute/models/guests.go
Labels: size/XS

#11311 fix(region): huawei disk tags
  pkg/multicloud/huawei/disk.go
  pkg/multicloud/tag_base.go
Labels: approved, area/region, lgtm, size/S

#11312 Automated cherry pick of #11311: fix(region): huawei disk tags
  pkg/multicloud/huawei/disk.go
  pkg/multicloud/tag_base.go
Labels: approved, lgtm, size/S

#11361 fix(region): validate disk status when create snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: area/region, size/M

#11362 Automated cherry pick of #11361: fix(region): validate disk status when create snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/M

#11363 Automated cherry pick of #11361: fix(region): validate disk status when create snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/M

#11364 Automated cherry pick of #11361: fix(region): validate disk status when create snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/M

#11359 fix(region): avoid update storage conf not work
  pkg/compute/storagedrivers/rbd.go
Labels: area/region, size/XS

#11360 Automated cherry pick of #11359: fix(region): avoid update storage conf not work
  pkg/compute/storagedrivers/rbd.go
Labels: size/XS

#11357 fix(region): avoid storage update not work
  pkg/compute/models/storages.go
Labels: area/region, size/XS

#11358 Automated cherry pick of #11357: fix(region): avoid storage update not work
  pkg/compute/models/storages.go
Labels: size/XS

#11354 feat(apigateway): support export dict keys
  pkg/apigateway/handler/resource.go
  pkg/util/excelutils/excelutils.go
Labels: area/apigateway, size/M

#11355 Automated cherry pick of #11354: feat(apigateway): support export dict keys
  pkg/apigateway/handler/resource.go
  pkg/util/excelutils/excelutils.go
Labels: size/M

#11356 Automated cherry pick of #11354: feat(apigateway): support export dict keys
  pkg/apigateway/handler/resource.go
  pkg/util/excelutils/excelutils.go
Labels: size/M

#11349 fix(cloudid): avoid duplicate create saml provider
  pkg/cloudid/models/cloudaccount.go
Labels: area/cloudid, size/XS

#11350 Automated cherry pick of #11349: fix(cloudid): avoid duplicate create saml provider
  pkg/cloudid/models/cloudaccount.go
Labels: size/XS

#11351 Automated cherry pick of #11349: fix(cloudid): avoid duplicate create saml provider
  pkg/cloudid/models/cloudaccount.go
Labels: size/XS

#11352 Automated cherry pick of #11349: fix(cloudid): avoid duplicate create saml provider
  pkg/cloudid/models/cloudaccount.go
Labels: size/XS

#11340 fix(cloudid): huawei group role attach and detach
  pkg/multicloud/huawei/client/modules/mod_groups.go
  pkg/multicloud/huawei/cloudgroup.go
  pkg/multicloud/huawei/shell/cloudgroup.go
Labels: area/cloudid, size/M

#11343 Automated cherry pick of #11340: fix(cloudid): huawei group role attach and detach
  pkg/multicloud/huawei/client/modules/mod_groups.go
  pkg/multicloud/huawei/cloudgroup.go
  pkg/multicloud/huawei/shell/cloudgroup.go
Labels: size/M

#11344 Automated cherry pick of #11340: fix(cloudid): huawei group role attach and detach
  pkg/multicloud/huawei/client/modules/mod_groups.go
  pkg/multicloud/huawei/cloudgroup.go
  pkg/multicloud/huawei/shell/cloudgroup.go
Labels: size/M

#11345 Automated cherry pick of #11340: fix(cloudid): huawei group role attach and detach
  pkg/multicloud/huawei/client/modules/mod_groups.go
  pkg/multicloud/huawei/cloudgroup.go
  pkg/multicloud/huawei/shell/cloudgroup.go
Labels: size/M

#11338 Add some tags to the monitoring data generated by the agent
  build/docker/Dockerfile.ansibleserver
  pkg/ansibleserver/models/ansibleplaybook_instance.go
  pkg/devtool/utils/influxdb_url.go
  pkg/util/ansiblev2/offline_session.go
  pkg/util/ansiblev2/playbook_session.go
Labels: area/devtool, size/M

#11339 Automated cherry pick of #11338: Add some tags to the monitoring data generated by the agent
  build/docker/Dockerfile.ansibleserver
  pkg/ansibleserver/models/ansibleplaybook_instance.go
  pkg/devtool/utils/influxdb_url.go
  pkg/util/ansiblev2/offline_session.go
  pkg/util/ansiblev2/playbook_session.go
Labels: size/M

#11310 fix(region): avoid vmware sync hosts panic
  pkg/compute/models/hosts.go
Labels: area/region, size/XS

#11307 Automated cherry pick of #11306: fix(region): skip server migrate quota check
  pkg/scheduler/algorithm/predicates/quota_predicate.go
Labels: size/XS

#11373 fix: update README 20210610
  README-CN.md
  README.md
Labels: approved, size/M

#11369 fix(host): get ceph used capacity
  pkg/hostman/storageman/storage_rbd.go
Labels: area/host, size/M

#11370 Automated cherry pick of #11369: fix(host): get ceph used capacity
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#11371 Automated cherry pick of #11369: fix(host): get ceph used capacity
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#11347 feat(mcclient): add bills dimension climc
  cmd/climc/shell/meter/bills_dimension.go
  pkg/mcclient/modules/mod_bills_dimension.go
  pkg/mcclient/options/meter/bills_dimension.go
Labels: size/L

#11348 Automated cherry pick of #11347: feat(mcclient): add bills dimension climc
  cmd/climc/shell/meter/bills_dimension.go
  pkg/mcclient/modules/mod_bills_dimension.go
  pkg/mcclient/options/meter/bills_dimension.go
Labels: size/L

#11383 feat(github): add document issue template
  .github/ISSUE_TEMPLATE/document_request.md
Labels: approved, size/S

#11374 fix: update README 20210610
  README-CN.md
  README.md
Labels: approved, size/M

#11367 fix(region): support cloudprovider bind project mapping
  cmd/climc/shell/compute/cloudproviders.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/project_mappings.go
  pkg/compute/policy/resources.go
  pkg/mcclient/options/compute/cloudproviders.go
Labels: area/region, size/XL

#11368 Automated cherry pick of #11367: fix(region): support cloudprovider bind project mapping
  cmd/climc/shell/compute/cloudproviders.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/project_mappings.go
  pkg/compute/policy/resources.go
  pkg/mcclient/options/compute/cloudproviders.go
Labels: size/XL

#11375 fix(host): update rbd storage capacity
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_rbd.go
Labels: area/region, size/S

#11377 Automated cherry pick of #11375: fix(host): update rbd storage capacity
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/S

#11378 Automated cherry pick of #11375: fix(host): update rbd storage capacity
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/S

#11376 fix(region): qcloud bandwidth pkg
  pkg/multicloud/qcloud/instance.go
Labels: area/region, size/S

#11380 fix(notify): clean verifiedNote when marking verified
  pkg/notify/models/receiver.go
Labels: area/notify, size/XS

#11381 Automated cherry pick of #11380: fix(notify): clean verifiedNote when marking verified
  pkg/notify/models/receiver.go
Labels: size/XS

#11382 Automated cherry pick of #11380: fix(notify): clean verifiedNote when marking verified
  pkg/notify/models/receiver.go
Labels: size/XS

#11396 fix: change site URL to www.cloudpods.org
  .github/pull_request_template.md
  CONTRIBUTING.md
  CONTRIBUTING_zh.md
  README-CN.md
  README.md
Labels: approved, size/M

#11395 Automated cherry pick of #11376: fix(region): qcloud bandwidth pkg
  pkg/multicloud/qcloud/instance.go
Labels: lgtm

#11394 Automated cherry pick of #11376: fix(region): qcloud bandwidth pkg
  pkg/multicloud/qcloud/instance.go
Labels: lgtm

#11393 Automated cherry pick of #11376: fix(region): qcloud bandwidth pkg
  pkg/multicloud/qcloud/instance.go
Labels: lgtm

#11397 fix(region): add status resource statistic
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/helper.go
  pkg/apis/output.go
  pkg/cloudcommon/db/statusstandalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/mcclient/options/base.go
Labels: area/region, size/L

#11398 Automated cherry pick of #11397: fix(region): add status resource statistic
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/helper.go
  pkg/apis/output.go
  pkg/cloudcommon/db/statusstandalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/mcclient/options/base.go
Labels: size/L

#11269 Automated cherry pick of #10849: Feature/yousong zombie
  cmd/ansibleserver/main.go
  cmd/baremetal-agent/main.go
  cmd/esxi-agent/main.go
  cmd/glance/main.go
  cmd/host-deployer/main.go
  cmd/host/main.go
  cmd/vpcagent/main.go
  pkg/ansibleserver/service/service.go
  pkg/util/procutils/zombie.go
Labels: approved, size/M

#11270 Automated cherry pick of #10849: Feature/yousong zombie
  cmd/ansibleserver/main.go
  cmd/baremetal-agent/main.go
  cmd/esxi-agent/main.go
  cmd/glance/main.go
  cmd/host-deployer/main.go
  cmd/host/main.go
  cmd/vpcagent/main.go
  pkg/ansibleserver/service/service.go
  pkg/util/procutils/zombie.go
Labels: approved, size/M

#11271 Automated cherry pick of #10849: Feature/yousong zombie
  cmd/ansibleserver/main.go
  cmd/baremetal-agent/main.go
  cmd/esxi-agent/main.go
  cmd/glance/main.go
  cmd/host-deployer/main.go
  cmd/host/main.go
  cmd/vpcagent/main.go
  pkg/ansibleserver/service/service.go
  pkg/util/procutils/zombie.go
Labels: approved, size/M

#11406 webconsole: wait zombies
  cmd/webconsole/main.go
Labels: approved, area/webconsole, size/XS

#11407 Automated cherry pick of #11406: webconsole: wait zombies
  cmd/webconsole/main.go
Labels: approved, size/XS

#11408 Automated cherry pick of #11406: webconsole: wait zombies
  cmd/webconsole/main.go
Labels: approved, size/XS

#11409 Automated cherry pick of #11406: webconsole: wait zombies
  cmd/webconsole/main.go
Labels: approved, size/XS

#11410 Automated cherry pick of #11406: webconsole: wait zombies
  cmd/webconsole/main.go
Labels: approved, size/XS

#11404 fix(region): ignore qcloud bw pkg error
  pkg/multicloud/qcloud/instance.go
Labels: area/region, size/XS

#11405 Automated cherry pick of #11404: fix(region): ignore qcloud bw pkg error
  pkg/multicloud/qcloud/instance.go
Labels: size/XS

#11411 Automated cherry pick of #11404: fix(region): ignore qcloud bw pkg error
  pkg/multicloud/qcloud/instance.go
Labels: size/XS

#11412 Automated cherry pick of #11404: fix(region): ignore qcloud bw pkg error
  pkg/multicloud/qcloud/instance.go
Labels: size/XS

#11205 feat(baremetal): support management of none BMC host
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
  pkg/baremetal/cronjobs.go
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/nic.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/stop.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/baremetal/types/types.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/uefi/doc.go
  pkg/baremetal/utils/uefi/uefi.go
  pkg/baremetal/utils/uefi/uefi_test.go
  pkg/cloudcommon/types/types.go
  pkg/cloudcommon/types/uefi.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/baremetal_maintenance_task.go
  pkg/compute/tasks/baremetal_server_sync_status_task.go
  pkg/compute/tasks/baremetal_sync_config_task.go
  pkg/compute/tasks/baremetal_sync_status_task.go
  pkg/compute/tasks/baremetal_unmaintenance_task.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/XXL

#11341 Automated cherry pick of #11205: feat(baremetal): support management of none BMC host
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
  pkg/baremetal/cronjobs.go
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/nic.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/stop.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/baremetal/types/types.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/uefi/doc.go
  pkg/baremetal/utils/uefi/uefi.go
  pkg/baremetal/utils/uefi/uefi_test.go
  pkg/cloudcommon/types/types.go
  pkg/cloudcommon/types/uefi.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/baremetal_maintenance_task.go
  pkg/compute/tasks/baremetal_server_sync_status_task.go
  pkg/compute/tasks/baremetal_sync_config_task.go
  pkg/compute/tasks/baremetal_sync_status_task.go
  pkg/compute/tasks/baremetal_unmaintenance_task.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/XXL

#11223 Automated cherry pick of #11205: feat(baremetal): support management of none BMC host
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
  pkg/baremetal/cronjobs.go
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/nic.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/base.go
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/interface.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
  pkg/baremetal/tasks/start.go
  pkg/baremetal/tasks/stop.go
  pkg/baremetal/tasks/unmaintenance.go
  pkg/baremetal/types/types.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/uefi/doc.go
  pkg/baremetal/utils/uefi/uefi.go
  pkg/baremetal/utils/uefi/uefi_test.go
  pkg/cloudcommon/types/types.go
  pkg/cloudcommon/types/uefi.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/baremetal_maintenance_task.go
  pkg/compute/tasks/baremetal_server_sync_status_task.go
  pkg/compute/tasks/baremetal_sync_config_task.go
  pkg/compute/tasks/baremetal_sync_status_task.go
  pkg/compute/tasks/baremetal_unmaintenance_task.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/mcclient/modules/mod_sshkeypairs.go
  pkg/util/ssh/ssh.go
Labels: approved, lgtm, size/XXL

#11415 fix: do not resize LVM paritition and skip and return success
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
Labels: approved, size/XS

#11416 Automated cherry pick of #11415: fix: do not resize LVM paritition and skip and return success
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
Labels: approved, size/XS

#11417 Automated cherry pick of #11415: fix: do not resize LVM paritition and skip and return success
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
Labels: approved, size/XS

#11413 fix: support windows 2003
  cmd/climc/shell/compute/servers.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: approved, size/M

#11414 Automated cherry pick of #11413: fix: support windows 2003
  cmd/climc/shell/compute/servers.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: approved, size/M

#11418 Automated cherry pick of #11413: fix: support windows 2003
  cmd/climc/shell/compute/servers.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: approved, size/M

#11402 fix(region): show project mapping managers info
  pkg/apis/compute/project_mappings.go
  pkg/compute/models/project_mappings.go
Labels: area/region, size/S

#11403 Automated cherry pick of #11402: fix(region): show project mapping managers info
  pkg/apis/compute/project_mappings.go
  pkg/compute/models/project_mappings.go
Labels: size/S

#11425 add meter billing exchange rate module
  pkg/mcclient/modules/mod_billing_exchange_rates.go
  pkg/mcclient/options/meter/billing_exchange_rates.go
Labels: approved, lgtm, size/M

#11426 Automated cherry pick of #11425: add meter billing exchange rate module
  pkg/mcclient/modules/mod_billing_exchange_rates.go
  pkg/mcclient/options/meter/billing_exchange_rates.go
Labels: approved, lgtm, size/M

#11430 fix(region): clean schedule cache when host add or delete netif
  pkg/baremetal/manager.go
  pkg/compute/models/hosts.go
Labels: approved, size/XS

#11431 Automated cherry pick of #11430: fix(region): clean schedule cache when host add or delete netif
  pkg/baremetal/manager.go
  pkg/compute/models/hosts.go
Labels: approved, size/XS

#11432 Automated cherry pick of #11430: fix(region): clean schedule cache when host add or delete netif
  pkg/baremetal/manager.go
  pkg/compute/models/hosts.go
Labels: approved, size/XS

#11436 fix(region): manager distinct field
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/XS

#11419 fix(region): add project filter for cloudprovider
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/XS

#11437 Automated cherry pick of #11436: fix(region): manager distinct field
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#11438 Automated cherry pick of #11436: fix(region): manager distinct field
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#11420 Automated cherry pick of #11419: fix(region): add project filter for cloudprovider
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#11421 Automated cherry pick of #11419: fix(region): add project filter for cloudprovider
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#11441 fix(region): skip disabled project mapping
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/XS

#11442 Automated cherry pick of #11441: fix(region): skip disabled project mapping
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#11422 feat(region): add app gateway resource
  cmd/climc/shell/compute/app_gateways.go
  pkg/apis/compute/app_gateways.go
  pkg/cloudprovider/app_gateways.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/app_gateways.go
  pkg/compute/models/cloudsync.go
  pkg/compute/policy/resources.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/app_gateway_syncstatus_task.go
  pkg/mcclient/modules/mod_app_gateways.go
  pkg/mcclient/options/compute/app_gateways.go
  pkg/multicloud/azure/app_gateways.go
  pkg/multicloud/azure/shell/app_gateways.go
  pkg/multicloud/region_base.go
Labels: area/region, size/XXL

#11447 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: approved, size/L

#11446 fix: update README to add user list and bilibili URL
  README-CN.md
  README.md
Labels: approved, size/S

#11434 Automated cherry pick of #11433: fix(region,scheduler): baremetal reuse ip
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/scheduler/cache/candidate/baremetals.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/test/mock/core.go
Labels: approved, lgtm, size/M

#11435 Automated cherry pick of #11433: fix(region,scheduler): baremetal reuse ip
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/scheduler/cache/candidate/baremetals.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/test/mock/core.go
Labels: approved, lgtm, size/M

#11433 fix(region,scheduler): baremetal reuse ip
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/scheduler/cache/candidate/baremetals.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/test/mock/core.go
Labels: approved, lgtm, size/M

#11428 feat(monitor) 3.7 add monitor resource overview
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/apis/monitor/monitor_resource.go
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/mcclient/modules/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_sync.go
  pkg/monitor/options/options.go
  pkg/monitor/service/handlers.go
  pkg/monitor/service/service.go
  pkg/monitor/tasks/detach_monitor_resource_task.go
  pkg/monitor/tasks/update_monitor_resource_task.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: area/monitor, size/XXL

#11444 Automated cherry pick of #11428: feat(monitor) 3.7 add monitor resource overview
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/apis/monitor/monitor_resource.go
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/mcclient/modules/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_sync.go
  pkg/monitor/options/options.go
  pkg/monitor/service/handlers.go
  pkg/monitor/service/service.go
  pkg/monitor/tasks/detach_monitor_resource_task.go
  pkg/monitor/tasks/update_monitor_resource_task.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/XXL

#11439 feat(notify): filter all recipients in this domain and recipients who have joined projects in this domain
  pkg/notify/models/receiver.go
Labels: area/notify, size/M

#11440 Automated cherry pick of #11439: feat(notify): filter all recipients in this domain and recipients who have joined projects in this domain
  pkg/notify/models/receiver.go
Labels: size/M

#11448 fix(baremetal): remove bundle libs build
  build/docker/Dockerfile.baremetal-agent
  scripts/docker_push.sh
Labels: approved, size/M

#11449 Automated cherry pick of #11448: fix(baremetal): remove bundle libs build
  build/docker/Dockerfile.baremetal-agent
  scripts/docker_push.sh
Labels: approved, size/M

#11450 Automated cherry pick of #11448: fix(baremetal): remove bundle libs build
  build/docker/Dockerfile.baremetal-agent
  scripts/docker_push.sh
Labels: approved, size/M

#11454 fix(monitor): exit monitor engine in time when happen err
  pkg/monitor/alerting/engine.go
Labels: area/monitor, size/XS

#11455 Automated cherry pick of #11454: fix(monitor): exit monitor engine in time when happen err
  pkg/monitor/alerting/engine.go
Labels: size/XS

#11456 Automated cherry pick of #11454: fix(monitor): exit monitor engine in time when happen err
  pkg/monitor/alerting/engine.go
Labels: size/XS

#11458 fix(region): add azure sql server
  pkg/apis/compute/dbinstance_const.go
  pkg/compute/models/dbinstances.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/dbinstance.go
  pkg/multicloud/azure/dbinstance_database.go
  pkg/multicloud/azure/rds_managed_sqlserver.go
  pkg/multicloud/azure/rds_managed_sqlserver_account.go
  pkg/multicloud/azure/rds_managed_sqlserver_database.go
  pkg/multicloud/azure/rds_sqlserver.go
  pkg/multicloud/azure/rds_sqlserver_account.go
  pkg/multicloud/azure/rds_sqlserver_backup.go
  pkg/multicloud/azure/rds_sqlserver_database.go
  pkg/multicloud/azure/shell/dbinstance.go
Labels: size/XL

#11461 fix(monitor): fix monitor overview
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_sync.go
Labels: area/monitor, size/M

#11462 Automated cherry pick of #11461: fix(monitor): fix monitor overview
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_sync.go
Labels: size/M

#11463 fix(hostman): show server status changed reason
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostutils/hostutils.go
Labels: area/host, size/M

#11464 Automated cherry pick of #11463: fix(hostman): show server status changed reason
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostutils/hostutils.go
Labels: size/M

#11465 Automated cherry pick of #11463: fix(hostman): show server status changed reason
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostutils/hostutils.go
Labels: size/M

#11466 Automated cherry pick of #11463: fix(hostman): show server status changed reason
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostutils/hostutils.go
Labels: size/M
