Repository yunionio/cloudpods, pull requests merged in 2021-11, with the labels that each got.

#12568 fix: clean up region data
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/aliyun/latitud_and_longitude.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/azure/geographicinfo.go
  pkg/multicloud/google/latitude_and_longitude.go
  pkg/multicloud/huawei/latitud_and_longitude.go
  pkg/multicloud/qcloud/latitud_and_longitude.go
Labels: lgtm, approved, area/region, size/XL

#12564 fix(region): init timerQueue correctly
  pkg/compute/models/scheduled_tasks.go
Labels: size/XS, area/region

#12566 Automated cherry pick of #12564: fix(region): init timerQueue correctly
  pkg/compute/models/scheduled_tasks.go
Labels: size/XS

#12565 Automated cherry pick of #12564: fix(region): init timerQueue correctly
  pkg/compute/models/scheduled_tasks.go
Labels: size/XS

#12559 fixes for notify
  pkg/notify/models/notification.go
  pkg/notify/models/robot.go
  pkg/notify/models/topic.go
Labels: size/M, area/notify

#12560 Automated cherry pick of #12559: fixes for notify
  pkg/notify/models/notification.go
  pkg/notify/models/robot.go
  pkg/notify/models/topic.go
Labels: size/M

#12574 Flag for installing agent
  cmd/climc/shell/cloudproxy/proxy_agents.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_sshable.go
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/models/guest_sshable.go
  pkg/mcclient/options/cloudproxy/proxy_agents.go
  pkg/mcclient/options/servers.go
Labels: size/M

#12575 Automated cherry pick of #12574: Flag for installing agent
  cmd/climc/shell/cloudproxy/proxy_agents.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_sshable.go
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/models/guest_sshable.go
  pkg/mcclient/options/cloudproxy/proxy_agents.go
  pkg/mcclient/options/servers.go
Labels: size/M

#12576 Automated cherry pick of #12574: Flag for installing agent
  cmd/climc/shell/cloudproxy/proxy_agents.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_sshable.go
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/models/guest_sshable.go
  pkg/mcclient/options/cloudproxy/proxy_agents.go
  pkg/mcclient/options/servers.go
Labels: size/M

#12571 fix(region): avoid panic when query is nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS, area/region

#12572 Automated cherry pick of #12571: fix(region): avoid panic when query is nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS

#12573 Automated cherry pick of #12571: fix(region): avoid panic when query is nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS

#12569 Automated cherry pick of #12568: fix: clean up region data
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/aliyun/latitud_and_longitude.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/azure/geographicinfo.go
  pkg/multicloud/google/latitude_and_longitude.go
  pkg/multicloud/huawei/latitud_and_longitude.go
  pkg/multicloud/qcloud/latitud_and_longitude.go
Labels: approved, size/XL

#12583 fix(notify): init ProjectId for robots without ProjectId
  pkg/notify/models/robot.go
Labels: size/S, area/notify

#12584 Automated cherry pick of #12583: fix(notify): init ProjectId for robots without ProjectId
  pkg/notify/models/robot.go
Labels: size/S

#12581 fix(region): cdn purge
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/purge.go
Labels: size/S, area/region

#12582 Automated cherry pick of #12581: fix(region): cdn purge
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/purge.go
Labels: size/S

#12577 fix(region): delete instance snapshot itself after deleting subsnapshots
  pkg/compute/tasks/instance_snapshot_delete_task.go
Labels: size/XS, area/region

#12578 Automated cherry pick of #12577: fix(region): delete instance snapshot itself after deleting subsnapshots
  pkg/compute/tasks/instance_snapshot_delete_task.go
Labels: size/XS

#12561 fix: delayed probing GPU on host init and add disable_gpu option
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/options/options.go
Labels: approved, size/M, area/host

#12563 Automated cherry pick of #12561: fix: delayed probing GPU on host init and add disable_gpu option
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/options/options.go
Labels: approved, size/M

#12567 Automated cherry pick of #12561: fix: delayed probing GPU on host init and add disable_gpu option
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/options/options.go
Labels: approved, size/M

#12586 fix: disable MFA by default
  pkg/apigateway/options/options.go
Labels: approved, size/XS

#12588 Automated cherry pick of #12585: feat(region,host): implement server change disk storage
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/disk_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/apis/host/types.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/mcclient/options/servers.go
  pkg/util/cephutils/ceph.go
  pkg/util/logclient/consts.go
Labels: size/XL

#12585 feat(region,host): implement server change disk storage
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/disk_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/apis/host/types.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/mcclient/options/servers.go
  pkg/util/cephutils/ceph.go
  pkg/util/logclient/consts.go
Labels: approved, area/region, area/host, size/XL

#12590 fix(esxi): avoid uplink dvpg
  pkg/multicloud/esxi/vswitch.go
Labels: size/XS, area/esxiagent

#12591 Automated cherry pick of #12590: fix(esxi): avoid uplink dvpg
  pkg/multicloud/esxi/vswitch.go
Labels: size/XS

#12592 Automated cherry pick of #12590: fix(esxi): avoid uplink dvpg
  pkg/multicloud/esxi/vswitch.go
Labels: size/XS

#12593 fix(region): avoid syncing when starting or stoping esxi vm
  pkg/compute/guestdrivers/esxi.go
Labels: size/M, area/region

#12594 Automated cherry pick of #12593: fix(region): avoid syncing when starting or stoping esxi vm
  pkg/compute/guestdrivers/esxi.go
Labels: size/M

#12598 fix(notify): init system tenant_id for robot without tenant_id
  pkg/notify/models/robot.go
Labels: size/M, area/notify

#12599 Automated cherry pick of #12598: fix(notify): init system tenant_id for robot without tenant_id
  pkg/notify/models/robot.go
Labels: size/M

#12595 fix(monitor): monitor alert support:{level} filter
  pkg/apis/monitor/alert_record_shield.go
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/recordshield.go
Labels: size/M, area/monitor

#12596 Automated cherry pick of #12595: fix(monitor): monitor alert support:{level} filter
  pkg/apis/monitor/alert_record_shield.go
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/recordshield.go
Labels: size/M

#12606 Automated cherry pick of #12605: feat(region,host): create or update server add machine option
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/mcclient/options/servers.go
Labels: size/M

#12607 Automated cherry pick of #12605: feat(region,host): create or update server add machine option
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_const.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/mcclient/options/servers.go
Labels: size/M

#12603 fix(webconsole): support vnc for openstack
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/shell/virtualmachine.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/jdcloud/instance.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/shell/instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/instance.go
  pkg/webconsole/handlers.go
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
Labels: size/L, area/webconsole

#12601 Automated cherry pick of #12600: support gcp regional lb sync
  pkg/apis/compute/loadbalancer_const.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/loadbalancer.go
  pkg/multicloud/google/loadbalancer_backend.go
  pkg/multicloud/google/loadbalancer_backendgroup.go
  pkg/multicloud/google/loadbalancer_cert.go
  pkg/multicloud/google/loadbalancer_components.go
  pkg/multicloud/google/loadbalancer_listener.go
  pkg/multicloud/google/loadbalancer_listenerrule.go
  pkg/multicloud/google/region.go
  pkg/multicloud/google/shell/loadbalancer.go
Labels: size/XXL

#12609 fix(region): avoid cidr change 0.0.0.0/0
  pkg/compute/models/secgrouprules.go
Labels: size/XS, area/region

#12610 Automated cherry pick of #12609: fix(region): avoid cidr change 0.0.0.0/0
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#12611 Automated cherry pick of #12609: fix(region): avoid cidr change 0.0.0.0/0
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#12612 Automated cherry pick of #12609: fix(region): avoid cidr change 0.0.0.0/0
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#12613 fix(monitor): monitor host query fix
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S, area/monitor

#12614 Automated cherry pick of #12613: fix(monitor): monitor host query fix
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S

#12324 guest start sync with cloud vm
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS, area/region

#12558 fix(region): cloud account sync optimized
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/subaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/L, area/region

#12570 fix(region): enable sync account by resource
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/L, area/region

#12620 fix: cleanup compile warnings
  cmd/climc/shell/compute/server_forward.go
  pkg/cloudcommon/options/changes.go
  pkg/devtool/utils/service_url.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/storagehelper.go
  pkg/monitor/suggestsysdrivers/doc.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/hcso/bucket.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/hcso/loadbalancer_backend.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/openstack/storage.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/vpcagent/models/modelset.go
Labels: size/L

#12621 Automated cherry pick of #12620: fix: cleanup compile warnings
  cmd/climc/shell/compute/server_forward.go
  pkg/cloudcommon/options/changes.go
  pkg/devtool/utils/service_url.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/storagehelper.go
  pkg/monitor/suggestsysdrivers/doc.go
  pkg/monitor/suggestsysdrivers/influxdbbasedriver.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/hcso/bucket.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/hcso/loadbalancer_backend.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/openstack/storage.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/vpcagent/models/modelset.go
Labels: size/L

#12622 Automated cherry pick of #12620: fix: cleanup compile warnings
  cmd/climc/shell/compute/server_forward.go
  cmd/cloudmon/main.go
  pkg/cloudcommon/options/changes.go
  pkg/devtool/utils/service_url.go
  pkg/hostman/host_services.go
  pkg/hostman/storageman/storagehelper.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/hcso/bucket.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/hcso/loadbalancer_backend.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/openstack/storage.go
Labels: size/S

#12580 fix(region): support progress for resource status
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/storagecache.go
  pkg/apis/update.go
  pkg/cloudcommon/db/statusbase.go
  pkg/cloudcommon/db/statusstandalone.go
  pkg/cloudprovider/resources.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/hostdrivers/baremetal.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/disk_create_task.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/ha_disk_create_task.go
  pkg/compute/tasks/storage_cache_image_task.go
  pkg/hostman/downloader/downloader.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_base.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/imagecachemanager_base.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/imagecachemanager_rbd.go
  pkg/hostman/storageman/remotefile/remotefile.go
  pkg/hostman/storageman/storage_local.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/aliyun/storagecache.go
  pkg/multicloud/aliyun/task.go
  pkg/multicloud/apsara/storagecache.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/azure/shell/storageaccount.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/azure/storagecache.go
  pkg/multicloud/azure/upload.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/storagecache.go
  pkg/multicloud/ctyun/storagecache.go
  pkg/multicloud/ecloud/storagecache.go
  pkg/multicloud/esxi/storagecache.go
  pkg/multicloud/google/storagecache.go
  pkg/multicloud/hcso/storagecache.go
  pkg/multicloud/huawei/storagecache.go
  pkg/multicloud/jdcloud/storagecache.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/openstack/region.go
  pkg/multicloud/openstack/shell/image.go
  pkg/multicloud/openstack/storagecache.go
  pkg/multicloud/progress.go
  pkg/multicloud/qcloud/storagecache.go
  pkg/multicloud/ucloud/storagecache.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/shell/image.go
  pkg/multicloud/zstack/storagecache.go
Labels: size/XXL, area/region, area/host

#12623 fix: provide manager/account info for storagecachedimage
  pkg/apis/compute/storagecache.go
  pkg/apis/compute/storagecachedimage.go
  pkg/cloudmon/collectors/ecloudmon/ecloudreport.go
  pkg/compute/hostdrivers/esxi.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecacheresource.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/mcclient/example/server.go
  pkg/multicloud/cloudpods/storagecache.go
Labels: size/L

#12639 fix(region): sync aliyun k8s by region
  pkg/multicloud/aliyun/kube_cluster.go
Labels: size/XS, area/region

#12636 qcloud&aliyun update backend weight value range fix
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/qcloud.go
Labels: size/XS

#12637 Automated cherry pick of #12636: qcloud&aliyun update backend weight value range fix
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/qcloud.go
Labels: size/XS

#12638 Automated cherry pick of #12636: qcloud&aliyun update backend weight value range fix
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/qcloud.go
Labels: size/XS

#12633 fix(region): aws redis not found error
  pkg/multicloud/aws/elasticache_instance.go
Labels: size/XS, area/region

#12634 Automated cherry pick of #12633: fix(region): aws redis not found error
  pkg/multicloud/aws/elasticache_instance.go
Labels: size/XS

#12631 fix(region): sync cloudpods metadata
  pkg/apis/cloudcommon/db/metadata.go
  pkg/apis/const.go
  pkg/multicloud/tag_base.go
Labels: size/S, area/region

#12632 Automated cherry pick of #12631: fix(region): sync cloudpods metadata
  pkg/apis/cloudcommon/db/metadata.go
  pkg/apis/const.go
  pkg/multicloud/tag_base.go
Labels: size/S

#12627 fix: optimize vm disk io parameters
  pkg/compute/models/guestdisks.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S, area/host

#12628 Automated cherry pick of #12627: fix: optimize vm disk io parameters
  pkg/compute/models/guestdisks.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#12644 fix(climc): climc json output
  cmd/climc/shell/compute/common.go
  cmd/climc/shell/utils.go
Labels: size/S, area/climc

#12645 Automated cherry pick of #12644: fix(climc): climc json output
  cmd/climc/shell/compute/common.go
  cmd/climc/shell/utils.go
Labels: size/S

#12642 fix(host): nfs clone disk from storage not implement
  pkg/hostman/storageman/storage_nas.go
Labels: size/XS, area/host

#12643 Automated cherry pick of #12642: fix(host): nfs clone disk from storage not implement
  pkg/hostman/storageman/storage_nas.go
Labels: size/XS

#12647 fix(webconsole): host ssh use cloudroot user error
  pkg/webconsole/command/ssh_command.go
Labels: lgtm, size/M, area/webconsole

#12648 Automated cherry pick of #12647: fix(webconsole): host ssh use cloudroot user error
  pkg/webconsole/command/ssh_command.go
Labels: lgtm, size/M

#12649 Automated cherry pick of #12647: fix(webconsole): host ssh use cloudroot user error
  pkg/webconsole/command/ssh_command.go
Labels: lgtm, size/M

#12652 Automated cherry pick of #12651: fix(climc): json output
  cmd/climc/shell/helper.go
  cmd/climc/shell/utils.go
Labels: lgtm, size/M

#12641 fix: false delted field for deleted resources
  pkg/cloudcommon/db/resourcebase.go
  pkg/mcclient/options/base.go
Labels: lgtm, size/XS

#12653 Automated cherry pick of #12641: fix: false delted field for deleted resources
  pkg/cloudcommon/db/resourcebase.go
  pkg/mcclient/options/base.go
Labels: size/XS

#12654 Automated cherry pick of #12641: fix: false delted field for deleted resources
  pkg/cloudcommon/db/resourcebase.go
  pkg/mcclient/options/base.go
Labels: size/XS

#12655 Automated cherry pick of #12641: fix: false delted field for deleted resources
  pkg/cloudcommon/db/resourcebase.go
  pkg/mcclient/options/base.go
Labels: size/XS

#12597 feature: pass ntp server by DHCP option
  cmd/rbdcli/main.go
  cmd/rbdcli/shell/cluster.go
  cmd/rbdcli/shell/pool.go
  cmd/rbdcli/shell/printutils.go
  go.mod
  go.sum
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/network.go
  pkg/apis/compute/network_const.go
  pkg/apis/compute/vpcs_ovn.go
  pkg/baremetal/nic.go
  pkg/cloudcommon/db/caller.go
  pkg/cloudcommon/db/caller_test.go
  pkg/cloudcommon/options/options.go
  pkg/cloudcommon/types/nic.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/netinterfaces.go
  pkg/compute/models/networks.go
  pkg/compute/options/options.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/auth/auth.go
  pkg/mcclient/options/network.go
  pkg/util/dhcp/helpers.go
  pkg/util/rbdutils/doc.go
  pkg/util/rbdutils/rbd.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/worker.go
  vendor/github.com/ceph/go-ceph/LICENSE
  vendor/github.com/ceph/go-ceph/rados/conn.go
  vendor/github.com/ceph/go-ceph/rados/doc.go
  vendor/github.com/ceph/go-ceph/rados/ioctx.go
  vendor/github.com/ceph/go-ceph/rados/rados.go
  vendor/github.com/ceph/go-ceph/rbd/doc.go
  vendor/github.com/ceph/go-ceph/rbd/rbd.go
  vendor/github.com/gofrs/uuid/.travis.yml
  vendor/github.com/gofrs/uuid/README.md
  vendor/github.com/gofrs/uuid/codec.go
  vendor/github.com/gofrs/uuid/generator.go
  vendor/github.com/gofrs/uuid/uuid.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/marshal.go
Labels: size/XXL, area/host, area/vpcagent

#12658 fix(region): google secgroup sync
  pkg/compute/models/cloudsync.go
Labels: size/XS, area/region

#12659 Automated cherry pick of #12658: fix(region): google secgroup sync
  pkg/compute/models/cloudsync.go
Labels: size/XS

#12656 fix: allocate eip from network that belong sto the same project
  pkg/compute/regiondrivers/kvm.go
Labels: size/M, area/region

#12657 Automated cherry pick of #12656: fix: allocate eip from network that belong sto the same project
  pkg/compute/regiondrivers/kvm.go
Labels: size/M

#12616 Bugfix/tb bugfix 110501
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/multicloud/google/loadbalancer.go
  pkg/multicloud/google/loadbalancer_components.go
  pkg/multicloud/google/loadbalancer_listener.go
Labels: size/M, area/region

#12617 Automated cherry pick of #12616: Bugfix/tb bugfix 110501
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/multicloud/google/loadbalancer.go
  pkg/multicloud/google/loadbalancer_components.go
  pkg/multicloud/google/loadbalancer_listener.go
Labels: size/M

#12629 fix(region): add api field for vpc-peering
  pkg/apis/compute/inter_vpc_network.go
  pkg/apis/compute/vpc_peering_connection.go
  pkg/apis/compute/vpcs_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/inter_vpc_network.go
  pkg/compute/models/purge.go
  pkg/compute/models/vpc_peering_connections.go
  pkg/compute/models/vpcs.go
  pkg/mcclient/options/vpc.go
Labels: size/L, area/region

#12630 Automated cherry pick of #12629: fix(region): add api field for vpc-peering
  pkg/apis/compute/inter_vpc_network.go
  pkg/apis/compute/vpc_peering_connection.go
  pkg/apis/compute/vpcs_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/inter_vpc_network.go
  pkg/compute/models/purge.go
  pkg/compute/models/vpc_peering_connections.go
  pkg/compute/models/vpcs.go
  pkg/mcclient/options/vpc.go
Labels: size/L

#12666 fix: fail to free reserved ip in non-owner project
  pkg/mcclient/modules/compute/mod_reservedips.go
Labels: size/XS

#12667 Automated cherry pick of #12666: fix: fail to free reserved ip in non-owner project
  pkg/mcclient/modules/mod_reservedips.go
Labels: size/XS

#12668 Automated cherry pick of #12666: fix: fail to free reserved ip in non-owner project
  pkg/mcclient/modules/mod_reservedips.go
Labels: size/XS

#12661 fix(climc): fix proxy for cli
  cmd/aliyuncli/main.go
  cmd/apsaracli/main.go
  cmd/awscli/main.go
  cmd/azurecli/main.go
  cmd/cloudpodscli/main.go
  cmd/ctyuncli/main.go
  cmd/ecloudcli/main.go
  cmd/esxicli/main.go
  cmd/googlecli/main.go
  cmd/hcsocli/main.go
  cmd/huaweicli/main.go
  cmd/jdcloudcli/main.go
  cmd/openstackcli/main.go
  cmd/qcloudcli/main.go
  cmd/ucloudcli/main.go
  cmd/zstackcli/main.go
Labels: size/L, area/climc

#12662 Automated cherry pick of #12661: fix(climc): fix proxy for cli
  cmd/aliyuncli/main.go
  cmd/apsaracli/main.go
  cmd/awscli/main.go
  cmd/azurecli/main.go
  cmd/cloudpodscli/main.go
  cmd/ctyuncli/main.go
  cmd/ecloudcli/main.go
  cmd/esxicli/main.go
  cmd/googlecli/main.go
  cmd/hcsocli/main.go
  cmd/huaweicli/main.go
  cmd/jdcloudcli/main.go
  cmd/openstackcli/main.go
  cmd/qcloudcli/main.go
  cmd/ucloudcli/main.go
  cmd/zstackcli/main.go
Labels: size/L

#12663 fix(region): sync k8s cluster info to kubeserver
  pkg/compute/models/cloudsync.go
  pkg/compute/models/kube_clusters.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/M, area/region

#12672 fix(region): waf app tag sync
  pkg/compute/models/app.go
  pkg/multicloud/azure/azure.go
Labels: size/XS, area/region

#12676 fix: remove irrelevant codes
  cmd/climc/shell/monitor/suggestsysruleconfig.go
  pkg/apis/const.go
  pkg/mcclient/modules/compute/mod_skus.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysalert.go
  pkg/mcclient/options/monitor/suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysruleconfig.go
  pkg/mcclient/options/version.go
  pkg/util/logclient/consts_i18n.go
Labels: size/XL

#12671 fix(monitor): 告警历史问题修复
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/alertresource.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S, area/monitor

#12677 Automated cherry pick of #12671: fix(monitor): 告警历史问题修复
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/alertresource.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/tasks/detach_alertresource_task.go
Labels: size/M

#12683 fix(region): export user_tags
  pkg/cloudcommon/db/standalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/notify/models/config.go
Labels: size/M, area/region

#12684 Automated cherry pick of #12683: fix(region): export user_tags
  pkg/cloudcommon/db/standalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/notify/models/config.go
Labels: size/M

#12679 fix(region): tag sync
  pkg/compute/models/waf_instances.go
  pkg/multicloud/azure/web_app.go
Labels: size/XS, area/region

#12680 Automated cherry pick of #12679: fix(region): tag sync
  pkg/compute/models/waf_instances.go
  pkg/multicloud/azure/web_app.go
Labels: size/XS

#12664 ctyun support crm account
  cmd/ctyuncli/main.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/endpoints.go
  pkg/cloudprovider/extra.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/project.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/ctyun/region.go
  pkg/multicloud/ctyun/shell/vpc.go
Labels: size/L, area/region

#12665 Automated cherry pick of #12664: ctyun support crm account
  cmd/ctyuncli/main.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/endpoints.go
  pkg/cloudprovider/extra.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/ctyun/project.go
  pkg/multicloud/ctyun/provider/provider.go
  pkg/multicloud/ctyun/region.go
Labels: size/L

#12685 Independent scheduledtask service
  build/docker/Dockerfile.scheduledtask
  cmd/climc/main.go
  cmd/climc/shell/scheduledtask/scheduledtask.go
  cmd/scheduledtask/main.go
  pkg/apis/const.go
  pkg/apis/scheduledtask/const.go
  pkg/apis/scheduledtask/doc.go
  pkg/apis/scheduledtask/scheduled_task.go
  pkg/apis/scheduledtask/scheduled_task_const.go
  pkg/apis/scheduledtask/zz_generated.model.go
  pkg/compute/models/guests.go
  pkg/compute/models/initdb.go
  pkg/compute/options/options.go
  pkg/compute/service/handlers.go
  pkg/compute/service/service.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/mcclient/modules/managers.go
  pkg/mcclient/modules/scheduledtask/doc.go
  pkg/mcclient/modules/scheduledtask/mod_scheduledtask.go
  pkg/notify/models/event_template.go
  pkg/scheduledtask/models/doc.go
  pkg/scheduledtask/models/scheduled_tasks.go
  pkg/scheduledtask/models/scheduledtask_activity.go
  pkg/scheduledtask/models/scheduledtask_label.go
  pkg/scheduledtask/models/timer.go
  pkg/scheduledtask/options/doc.go
  pkg/scheduledtask/options/options.go
  pkg/scheduledtask/service/doc.go
  pkg/scheduledtask/service/handlers.go
  pkg/scheduledtask/service/service.go
Labels: area/region, size/XL

#12635 fix: add license upload
  cmd/climc/shell/misc/licenses.go
Labels: size/M, area/region

#12681 fix: server-create-eip allocation prefer owner's eip network
  pkg/compute/models/elasticips.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/L

#12682 Automated cherry pick of #12681: fix: server-create-eip allocation prefer owner's eip network
  pkg/compute/models/elasticips.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/L

#12694 fix: fix sqlchemy version to v1.0.0 for release/3.8
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/regutils/regutils.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
Labels: size/M

#12696 fix: fix version of sqlchemy to v1.0.0 for release/3.6
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/pkg/errors/consts.go
  vendor/yunion.io/x/pkg/util/compare/compare.go
  vendor/yunion.io/x/pkg/util/regutils/regutils.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
  vendor/yunion.io/x/pkg/utils/tags.go
  vendor/yunion.io/x/sqlchemy/README.md
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/const.go
  vendor/yunion.io/x/sqlchemy/constraint.go
  vendor/yunion.io/x/sqlchemy/debug.go
  vendor/yunion.io/x/sqlchemy/errors.go
  vendor/yunion.io/x/sqlchemy/fetch.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/index.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/sql.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/tablealias.go
  vendor/yunion.io/x/sqlchemy/union.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XXL

#12692 gcp lb sync ip address fix
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/google/loadbalancer.go
Labels: size/M, area/region

#12693 Automated cherry pick of #12692: gcp lb sync ip address fix
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/google/loadbalancer.go
Labels: size/M

#12626 fix: qemu extra options support multiple values
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M, area/region, area/host

#12690 Automated cherry pick of #12626: fix: qemu extra options support multiple values
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#12687 fix(cloudevent): qcloud event time
  pkg/multicloud/qcloud/events.go
Labels: size/XS, area/cloudevent

#12688 Automated cherry pick of #12687: fix(cloudevent): qcloud event time
  pkg/multicloud/qcloud/events.go
Labels: size/XS

#12689 Automated cherry pick of #12687: fix(cloudevent): qcloud event time
  pkg/multicloud/qcloud/events.go
Labels: size/XS

#12640 fix: validate VM vdi,vga,machine input
  pkg/apis/compute/guest_const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
Labels: size/L, area/region

#12691 Automated cherry pick of #12640: fix: validate VM vdi,vga,machine input
  pkg/apis/compute/guest_const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
Labels: size/L

#12697 fix: add switch of sdnagent tc man
  pkg/hostman/options/options.go
Labels: size/XS

#12698 Automated cherry pick of #12697: fix: add switch of sdnagent tc man
  pkg/hostman/options/options.go
Labels: size/XS

#12670 feat(cloudmon): modify cloudmon deployment
  cmd/cloudmon/main.go
  cmd/cloudmon/main_exec.go
  pkg/cloudmon/collectors/alertrecordhistorymon/alertrecordhistoryreport.go
  pkg/cloudmon/collectors/alertrecordhistoryservice.go
  pkg/cloudmon/collectors/alimon/alicloudreport.go
  pkg/cloudmon/collectors/apsaramon/apsaracloudreport.go
  pkg/cloudmon/collectors/awsmon/awscloudreport.go
  pkg/cloudmon/collectors/azuremon/azurereport.go
  pkg/cloudmon/collectors/cloudaccountmon/cloudaccountreport.go
  pkg/cloudmon/collectors/cloudaccountservice.go
  pkg/cloudmon/collectors/cloudmoninit.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudmon/collectors/common/cloudreport.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/cloudmon/collectors/ecloudmon/ecloudreport.go
  pkg/cloudmon/collectors/elbservice.go
  pkg/cloudmon/collectors/gcpmon/gcpreport.go
  pkg/cloudmon/collectors/hostservice.go
  pkg/cloudmon/collectors/huaweimon/huaweicloudreport.go
  pkg/cloudmon/collectors/jdmon/jdcloudreport.go
  pkg/cloudmon/collectors/ossservice.go
  pkg/cloudmon/collectors/pinger.go
  pkg/cloudmon/collectors/qcmon/qcloudreport.go
  pkg/cloudmon/collectors/rdsservice.go
  pkg/cloudmon/collectors/redisservice.go
  pkg/cloudmon/collectors/serverservice.go
  pkg/cloudmon/collectors/service_const.go
  pkg/cloudmon/collectors/storagemon/storagereport.go
  pkg/cloudmon/collectors/storageservice.go
  pkg/cloudmon/collectors/usageservice.go
  pkg/cloudmon/collectors/vmwaremon/vmwarereport.go
  pkg/cloudmon/collectors/zstackmon/zstackreport.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/doc.go
  pkg/cloudmon/service/service.go
Labels: size/XL, area/cloudmon

#12705 gcp lb sync address bugfix
  pkg/compute/models/loadbalancers.go
Labels: size/XS, area/region

#12701 fix(host): only local disk enable file.locking option on arm64 host
  pkg/hostman/guestman/qemu-arm.go
Labels: lgtm, size/S, area/host

#12702 Automated cherry pick of #12701: fix(host): only local disk enable file.locking option on arm64 host
  pkg/hostman/guestman/qemu-arm.go
Labels: lgtm, size/S

#12704 Automated cherry pick of #12701: fix(host): only local disk enable file.locking option on arm64 host
  pkg/hostman/guestman/qemu-arm.go
Labels: lgtm, size/S

#12707 feat(cloudmon): cloudmon support aws rds,redis metric
  pkg/cloudmon/collectors/awsmon/awscloudreport.go
  pkg/cloudmon/collectors/awsmon/awsservice.go
  pkg/cloudmon/collectors/awsmon/awsutils.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/multicloud/aws/monitor.go
Labels: size/L, area/cloudmon

#12700 fix(apigateway): support filename export
  pkg/apigateway/handler/resource.go
Labels: size/S, area/apigateway

#12703 Automated cherry pick of #12700: fix(apigateway): support filename export
  pkg/apigateway/handler/resource.go
Labels: size/S

#12715 feat(apigateway): init scheduledtask packages
  pkg/apigateway/handler/init.go
Labels: size/XS

#12713 fix: adjust the initialization order of init function contents
  pkg/mcclient/modules/notify/mod_notification.go
  pkg/mcclient/modules/notify/mod_notify.go
Labels: size/S

#12711 fix: add host option for ethtool_enable_gso
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/options/options.go
  pkg/util/netutils2/netutils.go
Labels: size/S

#12712 Automated cherry pick of #12711: fix: add host option for ethtool_enable_gso
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/options/options.go
  pkg/util/netutils2/netutils.go
Labels: size/S

#12718 fix: update vendor 20211121
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/README.md
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/M

#12719 fix: sqlite3 needs to load inet extension to work with region
  Makefile
  build/region/root/opt/yunion/share/sqlite/inet.so
  go.mod
  go.sum
  pkg/cloudcommon/database.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/column.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/column.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/column.go
  vendor/yunion.io/x/sqlchemy/column.go
Labels: size/L

#12721 fix: update scheduler using new sqlchemy
  pkg/scheduler/service/service.go
Labels: size/XS

#12726 fix: update vendor to fix union error
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/README.md
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/S

#12724 fix(region): adjust the logic of rebuild guest
  pkg/compute/guestdrivers/openstack.go
Labels: lgtm, size/M, area/region

#12720 fix: disk driver persistence
  pkg/apis/compute/guest_disk.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/L

#12725 Automated cherry pick of #12720: fix: disk driver persistence
  pkg/apis/compute/guest_disk.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/L

#12716 fix: correct prefined policies definitions
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
Labels: size/L

#12717 Automated cherry pick of #12716: fix: correct prefined policies definitions
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
Labels: size/L

#12727 Automated cherry pick of #12724: fix(region): adjust the logic of rebuild guest
  pkg/compute/guestdrivers/openstack.go
Labels: size/M

#12728 Automated cherry pick of #12724: fix(region): adjust the logic of rebuild guest
  pkg/compute/guestdrivers/openstack.go
Labels: size/M

#12732 fix(region): apsara rds network sync
  pkg/multicloud/apsara/dbinstance.go
Labels: size/XS, area/region

#12734 Automated cherry pick of #12732: fix(region): apsara rds network sync
  pkg/multicloud/apsara/dbinstance.go
Labels: size/XS

#12686 fix(region): hostname for vm and host
  pkg/apis/cloudprovider/zz_generated.model.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/apis/compute/input.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/apis/zz_generated.model.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/subaccount.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostnameresource.go
  pkg/compute/models/hosts.go
  pkg/compute/models/initdb.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/apsara/host.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/host.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/jdcloud/instance.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/qcloud/host.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/instance.go
  pkg/util/stringutils2/stringutils.go
  pkg/util/stringutils2/stringutils_test.go
Labels: lgtm, area/region, size/XL

#12737 fix(region): add rows.Close func
  pkg/compute/models/natgateways.go
  pkg/compute/models/vpcs_mapped_address.go
  pkg/compute/models/zones.go
Labels: size/XS, area/region

#12743 Automated cherry pick of #12737: fix(region): add rows.Close func
  pkg/compute/models/natgateways.go
  pkg/compute/models/vpcs_mapped_address.go
  pkg/compute/models/zones.go
Labels: size/XS

#12744 Automated cherry pick of #12737: fix(region): add rows.Close func
  pkg/compute/models/natgateways.go
  pkg/compute/models/vpcs_mapped_address.go
  pkg/compute/models/zones.go
Labels: size/XS

#12740 fix: close it after using sql.Rows
  pkg/monitor/models/monitor_resource.go
  pkg/notify/models/notification.go
Labels: size/XS

#12741 Automated cherry pick of #12740: fix: close it after using sql.Rows
  pkg/monitor/models/monitor_resource.go
  pkg/notify/models/notification.go
Labels: size/XS

#12742 Automated cherry pick of #12740: fix: close it after using sql.Rows
  pkg/monitor/models/monitor_resource.go
  pkg/notify/models/notification.go
Labels: size/XS

#12745 fix(region): aliyun kube cluster 404 error
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/shell/kube_cluster.go
Labels: size/S, area/region

#12738 feat(region): add cdn create op for qcloud
  cmd/climc/shell/compute/cdn_domains.go
  pkg/apis/compute/cdn.go
  pkg/cloudprovider/cdn.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cdn_domains.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/cdn_domain_create_task.go
  pkg/mcclient/options/compute/cdn_domains.go
  pkg/multicloud/qcloud/cdn.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/shell/cdn.go
Labels: size/L, area/region
