Repository yunionio/cloudpods, pull requests merged in 2021-03, with the labels that each got.

#10279 Automated cherry pick of #10278: fix(baremetal-agent): baremetal fail to stop due to power off soft failed
  pkg/baremetal/tasks/stop.go
Labels: size/XS

#10280 Automated cherry pick of #10278: fix(baremetal-agent): baremetal fail to stop due to power off soft failed
  pkg/baremetal/tasks/stop.go
Labels: size/XS

#10208 fix(region): pull the network correctly
  pkg/compute/models/networks.go
Labels: area/region, size/XS

#10209 Automated cherry pick of #10208: fix(region): pull the network correctly
  pkg/compute/models/networks.go
Labels: size/XS

#10284 networks: server_type: do not allow update
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/mcclient/options/network.go
Labels: approved, area/climc, area/region, lgtm, size/S

#10285 Automated cherry pick of #10284: networks: server_type: do not allow update
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/mcclient/options/network.go
Labels: approved, lgtm, size/S

#10286 fix(hostdeployer): windows rootfs umount leak
  pkg/hostman/diskutils/interface.go
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/guestfishpart/guestfishpart.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
Labels: approved, area/host, lgtm, size/L

#10287 Automated cherry pick of #10286: fix(hostdeployer): windows rootfs umount leak
  pkg/hostman/diskutils/interface.go
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/guestfishpart/guestfishpart.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
Labels: approved, lgtm, size/L

#10288 Automated cherry pick of #10286: fix(hostdeployer): windows rootfs umount leak
  pkg/hostman/diskutils/interface.go
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/guestfishpart/guestfishpart.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
Labels: approved, lgtm, size/L

#10289 fix(keystone): adjust default system policy names
  pkg/keystone/locale/genpolicy.go
Labels: area/keystone, size/S

#10290 Automated cherry pick of #10289: fix(keystone): adjust default system policy names
  pkg/keystone/locale/genpolicy.go
Labels: size/S

#10291 Automated cherry pick of #10289: fix(keystone): adjust default system policy names
  pkg/keystone/locale/genpolicy.go
Labels: size/S

#10292 fix(monitor): fix monitor export err
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/monitor/models/commonalert.go
Labels: area/monitor, size/M

#10293 Automated cherry pick of #10292: fix(monitor): fix monitor export err
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/monitor/models/commonalert.go
Labels: size/M

#10294 Automated cherry pick of #10292: fix(monitor): fix monitor export err
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/monitor/models/commonalert.go
Labels: size/M

#10295 feat(monitor): alert policy filter by res_type
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/commonalert.go
Labels: area/monitor, size/S

#10296 Automated cherry pick of #10295: feat(monitor): alert policy filter by res_type
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/commonalert.go
Labels: size/S

#10299 redis update tags fix
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/elasticcache_instance.go
Labels: area/region, size/XS

#10300 Automated cherry pick of #10299: redis update tags fix
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/XS

#10303 feat(region): nat op support
  pkg/apis/compute/nat.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/nat_skus.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/networks.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/nat_create_task.go
  pkg/multicloud/aliyun/natdtable.go
  pkg/multicloud/aliyun/natgateway.go
  pkg/multicloud/aliyun/natstable.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/apsara/natgateway.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/natgateway_base.go
  pkg/multicloud/qcloud/natgateway.go
Labels: area/region, size/L

#10304 Automated cherry pick of #10303: feat(region): nat op support
  pkg/apis/compute/nat.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/nat_skus.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/networks.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/nat_create_task.go
  pkg/multicloud/aliyun/natdtable.go
  pkg/multicloud/aliyun/natgateway.go
  pkg/multicloud/aliyun/natstable.go
  pkg/multicloud/aliyun/vpc.go
  pkg/multicloud/apsara/natgateway.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/huawei/shell/natgateway.go
  pkg/multicloud/natgateway_base.go
  pkg/multicloud/qcloud/natgateway.go
Labels: size/L

#10301 feat(mcclient,itsm): modify itsm mcclient rpc func
  pkg/mcclient/modules/mod_itsm_historic_process_instances.go
Labels: size/S

#10302 Automated cherry pick of #10301: feat(mcclient,itsm): modify itsm mcclient rpc func
  pkg/mcclient/modules/mod_itsm_historic_process_instances.go
Labels: size/S

#10305 infos copyright add brand_en&brand_cn
  cmd/climc/shell/misc/copyright.go
Labels: area/region, size/S

#10306 Automated cherry pick of #10305: infos copyright add brand_en&brand_cn
  cmd/climc/shell/misc/copyright.go
Labels: size/S

#10307 Automated cherry pick of #10305: infos copyright add brand_en&brand_cn
  cmd/climc/shell/misc/copyright.go
Labels: size/S

#10308 Automated cherry pick of #10305: infos copyright add brand_en&brand_cn
  cmd/climc/shell/misc/copyright.go
Labels: size/S

#10309 Automated cherry pick of #10305: infos copyright add brand_en&brand_cn
  cmd/climc/shell/misc/copyright.go
Labels: size/S

#10310 bugfix(monitor): 导出信息中添加全局字典配置
  pkg/monitor/models/commonalert.go
Labels: area/monitor, size/S

#10311 Automated cherry pick of #10310: bugfix(monitor): 导出信息中添加全局字典配置
  pkg/monitor/models/commonalert.go
Labels: size/S

#10316 fix(region): check whether guest is nil
  pkg/compute/models/instance_snapshots.go
Labels: area/region, size/XS

#10317 Automated cherry pick of #10316: fix(region): check whether guest is nil
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#10318 Automated cherry pick of #10316: fix(region): check whether guest is nil
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#10319 Automated cherry pick of #10316: fix(region): check whether guest is nil
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#10312 fix: optimzed tag sync
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/resource_tags.go
  pkg/multicloud/aliyun/shell/resource_tag.go
Labels: area/region, size/XL

#10313 Automated cherry pick of #10312: fix: optimzed tag sync
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/loadbalancer.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/resource_tags.go
  pkg/multicloud/aliyun/shell/resource_tag.go
Labels: size/XL

#10314 fix: add nat sku provider filter
  pkg/apis/compute/nat_skus.go
  pkg/compute/models/nat_skus.go
Labels: area/region, size/XS

#10315 Automated cherry pick of #10314: fix: add nat sku provider filter
  pkg/apis/compute/nat_skus.go
  pkg/compute/models/nat_skus.go
Labels: size/XS

#10322 copyright update brand_cn&brand_en fix
  cmd/climc/shell/misc/copyright.go
Labels: area/region, size/XS

#10323 Automated cherry pick of #10322: copyright update brand_cn&brand_en fix
  cmd/climc/shell/misc/copyright.go
Labels: size/XS

#10324 Automated cherry pick of #10322: copyright update brand_cn&brand_en fix
  cmd/climc/shell/misc/copyright.go
Labels: size/XS

#10325 Automated cherry pick of #10322: copyright update brand_cn&brand_en fix
  cmd/climc/shell/misc/copyright.go
Labels: size/XS

#10326 Automated cherry pick of #10322: copyright update brand_cn&brand_en fix
  cmd/climc/shell/misc/copyright.go
Labels: size/XS

#10320 fix: add secgroup filter opts
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
  pkg/mcclient/options/secgroup.go
Labels: area/region, size/M

#10321 Automated cherry pick of #10320: fix: add secgroup filter opts
  pkg/apis/compute/secgroup.go
  pkg/compute/models/secgroups.go
  pkg/mcclient/options/secgroup.go
Labels: size/M

#10327 fix(cloudcommon): add default domain of common options
  pkg/cloudcommon/options/options.go
Labels: area/util, size/XS

#10328 Automated cherry pick of #10327: fix(cloudcommon): add default domain of common options
  pkg/cloudcommon/options/options.go
Labels: size/XS

#10336 fix(notify): enable filter of contact type 'email' and 'mobile'
  pkg/notify/models/receiver.go
Labels: approved, area/notify, lgtm, size/S

#10337 Automated cherry pick of #10336: fix(notify): enable filter of contact type 'email' and 'mobile'
  pkg/notify/models/receiver.go
Labels: approved, lgtm, size/S

#10338 Automated cherry pick of #10336: fix(notify): enable filter of contact type 'email' and 'mobile'
  pkg/notify/models/receiver.go
Labels: approved, lgtm, size/S

#10339 Automated cherry pick of #10336: fix(notify): enable filter of contact type 'email' and 'mobile'
  pkg/notify/models/receiver.go
Labels: approved, lgtm, size/S

#10334 fix: add nat sku policy
  pkg/compute/policy/defaults.go
Labels: area/region, size/S

#10335 Automated cherry pick of #10334: fix: add nat sku policy
  pkg/compute/policy/defaults.go
Labels: size/S

#10330 Automated cherry pick of #10329: fix: optimized bucket tag
  pkg/cloudprovider/objectstore.go
  pkg/cloudprovider/resourcetags.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: size/L

#10331 Automated cherry pick of #10329: fix: optimized bucket tag
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: size/L

#10332 Automated cherry pick of #10329: fix: optimized bucket tag
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/bucket_base.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: size/L

#10348 fix: add cancel expire action
  cmd/climc/shell/compute/natgateways.go
  pkg/apis/input.go
  pkg/compute/models/natgateways.go
  pkg/mcclient/options/compute/natgateways.go
Labels: area/region, size/M

#10349 Automated cherry pick of #10348: fix: add cancel expire action
  cmd/climc/shell/compute/natgateways.go
  pkg/apis/input.go
  pkg/compute/models/natgateways.go
  pkg/mcclient/options/compute/natgateways.go
Labels: size/M

#10341 Automated cherry pick of #10340: etcd: fix "fatal error: concurrent map writes"
  pkg/cloudcommon/etcd/etcd.go
Labels: size/S

#10340 etcd: fix "fatal error: concurrent map writes"
  pkg/cloudcommon/etcd/etcd.go
Labels: area/region, size/S

#10342 Automated cherry pick of #10340: etcd: fix "fatal error: concurrent map writes"
  pkg/cloudcommon/etcd/etcd.go
Labels: size/S

#10343 Automated cherry pick of #10340: etcd: fix "fatal error: concurrent map writes"
  pkg/cloudcommon/etcd/etcd.go
Labels: size/S

#10344 Automated cherry pick of #10340: etcd: fix "fatal error: concurrent map writes"
  pkg/cloudcommon/etcd/etcd.go
Labels: size/S

#10282 feat(region): increase the network number and host number limit when recommending the network
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/mcclient/options/cloudaccounts.go
Labels: area/region, size/M

#10283 Automated cherry pick of #10282: feat(region): increase the network number and host number limit when recommending the network
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#10345 feat(build): make multi arch manifest docker image
  scripts/docker_push.sh
Labels: approved, area/util, lgtm, size/M

#10346 Automated cherry pick of #10345: feat(build): make multi arch manifest docker image
  scripts/docker_push.sh
Labels: approved, lgtm, size/M

#10275 fix: automatically setup object miemtype when uploading
  pkg/multicloud/objectstore/shell.go
Labels: area/climc, size/S

#10347 Automated cherry pick of #10345: feat(build): make multi arch manifest docker image
  scripts/docker_push.sh
Labels: approved, lgtm, size/L

#10355 Automated cherry pick of #10189: host 编译跨平台兼容
  build/docker/multi-arch/Dockerfile.host.dockerignore
Labels: size/XS

#10360 fix(build): build arm64 image
  Makefile
  Makefile.common.mk
  build/docker/Dockerfile.host-deployer
Labels: area/util, size/L

#10362 Automated cherry pick of #10361: fix(keystone): update default role associated policy name
  pkg/keystone/locale/predefined_policies.go
Labels: size/S

#10363 Automated cherry pick of #10361: fix(keystone): update default role associated policy name
  pkg/keystone/locale/predefined_policies.go
Labels: size/S

#10358 fix: sync nat sku when sync cloudaccount
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/mcclient/options/cloudaccounts.go
Labels: area/region, size/M

#10359 Automated cherry pick of #10358: fix: sync nat sku when sync cloudaccount
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#10367 fix(build): DOCKER_CLI_EXPERIMENTAL=enabled
  scripts/docker_push.sh
Labels: area/util, size/XS

#10368 Automated cherry pick of #10367: fix(build): DOCKER_CLI_EXPERIMENTAL=enabled
  scripts/docker_push.sh
Labels: size/XS

#10351 fix(region): network eip stats not correct
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/hosts.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: area/region, size/L

#10352 Automated cherry pick of #10351: fix(region): network eip stats not correct
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/hosts.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: size/L

#10354 Automated cherry pick of #10351: fix(region): network eip stats not correct
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/hosts.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: size/L

#10357 qcloud redis support multi zones
  pkg/apis/compute/elasticcache.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/multicloud/qcloud/elasticcache_instance.go
  pkg/multicloud/qcloud/region.go
Labels: approved, area/region, lgtm, size/L

#10377 Automated cherry pick of #10357: qcloud redis support multi zones
  pkg/apis/compute/elasticcache.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/multicloud/qcloud/elasticcache_instance.go
  pkg/multicloud/qcloud/region.go
Labels: approved, lgtm, size/L

#10376 Automated cherry pick of #10357: qcloud redis support multi zones
  pkg/apis/compute/elasticcache.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/multicloud/qcloud/elasticcache_instance.go
  pkg/multicloud/qcloud/region.go
Labels: approved, lgtm, size/L

#10365 feat(region): filter schedtags from cloudprovider_id
  pkg/apis/compute/schedtag.go
  pkg/compute/models/schedtags.go
  pkg/mcclient/options/schedtags.go
Labels: area/region, size/S

#10366 Automated cherry pick of #10365: feat(region): filter schedtags from cloudaccount_id
  pkg/apis/compute/schedtag.go
  pkg/compute/models/schedtags.go
  pkg/mcclient/options/schedtags.go
Labels: size/S

#10372 Automated cherry pick of #10365: feat(region): filter schedtags from cloudaccount_id
  pkg/apis/compute/schedtag.go
  pkg/compute/models/schedtags.go
  pkg/mcclient/options/schedtags.go
Labels: size/S

#10373 Automated cherry pick of #10365: feat(region): filter schedtags from cloudaccount_id
  pkg/apis/compute/schedtag.go
  pkg/compute/models/schedtags.go
  pkg/mcclient/options/schedtags.go
Labels: size/S

#10382 fix(region): cloud provider filter by domain
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
Labels: area/region, size/M

#10385 Automated cherry pick of #10382: fix(region): cloud provider filter by domain
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
Labels: size/M

#10386 Automated cherry pick of #10382: fix(region): cloud provider filter by domain
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
Labels: size/M

#10380 fix: add bucket tooltip
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/compute/models/buckets.go
Labels: area/region, size/XXL

#10381 Automated cherry pick of #10380: fix: add bucket tooltip
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/compute/models/buckets.go
Labels: size/XXL

#10378 fix: aliyun tag list api
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/resource_tags.go
Labels: area/region, size/S

#10374 fix: aliyun public ip bandwidth
  pkg/multicloud/aliyun/instance.go
Labels: area/region, size/XS

#10375 Automated cherry pick of #10374: fix: aliyun public ip bandwidth
  pkg/multicloud/aliyun/instance.go
Labels: size/XS

#10370 Hotfix/qx prepaid change config
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/shell/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/shell/instance.go
Labels: area/region, size/L

#10371 Automated cherry pick of #10370: Hotfix/qx prepaid change config
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/aliyun/shell/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/shell/instance.go
Labels: size/L

#10395 feat(esxi): update guest os info
  pkg/multicloud/esxi/guestos.go
Labels: area/region, size/M

#10396 Automated cherry pick of #10395: feat(esxi): update guest os info
  pkg/multicloud/esxi/guestos.go
Labels: size/M

#10397 Automated cherry pick of #10395: feat(esxi): update guest os info
  pkg/multicloud/esxi/guestos.go
Labels: size/M

#10398 Automated cherry pick of #10395: feat(esxi): update guest os info
  pkg/multicloud/esxi/guestos.go
Labels: size/M

#10391 fix: sync new project for azure resource group
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/resourcegroup.go
Labels: area/region, size/M

#10392 Automated cherry pick of #10391: fix: sync new project for azure resource group
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/resourcegroup.go
Labels: size/M

#10393 Automated cherry pick of #10391: fix: sync new project for azure resource group
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/resourcegroup.go
Labels: size/M

#10394 Automated cherry pick of #10391: fix: sync new project for azure resource group
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/resourcegroup.go
Labels: size/M

#10387 fix(region): fail to update network gateway
  pkg/compute/models/networks.go
Labels: area/region, size/XS

#10388 Automated cherry pick of #10387: fix(region): fail to update network gateway
  pkg/compute/models/networks.go
Labels: size/XS

#10390 Automated cherry pick of #10387: fix(region): fail to update network gateway
  pkg/compute/models/networks.go
Labels: size/XS

#10403 Automated cherry pick of #10402: fix(region): cloud provider filter by domain_id ignore private case
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#10404 Automated cherry pick of #10402: fix(region): cloud provider filter by domain_id ignore private case
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#10405 Automated cherry pick of #10402: fix(region): cloud provider filter by domain_id ignore private case
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#10406 Automated cherry pick of #10402: fix(region): cloud provider filter by domain_id ignore private case
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#10407 fix: tag sync
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/qcloud/bucket.go
Labels: approved, area/region, lgtm, size/M

#10409 Automated cherry pick of #10407: fix: tag sync
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/aws/bucket.go
  pkg/multicloud/huawei/bucket.go
  pkg/multicloud/qcloud/bucket.go
Labels: approved, lgtm, size/M

#10410 fix: skip zone check when rds change config
  pkg/compute/models/dbinstances.go
Labels: approved, area/region, lgtm, size/S

#10413 Automated cherry pick of #10410: fix: skip zone check when rds change config
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm

#10412 Automated cherry pick of #10410: fix: skip zone check when rds change config
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/S

#10411 Automated cherry pick of #10410: fix: skip zone check when rds change config
  pkg/compute/models/dbinstances.go
Labels: approved, lgtm, size/S

#10414 fix: sync cloud tags when set tags
  pkg/compute/models/buckets.go
Labels: approved, area/region, lgtm, size/XS

#10416 Automated cherry pick of #10414: fix: sync cloud tags when set tags
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/XS

#10417 Automated cherry pick of #10414: fix: sync cloud tags when set tags
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/XS

#10415 Automated cherry pick of #10414: fix: sync cloud tags when set tags
  pkg/compute/models/buckets.go
Labels: approved, lgtm, size/XS

#10421 fix: qcloud bucket refer
  cmd/climc/shell/compute/buckets.go
  pkg/apis/compute/bucket.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: area/region, size/L

#10424 Automated cherry pick of #10421: fix: qcloud bucket refer
  cmd/climc/shell/compute/buckets.go
  pkg/apis/compute/bucket.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: size/L

#10423 Automated cherry pick of #10421: fix: qcloud bucket refer
  cmd/climc/shell/compute/buckets.go
  pkg/apis/compute/bucket.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: size/L

#10422 Automated cherry pick of #10421: fix: qcloud bucket refer
  cmd/climc/shell/compute/buckets.go
  pkg/apis/compute/bucket.go
  pkg/cloudprovider/objectstore.go
  pkg/compute/models/buckets.go
  pkg/multicloud/aliyun/bucket.go
  pkg/multicloud/objectstore/shell.go
  pkg/multicloud/qcloud/bucket.go
Labels: size/L

#10418 fix(telegraf): megactl raid add rebuild status
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: area/monitor, size/XS

#10419 Automated cherry pick of #10418: fix(telegraf): megactl raid add rebuild status
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#10420 Automated cherry pick of #10418: fix(telegraf): megactl raid add rebuild status
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/XS

#10425 fix: change rds config skip zone check
  pkg/apis/compute/dbinstance.go
  pkg/cloudprovider/dbinstance.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_change_config.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/qcloud/rds_mysql.go
Labels: area/region, size/L

#10426 Automated cherry pick of #10425: fix: change rds config skip zone check
  pkg/apis/compute/dbinstance.go
  pkg/cloudprovider/dbinstance.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_change_config.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/L

#10427 Automated cherry pick of #10425: fix: change rds config skip zone check
  pkg/apis/compute/dbinstance.go
  pkg/cloudprovider/dbinstance.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_change_config.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/L

#10428 Automated cherry pick of #10425: fix: change rds config skip zone check
  pkg/apis/compute/dbinstance.go
  pkg/cloudprovider/dbinstance.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_change_config.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/huawei/dbinstance.go
  pkg/multicloud/qcloud/rds_mysql.go
Labels: size/L

#10429 fix: optimized nat entry
  pkg/apis/compute/elasticips_const.go
  pkg/apis/compute/nat.go
  pkg/apis/compute/natgateway.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/vpc_peering_connections.go
  pkg/compute/models/vpcs.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/eip_associate_task.go
  pkg/compute/tasks/nat_common.go
  pkg/compute/tasks/nat_delete_task.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/mcclient/options/compute/eips.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/natgateway.go
Labels: area/region, size/XXL

#10430 Automated cherry pick of #10429: fix: optimized nat entry
  pkg/apis/compute/elasticips_const.go
  pkg/apis/compute/nat.go
  pkg/apis/compute/natgateway.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/natdtable.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/natstable.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/vpc_peering_connections.go
  pkg/compute/models/vpcs.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/eip_associate_task.go
  pkg/compute/tasks/nat_common.go
  pkg/compute/tasks/nat_delete_task.go
  pkg/compute/tasks/natdentry_create_task.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_create_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/mcclient/options/compute/eips.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/huawei/natgateway.go
Labels: size/XXL

#10433 fix: avoid stop or start vm failed
  pkg/compute/tasks/guest_save_image_task.go
  pkg/multicloud/aws/instance.go
Labels: area/region, size/M

#10434 Automated cherry pick of #10433: fix: avoid stop or start vm failed
  pkg/multicloud/aws/instance.go
Labels: size/S

#10435 Automated cherry pick of #10433: fix: avoid stop or start vm failed
  pkg/multicloud/aws/instance.go
Labels: size/S

#10436 Automated cherry pick of #10433: fix: avoid stop or start vm failed
  pkg/multicloud/aws/instance.go
Labels: size/S

#10399 fix: optimzed tag update and sync
  pkg/cloudprovider/fakeregion.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/syncutils.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/elasticcache_instance.go
  pkg/multicloud/apsara/loadbalancer.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/qcloud/bucket.go
  pkg/multicloud/qcloud/elasticcache_instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/resource_base.go
Labels: area/region, size/L

#10400 Automated cherry pick of #10399: fix: optimzed tag update and sync
  pkg/cloudprovider/fakeregion.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/syncutils.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/elasticcache_instance.go
  pkg/multicloud/apsara/loadbalancer.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/qcloud/bucket.go
  pkg/multicloud/qcloud/elasticcache_instance.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/resource_base.go
Labels: size/L

#10162 fix(region): struct input for detach server network
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: area/region, size/M

#10401 Automated cherry pick of #10162: fix(region): struct input for detach server network
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: size/M

#10441 fix(region): including domain info in project-role results
  pkg/mcclient/modules/mod_roleassignments.go
Labels: area/climc, size/L

#10442 Automated cherry pick of #10441: fix(region): including domain info in project-role results
  pkg/mcclient/modules/mod_roleassignments.go
Labels: size/L

#10443 Automated cherry pick of #10441: fix(region): including domain info in project-role results
  pkg/mcclient/modules/mod_roleassignments.go
Labels: size/L

#10444 Automated cherry pick of #10441: fix(region): including domain info in project-role results
  pkg/mcclient/modules/mod_roleassignments.go
Labels: size/L

#10437 fix(region): scoped policy filter by project id
  pkg/yunionconf/models/scopedpolicybindings.go
Labels: area/yunionconf, size/XS

#10438 Automated cherry pick of #10437: fix(region): scoped policy filter by project id
  pkg/yunionconf/models/scopedpolicybindings.go
Labels: size/XS

#10439 Automated cherry pick of #10437: fix(region): scoped policy filter by project id
  pkg/yunionconf/models/scopedpolicybindings.go
Labels: size/XS
