Repository yunionio/cloudpods, pull requests merged in 2021-01, with the labels that each got.

#9752 feature(region): sync cloud tags to local user tags
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/buckets.go
Labels: size/M

#9753 Automated cherry pick of #9752: feature(region): sync cloud tags to local user tags
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/buckets.go
Labels: size/M

#9757 fix(monitor): modify totalrecord query
  pkg/monitor/models/alertrecord.go
  pkg/monitor/tsdb/driver/influxdb/query_part.go
Labels: area/monitor, size/XS

#9758 Automated cherry pick of #9757: fix(monitor): modify totalrecord query
  pkg/monitor/models/alertrecord.go
  pkg/monitor/tsdb/driver/influxdb/query_part.go
Labels: size/XS

#9761 Automated cherry pick of #9760: fix(region): replace cloud tags
  pkg/compute/models/buckets.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/aws/instance.go
Labels: size/S

#9760 fix(region): replace cloud tags
  pkg/compute/models/buckets.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guests.go
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/aws/instance.go
Labels: area/region, lgtm, size/S

#9762 feat(region): stop guest before freeze
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
Labels: area/region, lgtm, size/M

#9763 Automated cherry pick of #9762: feat(region): stop guest before freeze
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
Labels: size/M

#9764 Automated cherry pick of #9762: feat(region): stop guest before freeze
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
Labels: size/M

#9765 Automated cherry pick of #9762: feat(region): stop guest before freeze
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
Labels: size/M

#9766 Automated cherry pick of #9762: feat(region): stop guest before freeze
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
Labels: size/M

#9768 fix(region): sync cachedimage info
  pkg/compute/models/cloudimages.go
  pkg/compute/models/cloudregions.go
Labels: area/region, size/S

#9769 Automated cherry pick of #9768: fix(region): sync cachedimage info
  pkg/compute/models/cloudimages.go
  pkg/compute/models/cloudregions.go
Labels: size/S

#9771 fix(region): avoid panic when register service not work
  pkg/multicloud/azure/azure.go
Labels: area/region, size/M

#9767 fix(region): aliyun support public ip
  pkg/cloudprovider/resources.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/instance_base.go
Labels: area/region, size/M

#9770 Automated cherry pick of #9767: fix(region): aliyun support public ip
  pkg/cloudprovider/resources.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/multicloud/aliyun/host.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/instance_base.go
Labels: size/M

#9773 Automated cherry pick of #9771: fix(region): avoid panic when register service not work
  pkg/multicloud/azure/azure.go
Labels: size/M

#9772 Automated cherry pick of #9771: fix(region): avoid panic when register service not work
  pkg/multicloud/azure/azure.go
Labels: size/M

#9774 Automated cherry pick of #9771: fix(region): avoid panic when register service not work
  pkg/multicloud/azure/azure.go
Labels: size/M

#9775 fix(cloudevent): default policy
  pkg/cloudevent/policy/resources.go
Labels: area/cloudevent, size/XS

#9776 Automated cherry pick of #9775: fix(cloudevent): default policy
  pkg/cloudevent/policy/resources.go
Labels: size/XS

#9777 Automated cherry pick of #9775: fix(cloudevent): default policy
  pkg/cloudevent/policy/resources.go
Labels: size/XS

#9778 fix(region): avoid auzre request timeout
  pkg/multicloud/azure/azure.go
Labels: area/region, size/XS

#9779 Automated cherry pick of #9778: fix(region): avoid auzre request timeout
  pkg/multicloud/azure/azure.go
Labels: size/XS

#9780 Automated cherry pick of #9778: fix(region): avoid auzre request timeout
  pkg/multicloud/azure/azure.go
Labels: size/XS

#9781 Automated cherry pick of #9778: fix(region): avoid auzre request timeout
  pkg/multicloud/azure/azure.go
Labels: size/XS

#9782 fix(monitor,suggestion): order commonalert metric and modify alertresoruce type value and add suggestion models climc
  cmd/climc/shell/suggestion/suggestsysalert.go
  pkg/apis/monitor/alertresource.go
  pkg/apis/monitor/metric.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysalert.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertresource.go
Labels: area/monitor, size/M

#9783 Automated cherry pick of #9782: fix(monitor,suggestion): order commonalert metric and modify alertresoruce type value and add suggestion models climc
  cmd/climc/shell/suggestion/suggestsysalert.go
  pkg/apis/monitor/alertresource.go
  pkg/apis/monitor/metric.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysalert.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertresource.go
Labels: size/M

#9784 Automated cherry pick of #9782: fix(monitor,suggestion): order commonalert metric and modify alertresoruce type value and add suggestion models climc
  cmd/climc/shell/suggestion/suggestsysalert.go
  pkg/apis/monitor/alertresource.go
  pkg/apis/monitor/metric.go
  pkg/mcclient/modules/monitor/suggestsysrule.go
  pkg/mcclient/options/monitor/suggestsysalert.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertresource.go
Labels: size/M

#9785 guest_deploy_task: log other deploy details with i18n
  pkg/compute/tasks/guest_deploy_task.go
Labels: area/region, size/XS

#9786 Automated cherry pick of #9785: guest_deploy_task: log other deploy details with i18n
  pkg/compute/tasks/guest_deploy_task.go
Labels: size/XS

#9787 Automated cherry pick of #9785: guest_deploy_task: log other deploy details with i18n
  pkg/compute/tasks/guest_deploy_task.go
Labels: size/XS

#9788 Automated cherry pick of #9785: guest_deploy_task: log other deploy details with i18n
  pkg/compute/tasks/guest_deploy_task.go
Labels: size/XS

#9789 Automated cherry pick of #9785: guest_deploy_task: log other deploy details with i18n
  pkg/compute/tasks/guest_deploy_task.go
Labels: size/XS

#9790 fix(host-deployer): add retry on check is vgactived
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
Labels: size/S

#9791 Automated cherry pick of #9790: fix(host-deployer): add retry on check is vgactived
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
Labels: size/S

#9792 Automated cherry pick of #9790: fix(host-deployer): add retry on check is vgactived
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
Labels: size/S

#9802 fix(notify): loose mobile phone number matching rules
  pkg/notify/models/receiver.go
Labels: area/notify, size/XS

#9805 Automated cherry pick of #9802: fix(notify): loose mobile phone number matching rules
  pkg/notify/models/receiver.go
Labels: size/XS

#9803 Automated cherry pick of #9802: fix(notify): loose mobile phone number matching rules
  pkg/notify/models/receiver.go
Labels: size/XS

#9804 Automated cherry pick of #9802: fix(notify): loose mobile phone number matching rules
  pkg/notify/models/receiver.go
Labels: size/XS

#9813 fix(notify): loose phone number rules in updating receiver
  pkg/notify/models/receiver.go
Labels: area/notify, size/XS

#9814 Automated cherry pick of #9813: fix(notify): loose phone number rules in updating receiver
  pkg/notify/models/receiver.go
Labels: size/XS

#9815 Automated cherry pick of #9813: fix(notify): loose phone number rules in updating receiver
  pkg/notify/models/receiver.go
Labels: size/XS

#9816 Automated cherry pick of #9813: fix(notify): loose phone number rules in updating receiver
  pkg/notify/models/receiver.go
Labels: size/XS

#9811 fix(region): avoid cachedimage never be in sync when it deleted
  pkg/compute/models/cloudimages.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/storagecaches.go
Labels: area/region, size/M

#9812 Automated cherry pick of #9811: fix(region): avoid cachedimage never be in sync when it deleted
  pkg/compute/models/cloudimages.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/storagecaches.go
Labels: size/M

#9798 fix(region): optimized for qcloud prepaid instance delete
  pkg/multicloud/qcloud/instance.go
Labels: area/region, size/S

#9799 Automated cherry pick of #9798: fix(region): optimized for qcloud prepaid instance delete
  pkg/multicloud/qcloud/instance.go
Labels: size/S

#9800 Automated cherry pick of #9798: fix(region): optimized for qcloud prepaid instance delete
  pkg/multicloud/qcloud/instance.go
Labels: size/S

#9801 Automated cherry pick of #9798: fix(region): optimized for qcloud prepaid instance delete
  pkg/multicloud/qcloud/instance.go
Labels: size/S

#9809 Automated cherry pick of #9808: fix(region): aws elb backendgroup sync bugfix
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancers.go
Labels: approved, lgtm, size/M

#9808 fix(region): aws elb backendgroup sync bugfix
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancers.go
Labels: approved, area/region, lgtm, size/M

#9810 Automated cherry pick of #9808: fix(region): aws elb backendgroup sync bugfix
  pkg/compute/models/loadbalancerawscachedlbbg.go
  pkg/compute/models/loadbalancers.go
Labels: approved, lgtm, size/M

#9820 fix(meter): add budget set alert log
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: approved, lgtm

#9821 Automated cherry pick of #9820: fix(meter): add budget set alert log
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: approved, lgtm, size/XS

#9830 loadbalancer add lb purge validate
  pkg/compute/models/loadbalancers.go
Labels: area/region, lgtm, size/S

#9825 fix(notify): avoid duplication of notification names
  pkg/notify/models/notification.go
Labels: area/notify, size/XS

#9826 Automated cherry pick of #9825: fix(notify): avoid duplication of notification names
  pkg/notify/models/notification.go
Labels: size/XS

#9827 Automated cherry pick of #9825: fix(notify): avoid duplication of notification names
  pkg/notify/models/notification.go
Labels: size/XS

#9828 Automated cherry pick of #9825: fix(notify): avoid duplication of notification names
  pkg/notify/models/notification.go
Labels: size/XS

#9817 fix(monitor): fix monitoroverview and meter send alerting info to notify
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
Labels: area/monitor, size/M

#9818 Automated cherry pick of #9817: fix(monitor): fix monitoroverview and meter send alerting info to notify
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
Labels: size/M

#9819 Automated cherry pick of #9817: fix(monitor): fix monitoroverview and meter send alerting info to notify
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
Labels: size/M

#9794 Automated cherry pick of #9793: feat(region): server sku os_arch & cpu_arch checking
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
Labels: size/S

#9795 Automated cherry pick of #9793: feat(region): server sku os_arch & cpu_arch checking
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
Labels: size/S

#9831 Automated cherry pick of #9830: loadbalancer add lb purge validate
  pkg/compute/models/loadbalancers.go
Labels: size/S

#9832 Automated cherry pick of #9830: loadbalancer add lb purge validate
  pkg/compute/models/loadbalancers.go
Labels: size/S

#9822 fix(apigateway): count city servers
  cmd/climc/shell/compute/cloudregions.go
  pkg/mcclient/modules/mod_cloudregions.go
Labels: area/region, size/M

#9823 Automated cherry pick of #9822: fix(apigateway): count city servers
  cmd/climc/shell/compute/cloudregions.go
  pkg/mcclient/modules/mod_cloudregions.go
Labels: size/M

#9796 fix(region): allowed to manually refresh cloudimage
  cmd/climc/shell/compute/cloudregions.go
  pkg/apis/compute/sku_const.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/cloudregions.go
  pkg/compute/tasks/cloudregion_sync_images_task.go
  pkg/mcclient/options/skus.go
Labels: area/region, size/M

#9797 Automated cherry pick of #9796: fix(region): allowed to manually refresh cloudimage
  cmd/climc/shell/compute/cloudregions.go
  pkg/apis/compute/sku_const.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/cloudregions.go
  pkg/compute/tasks/cloudregion_sync_images_task.go
  pkg/mcclient/options/skus.go
Labels: size/M

#9851 fix(monitor): monitor overview throw err
  pkg/monitor/models/alertrecord.go
Labels: area/monitor, size/XS

#9852 Automated cherry pick of #9851: fix(monitor): monitor overview throw err
  pkg/monitor/models/alertrecord.go
Labels: size/XS

#9853 Automated cherry pick of #9851: fix(monitor): monitor overview throw err
  pkg/monitor/models/alertrecord.go
Labels: size/XS

#9844 Feature/yousong i18n apigateway
  Makefile
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/auth_totp.go
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/misc.go
  pkg/apigateway/handler/resource.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/services.go
Labels: area/apigateway, area/keystone, size/XXL

#9845 Automated cherry pick of #9844: Feature/yousong i18n apigateway
  Makefile
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/auth_totp.go
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/misc.go
  pkg/apigateway/handler/resource.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/services.go
Labels: size/XXL

#9846 Automated cherry pick of #9844: Feature/yousong i18n apigateway
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/auth_totp.go
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/misc.go
  pkg/apigateway/handler/resource.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/services.go
Labels: size/XXL

#9841 server skus filter by mem size fix
  pkg/compute/models/skus.go
Labels: area/region, size/XS

#9842 Automated cherry pick of #9841: server skus filter by mem size fix
  pkg/compute/models/skus.go
Labels: size/XS

#9843 Automated cherry pick of #9841: server skus filter by mem size fix
  pkg/compute/models/skus.go
Labels: size/XS

#9833 fix(cloudid): multi cloudaccount with saml user
  pkg/cloudid/models/samluser.go
Labels: area/cloudid, size/S

#9834 Automated cherry pick of #9833: fix(cloudid): multi cloudaccount with saml user
  pkg/cloudid/models/samluser.go
Labels: size/S

#9836 fix(keystone): add suggestion previliges to meter admin
  pkg/keystone/locale/predefined_policies.go
Labels: area/keystone, size/M

#9837 Automated cherry pick of #9836: fix(keystone): add suggestion previliges to meter admin
  pkg/keystone/locale/predefined_policies.go
Labels: size/M

#9838 Automated cherry pick of #9836: fix(keystone): add suggestion previliges to meter admin
  pkg/keystone/locale/predefined_policies.go
Labels: size/XS

#9839 fix(cloudevent): add aws cloudevent
  go.mod
  go.sum
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/cloudtrail.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/cloudtrail.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/doc.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/errors.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/service.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/compare/compare.go
Labels: area/cloudevent, size/XXL

#9840 Automated cherry pick of #9839: fix(cloudevent): add aws cloudevent
  go.mod
  go.sum
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/cloudtrail.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/cloudtrail.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/api.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/doc.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/errors.go
  vendor/github.com/aws/aws-sdk-go/service/cloudtrail/service.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/compare/compare.go
Labels: size/XXL

#9847 feat(notify): send notifications of different templates according to language
  build/notify/root/opt/yunion/share/template/content@cn/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/content@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/content@en/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/content@en/VERIFY.email
  build/notify/root/opt/yunion/share/template/title@cn/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/title@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/title@en/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/title@en/VERIFY.email
  pkg/apis/notify/const.go
  pkg/notify/interface.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/template.go
  pkg/notify/rpc/send.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: area/region, size/L

#9848 Automated cherry pick of #9847: feat(notify): send notifications of different templates according to language
  build/notify/root/opt/yunion/share/template/content@cn/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/content@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/content@en/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/content@en/VERIFY.email
  build/notify/root/opt/yunion/share/template/title@cn/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/title@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/title@en/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/title@en/VERIFY.email
  pkg/apis/notify/const.go
  pkg/notify/interface.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/template.go
  pkg/notify/rpc/send.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/L

#9849 Automated cherry pick of #9847: feat(notify): send notifications of different templates according to language
  build/notify/root/opt/yunion/share/template/content@cn/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/content@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/content@en/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/content@en/VERIFY.email
  build/notify/root/opt/yunion/share/template/title@cn/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/title@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/title@en/IMAGE_ACTIVED
  build/notify/root/opt/yunion/share/template/title@en/VERIFY.email
  pkg/apis/notify/const.go
  pkg/notify/interface.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/template.go
  pkg/notify/rpc/send.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/L

#9829 fix(region): tag bugs fix
  pkg/apis/compute/dbinstance_const.go
  pkg/apis/compute/elasticcache_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/loadbalancer_const.go
  pkg/cloudprovider/resourcetags.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/guest_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/shell/instance.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/instance.go
Labels: area/region, lgtm, size/L

#9855 Automated cherry pick of #9829: fix(region): tag bugs fix
  pkg/apis/compute/dbinstance_const.go
  pkg/apis/compute/elasticcache_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/loadbalancer_const.go
  pkg/cloudprovider/resourcetags.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/buckets.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/guest_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/shell/instance.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/huawei/shell/instance.go
Labels: size/L

#9690 fix(region): optimized secgroup rule sync
  pkg/apis/compute/secgroup_const.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgroups.go
  pkg/compute/tasks/security_group_sync_rules_task.go
Labels: area/region, size/L

#9854 Automated cherry pick of #9690: fix(region): optimized secgroup rule sync
  pkg/apis/compute/secgroup_const.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgroups.go
  pkg/compute/tasks/security_group_sync_rules_task.go
Labels: size/L

#9857 fix(notify): set ModelManager in Receiver()
  pkg/notify/models/receiver_notification.go
Labels: area/notify, size/XS

#9858 Automated cherry pick of #9857: fix(notify): set ModelManager in Receiver()
  pkg/notify/models/receiver_notification.go
Labels: size/XS

#9859 Automated cherry pick of #9857: fix(notify): set ModelManager in Receiver()
  pkg/notify/models/receiver_notification.go
Labels: size/XS

#9861 Automated cherry pick of #9860: fix(region): update tags status
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
Labels: size/M

#9860 fix(region): update tags status
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/elasticcache_remote_update_task.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
Labels: lgtm

#9862 fix(notify): set status after sending
  pkg/notify/tasks/notifications_send_task.go
Labels: area/notify, size/M

#9864 Automated cherry pick of #9862: fix(notify): set status after sending
  pkg/notify/tasks/notifications_send_task.go
Labels: size/M

#9865 feat(monitor): support monitor overview influxdb query pass through
  pkg/apis/monitor/commalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: area/monitor, size/S

#9866 Automated cherry pick of #9865: feat(monitor): support monitor overview influxdb query pass through
  pkg/apis/monitor/commalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/S

#9867 Automated cherry pick of #9865: feat(monitor): support monitor overview influxdb query pass through
  pkg/apis/monitor/commalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/S

#9872 fix(region): AWS buckets in us-east-1 have null location
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/region.go
Labels: area/region, size/S

#9873 Automated cherry pick of #9872: fix(region): AWS buckets in us-east-1 have null location
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/region.go
Labels: size/S

#9874 Automated cherry pick of #9872: fix(region): AWS buckets in us-east-1 have null location
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/region.go
Labels: size/S

#9875 Automated cherry pick of #9872: fix(region): AWS buckets in us-east-1 have null location
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/region.go
Labels: size/S

#9876 Automated cherry pick of #9872: fix(region): AWS buckets in us-east-1 have null location
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/region.go
Labels: size/S

#9870 feature(climc): add policy-clone command
  cmd/climc/shell/identity/policies.go
Labels: area/climc, size/M

#9871 Automated cherry pick of #9870: feature(climc): add policy-clone command
  cmd/climc/shell/identity/policies.go
Labels: size/M

#9868 Send notification when abnormal login occurs
  build/notify/root/opt/yunion/share/template/content@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/content@en/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@en/USER_LOGIN_EXCEPTION
  pkg/apis/notify/const.go
  pkg/apis/notify/notification.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/default_admin.go
  pkg/keystone/models/users.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/token.go
  pkg/keystone/util/doc.go
  pkg/keystone/util/session.go
  pkg/mcclient/modules/notify/mod_notification.go
  pkg/notify/models/notification.go
Labels: area/keystone, area/notify, size/L

#9869 Automated cherry pick of #9868: Send notification when abnormal login occurs
  build/notify/root/opt/yunion/share/template/content@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/content@en/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@en/USER_LOGIN_EXCEPTION
  pkg/apis/notify/const.go
  pkg/apis/notify/notification.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/default_admin.go
  pkg/keystone/models/users.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/token.go
  pkg/keystone/util/doc.go
  pkg/keystone/util/session.go
  pkg/mcclient/modules/notify/mod_notification.go
  pkg/notify/models/notification.go
Labels: size/L

#9879 feat(monitor): influxQuery add P95 reduce
  pkg/monitor/alerting/conditions/reducer.go
Labels: area/monitor, size/S

#9880 Automated cherry pick of #9879: feat(monitor): influxQuery add P95 reduce
  pkg/monitor/alerting/conditions/reducer.go
Labels: size/S

#9881 Automated cherry pick of #9879: feat(monitor): influxQuery add P95 reduce
  pkg/monitor/alerting/conditions/reducer.go
Labels: size/S

#9882 Fix Notifition about Panic_Error Send too much
  pkg/notify/models/receiver.go
  pkg/notify/options/options.go
  pkg/notify/tasks/notifications_send_task.go
Labels: area/notify, size/XS

#9884 Automated cherry pick of #9882: Fix Notifition about Panic_Error Send too much
  pkg/notify/models/receiver.go
  pkg/notify/options/options.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/XS

#9856 fix(region): optimized azure reset linux pasword
  pkg/multicloud/azure/instance.go
Labels: area/region, size/M

#9885 Automated cherry pick of #9856: fix(region): optimized azure reset linux pasword
  pkg/multicloud/azure/instance.go
Labels: size/M

#9886 Automated cherry pick of #9856: fix(region): optimized azure reset linux pasword
  pkg/multicloud/azure/instance.go
Labels: size/M

#9887 Automated cherry pick of #9856: fix(region): optimized azure reset linux pasword
  pkg/multicloud/azure/instance.go
Labels: size/M

#9899 feat(vpcs): list: add order_by_network_count
  pkg/apis/compute/vpcs_const.go
  pkg/compute/models/vpcs.go
Labels: area/region, size/M

#9895 fix(region): update google latitude and langtitude
  pkg/multicloud/google/latitude_and_longitude.go
Labels: area/region, size/XS

#9896 Automated cherry pick of #9895: fix(region): update google latitude and langtitude
  pkg/multicloud/google/latitude_and_longitude.go
Labels: size/XS

#9897 Automated cherry pick of #9895: fix(region): update google latitude and langtitude
  pkg/multicloud/google/latitude_and_longitude.go
Labels: size/XS

#9898 Automated cherry pick of #9895: fix(region): update google latitude and langtitude
  pkg/multicloud/google/latitude_and_longitude.go
Labels: size/XS

#9893 refactor(climc): remove dependence for `yunion.io/x/pkg/cloudcommon/db`
  pkg/apis/cloudcommon/db/doc.go
  pkg/apis/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/metadata.go
  pkg/mcclient/options/base.go
Labels: area/climc, size/M

#9894 Automated cherry pick of #9893: refactor(climc): remove dependence for `yunion.io/x/pkg/cloudcommon/db`
  pkg/apis/cloudcommon/db/doc.go
  pkg/apis/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/metadata.go
  pkg/mcclient/options/base.go
Labels: size/M

#9877 fix(cloudevent): optimized cloudevent sync
  pkg/multicloud/aws/cloudtrail.go
Labels: size/S

#9878 Automated cherry pick of #9877: fix(cloudevent): optimized cloudevent sync
  pkg/multicloud/aws/cloudtrail.go
Labels: size/S

#9888 fix(cloudid): optimized saml sso
  pkg/apis/cloudid/cloudrole.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudrole.go
  pkg/cloudid/saml/providers/aliyun/driver.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/saml/providers/qcloud/driver.go
  pkg/multicloud/aliyun/provider/provider.go
Labels: area/cloudid, size/L

#9889 Automated cherry pick of #9888: fix(cloudid): optimized saml sso
  pkg/apis/cloudid/cloudrole.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudrole.go
  pkg/cloudid/saml/providers/aliyun/driver.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/saml/providers/qcloud/driver.go
  pkg/multicloud/aliyun/provider/provider.go
Labels: size/L

#9890 Automated cherry pick of #9888: fix(cloudid): optimized saml sso
  pkg/apis/cloudid/cloudrole.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudrole.go
  pkg/cloudid/saml/providers/aliyun/driver.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/saml/providers/qcloud/driver.go
  pkg/multicloud/aliyun/provider/provider.go
Labels: size/L

#9891 Repair of abnormal login notification
  build/notify/root/opt/yunion/share/template/content@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@en/USER_LOGIN_EXCEPTION
  pkg/cloudcommon/notifyclient/notify.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/users.go
  pkg/notify/models/notification.go
  pkg/notify/models/template.go
Labels: area/keystone, area/notify, lgtm, size/L

#9892 Automated cherry pick of #9891: Repair of abnormal login notification
  build/notify/root/opt/yunion/share/template/content@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@cn/USER_LOGIN_EXCEPTION
  build/notify/root/opt/yunion/share/template/title@en/USER_LOGIN_EXCEPTION
  pkg/cloudcommon/notifyclient/notify.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/users.go
  pkg/notify/models/notification.go
  pkg/notify/models/template.go
Labels: size/L

#9902 feat(meter): add cost report module
  cmd/climc/shell/meter/costreports.go
  pkg/mcclient/modules/mod_costreports.go
  pkg/mcclient/options/meter/costreports.go
Labels: size/L

#9903 Automated cherry pick of #9902: feat(meter): add cost report module
  cmd/climc/shell/meter/costreports.go
  pkg/mcclient/modules/mod_costreports.go
  pkg/mcclient/options/meter/costreports.go
Labels: size/L

#9908 Automated cherry pick of #9907: feat(monitor): influxQuery add P95 reduce
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/reducer_test.go
Labels: approved, lgtm, size/M

#9907 feat(monitor): query reduce percentile
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/reducer_test.go
Labels: approved, lgtm, size/M

#9909 Automated cherry pick of #9907: feat(monitor): influxQuery add P95 reduce
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/reducer_test.go
Labels: approved, lgtm, size/M

#9914 fix(cloudcommon): missing set_meta opslog
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/opslog.go
Labels: area/util, size/S

#9915 Automated cherry pick of #9914: fix(cloudcommon): missing set_meta opslog
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/opslog.go
Labels: size/S

#9916 Automated cherry pick of #9914: fix(cloudcommon): missing set_meta opslog
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/opslog.go
Labels: size/S

#9917 Automated cherry pick of #9914: fix(cloudcommon): missing set_meta opslog
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/opslog.go
Labels: size/S

#9918 Automated cherry pick of #9914: fix(cloudcommon): missing set_meta opslog
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/opslog.go
Labels: size/S

#9910 fix(region): avoid azure detach disk failed
  pkg/multicloud/azure/instance.go
Labels: approved, area/region, lgtm, size/S

#9913 Automated cherry pick of #9910: fix(region): avoid azure detach disk failed
  pkg/multicloud/azure/instance.go
Labels: approved, lgtm, size/S

#9911 Automated cherry pick of #9910: fix(region): avoid azure detach disk failed
  pkg/multicloud/azure/instance.go
Labels: approved, lgtm, size/S
