Repository yunionio/cloudpods, pull requests merged in 2021-05, with the labels that each got.

#10975 feat(arm64,build): arm 编译时,不编译 rbdcli
  scripts/docker_push.sh
Labels: approved, lgtm, size/XS

#10976 Automated cherry pick of #10975: feat(arm64,build): arm 编译时,不编译 rbdcli
  scripts/docker_push.sh
Labels: size/XS

#10977 Automated cherry pick of #10975: feat(arm64,build): arm 编译时,不编译 rbdcli
  scripts/docker_push.sh
Labels: size/XS

#10981 feat(region): host list order by server count
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: approved, area/region, size/S

#10982 Automated cherry pick of #10981: feat(region): host list order by server count
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: approved, size/S

#10979 fix for creating proxy endpoint
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/sshkeys/handler.go
  pkg/mcclient/models/base.go
Labels: approved, area/cloudproxy, area/region, lgtm, size/XS

#10993 Bugfix/yousong cloudproxy wait on error
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudproxy/agent/ssh/client.go
  pkg/cloudproxy/models/forwards.go
  pkg/compute/models/guest_sshable.go
Labels: approved, area/cloudproxy, area/region, lgtm, size/M

#10990 fix for install monitor agent
  build/docker/Dockerfile.ansibleserver
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: approved, area/devtool, lgtm, size/M

#10991 Automated cherry pick of #10990: fix for install monitor agent
  build/docker/Dockerfile.ansibleserver
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: size/M

#10988 fix: avoid return no data result
  pkg/mcclient/modulebase/base.go
Labels: area/region, size/XS

#10985 fix: add tag for databricks vm
  pkg/apis/metadata.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/syncutils.go
  pkg/multicloud/azure/instance.go
Labels: area/region, size/M

#10986 Automated cherry pick of #10985: fix: add tag for databricks vm
  pkg/apis/metadata.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/syncutils.go
  pkg/multicloud/azure/instance.go
Labels: size/M

#10980 Automated cherry pick of #10979: fix for creating proxy endpoint
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/sshkeys/handler.go
  pkg/mcclient/models/base.go
Labels: size/XS

#10984 Automated cherry pick of #10983: fix(monitor): monitor query : cloudaccount no data fix
  pkg/monitor/alerting/conditions/query.go
Labels: size/XS

#11000 fix(region): wire sql fix
  pkg/compute/models/wires.go
Labels: area/region, size/XS

#11001 Automated cherry pick of #11000: fix(region): wire sql fix
  pkg/compute/models/wires.go
Labels: size/XS

#11002 Automated cherry pick of #11000: fix(region): wire sql fix
  pkg/compute/models/wires.go
Labels: size/XS

#11003 Automated cherry pick of #11000: fix(region): wire sql fix
  pkg/compute/models/wires.go
Labels: size/XS

#11004 Automated cherry pick of #11000: fix(region): wire sql fix
  pkg/compute/models/wires.go
Labels: size/XS

#10983 fix(monitor): monitor query : cloudaccount no data fix
  pkg/monitor/alerting/conditions/query.go
Labels: area/monitor, size/XS

#10978 feat(monitor): add agent monitor metric
  pkg/apis/monitor/metric.go
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: area/monitor, size/M

#11008 cloudproxy: test proxy endpoint connectivity and remote config
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/cloudproxy/models/proxy_endpoints_remote_check_make.go
Labels: approved, size/L

#11009 Automated cherry pick of #11008: cloudproxy: test proxy endpoint connectivity and remote config
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/cloudproxy/models/proxy_endpoints_remote_check_make.go
Labels: approved, size/L

#11005 fix(monitor): alertpanel update don't chcek uniq name
  pkg/monitor/models/alertpannel.go
Labels: area/monitor, size/XS

#11007 Automated cherry pick of #11005: fix(monitor): alertpanel update don't chcek uniq name
  pkg/monitor/models/alertpannel.go
Labels: size/XS

#11014 Automated cherry pick of #11013: fix: missing yunionconf log
  pkg/util/logclient/logclient.go
  pkg/yunionconf/models/parameters.go
Labels: approved, size/S

#11015 Automated cherry pick of #11013: fix: missing yunionconf log
  pkg/util/logclient/logclient.go
  pkg/yunionconf/models/parameters.go
Labels: approved, size/S

#11016 fix: init cloud shell by apigateway
  build/climc/root/root/.bashrc
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
  build/docker/Makefile
  cmd/climc/shell/compute/webconsole.go
  pkg/apigateway/handler/init.go
  pkg/apis/webconsole/k8s.go
  pkg/mcclient/modules/webconsole/doc.go
  pkg/mcclient/modules/webconsole/mod_webconsole.go
  pkg/webconsole/command/kube_command.go
  pkg/webconsole/handlers.go
Labels: approved, size/L

#11017 Automated cherry pick of #11016: fix: init cloud shell by apigateway
  build/climc/root/root/.bashrc
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
  build/docker/Makefile
  cmd/climc/shell/compute/webconsole.go
  pkg/apigateway/handler/init.go
  pkg/apis/webconsole/k8s.go
  pkg/mcclient/modules/webconsole/doc.go
  pkg/mcclient/modules/webconsole/mod_webconsole.go
  pkg/webconsole/command/kube_command.go
  pkg/webconsole/handlers.go
Labels: approved, size/L

#10998 Automated cherry pick of #10996: fix(region): continue to sync the snapshots that are being created when syncing auto created snapshot
  pkg/compute/models/disks.go
Labels: size/S

#10999 Automated cherry pick of #10996: fix(region): continue to sync the snapshots that are being created when syncing auto created snapshot
  pkg/compute/models/disks.go
Labels: size/S

#11011 fix(cloudproxy): correct fetch projectId from server for PE
  pkg/cloudproxy/models/server_util.go
Labels: area/cloudproxy, size/XS

#11012 Automated cherry pick of #11011: fix(cloudproxy): correct fetch projectId from server for PE
  pkg/cloudproxy/models/server_util.go
Labels: size/XS

#11027 fix for installing agent for vm
  pkg/cloudproxy/models/forwards.go
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: approved, area/cloudproxy, area/devtool, lgtm, size/S

#11028 Automated cherry pick of #11027: fix for install agent for vm
  pkg/cloudproxy/models/forwards.go
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: approved, lgtm, size/S

#11021 Automated cherry pick of #11010: fix(region): support project mapping
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/compute/project_mappings.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/project_mappings.go
  pkg/apis/input.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/project_mapping_resource.go
  pkg/compute/models/project_mappings.go
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/mod_project_mappings.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/compute/project_mappings.go
Labels: size/XL

#11041 fix: resolve conflict of climc docker build
  build/climc/root/opt/yunion/scripts/motd/climc.sh
  build/docker/Dockerfile.climc
Labels: approved, size/XS

#11042 Automated cherry pick of #11041: fix: resolve conflict of climc docker build
  build/climc/root/opt/yunion/scripts/motd/climc.sh
  build/docker/Dockerfile.climc
Labels: approved, size/XS

#11036 fix(region): aliyun nas endpoint
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
Labels: area/region, size/M

#11037 Automated cherry pick of #11036: fix(region): aliyun nas endpoint
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
Labels: size/M

#11038 fix(region): add context for syncCloudproviderRegions
  pkg/appctx/context.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
Labels: area/region, lgtm, size/S

#11030 fix(region): add RequestRemoteUpdate for ESXiGuestDriver
  pkg/compute/guestdrivers/esxi.go
Labels: area/region, size/XS

#11031 Automated cherry pick of #11030: fix(region): add RequestRemoteUpdate for ESXiGuestDriver
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS

#11043 maintain compatibility with previous webhooks
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: area/region, size/XS

#11044 Automated cherry pick of #11043: maintain compatibility with previous webhooks
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/XS

#11045 fix(baremetal): register baremetal name invalid
  pkg/baremetal/tasks/bm_register.go
Labels: approved, size/XS

#11046 Automated cherry pick of #11045: fix(baremetal): register baremetal name invalid
  pkg/baremetal/tasks/bm_register.go
Labels: approved, size/XS

#11047 Automated cherry pick of #11045: fix(baremetal): register baremetal name invalid
  pkg/baremetal/tasks/bm_register.go
Labels: approved, size/XS

#11048 fix(glance): set fail status when upload image to s3
  pkg/apis/image/consts.go
  pkg/image/models/image_subs.go
  pkg/image/models/storage.go
  pkg/image/tasks/image_convert_task.go
Labels: approved, area/image, size/M

#11049 Automated cherry pick of #11048: fix(glance): set fail status when upload image to s3
  pkg/apis/image/consts.go
  pkg/image/models/image_subs.go
  pkg/image/models/storage.go
  pkg/image/tasks/image_convert_task.go
Labels: approved, size/M

#11051 Automated cherry pick of #11050: fix(ansibleserver): correct playbook path and role path
  pkg/util/ansiblev2/playbook_session.go
Labels: size/XS

#11050 fix(ansibleserver): correct playbook path and role path
  pkg/util/ansiblev2/playbook_session.go
Labels: approved, area/ansible, lgtm, size/XS

#11095 fix(region): use the previous method for guest notification instead of message subscription
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: area/region, size/M

#11096 Automated cherry pick of #11095: fix(region): use the previous method for guest notification instead of message subscription
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/M

#11053 fix(region): optimized sku sched clear
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: area/region, size/S

#11054 Automated cherry pick of #11053: fix(region): optimized sku sched clear
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: size/S

#11055 Automated cherry pick of #11053: fix(region): optimized sku sched clear
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: size/S

#11056 Automated cherry pick of #11053: fix(region): optimized sku sched clear
  pkg/compute/models/cloudsync.go
  pkg/compute/models/skus.go
  pkg/compute/models/skus_tools.go
Labels: size/S

#11032 fix(region): aliyun vpc endpoint
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/vpc.go
Labels: area/region, size/M

#11033 Automated cherry pick of #11032: fix(region): aliyun vpc endpoint
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/vpc.go
Labels: size/M

#11034 Automated cherry pick of #11032: fix(region): aliyun vpc endpoint
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/vpc.go
Labels: size/M

#11035 Automated cherry pick of #11032: fix(region): aliyun vpc endpoint
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/vpc.go
Labels: size/M

#11097 fix(region): allow update sku status
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
Labels: area/region, size/S

#11098 Automated cherry pick of #11097: fix(region): allow update sku status
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
Labels: size/S

#11099 Automated cherry pick of #11097: fix(region): allow update sku status
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
Labels: size/S

#11100 Automated cherry pick of #11097: fix(region): allow update sku status
  pkg/apis/compute/serversku.go
  pkg/compute/models/skus.go
Labels: size/S

#11094 fix(region): remove snapshots checking for huawei cloud while delete …
  pkg/compute/models/guests.go
Labels: area/region, size/S

#11112 fix(region): aws sync disk missing image id fix
  pkg/multicloud/aws/disk.go
Labels: area/region, size/XS

#11113 Automated cherry pick of #11112: fix(region): aws sync disk missing image id fix
  pkg/multicloud/aws/disk.go
Labels: size/XS

#11114 Automated cherry pick of #11112: fix(region): aws sync disk missing image id fix
  pkg/multicloud/aws/disk.go
Labels: size/XS

#11123 fix(region): project mapping optional
  pkg/compute/models/project_mapping_resource.go
Labels: approved, area/region, lgtm, size/XS

#11124 Automated cherry pick of #11123: fix(region): project mapping optional
  pkg/compute/models/project_mapping_resource.go
Labels: approved, lgtm, size/XS

#11121 fix(esxiagent): execute deploy operation by default in AgentDeployGuest
  pkg/hostman/storageman/storage_agent.go
Labels: area/esxiagent, size/XS

#11122 Automated cherry pick of #11121: fix(esxiagent): execute deploy operation by default in AgentDeployGuest
  pkg/hostman/storageman/storage_agent.go
Labels: size/XS

#11125 Automated cherry pick of #11121: fix(esxiagent): execute deploy operation by default in AgentDeployGuest
  pkg/hostman/storageman/storage_agent.go
Labels: size/XS

#11107 fix(esxiagent): make the copied disk type as thin
  pkg/multicloud/esxi/host.go
Labels: area/esxiagent, size/S

#11108 Automated cherry pick of #11107: fix(esxiagent): make the copied disk type as thin
  pkg/multicloud/esxi/host.go
Labels: size/S

#11109 Automated cherry pick of #11107: fix(esxiagent): make the copied disk type as thin
  pkg/multicloud/esxi/host.go
Labels: size/S

#11110 Automated cherry pick of #11107: fix(esxiagent): make the copied disk type as thin
  pkg/multicloud/esxi/host.go
Labels: size/S

#11116 webhook fix
  pkg/compute/tasks/dbinstance_create_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/loadbalancer_create_task.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
Labels: area/region, size/XS

#11118 Automated cherry pick of #11116: webhook fix
  pkg/compute/tasks/dbinstance_create_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/loadbalancer_create_task.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
Labels: size/XS

#11119 Automated cherry pick of #11116: webhook fix
  pkg/compute/tasks/dbinstance_create_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/loadbalancer_create_task.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
Labels: size/XS

#11120 Automated cherry pick of #11116: webhook fix
  pkg/compute/tasks/dbinstance_create_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/loadbalancer_create_task.go
  pkg/compute/tasks/loadbalancer_listener_create_task.go
Labels: size/XS

#11101 fix(region): optimized server sku sku
  pkg/compute/models/skus_tools.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: area/region, size/M

#11102 Automated cherry pick of #11101: fix(region): optimized server sku sku
  pkg/compute/models/skus_tools.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/M

#11103 Automated cherry pick of #11101: fix(region): optimized server sku sku
  pkg/compute/models/skus_tools.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/M

#11104 Automated cherry pick of #11101: fix(region): optimized server sku sku
  pkg/compute/models/skus_tools.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/M

#11052 fix(region): optimzed guest disks
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
Labels: area/region, size/L

#11130 fix(docs): update swagger api
  README.md
  pkg/apis/cloudevent/zz_generated.model.go
  pkg/apis/cloudid/zz_generated.model.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/apis/zz_generated.model.go
Labels: size/L

#11127 Automated cherry pick of #11126: fix(region): check whether the disks of the instance snapshot is empty when creating vm
  pkg/compute/models/guests.go
Labels: size/XS

#11128 Automated cherry pick of #11126: fix(region): check whether the disks of the instance snapshot is empty when creating vm
  pkg/compute/models/guests.go
Labels: size/XS

#11129 Automated cherry pick of #11126: fix(region): check whether the disks of the instance snapshot is empty when creating vm
  pkg/compute/models/guests.go
Labels: size/XS

#11126 fix(region): check whether the disks of the instance snapshot is empty when creating vm
  pkg/compute/models/guests.go
Labels: area/region, size/XS

#11134 fix(cloudid): clouduser use default domain
  pkg/multicloud/azure/clouduser.go
Labels: area/cloudid, size/M

#11135 Automated cherry pick of #11134: fix(cloudid): clouduser use default domain
  pkg/multicloud/azure/clouduser.go
Labels: size/M

#11136 Automated cherry pick of #11134: fix(cloudid): clouduser use default domain
  pkg/multicloud/azure/clouduser.go
Labels: size/M

#11137 Automated cherry pick of #11134: fix(cloudid): clouduser use default domain
  pkg/multicloud/azure/clouduser.go
Labels: size/M

#11142 fix(glance): make image is_standard updatable
  pkg/image/models/images.go
Labels: approved, size/XS

#11143 Automated cherry pick of #11142: fix(glance): make image is_standard updatable
  pkg/image/models/images.go
Labels: approved, size/XS

#11144 Automated cherry pick of #11142: fix(glance): make image is_standard updatable
  pkg/image/models/images.go
Labels: approved, size/XS

#11139 fix(region): ctyun delete secgroup fix
  pkg/multicloud/ctyun/region.go
Labels: area/region, size/XS

#11140 Automated cherry pick of #11139: fix(region): ctyun delete secgroup fix
  pkg/multicloud/ctyun/region.go
Labels: size/XS

#11141 Automated cherry pick of #11139: fix(region): ctyun delete secgroup fix
  pkg/multicloud/ctyun/region.go
Labels: size/XS

#11145 Automated cherry pick of #10586: fix: secgroup cache policy
  pkg/compute/models/secgroupcache.go
Labels: size/S

#11146 fix(region): more accounts details for project mapping
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/project_mappings.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/project_mappings.go
  pkg/mcclient/modules/mod_project_mappings.go
Labels: area/region, size/M

#11147 Automated cherry pick of #11146: fix(region): more accounts details for project mapping
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/project_mappings.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/project_mappings.go
  pkg/mcclient/modules/mod_project_mappings.go
Labels: size/M

#11148 feat(ansible): add rolePublic and timeout options
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
  pkg/ansibleserver/options/options.go
  pkg/util/ansiblev2/playbook_session.go
  pkg/util/ansiblev2/session.go
Labels: area/ansible, size/M

#11149 Automated cherry pick of #11148: feat(ansible): add rolePublic and timeout options
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
  pkg/ansibleserver/options/options.go
  pkg/util/ansiblev2/playbook_session.go
  pkg/util/ansiblev2/session.go
Labels: size/M

#11150 feat(ansible): add rolePublic and timeout options
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
  pkg/ansibleserver/options/options.go
  pkg/util/ansiblev2/session.go
Labels: area/ansible, size/S

#11151 Automated cherry pick of #11150: feat(ansible): add rolePublic and timeout options
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
  pkg/ansibleserver/options/options.go
  pkg/util/ansiblev2/session.go
Labels: size/S

#11158 fix(readme): remove deadlinks
  CONTRIBUTING.md
  README-CN.md
  README.md
Labels: approved, size/S

#11153 Automated cherry pick of #11152: fix(region): avoid index out of range panic
  pkg/compute/models/project_mappings.go
Labels: size/S

#11154 fix(region): avoid azure secgroup sync removed
  pkg/multicloud/azure/classic_vpc.go
Labels: area/region, size/S

#11155 Automated cherry pick of #11154: fix(region): avoid azure secgroup sync removed
  pkg/multicloud/azure/classic_vpc.go
Labels: size/S

#11156 Automated cherry pick of #11154: fix(region): avoid azure secgroup sync removed
  pkg/multicloud/azure/classic_vpc.go
Labels: size/S

#11157 Automated cherry pick of #11154: fix(region): avoid azure secgroup sync removed
  pkg/multicloud/azure/classic_vpc.go
Labels: size/S

#11159 feat(github): update github PR and issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  README.md
Labels: approved, size/S

#11161 Automated cherry pick of #11160: fix(region): check sku request error
  pkg/compute/models/skus_tools.go
Labels: size/XS

#11162 Automated cherry pick of #11160: fix(region): check sku request error
  pkg/compute/models/skus_tools.go
Labels: size/XS

#11163 Automated cherry pick of #11160: fix(region): check sku request error
  pkg/compute/models/skus_tools.go
Labels: size/XS

#11025 feat(monitor): add storage monitor metric
  pkg/apis/monitor/alertquery_const.go
  pkg/apis/monitor/metric.go
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: area/monitor, size/M

#11092 Automated cherry pick of #11025: feat(monitor): add storage monitor metric
  pkg/apis/monitor/alertquery_const.go
  pkg/apis/monitor/metric.go
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/M

#11093 Automated cherry pick of #11025: feat(monitor): add storage monitor metric
  pkg/apis/monitor/alertquery_const.go
  pkg/apis/monitor/metric.go
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/M

#11026 Automated cherry pick of #11025: feat(monitor): add storage monitor metric
  pkg/apis/monitor/metric.go
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/M

#11172 fix(monitor): fix storage tag
  pkg/apis/monitor/alertquery_const.go
Labels: area/monitor, size/XS

#11173 Automated cherry pick of #11172: fix(monitor): fix storage tag
  pkg/apis/monitor/alertquery_const.go
Labels: size/XS

#11174 Automated cherry pick of #11172: fix(monitor): fix storage tag
  pkg/apis/monitor/alertquery_const.go
Labels: size/XS

#11170 fix(region): avoid aws session not assume role
  pkg/multicloud/aws/aws.go
Labels: area/region, size/S

#11171 Automated cherry pick of #11170: fix(region): avoid aws session not assume role
  pkg/multicloud/aws/aws.go
Labels: size/S

#11168 fix(region): add host_id options for storage filter
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/mcclient/options/compute/storage.go
Labels: area/region, size/XS

#11169 Automated cherry pick of #11168: fix(region): add host_id options for storage filter
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/mcclient/options/compute/storage.go
Labels: size/XS

#11180 fix(region): avoid only query one guest disk
  pkg/compute/models/guest_queries.go
Labels: area/region, size/XS

#11181 Automated cherry pick of #11177: feat(region): loadbalancer certificate add purge methods
  pkg/apis/compute/loadbalancercertificate.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/purge.go
Labels: size/M

#11178 fix(region): add project and domain info for project mapping rules
  cmd/climc/shell/compute/project_mappings.go
  pkg/apis/compute/project_mappings.go
  pkg/compute/models/project_mappings.go
Labels: area/region, size/L

#11182 fix(monitor): 3.5 monitor query throw err when select domain or project
  pkg/monitor/models/unifiedmonitor.go
Labels: area/monitor, size/M

#11179 Automated cherry pick of #11178: fix(region): add project and domain info for project mapping rules
  cmd/climc/shell/compute/project_mappings.go
  pkg/apis/compute/project_mappings.go
  pkg/compute/models/project_mappings.go
Labels: size/L

#11191 fix(region): azure uniform tags
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/dbinstance.go
  pkg/multicloud/azure/disk.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/azure/vpc.go
Labels: area/region, size/M

#11192 Automated cherry pick of #11191: fix(region): azure uniform tags
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/classic_secruitygroup.go
  pkg/multicloud/azure/dbinstance.go
  pkg/multicloud/azure/disk.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/securitygroup.go
  pkg/multicloud/azure/storageaccount.go
  pkg/multicloud/azure/vpc.go
Labels: size/M

#11198 fix(region): restrict account project mapping
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
Labels: area/region, size/XS

#11199 Automated cherry pick of #11198: fix(region): restrict account project mapping
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#11196 fix(cloudid): avoid location missing api-version
  pkg/multicloud/azure/azure.go
Labels: area/cloudid, size/S

#11197 Automated cherry pick of #11196: fix(cloudid): avoid location missing api-version
  pkg/multicloud/azure/azure.go
Labels: size/S

#11166 feat(region): add server migration predication API
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/mcclient/options/servers.go
Labels: approved, size/L

#11211 Automated cherry pick of #11166: feat(region): add server migration predication API
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/mcclient/options/servers.go
Labels: approved, size/L

#11212 fix(region): aws vpc network eip disk tags sync
  pkg/compute/models/elasticips.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/network.go
  pkg/multicloud/aws/shell/vpc.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
Labels: area/region, size/L

#11213 Automated cherry pick of #11212: fix(region): aws vpc network eip disk tags sync
  pkg/compute/models/elasticips.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/shell/network.go
  pkg/multicloud/aws/shell/vpc.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
Labels: size/L

#11201 fix(region): show azure deploy failed error
  pkg/multicloud/azure/instance.go
Labels: area/region, size/XS

#11202 Automated cherry pick of #11201: fix(region): show azure deploy failed error
  pkg/multicloud/azure/instance.go
Labels: size/XS

#11203 Automated cherry pick of #11201: fix(region): show azure deploy failed error
  pkg/multicloud/azure/instance.go
Labels: size/XS

#11204 Automated cherry pick of #11201: fix(region): show azure deploy failed error
  pkg/multicloud/azure/instance.go
Labels: size/XS
