Repository yunionio/cloudpods, pull requests merged in 2021-04, with the labels that each got.

#10573 fix: avoid update protocol with any faild
  pkg/compute/models/secgrouprules.go
Labels: area/region, size/XS

#10574 Automated cherry pick of #10573: fix: avoid update protocol with any faild
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#10565 fix(esxi): be compatible with disconnected host
  pkg/multicloud/esxi/net_topology_pro.go
Labels: area/region, size/XS

#10566 Automated cherry pick of #10565: fix(esxi): be compatible with disconnected host
  pkg/multicloud/esxi/net_topology_pro.go
Labels: size/XS

#10567 Automated cherry pick of #10565: fix(esxi): be compatible with disconnected host
  pkg/multicloud/esxi/network.go
Labels: size/XS

#10572 Automated cherry pick of #10565: fix(esxi): be compatible with disconnected host
  pkg/multicloud/esxi/network.go
Labels: size/XS

#10561 fix: vendor update
  go.mod
  go.sum
  pkg/multicloud/qcloud/bucket.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/CHANGELOG.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/README.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/batch.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_accelerate.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_lifecycle.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_doc.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_media.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/cos.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/helper.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_part.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_select.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/progress.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: area/region, size/XXL

#10562 Automated cherry pick of #10561: fix: vendor update
  go.mod
  go.sum
  pkg/multicloud/qcloud/bucket.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/CHANGELOG.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/README.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/batch.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_accelerate.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_lifecycle.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_doc.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_media.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/cos.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/helper.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_part.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_select.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/progress.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XXL

#10563 Automated cherry pick of #10561: fix: vendor update
  go.mod
  go.sum
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/multicloud/qcloud/bucket.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/CHANGELOG.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/README.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/batch.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_accelerate.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_lifecycle.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_doc.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_media.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/cos.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/helper.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_part.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_select.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/progress.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/compare/compare.go
  vendor/yunion.io/x/pkg/utils/fibonacci_retrier.go
  vendor/yunion.io/x/sqlchemy/README.md
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XXL

#10564 Automated cherry pick of #10561: fix: vendor update
  go.mod
  go.sum
  pkg/multicloud/qcloud/bucket.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/CHANGELOG.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/README.md
  vendor/github.com/tencentyun/cos-go-sdk-v5/batch.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_accelerate.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/bucket_lifecycle.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_doc.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/ci_media.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/cos.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/helper.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_part.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/object_select.go
  vendor/github.com/tencentyun/cos-go-sdk-v5/progress.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/api/doc.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/register.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/v1/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/api/v1/doc.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/v1/register.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/v1/types.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/well_known_labels.go
  vendor/k8s.io/kubernetes/pkg/scheduler/api/zz_generated.deepcopy.go
  vendor/modules.txt
  vendor/yunion.io/x/log/formatter.go
  vendor/yunion.io/x/pkg/util/compare/compare.go
  vendor/yunion.io/x/pkg/utils/fibonacci_retrier.go
  vendor/yunion.io/x/sqlchemy/README.md
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/sql.go
  vendor/yunion.io/x/sqlchemy/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XXL

#10557 fix: cloudaccount auto sync
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/options/options.go
Labels: area/region, size/M

#10558 Automated cherry pick of #10557: fix: cloudaccount auto sync
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/options/options.go
Labels: size/M

#10559 Automated cherry pick of #10557: fix: cloudaccount auto sync
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/options/options.go
Labels: size/M

#10560 Automated cherry pick of #10557: fix: cloudaccount auto sync
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/options/options.go
Labels: size/M

#10555 fix: nat sku domain policy
  pkg/compute/policy/defaults.go
Labels: area/region, size/S

#10556 Automated cherry pick of #10555: fix: nat sku domain policy
  pkg/compute/policy/defaults.go
Labels: size/S

#10552 fix(monitor):修复监控总览图标钻取后返回数据异常的问题
  pkg/monitor/alerting/conditions/query.go
Labels: area/monitor, size/XS

#10553 Automated cherry pick of #10552: fix(monitor):修复监控总览图标钻取后返回数据异常的问题
  pkg/monitor/alerting/conditions/query.go
Labels: size/XS

#10554 Automated cherry pick of #10552: fix(monitor):修复监控总览图标钻取后返回数据异常的问题
  pkg/monitor/alerting/conditions/query.go
Labels: size/XS

#10549 fix(image): update min_disk of iso image
  pkg/image/models/images.go
Labels: size/S

#10550 Automated cherry pick of #10549: fix(image): update min_disk of iso image
  pkg/image/models/images.go
Labels: size/S

#10551 Automated cherry pick of #10549: fix(image): update min_disk of iso image
  pkg/image/models/images.go
Labels: size/S

#10546 fix(host): arm vm virtio-net-pci without addr
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: area/host, size/S

#10547 Automated cherry pick of #10546: fix(host): arm vm virtio-net-pci without addr
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#10548 Automated cherry pick of #10546: fix(host): arm vm virtio-net-pci without addr
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#10482 fix: before insert
  go.mod
  go.sum
  pkg/apis/output.go
  pkg/cloudcommon/db/external.go
  pkg/cloudid/models/clouduser.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/insert.go
Labels: approved, area/region, lgtm, size/M

#10575 Automated cherry pick of #10482: fix: before insert
  go.mod
  go.sum
  pkg/apis/output.go
  pkg/cloudcommon/db/external.go
  pkg/cloudid/models/clouduser.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/insert.go
Labels: approved, lgtm, size/M

#10568 fix: avoid listener worker leak
  pkg/mcclient/catalog.go
  pkg/mcclient/mcclient.go
Labels: approved, area/region, lgtm, size/S

#10571 Automated cherry pick of #10568: fix: avoid listener worker leak
  pkg/mcclient/catalog.go
  pkg/mcclient/mcclient.go
Labels: approved, lgtm, size/S

#10570 Automated cherry pick of #10568: fix: avoid listener worker leak
  pkg/mcclient/catalog.go
  pkg/mcclient/mcclient.go
Labels: approved, lgtm, size/S

#10569 Automated cherry pick of #10568: fix: avoid listener worker leak
  pkg/mcclient/catalog.go
  pkg/mcclient/mcclient.go
Labels: approved, lgtm, size/S

#7047 fix: adjust primary key length when sqlchemy utf8 default to utf8mb4
  pkg/keystone/models/configs.go
  pkg/keystone/models/nonlocal_users.go
Labels: area/image, area/keystone, area/region, size/XS

#10588 Automated cherry pick of #7047: fix: adjust primary key length when sqlchemy utf8 default to utf8mb4
  pkg/keystone/models/configs.go
  pkg/keystone/models/nonlocal_users.go
Labels: size/XS

#10589 Automated cherry pick of #7047: fix: adjust primary key length when sqlchemy utf8 default to utf8mb4
  pkg/keystone/models/configs.go
  pkg/keystone/models/nonlocal_users.go
Labels: size/XS

#10595 Fixes problem of Esxi Disk with iso creating
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/hostman/storageman/storage_agent.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: area/esxiagent, area/region, size/XL

#10596 Automated cherry pick of #10595: Fixes problem of Esxi Disk with iso creating
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/hostman/storageman/storage_agent.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/XL

#10598 Automated cherry pick of #10595: Fixes problem of Esxi Disk with iso creating
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/hostman/storageman/storage_agent.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/storage.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/XL

#10581 fix(hostman): recycle local disk file when rebuilding root
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_local.go
Labels: area/host, size/S

#10582 Automated cherry pick of #10581: fix(hostman): recycle local disk file when rebuilding root
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#10583 Automated cherry pick of #10581: fix(hostman): recycle local disk file when rebuilding root
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#10584 Automated cherry pick of #10581: fix(hostman): recycle local disk file when rebuilding root
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#10585 Automated cherry pick of #10581: fix(hostman): recycle local disk file when rebuilding root
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#10576 fix(region): allow ipmi probe when probe fail
  pkg/compute/models/hosts.go
Labels: area/region, size/XS

#10579 Automated cherry pick of #10576: fix(region): allow ipmi probe when probe fail
  pkg/compute/models/hosts.go
Labels: size/XS

#10580 Automated cherry pick of #10576: fix(region): allow ipmi probe when probe fail
  pkg/compute/models/hosts.go
Labels: size/XS

#10603 fix(baremetal): sas2iru parse line
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
Labels: area/baremetal, size/XS

#10604 Automated cherry pick of #10603: fix(baremetal): sas2iru parse line
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
Labels: size/XS

#10605 Automated cherry pick of #10603: fix(baremetal): sas2iru parse line
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
Labels: size/XS

#10606 Automated cherry pick of #10603: fix(baremetal): sas2iru parse line
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
Labels: size/XS

#10607 Automated cherry pick of #10603: fix(baremetal): sas2iru parse line
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
Labels: size/XS

#10601 Fix the problem of hostwire producted by #9723
  pkg/compute/models/hostwires.go
  pkg/compute/models/wires.go
Labels: area/region, size/XS

#10602 Automated cherry pick of #10601: Fix the problem of hostwire producted by #9723
  pkg/compute/models/hostwires.go
  pkg/compute/models/wires.go
Labels: size/XS

#10608 fix: time sync duration
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
Labels: approved, area/region, lgtm, size/XS

#10609 Automated cherry pick of #10608: fix: time sync duration
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
Labels: approved, lgtm, size/XS

#10611 Automated cherry pick of #10608: fix: time sync duration
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
Labels: approved, lgtm, size/XS

#10610 Automated cherry pick of #10608: fix: time sync duration
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
Labels: approved, lgtm, size/XS

#10616 fix(region): new aws region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
Labels: approved, area/region, lgtm, size/S

#10618 Automated cherry pick of #10616: fix(region): new aws region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
Labels: approved, lgtm, size/S

#10617 Automated cherry pick of #10616: fix(region): new aws region
  pkg/apis/compute/cloudregions_const.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
Labels: approved, lgtm, size/S

#10612 fix(region): add usage cache, speedup response
  cmd/climc/shell/compute/usages.go
  pkg/compute/usages/cache.go
  pkg/compute/usages/handler.go
Labels: area/region, size/L

#10613 Automated cherry pick of #10612: fix(region): add usage cache, speedup response
  cmd/climc/shell/compute/usages.go
  pkg/compute/usages/cache.go
  pkg/compute/usages/handler.go
Labels: size/L

#10614 Automated cherry pick of #10612: fix(region): add usage cache, speedup response
  cmd/climc/shell/compute/usages.go
  pkg/compute/usages/cache.go
  pkg/compute/usages/handler.go
Labels: size/L

#10615 Automated cherry pick of #10612: fix(region): add usage cache, speedup response
  cmd/climc/shell/compute/usages.go
  pkg/compute/usages/cache.go
  pkg/compute/usages/handler.go
Labels: size/L

#10627 feature: add a standalone dhcp relay service
  build/dhcprelay/root/etc/sysconfig/yunion_dhcprelay
  build/dhcprelay/root/usr/lib/systemd/system/yunion-dhcprelay.service
  build/dhcprelay/vars
  cmd/dhcprelay/main.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: area/util, size/L

#10628 Automated cherry pick of #10627: feature: add a standalone dhcp relay service
  build/dhcprelay/root/etc/sysconfig/yunion_dhcprelay
  build/dhcprelay/root/usr/lib/systemd/system/yunion-dhcprelay.service
  build/dhcprelay/vars
  cmd/dhcprelay/main.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/L

#10622 fix(keystone): role_assignment effective list ignore groups without user
  pkg/keystone/models/assignments.go
Labels: area/keystone, size/XS

#10623 Automated cherry pick of #10622: fix(keystone): role_assignment effective list ignore groups without user
  pkg/keystone/models/assignments.go
Labels: size/XS

#10624 Automated cherry pick of #10622: fix(keystone): role_assignment effective list ignore groups without user
  pkg/keystone/models/assignments.go
Labels: size/XS

#10625 Automated cherry pick of #10622: fix(keystone): role_assignment effective list ignore groups without user
  pkg/keystone/models/assignments.go
Labels: size/XS

#10626 Automated cherry pick of #10622: fix(keystone): role_assignment effective list ignore groups without user
  pkg/keystone/models/assignments.go
Labels: size/XS

#10633 fix: private cloud sku attached disk count
  pkg/compute/models/skus.go
  pkg/multicloud/apsara/instancetype.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/zstack/offering.go
Labels: area/region, size/S

#10634 Automated cherry pick of #10633: fix: private cloud sku attached disk count
  pkg/compute/models/skus.go
  pkg/multicloud/apsara/instancetype.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/zstack/offering.go
Labels: size/S

#10635 Automated cherry pick of #10633: fix: private cloud sku attached disk count
  pkg/compute/models/skus.go
  pkg/multicloud/apsara/instancetype.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/zstack/offering.go
Labels: size/S

#10636 Automated cherry pick of #10633: fix: private cloud sku attached disk count
  pkg/compute/models/skus.go
  pkg/multicloud/openstack/flavor.go
  pkg/multicloud/zstack/offering.go
Labels: size/L

#10631 apigateway: handler: add cloudproxy
  pkg/apigateway/handler/init.go
Labels: area/apigateway, size/XS

#10632 Automated cherry pick of #10631: apigateway: handler: add cloudproxy
  pkg/apigateway/handler/init.go
Labels: size/XS

#10638 feat(notify): 管理后台新建的联系人，手机号和邮箱无需进行校验
  pkg/notify/models/receiver.go
Labels: area/notify, size/XS

#10639 Automated cherry pick of #10638: feat(notify): 管理后台新建的联系人，手机号和邮箱无需进行校验
  pkg/notify/models/receiver.go
Labels: size/XS

#10637 fix(region): guest associate eip checking fix
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: area/region, size/M

#10629 feat(region): virtually display the esxiagent of the cached image as a host
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecaches.go
Labels: area/region, size/M

#10630 Automated cherry pick of #10629: feat(region): virtually display the esxiagent of the cached image as a host
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecaches.go
Labels: size/M

#10599 Feature/yousong sshable
  cmd/climc/shell/compute/servers.go
  pkg/apis/cloudproxy/forwards.go
  pkg/apis/compute/guest_sshable.go
  pkg/cloudproxy/agent/ssh/client.go
  pkg/cloudproxy/agent/ssh/client_config.go
  pkg/cloudproxy/agent/ssh/clientset.go
  pkg/cloudproxy/agent/worker/worker.go
  pkg/cloudproxy/models/forwards.go
  pkg/cloudproxy/service/handlers.go
  pkg/compute/models/guest_sshable.go
  pkg/util/ssh/ssh.go
Labels: area/climc, area/region, size/XL

#10600 Automated cherry pick of #10599: Feature/yousong sshable
  cmd/climc/shell/compute/servers.go
  pkg/apis/cloudproxy/forwards.go
  pkg/apis/compute/guest_sshable.go
  pkg/cloudproxy/agent/ssh/client.go
  pkg/cloudproxy/agent/ssh/client_config.go
  pkg/cloudproxy/agent/ssh/clientset.go
  pkg/cloudproxy/agent/worker/worker.go
  pkg/cloudproxy/models/forwards.go
  pkg/cloudproxy/service/handlers.go
  pkg/compute/models/guest_sshable.go
  pkg/util/ssh/ssh.go
Labels: size/XL

#10643 Automated cherry pick of #10637: fix(region): guest associate eip checking fix
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/M

#10640 Automated cherry pick of #10637: fix(region): guest associate eip checking fix
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/M

#10641 Automated cherry pick of #10637: fix(region): guest associate eip checking fix
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/M

#10642 Automated cherry pick of #10637: fix(region): guest associate eip checking fix
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: approved, lgtm, size/M

#10647 fix(region): avoid refreshing when checking the image
  pkg/compute/models/guest_template.go
Labels: area/region, size/XS

#10648 Automated cherry pick of #10647: fix(region): avoid refreshing when checking the image
  pkg/compute/models/guest_template.go
Labels: size/XS

#10649 Automated cherry pick of #10647: fix(region): avoid refreshing when checking the image
  pkg/compute/models/guest_template.go
Labels: size/XS

#10644 fix(region): allow ipmi probe in status unknown
  pkg/compute/models/hosts.go
Labels: area/region, size/XS

#10645 Automated cherry pick of #10644: fix(region): allow ipmi probe in status unknown
  pkg/compute/models/hosts.go
Labels: size/XS

#10646 Automated cherry pick of #10644: fix(region): allow ipmi probe in status unknown
  pkg/compute/models/hosts.go
Labels: size/XS

#10652 fix(region): rigorously merge the network under wire
  pkg/compute/tasks/networks_under_wire_merge_task.go
Labels: area/region, size/S

#10653 Automated cherry pick of #10652: fix(region): rigorously merge the network under wire
  pkg/compute/tasks/networks_under_wire_merge_task.go
Labels: size/S

#10650 feat(notify): filter receivers who join the project under the domain where the requester is currently located
  pkg/apis/notify/receiver.go
  pkg/mcclient/options/notify/receiver.go
  pkg/notify/models/receiver.go
Labels: area/notify, size/M

#10651 Automated cherry pick of #10650: feat(notify): filter receivers who join the project under the domain where the requester is currently located
  pkg/apis/notify/receiver.go
  pkg/mcclient/options/notify/receiver.go
  pkg/notify/models/receiver.go
Labels: size/M

#10497 Feature/yousong vpc route
  pkg/apis/compute/routetable_routesets.go
  pkg/vpcagent/models/models.go
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/modelsets.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/routes.go
  pkg/vpcagent/ovn/worker.go
Labels: area/region, area/vpcagent, lgtm, size/L

#10498 Automated cherry pick of #10497: [rfc] Feature/yousong vpc route
  pkg/apis/compute/routetable_routesets.go
  pkg/vpcagent/models/models.go
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/modelsets.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/routes.go
  pkg/vpcagent/ovn/worker.go
Labels: size/L

#10654 fix(notify): exempt the administrator to create the receiver verification
  pkg/notify/models/receiver.go
Labels: area/notify, size/S

#10655 Automated cherry pick of #10654: fix(notify): exempt the administrator to create the receiver verification
  pkg/notify/models/receiver.go
Labels: size/S

#10656 fix: validate secgroup references
  cmd/climc/shell/compute/secgroups.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/secgroups.go
Labels: area/region, size/M

#10657 Automated cherry pick of #10656: fix: validate secgroup references
  cmd/climc/shell/compute/secgroups.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/secgroups.go
Labels: size/M

#10658 fix(region): sync baremetal desc before do ipmi probing
  pkg/baremetal/manager.go
Labels: area/baremetal, size/XS

#10659 Automated cherry pick of #10658: fix(region): sync baremetal desc before do ipmi probing
  pkg/baremetal/manager.go
Labels: size/XS

#10660 Automated cherry pick of #10658: fix(region): sync baremetal desc before do ipmi probing
  pkg/baremetal/manager.go
Labels: size/XS

#10661 Automated cherry pick of #10531: fix(region): show storage capacity to project users
  pkg/compute/models/storages.go
Labels: size/XS

#10586 fix: secgroup cache policy
  pkg/compute/models/secgroupcache.go
Labels: area/region, size/S

#10587 Automated cherry pick of #10586: fix: secgroup cache policy
  pkg/compute/models/secgroupcache.go
Labels: size/S

#10619 fix(region): remove i18n lock and logs
  pkg/cloudcommon/db/i18n.go
  pkg/compute/models/i18nresource.go
  pkg/compute/options/options.go
Labels: area/region, size/S

#10620 Automated cherry pick of #10619: fix(region): remove i18n lock and logs
  pkg/cloudcommon/db/i18n.go
  pkg/compute/models/i18nresource.go
  pkg/compute/options/options.go
Labels: size/S

#10621 Automated cherry pick of #10619: fix(region): remove i18n lock and logs
  pkg/cloudcommon/db/i18n.go
  pkg/compute/models/i18nresource.go
  pkg/compute/options/options.go
Labels: size/S

#10662 fix(region): remove code about getting service url
  pkg/compute/service/service.go
Labels: area/region, size/S

#10663 Automated cherry pick of #10662: fix(region): remove code about getting service url
  pkg/compute/service/service.go
Labels: size/S

#10664 fix: qcloud eip bandwidth
  pkg/multicloud/qcloud/eip.go
  pkg/multicloud/qcloud/instance.go
Labels: area/region, size/M

#10665 Automated cherry pick of #10664: fix: qcloud eip bandwidth
  pkg/multicloud/qcloud/eip.go
  pkg/multicloud/qcloud/instance.go
Labels: size/M

#10592 fix(host): update host metric tags when server or host changeowner
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/host_sync_task.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: area/host, size/L

#10593 Automated cherry pick of #10592: fix(host): update host metric tags when server or host changeowner
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/host_sync_task.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#10594 Automated cherry pick of #10592: fix(host): update host metric tags when server or host changeowner
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/host_sync_task.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#10673 fix: optimized aliyun error
  pkg/multicloud/aliyun/aliyun.go
Labels: area/region, size/M

#10674 Automated cherry pick of #10673: fix: optimized aliyun error
  pkg/multicloud/aliyun/aliyun.go
Labels: size/M

#10675 fix: add trans info
  locales/locales.go
  locales/zh-CN/messages.gotext.json
Labels: area/region, size/XXL

#10676 Automated cherry pick of #10675: fix: add trans info
  locales/locales.go
  locales/zh-CN/messages.gotext.json
Labels: size/XXL

#10667 feat(notify): exempt the administrator to update the receiver verification
  pkg/notify/models/receiver.go
Labels: area/notify, size/S

#10668 Automated cherry pick of #10667: feat(notify): exempt the administrator to update the receiver verification
  pkg/notify/models/receiver.go
Labels: size/S

#10678 fix(host): detect ovs version
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, area/host, size/XS

#10679 Automated cherry pick of #10678: fix(host): detect ovs version
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, size/XS

#10680 Automated cherry pick of #10678: fix(host): detect ovs version
  pkg/hostman/hostinfo/hostinfo.go
Labels: approved, size/XS

#10681 fix: nas for huawei
  pkg/compute/models/cloudsync.go
  pkg/compute/models/filesystem.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/tasks/filesystem_create_task.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_sfs.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/sfs-turbo.go
  pkg/multicloud/huawei/shell/filesystem.go
Labels: area/region, size/L

#10682 Automated cherry pick of #10681: fix: nas for huawei
  pkg/compute/models/cloudsync.go
  pkg/compute/models/filesystem.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/tasks/filesystem_create_task.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/manager_resource.go
  pkg/multicloud/huawei/client/modules/mod_sfs.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/sfs-turbo.go
  pkg/multicloud/huawei/shell/filesystem.go
Labels: size/L

#10683 fix(baremetal-agent): baremetal will probe status in status unknown
  pkg/baremetal/cronjobs.go
Labels: approved, size/XS

#10684 Automated cherry pick of #10683: fix(baremetal-agent): baremetal will probe status in status unknown
  pkg/baremetal/cronjobs.go
Labels: approved, size/XS

#10686 Automated cherry pick of #10683: fix(baremetal-agent): baremetal will probe status in status unknown
  pkg/baremetal/cronjobs.go
Labels: approved, size/XS

#10687 Automated cherry pick of #10683: fix(baremetal-agent): baremetal will probe status in status unknown
  pkg/baremetal/cronjobs.go
Labels: approved, size/XS

#10692 fix(readme): rename OneCloud to YunionCloud
  README-CN.md
  README.md
Labels: approved, size/M

#10693 Automated cherry pick of #10692: fix(readme): rename OneCloud to YunionCloud
  README-CN.md
  README.md
Labels: approved, size/M

#10694 Automated cherry pick of #10692: fix(readme): rename OneCloud to YunionCloud
  README-CN.md
  README.md
Labels: approved, size/M

#10685 Automated cherry pick of #10683: fix(baremetal-agent): baremetal will probe status in status unknown
  pkg/baremetal/cronjobs.go
Labels: approved, size/XS

#10688 fix: actions domain filter by project doamin id
  pkg/cloudcommon/db/opslog.go
Labels: area/region, size/XS

#10689 Automated cherry pick of #10688: fix: actions domain filter by project doamin id
  pkg/cloudcommon/db/opslog.go
Labels: size/XS

#10690 Automated cherry pick of #10688: fix: actions domain filter by project doamin id
  pkg/cloudcommon/db/opslog.go
Labels: size/XS

#10691 Automated cherry pick of #10688: fix: actions domain filter by project doamin id
  pkg/cloudcommon/db/opslog.go
Labels: size/XS

#10671 fix(monitor): alertPanel add dumplicate name check
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/alertpannel.go
Labels: area/monitor, size/M

#10672 Automated cherry pick of #10671: fix(monitor): alertPanel add dumplicate name check
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/alertpannel.go
Labels: size/M

#10699 feat(fetcherfs): make rpm and deb package
  Makefile
  build/convert_rpm2deb.sh
  build/docker/Dockerfile.debian-base
  build/docker/Makefile
Labels: approved, area/util, size/M

#10700 Automated cherry pick of #10699: feat(fetcherfs): make rpm and deb package
  Makefile
  build/convert_rpm2deb.sh
  build/docker/Dockerfile.debian-base
  build/docker/Makefile
Labels: approved, size/M

#10701 Automated cherry pick of #10699: feat(fetcherfs): make rpm and deb package
  Makefile
  build/convert_rpm2deb.sh
  build/docker/Dockerfile.debian-base
  build/docker/Makefile
Labels: approved, size/M

#10695 feat(region): allow to update account with provider vmware
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/provider/provider.go
Labels: area/region, size/M

#10696 Automated cherry pick of #10695: feat(region): allow to update account with provider vmware
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/provider/provider.go
Labels: size/M

#10698 Automated cherry pick of #10695: feat(region): allow to update account with provider vmware
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/provider/provider.go
Labels: size/M
