Repository yunionio/cloudpods, pull requests merged in 2021-09, with the labels that each got.

#12083 fix: add ceph-common to climc image, so as to make rbcli work
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
Labels: approved, size/XS

#12084 Automated cherry pick of #12083: fix: add ceph-common to climc image, so as to make rbcli work
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
Labels: approved, size/XS

#12085 Automated cherry pick of #12083: fix: add ceph-common to climc image, so as to make rbcli work
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
Labels: approved, size/XS

#12077 lb list api support search elastic ip
  pkg/compute/models/loadbalancers.go
Labels: size/XS, area/region

#12079 Automated cherry pick of #12077: lb list api support search elastic ip
  pkg/compute/models/loadbalancers.go
Labels: size/XS

#12078 Automated cherry pick of #12077: lb list api support search elastic ip
  pkg/compute/models/loadbalancers.go
Labels: size/XS

#12080 fix(region): access group policy
  pkg/compute/models/access_group_caches.go
  pkg/compute/policy/resources.go
Labels: size/XS, area/region

#12081 Automated cherry pick of #12080: fix(region): access group policy
  pkg/compute/models/access_group_caches.go
  pkg/compute/policy/resources.go
Labels: size/XS

#12082 Automated cherry pick of #12080: fix(region): access group policy
  pkg/compute/models/access_group_caches.go
  pkg/compute/policy/resources.go
Labels: size/XS

#12067 feat(region): allow custom sshport when make sshable
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_metadata.go
  pkg/apis/compute/guest_sshable.go
  pkg/apis/compute/guests.go
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/models/guest_sshable.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: size/M, area/region

#12070 Automated cherry pick of #12067: feat(region): allow custom sshport when make sshable
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_metadata.go
  pkg/apis/compute/guest_sshable.go
  pkg/cloudproxy/models/proxy_endpoints.go
  pkg/compute/models/guest_sshable.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: size/M

#12090 fix(climc-base): update tag to 20210901
  build/docker/Makefile
Labels: approved, size/XS, area/climc

#12092 Automated cherry pick of #12090: fix(climc-base): update tag to 20210901
  build/docker/Makefile
Labels: approved, size/XS

#12076 Automated cherry pick of #12075: fix(region): struct guest json desc
  pkg/apis/compute/cdrom.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/isolated_device.go
  pkg/apis/compute/secgroup.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/container.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestcdrom.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/host_recycle.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/netinterfaces.go
  pkg/compute/models/secgroups.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/baremetal_server_start_task.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_block_io_throttle_task.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/compute/tasks/guest_delete_on_host_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/compute/tasks/guest_detach_all_disks_task.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
  pkg/compute/tasks/host_import_libvirt_servers_task.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/XXL

#12086 fix(baremetal): reindex nic
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/guestfs/core.go
Labels: size/M, area/baremetal

#12087 Automated cherry pick of #12086: fix(baremetal): reindex nic
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/guestfs/core.go
Labels: approved, size/M

#12088 Automated cherry pick of #12086: fix(baremetal): reindex nic
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/guestfs/core.go
Labels: approved, size/M

#12089 Automated cherry pick of #12086: fix(baremetal): reindex nic
  pkg/baremetal/manager.go
  pkg/baremetal/pxe/dhcp.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/guestfs/core.go
Labels: approved, size/M

#12102 fix(host): return cache image error
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_base.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/imagecachemanager_base.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/imagecachemanager_rbd.go
  pkg/hostman/storageman/remotefile/remotefile.go
  pkg/hostman/storageman/storage_local.go
Labels: lgtm, approved, area/host

#12103 Automated cherry pick of #12102: fix(host): return cache image error
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_base.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/imagecachemanager_base.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/imagecachemanager_rbd.go
  pkg/hostman/storageman/remotefile/remotefile.go
  pkg/hostman/storageman/storage_local.go
Labels: lgtm, approved

#12106 Automated cherry pick of #12105: feat(devtool): add sshinfo and serviceurl
  cmd/climc/shell/devtool/serviceurl.go
  cmd/climc/shell/devtool/sshinfo.go
  pkg/apis/devtool/script.go
  pkg/apis/devtool/serviceurl.go
  pkg/apis/devtool/sshinfo.go
  pkg/devtool/models/service_url.go
  pkg/devtool/models/sshinfo.go
  pkg/devtool/service/handler.go
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/tasks/serviceurl_create_task.go
  pkg/devtool/tasks/sshinfo_create_task.go
  pkg/devtool/tasks/sshinfo_delete_task.go
  pkg/devtool/utils/influxdb_url.go
  pkg/devtool/utils/service_url.go
  pkg/devtool/utils/ssh.go
  pkg/mcclient/modules/mod_devtools.go
  pkg/mcclient/options/devtool/serviceurl.go
  pkg/mcclient/options/devtool/sshinfo.go
Labels: size/XXL

#12107 Automated cherry pick of #12105: feat(devtool): add sshinfo and serviceurl
  cmd/climc/shell/devtool/serviceurl.go
  cmd/climc/shell/devtool/sshinfo.go
  pkg/apis/devtool/script.go
  pkg/apis/devtool/serviceurl.go
  pkg/apis/devtool/sshinfo.go
  pkg/devtool/models/service_url.go
  pkg/devtool/models/sshinfo.go
  pkg/devtool/service/handler.go
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/tasks/serviceurl_create_task.go
  pkg/devtool/tasks/sshinfo_create_task.go
  pkg/devtool/tasks/sshinfo_delete_task.go
  pkg/devtool/utils/influxdb_url.go
  pkg/devtool/utils/service_url.go
  pkg/devtool/utils/ssh.go
  pkg/mcclient/modules/mod_devtools.go
  pkg/mcclient/options/devtool/serviceurl.go
  pkg/mcclient/options/devtool/sshinfo.go
Labels: size/XXL

#12105 feat(devtool): add sshinfo and serviceurl
  cmd/climc/shell/devtool/serviceurl.go
  cmd/climc/shell/devtool/sshinfo.go
  pkg/apis/devtool/script.go
  pkg/apis/devtool/serviceurl.go
  pkg/apis/devtool/sshinfo.go
  pkg/devtool/models/service_url.go
  pkg/devtool/models/sshinfo.go
  pkg/devtool/service/handler.go
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/tasks/serviceurl_create_task.go
  pkg/devtool/tasks/sshinfo_create_task.go
  pkg/devtool/tasks/sshinfo_delete_task.go
  pkg/devtool/utils/influxdb_url.go
  pkg/devtool/utils/service_url.go
  pkg/devtool/utils/ssh.go
  pkg/mcclient/modules/mod_devtools.go
  pkg/mcclient/options/devtool/serviceurl.go
  pkg/mcclient/options/devtool/sshinfo.go
Labels: lgtm, size/XXL, approved, area/devtool

#12112 fix(region): sku region info
  pkg/compute/models/skus.go
Labels: lgtm, approved, size/XS, area/region

#12113 Automated cherry pick of #12112: fix(region): sku region info
  pkg/compute/models/skus.go
Labels: lgtm, approved, size/XS

#12114 NetworkUsableZoneIds remove duplicate zone ids
  pkg/compute/models/skus.go
  pkg/compute/models/zones.go
Labels: size/S, area/region

#12115 Automated cherry pick of #12114: NetworkUsableZoneIds remove duplicate zone ids
  pkg/compute/models/skus.go
  pkg/compute/models/zones.go
Labels: size/S

#12116 Automated cherry pick of #12114: NetworkUsableZoneIds remove duplicate zone ids
  pkg/compute/models/skus.go
  pkg/compute/models/zones.go
Labels: size/S

#12117 fix(devtool): create serviceurl
  pkg/devtool/models/service_url.go
  pkg/devtool/utils/service_url.go
  pkg/mcclient/options/devtool/serviceurl.go
Labels: size/M, area/devtool

#12118 Automated cherry pick of #12117: fix(devtool): create serviceurl
  pkg/devtool/models/service_url.go
  pkg/devtool/utils/service_url.go
  pkg/mcclient/options/devtool/serviceurl.go
Labels: size/M

#12119 Automated cherry pick of #12117: fix(devtool): create serviceurl
  pkg/devtool/models/service_url.go
  pkg/devtool/utils/service_url.go
  pkg/mcclient/options/devtool/serviceurl.go
Labels: size/M

#12121 fix(region): apsara endpoint fix
  pkg/multicloud/apsara/provider/provider.go
Labels: size/XS, area/region

#12122 Automated cherry pick of #12121: fix(region): apsara endpoint fix
  pkg/multicloud/apsara/provider/provider.go
Labels: size/XS

#12123 Automated cherry pick of #12121: fix(region): apsara endpoint fix
  pkg/multicloud/apsara/provider/provider.go
Labels: size/XS

#12124 Automated cherry pick of #12121: fix(region): apsara endpoint fix
  pkg/multicloud/apsara/provider/provider.go
Labels: size/XS

#12130 fix(region): hcso sync server fix
  pkg/multicloud/hcso/instance.go
Labels: size/XS, area/region

#12131 Automated cherry pick of #12130: fix(region): hcso sync server fix
  pkg/multicloud/hcso/instance.go
Labels: size/XS

#12132 Automated cherry pick of #12130: fix(region): hcso sync server fix
  pkg/multicloud/hcso/instance.go
Labels: size/XS

#12134 fix(region): change disk and network drivers for Esxi converted VM
  pkg/compute/models/guest_actions.go
Labels: size/S, approved

#12135 Automated cherry pick of #12134: fix(region): change disk and network drivers for Esxi converted VM
  pkg/compute/models/guest_actions.go
Labels: size/S, approved

#12136 Automated cherry pick of #12134: fix(region): change disk and network drivers for Esxi converted VM
  pkg/compute/models/guest_actions.go
Labels: size/S, approved

#12137 Automated cherry pick of #12134: fix(region): change disk and network drivers for Esxi converted VM
  pkg/compute/models/guest_actions.go
Labels: size/S, approved

#12126 fix(region): apsara default region
  pkg/cloudprovider/endpoints.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
Labels: size/S, area/region

#12127 Automated cherry pick of #12126: fix(region): apsara default region
  pkg/cloudprovider/endpoints.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
Labels: size/S

#12128 Automated cherry pick of #12126: fix(region): apsara default region
  pkg/cloudprovider/endpoints.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
Labels: size/S

#12129 Automated cherry pick of #12126: fix(region): apsara default region
  pkg/cloudprovider/endpoints.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/provider/provider.go
Labels: size/S

#12138 Automated cherry pick of #12126: fix(region): apsara default region
  pkg/mcclient/options/cloudaccounts.go
Labels: size/XS

#12140 Automated cherry pick of #12126: fix(region): apsara default region
  pkg/mcclient/options/cloudaccounts.go
Labels: size/XS

#12139 Automated cherry pick of #12126: fix(region): apsara default region
  pkg/mcclient/options/cloudaccounts.go
Labels: size/XS

#12145 fix(region): resource apsara resource id not found error
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/storagecache.go
Labels: size/M, area/region

#12146 Automated cherry pick of #12145: fix(region): resource apsara resource id not found error
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/storagecache.go
Labels: size/M

#12148 Automated cherry pick of #12145: fix(region): resource apsara resource id not found error
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/storagecache.go
Labels: size/M

#12147 Automated cherry pick of #12145: fix(region): resource apsara resource id not found error
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/storagecache.go
Labels: size/M

#12141 fix(devtool): get tenant info via correct field
  pkg/devtool/utils/influxdb_url.go
Labels: size/XS

#12142 Automated cherry pick of #12141: fix(devtool): get tenant info via correct field
  pkg/devtool/utils/influxdb_url.go
Labels: size/XS

#12143 Automated cherry pick of #12141: fix(devtool): get tenant info via correct field
  pkg/devtool/utils/influxdb_url.go
Labels: size/XS

#12154 fix(region): sync aliyun qcloud default project
  pkg/cloudprovider/subaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/qcloud/qcloud.go
Labels: size/M, area/region

#12155 Automated cherry pick of #12154: fix(region): sync aliyun qcloud default project
  pkg/cloudprovider/subaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/qcloud/qcloud.go
Labels: size/M

#12156 Automated cherry pick of #12154: fix(region): sync aliyun qcloud default project
  pkg/cloudprovider/subaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/qcloud/qcloud.go
Labels: size/M

#12149 fix(monitor): add monitor resource details field
  pkg/apis/monitor/monitor_resource.go
  pkg/monitor/models/modelset.go
  pkg/monitor/models/monitor_resource.go
Labels: size/XS, area/monitor

#12150 Automated cherry pick of #12149: fix(monitor): add monitor resource details field
  pkg/apis/monitor/monitor_resource.go
  pkg/monitor/models/modelset.go
  pkg/monitor/models/monitor_resource.go
Labels: size/XS

#12151 Automated cherry pick of #12149: fix(monitor): add monitor resource details field
  pkg/apis/monitor/monitor_resource.go
  pkg/monitor/models/modelset.go
  pkg/monitor/models/monitor_resource.go
Labels: size/XS

#12152 fix(monitor): add record shield details param
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/recordshield.go
Labels: size/XS, area/monitor

#12153 Automated cherry pick of #12152: fix(monitor): add record shield details param
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/recordshield.go
Labels: size/XS

#12157 fix: set disk driver and network driver for converting esxi to kvm
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: approved, size/M

#12159 Automated cherry pick of #12157: fix: set disk driver and network driver for converting esxi to kvm
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: approved, size/M

#12160 Automated cherry pick of #12157: fix: set disk driver and network driver for converting esxi to kvm
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: approved, size/M

#12162 fix(region): sync apsara region
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/region.go
Labels: size/M, area/region

#12163 Automated cherry pick of #12162: fix(region): sync apsara region
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/region.go
Labels: size/M

#12164 Automated cherry pick of #12162: fix(region): sync apsara region
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/region.go
Labels: size/M

#12165 Automated cherry pick of #12162: fix(region): sync apsara region
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/region.go
Labels: size/M

#12168 fix(region): optimized qcloud tag sync
  pkg/cloudprovider/resourcetags.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/compute/tasks/loadbalancer_syncstatus_task.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/qcloud/tags.go
  pkg/multicloud/tag_base.go
Labels: size/L, area/region

#12169 Automated cherry pick of #12168: fix(region): optimized qcloud tag sync
  pkg/cloudprovider/resourcetags.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/compute/tasks/loadbalancer_syncstatus_task.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/qcloud/tags.go
  pkg/multicloud/tag_base.go
Labels: size/L

#12170 Automated cherry pick of #12168: fix(region): optimized qcloud tag sync
  pkg/cloudprovider/resourcetags.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/loadbalancer_remote_update_task.go
  pkg/compute/tasks/loadbalancer_syncstatus_task.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/qcloud/loadbalancer.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/qcloud/tags.go
  pkg/multicloud/tag_base.go
Labels: size/L

#12171 fix(scheduler): options for openstack scheduler
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/options/options.go
Labels: size/S, area/scheduler

#12172 Automated cherry pick of #12171: fix(scheduler): options for openstack scheduler
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/options/options.go
Labels: size/S

#12173 Automated cherry pick of #12171: fix(scheduler): options for openstack scheduler
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/options/options.go
Labels: size/S

#12125 fix(climc): SSH terminal window changes with the change of local terminal
  cmd/climc/shell/compute/servers.go
  pkg/util/ssh/ssh.go
Labels: lgtm, approved, size/M, area/climc

#12174 Automated cherry pick of #12125: fix(climc): SSH terminal window changes with the change of local terminal
  cmd/climc/shell/compute/servers.go
  pkg/util/ssh/ssh.go
Labels: approved, size/M

#12175 Automated cherry pick of #12125: fix(climc): SSH terminal window changes with the change of local terminal
  cmd/climc/shell/compute/servers.go
  pkg/util/ssh/ssh.go
Labels: approved, size/M

#12181 Hotfix/qx apsara project
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/disk.go
  pkg/multicloud/apsara/eip.go
  pkg/multicloud/apsara/elasticcache_instance.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/apsara/loadbalancer.go
  pkg/multicloud/apsara/loadbalanceracl.go
  pkg/multicloud/apsara/loadbalancerbackend.go
  pkg/multicloud/apsara/loadbalancerbackendgroup.go
  pkg/multicloud/apsara/loadbalancerdefaultbackend.go
  pkg/multicloud/apsara/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/apsara/loadbalancerhttplistener.go
  pkg/multicloud/apsara/loadbalancerhttpslistener.go
  pkg/multicloud/apsara/loadbalancerlistenerrule.go
  pkg/multicloud/apsara/loadbalancermasterslavebackend.go
  pkg/multicloud/apsara/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/apsara/loadbalancerservercertificate.go
  pkg/multicloud/apsara/loadbalancertcplistener.go
  pkg/multicloud/apsara/loadbalancerudplistener.go
  pkg/multicloud/apsara/networkinterfaces.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/apsara/snapshot.go
  pkg/multicloud/apsara/snapshot_policy.go
  pkg/multicloud/apsara/vswitch.go
Labels: size/L, area/region

#12182 Automated cherry pick of #12181: Hotfix/qx apsara project
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/disk.go
  pkg/multicloud/apsara/eip.go
  pkg/multicloud/apsara/elasticcache_instance.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/apsara/loadbalancer.go
  pkg/multicloud/apsara/loadbalanceracl.go
  pkg/multicloud/apsara/loadbalancerbackend.go
  pkg/multicloud/apsara/loadbalancerbackendgroup.go
  pkg/multicloud/apsara/loadbalancerdefaultbackend.go
  pkg/multicloud/apsara/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/apsara/loadbalancerhttplistener.go
  pkg/multicloud/apsara/loadbalancerhttpslistener.go
  pkg/multicloud/apsara/loadbalancerlistenerrule.go
  pkg/multicloud/apsara/loadbalancermasterslavebackend.go
  pkg/multicloud/apsara/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/apsara/loadbalancerservercertificate.go
  pkg/multicloud/apsara/loadbalancertcplistener.go
  pkg/multicloud/apsara/loadbalancerudplistener.go
  pkg/multicloud/apsara/networkinterfaces.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/apsara/snapshot.go
  pkg/multicloud/apsara/snapshot_policy.go
  pkg/multicloud/apsara/vswitch.go
Labels: size/L

#12183 Automated cherry pick of #12181: Hotfix/qx apsara project
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/apsara/disk.go
  pkg/multicloud/apsara/eip.go
  pkg/multicloud/apsara/elasticcache_instance.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/apsara/loadbalancer.go
  pkg/multicloud/apsara/loadbalanceracl.go
  pkg/multicloud/apsara/loadbalancerbackend.go
  pkg/multicloud/apsara/loadbalancerbackendgroup.go
  pkg/multicloud/apsara/loadbalancerdefaultbackend.go
  pkg/multicloud/apsara/loadbalancerdefaultbackendgroup.go
  pkg/multicloud/apsara/loadbalancerhttplistener.go
  pkg/multicloud/apsara/loadbalancerhttpslistener.go
  pkg/multicloud/apsara/loadbalancerlistenerrule.go
  pkg/multicloud/apsara/loadbalancermasterslavebackend.go
  pkg/multicloud/apsara/loadbalancermasterslavebackendgroup.go
  pkg/multicloud/apsara/loadbalancerservercertificate.go
  pkg/multicloud/apsara/loadbalancertcplistener.go
  pkg/multicloud/apsara/loadbalancerudplistener.go
  pkg/multicloud/apsara/networkinterfaces.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/apsara/securitygroup.go
  pkg/multicloud/apsara/snapshot.go
  pkg/multicloud/apsara/snapshot_policy.go
  pkg/multicloud/apsara/vswitch.go
Labels: size/L

#12176 fix(region): huawei region id with project name
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: size/M, area/region

#12177 Automated cherry pick of #12176: fix(region): huawei region id with project name
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: size/M

#12178 Automated cherry pick of #12176: fix(region): huawei region id with project name
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: size/M

#12179 Automated cherry pick of #12176: fix(region): huawei region id with project name
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: size/S

#12180 Automated cherry pick of #12176: fix(region): huawei region id with project name
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
Labels: size/S

#12184 fix(region): qcloud database sync
  pkg/multicloud/qcloud/rds_mysql_database.go
Labels: lgtm, approved, size/XS, area/region

#12185 Automated cherry pick of #12184: fix(region): qcloud database sync
  pkg/multicloud/qcloud/rds_mysql_database.go
Labels: lgtm, approved, size/XS

#12186 Automated cherry pick of #12184: fix(region): qcloud database sync
  pkg/multicloud/qcloud/rds_mysql_database.go
Labels: lgtm, approved, size/XS

#12188 Automated cherry pick of #12184: fix(region): qcloud database sync
  pkg/multicloud/qcloud/rds_mysql_database.go
Labels: lgtm, approved, size/XS

#12187 Automated cherry pick of #12184: fix(region): qcloud database sync
  pkg/multicloud/qcloud/rds_mysql_database.go
Labels: lgtm, approved, size/XS

#12189 fix(region): isolated_device desc include addr
  pkg/compute/models/isolated_devices.go
Labels: approved, size/XS

#12193 fix(region): apsara resource group
  pkg/multicloud/apsara/project.go
Labels: size/XS, area/region

#12194 Automated cherry pick of #12193: fix(region): apsara resource group
  pkg/multicloud/apsara/project.go
Labels: size/XS

#12195 Automated cherry pick of #12193: fix(region): apsara resource group
  pkg/multicloud/apsara/project.go
Labels: size/XS

#12196 pure hcso zone is not empty fix
  pkg/compute/models/purge.go
Labels: lgtm, size/S, area/region

#12197 Automated cherry pick of #12196: pure hcso zone is not empty fix
  pkg/compute/models/purge.go
Labels: size/S

#12198 Automated cherry pick of #12196: pure hcso zone is not empty fix
  pkg/compute/models/purge.go
Labels: size/S

#12203 feat(cloudmon): support classic vm metrics
  pkg/cloudmon/collectors/azuremon/azureservice.go
  pkg/cloudmon/collectors/azuremon/azureutils.go
  pkg/cloudmon/collectors/common/basemon.go
Labels: lgtm, approved, size/M, area/cloudmon

#12204 Automated cherry pick of #12203: feat(cloudmon): support classic vm metrics
  pkg/cloudmon/collectors/azuremon/azureservice.go
  pkg/cloudmon/collectors/azuremon/azureutils.go
  pkg/cloudmon/collectors/common/basemon.go
Labels: lgtm, approved, size/M

#12205 Automated cherry pick of #12203: feat(cloudmon): support classic vm metrics
  pkg/cloudmon/collectors/azuremon/azureservice.go
  pkg/cloudmon/collectors/azuremon/azureutils.go
  pkg/cloudmon/collectors/common/basemon.go
Labels: lgtm, approved, size/M

#12209 fix(region): change aws disk iops
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/instance.go
Labels: size/M, area/region

#12211 Automated cherry pick of #12209: fix(region): change aws disk iops
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/instance.go
Labels: size/M

#12210 Automated cherry pick of #12209: fix(region): change aws disk iops
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/instance.go
Labels: size/M

#12199 fix(region): apsara metric data
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/apsaramon/apsarautils.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/apsara/monitor.go
  pkg/multicloud/apsara/organization.go
  pkg/multicloud/apsara/shell/resourcegroup.go
Labels: size/L, area/region

#12200 Automated cherry pick of #12199: fix(region): apsara metric data
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/apsaramon/apsarautils.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/apsara/monitor.go
  pkg/multicloud/apsara/organization.go
  pkg/multicloud/apsara/shell/resourcegroup.go
Labels: size/L

#12201 Automated cherry pick of #12199: fix(region): apsara metric data
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/apsaramon/apsarautils.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/apsara/monitor.go
  pkg/multicloud/apsara/organization.go
  pkg/multicloud/apsara/shell/resourcegroup.go
Labels: size/L

#12166 feat(region): add cloudcache for dnszone and secgroup details
  pkg/apis/compute/dnszone.go
  pkg/apis/compute/secgroup.go
  pkg/compute/models/dns_zones.go
  pkg/compute/models/secgroups.go
  pkg/mcclient/options/dnszone.go
  pkg/mcclient/options/secgroup.go
Labels: size/M, area/region

#12167 Automated cherry pick of #12166: feat(region): add cloudcache for dnszone and secgroup details
  pkg/apis/compute/dnszone.go
  pkg/apis/compute/secgroup.go
  pkg/compute/models/dns_zones.go
  pkg/compute/models/secgroups.go
  pkg/mcclient/options/dnszone.go
  pkg/mcclient/options/secgroup.go
Labels: size/M

#12212 Automated cherry pick of #12166: feat(region): add cloudcache for dnszone and secgroup details
  pkg/apis/compute/dnszone.go
  pkg/apis/compute/secgroup.go
  pkg/compute/models/dns_zones.go
  pkg/compute/models/secgroups.go
  pkg/mcclient/options/dnszone.go
  pkg/mcclient/options/secgroup.go
Labels: size/M

#12202 feat(climc): SSH Login with cloudroot (add new parameter --use-cloudroot in server-ssh)
  cmd/climc/shell/compute/servers.go
  pkg/mcclient/modules/mod_sshkeypairs.go
  pkg/mcclient/options/servers.go
Labels: lgtm, approved, size/M, area/climc

#12206 fix: AWS asume role with optional name
  pkg/cloudevent/models/cloudproviders.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/extra.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_test.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/hcso/bucket.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/hcso/saml_provider.go
  pkg/multicloud/hcso/wire.go
Labels: approved, size/L

#12207 Automated cherry pick of #12206: fix: AWS asume role with optional name
  pkg/cloudevent/models/cloudproviders.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/extra.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_test.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/hcso/bucket.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/hcso/saml_provider.go
  pkg/multicloud/hcso/wire.go
Labels: approved, size/L

#12208 Automated cherry pick of #12206: fix: AWS asume role with optional name
  pkg/cloudevent/models/cloudproviders.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/extra.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/bucket.go
  pkg/multicloud/apsara/provider/provider.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_test.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/hcso/bucket.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/provider/provider.go
  pkg/multicloud/hcso/saml_provider.go
  pkg/multicloud/hcso/wire.go
Labels: approved, size/L

#12217 Automated cherry pick of #12202: feat(climc): SSH Login with cloudroot (add new parameter --use-cloudroot in server-ssh)
  cmd/climc/shell/compute/servers.go
  pkg/mcclient/modules/mod_sshkeypairs.go
  pkg/mcclient/options/servers.go
Labels: approved, size/M

#12218 Automated cherry pick of #12202: feat(climc): SSH Login with cloudroot (add new parameter --use-cloudroot in server-ssh)
  cmd/climc/shell/compute/servers.go
  pkg/mcclient/modules/mod_sshkeypairs.go
  pkg/mcclient/options/servers.go
Labels: approved, size/M

#12214 fix(cloudmon): Azure metric pull support metric interval
  pkg/cloudmon/collectors/azuremon/azureservice.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/azure/monitor.go
Labels: size/M, area/cloudmon

#12215 Automated cherry pick of #12214: fix(cloudmon): Azure metric pull support metric interval
  pkg/cloudmon/collectors/azuremon/azureservice.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/azure/monitor.go
Labels: size/M

#12216 Automated cherry pick of #12214: fix(cloudmon): Azure metric pull support metric interval
  pkg/cloudmon/collectors/azuremon/azureservice.go
  pkg/cloudmon/collectors/common/basemon.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/azure/monitor.go
Labels: size/M

#12230 fix(baremetal): parse mptsas duplicated devices
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru_test.go
Labels: lgtm, approved, size/M, area/baremetal

#12231 Automated cherry pick of #12230: fix(baremetal): parse mptsas duplicated devices
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru_test.go
Labels: lgtm, approved, size/M

#12232 Automated cherry pick of #12230: fix(baremetal): parse mptsas duplicated devices
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru_test.go
Labels: lgtm, approved, size/M

#12233 Automated cherry pick of #12230: fix(baremetal): parse mptsas duplicated devices
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru_test.go
Labels: lgtm, approved, size/M

#12228 fix: climc event-show filter by resource name
  cmd/climc/shell/events/events.go
Labels: size/S, approved

#12229 Automated cherry pick of #12228: fix: climc event-show filter by resource name
  cmd/climc/shell/events/events.go
Labels: size/S, approved

#12219 fix(region): disk choice master host with os arch
  pkg/apis/const.go
  pkg/compute/models/disks.go
  pkg/compute/tasks/disk_create_task.go
Labels: size/M, area/region

#12220 Automated cherry pick of #12219: fix(region): disk choice master host with os arch
  pkg/apis/const.go
  pkg/compute/models/disks.go
  pkg/compute/tasks/disk_create_task.go
Labels: size/M

#12221 Automated cherry pick of #12219: fix(region): disk choice master host with os arch
  pkg/apis/const.go
  pkg/compute/models/disks.go
  pkg/compute/tasks/disk_create_task.go
Labels: size/M

#12227 feat(climc): SSH login of a host by private key
  cmd/climc/shell/compute/hosts.go
Labels: lgtm, approved, size/M, area/climc

#12235 Automated cherry pick of #12227: feat(climc): SSH login of a host by private key
  cmd/climc/shell/compute/hosts.go
Labels: approved, size/M

#12238 Automated cherry pick of #12213: fix(cloudmon): batch send data
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/apsara/monitor.go
Labels: size/M

#12239 Automated cherry pick of #12213: fix(cloudmon): batch send data
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/apsara/monitor.go
Labels: size/M

#12213 fix(cloudmon): batch send data
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/multicloud/apsara/monitor.go
Labels: size/M, area/cloudmon

#12247 fix(scheduler): openstack scheduler options
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/options/options.go
  pkg/scheduler/options/options.go
  pkg/scheduler/service/service.go
Labels: size/M, area/scheduler

#12248 Automated cherry pick of #12247: fix(scheduler): openstack scheduler options
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/options/options.go
  pkg/scheduler/options/options.go
  pkg/scheduler/service/service.go
Labels: size/M

#12249 Automated cherry pick of #12247: fix(scheduler): openstack scheduler options
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/options/options.go
  pkg/scheduler/options/options.go
  pkg/scheduler/service/service.go
Labels: size/M

#12250 fix(region): get region driver
  pkg/compute/tasks/network_create_task.go
Labels: size/XS, area/region

#12251 Automated cherry pick of #12250: fix(region): get region driver
  pkg/compute/tasks/network_create_task.go
Labels: size/XS

#12242 Automated cherry pick of #12240: fix(hostman): rbd command
  build/docker/Dockerfile.host
  build/docker/multi-arch/Dockerfile.host
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/util/cephutils/ceph.go
  pkg/util/cephutils/doc.go
Labels: size/XXL

#12240 fix(hostman): rbd command
  build/docker/Dockerfile.host
  build/docker/multi-arch/Dockerfile.host
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/util/cephutils/ceph.go
  pkg/util/cephutils/doc.go
Labels: size/XXL, area/host

#12234 Automated cherry pick of #12227: feat(climc): SSH login of a host by private key
  cmd/climc/shell/compute/hosts.go
Labels: approved, size/M

#12254 fix(host): ceph snap delete
  pkg/util/cephutils/ceph.go
Labels: size/M, area/host

#12255 Automated cherry pick of #12254: fix(host): ceph snap delete
  pkg/util/cephutils/ceph.go
Labels: size/M

#12236 fix: ensure the success of vgrenam
  build/docker/Dockerfile.host-deployer
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M, area/host-deployer

#12237 Automated cherry pick of #12236: fix: ensure the success of vgrenam
  build/docker/Dockerfile.host-deployer
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#12253 fix(region): optimzed network query
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/compute/regiondrivers/aws.go
Labels: size/L, area/region

#12256 Automated cherry pick of #12253: fix(region): optimzed network query
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/compute/regiondrivers/aws.go
Labels: size/L

#12257 Automated cherry pick of #12253: fix(region): optimzed network query
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/compute/regiondrivers/aws.go
Labels: size/L
