Repository yunionio/cloudpods, pull requests merged in 2021-02, with the labels that each got.

#10093 fix(region): avoid update tags task loop
  pkg/cloudcommon/db/metadata.go
Labels: area/region, size/XS

#10094 Automated cherry pick of #10093: fix(region): avoid update tags task loop
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#10095 Automated cherry pick of #10093: fix(region): avoid update tags task loop
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#10113 feat(notify): verification email style optimization
  build/notify/root/opt/yunion/share/template/content@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/content@en/VERIFY.email
  pkg/notify/models/template.go
  pkg/notify/tasks/verification_send_task.go
Labels: area/notify, size/S

#10115 Automated cherry pick of #10113: feat(notify): verification email style optimization
  build/notify/root/opt/yunion/share/template/content@cn/VERIFY.email
  build/notify/root/opt/yunion/share/template/content@en/VERIFY.email
  pkg/notify/models/template.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/S

#10124 Automated cherry pick of #10122: fix(region): check the global network situation when expanding the network
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/network.go
Labels: size/L

#10123 Automated cherry pick of #10122: fix(region): check the global network situation when expanding the network
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/network.go
Labels: size/L

#10125 Automated cherry pick of #10122: fix(region): check the global network situation when expanding the network
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/esxi/network.go
Labels: size/L

#10117 fix(region): add option auto reconcile backup servers
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: area/region, size/XS

#10119 Automated cherry pick of #10117: fix(region): add option auto reconcile backup servers
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/XS

#10121 Automated cherry pick of #10117: fix(region): add option auto reconcile backup servers
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/XS

#10104 fix(region): delete virtual nics with network
  pkg/compute/models/networks.go
Labels: area/region, size/S

#10105 Automated cherry pick of #10104: fix(region): delete virtual nics with network
  pkg/compute/models/networks.go
Labels: size/S

#10106 Automated cherry pick of #10104: fix(region): delete virtual nics with network
  pkg/compute/models/networks.go
Labels: size/S

#10107 Automated cherry pick of #10104: fix(region): delete virtual nics with network
  pkg/compute/models/networks.go
Labels: size/S

#10108 Automated cherry pick of #10104: fix(region): delete virtual nics with network
  pkg/compute/models/networks.go
Labels: size/S

#10109 fix(region): avoid sync huawei unusable account
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/shell/region.go
Labels: area/region, size/S

#10111 Automated cherry pick of #10109: fix(region): avoid sync huawei unusable account
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/shell/region.go
Labels: size/S

#10116 Automated cherry pick of #10114: Bugfix/yousong usage
  pkg/compute/models/wires.go
  pkg/compute/usages/handler.go
Labels: size/M

#10091 fix(monitor): fix alert duration
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/eval_context_test.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/alerting/result_handler.go
  pkg/monitor/alerting/rule.go
  pkg/monitor/alerting/scheduler.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertnotification.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/notification.go
Labels: approved, lgtm, size/L

#10092 Automated cherry pick of #10091: fix(monitor): fix alert duration
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/eval_context_test.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/alerting/result_handler.go
  pkg/monitor/alerting/rule.go
  pkg/monitor/alerting/scheduler.go
  pkg/monitor/models/alert.go
  pkg/monitor/models/alertnotification.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/notification.go
Labels: approved, lgtm, size/L

#10102 feat(esxi): support iso when creating vm
  pkg/compute/hostdrivers/esxi.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/storage.go
Labels: area/esxiagent, area/region, size/M

#10103 Automated cherry pick of #10102: feat(esxi): support iso when creating vm
  pkg/compute/hostdrivers/esxi.go
  pkg/hostman/storageman/imagecachemanager_agent.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/storage.go
Labels: size/M

#10110 Automated cherry pick of #10109: fix(region): avoid sync huawei unusable account
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/shell/region.go
Labels: size/S

#10099 fix(hostman): avoid panic when disk is nil
  pkg/apis/compute/snapshot_const.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/esxi/handler/handlers.go
  pkg/hostman/downloader/downloadhandler.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_rbd.go
Labels: area/region, size/L

#10100 Automated cherry pick of #10099: fix(hostman): avoid panic when disk is nil
  pkg/apis/compute/snapshot_const.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/esxi/handler/handlers.go
  pkg/hostman/downloader/downloadhandler.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/L

#10101 Automated cherry pick of #10099: fix(hostman): avoid panic when disk is nil
  pkg/apis/compute/snapshot_const.go
  pkg/compute/storagedrivers/rbd.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/esxi/handler/handlers.go
  pkg/hostman/downloader/downloadhandler.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/L

#10096 fix(region): filter resource by classic vpc
  pkg/apis/compute/vpcs_const.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/routetables.go
  pkg/compute/models/scaling_group.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: area/region, size/M

#10097 Automated cherry pick of #10096: fix(region): filter resource by classic vpc
  pkg/apis/compute/vpcs_const.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/routetables.go
  pkg/compute/models/scaling_group.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/M

#10098 Automated cherry pick of #10096: fix(region): filter resource by classic vpc
  pkg/apis/compute/vpcs_const.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/routetables.go
  pkg/compute/models/scaling_group.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/M

#10126 fix(cloudevent): add distinct filed for cloudevent
  pkg/apis/cloudevent/cloudevent.go
  pkg/apis/input.go
  pkg/cloudcommon/db/distinct_fields.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudevent/models/cloudevents.go
  pkg/cloudevent/service/handlers.go
Labels: area/cloudevent, size/L

#10129 Automated cherry pick of #10126: fix(cloudevent): add distinct filed for cloudevent
  pkg/apis/cloudevent/cloudevent.go
  pkg/apis/input.go
  pkg/cloudcommon/db/distinct_fields.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudevent/models/cloudevents.go
  pkg/cloudevent/service/handlers.go
Labels: size/L

#9723 Optimization of vmware network
  cmd/climc/shell/compute/wires.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/wire.go
  pkg/apis/compute/wire_const.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/db/statusbase.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/compute/models/netinterfaces.go
  pkg/compute/models/networks.go
  pkg/compute/models/wire_id_change_handler.go
  pkg/compute/models/wires.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/compute/tasks/networks_under_wire_merge_task.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/wire.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/net_topology.go
  pkg/multicloud/esxi/net_topology_pro.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/vswitch.go
  pkg/util/logclient/consts.go
Labels: area/region, size/XXL

#9749 Automated cherry pick of #9723: Optimization of vmware network
  cmd/climc/shell/compute/wires.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/wire.go
  pkg/apis/compute/wire_const.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/db/statusbase.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
  pkg/compute/models/netinterfaces.go
  pkg/compute/models/networks.go
  pkg/compute/models/wire_id_change_handler.go
  pkg/compute/models/wires.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/compute/tasks/networks_under_wire_merge_task.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/wire.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/manager.go
  pkg/multicloud/esxi/net_topology.go
  pkg/multicloud/esxi/net_topology_pro.go
  pkg/multicloud/esxi/network.go
  pkg/multicloud/esxi/vswitch.go
  pkg/util/logclient/consts.go
Labels: size/XXL

#10127 feat(monitor): alert add silent period param
  pkg/apis/monitor/alertrecord.go
  pkg/apis/monitor/commalert.go
  pkg/apis/monitor/notification.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/nodealert.go
  pkg/monitor/models/notification.go
Labels: area/monitor, size/M

#10128 Automated cherry pick of #10127: feat(monitor): alert add silent period param
  pkg/apis/monitor/alertrecord.go
  pkg/apis/monitor/commalert.go
  pkg/apis/monitor/notification.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/nodealert.go
  pkg/monitor/models/notification.go
Labels: size/M

#10130 fix(hostman): fix kvm create disk failed error
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: area/region, size/S

#10131 Automated cherry pick of #10130: fix(hostman): fix kvm create disk failed error
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/S

#10132 Automated cherry pick of #10130: fix(hostman): fix kvm create disk failed error
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/S

#10137 fix(region): delete not exist disk failed
  pkg/compute/hostdrivers/kvm.go
Labels: area/region, size/XS

#10138 Automated cherry pick of #10137: fix(region): delete not exist disk failed
  pkg/compute/hostdrivers/kvm.go
Labels: size/XS

#10139 Automated cherry pick of #10137: fix(region): delete not exist disk failed
  pkg/compute/hostdrivers/kvm.go
Labels: size/S

#10140 fix(region): bucket size stats should not count invalid sizes of -1
  go.mod
  go.sum
  pkg/compute/models/buckets.go
  vendor/github.com/minio/minio-go/v6/pkg/policy/bucket-policy-condition.go
  vendor/github.com/minio/minio-go/v6/pkg/policy/bucket-policy.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, area/region, lgtm, size/XL

#10141 Automated cherry pick of #10140: fix(region): bucket size stats should not count invalid sizes of -1
  go.mod
  go.sum
  pkg/compute/models/buckets.go
  vendor/github.com/minio/minio-go/v6/pkg/policy/bucket-policy-condition.go
  vendor/github.com/minio/minio-go/v6/pkg/policy/bucket-policy.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, lgtm, size/XL

#10142 Automated cherry pick of #10140: fix(region): bucket size stats should not count invalid sizes of -1
  go.mod
  go.sum
  pkg/compute/models/buckets.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: approved, lgtm, size/L

#10158 fix(apigateway): add enable_quota_check and return-domain-list
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/XS

#10159 Automated cherry pick of #10158: fix(apigateway): add enable_quota_check and return-domain-list
  pkg/apigateway/handler/auth.go
Labels: size/XS

#10160 fix(keystone): add alertrecords to default dashboard permission
  pkg/keystone/locale/predefined_policies.go
Labels: area/keystone, size/XS

#10161 Automated cherry pick of #10160: fix(keystone): add alertrecords to default dashboard permission
  pkg/keystone/locale/predefined_policies.go
Labels: size/XS

#10156 fix(monitor): 3.7 nodata and alertOverview fix
  pkg/apis/monitor/commalert.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/notification.go
Labels: area/monitor, size/L

#10157 Automated cherry pick of #10156: fix(monitor): 3.7 nodata and alertOverview fix
  pkg/apis/monitor/commalert.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/notification.go
Labels: size/L

#10163 fix(cloudid): sync role policy
  pkg/cloudid/models/cloudrole.go
  pkg/multicloud/aws/shell/iam_role.go
Labels: area/cloudid, size/M

#10164 Automated cherry pick of #10163: fix(cloudid): sync role policy
  pkg/cloudid/models/cloudrole.go
  pkg/multicloud/aws/shell/iam_role.go
Labels: size/M

#10165 Automated cherry pick of #10163: fix(cloudid): sync role policy
  pkg/cloudid/models/cloudrole.go
  pkg/multicloud/aws/shell/iam_role.go
Labels: size/M

#10168 fix(region): secgroup clone set status
  pkg/compute/models/secgroups.go
Labels: area/region, size/XS

#10143 fix(baremetal): try channel 8 for default profile
  pkg/baremetal/profiles/profiles.go
Labels: area/baremetal, size/XS

#10144 Automated cherry pick of #10143: fix(baremetal): try channel 8 for default profile
  pkg/baremetal/profiles/profiles.go
Labels: size/XS

#10145 Automated cherry pick of #10143: fix(baremetal): try channel 8 for default profile
  pkg/baremetal/profiles/profiles.go
Labels: size/XS

#10135 fix(region,scheduler): filter enabled skus
  pkg/compute/models/skus.go
  pkg/scheduler/data_manager/sku/sku.go
Labels: area/region, area/scheduler, size/XS

#10136 Automated cherry pick of #10135: fix(region,scheduler): filter enabled skus
  pkg/compute/models/skus.go
  pkg/scheduler/data_manager/sku/sku.go
Labels: size/XS

#10133 fix(region): init and change status
  pkg/apis/compute/wire_const.go
  pkg/compute/models/wires.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/compute/tasks/networks_under_wire_merge_task.go
Labels: size/S

#10134 Automated cherry pick of #10133: fix(region): init and change status
  pkg/apis/compute/wire_const.go
  pkg/compute/models/wires.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/compute/tasks/networks_under_wire_merge_task.go
Labels: size/S

#10171 fix(keystone): idp filter by sso_domain returns domain's idp only
  pkg/keystone/models/identity_provider.go
Labels: area/keystone, size/XS

#10172 Automated cherry pick of #10171: fix(keystone): idp filter by sso_domain returns domain's idp only
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#10173 fix(keystone): cas sso may create new project whenever user login
  pkg/keystone/models/identity_provider.go
Labels: area/keystone, size/XS

#10174 Automated cherry pick of #10173: fix(keystone): cas sso may create new project whenever user login
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#10175 Automated cherry pick of #10173: fix(keystone): cas sso may create new project whenever user login
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#10169 feat(monitor): alert record add silentPeriod info
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/rule.go
  pkg/monitor/models/notification.go
Labels: area/monitor, size/S

#10170 Automated cherry pick of #10169: feat(monitor): alert record add silentPeriod info
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/rule.go
  pkg/monitor/models/notification.go
Labels: size/S

#10146 Feature/baremetal h3c oem
  pkg/baremetal/profiles/profiles.go
  pkg/cloudcommon/types/types.go
Labels: approved, lgtm, size/S

#10147 Automated cherry pick of #10146: Feature/baremetal h3c oem
  pkg/baremetal/profiles/profiles.go
  pkg/cloudcommon/types/types.go
Labels: approved, lgtm, size/S

#10148 Automated cherry pick of #10146: Feature/baremetal h3c oem
  pkg/baremetal/profiles/profiles.go
  pkg/cloudcommon/types/types.go
Labels: approved, lgtm

#10166 warp aws err with errors.Wrap
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/dbinstance_parameter.go
  pkg/multicloud/aws/dbinstance_snapshot.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/keypair.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancercert.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/networkinterface.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/aws/wire.go
  pkg/multicloud/aws/zone.go
Labels: area/region, size/XL

#10167 Automated cherry pick of #10166: warp aws err with errors.Wrap
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/dbinstance_parameter.go
  pkg/multicloud/aws/dbinstance_snapshot.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/host.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/keypair.go
  pkg/multicloud/aws/loadbalancer.go
  pkg/multicloud/aws/loadbalancerbackendgroup.go
  pkg/multicloud/aws/loadbalancercert.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/networkinterface.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/utils.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/aws/wire.go
  pkg/multicloud/aws/zone.go
Labels: size/XL

#10177 imagetools NormalizeImageInfo update
  pkg/apis/image/consts.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/google/image.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/ucloud/image.go
  pkg/multicloud/zstack/image.go
  pkg/util/imagetools/imagetools.go
Labels: area/region, lgtm, size/L

#10178 Automated cherry pick of #10177: imagetools NormalizeImageInfo update
  pkg/apis/image/consts.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/google/image.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/ucloud/image.go
  pkg/multicloud/zstack/image.go
  pkg/util/imagetools/imagetools.go
Labels: size/L

#10180 Automated cherry pick of #10179: fix(monitor): fix update alert duration fail
  pkg/apis/monitor/alert.go
  pkg/monitor/models/commonalert.go
Labels: approved, lgtm, size/XS

#10179 fix(monitor): fix update alert duration fail
  pkg/apis/monitor/alert.go
  pkg/monitor/models/commonalert.go
Labels: approved, area/monitor, lgtm, size/XS

#10181 fix(apigateway): add auth/stats api to retrieve system info
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/M

#10182 Automated cherry pick of #10181: fix(apigateway): add auth/stats api to retrieve system info
  pkg/apigateway/handler/auth.go
Labels: size/M

#10183 fix(monitor,host): replace space to '+' when write to influxdb and replace '+' to space when query
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/monitor/models/datasource.go
  pkg/monitor/tsdb/driver/influxdb/query.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
Labels: approved, area/monitor, lgtm, size/S

#10184 Automated cherry pick of #10183: fix(monitor,host): replace space to '+' when write to influxdb and replace '+' to space when query
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/monitor/models/datasource.go
  pkg/monitor/tsdb/driver/influxdb/query.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
Labels: approved, lgtm, size/S

#10185 Automated cherry pick of #10183: fix(monitor,host): replace space to '+' when write to influxdb and replace '+' to space when query
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/monitor/models/datasource.go
  pkg/monitor/tsdb/driver/influxdb/query.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
Labels: approved, lgtm, size/S

#10189 host 编译跨平台兼容
  build/docker/multi-arch/Dockerfile.host.dockerignore
Labels: approved, lgtm, size/XS

#10188 Automated cherry pick of #10158: fix(apigateway): add enable_quota_check and return-domain-list
  pkg/apigateway/handler/auth.go
Labels: approved, lgtm, size/XS

#10186 Automated cherry pick of #10158: fix(apigateway): add enable_quota_check and return-domain-list
  pkg/apigateway/handler/auth.go
Labels: approved, lgtm, size/XS

#10187 Automated cherry pick of #10158: fix(apigateway): add enable_quota_check and return-domain-list
  pkg/apigateway/handler/auth.go
Labels: approved, lgtm

#10149 chore(utils): add deb build script
  Makefile
  build/build_deb.sh
Labels: approved, lgtm, size/M

#10150 Automated cherry pick of #10149: chore(utils): add deb build script
  Makefile
  build/build_deb.sh
Labels: approved, lgtm, size/M

#10151 Automated cherry pick of #10149: chore(utils): add deb build script
  Makefile
  build/build_deb.sh
Labels: approved, lgtm, size/M

#10191 Automated cherry pick of #10190: fix(scheduler): storage medium type should not exact match
  pkg/apis/compute/storage_const.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: size/S

#10192 Automated cherry pick of #10190: fix(scheduler): storage medium type should not exact match
  pkg/apis/compute/storage_const.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: size/S

#10193 Automated cherry pick of #10190: fix(scheduler): storage medium type should not exact match
  pkg/apis/compute/storage_const.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: size/S

#10190 fix(scheduler): storage medium type should not exact match
  pkg/apis/compute/storage_const.go
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: area/scheduler, size/S

#10194 fix(keystone): hide system scope policies in domain scope view
  pkg/keystone/models/policies.go
Labels: area/keystone, size/XS

#10195 Automated cherry pick of #10194: fix(keystone): hide system scope policies in domain scope view
  pkg/keystone/models/policies.go
Labels: size/XS

#10196 Automated cherry pick of #10194: fix(keystone): hide system scope policies in domain scope view
  pkg/keystone/models/policies.go
Labels: size/XS

#10197 fix(monitor): fix 报警静默期和未恢复告警策略的兼容
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/engine.go
  pkg/monitor/models/alertrecord.go
Labels: approved, area/monitor, lgtm, size/S

#10198 Automated cherry pick of #10197: fix(monitor): fix 报警静默期和未恢复告警策略的兼容
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/engine.go
  pkg/monitor/models/alertrecord.go
Labels: approved, lgtm, size/S

#10199 fix(keystone): policy name duplication
  cmd/climc/shell/identity/policies.go
  pkg/keystone/models/policies.go
Labels: area/keystone, size/M

#10200 Automated cherry pick of #10199: fix(keystone): policy name duplication
  cmd/climc/shell/identity/policies.go
  pkg/keystone/models/policies.go
Labels: size/M

#10201 Automated cherry pick of #10199: fix(keystone): policy name duplication
  cmd/climc/shell/identity/policies.go
  pkg/keystone/models/policies.go
Labels: size/M

#10205 fix(region): host search by any ip
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
Labels: area/region, size/S

#10206 Automated cherry pick of #10205: fix(region): host search by any ip
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
Labels: size/S

#10207 Automated cherry pick of #10205: fix(region): host search by any ip
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
Labels: size/S

#10211 Automated cherry pick of #10210: change os_arch_arm to os_arch_aarch64
  pkg/apis/compute/guest_const.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/image/models/images.go
  pkg/scheduler/algorithm/predicates/guest/cpu_predicate.go
Labels: size/S

#10220 fix(region): set next stage for start vm
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: area/region, size/XS

#10221 Automated cherry pick of #10220: fix(region): set next stage for start vm
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/XS

#10217 server create sku parameter fix
  pkg/compute/models/guests.go
Labels: area/region, size/XS

#10214 feat(monitor): monitor add trigger value when send notify info
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: area/monitor, size/M

#10215 Automated cherry pick of #10214: feat(monitor): monitor add trigger value when send notify info
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/M

#10202 feature(compute): allow live migration without checking Host CPU modes
  pkg/apis/compute/guests.go
  pkg/apis/scheduler/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/host_guests_migrate_task.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/S

#10203 Automated cherry pick of #10202: feature(compute): allow live migration without checking Host CPU modes
  pkg/apis/compute/guests.go
  pkg/apis/scheduler/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/host_guests_migrate_task.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/S

#10204 Automated cherry pick of #10202: feature(compute): allow live migration without checking Host CPU modes
  pkg/apis/compute/guests.go
  pkg/apis/scheduler/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/host_guests_migrate_task.go
  pkg/mcclient/options/servers.go
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/S

#10213 feature(region): support AWS organization
  cmd/awscli/main.go
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/instancenic.go
  pkg/multicloud/aws/keypair.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/organizations.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/reservedinstance.go
  pkg/multicloud/aws/routetable.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/organizations.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/aws/vpc_peering_connection.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/api.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/doc.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/errors.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/service.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/utils/fibonacci_retrier.go
  vendor/yunion.io/x/sqlchemy/README.md
Labels: area/region, lgtm, size/XXL

#10216 Automated cherry pick of #10213: feature(region): support AWS organization
  cmd/awscli/main.go
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/disk.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/aws/instancenic.go
  pkg/multicloud/aws/keypair.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/organizations.go
  pkg/multicloud/aws/provider/provider.go
  pkg/multicloud/aws/region.go
  pkg/multicloud/aws/reservedinstance.go
  pkg/multicloud/aws/routetable.go
  pkg/multicloud/aws/securitygroup.go
  pkg/multicloud/aws/shell/organizations.go
  pkg/multicloud/aws/snapshot.go
  pkg/multicloud/aws/storagecache.go
  pkg/multicloud/aws/vpc.go
  pkg/multicloud/aws/vpc_peering_connection.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/api.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/doc.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/errors.go
  vendor/github.com/aws/aws-sdk-go/service/organizations/service.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/utils/fibonacci_retrier.go
  vendor/yunion.io/x/sqlchemy/README.md
Labels: size/XXL

#10240 fix(region): set redis reboot timeout to 30 mins
  pkg/compute/regiondrivers/managedvirtual.go
Labels: area/region, size/XS

#10241 Automated cherry pick of #10240: fix(region): set redis reboot timeout to 30 mins
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#10242 Automated cherry pick of #10240: fix(region): set redis reboot timeout to 30 mins
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#10234 fix(region): avoid not sync dns zone
  pkg/compute/models/cloudaccounts.go
Labels: area/region, size/S

#10235 Automated cherry pick of #10234: fix(region): avoid not sync dns zone
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#10236 Automated cherry pick of #10234: fix(region): avoid not sync dns zone
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#10237 Automated cherry pick of #10234: fix(region): avoid not sync dns zone
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#10238 Automated cherry pick of #10234: fix(region): avoid not sync dns zone
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#9071 feat(climc): k8s cluster addon add enable native ip alloc option
  cmd/climc/shell/k8s/clusters.go
  cmd/climc/shell/k8s/machines.go
  pkg/mcclient/modules/k8s/cluster.go
  pkg/mcclient/modules/k8s/machine.go
  pkg/mcclient/options/k8s/cluster.go
  pkg/mcclient/options/k8s/machine.go
Labels: area/climc, size/L

#10239 Automated cherry pick of #9071: feat(climc): k8s cluster addon add enable native ip alloc option
  cmd/climc/shell/k8s/clusters.go
  cmd/climc/shell/k8s/machines.go
  pkg/mcclient/modules/k8s/cluster.go
  pkg/mcclient/modules/k8s/machine.go
  pkg/mcclient/options/k8s/cluster.go
  pkg/mcclient/options/k8s/machine.go
Labels: size/L

#10243 Automated cherry pick of #6083: climc: add k8s monitor component
  cmd/climc/shell/k8s/clusters.go
Labels: size/S

#10233 fix(region): support peer secgroup
  cmd/climc/shell/compute/secgrouprules.go
  pkg/apis/compute/secgroup.go
  pkg/apis/compute/secgrouprule.go
  pkg/cloudcommon/validators/validators.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/syncworkers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_kvm_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/mcclient/modules/mod_secgrouprules.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/secgrouprule.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/vpcagent/ovn/keeper.go
Labels: area/region, size/XXL

#10227 fix(region): qcloud quota sync
  pkg/multicloud/qcloud/quota.go
Labels: area/region, size/XS

#10228 Automated cherry pick of #10227: fix(region): qcloud quota sync
  pkg/multicloud/qcloud/quota.go
Labels: size/XS

#10229 Automated cherry pick of #10227: fix(region): qcloud quota sync
  pkg/multicloud/qcloud/quota.go
Labels: size/XS

#10230 Automated cherry pick of #10227: fix(region): qcloud quota sync
  pkg/multicloud/qcloud/quota.go
Labels: size/XS

#10244 fix(region): fix rds tag set error
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/shell/dbinstance.go
Labels: area/region, size/S

#10245 Automated cherry pick of #10244: fix(region): fix rds tag set error
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/multicloud/aliyun/shell/dbinstance.go
Labels: size/S

#10247 Automated cherry pick of #10233: fix(region): support peer secgroup
  cmd/climc/shell/compute/secgrouprules.go
  pkg/apis/compute/secgroup.go
  pkg/apis/compute/secgrouprule.go
  pkg/cloudcommon/validators/validators.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/syncworkers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_kvm_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/mcclient/modules/mod_secgrouprules.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/secgrouprule.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/XXL

#10231 Bugfix/tb bugfix 022202
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
Labels: area/region, size/M

#10232 Automated cherry pick of #10231: Bugfix/tb bugfix 022202
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
Labels: size/M

#10246 fix(region): more details for get aws region error
  cmd/awscli/main.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/organizations.go
  pkg/multicloud/aws/shell/region.go
Labels: area/region, size/M

#10223 fix(host-deployer): mount may fail to lock /etc/mtab, add retrier
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/M

#10225 Automated cherry pick of #10224: fix(region): optimized aws cloudtrail sync
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/cloudtrail.go
  pkg/multicloud/aws/shell/cloudtrail.go
Labels: size/M

#10249 Automated cherry pick of #10223: fix(host-deployer): mount may fail to lock /etc/mtab, add retrier
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/M

#10250 Automated cherry pick of #10223: fix(host-deployer): mount may fail to lock /etc/mtab, add retrier
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/M

#10258 fix(region): redis change spec bugfix
  pkg/compute/regiondrivers/managedvirtual.go
Labels: area/region, size/XS

#10259 Automated cherry pick of #10258: fix(region): redis change spec bugfix
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#10260 Automated cherry pick of #10258: fix(region): redis change spec bugfix
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#10257 Automated cherry pick of #10256: fix(region): optimized qcloud error code
  pkg/multicloud/qcloud/qcloud.go
Labels: size/M

#10256 fix(region): optimized qcloud error code
  pkg/multicloud/qcloud/qcloud.go
Labels: area/region, size/M

#10254 fix(region): aliyun request retry
  pkg/multicloud/aliyun/aliyun.go
  pkg/util/httputils/httputils.go
Labels: area/region, size/XS

#10255 Automated cherry pick of #10254: fix(region): aliyun request retry
  pkg/multicloud/aliyun/aliyun.go
  pkg/util/httputils/httputils.go
Labels: size/XS

#10251 Automated cherry pick of #10247: Automated cherry pick of #10233: fix(region): support peer secgroup
  cmd/climc/shell/compute/secgrouprules.go
  pkg/apis/compute/secgroup.go
  pkg/apis/compute/secgrouprule.go
  pkg/cloudcommon/validators/validators.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/syncworkers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/secgroup_kvm_test.go
  pkg/compute/regiondrivers/secgroup_test.go
  pkg/mcclient/modules/mod_secgrouprules.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/secgrouprule.go
  pkg/multicloud/aliyun/securitygroup.go
  pkg/multicloud/qcloud/securitygroup.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/XXL
