Repository yunionio/cloudpods, pull requests merged in 2021-07, with the labels that each got.

#11539 fix: do not use ntfsresize to resize NTFS partition
  pkg/hostman/diskutils/fsutils/fsutils.go
Labels: approved, size/XS

#11540 Automated cherry pick of #11539: fix: do not use ntfsresize to resize NTFS partition
  pkg/hostman/diskutils/fsutils/fsutils.go
Labels: approved, size/XS

#11541 Automated cherry pick of #11539: fix: do not use ntfsresize to resize NTFS partition
  pkg/hostman/diskutils/fsutils/fsutils.go
Labels: approved, size/XS

#11542 fix(climc): update climc-base image to 20210701
  build/docker/Dockerfile.climc
  build/docker/Makefile
Labels: area/climc, size/XS

#11543 Automated cherry pick of #11542: fix(climc): update climc-base image to 20210701
  build/docker/Dockerfile.climc
  build/docker/Makefile
Labels: approved, size/XS

#11544 Automated cherry pick of #11542: fix(climc): update climc-base image to 20210701
  build/docker/Dockerfile.climc
  build/docker/Makefile
Labels: approved, size/XS

#11537 Notify templates
  cmd/climc/shell/notifyv2/template.go
  pkg/apis/notify/template.go
  pkg/notify/models/config.go
  pkg/notify/models/template.go
Labels: area/notify, size/L

#11553 fix: minor changes of LICENSE and README
  LICENSE
  README-CN.md
  README.md
Labels: approved, size/XS

#11554 fix: add cloudroot as system account, so as not using normal user id
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: area/host, size/S

#11555 Automated cherry pick of #11554: fix: add cloudroot as system account, so as not using normal user id
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: approved, size/S

#11556 Automated cherry pick of #11554: fix: add cloudroot as system account, so as not using normal user id
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: approved, size/S

#11560 update OWNERS
  OWNERS
Labels: approved, size/XS

#11547 fix(region): return disk type
  pkg/compute/models/guest_queries.go
Labels: area/region, size/XS

#11567 fix(region): sync azure waf instance
  pkg/multicloud/azure/azure.go
Labels: area/region, size/XS

#11564 feat(host): add openEuler rootFs driver
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, area/host, lgtm, size/M

#11565 Automated cherry pick of #11564: feat(host): add openEuler rootFs driver
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/M

#11566 Automated cherry pick of #11564: feat(host): add openEuler rootFs driver
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: approved, lgtm, size/M

#11577 Automated cherry pick of #11574: fix(host-deployer): detect UEFI supported not correct
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: approved, lgtm, size/M

#11574 fix(host-deployer): detect UEFI supported not correct
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: approved, lgtm, size/M

#11576 Automated cherry pick of #11574: fix(host-deployer): detect UEFI supported not correct
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: approved, lgtm, size/M

#11557 support azure elb sync
  pkg/apis/compute/loadbalancerbackendgroup.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/multicloud/aliyun/loadbalancerhttplistener.go
  pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  pkg/multicloud/aliyun/loadbalancertcplistener.go
  pkg/multicloud/aliyun/loadbalancerudplistener.go
  pkg/multicloud/apsara/loadbalancerhttplistener.go
  pkg/multicloud/apsara/loadbalancerhttpslistener.go
  pkg/multicloud/apsara/loadbalancerlistenerrule.go
  pkg/multicloud/apsara/loadbalancertcplistener.go
  pkg/multicloud/apsara/loadbalancerudplistener.go
  pkg/multicloud/aws/loadbalancerlistener.go
  pkg/multicloud/aws/loadbalancerlistenerrule.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancer_props.go
  pkg/multicloud/azure/loadbalancerbackend.go
  pkg/multicloud/azure/loadbalancerbackendgroup.go
  pkg/multicloud/azure/loadbalancercert.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/azure/loadbalancerlistenerrule.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/shell/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
  pkg/multicloud/lbredirect_base.go
  pkg/multicloud/openstack/loadbalancerl7rule.go
  pkg/multicloud/openstack/loadbalancerlistener.go
  pkg/multicloud/qcloud/loadbalancer_listener.go
  pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: area/region, lgtm, size/XXL

#11571 Automated cherry pick of #11570: feat(hostdeployer): change the way fo GetLoginAccount in windows
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/S

#11572 Automated cherry pick of #11570: feat(hostdeployer): change the way fo GetLoginAccount in windows
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/S

#11570 feat(hostdeployer): change the way fo GetLoginAccount in windows
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: lgtm, size/S

#11579 fix(region): update jdcloud rds port
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/jdcloud/rds.go
  pkg/multicloud/jdcloud/shell/rds.go
Labels: area/region, size/M

#11575 fix(notify): set default lang 'zh_CN' for robot
  pkg/notify/models/robot.go
Labels: area/notify, size/S

#11586 fix(region): azure cache capability
  pkg/multicloud/azure/azure.go
Labels: area/region, size/XS

#11583 fix(region): handle the error of RequestGuestCreateAllDisks
  pkg/compute/tasks/guest_create_task.go
Labels: area/region, size/XS

#11584 Automated cherry pick of #11583: fix(region): handle the error of RequestGuestCreateAllDisks
  pkg/compute/tasks/guest_create_task.go
Labels: size/XS

#11585 Automated cherry pick of #11583: fix(region): handle the error of RequestGuestCreateAllDisks
  pkg/compute/tasks/guest_create_task.go
Labels: size/XS

#11587 feat(monitor): update monitor resource overview
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_sync.go
  pkg/monitor/tasks/detach_alertresource_task.go
Labels: area/monitor, size/M

#11589 Automated cherry pick of #11587: feat(monitor): update monitor resource overview
  pkg/apis/monitor/monitor_resource_alert.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_sync.go
  pkg/monitor/tasks/detach_alertresource_task.go
Labels: size/M

#11588 fix(region): avoid sync azure china redis failed
  pkg/multicloud/azure/redis.go
Labels: area/region, size/S

#11590 fix(region): validate jdcloud rds err
  pkg/multicloud/jdcloud/rds.go
Labels: area/region, size/XS

#11598 Automated cherry pick of #11597: fix(host-deployer): make SKVMGuestLVMPartition work find
  pkg/hostman/diskutils/nbd/lvmutils.go
Labels: size/L

#11599 Automated cherry pick of #11597: fix(host-deployer): make SKVMGuestLVMPartition work find
  pkg/hostman/diskutils/nbd/lvmutils.go
Labels: size/L

#11597 fix(host-deployer): make SKVMGuestLVMPartition work find
  pkg/hostman/diskutils/nbd/lvmutils.go
Labels: approved, area/host-deployer, lgtm, size/L

#11563 feat(host): aware of kubelet eviction config
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/hostutils/kubelet/doc.go
  pkg/hostman/hostutils/kubelet/docker.go
  pkg/hostman/hostutils/kubelet/eviction/doc.go
  pkg/hostman/hostutils/kubelet/eviction/eviction.go
  pkg/hostman/hostutils/kubelet/eviction/eviction_test.go
  pkg/hostman/hostutils/kubelet/kubelet.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/cgrouputils/cgrouputils.go
  pkg/util/fileutils2/fileutils.go
Labels: approved, area/host, lgtm, size/XL

#11596 Automated cherry pick of #11563: feat(host): aware of kubelet eviction config
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/hostutils/kubelet/doc.go
  pkg/hostman/hostutils/kubelet/docker.go
  pkg/hostman/hostutils/kubelet/eviction/doc.go
  pkg/hostman/hostutils/kubelet/eviction/eviction.go
  pkg/hostman/hostutils/kubelet/eviction/eviction_test.go
  pkg/hostman/hostutils/kubelet/kubelet.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/cgrouputils/cgrouputils.go
  pkg/util/fileutils2/fileutils.go
Labels: approved, lgtm, size/XL

#11594 Automated cherry pick of #11563: feat(host): aware of kubelet eviction config
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/hostutils/kubelet/doc.go
  pkg/hostman/hostutils/kubelet/docker.go
  pkg/hostman/hostutils/kubelet/eviction/doc.go
  pkg/hostman/hostutils/kubelet/eviction/eviction.go
  pkg/hostman/hostutils/kubelet/eviction/eviction_test.go
  pkg/hostman/hostutils/kubelet/kubelet.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/cgrouputils/cgrouputils.go
  pkg/util/fileutils2/fileutils.go
Labels: approved, lgtm, size/XL

#11580 fix(region): update manager name
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: area/region, size/S

#11601 Feature/qj google oidc identity provider
  cmd/climc/shell/identity/identityproviders.go
  pkg/apis/identity/config.go
  pkg/apis/identity/oidc.go
  pkg/keystone/driver/oidc/oidc.go
  pkg/keystone/driver/oidc/template.go
Labels: approved, size/M

#11593 Bugfix/tb bugfix 0700701
  pkg/cloudprovider/resources.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/multicloud/aliyun/loadbalancerbackend.go
  pkg/multicloud/aliyun/loadbalancerdefaultbackend.go
  pkg/multicloud/aliyun/loadbalancermasterslavebackend.go
  pkg/multicloud/apsara/loadbalancerbackend.go
  pkg/multicloud/apsara/loadbalancerdefaultbackend.go
  pkg/multicloud/apsara/loadbalancermasterslavebackend.go
  pkg/multicloud/aws/loadbalancerbackend.go
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancer_props.go
  pkg/multicloud/azure/loadbalancerbackend.go
  pkg/multicloud/azure/loadbalancerbackendgroup.go
  pkg/multicloud/azure/loadbalancerlistener.go
  pkg/multicloud/azure/shell/loadbalancer.go
  pkg/multicloud/huawei/loadbalancer_backend.go
  pkg/multicloud/openstack/loadbalancermember.go
  pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: area/region, size/L

#11610 fix: host detach wire not update netinterface
  pkg/apigateway/handler/resource.go
  pkg/compute/models/hosts.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/netinterfaces.go
Labels: approved, size/M

#11614 Automated cherry pick of #11610: fix: host detach wire not update netinterface
  pkg/apigateway/handler/resource.go
  pkg/compute/models/hosts.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/netinterfaces.go
Labels: approved, size/M

#11613 Automated cherry pick of #11610: fix: host detach wire not update netinterface
  pkg/apigateway/handler/resource.go
  pkg/compute/models/hosts.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/netinterfaces.go
Labels: approved, size/M

#11603 fix(monitor): alert policy use ownerId when update
  pkg/monitor/models/commonalert.go
Labels: area/monitor, size/S

#11605 Automated cherry pick of #11603: fix(monitor): alert policy use ownerId when update
  pkg/monitor/models/commonalert.go
Labels: size/S

#11606 Automated cherry pick of #11603: fix(monitor): alert policy use ownerId when update
  pkg/monitor/models/commonalert.go
Labels: size/S

#11620 update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: area/region, size/S

#11609 fix(baremetal): use ipmitool power reset when redfish power on error
  pkg/baremetal/manager.go
Labels: approved, area/baremetal, lgtm, size/S

#11612 Automated cherry pick of #11609: fix(baremetal): use ipmitool power reset when redfish power on error
  pkg/baremetal/manager.go
Labels: approved, lgtm, size/S

#11611 Automated cherry pick of #11609: fix(baremetal): use ipmitool power reset when redfish power on error
  pkg/baremetal/manager.go
Labels: approved, lgtm, size/S

#11622 fix(region): set DefaultSysDiskBackend as empty for esxi guest
  pkg/compute/guestdrivers/esxi.go
Labels: area/region, size/XS

#11623 Automated cherry pick of #11622: fix(region): set DefaultSysDiskBackend as empty for esxi guest
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS

#11624 Automated cherry pick of #11622: fix(region): set DefaultSysDiskBackend as empty for esxi guest
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS

#11617 fix(monitor): fix monitor resourece update
  pkg/monitor/models/monitor_resource_sync.go
Labels: area/monitor, size/XS

#11618 Automated cherry pick of #11617: fix(monitor): fix monitor resourece update
  pkg/monitor/models/monitor_resource_sync.go
Labels: size/XS

#11592 feat(devtool): use server forward direct for guest with kvm hypervisor
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: area/devtool, size/L

#11621 Automated cherry pick of #11592: feat(devtool): use server forward direct for guest with kvm hypervisor
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: size/L

#11628 fix(keystone): user not found error fix
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/idp_test.go
Labels: approved, area/region, lgtm, size/XS

#11629 Automated cherry pick of #11628: fix(keystone): user not found error fix
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/idp_test.go
Labels: approved, lgtm, size/XS

#11630 Automated cherry pick of #11628: fix(keystone): user not found error fix
  pkg/apigateway/handler/idp.go
  pkg/apigateway/handler/idp_test.go
Labels: approved, lgtm, size/XS

#11582 fix(notify): Support selective update of robot field
  pkg/notify/models/robot.go
Labels: area/notify, size/M

#11595 Feat/qx elk
  cmd/climc/shell/compute/elastic_search.go
  pkg/apis/compute/elastic_search.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/elastic_search.go
  pkg/compute/models/purge.go
  pkg/compute/service/handlers.go
  pkg/compute/tasks/elastic_search_delete_task.go
  pkg/compute/tasks/elastic_search_syncstatus_task.go
  pkg/compute/usages/handler.go
  pkg/mcclient/modules/mod_elastic_searchs.go
  pkg/mcclient/options/compute/elastic_search.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/elastic_search.go
  pkg/multicloud/aliyun/elastic_search_instance_types.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/shell/elk.go
  pkg/multicloud/qcloud/elastic_search.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/elasticcache.go
  pkg/multicloud/qcloud/shell/elasticsearch.go
  pkg/multicloud/region_base.go
  pkg/multicloud/tag_base.go
Labels: area/region, size/XXL

#11627 fix(region): allocate server eip without hostwire restrict
  pkg/compute/models/elasticips.go
Labels: area/region, size/XS

#11631 Automated cherry pick of #11627: fix(region): allocate server eip without hostwire restrict
  pkg/compute/models/elasticips.go
Labels: size/XS

#11633 Automated cherry pick of #11627: fix(region): allocate server eip without hostwire restrict
  pkg/compute/models/elasticips.go
Labels: size/XS

#11635 feat(yunionapi): pre login hook fix
  pkg/apigateway/handler/auth.go
Labels: area/apigateway, size/XS

#11600 fix(region): sync storage before syncing host in syncOnPremiseCloudProviderInfo
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storages.go
Labels: area/region, size/M

#11604 Automated cherry pick of #11600: fix(region): sync storage before syncing host in syncOnPremiseCloudProviderInfo
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storages.go
Labels: size/M

#11615 Automated cherry pick of #11600: fix(region): sync storage before syncing host in syncOnPremiseCloudProviderInfo
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storages.go
Labels: size/M

#11638 fix(region): remove debug info
  pkg/appsrv/dispatcher/dispatcher.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/dns_recordsets.go
  pkg/notify/models/notification.go
  pkg/notify/models/subscriber.go
  pkg/notify/models/topic.go
Labels: area/region, size/XS

#11639 Automated cherry pick of #11638: fix(region): remove debug info
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/dns_recordsets.go
Labels: size/XS

#11640 Automated cherry pick of #11638: fix(region): remove debug info
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/dns_recordsets.go
Labels: size/XS

#11626 fix: compatible with new io scheduler(bfq/mq-deadline) of new Linux kernel
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/cgrouputils/cgrouputils.go
  pkg/util/fileutils2/fileutils.go
  pkg/util/fileutils2/fileutils_test.go
  pkg/util/iproute2/route_test.go
Labels: approved, size/L

#11636 Automated cherry pick of #11580: fix(region): update manager name
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#11650 feat(meter): add meter cost conversion
  cmd/climc/shell/meter/cost_conversions.go
  pkg/mcclient/modules/mod_cost_conversions.go
  pkg/mcclient/options/meter/cost_conversions.go
Labels: size/L

#11651 Automated cherry pick of #11650: feat(meter): add meter cost conversion
  cmd/climc/shell/meter/cost_conversions.go
  pkg/mcclient/modules/mod_cost_conversions.go
  pkg/mcclient/options/meter/cost_conversions.go
Labels: size/L

#11637 fix(region): add qcloud tdsql
  pkg/apis/compute/dbinstance_const.go
  pkg/multicloud/qcloud/dbinstance.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/rds_mysql.go
  pkg/multicloud/qcloud/rds_tdsql.go
  pkg/multicloud/qcloud/region.go
  pkg/multicloud/qcloud/shell/tdsql.go
  pkg/multicloud/qcloud/tdsql_account.go
  pkg/multicloud/qcloud/tdsql_database.go
Labels: size/XL

#11642 fix(region): aws waf sync
  pkg/cloudprovider/waf.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/aws/waf_rules.go
Labels: area/region, size/M

#11655 Automated cherry pick of #11274: fix(region): disable public cloud ip pre allocate
  pkg/compute/options/options.go
Labels: size/XS

#11656 Automated cherry pick of #11274: fix(region): disable public cloud ip pre allocate
  pkg/compute/options/options.go
Labels: size/XS

#11644 azure lb sync listener frontip fix
  pkg/multicloud/azure/loadbalancer.go
  pkg/multicloud/azure/loadbalancerlistener.go
Labels: area/region, lgtm, size/M

#11634 Fix for Notify Config and Robot
  pkg/apis/notify/config.go
  pkg/mcclient/modules/mod_notify.go
  pkg/mcclient/options/notify/receiver.go
  pkg/notify/models/config.go
  pkg/notify/models/receiver.go
  pkg/notify/models/robot.go
Labels: area/notify, size/L

#11647 fix(baremetal): compatible with SN empty of MegaRaid
  pkg/baremetal/utils/raid/megactl/megactl.go
  pkg/baremetal/utils/raid/megactl/megactl_test.go
Labels: approved, area/baremetal, lgtm, size/L

#11648 Automated cherry pick of #11647: fix(baremetal): compatible with SN empty of MegaRaid
  pkg/baremetal/utils/raid/megactl/megactl.go
  pkg/baremetal/utils/raid/megactl/megactl_test.go
Labels: approved, size/L

#11649 Automated cherry pick of #11647: fix(baremetal): compatible with SN empty of MegaRaid
  pkg/baremetal/utils/raid/megactl/megactl.go
  pkg/baremetal/utils/raid/megactl/megactl_test.go
Labels: approved, size/L

#11641 feature: allow server switch network without service interruption
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_migrate_network.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/options/servers.go
Labels: approved, size/L

#11652 Automated cherry pick of #11641: feature: allow server switch network without service interruption
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_migrate_network.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/options/servers.go
Labels: approved, size/L

#11653 Automated cherry pick of #11641: feature: allow server switch network without service interruption
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_migrate_network.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/options/servers.go
Labels: approved, size/L

#11661 fix(climc): json tag
  pkg/mcclient/options/meter/cost_conversions.go
Labels: area/climc, size/XS

#11662 Automated cherry pick of #11661: fix(climc): json tag
  pkg/mcclient/options/meter/cost_conversions.go
Labels: size/XS

#11658 fix(region): sync auzre subscription health status
  pkg/cloudprovider/subaccount.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/subscription.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/huawei/huawei.go
Labels: area/region, size/S

#11660 Automated cherry pick of #11658: fix(region): sync auzre subscription health status
  pkg/cloudprovider/subaccount.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/subscription.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/huawei/huawei.go
Labels: size/S

#11659 Automated cherry pick of #11658: fix(region): sync auzre subscription health status
  pkg/cloudprovider/subaccount.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/subscription.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/huawei/huawei.go
Labels: size/S

#11664 fix(region): avoid aws waf sync lost id
  pkg/multicloud/aws/waf.go
  pkg/multicloud/aws/waf_rules.go
  pkg/multicloud/azure/waf.go
Labels: area/region, size/L

#11667 fix(keystone): avoid sql error
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/wires.go
  pkg/keystone/models/assignments.go
Labels: area/keystone, size/S

#11668 Automated cherry pick of #11667: fix(keystone): avoid sql error
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/wires.go
  pkg/keystone/models/assignments.go
Labels: size/S

#11670 Automated cherry pick of #11667: fix(keystone): avoid sql error
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/keystone/models/assignments.go
Labels: size/S

#11669 Automated cherry pick of #11667: fix(keystone): avoid sql error
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/keystone/models/assignments.go
Labels: size/S

#11671 fix(region): kafka usage
  pkg/compute/models/kafka.go
  pkg/compute/usages/handler.go
Labels: area/region, size/XS

#11674 fix(region): rds network sync
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
Labels: area/region, size/M

#11675 Automated cherry pick of #11674: fix(region): rds network sync
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
Labels: size/M

#11678 fix(build): baremetal arm64 build
  build/docker/Dockerfile.baremetal-agent
  build/docker/Makefile
Labels: approved, area/util, size/XS

#11679 Automated cherry pick of #11678: fix(build): baremetal arm64 build
  build/docker/Dockerfile.baremetal-agent
  build/docker/Makefile
Labels: approved, size/XS

#11680 Automated cherry pick of #11678: fix(build): baremetal arm64 build
  build/docker/Dockerfile.baremetal-agent
  build/docker/Makefile
Labels: approved, size/XS

#11663 feat(hostdeployer): change UserAdd to CheckOrAddUser
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: area/host-deployer, size/M

#11665 Automated cherry pick of #11663: feat(hostdeployer): change UserAdd to CheckOrAddUser
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/M

#11666 Automated cherry pick of #11663: feat(hostdeployer): change UserAdd to CheckOrAddUser
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/M

#11682 fix(region): waf cloud resources
  pkg/cloudprovider/waf.go
  pkg/compute/models/waf_instances.go
Labels: area/region, size/S

#11683 Automated cherry pick of #11681: fix(keystone): policy filter by role
  cmd/climc/shell/identity/policies.go
  cmd/climc/shell/identity/roles.go
  pkg/apis/identity/input.go
  pkg/keystone/models/policies.go
  pkg/mcclient/options/identity/doc.go
  pkg/mcclient/options/identity/policy.go
  pkg/mcclient/options/identity/roles.go
Labels: size/L

#11684 Automated cherry pick of #11681: fix(keystone): policy filter by role
  cmd/climc/shell/identity/policies.go
  cmd/climc/shell/identity/roles.go
  pkg/apis/identity/input.go
  pkg/keystone/models/policies.go
  pkg/mcclient/options/identity/doc.go
  pkg/mcclient/options/identity/policy.go
  pkg/mcclient/options/identity/roles.go
Labels: size/L

#11677 Automated cherry pick of #11674: fix(region): rds network sync
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
Labels: size/M

#11676 Automated cherry pick of #11674: fix(region): rds network sync
  pkg/compute/models/dbinstancenetworks.go
  pkg/compute/models/dbinstances.go
Labels: size/M

#11681 fix(keystone): policy filter by role
  cmd/climc/shell/identity/policies.go
  cmd/climc/shell/identity/roles.go
  pkg/apis/identity/input.go
  pkg/keystone/models/policies.go
  pkg/mcclient/options/identity/doc.go
  pkg/mcclient/options/identity/policy.go
  pkg/mcclient/options/identity/roles.go
Labels: area/keystone, size/L

#11686 Use custom version Telegraf as monitor agent
  build/docker/Dockerfile.ansibleserver
  build/docker/Dockerfile.file-repo
Labels: size/S

#11687 Automated cherry pick of #11686: Use custom version Telegraf as monitor agent
  build/docker/Dockerfile.ansibleserver
  build/docker/Dockerfile.file-repo
Labels: size/S

#11685 fix(region): aliyun kafka delete
  pkg/multicloud/aliyun/aliyun.go
Labels: area/region, size/XS

#11696 Automated cherry pick of #11695: fix: qemu-img create disk may fail to preallocation=metadata enable for large disk
  pkg/util/qemuimg/init.go
  pkg/util/qemuimg/qemuimg.go
Labels: approved, size/S

#11695 fix: qemu-img create disk may fail to preallocation=metadata enable for large disk
  pkg/util/qemuimg/init.go
  pkg/util/qemuimg/qemuimg.go
Labels: approved, size/S

#11697 Automated cherry pick of #11695: fix: qemu-img create disk may fail to preallocation=metadata enable for large disk
  pkg/util/qemuimg/init.go
  pkg/util/qemuimg/qemuimg.go
Labels: approved, size/S

#11698 fix(region): avoid panic when locking
  pkg/compute/models/storages.go
Labels: area/region, lgtm, size/S

#11693 feat: support install monitor agent in baremetal
  build/docker/Dockerfile.ansibleserver
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: area/devtool, size/S

#11694 Automated cherry pick of #11693: feat: support install monitor agent in baremetal
  build/docker/Dockerfile.ansibleserver
  pkg/devtool/tasks/apply_script_task.go
  pkg/devtool/utils/influxdb_url.go
Labels: size/S

#11699 fix(region): sync aws waf default action
  pkg/cloudprovider/waf.go
  pkg/multicloud/aliyun/waf_domain.go
  pkg/multicloud/aws/waf.go
  pkg/multicloud/azure/app_gateways.go
  pkg/multicloud/azure/waf.go
Labels: area/region, size/M

#11700 feat(notify): add receivers query in receivers/get-types
  pkg/apis/notify/config.go
  pkg/mcclient/options/notify/receiver.go
  pkg/notify/models/receiver.go
Labels: area/notify, size/S

#11706 fix(region): v3.5 sec group fix
  pkg/cloudprovider/securitygroup.go
  pkg/compute/regiondrivers/secgroup_aliyun_test.go
  pkg/compute/regiondrivers/secgroup_azure_test.go
  pkg/compute/regiondrivers/secgroup_kvm_test.go
  pkg/compute/regiondrivers/secgroup_openstack_test.go
  pkg/compute/regiondrivers/secgroup_qcloud_test.go
Labels: area/region, size/L

#11691 fix(region): account aksk error
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/ecloud/request.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/jdcloud/image.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/client.go
  pkg/multicloud/zstack/zstack.go
  pkg/util/httputils/httputils.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/errors/consts.go
Labels: area/region, size/L

#11701 fix(region): azure quota sync
  pkg/multicloud/azure/usage.go
Labels: area/region, size/XS

#11702 Automated cherry pick of #11701: fix(region): azure quota sync
  pkg/multicloud/azure/usage.go
Labels: size/XS

#11703 Automated cherry pick of #11701: fix(region): azure quota sync
  pkg/multicloud/azure/usage.go
Labels: size/XS

#11704 Automated cherry pick of #11701: fix(region): azure quota sync
  pkg/multicloud/azure/usage.go
Labels: size/XS

#11692 Automated cherry pick of #11691: fix(region): account aksk error
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  pkg/httperrors/consts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/ecloud/request.go
  pkg/multicloud/huawei/client/modules/manager_base.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/client.go
  pkg/multicloud/zstack/zstack.go
  pkg/util/httputils/httputils.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/errors/consts.go
Labels: size/L

#11707 fix(region): update qcloud secgroup rule
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
Labels: area/region, size/L

#11708 Automated cherry pick of #11707: fix(region): update qcloud secgroup rule
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
Labels: size/L

#11709 Automated cherry pick of #11707: fix(region): update qcloud secgroup rule
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
Labels: size/L

#11710 Automated cherry pick of #11707: fix(region): update qcloud secgroup rule
  pkg/multicloud/qcloud/securitygroup.go
  pkg/multicloud/qcloud/shell/securitygroup.go
Labels: size/L

#11711 fix(host): find same vendor iommu_group devices
  pkg/hostman/isolated_device/isolated_device.go
Labels: approved, area/host, lgtm, size/S

#11712 Automated cherry pick of #11711: fix(host): find same vendor iommu_group devices
  pkg/hostman/isolated_device/isolated_device.go
Labels: approved, lgtm, size/S

#11713 Automated cherry pick of #11711: fix(host): find same vendor iommu_group devices
  pkg/hostman/isolated_device/isolated_device.go
Labels: approved, lgtm, size/S

#11715 fix(region): cpu desc too long
  pkg/compute/models/hosts.go
Labels: area/region, size/S

#11716 Automated cherry pick of #11715: fix(region): cpu desc too long
  pkg/compute/models/hosts.go
Labels: size/S

#11717 Automated cherry pick of #11715: fix(region): cpu desc too long
  pkg/compute/models/hosts.go
Labels: size/S

#11718 Automated cherry pick of #11715: fix(region): cpu desc too long
  pkg/compute/models/hosts.go
Labels: size/S

#11720 fix(region): openstack ip pre allocate
  pkg/multicloud/openstack/instance.go
Labels: area/region, size/S

#11722 Automated cherry pick of #11720: fix(region): openstack ip pre allocate
  pkg/multicloud/openstack/instance.go
Labels: size/S

#11721 Automated cherry pick of #11720: fix(region): openstack ip pre allocate
  pkg/multicloud/openstack/instance.go
Labels: size/S

#11723 Automated cherry pick of #11720: fix(region): openstack ip pre allocate
  pkg/multicloud/openstack/instance.go
Labels: size/S

#11724 fix(region): fetch zone before syncing promise cloud provider storages
  pkg/compute/models/cloudsync.go
Labels: area/region, size/M
