Repository yunionio/cloudpods, pull requests merged in 2022-05, with the labels that each got.

#11423 Feature/yousong vpc elb
  go.mod
  go.sum
  pkg/apis/compute/elasticips_const.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalanceragents.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/eip_associate_task.go
  pkg/compute/tasks/eip_dissociate_task.go
  pkg/lbagent/api.go
  pkg/lbagent/models/agentparams.go
  pkg/lbagent/models/corpus.go
  pkg/lbagent/models/gobetween.go
  pkg/lbagent/models/haproxy.go
  pkg/lbagent/models/keepalived.go
  pkg/lbagent/models/models.go
  pkg/lbagent/models/modelset.go
  pkg/lbagent/models/modelset_test.go
  pkg/lbagent/models/modelsets.go
  pkg/lbagent/models/reflect.go
  pkg/lbagent/ovn.go
  pkg/mcclient/models/loadbalancers.go
  pkg/mcclient/modules/compute/mod_loadbalancernetworks.go
  pkg/mcclient/options/compute/eips.go
  pkg/util/iproute2/address.go
  pkg/util/logclient/consts.go
  pkg/vpcagent/models/models.go
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/modelsets.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/lb_acl.go
  pkg/vpcagent/ovn/names.go
  pkg/vpcagent/ovn/worker.go
  vendor/github.com/coreos/go-iptables/LICENSE
  vendor/github.com/coreos/go-iptables/NOTICE
  vendor/github.com/coreos/go-iptables/iptables/iptables.go
  vendor/github.com/coreos/go-iptables/iptables/lock.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go
  vendor/github.com/vishvananda/netns/README.md
  vendor/github.com/vishvananda/netns/go.mod
  vendor/github.com/vishvananda/netns/go.sum
  vendor/github.com/vishvananda/netns/netns.go
  vendor/github.com/vishvananda/netns/netns_linux.go
  vendor/modules.txt
Labels: size/XXL, area/region, area/vpcagent

#14231 Splittable checksum
  pkg/cloudcommon/db/checksum.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/tablespec.go
  pkg/util/splitable/metadata.go
Labels: area/logger

#14233 fix(region): get spec of baremetal in ready status
  pkg/compute/models/hosts.go
Labels: area/region

#14246 feat(climc): SERVERIDS of devtool batch apply
  pkg/mcclient/options/devtool/script.go
Labels: area/devtool

#14297 fix(region): avoid panic with qcloud sync
  pkg/multicloud/qcloud/certificate.go
Labels: size/S, area/region

#14298 Automated cherry pick of #14297: fix(region): avoid panic with qcloud sync
  pkg/multicloud/qcloud/certificate.go
Labels: size/S

#14299 Automated cherry pick of #14297: fix(region): avoid panic with qcloud sync
  pkg/multicloud/qcloud/certificate.go
Labels: size/S

#14301 fix(region): huawei object temp url
  pkg/multicloud/huawei/obs/conf.go
  pkg/multicloud/objectstore/shell.go
Labels: size/M, area/region

#14302 Automated cherry pick of #14301: fix(region): huawei object temp url
  pkg/multicloud/huawei/obs/conf.go
  pkg/multicloud/objectstore/shell.go
Labels: size/M

#14300 fix(region): eip associate type
  pkg/compute/models/elasticips.go
  pkg/compute/tasks/eip_syncstatus_task.go
  pkg/multicloud/aliyun/eip.go
  pkg/multicloud/apsara/eip.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/azure/classic_eip.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/bingocloud/eip.go
  pkg/multicloud/ecloud/eip.go
  pkg/multicloud/google/eip.go
  pkg/multicloud/hcso/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/jdcloud/eip.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/qcloud/eip.go
  pkg/multicloud/ucloud/eip.go
  pkg/multicloud/zstack/eip.go
Labels: size/L, area/region

#14304 feature: daemon server support
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S, area/region, area/host

#14305 Automated cherry pick of #14304: feature: daemon server support
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#14293 feat(climc): feature configuration
  cmd/climc/shell/misc/feature.go
Labels: size/L, area/climc

#14294 Automated cherry pick of #14293: feat(climc): feature configuration
  cmd/climc/shell/misc/feature.go
Labels: size/L

#14295 fix(region): account probe lock
  pkg/compute/models/cloudaccounts.go
Labels: size/S, area/region

#14296 Automated cherry pick of #14295: fix(region): account probe lock
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#14306 Automated cherry pick of #14300: fix(region): eip associate type
  pkg/compute/models/elasticips.go
  pkg/compute/tasks/eip_syncstatus_task.go
  pkg/multicloud/aliyun/eip.go
  pkg/multicloud/apsara/eip.go
  pkg/multicloud/aws/eip.go
  pkg/multicloud/azure/classic_eip.go
  pkg/multicloud/azure/eip.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/bingocloud/eip.go
  pkg/multicloud/ecloud/eip.go
  pkg/multicloud/google/eip.go
  pkg/multicloud/hcso/eip.go
  pkg/multicloud/huawei/eip.go
  pkg/multicloud/jdcloud/eip.go
  pkg/multicloud/openstack/eip.go
  pkg/multicloud/qcloud/eip.go
  pkg/multicloud/ucloud/eip.go
  pkg/multicloud/zstack/eip.go
Labels: size/L

#14311 Automated cherry pick of #14310: fix(region): eip update
  pkg/compute/models/elasticips.go
  pkg/mcclient/options/compute/eips.go
Labels: size/XS

#14309 Automated cherry pick of #14308: fix(region): azure disk status
  pkg/multicloud/azure/disk.go
  pkg/multicloud/azure/eip.go
Labels: size/XS

#14312 fix(region): aliyun oss https
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS, area/region

#14313 Automated cherry pick of #14312: fix(region): aliyun oss https
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS

#14314 Automated cherry pick of #14312: fix(region): aliyun oss https
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS

#14318 fix: make server is_daemon an admin attribute
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/compute/models/guests.go
Labels: lgtm, size/XS

#14319 Automated cherry pick of #14318: fix: make server is_daemon an admin attribute
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/compute/models/guests.go
Labels: size/XS

#14320 Automated cherry pick of #14310: fix(region): eip update
  pkg/compute/models/elasticips.go
  pkg/mcclient/options/compute/eips.go
Labels: size/XS

#14325 fix: add widget-settings
  pkg/mcclient/modules/yunionconf/mod_parameters.go
Labels: size/S

#14326 fix(region): add filter for eip
  pkg/compute/models/elasticips.go
  pkg/mcclient/options/compute/eips.go
Labels: size/S, area/region

#14327 Automated cherry pick of #14326: fix(region): add filter for eip
  pkg/compute/models/elasticips.go
  pkg/mcclient/options/compute/eips.go
Labels: size/S

#14328 fix(region): apsara bucket limit
  pkg/multicloud/apsara/bucket.go
Labels: size/XS, area/region

#14329 Automated cherry pick of #14328: fix(region): apsara bucket limit
  pkg/multicloud/apsara/bucket.go
Labels: size/XS

#14330 fix(region): huawei lb eip sync
  pkg/compute/regiondrivers/huawei.go
Labels: size/XS, area/region

#14331 Automated cherry pick of #14330: fix(region): huawei lb eip sync
  pkg/compute/regiondrivers/huawei.go
Labels: size/XS

#14334 fix: hide server rtc_change event log
  pkg/hostman/monitor/qmp.go
Labels: size/XS

#14335 Automated cherry pick of #14334: fix: hide server rtc_change event log
  pkg/hostman/monitor/qmp.go
Labels: size/XS

#14336 Automated cherry pick of #14334: fix: hide server rtc_change event log
  pkg/hostman/monitor/qmp.go
Labels: size/XS

#14332 fix(region): vpc lb with eip
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/M, area/region

#14339 fix: server associate eip check
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/S

#14341 Automated cherry pick of #14339: fix: server associate eip check
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/S

#14340 Automated cherry pick of #14339: fix: server associate eip check
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/S

#14333 fix: backup pack missing encrypt_key_id
  cmd/climc/shell/compute/backup.go
  cmd/climc/shell/compute/disks.go
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/events/events.go
  cmd/cryptool/shell/zeroclean.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/instance_backup.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/diskbackups.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/instance_backup_pack_task.go
  pkg/compute/tasks/instance_backup_unpack_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/mcclient/options/compute/backup.go
  pkg/mcclient/options/compute/disks.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/L

#14337 Automated cherry pick of #14333: fix: backup pack missing encrypt_key_id
  cmd/climc/shell/compute/backup.go
  cmd/climc/shell/compute/disks.go
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/events/events.go
  cmd/cryptool/shell/zeroclean.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/instance_backup.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/diskbackups.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/instance_backup_pack_task.go
  pkg/compute/tasks/instance_backup_unpack_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/mcclient/options/compute/backup.go
  pkg/mcclient/options/compute/disks.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/L

#14338 fix: lb apis for create-eip/associate-eip/dissociate-eip
  cmd/climc/shell/compute/loadbalanceracls.go
  cmd/climc/shell/compute/loadbalanceragents.go
  cmd/climc/shell/compute/loadbalancerbackendgroups.go
  cmd/climc/shell/compute/loadbalancerbackends.go
  cmd/climc/shell/compute/loadbalancercachedacls.go
  cmd/climc/shell/compute/loadbalancercachedcertificates.go
  cmd/climc/shell/compute/loadbalancercertificates.go
  cmd/climc/shell/compute/loadbalancerclusters.go
  cmd/climc/shell/compute/loadbalancerlistenerrules.go
  cmd/climc/shell/compute/loadbalancerlisteners.go
  cmd/climc/shell/compute/loadbalancers.go
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/loadbalancer_delete_task.go
  pkg/lbagent/api.go
  pkg/mcclient/options/compute/loadbalanceracls.go
  pkg/mcclient/options/compute/loadbalanceragents.go
  pkg/mcclient/options/compute/loadbalancerbackendgroups.go
  pkg/mcclient/options/compute/loadbalancerbackends.go
  pkg/mcclient/options/compute/loadbalancercertificates.go
  pkg/mcclient/options/compute/loadbalancerclusters.go
  pkg/mcclient/options/compute/loadbalancerlistenerrules.go
  pkg/mcclient/options/compute/loadbalancerlisteners.go
  pkg/mcclient/options/compute/loadbalancers.go
Labels: size/XL

#14343 fix: vpc eip misc fixes: 1. eip filter 2. lb filter 3. create eip when lb creating
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/loadbalancer_delete_task.go
  pkg/mcclient/options/compute/loadbalancers.go
Labels: size/L

#14344 fix: allow set pagination order
  cmd/climc/shell/events/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/mcclient/options/base.go
Labels: size/S

#14345 fix: recover host status if maintain an empty host
  pkg/compute/tasks/host_maintenance_task.go
Labels: size/XS

#14346 Automated cherry pick of #14345: fix: recover host status if maintain an empty host
  pkg/compute/tasks/host_maintenance_task.go
Labels: size/XS

#14347 Automated cherry pick of #14345: fix: recover host status if maintain an empty host
  pkg/compute/tasks/host_maintenance_task.go
Labels: size/XS

#14352 Automated cherry pick of #14351: fix(region): aliyun disk external id
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#14353 Automated cherry pick of #14351: fix(region): aliyun disk external id
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#14355 update vendor 3.9 20220530
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/functions.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/functions.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/functions.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/errors.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/subquery.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/XXL

#14354 update vendor master 20220530
  go.mod
  go.sum
  vendor/github.com/pierrec/lz4/.gitignore
  vendor/github.com/pierrec/lz4/.travis.yml
  vendor/github.com/pierrec/lz4/README.md
  vendor/github.com/pierrec/lz4/block.go
  vendor/github.com/pierrec/lz4/decode_amd64.go
  vendor/github.com/pierrec/lz4/decode_amd64.s
  vendor/github.com/pierrec/lz4/decode_other.go
  vendor/github.com/pierrec/lz4/errors.go
  vendor/github.com/pierrec/lz4/internal/xxh32/xxh32zero.go
  vendor/github.com/pierrec/lz4/lz4.go
  vendor/github.com/pierrec/lz4/reader.go
  vendor/github.com/pierrec/lz4/reader_legacy.go
  vendor/github.com/pierrec/lz4/writer.go
  vendor/github.com/pierrec/lz4/writer_legacy.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/functions.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/functions.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/functions.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/case.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/errors.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/subquery.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/XXL

#14348 fix(region): public cloud user data
  pkg/apis/compute/api.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
Labels: size/S, area/region

#14350 Automated cherry pick of #14348: fix(region): public cloud user data
  pkg/apis/compute/api.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#14356 Automated cherry pick of #14344: fix: allow set pagination order
  cmd/climc/shell/events/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/mcclient/options/base.go
Labels: size/S

#14357 Automated cherry pick of #14344: fix: allow set pagination order
  cmd/climc/shell/events/events.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/mcclient/options/base.go
Labels: size/S

#14358 fix: more detailed log for server change_config
  pkg/compute/models/guest_actions.go
Labels: size/XS

#14360 Automated cherry pick of #14358: fix: more detailed log for server change_config
  pkg/compute/models/guest_actions.go
Labels: size/XS

#14361 Automated cherry pick of #14358: fix: more detailed log for server change_config
  pkg/compute/models/guest_actions.go
Labels: size/XS

#14359 fix: wrong hypervisor in kvm vnc info
  pkg/compute/guestdrivers/kvm.go
Labels: lgtm, size/XS

#14362 Automated cherry pick of #14359: fix: wrong hypervisor in kvm vnc info
  pkg/compute/guestdrivers/kvm.go
Labels: lgtm, size/XS
