Repository yunionio/cloudpods, pull requests merged in 2022-11, with the labels that each got.

#15269 feat(region): no_bmc option of host create api
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: size/XS, area/region

#15270 Automated cherry pick of #15269: feat(region): no_bmc option of host create api
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: size/XS

#15281 fix/modelarts status
  pkg/apis/compute/modelarts_pool.go
  pkg/compute/tasks/modelarts_pool_change_config_task.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/M

#15282 Automated cherry pick of #15281: fix/modelarts status
  pkg/apis/compute/modelarts_pool.go
  pkg/compute/tasks/modelarts_pool_change_config_task.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#15268 fix: save unsynced ip to metadata
  pkg/compute/models/guests.go
Labels: lgtm, size/S

#15272 fix(region): panic on host offline and update health status is nil
  pkg/compute/models/hosts.go
Labels: size/XS

#15273 Automated cherry pick of #15272: fix(region): panic on host offline and update health status is nil
  pkg/compute/models/hosts.go
Labels: size/XS

#15274 Automated cherry pick of #15272: fix(region): panic on host offline and update health status is nil
  pkg/compute/models/hosts.go
Labels: size/XS

#15277 fix(region): dns record sync
  pkg/multicloud/aliyun/dns_domain_record.go
Labels: size/S, area/region

#15278 Automated cherry pick of #15277: fix(region): dns record sync
  pkg/multicloud/aliyun/dns_domain_record.go
Labels: size/S

#15276 fix(region): implement failed stage: OnDiskLiveChangeStorageReadyFailed
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/XS

#15279 Automated cherry pick of #15276: fix(region): implement failed stage: OnDiskLiveChangeStorageReadyFailed
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/XS

#15286 fix(host-deployer): add deploy telegraf error info
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#15287 Automated cherry pick of #15286: fix(host-deployer): add deploy telegraf error info
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#15285 fix(region): check cloudpods self manage
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/provider/provider.go
Labels: size/S, area/region

#15280 fix: allow upload image via apigateway backend proxy
  pkg/apigateway/handler/backendproxy.go
  pkg/appsrv/appsrv.go
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/token3.go
Labels: lgtm, size/M

#15289 Automated cherry pick of #15280: fix: allow upload image via apigateway backend proxy
  pkg/apigateway/handler/backendproxy.go
  pkg/appsrv/appsrv.go
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/token3.go
Labels: size/M

#15267 Automated cherry pick of #15266: fix: allow duplicate vm ids when sync
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/compare/compare.go
Labels: size/M

#15291 fix(cloudid): hcso saml provider update
  pkg/multicloud/hcso/saml_provider.go
Labels: size/S

#15257 fix(keystone): optimzed project list
  pkg/apis/identity/project.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/project_resources.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/users.go
Labels: size/L, area/keystone

#15258 Automated cherry pick of #15257: fix(keystone): optimzed project list
  pkg/apis/identity/project.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/project_resources.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/users.go
Labels: size/L

#15292 fix(region):modelarts task
  pkg/compute/tasks/modelarts_pool_change_config_task.go
  pkg/compute/tasks/modelarts_pool_create_task.go
Labels: lgtm, size/XS

#15293 Automated cherry pick of #15292: fix(region):modelarts task
  pkg/compute/tasks/modelarts_pool_change_config_task.go
  pkg/compute/tasks/modelarts_pool_create_task.go
Labels: size/XS

#15295 fix(region):modelartsTimeout
  pkg/apis/compute/modelarts_pool.go
  pkg/compute/tasks/modelarts_pool_change_config_task.go
  pkg/compute/tasks/modelarts_pool_create_task.go
Labels: lgtm, size/S

#15296 Automated cherry pick of #15295: fix(region):modelartsTimeout
  pkg/apis/compute/modelarts_pool.go
  pkg/compute/tasks/modelarts_pool_change_config_task.go
  pkg/compute/tasks/modelarts_pool_create_task.go
Labels: size/S

#15294 fix: vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/dns_domain_record.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/cloudpods.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/eip.go
Labels: size/L, area/region

#15302 fix: vender update
  go.mod
  go.sum
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/saml_provider.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/options/options.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/images.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/cloudpods.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/storagecache.go
Labels: size/L, area/region

#15308 fix(region): set power status on guest status ready
  pkg/compute/models/guest_actions.go
Labels: size/XS

#15111 fix: secgroup peer secgroup constraint
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_secgroups.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
Labels: size/XL

#15309 Automated cherry pick of #15111: fix: secgroup peer secgroup constraint
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_secgroups.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
Labels: size/XL

#15303 fix: generate ssh host keys for linux guest
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: lgtm, size/S

#15304 Automated cherry pick of #15303: fix: generate ssh host keys for linux guest
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/S

#15305 Automated cherry pick of #15303: fix: generate ssh host keys for linux guest
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/S

#15297 fix(monitor): only query enabled host for alerting
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/apis/monitor/alert.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/rule.go
Labels: size/M, area/monitor

#15300 Automated cherry pick of #15297: fix(monitor): only query enabled host for alerting
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/apis/monitor/alert.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/rule.go
Labels: size/M

#15301 Automated cherry pick of #15297: fix(monitor): only query enabled host for alerting
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/apis/monitor/alert.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/rule.go
Labels: size/M

#15298 fix(region,host): disconnect esxi disk on disk delete
  pkg/apis/compute/disk.go
  pkg/compute/hostdrivers/kvm.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/M

#15299 Automated cherry pick of #15298: fix(region,host): disconnect esxi disk on disk delete
  pkg/apis/compute/disk.go
  pkg/compute/hostdrivers/kvm.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/M

#15306 fix: choose available storage by server_id
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/storages.go
Labels: size/S

#15307 Automated cherry pick of #15306: fix: choose available storage by server_id
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/storages.go
Labels: size/S

#15312 fix: add openstack oscli doc
  pkg/multicloud/openstack/oscli/doc.go
Labels: size/S

#15319 fix(regioin): modelarts refresh status
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/XS

#15317 fix(cloudmux): modelarts refresh status
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
Labels: size/S

#15320 fix(region: remove dependency
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/consts.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/i18n.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/storageaccount.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/cloudpods.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/client/modules/manager_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/client/modules/mod_ces.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/client/modules/mod_images.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/manager_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_ces.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_images.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/incloudsphere/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/ceph/adminapi.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/ceph/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/ceph/ceph.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/xsky/adminapi.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/oscli/session.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/oscli/token3.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/zstack.go
Labels: area/region, size/XL

#15321 fix(common): avoid return invalid delete status
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS, area/common

#15322 Automated cherry pick of #15321: fix(common): avoid return invalid delete status
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS

#15314 fix(host-deployer): check /etc/network dir is exist
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#15315 Automated cherry pick of #15314: fix(host-deployer): check /etc/network dir is esixt
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#15323 fix(region): add power states check in some cases
  pkg/compute/models/guest_actions.go
Labels: size/XS

#15328 fix: format version for rpm spec
  build/build.sh
Labels: size/XS

#15329 Automated cherry pick of #15328: fix: format version for rpm spec
  build/build.sh
Labels: size/XS

#15330 Automated cherry pick of #15328: fix: format version for rpm spec
  build/build.sh
Labels: size/XS

#15324 fix(region): 避免i18n重复删除再创建
  pkg/cloudcommon/db/i18n.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/zones.go
Labels: size/M, area/region

#15325 Automated cherry pick of #15324: fix(region): 避免i18n重复删除再创建
  pkg/cloudcommon/db/i18n.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/zones.go
Labels: size/M

#15334 fix(host): remove has pcie extend bus check
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#15332 fix: image osinfo nil panic
  pkg/image/models/images.go
Labels: size/XS

#15333 Automated cherry pick of #15332: fix: image osinfo nil panic
  pkg/image/models/images.go
Labels: size/XS

#15335 fix(scheduler): only check actual_free_capacity when storage is local
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: size/S, area/scheduler

#15336 Automated cherry pick of #15335: fix(scheduler): only check actual_free_capacity when storage is local
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: size/S

#15337 Automated cherry pick of #15335: fix(scheduler): only check actual_free_capacity when storage is local
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
Labels: size/S

#15338 fix(region): region geo info sync
  go.mod
  go.sum
  pkg/compute/models/cloudregions.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/geoinfo.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/natdtable.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/natgateway.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/tags.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/vpc_peering_connection.go
Labels: area/region, size/XL

#15340 feat(glance): precise_match option of image list input
  pkg/apis/image/image.go
  pkg/image/models/images.go
  pkg/mcclient/options/glance/image.go
Labels: size/M, area/image

#15341 Automated cherry pick of #15340: feat(glance): precise_match option of image list input
  pkg/apis/image/image.go
  pkg/image/models/images.go
  pkg/mcclient/options/glance/image.go
Labels: size/M

#15339 fix(host): set max cpus for virt machine type
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#15343 fix(region): hcso region cache
  pkg/multicloud/hcso/huawei.go
Labels: size/S, area/region

#15344 fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/remotefile.go
Labels: size/M, area/region

#15345 fix(region): task panic
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/util/logclient/consts.go
Labels: size/S, area/region

#15346 Automated cherry pick of #15345: fix(region): task panic
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/util/logclient/consts.go
Labels: size/S

#15353 fix: make excel output floating number pretty
  pkg/util/excelutils/excelutils.go
  pkg/util/stringutils2/stringutils.go
  pkg/util/stringutils2/stringutils_test.go
Labels: size/L

#15354 Automated cherry pick of #15353: fix: make excel output floating number pretty
  pkg/util/excelutils/excelutils.go
  pkg/util/stringutils2/stringutils.go
  pkg/util/stringutils2/stringutils_test.go
Labels: size/L

#15348 fix: scheduler ignore storage capacity constraint if migrating
  pkg/scheduler/algorithm/predicates/guest/storage_predicate.go
Labels: size/XS

#15350 Automated cherry pick of #15348: fix: scheduler ignore storage capacity constraint if migrating
  pkg/scheduler/algorithm/predicates/guest/storage_predicate.go
Labels: size/XS

#15349 Automated cherry pick of #15348: fix: scheduler ignore storage capacity constraint if migrating
  pkg/scheduler/algorithm/predicates/guest/storage_predicate.go
Labels: size/XS

#15347 fix(region): upload modelarts network cidr
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/XS

#15342 feat(region,host): sriov nic support
  pkg/apis/compute/api.go
  pkg/apis/compute/isolated_device.go
  pkg/apis/compute/network_const.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nic.go
  pkg/hostman/isolated_device/usb.go
  pkg/hostman/options/options.go
  pkg/scheduler/algorithm/predicates/isolated_device_predicate.go
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/test/mock/core.go
Labels: size/XL

#15351 fix(host-deployer): os arch and uefi detect
  build/docker/Dockerfile.host-deployer
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/util/winutils/winutils.go
Labels: size/L

#15352 Automated cherry pick of #15351: fix(host-deployer): os arch and uefi detect
  build/docker/Dockerfile.host-deployer
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/util/winutils/winutils.go
Labels: size/L

#15360 fix(region): add modelarts created failed
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/M

#15363 fix(region): dead lock on batch migrate
  pkg/compute/models/guest_actions.go
Labels: size/M

#15364 Automated cherry pick of #15363: fix(region): dead lock on batch migrate
  pkg/compute/models/guest_actions.go
Labels: size/M

#15361 fix(scheduler): ignore fetch disk image failed
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/S

#15362 Automated cherry pick of #15361: fix(scheduler): ignore fetch disk image failed
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/S

#15358 fix: do not detect vm ips when managing vmware
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/net_topology.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/net_topology_pro.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/instance_base.go
Labels: lgtm, size/L

#15359 Automated cherry pick of #15358: fix: do not detect vm ips when managing vmware
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudaccounts_test.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/multicloud/esxi/net_topology.go
  pkg/multicloud/esxi/net_topology_pro.go
Labels: size/L

#15368 fix(region): add retry for request
  pkg/util/httputils/httputils.go
Labels: size/M

#15365 fix: automatically set disk is_ssd according to storage medium_type
  pkg/compute/models/disks.go
  pkg/compute/models/storages.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/sysutils/storages.go
  pkg/util/sysutils/storages_test.go
Labels: lgtm, size/L

#15371 feat(climc): k8s cluster force deploy
  cmd/climc/shell/k8s/clusters.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S, area/climc

#15372 Automated cherry pick of #15371: feat(climc): k8s cluster force deploy
  cmd/climc/shell/k8s/clusters.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S

#15356 Automated cherry pick of #15355: fix: vpc secgroup should deny any ingress traffic be default
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/secgrouprules_sort.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/secgrouprules_acl.go
Labels: size/M

#15357 Automated cherry pick of #15355: fix: vpc secgroup should deny any ingress traffic be default
  pkg/vpcagent/models/modelset.go
  pkg/vpcagent/models/secgrouprules_sort.go
  pkg/vpcagent/ovn/keeper.go
  pkg/vpcagent/ovn/secgrouprules_acl.go
Labels: size/M

#15373 fix(region): fix modelarts network no available bug
  pkg/apis/compute/modelarts_pool.go
  pkg/cloudprovider/modelarts_pool.go
  pkg/compute/models/modelarts_pools.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/mcclient/options/compute/modelarts_pool.go
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: size/L

#15375 fix(region): account clean host cache
  pkg/compute/models/cloudproviders.go
Labels: size/XS, area/region

#15377 Automated cherry pick of #15375: fix(region): account clean host cache
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#15376 Automated cherry pick of #15375: fix(region): account clean host cache
  pkg/compute/models/cloudproviders.go
Labels: size/XS

#15378 fix(region) :fix modelarts sku bug
  pkg/apis/compute/modelarts_pool_sku.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/modelarts_pool_sku.go
  pkg/multicloud/hcso/modelarts_sku.go
  pkg/multicloud/huawei/modelarts_pool_sku.go
Labels: lgtm, size/M

#15374 fix(host): virito-blk pci addr dup prefix
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#15370 fix(common): show version when action not found
  pkg/cloudcommon/db/caller.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/modelbase.go
  pkg/logger/models/actionlog.go
Labels: size/S

#15369 feat(region,climc): server set boot index
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestcdrom.go
  pkg/compute/models/guestdisks.go
  pkg/mcclient/modules/compute/mod_serverdisks.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#15382 feature: separate region and cloudmux
  Makefile
  cmd/region/main.go
  go.mod
  go.sum
  pkg/compute/service/service.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
Labels: size/L

#15388 fix(region): modelarts sku external id
  pkg/multicloud/hcso/modelarts_sku.go
  pkg/multicloud/huawei/modelarts_pool_sku.go
Labels: size/S

#15389 feat(climc): k8s cluster extra config
  cmd/climc/shell/k8s/clusters.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S, area/climc

#15385 fix(cloudmon): collect system metric
  pkg/cloudmon/misc/system.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/service.go
Labels: size/L, area/cloudmon

#15386 Automated cherry pick of #15385: fix(cloudmon): collect system metric
  pkg/cloudmon/misc/system.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/service.go
Labels: size/L

#15391 fix(region): hcs vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/modelarts_pool_sku.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/hcs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/port.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts_sku.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool_sku.go
Labels: size/M, area/region

#15390 Automated cherry pick of #15389: feat(climc): k8s cluster extra config
  cmd/climc/shell/k8s/clusters.go
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S

#15396 fix(region): hcs storage type width
  go.mod
  go.sum
  pkg/compute/models/storages.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/region.go
Labels: size/M, area/region

#15397 fix(region): cloudpods self manage check
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/provider/provider.go
Labels: size/XS, area/region

#15398 fix(region): cloudpods self manage check
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cloudpods/cloudpods.go
Labels: size/S, area/region

#15407 fix(host): ceph utils command add timeout
  pkg/util/cephutils/ceph.go
Labels: size/S

#15408 Automated cherry pick of #15407: fix(host): ceph utils command add timeout
  pkg/util/cephutils/ceph.go
Labels: size/S

#15405 fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/natdtable.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/port.go
Labels: size/M, area/region

#15413 Automated cherry pick of #15406: fix(host): filter usb hub devices
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/usb.go
  pkg/hostman/isolated_device/usb_test.go
Labels: size/L

#15406 fix(host): filter usb hub devices
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/usb.go
  pkg/hostman/isolated_device/usb_test.go
Labels: size/L, area/host

#15414 Automated cherry pick of #15406: fix(host): filter usb hub devices
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/usb.go
  pkg/hostman/isolated_device/usb_test.go
Labels: size/L

#15383 Fix/migrate
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesttasks.go
Labels: size/M

#15420 Automated cherry pick of #15383: Fix/migrate
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/guesttasks.go
Labels: size/M

#15410 fix(region): ceph df size
  pkg/util/cephutils/ceph.go
Labels: size/XS, area/region

#15411 Automated cherry pick of #15410: fix(region): ceph df size
  pkg/util/cephutils/ceph.go
Labels: size/XS

#15412 Automated cherry pick of #15410: fix(region): ceph df size
  pkg/util/cephutils/ceph.go
Labels: size/XS

#15402 fix: fail to delete guest due to guestdisk inconsistency
  pkg/compute/tasks/guest_delete_task.go
Labels: lgtm, size/S

#15404 Automated cherry pick of #15402: fix: fail to delete guest due to guestdisk inconsistency
  pkg/compute/tasks/guest_delete_task.go
Labels: size/S

#15403 Automated cherry pick of #15402: fix: fail to delete guest due to guestdisk inconsistency
  pkg/compute/tasks/guest_delete_task.go
Labels: size/S

#15399 fix: filter projects by idp
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
  pkg/mcclient/options/identity/project.go
Labels: size/S

#15400 Automated cherry pick of #15399: fix: filter projects by idp
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
  pkg/mcclient/options/identity/project.go
Labels: size/S

#15418 fix(region,host): live migrate quickly converge
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qmp.go
Labels: size/M

#15419 Automated cherry pick of #15418: fix(region,host): live migrate quickly converge
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qmp.go
Labels: size/M

#15422 Automated cherry pick of #15394: fix(baremetal): Physical server installation OS optimization
  pkg/baremetal/manager.go
Labels: size/XS

#15423 Automated cherry pick of #15394: fix(baremetal): Physical server installation OS optimization
  pkg/baremetal/manager.go
Labels: size/XS

#15395 fix(region): fix modelarts sku and cidr
  go.mod
  go.sum
  pkg/apis/compute/modelarts_pool.go
  pkg/apis/compute/modelarts_pool_sku.go
  pkg/compute/models/modelarts_pool_sku.go
  pkg/compute/models/modelarts_pools.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/mcclient/options/compute/modelarts_pool.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/M

#15421 fix(region): fix network status
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/S

#15426 fix(region): hcs vm disk attach
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/disk.go
Labels: size/S, area/region

#15427 fix(region): vender update
  go.mod
  go.sum
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/managedvirtual.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/loadbalancerbackendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/loadbalabcerpool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/loadbalbacer.go
Labels: size/XXL, area/region

#15428 fix(region): hcs misc fix
  go.mod
  go.sum
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/elasticips.go
  pkg/compute/regiondrivers/hcs.go
  pkg/compute/regiondrivers/managedvirtual.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/hcs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/job.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/redis.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/elasticcache_instance.go
Labels: size/M, area/region

#15429 Automated cherry pick of #15428: fix(region): hcs misc fix
  Makefile
  go.mod
  go.sum
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/elasticips.go
  pkg/compute/regiondrivers/hcs.go
  pkg/compute/regiondrivers/managedvirtual.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/hcs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/job.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/redis.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/elasticcache_instance.go
Labels: size/M

#15430 fix(region): hcs image import
  go.mod
  go.sum
  pkg/compute/guestdrivers/hcs.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/redis.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/storagecache.go
Labels: size/L, area/region

#15431 Automated cherry pick of #15430: fix(region): hcs image import
  go.mod
  go.sum
  pkg/compute/guestdrivers/hcs.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/disks.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/redis.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/storagecache.go
Labels: size/L

#15436 fix(region): delete modelart Sku purgeAll.managerId
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/modelarts_pool_sku.go
  pkg/compute/models/purge.go
Labels: lgtm, size/M

#15380 fix(region,host): check memdev on live migration
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/util/qemutils/cmdline.go
Labels: size/L

#15433 fix: keep schedtask_label table name
  pkg/scheduledtask/models/scheduledtask_label.go
Labels: size/XS

#15435 Automated cherry pick of #15433: fix: keep schedtask_label table name
  pkg/scheduledtask/models/scheduledtask_label.go
Labels: size/XS

#15434 Automated cherry pick of #15433: fix: keep schedtask_label table name
  pkg/scheduledtask/models/scheduledtask_label.go
Labels: size/XS

#15440 fix(region): add modelarts sku policy
  pkg/compute/policy/defaults.go
Labels: lgtm, size/S

#15441 Automated cherry pick of #15440: fix(region): add modelarts sku policy
  pkg/compute/policy/defaults.go
Labels: size/S

#15442 Automated cherry pick of #15440: fix(region): add modelarts sku policy
  pkg/compute/policy/defaults.go
Labels: size/S

#15438 fix(region): delete modelart Sku purgeAll.managerId
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/purge.go
Labels: size/S

#15443 Automated cherry pick of #15438: fix(region): delete modelart Sku purgeAll.managerId
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/purge.go
Labels: size/S

#15331 fix: lbagent master fixes
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/lbagent/haproxy.go
Labels: size/M

#15449 Automated cherry pick of #15331: fix: lbagent master fixes
  pkg/compute/models/loadbalanceragents_deploy.go
  pkg/lbagent/haproxy.go
Labels: size/M

#15445 fix: vmware convert to kvm need check network configuration
  pkg/compute/models/guest_actions.go
Labels: lgtm, size/S

#15446 Automated cherry pick of #15445: fix: vmware convert to kvm need check network configuration
  pkg/compute/models/guest_actions.go
Labels: size/S
