Repository yunionio/cloudpods, pull requests merged in 2022-06, with the labels that each got.

#14368 Hotfix/qj disable disk io multiqueue
  pkg/compute/models/guestdisks.go
  pkg/compute/options/options.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/S

#14369 Automated cherry pick of #14368: Hotfix/qj disable disk io multiqueue
  pkg/compute/models/guestdisks.go
  pkg/compute/options/options.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/S

#14370 Automated cherry pick of #14368: Hotfix/qj disable disk io multiqueue
  pkg/compute/models/guestdisks.go
  pkg/compute/options/options.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/S

#14364 fix(region): aliyun bucket access url
  pkg/multicloud/aliyun/bucket.go
Labels: size/S, area/region

#14366 Automated cherry pick of #14364: fix(region): aliyun bucket access url
  pkg/multicloud/aliyun/bucket.go
Labels: size/S

#14365 Automated cherry pick of #14364: fix(region): aliyun bucket access url
  pkg/multicloud/aliyun/bucket.go
Labels: size/S

#14375 fix: remove virtio-blk num-queues param
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#14376 Automated cherry pick of #14375: fix: remove virtio-blk num-queues param
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#14374 fix: remove virtio-blk num-queues param
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#14380 fix(region): clean vm misc options
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
Labels: size/S, area/region

#14381 Automated cherry pick of #14380: fix(region): clean vm misc options
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
Labels: size/S

#14382 Automated cherry pick of #14380: fix(region): clean vm misc options
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
Labels: size/S

#14377 fix(region): disk save task
  pkg/compute/tasks/disk_save_task.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M, area/region

#14378 Automated cherry pick of #14377: fix(region): disk save task
  pkg/compute/tasks/disk_save_task.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#14379 Automated cherry pick of #14377: fix(region): disk save task
  pkg/compute/tasks/disk_save_task.go
Labels: size/M

#14372 fix(region): 避免加锁导致设置标签超时
  pkg/cloudprovider/resourcetags.go
  pkg/multicloud/qcloud/tags.go
Labels: size/S, area/region

#14373 Automated cherry pick of #14372: fix(region): 避免加锁导致设置标签超时
  pkg/cloudprovider/resourcetags.go
  pkg/multicloud/qcloud/tags.go
Labels: size/S

#14367 fix(region): lb eip api fix
  pkg/compute/models/loadbalancers.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/M, area/region

#14383 fix(region): api doc
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/input.go
  pkg/cloudcommon/db/standalone_anon.go
Labels: size/M, area/region

#14384 Automated cherry pick of #14383: fix(region): api doc
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/input.go
  pkg/cloudcommon/db/standalone_anon.go
Labels: size/M

#14385 optimize(region): add more image dist
  pkg/util/imagetools/imagetools.go
Labels: size/S, area/region

#14386 Automated cherry pick of #14385: optimize(region): add more image dist
  pkg/util/imagetools/imagetools.go
Labels: size/S

#14388 Automated cherry pick of #14387: fix(region): apsara bucket limit size
  pkg/multicloud/apsara/bucket.go
Labels: size/XS

#14342 feat(host,region): suport live change disk storage
  pkg/apis/compute/guest_metadata.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/XL

#14363 Automated cherry pick of #14342: feat(host,region): suport live change disk storage
  pkg/apis/compute/guest_metadata.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/compute/tasks/guest_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/XL

#14389 fix(region): eip allocate
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/eip_allocate_task.go
Labels: size/M, area/region

#14391 Automated cherry pick of #14389: fix(region): eip allocate
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/eip_allocate_task.go
Labels: size/M

#14390 Automated cherry pick of #14389: fix(region): eip allocate
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/eip_allocate_task.go
Labels: size/M

#14392 fix(host): openvswitch service name on UOS
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS, area/host

#14393 Automated cherry pick of #14392: fix(host): openvswitch service name on UOS
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#14395 feature: fetch options of an application via api
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/misc/appoptions.go
  pkg/baremetal/handler/handlers.go
  pkg/cloudcommon/app/options.go
  pkg/compute/models/hosts.go
  pkg/compute/service/handlers.go
  pkg/hostman/host_services.go
  pkg/hostman/options/options.go
  pkg/image/service/handlers.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modulebase/appoptions.go
  pkg/mcclient/modules/appoptions.go
Labels: size/L, area/common

#14397 Automated cherry pick of #14395: feature: fetch options of an application via api
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/misc/appoptions.go
  pkg/baremetal/handler/handlers.go
  pkg/cloudcommon/app/options.go
  pkg/compute/models/hosts.go
  pkg/compute/service/handlers.go
  pkg/hostman/host_services.go
  pkg/hostman/options/options.go
  pkg/image/service/handlers.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modulebase/appoptions.go
  pkg/mcclient/modules/appoptions.go
Labels: size/L

#14398 Automated cherry pick of #14395: feature: fetch options of an application via api
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/misc/appoptions.go
  pkg/baremetal/handler/handlers.go
  pkg/cloudcommon/app/options.go
  pkg/compute/models/hosts.go
  pkg/compute/service/handlers.go
  pkg/hostman/host_services.go
  pkg/hostman/options/options.go
  pkg/image/service/handlers.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modulebase/appoptions.go
  pkg/mcclient/modules/appoptions.go
Labels: size/L

#14399 update vendor master 20220604
  go.mod
  go.sum
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/LICENSE
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/circuit_breaker.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/clienttoken.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/common_client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/cvm_role_credential.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/cvm_role_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/env_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/go.mod
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/common_request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/common_response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/ini.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/netretry.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/provider_chain.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/ratelimitretry.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/regions/regions.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_credential.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/section.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/testdata_invalid.ini
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/testdata_valid.ini
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/value.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/column.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/functions.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/sync.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XXL

#14400 update vendor 20220604 3.9
  go.mod
  go.sum
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/LICENSE
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/circuit_breaker.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/clienttoken.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/common_client.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/cvm_role_credential.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/cvm_role_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/env_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/go.mod
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/common_request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/common_response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/ini.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/netretry.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/provider_chain.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/ratelimitretry.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/regions/regions.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_credential.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/role_arn_provider.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/section.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/testdata_invalid.ini
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/testdata_valid.ini
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go
  vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/value.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/column.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/functions.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/sync.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XXL

#14396 fix(region):资源统计bug，已使用资源统计包含裸金属资源，总数未包含，导致资源使用率统计异常。
  pkg/compute/usages/handler.go
Labels: size/XS, area/region

#14402 Automated cherry pick of #14396: fix(region):资源统计bug，已使用资源统计包含裸金属资源，总数未包含，导致资源使用率统计异常。
  pkg/compute/usages/handler.go
Labels: size/XS

#14403 Automated cherry pick of #14396: fix(region):资源统计bug，已使用资源统计包含裸金属资源，总数未包含，导致资源使用率统计异常。
  pkg/compute/usages/handler.go
Labels: size/XS

#14404 Automated cherry pick of #14396: fix(region):资源统计bug，已使用资源统计包含裸金属资源，总数未包含，导致资源使用率统计异常。
  pkg/compute/usages/handler.go
Labels: size/XS

#14407 update vendor master 20220605
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/M

#14408 update vendor 3.9 20220605
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/M

#14406 feature: support apigatewa type of endpoint
  pkg/apigateway/app/app.go
  pkg/apigateway/handler/backendproxy.go
  pkg/apigateway/handler/misc.go
  pkg/apigateway/options/options.go
  pkg/apis/identity/consts.go
  pkg/mcclient/session.go
Labels: size/L, area/climc, area/apigateway

#14409 Automated cherry pick of #14406: feature: support apigatewa type of endpoint
  pkg/apigateway/app/app.go
  pkg/apigateway/handler/backendproxy.go
  pkg/apigateway/handler/misc.go
  pkg/apigateway/options/options.go
  pkg/apis/identity/consts.go
  pkg/mcclient/session.go
Labels: size/L

#14410 fix(region): api doc replace tab to space
  pkg/apis/cloudid/cloudpolicy.go
  pkg/apis/cloudid/clouduser.go
  pkg/apis/compute/api.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/dbinstance_account.go
  pkg/apis/compute/dbinstance_database.go
  pkg/apis/compute/dnszone.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/elasticip.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/schedtag.go
  pkg/apis/compute/secgroup.go
  pkg/apis/compute/serversku.go
  pkg/apis/compute/storage.go
  pkg/cloudprovider/cloudprovider.go
Labels: size/L, area/region

#14411 Automated cherry pick of #14410: fix(region): api doc replace tab to space
  pkg/apis/cloudid/cloudpolicy.go
  pkg/apis/cloudid/clouduser.go
  pkg/apis/compute/api.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/dbinstance_account.go
  pkg/apis/compute/dbinstance_database.go
  pkg/apis/compute/dnszone.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/elasticip.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/schedtag.go
  pkg/apis/compute/secgroup.go
  pkg/apis/compute/serversku.go
  pkg/apis/compute/storage.go
  pkg/cloudprovider/cloudprovider.go
Labels: size/L

#14413 fix(climc): support proxy for climc
  cmd/climc/entry/climc.go
Labels: size/S, area/region

#14414 Automated cherry pick of #14413: fix(climc): support proxy for climc
  cmd/climc/entry/climc.go
Labels: size/S

#14417 Automated cherry pick of #14415: fix(host): ceph pool size
  pkg/util/cephutils/ceph.go
Labels: size/XS

#14418 fix(scheduler): check if chached image supports UEFI
  pkg/scheduler/algorithm/predicates/baremetal/uefi_predicate.go
Labels: size/S, area/scheduler

#14419 Automated cherry pick of #14418: fix(scheduler): check if chached image supports UEFI
  pkg/scheduler/algorithm/predicates/baremetal/uefi_predicate.go
Labels: size/S

#14421 fix(host): Telegraf 1.19.2 conf
  pkg/hostman/system_service/telegraf.go
Labels: size/XS, area/host

#14422 Automated cherry pick of #14421: fix(host): Telegraf 1.19.2 conf
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#14423 Automated cherry pick of #14421: fix(host): Telegraf 1.19.2 conf
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#14420 fix(baremetal): storcli set sysblock rotational of SSD logical volume
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/types/types.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/raid/adaptec/adaptec.go
  pkg/baremetal/utils/raid/drivers/drivers.go
  pkg/baremetal/utils/raid/hpssactl/hpssactl.go
  pkg/baremetal/utils/raid/interface.go
  pkg/baremetal/utils/raid/megactl/driver.go
  pkg/baremetal/utils/raid/megactl/helper.go
  pkg/baremetal/utils/raid/megactl/megactl.go
  pkg/baremetal/utils/raid/megactl/megactl_test.go
  pkg/baremetal/utils/raid/megactl/storcli.go
  pkg/baremetal/utils/raid/megactl/storcli_test.go
  pkg/baremetal/utils/raid/mvcli/mvcli.go
  pkg/baremetal/utils/raid/raid.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
  pkg/hostman/guestfs/fsdriver/kylin.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/XXL, area/baremetal

#14424 Automated cherry pick of #14420: fix(baremetal): storcli set sysblock rotational of SSD logical volume
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/types/types.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/baremetal/utils/raid/adaptec/adaptec.go
  pkg/baremetal/utils/raid/drivers/drivers.go
  pkg/baremetal/utils/raid/hpssactl/hpssactl.go
  pkg/baremetal/utils/raid/interface.go
  pkg/baremetal/utils/raid/megactl/driver.go
  pkg/baremetal/utils/raid/megactl/helper.go
  pkg/baremetal/utils/raid/megactl/megactl.go
  pkg/baremetal/utils/raid/megactl/megactl_test.go
  pkg/baremetal/utils/raid/megactl/storcli.go
  pkg/baremetal/utils/raid/megactl/storcli_test.go
  pkg/baremetal/utils/raid/mvcli/mvcli.go
  pkg/baremetal/utils/raid/raid.go
  pkg/baremetal/utils/raid/sas2iru/sas2iru.go
  pkg/hostman/guestfs/fsdriver/kylin.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/XXL

#14429 fix: update vendor 20220611 master
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/parse.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/parse.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/index.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/L

#14430 update vendor 20220611 release/3.9
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/parse.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/parse.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/index.go
  vendor/yunion.io/x/sqlchemy/query.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/L

#14426 fix: manage_ntp_configuration not effective
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#14427 Automated cherry pick of #14426: fix: manage_ntp_configuration not effective
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#14428 Automated cherry pick of #14426: fix: manage_ntp_configuration not effective
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#14431 fix: move hostoptions of qemu_version and host_cpu_passthrough to base options
  pkg/hostman/options/options.go
Labels: size/S

#14434 fix: splitable add index should modify base spec
  pkg/keystone/models/domains.go
  pkg/util/splitable/splitable.go
Labels: size/S, area/common

#14435 Automated cherry pick of #14434: fix: splitable add index should modify base spec
  pkg/keystone/models/domains.go
  pkg/util/splitable/splitable.go
Labels: size/S

#14439 fix: keystoen cronman use uninitialized admin token
  pkg/cloudcommon/cronman/cronman.go
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/models/default_admin.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/token.go
  pkg/keystone/util/session.go
Labels: size/M

#14440 Automated cherry pick of #14439: fix: keystoen cronman use uninitialized admin token
  pkg/cloudcommon/cronman/cronman.go
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/models/default_admin.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/token.go
  pkg/keystone/util/session.go
Labels: size/M

#14441 Automated cherry pick of #14439: fix: keystoen cronman use uninitialized admin token
  pkg/cloudcommon/cronman/cronman.go
  pkg/keystone/cronjobs/project_resources.go
  pkg/keystone/models/default_admin.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/token.go
  pkg/keystone/util/session.go
Labels: size/L

#14442 fix: add CreateByInsertOrUpdate flag
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudevent/models/cloudevents.go
  pkg/compute/models/access_group_rules.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/dbinstance_privileges.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/secgrouprules.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/passwords.go
  pkg/logger/models/baremetalevents.go
  pkg/scheduledtask/models/scheduledtask_label.go
  pkg/yunionconf/models/parameters.go
Labels: size/M, area/common

#14443 Automated cherry pick of #14442: fix: add CreateByInsertOrUpdate flag
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudevent/models/cloudevents.go
  pkg/compute/models/access_group_rules.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/dbinstance_privileges.go
  pkg/compute/models/reservedips.go
  pkg/compute/models/secgrouprules.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/passwords.go
  pkg/logger/models/baremetalevents.go
  pkg/scheduledtask/models/scheduledtask_label.go
  pkg/yunionconf/models/parameters.go
Labels: size/M

#14451 fix(region): aliyun readonly
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS, area/region

#14452 Automated cherry pick of #14451: fix(region): aliyun readonly
  pkg/multicloud/aliyun/aliyun.go
Labels: size/XS

#14456 fix: fail to update billingresourcecheck_tbl
  pkg/compute/models/billingresource.go
  pkg/scheduledtask/models/scheduledtask_label.go
Labels: size/XS

#14457 Automated cherry pick of #14456: fix: fail to update billingresourcecheck_tbl
  pkg/compute/models/billingresource.go
  pkg/scheduledtask/models/scheduledtask_label.go
Labels: size/XS

#14449 fix(region): custom user data
  pkg/apis/compute/api.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/huaweistack.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/nutanix.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/guestdrivers.go
Labels: size/L, area/region

#14450 Automated cherry pick of #14449: fix(region): custom user data
  pkg/apis/compute/api.go
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/huaweistack.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/nutanix.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/guestdrivers.go
Labels: size/L

#14455 feat(region,host): support multiqueues on vhost network
  pkg/apis/compute/api.go
  pkg/apis/compute/guestnetwork.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#14444 fix(cloudmon): aliyun rds metric debug log
  pkg/cloudmon/collectors/alimon/aliservice.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
Labels: size/S, area/cloudmon

#14445 Automated cherry pick of #14444: fix(cloudmon): aliyun rds metric debug log
  pkg/cloudmon/collectors/alimon/aliservice.go
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
Labels: size/S

#14459 Automated cherry pick of #14455: feat(region,host): support multiqueues on vhost network
  pkg/apis/compute/api.go
  pkg/apis/compute/guestnetwork.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#14433 feature: tap service support
  cmd/climc/shell/compute/net_tap_flows.go
  cmd/climc/shell/compute/net_tap_services.go
  pkg/apis/compute/net_tap_flows.go
  pkg/apis/compute/net_tap_services.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/loadbalancernetworks.go
  pkg/compute/models/mac_generator.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/compute/service/handlers.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/modules/compute/mod_tap_flows.go
  pkg/mcclient/modules/compute/mod_tap_services.go
  pkg/mcclient/options/compute/net_tap_flows.go
  pkg/mcclient/options/compute/net_tap_services.go
  pkg/util/seclib2/hash.go
  pkg/util/seclib2/hash_test.go
  pkg/util/sysutils/kvm.go
  pkg/util/sysutils/nics.go
  pkg/util/sysutils/nics_test.go
Labels: size/XXL, area/region

#14460 Automated cherry pick of #14433: feature: tap service support
  cmd/climc/shell/compute/net_tap_flows.go
  cmd/climc/shell/compute/net_tap_services.go
  pkg/apis/compute/net_tap_flows.go
  pkg/apis/compute/net_tap_services.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/mac_generator.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/compute/service/handlers.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/modules/compute/mod_tap_flows.go
  pkg/mcclient/modules/compute/mod_tap_services.go
  pkg/mcclient/options/compute/net_tap_flows.go
  pkg/mcclient/options/compute/net_tap_services.go
  pkg/util/seclib2/hash.go
  pkg/util/seclib2/hash_test.go
  pkg/util/sysutils/kvm.go
  pkg/util/sysutils/nics.go
  pkg/util/sysutils/nics_test.go
Labels: size/XXL

#14464 feat(climc): server-list --os-arch
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S, area/climc

#14465 Automated cherry pick of #14464: feat(climc): server-list --os-arch
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#14463 Automated cherry pick of #14461: feat(baremetal): wrap pxe error
  pkg/baremetal/pxe/dhcp.go
Labels: size/S

#14462 Automated cherry pick of #14461: feat(baremetal): wrap pxe error
  pkg/baremetal/pxe/dhcp.go
Labels: size/S

#14461 feat(baremetal): wrap pxe error
  pkg/baremetal/pxe/dhcp.go
Labels: size/S, area/baremetal

#14467 Automated cherry pick of #14466: feature: support tap service phase 2
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host_tap.go
  pkg/apis/compute/net_tap_flows.go
  pkg/apis/compute/net_tap_services.go
  pkg/compute/models/guests.go
  pkg/compute/models/host_taps.go
  pkg/compute/models/hosts.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/compute/models/networks.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/mcclient/options/compute/net_tap_flows.go
  pkg/mcclient/options/compute/net_tap_services.go
Labels: size/XL

#14466 feature: support tap service phase 2
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host_tap.go
  pkg/apis/compute/net_tap_flows.go
  pkg/apis/compute/net_tap_services.go
  pkg/compute/models/guests.go
  pkg/compute/models/host_taps.go
  pkg/compute/models/hosts.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/compute/models/networks.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/mcclient/options/compute/net_tap_flows.go
  pkg/mcclient/options/compute/net_tap_services.go
Labels: size/XL

#14470 fix(baremetal): EnableSerialConsole of UOS
  pkg/hostman/guestfs/fsdriver/anolis.go
  pkg/hostman/guestfs/fsdriver/kylin.go
  pkg/hostman/guestfs/fsdriver/uos.go
Labels: size/S, area/baremetal

#14471 Automated cherry pick of #14470: fix(baremetal): EnableSerialConsole of UOS
  pkg/hostman/guestfs/fsdriver/anolis.go
  pkg/hostman/guestfs/fsdriver/kylin.go
  pkg/hostman/guestfs/fsdriver/uos.go
Labels: size/S

#14474 fix(region): show more statistic info
  pkg/apis/output.go
  pkg/cloudcommon/db/enabledstatusinfrasresource.go
  pkg/cloudcommon/db/statusinfrasresource.go
  pkg/cloudcommon/db/statusstandalone.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guests.go
Labels: size/M, area/region

#14476 Hotfix/qj tap service mirrorfixes2
  pkg/apis/compute/host_tap.go
  pkg/apis/compute/net_tap_flows.go
  pkg/compute/models/host_taps.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/options/options.go
Labels: size/M, area/region, area/host

#14477 Automated cherry pick of #14476: Hotfix/qj tap service mirrorfixes2
  pkg/apis/compute/host_tap.go
  pkg/apis/compute/net_tap_flows.go
  pkg/compute/models/host_taps.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/options/options.go
Labels: size/M

#14478 fix: tap flow check duplicity
  pkg/compute/models/net_tap_flows.go
Labels: size/S, area/region

#14479 Automated cherry pick of #14478: fix: tap flow check duplicity
  pkg/compute/models/net_tap_flows.go
Labels: size/S

#14480 fix: scheduler options not updated by OptionManager
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/openstack.go
  pkg/scheduler/algorithm/predicates/baremetal/base.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/default.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/handler/ping.go
  pkg/scheduler/manager/completed_queue.go
  pkg/scheduler/manager/expire_queue.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/manager/task_history.go
  pkg/scheduler/options/options.go
  pkg/scheduler/service/service.go
Labels: size/L, area/scheduler

#14486 Automated cherry pick of #14480: fix: scheduler options not updated by OptionManager
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/openstack.go
  pkg/scheduler/algorithm/predicates/baremetal/base.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/default.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/handler/ping.go
  pkg/scheduler/manager/completed_queue.go
  pkg/scheduler/manager/expire_queue.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/manager/task_history.go
  pkg/scheduler/options/options.go
  pkg/scheduler/service/service.go
Labels: size/L

#14487 Automated cherry pick of #14480: fix: scheduler options not updated by OptionManager
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/openstack.go
  pkg/scheduler/algorithm/predicates/baremetal/base.go
  pkg/scheduler/algorithm/predicates/quota_predicate.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/default.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/handler/ping.go
  pkg/scheduler/manager/completed_queue.go
  pkg/scheduler/manager/expire_queue.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/manager/task_history.go
  pkg/scheduler/options/options.go
  pkg/scheduler/service/service.go
Labels: size/L

#14472 feat(region): add tablestore sync
  cmd/climc/shell/compute/tablestore.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/tablestores.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/ipv6_gateways.go
  pkg/compute/models/purge.go
  pkg/compute/models/tablestores.go
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/compute/mod_tablestores.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/compute/tablestore.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/shell/tablestore.go
  pkg/multicloud/aliyun/tablestore.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/ots.go
  pkg/multicloud/region_base.go
Labels: area/region, size/XL

#14473 Automated cherry pick of #14472: feat(region): add tablestore sync
  cmd/climc/shell/compute/tablestore.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/tablestores.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/ipv6_gateways.go
  pkg/compute/models/purge.go
  pkg/compute/models/tablestores.go
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/compute/mod_tablestores.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/compute/tablestore.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/shell/tablestore.go
  pkg/multicloud/aliyun/tablestore.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/ots.go
  pkg/multicloud/region_base.go
Labels: size/XL

#14481 fix: nas support create from encrypted snapshot
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_nas.go
  pkg/hostman/storageman/storage_nas.go
Labels: size/S, area/host

#14482 Automated cherry pick of #14481: fix: nas support create from encrypted snapshot
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_nas.go
  pkg/hostman/storageman/storage_nas.go
Labels: size/S

#14484 Automated cherry pick of #14483: fix: climc create aksk not return access_key
  cmd/climc/shell/identity/credentials.go
Labels: size/XS

#14485 Automated cherry pick of #14483: fix: climc create aksk not return access_key
  cmd/climc/shell/identity/credentials.go
Labels: size/XS

#14488 fix(region): not delete groupnetwork when deleting guest
  pkg/compute/models/groupnetworks.go
  pkg/compute/models/groups.go
  pkg/compute/models/initdb.go
Labels: size/M

#14490 Automated cherry pick of #14488: fix(region): not delete groupnetwork when deleting guest
  pkg/compute/models/groupnetworks.go
  pkg/compute/models/groups.go
  pkg/compute/models/initdb.go
Labels: size/M

#14496 fix: clickhouse set max idle connections
  go.mod
  go.sum
  pkg/cloudcommon/database.go
  pkg/cloudcommon/db/database.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/sql.go
Labels: size/M

#14498 Automated cherry pick of #14496: fix: clickhouse set max idle connections
  go.mod
  go.sum
  pkg/cloudcommon/database.go
  pkg/cloudcommon/db/database.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/sql.go
Labels: size/M

#14499 fix: splitable auto_incremental steps should be more than 1 (in case of HA setup)
  pkg/util/splitable/insert.go
Labels: size/XS

#14500 Automated cherry pick of #14499: fix: splitable auto_incremental steps should be more than 1 (in case of HA setup)
  pkg/util/splitable/insert.go
Labels: size/XS

#14505 fix: imageinfo.OsInfo empty
  pkg/image/models/images.go
Labels: size/XS

#14506 Automated cherry pick of #14505: fix: imageinfo.OsInfo empty
  pkg/image/models/images.go
Labels: size/XS

#14503 fix: cleanup tap flows and services for deleted guest and host
  pkg/compute/models/guests.go
  pkg/compute/models/host_taps.go
  pkg/compute/models/hosts.go
  pkg/compute/models/net_tap_flows.go
  pkg/compute/models/net_tap_services.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/L

#14508 fix: migrate failure for encrypted local vm
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/hostman/guestman/qemu/qemu_test.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#14497 fix(region,host): auto migrate on host down
  pkg/cloudcommon/etcd/etcd.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/types/interface.go
  pkg/hostman/host_health/etcd.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#14511 Automated cherry pick of #14497: fix(region,host): auto migrate on host down
  pkg/cloudcommon/etcd/etcd.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/types/interface.go
  pkg/hostman/host_health/etcd.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#14515 fix(cloudmon): GetAdminSession by configuration
  pkg/cloudmon/service/service.go
Labels: size/XS, area/cloudmon

#14513 fix: fail to detect host physical nics
  pkg/util/sysutils/nics.go
Labels: size/XS

#14495 Automated cherry pick of #14494: fix(region): user data fix
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/S

#14517 fix(telegraf-raid-plugin): release-1.6.4 image
  Makefile
Labels: size/XS, area/host

#14519 Automated cherry pick of #14517: fix(telegraf-raid-plugin): release-1.6.4 image
  Makefile
Labels: size/XS

#14523 host_health: auto migrate on host shutdown
  pkg/compute/models/host_health.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger.go
Labels: size/M

#14525 Automated cherry pick of #14523: host_health: auto migrate on host shutdown
  pkg/compute/models/host_health.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger.go
Labels: size/M

#14524 Automated cherry pick of #14523: host_health: auto migrate on host shutdown
  pkg/compute/models/host_health.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger.go
Labels: size/M

#14502 feat(region): Support InCloud Sphere
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/incloudspherecli/main.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/incloudsphere.go
  pkg/compute/hostdrivers/incloudsphere.go
  pkg/compute/regiondrivers/incloudsphere.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/incloudsphere/disk.go
  pkg/multicloud/incloudsphere/doc.go
  pkg/multicloud/incloudsphere/host.go
  pkg/multicloud/incloudsphere/instance.go
  pkg/multicloud/incloudsphere/network.go
  pkg/multicloud/incloudsphere/nic.go
  pkg/multicloud/incloudsphere/provider/doc.go
  pkg/multicloud/incloudsphere/provider/provider.go
  pkg/multicloud/incloudsphere/region.go
  pkg/multicloud/incloudsphere/shell/disk.go
  pkg/multicloud/incloudsphere/shell/doc.go
  pkg/multicloud/incloudsphere/shell/host.go
  pkg/multicloud/incloudsphere/shell/instance.go
  pkg/multicloud/incloudsphere/shell/network.go
  pkg/multicloud/incloudsphere/shell/printutils.go
  pkg/multicloud/incloudsphere/shell/region.go
  pkg/multicloud/incloudsphere/shell/storage.go
  pkg/multicloud/incloudsphere/shell/wire.go
  pkg/multicloud/incloudsphere/shell/zone.go
  pkg/multicloud/incloudsphere/sphere.go
  pkg/multicloud/incloudsphere/storage.go
  pkg/multicloud/incloudsphere/vpc.go
  pkg/multicloud/incloudsphere/wire.go
  pkg/multicloud/incloudsphere/zone.go
  pkg/multicloud/loader/loader.go
  pkg/multicloud/tag_base.go
Labels: size/XXL, area/region

#14526 fix: upgrade go version to 1.16 for build docker images
  .circleci/config.yml
  .github/workflows/docker.yml
  Makefile.common.mk
Labels: size/S

#14527 Automated cherry pick of #14526: fix: upgrade go version to 1.16 for build docker images
  .circleci/config.yml
  .github/workflows/docker.yml
  Makefile.common.mk
Labels: size/S

#14529 fix(region): incloudsphere error
  pkg/multicloud/incloudsphere/sphere.go
Labels: size/XS, area/region

#14530 fix(region): azure region city
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/azure/geographicinfo.go
Labels: size/S, area/region

#14531 Automated cherry pick of #14530: fix(region): azure region city
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/azure/geographicinfo.go
Labels: size/S

#14532 Automated cherry pick of #14530: fix(region): azure region city
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/azure/geographicinfo.go
Labels: size/S

#14533 fix: update build image
  Makefile.common.mk
Labels: size/XS

#14536 fix(build): fatal: unsafe repository ('/root/go/src/yunion.io/x/onecl…
  Makefile.common.mk
Labels: size/XS, area/util

#14537 Automated cherry pick of #14536: fix(build): fatal: unsafe repository ('/root/go/src/yunion.io/x/onecl…
  Makefile.common.mk
Labels: size/XS

#14539 fix(monitor): cpu usage score
  pkg/monitor/controller/balancer/cpu.go
Labels: size/S, area/monitor

#14540 Automated cherry pick of #14539: fix(monitor): cpu usage score
  pkg/monitor/controller/balancer/cpu.go
Labels: size/S

#14542 fix: typo of clickhouse_db
  pkg/cloudcommon/db/database.go
Labels: size/XS

#14543 Automated cherry pick of #14542: fix: typo of clickhouse_db
  pkg/cloudcommon/db/database.go
Labels: size/XS

#14545 fix(host): use alpine-build:3.16.0-go-1.18.2-0
  build/docker/multi-arch/Dockerfile.host
Labels: size/XS, area/host

#14546 Automated cherry pick of #14545: fix(host): use alpine-build:3.16.0-go-1.18.2-0
  build/docker/multi-arch/Dockerfile.host
Labels: size/XS

#14550 Automated cherry pick of #14549: fix: update vendor master 20220630
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/regutils/regutils.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/column.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/columninfo.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/sql.go
Labels: size/M
