Repository yunionio/cloudpods, pull requests merged in 2022-04, with the labels that each got.

#13851 fix(host): arm ovmf not injected
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS, area/host

#13852 Automated cherry pick of #13851: fix(host): arm ovmf not injected
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#13853 fix: cloudshell use dynamic keystone endpoint
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/XS

#13854 Automated cherry pick of #13853: fix: cloudshell use dynamic keystone endpoint
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/XS

#13855 Automated cherry pick of #13853: fix: cloudshell use dynamic keystone endpoint
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/XS

#13856 fix: fail to snapshot and clone due to mismatch class metadata
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#13857 Automated cherry pick of #13856: fix: fail to snapshot and clone due to mismatch class metadata
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#13848 fix(region): show account lake of permission
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/httperrors/consts.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/business.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/aliyun/ram.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/sts.go
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/tags.go
Labels: size/L, area/region

#13849 Automated cherry pick of #13848: fix(region): show account lake of permission
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/httperrors/consts.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/business.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/aliyun/ram.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/sts.go
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/tags.go
Labels: size/L

#13850 Automated cherry pick of #13848: fix(region): show account lake of permission
  pkg/apis/compute/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/httperrors/consts.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/business.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/aliyun/ram.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/sts.go
  pkg/multicloud/qcloud/monitor.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/tags.go
Labels: size/L

#13860 fix(cloudmon): fix gcp metric pull
  pkg/cloudmon/collectors/gcpmon/gcpservice.go
Labels: size/XS, area/cloudmon

#13861 Automated cherry pick of #13860: fix(cloudmon): fix gcp metric pull
  pkg/cloudmon/collectors/gcpmon/gcpservice.go
Labels: size/XS

#13867 fix: support qemu backing file with json format
  pkg/util/qemuimg/qemuimg.go
  pkg/util/qemuimg/qemuimg_test.go
Labels: size/M

#13868 Automated cherry pick of #13867: fix: support qemu backing file with json format
  pkg/util/qemuimg/qemuimg.go
  pkg/util/qemuimg/qemuimg_test.go
Labels: size/M

#13839 fix(region): qcloud use new dns api
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/multicloud/qcloud/dnspod_domain.go
  pkg/multicloud/qcloud/dnspod_record.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/dnspod.go
Labels: size/L, area/region

#13840 Automated cherry pick of #13839: fix(region): qcloud use new dns api
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/multicloud/qcloud/dnspod_domain.go
  pkg/multicloud/qcloud/dnspod_record.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/dnspod.go
Labels: size/L

#13841 Automated cherry pick of #13839: fix(region): qcloud use new dns api
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudsync.go
  pkg/multicloud/qcloud/dnspod_domain.go
  pkg/multicloud/qcloud/dnspod_record.go
  pkg/multicloud/qcloud/provider/provider.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/dnspod.go
Labels: size/L

#13869 fix(region): vm public ip sync
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/S, area/region

#13870 Automated cherry pick of #13869: fix(region): vm public ip sync
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/S

#13871 Automated cherry pick of #13869: fix(region): vm public ip sync
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/S

#13872 feat(region): add reason when syning status for backup storage
  pkg/compute/regiondrivers/kvm.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/S, area/region, area/host

#13873 Automated cherry pick of #13872: feat(region): add reason when syning status for backup storage
  pkg/compute/regiondrivers/kvm.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/S

#13865 Security notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/USER_LOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/USER_LOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/USER_LOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/USER_LOCK.tmpl
  cmd/climc/shell/notifyv2/notification.go
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/database.go
  pkg/cloudcommon/db/checksum.go
  pkg/cloudcommon/db/database.go
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/tablespec.go
  pkg/cloudcommon/db/taskman/interface.go
  pkg/cloudcommon/interface.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudevent/models/cloudevents.go
  pkg/cloudir/service/service.go
  pkg/cloutpost/service/service.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/image/models/image_subs.go
  pkg/image/models/images.go
  pkg/keystone/driver/sql/sql.go
  pkg/logger/models/actionlog.go
  pkg/logger/models/baremetalevents.go
  pkg/notify/models/event.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/scheduler/service/service.go
  pkg/util/logclient/logclient.go
  pkg/yunionconf/service/service.go
Labels: size/L, area/region, area/host, area/keystone, area/notify

#13866 Automated cherry pick of #13865: Security notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/USER_LOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/USER_LOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/USER_LOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/CHECKSUM_TEST_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/USER_LOCK.tmpl
  cmd/climc/shell/notifyv2/notification.go
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/database.go
  pkg/cloudcommon/db/checksum.go
  pkg/cloudcommon/db/database.go
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/opslog.go
  pkg/cloudcommon/db/tablespec.go
  pkg/cloudcommon/db/taskman/interface.go
  pkg/cloudcommon/interface.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudevent/models/cloudevents.go
  pkg/cloudir/service/service.go
  pkg/cloutpost/service/service.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/image/models/image_subs.go
  pkg/image/models/images.go
  pkg/keystone/driver/sql/sql.go
  pkg/logger/models/actionlog.go
  pkg/logger/models/baremetalevents.go
  pkg/notify/models/event.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/scheduler/service/service.go
  pkg/util/logclient/logclient.go
  pkg/yunionconf/service/service.go
Labels: size/L

#13877 fix(notify): enable websocket notifications defaultly for event notify
  pkg/notify/models/notification.go
Labels: size/XS, area/notify

#13878 Automated cherry pick of #13877: fix(notify): enable websocket notifications defaultly for event notify
  pkg/notify/models/notification.go
Labels: size/XS

#13879 Automated cherry pick of #13877: fix(notify): enable websocket notifications defaultly for event notify
  pkg/notify/models/notification.go
Labels: size/XS

#13863 fix(apigateway): convert net err to service error
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/httperrors/consts.go
  pkg/httperrors/errors.go
  pkg/mcclient/modulebase/base.go
Labels: size/XXL

#13864 Automated cherry pick of #13863: fix(apigateway): convert net err to service error
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/httperrors/consts.go
  pkg/httperrors/errors.go
  pkg/mcclient/modulebase/base.go
Labels: size/XXL

#13898 fix: make test format errors
  cmd/climc/shell/compute/disks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/image/models/images.go
  pkg/multicloud/nutanix/zone.go
Labels: size/S

#13900 Automated cherry pick of #13898: fix: make test format errors
  cmd/climc/shell/compute/disks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/image/models/images.go
  pkg/multicloud/nutanix/zone.go
Labels: size/S

#13899 Automated cherry pick of #13898: fix: make test format errors
  cmd/climc/shell/compute/disks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/image/models/images.go
  pkg/multicloud/nutanix/zone.go
Labels: size/S

#13896 fix: host inherit class metadata from wire
  cmd/climc/shell/compute/wires.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/backup.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/wires.go
  pkg/compute/regiondrivers/kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger.go
  pkg/mcclient/options/metadata.go
Labels: size/L

#13897 Automated cherry pick of #13896: fix: host inherit class metadata from wire
  cmd/climc/shell/compute/wires.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/backup.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/hostwires.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/networks.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/wires.go
  pkg/compute/regiondrivers/kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger.go
  pkg/mcclient/options/metadata.go
Labels: size/L

#13894 fix: opsadmin should have project list and get permission
  pkg/keystone/locale/predefined_yaml.go
Labels: size/S

#13895 Automated cherry pick of #13894: fix: opsadmin should have project list and get permission
  pkg/keystone/locale/predefined_yaml.go
Labels: size/S

#13883 Automated cherry pick of #13881: fix: make temporary snapshots invisible
  pkg/compute/models/disks.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/disk_backup_create_task.go
Labels: size/S

#13882 Automated cherry pick of #13881: fix: make temporary snapshots invisible
  pkg/compute/models/disks.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/disk_backup_create_task.go
Labels: size/S

#13881 fix: make temporary snapshots invisible
  pkg/compute/models/disks.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/disk_backup_create_task.go
Labels: size/S

#13890 fix: better handling of network not avaiable on host error
  pkg/compute/models/guests.go
Labels: size/XS

#13893 Automated cherry pick of #13890: fix: better handling of network not avaiable on host error
  pkg/compute/models/guests.go
Labels: size/XS

#13892 Automated cherry pick of #13890: fix: better handling of network not avaiable on host error
  pkg/compute/models/guests.go
Labels: size/XS

#13891 Automated cherry pick of #13890: fix: better handling of network not avaiable on host error
  pkg/compute/models/guests.go
Labels: size/XS

#13884 fix: cloudaccounts getMoreDetails should pass ctx
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#13885 Automated cherry pick of #13884: fix: cloudaccounts getMoreDetails should pass ctx
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#13886 Automated cherry pick of #13884: fix: cloudaccounts getMoreDetails should pass ctx
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#13887 Automated cherry pick of #13884: fix: cloudaccounts getMoreDetails should pass ctx
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#13874 fix(region): optimized disk-list
  pkg/compute/models/disks.go
Labels: size/L, area/region

#13875 Automated cherry pick of #13874: fix(region): optimized disk-list
  pkg/compute/models/disks.go
Labels: size/L

#13876 Automated cherry pick of #13874: fix(region): optimized disk-list
  pkg/compute/models/disks.go
Labels: size/L

#13846 fix(region): sync aliyun remark to cloud
  pkg/cloudprovider/dnszone.go
  pkg/compute/models/dns_zonecaches.go
  pkg/multicloud/aliyun/dns_domain.go
  pkg/multicloud/aliyun/dns_domain_record.go
Labels: size/M, area/region

#13847 Automated cherry pick of #13846: fix(region): sync aliyun remark to cloud
  pkg/cloudprovider/dnszone.go
  pkg/compute/models/dns_zonecaches.go
  pkg/multicloud/aliyun/dns_domain.go
  pkg/multicloud/aliyun/dns_domain_record.go
Labels: size/M

#13912 fix: update vendor for sqlchemy
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#13913 Automated cherry pick of #13912: fix: update vendor for sqlchemy
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/field_update.go
  vendor/yunion.io/x/sqlchemy/inc.go
  vendor/yunion.io/x/sqlchemy/parser.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#13903 fix: save image for aarch64 os show os_arch of x86_64
  pkg/compute/models/disks.go
Labels: size/XS

#13906 Automated cherry pick of #13903: fix: save image for aarch64 os show os_arch of x86_64
  pkg/compute/models/disks.go
Labels: size/XS

#13905 Automated cherry pick of #13903: fix: save image for aarch64 os show os_arch of x86_64
  pkg/compute/models/disks.go
Labels: size/XS

#13907 fix: chage parameter not compatible with fangde OS
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/S

#13909 Automated cherry pick of #13907: fix: chage parameter not compatible with fangde OS
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/S

#13908 Automated cherry pick of #13907: fix: chage parameter not compatible with fangde OS
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/S

#13914 fix: typos in predefined policy yaml
  pkg/keystone/locale/predefined_yaml.go
Labels: size/S

#13915 Automated cherry pick of #13914: fix: typos in predefined policy yaml
  pkg/keystone/locale/predefined_yaml.go
Labels: size/S

#13916 fix: logout event log
  pkg/apigateway/handler/auth.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
  pkg/util/logclient/logclient.go
Labels: size/M

#13917 Automated cherry pick of #13916: fix: logout event log
  pkg/apigateway/handler/auth.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
  pkg/util/logclient/logclient.go
Labels: size/M

#13919 feature: event log add severity and kind fields
  pkg/apis/logger/consts.go
  pkg/apis/logger/input.go
  pkg/logger/extern/syslog.go
  pkg/logger/models/actionlog.go
  pkg/util/logclient/logclient.go
Labels: size/L

#13920 Automated cherry pick of #13919: feature: event log add severity and kind fields
  pkg/apis/logger/consts.go
  pkg/apis/logger/input.go
  pkg/logger/extern/syslog.go
  pkg/logger/models/actionlog.go
  pkg/util/logclient/logclient.go
Labels: size/L

#13888 fix: panic when locking on Background or TODO context
  pkg/cloudcommon/db/lockman/lockman.go
Labels: size/S

#13889 Automated cherry pick of #13888: fix: panic when locking on Background or TODO context
  pkg/cloudcommon/db/lockman/lockman.go
Labels: size/S

#13910 fix: migrate set downtime
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/hostman/options/options.go
Labels: size/M

#13911 Automated cherry pick of #13910: fix: migrate set downtime
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/hostman/options/options.go
Labels: size/M

#13923 fix(region): cloudpods misc fix
  pkg/multicloud/cloudpods/disk.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/cloudpods/storagecache.go
Labels: size/S, area/region

#13928 fix(region): aws storage type sync
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/shell/disk.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/zone.go
Labels: size/L, area/region

#13929 Automated cherry pick of #13928: fix(region): aws storage type sync
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/shell/disk.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/zone.go
Labels: size/L

#13930 Automated cherry pick of #13928: fix(region): aws storage type sync
  pkg/multicloud/aws/shell/disk.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/zone.go
Labels: size/M

#13931 Automated cherry pick of #13928: fix(region): aws storage type sync
  pkg/multicloud/aws/shell/disk.go
  pkg/multicloud/aws/storage.go
  pkg/multicloud/aws/zone.go
Labels: size/M

#13927 Automated cherry pick of #13923: fix(region): cloudpods misc fix
  pkg/multicloud/cloudpods/disk.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/cloudpods/storagecache.go
Labels: size/S

#13933 host: fix isImportFromLibvirt
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#13934 Automated cherry pick of #13933: host: fix isImportFromLibvirt
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#13935 Automated cherry pick of #13933: host: fix isImportFromLibvirt
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#13880 fix(region): qcloud client no need fetch bucket
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/sts.go
  pkg/multicloud/qcloud/sts.go
Labels: size/L, area/region

#13921 Automated cherry pick of #13880: fix(region): qcloud client no need fetch bucket
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/qcloud/shell/sts.go
  pkg/multicloud/qcloud/sts.go
Labels: size/L

#13936 feat(build): add onecloud-base:v3.15.4-0 image build file
  build/docker/Dockerfile.onecloud-base-3-15-4
  build/docker/Makefile
Labels: size/S, area/util

#13937 Automated cherry pick of #13936: feat(build): add onecloud-base:v3.15.4-0 image build file
  build/docker/Dockerfile.onecloud-base-3-15-4
  build/docker/Makefile
Labels: size/S

#13922 fix(region): account read only
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/transport.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/mcclient.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/google/google.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/obs/client.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/utils.go
  pkg/multicloud/zstack/zstack.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/errors/consts.go
Labels: size/L, area/region

#13932 Automated cherry pick of #13922: fix(region): account read only
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/consts.go
  pkg/cloudprovider/transport.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/mcclient.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/google/google.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/obs/client.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/utils.go
  pkg/multicloud/zstack/zstack.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/errors/consts.go
Labels: size/L

#13938 fix(notify): lock panic when InitializeData
  pkg/notify/models/robot.go
Labels: size/XS, area/notify

#13939 Automated cherry pick of #13938: fix(notify): lock panic when InitializeData
  pkg/notify/models/robot.go
Labels: size/XS

#13946 fix(region): read only fix
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/ucloud/client.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/ucloud/utils.go
Labels: size/M, area/region

#13947 Automated cherry pick of #13946: fix(region): read only fix
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/ucloud/client.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/ucloud/utils.go
Labels: size/M

#13941 fix(region): exclude the host whose config or config.network is nil
  pkg/multicloud/esxi/net_topology_pro.go
Labels: size/XS, area/region

#13942 Automated cherry pick of #13941: fix(region): exclude the host whose config or config.network is nil
  pkg/multicloud/esxi/net_topology_pro.go
Labels: size/XS

#13943 Automated cherry pick of #13941: fix(region): exclude the host whose config or config.network is nil
  pkg/multicloud/esxi/net_topology_pro.go
Labels: size/XS

#13948 fix: keystone issues: 1. add no_policy_violation_check
  go.mod
  go.sum
  pkg/apis/identity/domain.go
  pkg/apis/identity/user.go
  pkg/cloudcommon/db/quotas/usageworker.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/users.go
  pkg/keystone/options/options.go
  pkg/keystone/service/localpolicy.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/insert.go
Labels: size/M

#13949 Automated cherry pick of #13948: fix: keystone issues: 1. add no_policy_violation_check
  go.mod
  go.sum
  pkg/apis/identity/domain.go
  pkg/apis/identity/user.go
  pkg/cloudcommon/db/quotas/usageworker.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/users.go
  pkg/keystone/options/options.go
  pkg/keystone/service/localpolicy.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends_mock.go
  vendor/yunion.io/x/sqlchemy/insert.go
Labels: size/M

#13952 fix: fangde desktop
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/fangde.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#13953 Automated cherry pick of #13952: fix: fangde desktop
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/fangde.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#13940 fix(region): google label encode
  pkg/multicloud/google/instance.go
  pkg/multicloud/tag_base.go
  pkg/util/encode/doc.go
  pkg/util/encode/encode.go
  pkg/util/encode/encode_test.go
Labels: size/L, area/region

#13944 Automated cherry pick of #13940: fix(region): google label encode
  pkg/multicloud/google/instance.go
  pkg/multicloud/tag_base.go
  pkg/util/encode/doc.go
  pkg/util/encode/encode.go
  pkg/util/encode/encode_test.go
Labels: size/L

#13945 Automated cherry pick of #13940: fix(region): google label encode
  pkg/multicloud/google/instance.go
  pkg/multicloud/tag_base.go
  pkg/util/encode/doc.go
  pkg/util/encode/encode.go
  pkg/util/encode/encode_test.go
Labels: size/L

#13950 fix: support create encrypt key on create
  pkg/apis/compute/disk.go
  pkg/apis/encrypt.go
  pkg/cloudcommon/db/encrypted.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/image/models/images.go
  pkg/mcclient/modules/identity/mod_credentials.go
Labels: size/M

#13951 Automated cherry pick of #13950: fix: support create encrypt key on create
  pkg/apis/compute/disk.go
  pkg/apis/encrypt.go
  pkg/cloudcommon/db/encrypted.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/image/models/images.go
  pkg/mcclient/modules/identity/mod_credentials.go
Labels: size/M

#13956 fix: disable lock ctx check
  pkg/cloudcommon/db/lockman/lockman.go
Labels: size/XS

#13957 Automated cherry pick of #13956: fix: disable lock ctx check
  pkg/cloudcommon/db/lockman/lockman.go
Labels: size/XS

#13954 fix(region): app replace backgroud ctx
  pkg/appsrv/appsrv.go
  pkg/cloudcommon/db/tenantcachesync.go
  pkg/util/ctx/context.go
  pkg/util/ctx/doc.go
Labels: size/S, area/region

#13955 Automated cherry pick of #13954: fix(region): app replace backgroud ctx
  pkg/appsrv/appsrv.go
  pkg/cloudcommon/db/tenantcachesync.go
  pkg/util/ctx/context.go
  pkg/util/ctx/doc.go
Labels: size/S

#13958 fix(region): cloud lake of permissions
  pkg/cloudprovider/transport.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/business.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/aliyun/ram.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/sts.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/google/google.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L, area/region

#13959 Automated cherry pick of #13958: fix(region): cloud lake of permissions
  pkg/cloudprovider/transport.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/business.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/aliyun/ram.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/sts.go
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/ctyun/ctyun.go
  pkg/multicloud/google/google.go
  pkg/multicloud/hcso/huawei.go
  pkg/multicloud/hcso/region.go
  pkg/multicloud/huawei/huawei.go
  pkg/multicloud/huawei/region.go
  pkg/multicloud/nutanix/nutanix.go
  pkg/multicloud/openstack/openstack.go
  pkg/multicloud/qcloud/qcloud.go
  pkg/multicloud/ucloud/ucloud.go
  pkg/multicloud/zstack/zstack.go
Labels: size/L

#13960 feat(region): kvm qemu version and cmdline info
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: size/S, area/region

#13961 Automated cherry pick of #13960: feat(region): kvm qemu version and cmdline info
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#13962 fix(region): aws all regions
  pkg/multicloud/aws/aws.go
Labels: size/XS, area/region

#13963 Automated cherry pick of #13962: fix(region): aws all regions
  pkg/multicloud/aws/aws.go
Labels: size/XS

#13964 Automated cherry pick of #13962: fix(region): aws all regions
  pkg/multicloud/aws/aws.go
Labels: size/XS

#13965 Automated cherry pick of #13962: fix(region): aws all regions
  pkg/multicloud/aws/aws.go
Labels: size/XS

#13967 fix: create table missing indexes
  go.mod
  go.sum
  pkg/util/splitable/splitable.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/M

#13968 Automated cherry pick of #13967: fix: create table missing indexes
  go.mod
  go.sum
  pkg/util/splitable/splitable.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sync.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/M

#13969 fix: schduler not sync cached image class metadata
  pkg/cloudcommon/db/interface.go
  pkg/compute/models/cachedimages.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/M

#13970 Automated cherry pick of #13969: fix: schduler not sync cached image class metadata
  pkg/cloudcommon/db/interface.go
  pkg/compute/models/cachedimages.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/M

#13971 fix: disk create input preserve encrypt info
  pkg/compute/models/disks.go
Labels: size/XS

#13973 fix: encrypt server cannot attach disk with conflict encrypt key
  pkg/compute/models/guest_actions.go
Labels: size/XS

#13974 Automated cherry pick of #13973: fix: encrypt server cannot attach disk with conflict encrypt key
  pkg/compute/models/guest_actions.go
Labels: size/XS

#13975 fix: more detailed privilege hint
  pkg/cloudcommon/db/fetch.go
Labels: size/XS

#13978 Automated cherry pick of #13975: fix: more detailed privilege hint
  pkg/cloudcommon/db/fetch.go
Labels: size/XS

#13977 Automated cherry pick of #13975: fix: more detailed privilege hint
  pkg/cloudcommon/db/fetch.go
Labels: size/XS

#13976 Automated cherry pick of #13975: fix: more detailed privilege hint
  pkg/cloudcommon/db/fetch.go
Labels: size/XS

#13985 feat(notify): filter notification by topic_type
  cmd/climc/shell/notifyv2/notification.go
  pkg/apis/notify/notification.go
  pkg/notify/models/event.go
  pkg/notify/models/notification.go
  pkg/notify/models/topic.go
Labels: size/M, area/notify

#13986 Automated cherry pick of #13985: feat(notify): filter notification by topic_type
  cmd/climc/shell/notifyv2/notification.go
  pkg/apis/notify/notification.go
  pkg/notify/models/event.go
  pkg/notify/models/notification.go
  pkg/notify/models/topic.go
Labels: size/M

#13979 fix: change qemu default version to 4.2.0
  pkg/hostman/options/options.go
Labels: size/XS

#13980 Automated cherry pick of #13979: fix: change qemu default version to 4.2.0
  pkg/hostman/options/options.go
Labels: size/XS

#13988 fix(README): ocboot use branch release/3.8
  README-CN.md
  README.md
Labels: size/XS

#13989 fix(region): avoid panic
  pkg/compute/models/hosts.go
Labels: size/XS, area/region

#13990 Automated cherry pick of #13989: fix(region): avoid panic
  pkg/compute/models/hosts.go
Labels: size/XS

#13991 Automated cherry pick of #13989: fix(region): avoid panic
  pkg/compute/models/hosts.go
Labels: size/XS

#13992 Automated cherry pick of #13989: fix(region): avoid panic
  pkg/compute/models/hosts.go
Labels: size/XS

#13995 Automated cherry pick of #13987: fix(region): huawei api
  pkg/compute/models/guest_actions.go
  pkg/multicloud/huawei/instance.go
Labels: size/M

#13996 fix: migrate set down time
  pkg/compute/tasks/instance_backup_delete_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/hostinfo/hostpinger.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/S

#13997 Automated cherry pick of #13996: fix: migrate set down time
  pkg/compute/tasks/instance_backup_delete_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/hostinfo/hostpinger.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/S

#13998 fix: adjust admin default permissions
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#13999 Automated cherry pick of #13998: fix: adjust admin default permissions
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#13981 fix(region): multi disk created after instance snapshot
  pkg/compute/models/instance_snapshot_joint.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/M, area/region

#13982 Automated cherry pick of #13981: fix(region): multi disk created after instance snapshot
  pkg/compute/models/instance_snapshot_joint.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/M

#13983 Automated cherry pick of #13981: fix(region): multi disk created after instance snapshot
  pkg/compute/models/instance_snapshot_joint.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/M

#14000 fix: backup bugifxes: 1. not inherit projects of disk. 2. class not inherit by disk 3. fail to creat guest image
  pkg/compute/models/backup.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/disk_backup_recovery_task.go
Labels: size/M

#14001 Automated cherry pick of #14000: fix: backup bugifxes: 1. not inherit projects of disk. 2. class not inherit by disk 3. fail to creat guest image
  pkg/compute/models/backup.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/disk_backup_recovery_task.go
Labels: size/M

#14003 Automated cherry pick of #14002: fix(region): host order by commit rate
  go.mod
  go.sum
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/L

#14004 Automated cherry pick of #14002: fix(region): host order by commit rate
  Makefile
  go.mod
  go.sum
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/errors/consts.go
  vendor/yunion.io/x/pkg/util/regutils/regutils.go
  vendor/yunion.io/x/pkg/util/timeutils/timeutils.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/L

#14005 feat(notify): add topic_type in notification details
  pkg/apis/notify/notification.go
  pkg/notify/models/notification.go
Labels: size/M, area/notify

#14007 fix(region): avoid export duplicate tag key
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S, area/region

#14008 Automated cherry pick of #14007: fix(region): avoid export duplicate tag key
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S

#14009 Automated cherry pick of #14007: fix(region): avoid export duplicate tag key
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S

#14010 Automated cherry pick of #14007: fix(region): avoid export duplicate tag key
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S
