Repository yunionio/cloudpods, pull requests merged in 2022-02, with the labels that each got.

#13373 feature: baremetal tftp send customized files according to a file map
  pkg/baremetal/options/options.go
  pkg/baremetal/pxe/tftp.go
Labels: size/XS

#13374 Automated cherry pick of #13373: feature: baremetal tftp send customized files according to a file map
  pkg/baremetal/options/options.go
  pkg/baremetal/pxe/tftp.go
Labels: size/XS

#13375 Automated cherry pick of #13373: feature: baremetal tftp send customized files according to a file map
  pkg/baremetal/options/options.go
  pkg/baremetal/pxe/tftp.go
Labels: size/XS

#13376 feature: cleanup native hugepage codes
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/util/sysutils/hugepages.go
  pkg/util/sysutils/hugepages_test.go
  pkg/util/zeroclean/doc.go
  pkg/util/zeroclean/zeroclean.go
Labels: area/region, area/host, size/XL

#13377 Automated cherry pick of #13376: feature: cleanup native hugepage codes
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/util/sysutils/hugepages.go
  pkg/util/sysutils/hugepages_test.go
  pkg/util/zeroclean/doc.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/XL

#13378 Automated cherry pick of #13376: feature: cleanup native hugepage codes
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/util/sysutils/hugepages.go
  pkg/util/sysutils/hugepages_test.go
  pkg/util/zeroclean/doc.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/XL

#13379 feat(region,keystone): add enable_tls_migration config
  pkg/apis/identity/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
  pkg/compute/models/guest_actions.go
Labels: size/XS, area/region, area/keystone

#13380 Automated cherry pick of #13379: feat(region,keystone): add enable_tls_migration config
  pkg/apis/identity/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
  pkg/compute/models/guest_actions.go
Labels: size/XS

#13381 Automated cherry pick of #13379: feat(region,keystone): add enable_tls_migration config
  pkg/apis/identity/consts.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
  pkg/compute/models/guest_actions.go
Labels: size/XS

#13382 fix: qemu-img info force share (-U)
  pkg/util/qemuimg/qemuimg.go
Labels: size/XS

#13383 Automated cherry pick of #13382: fix: qemu-img info force share (-U)
  pkg/util/qemuimg/qemuimg.go
Labels: size/XS

#13384 fix: qemu-img info force share (-U) 3.8
  pkg/util/qemuimg/qemuimg.go
Labels: size/XS

#13385 fix(host): add space before -object memory-backend-ram
  pkg/hostman/guestman/qemu-arm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS, area/host

#13386 fix(host): dist prepare migrate_certs
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/S, area/host

#13388 Automated cherry pick of #13386: fix(host): dist prepare migrate_certs
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/S

#13387 Automated cherry pick of #13386: fix(host): dist prepare migrate_certs
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/S

#13389 fix(region): batch migrate use enable_tls_migration option
  pkg/apis/compute/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/host_guests_migrate_task.go
Labels: size/S, area/region

#13390 Automated cherry pick of #13389: fix(region): batch migrate use enable_tls_migration option
  pkg/apis/compute/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/host_guests_migrate_task.go
Labels: size/S

#13391 Automated cherry pick of #13389: fix(region): batch migrate use enable_tls_migration option
  pkg/apis/compute/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/host_guests_migrate_task.go
Labels: size/S

#13393 Automated cherry pick of #13392: fix(host): make tls-creds empty when no tls migrate
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#13394 Automated cherry pick of #13392: fix(host): make tls-creds empty when no tls migrate
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#13397 Automated cherry pick of #13396: fix(host): sparse file seek
  pkg/util/sparsefile/sparse.go
Labels: size/XS

#13398 fix(region): huawei routetable
  pkg/apis/compute/routetable_routesets.go
  pkg/compute/models/routetable_routesets.go
  pkg/multicloud/aliyun/cloud_enterprise_network_route.go
  pkg/multicloud/aliyun/routetable.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/route.go
  pkg/multicloud/hcso/routetable.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/mod_routetables.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/routetable.go
  pkg/multicloud/huawei/routetables.go
  pkg/multicloud/huawei/shell/routetable.go
  pkg/multicloud/huawei/vpc.go
  pkg/multicloud/qcloud/cloud_connect_network_route.go
  pkg/multicloud/qcloud/route_table.go
  pkg/vpcagent/ovn/routes.go
Labels: area/region, size/XL

#13400 Automated cherry pick of #13398: fix(region): huawei routetable
  pkg/apis/compute/routetable_routesets.go
  pkg/compute/models/routetable_routesets.go
  pkg/multicloud/aliyun/cloud_enterprise_network_route.go
  pkg/multicloud/aliyun/routetable.go
  pkg/multicloud/aws/network.go
  pkg/multicloud/aws/route.go
  pkg/multicloud/hcso/routetable.go
  pkg/multicloud/huawei/client/client.go
  pkg/multicloud/huawei/client/modules/mod_routetables.go
  pkg/multicloud/huawei/provider/provider.go
  pkg/multicloud/huawei/routetable.go
  pkg/multicloud/huawei/routetables.go
  pkg/multicloud/huawei/shell/routetable.go
  pkg/multicloud/huawei/vpc.go
  pkg/multicloud/qcloud/cloud_connect_network_route.go
  pkg/multicloud/qcloud/route_table.go
  pkg/vpcagent/ovn/routes.go
Labels: size/XL

#13405 Automated cherry pick of #13404: fix(cloudmon): fix Apsara elb metric
  pkg/cloudmon/collectors/apsaramon/apsaraservice.go
  pkg/cloudmon/collectors/apsaramon/apsarautils.go
  pkg/cloudmon/collectors/common/basemon.go
Labels: size/S

#13401 fix(baremetal): add boot_loader syslinux and grub option
  pkg/baremetal/manager.go
  pkg/baremetal/nic.go
  pkg/baremetal/options/options.go
  pkg/baremetal/service/service.go
Labels: size/M, area/baremetal

#13402 Automated cherry pick of #13401: fix(baremetal): add boot_loader syslinux and grub option
  pkg/baremetal/manager.go
  pkg/baremetal/nic.go
  pkg/baremetal/options/options.go
  pkg/baremetal/service/service.go
Labels: size/M

#13411 feature: policy import/export utils
  cmd/climc/shell/identity/policies.go
Labels: size/M

#13412 Automated cherry pick of #13411: feature: policy import/export utils
  cmd/climc/shell/identity/policies.go
Labels: size/M

#13408 Automated cherry pick of #13406: fix(region): skip first sync waf rule
  pkg/compute/models/waf_rule_groups.go
  pkg/compute/models/waf_rules.go
Labels: size/S

#13415 fix(region): action log
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/M, area/region

#13417 Automated cherry pick of #13415: fix(region): action log
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/M

#13418 Automated cherry pick of #13415: fix(region): action log
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/M

#13414 feat(baremetal): grub http boot initrd and kernel
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/baremetal/utils/grub/grub.go
Labels: size/S, area/baremetal

#13416 Automated cherry pick of #13414: feat(baremetal): grub http boot initrd and kernel
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/baremetal/utils/grub/grub.go
Labels: size/S

#13419 fix(region): vm_sync_isolated_device i18n
  pkg/util/logclient/consts_i18n.go
Labels: size/XS, area/region

#13421 Automated cherry pick of #13419: fix(region): vm_sync_isolated_device i18n
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#13436 fix: missing instance type for cloned server
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/tasks/disk_create_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
Labels: size/L

#13437 Automated cherry pick of #13436: fix: missing instance type for cloned server
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/tasks/disk_create_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
Labels: size/L

#13438 Automated cherry pick of #13436: fix: missing instance type for cloned server
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/tasks/disk_create_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
Labels: size/L

#13433 feature: customizable totp issuer string
  pkg/apigateway/handler/auth_totp.go
  pkg/apigateway/options/options.go
Labels: size/S

#13434 Automated cherry pick of #13433: feature: customizable totp issuer string
  pkg/apigateway/handler/auth_totp.go
  pkg/apigateway/options/options.go
Labels: size/S

#13435 Automated cherry pick of #13433: feature: customizable totp issuer string
  pkg/apigateway/handler/auth_totp.go
  pkg/apigateway/options/options.go
Labels: size/S

#13430 feature: local user add need_reset_password field
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/user.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/users.go
Labels: size/M

#13431 Automated cherry pick of #13430: feature: local user add need_reset_password field
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/user.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/users.go
Labels: size/M

#13426 fix: delay block stream after server start
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#13427 Automated cherry pick of #13426: fix: delay block stream after server start
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#13428 Automated cherry pick of #13426: fix: delay block stream after server start
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#13429 Automated cherry pick of #13426: fix: delay block stream after server start
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#13409 fix(region): associate manager with external project
  pkg/cloudprovider/resources.go
  pkg/compute/models/external_projects.go
  pkg/multicloud/apsara/organization.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/resourcegroup.go
  pkg/multicloud/project_base.go
Labels: size/M, area/region

#13410 Automated cherry pick of #13409: fix(region): associate manager with external project
  pkg/cloudprovider/resources.go
  pkg/compute/models/external_projects.go
  pkg/multicloud/apsara/organization.go
  pkg/multicloud/apsara/project.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/resourcegroup.go
  pkg/multicloud/project_base.go
Labels: size/M

#13439 fix: delete disk skip recycle_bin
  pkg/apis/compute/disk.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#13440 Automated cherry pick of #13439: fix: delete disk skip recycle_bin
  pkg/apis/compute/disk.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#13441 Automated cherry pick of #13439: fix: delete disk skip recycle_bin
  pkg/apis/compute/disk.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#13443 fix(region): minio s3 object set acl error
  pkg/multicloud/objectstore/object.go
Labels: size/XS, area/region

#13444 Automated cherry pick of #13443: fix(region): minio s3 object set acl error
  pkg/multicloud/objectstore/object.go
Labels: size/XS

#13445 Automated cherry pick of #13443: fix(region): minio s3 object set acl error
  pkg/multicloud/objectstore/object.go
Labels: size/XS

#13446 fix(host): arm qemu remove -no-kvm
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/S, area/host

#13447 Automated cherry pick of #13446: fix(host): arm qemu remove -no-kvm
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/S

#13442 fix: filter server by vip or eip of vip
  pkg/apis/compute/guests.go
  pkg/apis/compute/instance_group.go
  pkg/compute/models/groups.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
Labels: size/L

#13449 Automated cherry pick of #13442: fix: filter server by vip or eip of vip
  pkg/apis/compute/guests.go
  pkg/apis/compute/instance_group.go
  pkg/compute/models/groups.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
Labels: size/L

#13450 Automated cherry pick of #13442: fix: filter server by vip or eip of vip
  pkg/apis/compute/guests.go
  pkg/apis/compute/instance_group.go
  pkg/compute/models/groups.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
Labels: size/L

#13454 fix(host): aarch64 vm usb id duplicated
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: lgtm, size/XS, area/host

#13455 Automated cherry pick of #13454: fix(host): aarch64 vm usb id duplicated
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#13456 Automated cherry pick of #13454: fix(host): aarch64 vm usb id duplicated
  pkg/hostman/guestman/qemu-arm.go
Labels: size/XS

#13451 fix: class network mtu should consider default_mtu
  pkg/compute/models/networks.go
Labels: size/XS

#13452 Automated cherry pick of #13451: fix: class network mtu should consider default_mtu
  pkg/compute/models/networks.go
Labels: size/XS

#13453 Automated cherry pick of #13451: fix: class network mtu should consider default_mtu
  pkg/compute/models/networks.go
Labels: size/XS

#13460 fix(region): qcloud tdsql tags
  pkg/multicloud/qcloud/rds_tdsql.go
  pkg/multicloud/tag_base.go
Labels: size/S, area/region

#13461 Automated cherry pick of #13460: fix(region): qcloud tdsql tags
  pkg/multicloud/qcloud/rds_tdsql.go
  pkg/multicloud/tag_base.go
Labels: size/S

#13462 Automated cherry pick of #13460: fix(region): qcloud tdsql tags
  pkg/multicloud/qcloud/rds_tdsql.go
  pkg/multicloud/tag_base.go
Labels: size/S

#13466 fix(baremetal): grub msdos partition detected
  pkg/baremetal/utils/grub/grub.go
Labels: size/XS, area/baremetal

#13467 Automated cherry pick of #13466: fix(baremetal): grub msdos partition detected
  pkg/baremetal/utils/grub/grub.go
Labels: size/XS

#13463 fix(region): tag key export
  pkg/cloudcommon/db/standalone.go
Labels: size/XS, area/region

#13465 Automated cherry pick of #13463: fix(region): tag key export
  pkg/cloudcommon/db/standalone.go
Labels: size/XS

#13457 fix(keyston): add sync log for ldap
  pkg/keystone/models/syncworker.go
Labels: size/XS, area/keystone

#13458 Automated cherry pick of #13457: fix(keyston): add sync log for ldap
  pkg/keystone/models/syncworker.go
Labels: size/XS

#13468 fix(glance): image statistics
  cmd/climc/shell/image/images.go
  pkg/mcclient/modules/image/mod_images.go
  pkg/mcclient/options/glance/doc.go
  pkg/mcclient/options/glance/image.go
Labels: size/L, area/image

#13469 Automated cherry pick of #13468: fix(glance): image statistics
  cmd/climc/shell/image/images.go
  pkg/mcclient/modules/image/mod_images.go
  pkg/mcclient/options/glance/doc.go
  pkg/mcclient/options/glance/image.go
Labels: size/L

#13470 Automated cherry pick of #13468: fix(glance): image statistics
  cmd/climc/shell/image/images.go
  pkg/mcclient/modules/mod_images.go
  pkg/mcclient/options/glance/doc.go
  pkg/mcclient/options/glance/image.go
Labels: size/L

#13472 Automated cherry pick of #13341: feat(host): transfer sparse file over network
  cmd/climc/shell/compute/disks.go
  go.mod
  go.sum
  pkg/hostman/downloader/downloader.go
  pkg/hostman/downloader/downloadhandler.go
  pkg/hostman/downloader/guest_downloader.go
  pkg/hostman/downloader/image_downloader.go
  pkg/hostman/downloader/imagecache_downloader.go
  pkg/hostman/downloader/snapshot_downloader.go
  pkg/hostman/storageman/remotefile/remotefile.go
  pkg/util/pb/doc.go
  pkg/util/pb/pb.go
  pkg/util/sparsefile/doc.go
  pkg/util/sparsefile/hole_other.go
  pkg/util/sparsefile/hole_unix.go
  pkg/util/sparsefile/sparse.go
  vendor/github.com/VividCortex/ewma/.gitignore
  vendor/github.com/VividCortex/ewma/LICENSE
  vendor/github.com/VividCortex/ewma/README.md
  vendor/github.com/VividCortex/ewma/ewma.go
  vendor/github.com/cheggaaa/pb/v3/LICENSE
  vendor/github.com/cheggaaa/pb/v3/element.go
  vendor/github.com/cheggaaa/pb/v3/go.mod
  vendor/github.com/cheggaaa/pb/v3/go.sum
  vendor/github.com/cheggaaa/pb/v3/io.go
  vendor/github.com/cheggaaa/pb/v3/pb.go
  vendor/github.com/cheggaaa/pb/v3/preset.go
  vendor/github.com/cheggaaa/pb/v3/speed.go
  vendor/github.com/cheggaaa/pb/v3/template.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_appengine.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_bsd.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_linux.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_nix.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_plan9.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_solaris.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_win.go
  vendor/github.com/cheggaaa/pb/v3/termutil/term_x.go
  vendor/github.com/cheggaaa/pb/v3/util.go
  vendor/modules.txt
Labels: size/XXL

#13473 Automated cherry pick of #13396: fix(host): sparse file seek
  pkg/util/sparsefile/sparse.go
Labels: size/XS

#13474 fix(region): swagger server create count ignore
  pkg/apis/compute/api.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
Labels: size/L, area/region

#13371 Classification of resources
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/identity/projects.go
  pkg/apis/cloudcommon/db/metadata.go
  pkg/apis/compute/cachedimage.go
  pkg/apis/const.go
  pkg/apis/image/consts.go
  pkg/apis/input.go
  pkg/apis/scheduler/api.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/backup.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/image/tasks/image_sync_classmetadata_task.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/test/mock/core.go
  pkg/util/logclient/consts.go
Labels: area/region, area/scheduler, area/image, size/XL

#13372 Automated cherry pick of #13371: Classification of resources
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/identity/projects.go
  pkg/apis/cloudcommon/db/metadata.go
  pkg/apis/compute/cachedimage.go
  pkg/apis/const.go
  pkg/apis/image/consts.go
  pkg/apis/input.go
  pkg/apis/scheduler/api.go
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/backup.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/models/snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/image/tasks/image_sync_classmetadata_task.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
  pkg/scheduler/algorithmprovider/defaults.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/core/types.go
  pkg/scheduler/test/mock/core.go
  pkg/util/logclient/consts.go
Labels: size/XL

#13482 Automated cherry pick of #13481: Fix for secret/resource
  pkg/cloudcommon/db/standalone_anon.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/image/models/images.go
Labels: size/M

#13486 fix(region): send SERVER_DELETE event notify when guest is actually deleted
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS, area/region

#13487 Automated cherry pick of #13486: fix(region): send SERVER_DELETE event notify when guest is actually deleted
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#13488 Automated cherry pick of #13486: fix(region): send SERVER_DELETE event notify when guest is actually deleted
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#13485 fix(baremetal): update baremetal-base image version
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
Labels: size/XS, area/baremetal

#13492 Automated cherry pick of #13485: fix(baremetal): update baremetal-base image version
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
Labels: size/XS

#13478 fix(climc): server create with disk desc
  cmd/climc/shell/compute/servers.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L, area/climc

#13479 Automated cherry pick of #13478: fix(climc): server create with disk desc
  cmd/climc/shell/compute/servers.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#13489 feat(climc): add public and private for backupstorage
  cmd/climc/shell/compute/backup.go
Labels: size/XS, area/climc

#13490 Automated cherry pick of #13489: feat(climc): add public and private for backupstorage
  cmd/climc/shell/compute/backup.go
Labels: size/XS

#13491 Automated cherry pick of #13489: feat(climc): add public and private for backupstorage
  cmd/climc/shell/compute/backup.go
Labels: size/XS

#13504 fix: user create user nil pointer error
  pkg/keystone/models/localusers.go
Labels: size/XS

#13505 Automated cherry pick of #13504: fix: user create user nil pointer error
  pkg/keystone/models/localusers.go
Labels: size/XS

#13507 Automated cherry pick of #13504: fix: user create user nil pointer error
  pkg/keystone/models/localusers.go
Labels: size/XS

#13502 fix(climc): log purge
  cmd/climc/shell/cloudevent/cloudevents.go
  cmd/climc/shell/cloudevent/common.go
  cmd/climc/shell/events/events.go
  cmd/climc/shell/events/splitable.go
  pkg/apis/input.go
  pkg/cloudcommon/db/modelbase.go
  pkg/mcclient/modules/cloudevent/mod_cloudevents.go
  pkg/mcclient/modules/compute/mod_logs.go
  pkg/mcclient/modules/identity/mod_identity.go
  pkg/mcclient/modules/image/mod_images.go
  pkg/mcclient/modules/logger/mod_actions.go
  pkg/mcclient/modules/mod_logs.go
  pkg/mcclient/options/logs.go
  pkg/util/splitable/purge.go
Labels: size/L, area/region

#13503 Automated cherry pick of #13502: fix(climc): log purge
  cmd/climc/shell/cloudevent/cloudevents.go
  cmd/climc/shell/cloudevent/common.go
  cmd/climc/shell/events/events.go
  cmd/climc/shell/events/splitable.go
  pkg/apis/input.go
  pkg/cloudcommon/db/modelbase.go
  pkg/mcclient/modules/cloudevent/mod_cloudevents.go
  pkg/mcclient/modules/compute/mod_logs.go
  pkg/mcclient/modules/identity/mod_identity.go
  pkg/mcclient/modules/image/mod_images.go
  pkg/mcclient/modules/logger/mod_actions.go
  pkg/mcclient/modules/mod_logs.go
  pkg/mcclient/options/logs.go
  pkg/util/splitable/purge.go
Labels: size/L

#13499 feature: policy limited by time range
  pkg/apis/identity/policy.go
  pkg/apis/identity/rolepolicy.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
  pkg/keystone/service/localpolicy.go
  pkg/keystone/tokens/policy.go
  pkg/keystone/tokens/token.go
Labels: size/M

#13500 Automated cherry pick of #13499: feature: policy limited by time range
  pkg/apis/identity/policy.go
  pkg/apis/identity/rolepolicy.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
  pkg/keystone/service/localpolicy.go
  pkg/keystone/tokens/policy.go
  pkg/keystone/tokens/token.go
Labels: size/M

#13493 fix(host-image): update build flags
  Makefile
Labels: lgtm, size/XS, area/util

#13496 fix(host): add host online offline log
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L, area/host

#13497 Automated cherry pick of #13496: fix(host): add host online offline log
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#13498 Automated cherry pick of #13496: fix(host): add host online offline log
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#13509 Automated cherry pick of #13508: fix(region): live migrate skip_kernel_check api
  pkg/apis/compute/api.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/host_guests_migrate_task.go
Labels: size/M

#13511 fix(host): ceph df with total_bytes
  pkg/util/cephutils/ceph.go
Labels: size/XS, area/host

#13512 Automated cherry pick of #13511: fix(host): ceph df with total_bytes
  pkg/util/cephutils/ceph.go
Labels: size/XS

#13513 Automated cherry pick of #13511: fix(host): ceph df with total_bytes
  pkg/util/cephutils/ceph.go
Labels: size/XS

#13515 fix(host): host register
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L, area/host

#13516 Automated cherry pick of #13515: fix(host): host register
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#13517 Automated cherry pick of #13515: fix(host): host register
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#13514 fix(host): ceph df size
  pkg/hostman/storageman/storage_rbd.go
Labels: size/XS, area/host

#13521 fix(region): delete disk actually when cleaning disks
  pkg/compute/models/disks.go
Labels: size/XS, area/region

#13524 Automated cherry pick of #13521: fix(region): delete disk actually when cleaning disks
  pkg/compute/models/disks.go
Labels: size/XS

#13522 Automated cherry pick of #13521: fix(region): delete disk actually when cleaning disks
  pkg/compute/models/disks.go
Labels: size/XS

#13523 Automated cherry pick of #13521: fix(region): delete disk actually when cleaning disks
  pkg/compute/models/disks.go
Labels: size/XS

#13518 fix(region): vm nic sync with network
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
Labels: size/S, area/region

#13519 Automated cherry pick of #13518: fix(region): vm nic sync with network
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
Labels: size/S

#13520 Automated cherry pick of #13518: fix(region): vm nic sync with network
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
Labels: size/S

#13526 Automated cherry pick of #13525: feat(region,host): support packing and unpacking instancebackup
  cmd/climc/shell/compute/backup.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/instance_backup.go
  pkg/apis/compute/zz_generated.model.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/backup.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/instance_backup_pack_task.go
  pkg/compute/tasks/instance_backup_recovery_task.go
  pkg/compute/tasks/instance_backup_unpack_task.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/mcclient/options/compute/backup.go
  pkg/util/logclient/consts.go
Labels: size/XL

#13525 feat(region,host): support packing and unpacking instancebackup
  cmd/climc/shell/compute/backup.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/instance_backup.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/backup.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/instance_backup_pack_task.go
  pkg/compute/tasks/instance_backup_recovery_task.go
  pkg/compute/tasks/instance_backup_unpack_task.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/mcclient/options/compute/backup.go
  pkg/util/logclient/consts.go
Labels: area/region, area/host, size/XL

#13527 feat(region,host): server cpuset supported
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  go.mod
  go.sum
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/apis/host/types.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_cpuset_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/hostutils/hardware/cpu.go
  pkg/hostman/hostutils/hardware/doc.go
  pkg/hostman/hostutils/hardware/topology.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
  vendor/github.com/StackExchange/wmi/swbemservices.go
  vendor/github.com/StackExchange/wmi/wmi.go
  vendor/github.com/go-ole/go-ole/.travis.yml
  vendor/github.com/go-ole/go-ole/go.mod
  vendor/github.com/go-ole/go-ole/go.sum
  vendor/github.com/jaypipes/ghw/COPYING
  vendor/github.com/jaypipes/ghw/pkg/context/context.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_stub.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_windows.go
  vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go
  vendor/github.com/jaypipes/ghw/pkg/marshal/marshal.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_cache.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_cache_linux.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_stub.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_windows.go
  vendor/github.com/jaypipes/ghw/pkg/option/option.go
  vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_block.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_gpu.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_net.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_pci.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/testdata.tar.gz
  vendor/github.com/jaypipes/ghw/pkg/snapshot/trace.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/unpack.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology_linux.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology_stub.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology_windows.go
  vendor/github.com/jaypipes/ghw/pkg/unitutil/unit.go
  vendor/github.com/jaypipes/ghw/pkg/util/util.go
  vendor/modules.txt
Labels: size/XXL, area/region, area/host

#13528 Automated cherry pick of #13527: feat(region,host): server cpuset supported
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  go.mod
  go.sum
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/apis/host/types.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_cpuset_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/hostutils/hardware/cpu.go
  pkg/hostman/hostutils/hardware/doc.go
  pkg/hostman/hostutils/hardware/topology.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
  vendor/github.com/StackExchange/wmi/swbemservices.go
  vendor/github.com/StackExchange/wmi/wmi.go
  vendor/github.com/go-ole/go-ole/.travis.yml
  vendor/github.com/go-ole/go-ole/go.mod
  vendor/github.com/go-ole/go-ole/go.sum
  vendor/github.com/jaypipes/ghw/COPYING
  vendor/github.com/jaypipes/ghw/pkg/context/context.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_stub.go
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_windows.go
  vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go
  vendor/github.com/jaypipes/ghw/pkg/marshal/marshal.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_cache.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_cache_linux.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_stub.go
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_windows.go
  vendor/github.com/jaypipes/ghw/pkg/option/option.go
  vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_block.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_gpu.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_net.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_pci.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/testdata.tar.gz
  vendor/github.com/jaypipes/ghw/pkg/snapshot/trace.go
  vendor/github.com/jaypipes/ghw/pkg/snapshot/unpack.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology_linux.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology_stub.go
  vendor/github.com/jaypipes/ghw/pkg/topology/topology_windows.go
  vendor/github.com/jaypipes/ghw/pkg/unitutil/unit.go
  vendor/github.com/jaypipes/ghw/pkg/util/util.go
  vendor/modules.txt
Labels: size/XXL

#13531 fix(region): init scalinggroup controller in correct order
  pkg/controller/autoscaling/controller.go
Labels: size/M, area/region

#13532 Automated cherry pick of #13531: fix(region): init scalinggroup controller in correct order
  pkg/controller/autoscaling/controller.go
Labels: size/M

#13533 Automated cherry pick of #13531: fix(region): init scalinggroup controller in correct order
  pkg/controller/autoscaling/controller.go
Labels: size/M

#13480 fix(climc): support --help args
  cmd/climc/entry/climc.go
  cmd/climc/promputils/executor.go
  go.mod
  go.sum
  vendor/github.com/c-bata/go-prompt/.gitignore
  vendor/github.com/c-bata/go-prompt/CHANGELOG.md
  vendor/github.com/c-bata/go-prompt/DEVELOPER_GUIDE.md
  vendor/github.com/c-bata/go-prompt/Gopkg.lock
  vendor/github.com/c-bata/go-prompt/Gopkg.toml
  vendor/github.com/c-bata/go-prompt/Makefile
  vendor/github.com/c-bata/go-prompt/README.md
  vendor/github.com/c-bata/go-prompt/bisect.go
  vendor/github.com/c-bata/go-prompt/buffer.go
  vendor/github.com/c-bata/go-prompt/completion.go
  vendor/github.com/c-bata/go-prompt/document.go
  vendor/github.com/c-bata/go-prompt/emacs.go
  vendor/github.com/c-bata/go-prompt/filter.go
  vendor/github.com/c-bata/go-prompt/go.mod
  vendor/github.com/c-bata/go-prompt/go.sum
  vendor/github.com/c-bata/go-prompt/input.go
  vendor/github.com/c-bata/go-prompt/input_posix.go
  vendor/github.com/c-bata/go-prompt/input_windows.go
  vendor/github.com/c-bata/go-prompt/internal/bisect/bisect.go
  vendor/github.com/c-bata/go-prompt/internal/debug/assert.go
  vendor/github.com/c-bata/go-prompt/internal/debug/log.go
  vendor/github.com/c-bata/go-prompt/internal/strings/strings.go
  vendor/github.com/c-bata/go-prompt/internal/term/raw.go
  vendor/github.com/c-bata/go-prompt/internal/term/term.go
  vendor/github.com/c-bata/go-prompt/key.go
  vendor/github.com/c-bata/go-prompt/key_bind.go
  vendor/github.com/c-bata/go-prompt/key_bind_func.go
  vendor/github.com/c-bata/go-prompt/option.go
  vendor/github.com/c-bata/go-prompt/output.go
  vendor/github.com/c-bata/go-prompt/output_posix.go
  vendor/github.com/c-bata/go-prompt/output_vt100.go
  vendor/github.com/c-bata/go-prompt/output_windows.go
  vendor/github.com/c-bata/go-prompt/posix_input.go
  vendor/github.com/c-bata/go-prompt/posix_output.go
  vendor/github.com/c-bata/go-prompt/prompt.go
  vendor/github.com/c-bata/go-prompt/render.go
  vendor/github.com/c-bata/go-prompt/shortcut.go
  vendor/github.com/c-bata/go-prompt/signal_posix.go
  vendor/github.com/c-bata/go-prompt/signal_windows.go
  vendor/github.com/c-bata/go-prompt/windows_input.go
  vendor/github.com/c-bata/go-prompt/windows_output.go
  vendor/github.com/pkg/term/termios/ioctl.go
  vendor/github.com/pkg/term/termios/ioctl_solaris.go
  vendor/github.com/pkg/term/termios/pty.go
  vendor/github.com/pkg/term/termios/pty_darwin.go
  vendor/github.com/pkg/term/termios/pty_freebsd.go
  vendor/github.com/pkg/term/termios/pty_linux.go
  vendor/github.com/pkg/term/termios/termios.go
  vendor/github.com/pkg/term/termios/termios_bsd.go
  vendor/github.com/pkg/term/termios/termios_linux.go
  vendor/github.com/pkg/term/termios/termios_solaris.go
  vendor/modules.txt
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/XXL, area/climc

#13535 Automated cherry pick of #13480: fix(climc): support --help args
  cmd/climc/entry/climc.go
  cmd/climc/promputils/executor.go
  go.mod
  go.sum
  vendor/github.com/c-bata/go-prompt/.gitignore
  vendor/github.com/c-bata/go-prompt/CHANGELOG.md
  vendor/github.com/c-bata/go-prompt/DEVELOPER_GUIDE.md
  vendor/github.com/c-bata/go-prompt/Gopkg.lock
  vendor/github.com/c-bata/go-prompt/Gopkg.toml
  vendor/github.com/c-bata/go-prompt/Makefile
  vendor/github.com/c-bata/go-prompt/README.md
  vendor/github.com/c-bata/go-prompt/bisect.go
  vendor/github.com/c-bata/go-prompt/buffer.go
  vendor/github.com/c-bata/go-prompt/completion.go
  vendor/github.com/c-bata/go-prompt/document.go
  vendor/github.com/c-bata/go-prompt/emacs.go
  vendor/github.com/c-bata/go-prompt/filter.go
  vendor/github.com/c-bata/go-prompt/go.mod
  vendor/github.com/c-bata/go-prompt/go.sum
  vendor/github.com/c-bata/go-prompt/input.go
  vendor/github.com/c-bata/go-prompt/input_posix.go
  vendor/github.com/c-bata/go-prompt/input_windows.go
  vendor/github.com/c-bata/go-prompt/internal/bisect/bisect.go
  vendor/github.com/c-bata/go-prompt/internal/debug/assert.go
  vendor/github.com/c-bata/go-prompt/internal/debug/log.go
  vendor/github.com/c-bata/go-prompt/internal/strings/strings.go
  vendor/github.com/c-bata/go-prompt/internal/term/raw.go
  vendor/github.com/c-bata/go-prompt/internal/term/term.go
  vendor/github.com/c-bata/go-prompt/key.go
  vendor/github.com/c-bata/go-prompt/key_bind.go
  vendor/github.com/c-bata/go-prompt/key_bind_func.go
  vendor/github.com/c-bata/go-prompt/option.go
  vendor/github.com/c-bata/go-prompt/output.go
  vendor/github.com/c-bata/go-prompt/output_posix.go
  vendor/github.com/c-bata/go-prompt/output_vt100.go
  vendor/github.com/c-bata/go-prompt/output_windows.go
  vendor/github.com/c-bata/go-prompt/posix_input.go
  vendor/github.com/c-bata/go-prompt/posix_output.go
  vendor/github.com/c-bata/go-prompt/prompt.go
  vendor/github.com/c-bata/go-prompt/render.go
  vendor/github.com/c-bata/go-prompt/shortcut.go
  vendor/github.com/c-bata/go-prompt/signal_posix.go
  vendor/github.com/c-bata/go-prompt/signal_windows.go
  vendor/github.com/c-bata/go-prompt/windows_input.go
  vendor/github.com/c-bata/go-prompt/windows_output.go
  vendor/github.com/pkg/term/termios/ioctl.go
  vendor/github.com/pkg/term/termios/ioctl_solaris.go
  vendor/github.com/pkg/term/termios/pty.go
  vendor/github.com/pkg/term/termios/pty_darwin.go
  vendor/github.com/pkg/term/termios/pty_freebsd.go
  vendor/github.com/pkg/term/termios/pty_linux.go
  vendor/github.com/pkg/term/termios/termios.go
  vendor/github.com/pkg/term/termios/termios_bsd.go
  vendor/github.com/pkg/term/termios/termios_linux.go
  vendor/github.com/pkg/term/termios/termios_solaris.go
  vendor/modules.txt
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/XXL

#13510 fix: allow IDP initiated SAML login
  cmd/climc/shell/identity/identityproviders.go
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/idp.go
  pkg/apis/identity/identityprovider.go
  pkg/apis/identity/saml.go
  pkg/keystone/driver/base.go
  pkg/keystone/driver/driver.go
  pkg/keystone/driver/saml/class.go
  pkg/keystone/driver/saml/saml.go
  pkg/keystone/models/identity_provider.go
Labels: size/L

#13530 Automated cherry pick of #13510: fix: allow IDP initiated SAML login
  cmd/climc/shell/identity/identityproviders.go
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/idp.go
  pkg/apis/identity/identityprovider.go
  pkg/apis/identity/saml.go
  pkg/keystone/driver/base.go
  pkg/keystone/driver/driver.go
  pkg/keystone/driver/saml/class.go
  pkg/keystone/driver/saml/saml.go
  pkg/keystone/models/identity_provider.go
Labels: size/L

#13541 fix(region): call parent's PostCreate in virtualResourceBase.PostCreate
  pkg/cloudcommon/db/virtualresource.go
Labels: lgtm, size/XS, area/region

#13542 Automated cherry pick of #13541: fix(region): call parent's PostCreate in virtualResourceBase.PostCreate
  pkg/cloudcommon/db/virtualresource.go
Labels: size/XS

#13543 fix(host): arm kvm duplicate video0 device
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS, area/host

#13544 Automated cherry pick of #13543: fix(host): arm kvm duplicate video0 device
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#13536 fix(region): nutanix nic sync
  pkg/multicloud/nutanix/instancenic.go
Labels: size/XS, area/region

#13537 Automated cherry pick of #13536: fix(region): nutanix nic sync
  pkg/multicloud/nutanix/instancenic.go
Labels: size/XS

#13538 Automated cherry pick of #13536: fix(region): nutanix nic sync
  pkg/multicloud/nutanix/instancenic.go
Labels: size/XS

#13477 Automated cherry pick of #13471: fix(region): project tags filter for usages
  pkg/compute/models/storages.go
  pkg/compute/usages/cache.go
  pkg/compute/usages/handler.go
  pkg/image/usages/handler.go
  pkg/keystone/usages/handler.go
Labels: size/M

#13548 feat(region): add server-cpuset-cores cmd to get pinned and usable cores
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: size/M, area/region

#13549 Automated cherry pick of #13548: feat(region): add server-cpuset-cores cmd to get pinned and usable cores
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: size/M

#13551 fix: update README indicate that ssh private key without passphrase
  README-CN.md
  README.md
Labels: size/M

#13293 fix(glance): convert image in s3 storage
  pkg/image/models/image_subs.go
  pkg/image/models/storage.go
Labels: size/L, area/image

#13294 Automated cherry pick of #13293: fix(glance): convert image in s3 storage
  pkg/image/models/image_subs.go
  pkg/image/models/storage.go
Labels: size/L

#13295 Automated cherry pick of #13293: fix(glance): convert image in s3 storage
  pkg/image/models/image_subs.go
  pkg/image/models/storage.go
Labels: size/L

#13296 Automated cherry pick of #13293: fix(glance): convert image in s3 storage
  pkg/image/models/image_subs.go
  pkg/image/models/storage.go
Labels: size/L

#13529 fix(region): aws rds create
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/dbinstance_const.go
  pkg/apis/const.go
  pkg/cloudprovider/dbinstance.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/resource_syncstatus.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_change_config.go
  pkg/compute/tasks/dbinstance_create_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/dbinstance_renew_task.go
  pkg/compute/tasks/dbinstance_set_auto_renew_task.go
  pkg/compute/tasks/dbinstance_sync_secgroups_task.go
  pkg/compute/tasks/dbinstance_sync_status_task.go
  pkg/compute/tasks/dbinstance_sync_task.go
  pkg/mcclient/options/compute/dbinstances.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/dbinstance_const.go
  pkg/multicloud/aws/dbinstance_snapshot.go
  pkg/multicloud/aws/shell/dbinstance.go
  pkg/multicloud/aws/shell/dbinstance_snapshot.go
  pkg/multicloud/tag_base.go
Labels: area/region, size/XL

#13550 Automated cherry pick of #13529: fix(region): aws rds create
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/dbinstance_const.go
  pkg/apis/const.go
  pkg/cloudprovider/dbinstance.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/resource_syncstatus.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/dbinstance_change_config.go
  pkg/compute/tasks/dbinstance_create_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/dbinstance_remote_update_task.go
  pkg/compute/tasks/dbinstance_renew_task.go
  pkg/compute/tasks/dbinstance_set_auto_renew_task.go
  pkg/compute/tasks/dbinstance_sync_secgroups_task.go
  pkg/compute/tasks/dbinstance_sync_status_task.go
  pkg/compute/tasks/dbinstance_sync_task.go
  pkg/mcclient/options/compute/dbinstances.go
  pkg/multicloud/aws/aws.go
  pkg/multicloud/aws/aws_request.go
  pkg/multicloud/aws/dbinstance.go
  pkg/multicloud/aws/dbinstance_const.go
  pkg/multicloud/aws/dbinstance_snapshot.go
  pkg/multicloud/aws/shell/dbinstance.go
  pkg/multicloud/aws/shell/dbinstance_snapshot.go
  pkg/multicloud/tag_base.go
Labels: size/XL
