Repository yunionio/cloudpods, pull requests merged in 2022-08, with the labels that each got.

#14744 fix(region): sync domain_id to kubeserver
  pkg/compute/models/kube_clusters.go
Labels: size/XS, area/region

#14745 Automated cherry pick of #14744: fix(region): sync domain_id to kubeserver
  pkg/compute/models/kube_clusters.go
Labels: size/XS

#14747 fix(region): incloudsphere image
  pkg/multicloud/incloudsphere/host.go
  pkg/multicloud/incloudsphere/image.go
  pkg/multicloud/incloudsphere/instance.go
  pkg/multicloud/incloudsphere/region.go
  pkg/multicloud/incloudsphere/shell/image.go
  pkg/multicloud/incloudsphere/sphere.go
  pkg/multicloud/incloudsphere/storage.go
  pkg/multicloud/incloudsphere/storagecache.go
Labels: size/L, area/region

#14737 fix: climc detach disk ignore keep_disk param
  cmd/climc/shell/compute/serverdisks.go
Labels: size/XS

#14738 Automated cherry pick of #14737: fix: climc detach disk ignore keep_disk param
  cmd/climc/shell/compute/serverdisks.go
Labels: size/XS

#14739 Automated cherry pick of #14737: fix: climc detach disk ignore keep_disk param
  cmd/climc/shell/compute/serverdisks.go
Labels: size/XS

#14734 fix: choose host storage without considering storage capacity
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/hosts.go
Labels: size/S

#14735 Automated cherry pick of #14734: fix: choose host storage without considering storage capacity
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/hosts.go
Labels: size/S

#14736 Automated cherry pick of #14734: fix: choose host storage without considering storage capacity
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/hosts.go
Labels: size/S

#14743 fix(region,host): mount fusefs on guest start
  pkg/compute/models/disks.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/snapshots.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/storageman/disk_base.go
Labels: size/L

#14746 Automated cherry pick of #14743: fix(region,host): mount fusefs on guest start
  pkg/compute/models/disks.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/snapshots.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/storageman/disk_base.go
Labels: size/L

#14740 fix: adjust circle config on release/3.8
  .circleci/config.yml
Labels: size/M

#14732 fix(region): 避免缺失department信息导致获取bucket容量失败
  pkg/multicloud/apsara/region.go
Labels: size/S, area/region

#14733 Automated cherry pick of #14732: fix(region): 避免缺失department信息导致获取bucket容量失败
  pkg/multicloud/apsara/region.go
Labels: size/S

#14748 fix cherry pick of #14743
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/S

#14776 Automated cherry pick of #14768: fix: no log for storage enable/disable
  pkg/compute/models/storages.go
Labels: size/XS

#14770 修改getYears,getMonth顺序bug
  pkg/multicloud/aliyun/dbinstance.go
Labels: lgtm

#14775 Automated cherry pick of #14770: 修改getYears,getMonth顺序bug
  pkg/multicloud/aliyun/dbinstance.go
Labels: size/XS

#14779 fix(host): host desc missing security rulers
  pkg/hostman/guestman/desc/desc.go
Labels: size/XS

#14780 feature: model manager dispatcher
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/db_joint_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/logger/models/actionlog.go
Labels: size/M

#14785 feat(region): add virtio vga type support
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/XS

#14786 Automated cherry pick of #14785: feat(region): add virtio vga type support
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/XS

#14795 虚拟机、磁盘排序与过滤
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: lgtm, size/M, area/region

#14796 Automated cherry pick of #14795: 虚拟机、磁盘排序与过滤
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#14797 Automated cherry pick of #14795: 虚拟机、磁盘排序与过滤
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/servers.go
Labels: size/M

#14792 fix(region): secgroup rule sync
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/security_group_sync_rules_task.go
Labels: size/M, area/region

#14793 Automated cherry pick of #14792: fix(region): secgroup rule sync
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/security_group_sync_rules_task.go
Labels: size/M

#14794 Automated cherry pick of #14792: fix(region): secgroup rule sync
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/security_group_sync_rules_task.go
Labels: size/M

#14782 fix(region): huawei lb rule sync
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
Labels: size/XS, area/region

#14783 Automated cherry pick of #14782: fix(region): huawei lb rule sync
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
Labels: size/XS

#14784 Automated cherry pick of #14782: fix(region): huawei lb rule sync
  pkg/multicloud/huawei/loadbalancer_listener.go
  pkg/multicloud/huawei/loadbalancer_listener_rule.go
Labels: size/XS

#14787 fix(region): incloudsphere resize disk
  pkg/compute/guestdrivers/incloudsphere.go
  pkg/compute/hostdrivers/incloudsphere.go
Labels: size/M, area/region

#14762 fix: allow start vm on raspberry pi 4
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/hostman/options/options.go
Labels: size/S

#14764 Automated cherry pick of #14762: fix: allow start vm on raspberry pi 4
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/hostman/options/options.go
Labels: size/S

#14798 fix: add host-type-count climc subcommand
  cmd/climc/shell/compute/hosts.go
Labels: size/S

#14805 阿里云内网connectionStr
  pkg/multicloud/aliyun/dbinstance.go
Labels: lgtm, size/XS

#14806 Automated cherry pick of #14805: 阿里云内网connectionStr
  pkg/multicloud/aliyun/dbinstance.go
Labels: size/XS

#14803 Automated cherry pick of #14766: fix(region): add cloud_env filter options for network address
  pkg/apis/compute/networkaddress.go
  pkg/compute/models/networkaddresses.go
  pkg/mcclient/options/networkaddress.go
Labels: size/S

#14804 Automated cherry pick of #14766: fix(region): add cloud_env filter options for network address
  pkg/apis/compute/networkaddress.go
  pkg/compute/models/networkaddresses.go
  pkg/mcclient/options/networkaddress.go
Labels: size/S

#14801 feature(apigateway): SP-initiated logout
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/oidc.go
Labels: size/L

#14802 Automated cherry pick of #14801: feature(apigateway): SP-initiated logout
  pkg/apigateway/handler/auth.go
  pkg/apigateway/handler/oidc.go
Labels: size/L

#14807 fix(climc): options for network address
  pkg/mcclient/options/networkaddress.go
Labels: size/XS, area/climc

#14809 Automated cherry pick of #14807: fix(climc): options for network address
  pkg/mcclient/options/networkaddress.go
Labels: size/XS

#14808 Automated cherry pick of #14807: fix(climc): options for network address
  pkg/mcclient/options/networkaddress.go
Labels: size/XS

#14816 Automated cherry pick of #14814: order-by-guest-count
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
Labels: size/S

#14814 order-by-guest-count
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
Labels: lgtm, size/S

#14815 Automated cherry pick of #14814: order-by-guest-count
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
Labels: size/S

#14811 fix: host mem_commit_bound typo
  pkg/apis/compute/host.go
Labels: size/XS

#14812 Automated cherry pick of #14811: fix: host mem_commit_bound typo
  pkg/apis/compute/host.go
Labels: size/XS

#14813 Automated cherry pick of #14811: fix: host mem_commit_bound typo
  pkg/apis/compute/host.go
Labels: size/XS

#14819 fix(region): choose storage when no medium specified
  pkg/compute/guestdrivers/virtualization.go
Labels: size/XS, area/region

#14820 Automated cherry pick of #14819: fix(region): choose storage when no medium specified
  pkg/compute/guestdrivers/virtualization.go
Labels: size/XS

#14821 Automated cherry pick of #14819: fix(region): choose storage when no medium specified
  pkg/compute/guestdrivers/virtualization.go
Labels: size/XS

#14822 fix: cloud_env options
  pkg/apihelper/reflect.go
Labels: size/XS, area/vpcagent

#14823 Automated cherry pick of #14822: fix: cloud_env options
  pkg/apihelper/reflect.go
Labels: size/XS

#14824 Automated cherry pick of #14822: fix: cloud_env options
  pkg/apihelper/reflect.go
Labels: size/XS

#14825 fix(cloudmon): allow disable ping probe at 3.8
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/cloudmon/collectors/pinger.go
Labels: size/XS

#14817 fix(cloudmon): allow disable ping probe
  pkg/cloudmon/collectors/pinger.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/service.go
Labels: size/XS

#14818 Automated cherry pick of #14817: fix(cloudmon): allow disable ping probe
  pkg/cloudmon/collectors/pinger.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/service.go
Labels: size/XS

#14833 Automated cherry pick of #14713: 添加mongodb最大链接数、所用磁盘占比等、、、
  pkg/cloudprovider/resources.go
  pkg/compute/models/buckets.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/mongodb.go
  pkg/compute/usages/handler.go
  pkg/multicloud/aliyun/dbinstance.go
  pkg/multicloud/aliyun/mongodb.go
  pkg/multicloud/apsara/dbinstance.go
  pkg/multicloud/dbinstance_base.go
  pkg/multicloud/mongodb_base.go
  pkg/multicloud/qcloud/mongodb.go
Labels: size/L

#14834 fix(region): apsara instance id
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/apsara/shell/instance.go
Labels: size/S, area/region

#14835 Automated cherry pick of #14834: fix(region): apsara instance id
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/apsara/shell/instance.go
Labels: size/S

#14831 fix(region): k8s purge when deleted
  pkg/compute/models/kube_clusters.go
Labels: size/S, area/region

#14832 Automated cherry pick of #14831: fix(region): k8s purge when deleted
  pkg/compute/models/kube_clusters.go
Labels: size/S

#14828 fix(region): billing cycle
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS, area/region

#14829 Automated cherry pick of #14828: fix(region): billing cycle
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#14830 Automated cherry pick of #14828: fix(region): billing cycle
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#14839 fix(region): api version for k8s
  pkg/compute/models/kube_clusters.go
Labels: size/XS, area/region

#14840 Automated cherry pick of #14839: fix(region): api version for k8s
  pkg/compute/models/kube_clusters.go
Labels: size/XS

#14844 feat(region,host): custom usb controller type
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#14845 Automated cherry pick of #14844: feat(region,host): custom usb controller type
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#14846 Automated cherry pick of #14845: Automated cherry pick of #14844: feat(region,host): custom usb controller type
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#14847 fix(region): update host cpu_reserved on reserve cpus
  pkg/compute/models/hosts.go
Labels: size/XS

#14848 Automated cherry pick of #14847: fix(region): update host cpu_reserved on reserve cpus
  pkg/compute/models/hosts.go
Labels: size/XS

#14842 fix(host): fix panic on change cdrom succ
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
Labels: size/XS

#14850 fix: circle ci use large resource_class
  .circleci/config.yml
Labels: size/XS

#14858 fix: ensure update user mobile
  pkg/notify/tasks/subcontact_pull_task.go
Labels: size/M

#14859 Automated cherry pick of #14858: fix: ensure update user mobile
  pkg/notify/tasks/subcontact_pull_task.go
Labels: size/M

#14860 fix(host): compare desc cdrom
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/S

#14861 fix: add password info to server vnc info
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
Labels: size/M

#14862 Automated cherry pick of #14861: fix: add password info to server vnc info
  pkg/cloudprovider/instance.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
Labels: size/M

#14863 fix(region): jdcloud misc
  pkg/multicloud/jdcloud/provider/provider.go
Labels: size/S, area/region

#14864 Automated cherry pick of #14863: fix(region): jdcloud misc
  pkg/multicloud/jdcloud/provider/provider.go
Labels: size/S

#14875 fix(cloudmon): huawei metric pull
  pkg/multicloud/huawei/provider/provider.go
Labels: size/XS, area/cloudmon

#14876 Automated cherry pick of #14875: fix(cloudmon): huawei metric pull
  pkg/multicloud/huawei/provider/provider.go
Labels: size/XS

#14873 fix: policy cache get/set with atomic ops
  pkg/cloudcommon/policy/policy.go
Labels: lgtm, size/XS

#14874 Automated cherry pick of #14873: fix: policy cache get/set with atomic ops
  pkg/cloudcommon/policy/policy.go
Labels: size/XS

#14855 fix(region): support enable aws monitor agent
  pkg/compute/options/options.go
  pkg/multicloud/aws/instance.go
Labels: size/XS, area/region

#14856 Automated cherry pick of #14855: fix(region): support enable aws monitor agent
  pkg/compute/options/options.go
  pkg/multicloud/aws/instance.go
Labels: size/XS

#14867 fix(cloudid): support redirect url for qcloud aliyun and aws
  pkg/cloudid/saml/providers/aliyun/driver.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/saml/providers/qcloud/driver.go
Labels: size/S, area/cloudid

#14868 Automated cherry pick of #14867: fix(cloudid): support redirect url for qcloud aliyun and aws
  pkg/cloudid/saml/providers/aliyun/driver.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/saml/providers/qcloud/driver.go
Labels: size/S

#14872 Automated cherry pick of #14854: fix(host): get unused port
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#14854 fix(host): get unused port
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#14869 fix(region): show huawei cloudprovider with region name
  pkg/cloudprovider/subaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/multicloud/huawei/huawei.go
Labels: size/S, area/region

#14871 Automated cherry pick of #14869: fix(region): show huawei cloudprovider with region name
  pkg/cloudprovider/subaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/multicloud/huawei/huawei.go
Labels: size/S

#14877 fix(cloudmon): azure windows metric
  pkg/multicloud/azure/monitor.go
Labels: size/S, area/cloudmon

#14878 Automated cherry pick of #14877: fix(cloudmon): azure windows metric
  pkg/multicloud/azure/monitor.go
Labels: size/S

#14879 fix(cloudmon): qcloud k8s metric
  pkg/apis/compute/kube_cluster.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/qcloud.go
  pkg/cloudprovider/metrics.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/azure/monitor.go
  pkg/multicloud/qcloud/monitor.go
Labels: size/L, area/cloudmon

#14880 Automated cherry pick of #14879: fix(cloudmon): qcloud k8s metric
  pkg/apis/compute/kube_cluster.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/qcloud.go
  pkg/cloudprovider/metrics.go
  pkg/multicloud/aliyun/monitor.go
  pkg/multicloud/azure/monitor.go
  pkg/multicloud/qcloud/monitor.go
Labels: size/L

#14881 fix(notify): fail to create deleted contacts
  pkg/notify/models/receiver.go
Labels: size/XS

#14882 Automated cherry pick of #14881: fix(notify): fail to create deleted contacts
  pkg/notify/models/receiver.go
Labels: size/XS

#14883 fix(cloudmon): bucket and redis metric
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/resources/resources.go
Labels: size/XS, area/cloudmon

#14884 Automated cherry pick of #14883: fix(cloudmon): bucket and redis metric
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/resources/resources.go
Labels: size/XS

#14893 fix(cloudmon): k8s metric
  pkg/cloudmon/providerdriver/aliyun.go
  pkg/multicloud/aliyun/monitor.go
Labels: size/M, area/cloudmon

#14894 Automated cherry pick of #14893: fix(cloudmon): k8s metric
  pkg/cloudmon/providerdriver/aliyun.go
  pkg/multicloud/aliyun/monitor.go
Labels: size/M

#14891 fix(region): aws not found error
  pkg/multicloud/aws/aws_request.go
Labels: size/XS, area/region

#14892 Automated cherry pick of #14891: fix(region): aws not found error
  pkg/multicloud/aws/aws_request.go
Labels: size/XS
