Repository yunionio/cloudpods, pull requests merged in 2022-10, with the labels that each got.

#15114 fix: preserve os info of instance
  pkg/cloudprovider/images.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/osinfo.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guests.go
  pkg/multicloud/aliyun/elastic_search_instance_types.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/image.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/bingocloud/image.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ecloud/image.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/image.go
  pkg/multicloud/esxi/template.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/image.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcso/image.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/incloudsphere/image.go
  pkg/multicloud/incloudsphere/instance.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/jdcloud/image.go
  pkg/multicloud/jdcloud/instance.go
  pkg/multicloud/nutanix/image.go
  pkg/multicloud/nutanix/instance.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/proxmox/image.go
  pkg/multicloud/proxmox/instance.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/remotefile/instance.go
  pkg/multicloud/ucloud/image.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/instance.go
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/XXL

#15115 Automated cherry pick of #15114: fix: preserve os info of instance
  pkg/cloudprovider/images.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/osinfo.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guests.go
  pkg/multicloud/aliyun/elastic_search_instance_types.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/image.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/bingocloud/image.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ecloud/image.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/image.go
  pkg/multicloud/esxi/template.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/image.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcso/image.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/jdcloud/image.go
  pkg/multicloud/jdcloud/instance.go
  pkg/multicloud/nutanix/image.go
  pkg/multicloud/nutanix/instance.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/ucloud/image.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/instance.go
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/XXL

#15116 Automated cherry pick of #15114: fix: preserve os info of instance
  pkg/cloudprovider/images.go
  pkg/cloudprovider/instance.go
  pkg/cloudprovider/osinfo.go
  pkg/cloudprovider/resources.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guests.go
  pkg/multicloud/aliyun/elastic_search_instance_types.go
  pkg/multicloud/aliyun/image.go
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/apsara/image.go
  pkg/multicloud/apsara/instance.go
  pkg/multicloud/aws/image.go
  pkg/multicloud/aws/instance.go
  pkg/multicloud/azure/classic_instance.go
  pkg/multicloud/azure/image.go
  pkg/multicloud/azure/instance.go
  pkg/multicloud/cloudpods/image.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/ctyun/image.go
  pkg/multicloud/ctyun/instance.go
  pkg/multicloud/ecloud/image.go
  pkg/multicloud/ecloud/instance.go
  pkg/multicloud/esxi/image.go
  pkg/multicloud/esxi/template.go
  pkg/multicloud/esxi/virtualmachine.go
  pkg/multicloud/google/image.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/hcso/image.go
  pkg/multicloud/hcso/instance.go
  pkg/multicloud/huawei/image.go
  pkg/multicloud/huawei/instance.go
  pkg/multicloud/instance_base.go
  pkg/multicloud/jdcloud/image.go
  pkg/multicloud/jdcloud/instance.go
  pkg/multicloud/nutanix/image.go
  pkg/multicloud/nutanix/instance.go
  pkg/multicloud/openstack/image.go
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/qcloud/image.go
  pkg/multicloud/qcloud/instance.go
  pkg/multicloud/ucloud/image.go
  pkg/multicloud/ucloud/instance.go
  pkg/multicloud/zstack/image.go
  pkg/multicloud/zstack/instance.go
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/XXL

#15117 fix(monitor): monitor error message
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
Labels: size/XS, area/monitor

#15118 Automated cherry pick of #15117: fix(monitor): monitor error message
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
Labels: size/XS

#15119 Automated cherry pick of #15117: fix(monitor): monitor error message
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
Labels: size/XS

#15120 optimize(scheduler): global cache for schedtag
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/analysor_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/doc.go
  pkg/scheduler/data_manager/schedtag/schedtag.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/service/service.go
Labels: area/scheduler, size/XL

#15121 Automated cherry pick of #15120: optimize(scheduler): global cache for schedtag
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/analysor_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/doc.go
  pkg/scheduler/data_manager/schedtag/schedtag.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/service/service.go
Labels: size/XL

#15124 Automated cherry pick of #15120: optimize(scheduler): global cache for schedtag
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/analysor_test.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/doc.go
  pkg/scheduler/data_manager/schedtag/schedtag.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/service/service.go
Labels: size/XL

#15128 fix(cloudid): aliyun saml provider name
  pkg/multicloud/aliyun/saml_provider.go
Labels: size/XS, area/cloudid

#15129 Automated cherry pick of #15128: fix(cloudid): aliyun saml provider name
  pkg/multicloud/aliyun/saml_provider.go
Labels: size/XS

#15130 Automated cherry pick of #15128: fix(cloudid): aliyun saml provider name
  pkg/multicloud/aliyun/saml_provider.go
Labels: size/XS

#15125 fix(region): api gen
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/monitor/zz_generated.model.go
Labels: size/L

#15131 fix(region): add project tag short desc
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/virtualresource.go
Labels: size/S, area/region

#15132 Automated cherry pick of #15131: fix(region): add project tag short desc
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/virtualresource.go
Labels: size/S

#15102 fix(region): azure resource group
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/resourcegroup.go
Labels: size/L, area/region

#15103 Automated cherry pick of #15102: fix(region): azure resource group
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/region.go
  pkg/multicloud/azure/resourcegroup.go
Labels: size/L

#15143 fix(host): marshal cycle struct guest
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/XS

#15146 Automated cherry pick of #15143: fix(host): marshal cycle struct guest
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/XS

#15144 fix(region): recover code remove by #14996
  pkg/compute/models/guest_actions.go
Labels: size/M

#15145 Automated cherry pick of #15144: fix(region): recover code remove by #14996
  pkg/compute/models/guest_actions.go
Labels: size/M

#15148 fix(region): apsara region endpoint
  pkg/multicloud/apsara/region.go
Labels: size/XS, area/region

#15149 Automated cherry pick of #15148: fix(region): apsara region endpoint
  pkg/multicloud/apsara/region.go
Labels: size/XS

#15154 fix(region): oss permission
  pkg/multicloud/aliyun/aliyun.go
Labels: size/S, area/region

#15155 Automated cherry pick of #15154: fix(region): oss permission
  pkg/multicloud/aliyun/aliyun.go
Labels: size/S

#15138 fix(region): lb sync panic
  pkg/compute/models/loadbalancerlistenerrules.go
Labels: size/XS, area/region

#15139 Automated cherry pick of #15138: fix(region): lb sync panic
  pkg/compute/models/loadbalancerlistenerrules.go
Labels: size/XS

#15140 Automated cherry pick of #15138: fix(region): lb sync panic
  pkg/compute/models/loadbalancerlistenerrules.go
Labels: size/XS

#15133 fix(region): incloudsphere network
  pkg/multicloud/incloudsphere/network.go
Labels: size/S, area/region

#15134 fix: override valid os info in metadata
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/M

#15135 Automated cherry pick of #15134: fix: override valid os info in metadata
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/M

#15136 Automated cherry pick of #15134: fix: override valid os info in metadata
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/M

#15137 fix(region): snapshot time zone
  pkg/compute/models/disks.go
Labels: size/XS, area/region

#15141 Automated cherry pick of #15137: fix(region): snapshot time zone
  pkg/compute/models/disks.go
Labels: size/XS

#15142 Automated cherry pick of #15137: fix(region): snapshot time zone
  pkg/compute/models/disks.go
Labels: size/XS

#15147 fix(climc): python sdk generage
  cmd/climc/shell/misc/sdk.go
Labels: size/L

#15150 fix(host-image): cancel auth host-image http requests
  pkg/hostimage/host_image_service.go
Labels: size/S

#15151 Automated cherry pick of #15150: fix(host-image): cancel auth host-image http requests
  pkg/hostimage/host_image_service.go
Labels: size/S

#15108 Feat/qemu kvm caps
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/arm.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/pci.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#15161 Automated cherry pick of #15160: fix: debian 11 support missing at release/3.8
  pkg/util/imagetools/image_test.go
Labels: size/XS

#15162 Automated cherry pick of #15160: fix: debian 11 support missing at release/3.8
  pkg/util/imagetools/image_test.go
  pkg/util/imagetools/imagetools.go
Labels: size/S

#15158 fix(region): only kvm use qgs set password in guest running status
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
Labels: size/XS

#15159 Automated cherry pick of #15158: fix(region): only kvm use qgs set password in guest running status
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
Labels: size/XS

#15152 fix: climc image cache
  scripts/docker_push.sh
Labels: size/XS, area/climc

#15153 Automated cherry pick of #15152: fix: climc image cache
  scripts/docker_push.sh
Labels: size/XS

#15165 fix(region): avoid panic
  pkg/multicloud/google/region.go
  pkg/multicloud/google/zone.go
Labels: size/XS, area/region

#15166 Automated cherry pick of #15165: fix(region): avoid panic
  pkg/multicloud/google/region.go
  pkg/multicloud/google/zone.go
Labels: size/XS

#15167 Automated cherry pick of #15165: fix(region): avoid panic
  pkg/multicloud/google/region.go
  pkg/multicloud/google/zone.go
Labels: size/XS

#15174 fix: no etcd watching if endpoint type is not internal
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/options/manager.go
Labels: size/S

#15176 Automated cherry pick of #15174: fix: no etcd watching if endpoint type is not internal
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/options/manager.go
Labels: size/S

#15172 fix(cloudmon): show unmarshal error
  pkg/cloudmon/resources/resources.go
Labels: size/M, area/cloudmon

#15173 Automated cherry pick of #15172: fix(cloudmon): show unmarshal error
  pkg/cloudmon/resources/resources.go
Labels: size/M

#15170 fix(region): purge vm by tags
  pkg/compute/models/hosts.go
Labels: size/XS, area/region

#15156 fix(region): openstack vnc
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/shell/instance.go
Labels: size/M, area/region

#15157 Automated cherry pick of #15156: fix(region): openstack vnc
  pkg/multicloud/openstack/instance.go
  pkg/multicloud/openstack/shell/instance.go
Labels: size/M

#15163 fix: ssd(rotation_rate=1) option only applicable to scsi-hd device
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#15164 Automated cherry pick of #15163: fix: ssd(rotation_rate=1) option only applicable to scsi-hd device
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#15169 Automated cherry pick of #15163: fix: ssd(rotation_rate=1) option only applicable to scsi-hd device
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#15168 feat(region,host): hugepage optimize
  pkg/apis/compute/host.go
  pkg/apis/scheduler/api.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/options/options.go
  pkg/scheduler/algorithm/predicates/error.go
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/L

#15178 Automated cherry pick of #15177: fix: disk fallocate support
  pkg/hostman/storageman/disk_local.go
Labels: size/M

#15179 fix(region): skip duplicate account check
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M, area/region

#15180 Automated cherry pick of #15179: fix(region): skip duplicate account check
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#15189 fix(region): hugepage validate mem update
  pkg/compute/models/hosts.go
Labels: size/XS

#15183 fix(region): skip account check
  pkg/compute/models/cloudaccounts.go
Labels: size/XS, area/region

#15184 Automated cherry pick of #15183: fix(region): skip account check
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#15187 fix(region): optimized sku list
  pkg/compute/models/skus.go
Labels: size/M, area/region

#15188 Automated cherry pick of #15187: fix(region): optimized sku list
  pkg/compute/models/skus.go
Labels: size/M

#15186 fix(region): incloudsphere vm ip
  pkg/multicloud/incloudsphere/host.go
Labels: size/XS, area/region

#15192 fix(scheduler): check free capacity of each storage
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/S, area/scheduler

#15193 Automated cherry pick of #15192: fix(scheduler): check free capacity of each storage
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/S

#15194 Automated cherry pick of #15192: fix(scheduler): check free capacity of each storage
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/S

#15190 fix(region): incloudsphere list items
  pkg/multicloud/incloudsphere/sphere.go
Labels: size/XS, area/region

#15196 fix(reigon): incloudsphere image sync
  pkg/multicloud/incloudsphere/storagecache.go
Labels: size/XS, area/region

#15198 fix/huawei-aksk-createdAt
  pkg/cloudprovider/clouduser.go
  pkg/multicloud/hcso/clouduser.go
  pkg/multicloud/huawei/clouduser.go
Labels: size/M

#15200 Automated cherry pick of #15198: fix/huawei-aksk-createdAt
  pkg/cloudprovider/clouduser.go
  pkg/multicloud/hcso/clouduser.go
  pkg/multicloud/huawei/clouduser.go
Labels: size/M

#15185 fix/remotefile guest
  pkg/compute/models/guests.go
  pkg/multicloud/remotefile/projects.go
  pkg/multicloud/remotefile/region.go
Labels: lgtm, size/S

#14995 fix(glance): esxi vmdk requre streamOptimized
  pkg/util/qemuimg/qemuimg.go
Labels: size/XS, area/image

#15181 Automated cherry pick of #14995: fix(glance): esxi vmdk requre streamOptimized
  pkg/util/qemuimg/qemuimg.go
Labels: size/XS

#15195 fix(websonsole): vnc query
  pkg/webconsole/handlers.go
Labels: size/XS

#15197 Automated cherry pick of #15195: fix(websonsole): vnc query
  pkg/webconsole/handlers.go
Labels: size/XS

#15201 feature: api for sending emails with attachments
  .gitignore
  cmd/climc/shell/notifyv2/emailqueues.go
  go.mod
  go.sum
  pkg/apis/notify/emailqueue.go
  pkg/cloudcommon/db/baselog.go
  pkg/cloudcommon/db/opslog.go
  pkg/logger/models/actionlog.go
  pkg/mcclient/modules/notify/mod_emailqueues.go
  pkg/mcclient/options/notify/emailqueues.go
  pkg/notify/models/config.go
  pkg/notify/models/emailqueue.go
  pkg/notify/models/emailqueuestatus.go
  pkg/notify/models/event.go
  pkg/notify/models/notification.go
  pkg/notify/sender/doc.go
  pkg/notify/sender/email.go
  pkg/notify/sender/worker.go
  pkg/notify/service/handlers.go
  pkg/webconsole/models/commandlog.go
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/LICENSE
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/README.md
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/encodedword.go
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/pool.go
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/pool_go12.go
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/reader.go
  vendor/gopkg.in/alexcesaro/quotedprintable.v3/writer.go
  vendor/gopkg.in/mail.v2/.gitignore
  vendor/gopkg.in/mail.v2/.travis.yml
  vendor/gopkg.in/mail.v2/CHANGELOG.md
  vendor/gopkg.in/mail.v2/CONTRIBUTING.md
  vendor/gopkg.in/mail.v2/LICENSE
  vendor/gopkg.in/mail.v2/README.md
  vendor/gopkg.in/mail.v2/auth.go
  vendor/gopkg.in/mail.v2/doc.go
  vendor/gopkg.in/mail.v2/errors.go
  vendor/gopkg.in/mail.v2/message.go
  vendor/gopkg.in/mail.v2/mime.go
  vendor/gopkg.in/mail.v2/mime_go14.go
  vendor/gopkg.in/mail.v2/send.go
  vendor/gopkg.in/mail.v2/smtp.go
  vendor/gopkg.in/mail.v2/writeto.go
  vendor/modules.txt
Labels: size/XXL

#15203 fix: update auto-gen model api 20221017
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/notify/emailqueue.go
  pkg/apis/notify/zz_generated.model.go
  pkg/apis/zz_generated.model.go
Labels: size/M

#15204 fix(ansibleserver): force sleep 50s before running
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS, area/ansible

#15205 Automated cherry pick of #15204: fix(ansibleserver): force sleep 50s before running
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS

#15206 Automated cherry pick of #15204: fix(ansibleserver): force sleep 50s before running
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS

#15210 fix(region): add disk_type for disk short desc
  pkg/cloudcommon/db/resourcebase.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/miscresources.go
Labels: size/M, area/region

#15211 Automated cherry pick of #15210: fix(region): add disk_type for disk short desc
  pkg/cloudcommon/db/resourcebase.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
Labels: size/S

#15207 fix(cloudmon): default delay time for 6 minutes
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/bingocloud.go
Labels: size/XS, area/cloudmon

#15208 Automated cherry pick of #15207: fix(cloudmon): default delay time for 6 minutes
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/bingocloud.go
Labels: size/XS

#15217 fix/remoteFileReturnBug
  pkg/compute/models/disks.go
Labels: lgtm, size/XS

#15218 Automated cherry pick of #15217: fix/remoteFileReturnBug
  pkg/compute/models/disks.go
Labels: size/XS

#15214 fix(scheduler): do free capacity check when storage filter enabled
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/error.go
Labels: lgtm, size/S, area/scheduler

#15216 Automated cherry pick of #15214: fix(scheduler): do free capacity check when storage filter enabled
  pkg/scheduler/algorithm/predicates/disk_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/error.go
Labels: size/S

#15209 fix(region): incloudsphere vm nic with ip
  pkg/multicloud/incloudsphere/host.go
  pkg/multicloud/incloudsphere/instance.go
  pkg/multicloud/incloudsphere/network.go
Labels: size/M, area/region

#15182 fix(climc): origin vnc
  cmd/climc/shell/compute/servers.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S, area/climc

#15219 fixModelartsNodeCount nullable
  pkg/compute/models/modelarts_pools.go
Labels: lgtm, size/XS

#15220 Automated cherry pick of #15219: fixModelartsNodeCount nullable
  pkg/compute/models/modelarts_pools.go
Labels: size/XS

#15222 fix(region): multi cdrom interface not compatible
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
Labels: size/S

#15221 feat(host): add hyperv cpu features for kernel 5.4
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/arm.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
Labels: size/L

#15212 fix(host): alloc numa node for guest
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#15227 Automated cherry pick of #15223: fix: access backend service by specific region/zone
  pkg/apigateway/handler/backendproxy.go
  pkg/mcclient/session.go
Labels: size/M

#15223 fix: access backend service by specific region/zone
  pkg/apigateway/handler/backendproxy.go
  pkg/mcclient/session.go
Labels: size/M

#15236 fix: ignore secgroup sync error
  pkg/vpcagent/models/modelset.go
Labels: size/XS

#15237 Automated cherry pick of #15236: fix: ignore secgroup sync error
  pkg/vpcagent/models/modelset.go
Labels: size/XS

#15238 Automated cherry pick of #15236: fix: ignore secgroup sync error
  pkg/vpcagent/models/modelset.go
Labels: size/XS

#15225 feature: automatically purge expired splitables
  pkg/cloudcommon/db/database.go
  pkg/cloudevent/service/service.go
  pkg/cloudid/service/service.go
  pkg/compute/service/service.go
  pkg/image/service/service.go
  pkg/keystone/service/service.go
  pkg/logger/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/service/service.go
  pkg/scheduledtask/service/service.go
  pkg/util/splitable/purge.go
  pkg/util/splitable/splitable.go
  pkg/webconsole/service/service.go
Labels: lgtm, size/M

#15230 Automated cherry pick of #15224: fix: force reset expired password
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/user.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/users.go
Labels: size/M

#15224 fix: force reset expired password
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/user.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/users.go
Labels: size/M

#15213 feature: google shell support query bigquery
  pkg/multicloud/google/bigquery.go
  pkg/multicloud/google/google.go
  pkg/multicloud/google/shell/bigquery.go
Labels: lgtm, size/L

#15191 fix(region): aliyun sync by resource group
  pkg/compute/options/options.go
  pkg/multicloud/aliyun/aliyun.go
  pkg/multicloud/aliyun/region.go
  pkg/multicloud/aliyun/tablestore.go
Labels: size/M, area/region

#15231 fix(region): skip disk sync by system tags
  pkg/compute/models/disks.go
  pkg/compute/models/hosts.go
  pkg/compute/options/options.go
  pkg/multicloud/aliyun/storage.go
  pkg/multicloud/tag_base.go
Labels: size/M, area/region

#15232 Automated cherry pick of #15231: fix(region): skip disk sync by system tags
  pkg/compute/models/disks.go
  pkg/compute/models/hosts.go
  pkg/compute/options/options.go
  pkg/multicloud/aliyun/storage.go
  pkg/multicloud/tag_base.go
Labels: size/M

#15233 controlMetricsGoroutineCount
  pkg/cloudmon/options/options.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/resources/resources.go
Labels: lgtm, size/M

#15235 Automated cherry pick of #15233: controlMetricsGoroutineCount
  pkg/cloudmon/options/options.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/resources/resources.go
Labels: size/M

#15251 Automated cherry pick of #15246: fix(cloudmon):cloudpodsMonitor
  pkg/cloudmon/providerdriver/cloudpods.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/cloudpods/provider/provider.go
  pkg/multicloud/cloudpods/shell/instance.go
Labels: size/M

#15246 fix(cloudmon):cloudpodsMonitor
  pkg/cloudmon/providerdriver/cloudpods.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/multicloud/cloudpods/instance.go
  pkg/multicloud/cloudpods/provider/provider.go
  pkg/multicloud/cloudpods/shell/instance.go
Labels: lgtm, size/M

#15248 fix(baremetal): panic occured when get server ssh client
  pkg/baremetal/manager.go
Labels: size/XS, area/baremetal

#15249 Automated cherry pick of #15248: fix(baremetal): panic occured when get server ssh client
  pkg/baremetal/manager.go
Labels: size/XS

#15244 feature: enable monitor proxy at host metadata server
  pkg/apis/compute/guests.go
  pkg/apis/const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
  pkg/devtool/options/option.go
  pkg/devtool/utils/influxdb_url.go
  pkg/hostman/metadata/metadatahandler.go
Labels: size/M

#15245 Automated cherry pick of #15244: feature: enable monitor proxy at host metadata server
  pkg/apis/compute/guests.go
  pkg/apis/const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
  pkg/devtool/options/option.go
  pkg/devtool/utils/influxdb_url.go
  pkg/hostman/metadata/metadatahandler.go
Labels: size/M

#15253 feat(gpus): add hotplug support of gpu devices
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/usb.go
Labels: size/L

#15234 fix(host): x86 machine max cpus
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/guestman.go
Labels: size/S

#15228 fix(region): hcs vpc create
  pkg/apis/webconsole/consts.go
  pkg/webconsole/handlers.go
  pkg/webconsole/session/remote_console.go
Labels: size/XS, area/region

#15247 fix(region): lb validate
  go.mod
  go.sum
  pkg/apis/compute/loadbalancer.go
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/networks.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aliyun.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/nutanix.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  pkg/compute/tasks/loadbalancer_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/fakeregion.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/no_lb_region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/loadbalbacer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/region.go
Labels: size/XXL, area/region

#15229 feat(region,host): support assign bootindex for cdrom or disks
  pkg/apis/compute/api.go
  pkg/apis/compute/cdrom.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestcdrom.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_detach_disk_task.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/mcclient/modules/compute/mod_serverdisks.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#15264 feat(misc): use python3 for scripts/codegen.py
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  scripts/codegen.py
Labels: size/S, area/util

#15262 fix(region): account balance
  pkg/cloudmon/providerdriver/aliyun.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/huawei.go
  pkg/cloudmon/providerdriver/qcloud.go
Labels: size/L, area/cloudmon

#15263 Automated cherry pick of #15262: fix(region): account balance
  pkg/cloudmon/providerdriver/aliyun.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/huawei.go
  pkg/cloudmon/providerdriver/qcloud.go
Labels: size/L
