Repository yunionio/cloudpods, pull requests merged in 2022-03, with the labels that each got.

#13554 Automated cherry pick of #13552: fix(yunionapi): reset password with base64
  pkg/apigateway/handler/auth.go
Labels: size/S

#13552 fix(yunionapi): reset password with base64
  pkg/apigateway/handler/auth.go
Labels: size/S, area/apigateway

#13553 Automated cherry pick of #13552: fix(yunionapi): reset password with base64
  pkg/apigateway/handler/auth.go
Labels: size/S

#13558 Automated cherry pick of #13552: fix(yunionapi): reset password with base64
  pkg/apigateway/handler/auth.go
Labels: size/S

#13561 fix(climc): add cmd for global vpc
  cmd/climc/shell/compute/globalvpcs.go
Labels: size/XS, area/climc

#13562 Automated cherry pick of #13561: fix(climc): add cmd for global vpc
  cmd/climc/shell/compute/globalvpcs.go
Labels: size/XS

#13555 fi(apigateway): user info with totp
  pkg/apigateway/handler/auth.go
Labels: size/XS, area/apigateway

#13556 Automated cherry pick of #13555: fi(apigateway): user info with totp
  pkg/apigateway/handler/auth.go
Labels: size/XS

#13557 Automated cherry pick of #13555: fi(apigateway): user info with totp
  pkg/apigateway/handler/auth.go
Labels: size/XS

#13563 fix(region): expiration notification works for resources after renewal
  pkg/compute/models/billingresource.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guest_billing.go
Labels: size/L, area/region

#13564 Automated cherry pick of #13563: fix(region): expiration notification works for resources after renewal
  pkg/compute/models/billingresource.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guest_billing.go
Labels: size/L

#13565 Automated cherry pick of #13563: fix(region): expiration notification works for resources after renewal
  pkg/compute/models/billingresource.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/guest_billing.go
Labels: size/L

#13566 fix(notify): add panic notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PANIC.tmpl
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/syncworkers.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/notify/models/topic.go
  pkg/util/panicutils/doc.go
  pkg/util/panicutils/panicutil.go
Labels: size/L, area/region, area/host, area/notify

#13567 Automated cherry pick of #13566: fix(notify): add panic notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PANIC.tmpl
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/syncworkers.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/notify/models/topic.go
  pkg/util/panicutils/doc.go
  pkg/util/panicutils/panicutil.go
Labels: size/L

#13568 Automated cherry pick of #13566: fix(notify): add panic notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PANIC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/EXCEPTION.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/OFFLINE.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PANIC.tmpl
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/syncworkers.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/notify/models/topic.go
  pkg/util/panicutils/doc.go
  pkg/util/panicutils/panicutil.go
Labels: size/L

#13570 fix(host): rbd disk path
  pkg/hostman/storageman/disk_rbd.go
Labels: size/XS, area/host

#13571 Automated cherry pick of #13570: fix(host): rbd disk path
  pkg/hostman/storageman/disk_rbd.go
Labels: size/XS

#13572 Automated cherry pick of #13570: fix(host): rbd disk path
  pkg/hostman/storageman/disk_rbd.go
Labels: size/XS

#13575 fix: host update sn
  cmd/climc/shell/compute/hosts.go
Labels: size/XS

#13576 Automated cherry pick of #13575: fix: host update sn
  cmd/climc/shell/compute/hosts.go
Labels: size/XS

#13578 fix(host): remove addr of qemu nic option
  pkg/hostman/guestman/qemu/generate.go
Labels: size/S, area/host

#13579 Automated cherry pick of #13578: fix(host): remove addr of qemu nic option
  pkg/hostman/guestman/qemu/generate.go
Labels: size/S

#13573 class metadata limit for vpc, wire and network
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/wires.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/M, area/region, area/scheduler

#13574 Automated cherry pick of #13573: class metadata limit for vpc, wire and network
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/wires.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/M

#13577 feat(host): server instance snapshot with memory
  cmd/climc/shell/compute/instance_snapshots.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/apis/host/memory_snapshot.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/guest_resume_task.go
  pkg/compute/tasks/guest_suspend_task.go
  pkg/compute/tasks/instance_snapshot_create_task.go
  pkg/compute/tasks/instance_snapshot_reset_task.go
  pkg/hostman/downloader/downloadhandler.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/hostman/options/options.go
  pkg/util/logclient/consts.go
Labels: area/region, area/host, size/XL

#13593 fix(region): external project filter by manager id
  pkg/compute/models/external_projects.go
Labels: size/XS, area/region

#13594 Automated cherry pick of #13593: fix(region): external project filter by manager id
  pkg/compute/models/external_projects.go
Labels: size/XS

#13595 Automated cherry pick of #13593: fix(region): external project filter by manager id
  pkg/compute/models/external_projects.go
Labels: size/XS

#13596 fix(ansible): use the correct length value 'text'
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS, area/ansible

#13597 Automated cherry pick of #13596: fix(ansible): use the correct length value 'text'
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS

#13598 Automated cherry pick of #13596: fix(ansible): use the correct length value 'text'
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS

#13599 Automated cherry pick of #13596: fix(ansible): use the correct length value 'text'
  pkg/ansibleserver/models/ansibleplaybooks_v2.go
Labels: size/XS

#13600 fix(region): remote useless info of azure lb
  pkg/multicloud/azure/loadbalancer.go
Labels: size/XS, area/region

#13601 Automated cherry pick of #13600: fix(region): remote useless info of azure lb
  pkg/multicloud/azure/loadbalancer.go
Labels: size/XS

#13602 Automated cherry pick of #13600: fix(region): remote useless info of azure lb
  pkg/multicloud/azure/loadbalancer.go
Labels: size/XS

#13603 fix(region): expend length lb info
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/azure/loadbalancer.go
Labels: size/XS, area/region

#13604 Automated cherry pick of #13603: fix(region): expend length lb info
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/azure/loadbalancer.go
Labels: size/XS

#13605 Automated cherry pick of #13603: fix(region): expend length lb info
  pkg/compute/models/loadbalancers.go
  pkg/multicloud/azure/loadbalancer.go
Labels: size/XS

#13613 fix(region): rds project sync
  pkg/compute/models/dbinstances.go
Labels: size/XS, area/region

#13614 Automated cherry pick of #13613: fix(region): rds project sync
  pkg/compute/models/dbinstances.go
Labels: size/XS

#13610 fix(scheduledtask): treat hour and minute as utc time
  pkg/compute/models/scaling_trigger_test.go
  pkg/compute/models/timer.go
  pkg/scheduledtask/models/timer.go
Labels: size/S

#13611 Automated cherry pick of #13610: fix(scheduledtask): treat hour and minute as utc time
  pkg/compute/models/scaling_trigger_test.go
  pkg/compute/models/timer.go
  pkg/scheduledtask/models/timer.go
Labels: size/S

#13612 Automated cherry pick of #13610: fix(scheduledtask): treat hour and minute as utc time
  pkg/compute/models/scaling_trigger_test.go
  pkg/compute/models/timer.go
Labels: size/S

#13615 Automated cherry pick of #13613: fix(region): rds project sync
  pkg/compute/models/dbinstances.go
Labels: size/XS

#13618 Instancebackup/syncstatus
  cmd/climc/shell/compute/backup.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/instance_backup.go
  pkg/compute/models/backup.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/backup_storage_syncstatus_task.go
  pkg/compute/tasks/instance_backup_create_task.go
  pkg/compute/tasks/instance_backup_delete_task.go
  pkg/compute/tasks/instance_backup_syncstatus.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L, area/region, area/host

#13619 Automated cherry pick of #13618: Instancebackup/syncstatus
  cmd/climc/shell/compute/backup.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/instance_backup.go
  pkg/compute/models/backup.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/backup_storage_syncstatus_task.go
  pkg/compute/tasks/instance_backup_create_task.go
  pkg/compute/tasks/instance_backup_delete_task.go
  pkg/compute/tasks/instance_backup_syncstatus.go
  pkg/hostman/storageman/backupstorage/backup_storage.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#13624 feat(telegraf-raid-plugin): update rootfs and image version
  Makefile
  build/docker/Dockerfile.telegraf-raid-plugin
Labels: size/XS, area/util

#13626 Automated cherry pick of #13624: feat(telegraf-raid-plugin): update rootfs and image version
  Makefile
  build/docker/Dockerfile.telegraf-raid-plugin
Labels: size/XS

#13625 Automated cherry pick of #13624: feat(telegraf-raid-plugin): update rootfs and image version
  Makefile
  build/docker/Dockerfile.telegraf-raid-plugin
Labels: size/XS

#13627 Automated cherry pick of #13624: feat(telegraf-raid-plugin): update rootfs and image version
  Makefile
  build/docker/Dockerfile.telegraf-raid-plugin
Labels: size/XS

#13628 Automated cherry pick of #13624: feat(telegraf-raid-plugin): update rootfs and image version
  Makefile
  build/docker/Dockerfile.telegraf-raid-plugin
Labels: size/XS

#13620 fix(region): qcloud disk range changed
  pkg/compute/guestdrivers/qcloud.go
Labels: size/M, area/region

#13621 Automated cherry pick of #13620: fix(region): qcloud disk range changed
  pkg/compute/guestdrivers/qcloud.go
Labels: size/M

#13622 Automated cherry pick of #13620: fix(region): qcloud disk range changed
  pkg/compute/guestdrivers/qcloud.go
Labels: size/M

#13623 Automated cherry pick of #13620: fix(region): qcloud disk range changed
  pkg/compute/guestdrivers/qcloud.go
Labels: size/M

#13609 Automated cherry pick of #13606: fix: disable cache for oidc auth callback
  pkg/apigateway/handler/oidc.go
Labels: size/XS

#13633 fix(region): allow skip server sync by system tags
  pkg/compute/models/hosts.go
  pkg/compute/options/options.go
Labels: size/M, area/region

#13635 Automated cherry pick of #13633: fix(region): allow skip server sync by system tags
  pkg/compute/models/hosts.go
  pkg/compute/options/options.go
Labels: size/M

#13631 Instancebackup force delete
  cmd/climc/shell/compute/backup.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/backup.go
  pkg/compute/models/backup.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/instance_backup.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/disk_backup_delete_task.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/mcclient/options/compute/backup.go
Labels: size/L, area/region, area/climc

#13632 Automated cherry pick of #13631: Instancebackup force delete
  cmd/climc/shell/compute/backup.go
  cmd/climc/shell/helper.go
  pkg/apis/compute/backup.go
  pkg/compute/models/backup.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/instance_backup.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/disk_backup_delete_task.go
  pkg/hostman/storageman/backupstorage/backup_storage_nfs.go
  pkg/mcclient/options/compute/backup.go
Labels: size/L

#13629 feat(region): instance snapshot with_memory filter
  cmd/climc/shell/compute/instance_snapshots.go
  pkg/apis/compute/instance_snapshot.go
  pkg/compute/models/instance_snapshots.go
Labels: size/S, area/region, area/climc

#13630 Automated cherry pick of #13629: feat(region): instance snapshot with_memory filter
  cmd/climc/shell/compute/instance_snapshots.go
  pkg/apis/compute/instance_snapshot.go
  pkg/compute/models/instance_snapshots.go
Labels: size/S

#13636 fix(region): add generate_name if not before validate guest creating data
  pkg/compute/models/guest_template.go
Labels: size/XS, area/region

#13637 Automated cherry pick of #13636: fix(region): add generate_name if not before validate guest creating data
  pkg/compute/models/guest_template.go
Labels: size/XS

#13639 fix(region): show guest cnt for host
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: size/L, area/region

#13640 Automated cherry pick of #13639: fix(region): show guest cnt for host
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: size/L

#13653 Automated cherry pick of #13651: fix(scheduler): init db after init auth
  pkg/scheduler/service/service.go
Labels: size/XS

#13651 fix(scheduler): init db after init auth
  pkg/scheduler/service/service.go
Labels: size/XS, area/scheduler

#13655 Automated cherry pick of #13651: fix(scheduler): init db after init auth
  pkg/scheduler/service/service.go
Labels: size/XS

#13656 Automated cherry pick of #13651: fix(scheduler): init db after init auth
  pkg/scheduler/service/service.go
Labels: size/XS

#13652 fix(cloudmon): 3.9 release add Usage pull func
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/cloudmon/collectors/usageservice.go
Labels: size/M, area/cloudmon

#13654 Automated cherry pick of #13652: fix(cloudmon): 3.9 release add Usage pull func
  pkg/cloudmon/collectors/common/multiCloudMonUtils.go
  pkg/cloudmon/collectors/usageservice.go
Labels: size/M

#13647 fix(region): huawei storage type
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/hostdrivers/huawei.go
Labels: size/S, area/region

#13648 Automated cherry pick of #13647: fix(region): huawei storage type
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/hostdrivers/huawei.go
Labels: size/S

#13649 Automated cherry pick of #13647: fix(region): huawei storage type
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/hostdrivers/huawei.go
Labels: size/S

#13650 Automated cherry pick of #13647: fix(region): huawei storage type
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/hostdrivers/huawei.go
Labels: size/S

#13658 Automated cherry pick of #13657: fix(region): host guest cnt for deleted
  pkg/compute/models/hosts.go
Labels: size/XS

#13641 optimization for class metadata and instance backup
  pkg/compute/models/guestdisks.go
  pkg/compute/models/instance_backup.go
  pkg/compute/tasks/instance_backup_recovery_task.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/S, area/region, area/scheduler

#13642 Automated cherry pick of #13641: optimization for class metadata and instance backup
  pkg/compute/models/guestdisks.go
  pkg/compute/models/instance_backup.go
  pkg/compute/tasks/instance_backup_recovery_task.go
  pkg/scheduler/algorithm/predicates/class_metadata_predicate.go
Labels: size/S

#13666 fix: qemu no nic addr at release/3.8
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#13667 fix(host): avoid deadlock when fetch image fails
  pkg/hostman/storageman/imagecache_local.go
Labels: size/XS, area/host

#13668 Automated cherry pick of #13667: fix(host): avoid deadlock when fetch image fails
  pkg/hostman/storageman/imagecache_local.go
Labels: size/XS

#13669 Automated cherry pick of #13667: fix(host): avoid deadlock when fetch image fails
  pkg/hostman/storageman/imagecache_local.go
Labels: size/XS

#13660 Automated cherry pick of #13659: fix: aws s3 object with leading slash
  pkg/multicloud/aws/region.go
Labels: size/XS

#13661 Automated cherry pick of #13659: fix: aws s3 object with leading slash
  pkg/multicloud/aws/region.go
Labels: size/XS

#13662 Automated cherry pick of #13659: fix: aws s3 object with leading slash
  pkg/multicloud/aws/region.go
Labels: size/XS

#13645 fix(region): remove nullable tag
  pkg/cloudcommon/db/enabledbase.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/clouduser.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/deletepreventableresource.go
  pkg/compute/models/dnsrecords.go
  pkg/compute/models/dynamicschedtags.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/scalinggroup_guest.go
  pkg/compute/models/schedpolicies.go
  pkg/compute/models/skus.go
  pkg/compute/models/storages.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/endpoints.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/services.go
  pkg/keystone/models/users.go
  pkg/monitor/models/datasource.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subcontact.go
Labels: size/L, area/region

#13646 Automated cherry pick of #13645: fix(region): remove nullable tag
  pkg/cloudcommon/db/enabledbase.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/clouduser.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/deletepreventableresource.go
  pkg/compute/models/dnsrecords.go
  pkg/compute/models/dynamicschedtags.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/scalinggroup_guest.go
  pkg/compute/models/schedpolicies.go
  pkg/compute/models/skus.go
  pkg/compute/models/storages.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/endpoints.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/localusers.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/services.go
  pkg/keystone/models/users.go
  pkg/monitor/models/datasource.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subcontact.go
Labels: size/L

#13663 fix(climc): add purge splitable for action and cloudevent
  cmd/climc/shell/cloudevent/cloudevents.go
  cmd/climc/shell/logger/actions.go
Labels: size/M, area/climc

#13665 Automated cherry pick of #13663: fix(climc): add purge splitable for action and cloudevent
  cmd/climc/shell/cloudevent/cloudevents.go
  cmd/climc/shell/logger/actions.go
Labels: size/M

#13664 Automated cherry pick of #13663: fix(climc): add purge splitable for action and cloudevent
  cmd/climc/shell/cloudevent/cloudevents.go
  cmd/climc/shell/logger/actions.go
Labels: size/M

#13643 fix(region): bingo cloud request proxy
  pkg/multicloud/bingocloud/bingo.go
Labels: size/M, area/region

#13644 Automated cherry pick of #13643: fix(region): bingo cloud request proxy
  pkg/multicloud/bingocloud/bingo.go
Labels: size/M

#13670 fix(region): google disk name
  pkg/multicloud/google/instance.go
Labels: size/S, area/region

#13672 Automated cherry pick of #13670: fix(region): google disk name
  pkg/multicloud/google/instance.go
Labels: size/S

#13671 Automated cherry pick of #13670: fix(region): google disk name
  pkg/multicloud/google/instance.go
Labels: size/S

#13673 fix(glance): image save
  pkg/image/models/images.go
  pkg/image/models/storage.go
  pkg/image/tasks/image_probe_task.go
Labels: size/M, area/image

#13676 Automated cherry pick of #13673: fix(glance): image save
  pkg/image/models/images.go
  pkg/image/models/storage.go
  pkg/image/tasks/image_probe_task.go
Labels: size/M

#13674 Automated cherry pick of #13673: fix(glance): image save
  pkg/image/models/images.go
  pkg/image/models/storage.go
  pkg/image/tasks/image_probe_task.go
Labels: size/M

#13675 Automated cherry pick of #13673: fix(glance): image save
  pkg/image/models/images.go
  pkg/image/models/storage.go
  pkg/image/tasks/image_probe_task.go
Labels: size/M

#13678 Automated cherry pick of #13677: fix: server inherit the vdi_protocol of image property
  cmd/climc/shell/image/images.go
  pkg/apis/image/consts.go
  pkg/compute/models/guests.go
Labels: size/XS

#13192 Automated cherry pick of #13061: fix(keystone): auth token error
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/token.go
Labels: size/S

#13061 fix(keystone): auth token error
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/token.go
Labels: size/S, area/keystone

#13683 fix(region): remove random sync
  pkg/compute/models/cloudproviderregions.go
Labels: size/M, area/region

#13684 Automated cherry pick of #13683: fix(region): remove random sync
  pkg/compute/models/cloudproviderregions.go
Labels: size/M

#13685 Automated cherry pick of #13683: fix(region): remove random sync
  pkg/compute/models/cloudproviderregions.go
Labels: size/M

#13682 Automated cherry pick of #13679: feat(cloudcommon): db record checksum for consistency
  cmd/climc/shell/compute/servers.go
  pkg/apis/identity/consts.go
  pkg/cloudcommon/db/checksum.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/tablespec.go
  pkg/cloudcommon/options/options.go
  pkg/devtool/service/service.go
  pkg/scheduler/service/service.go
  pkg/yunionconf/service/service.go
Labels: size/L

#13686 Automated cherry pick of #13636: fix(region): add generate_name if not before validate guest creating data
  pkg/compute/models/guest_template.go
Labels: size/XS

#13559 fix(host): upload storage info with zone id
  pkg/baremetal/agent.go
  pkg/cloudcommon/agent/agent.go
  pkg/cloudcommon/agent/iagent/interface.go
  pkg/esxi/agent.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M, area/host

#13560 Automated cherry pick of #13559: fix(host): upload storage info with zone id
  pkg/baremetal/agent.go
  pkg/cloudcommon/agent/agent.go
  pkg/cloudcommon/agent/iagent/interface.go
  pkg/esxi/agent.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nas.go
  pkg/hostman/storageman/storage_nfs.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#13681 fix(host/region): fix import servers from libvirt
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#13689 Automated cherry pick of #13681: fix(host/region): fix import servers from libvirt
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#13690 Automated cherry pick of #13681: fix(host/region): fix import servers from libvirt
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/libvirt.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#13691 Db checksum
  pkg/apis/identity/consts.go
Labels: size/XS, area/keystone

#13692 Automated cherry pick of #13691: Db checksum
  pkg/apis/identity/consts.go
Labels: size/XS

#13693 fix(region): redis project sync
  pkg/compute/models/elasticcache_instances.go
Labels: size/XS, area/region

#13694 Automated cherry pick of #13693: fix(region): redis project sync
  pkg/compute/models/elasticcache_instances.go
Labels: size/XS

#13695 Automated cherry pick of #13693: fix(region): redis project sync
  pkg/compute/models/elasticcache_instances.go
Labels: size/XS

#13707 Automated cherry pick of #13705: feat(region,esxiagent): support specifying storage when creating a data disk
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/multicloud/esxi/devtools.go
  pkg/multicloud/esxi/host.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#13699 fix(region): sync owner id
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/enterprise_redis.go
  pkg/multicloud/azure/rds_managed_sqlserver.go
  pkg/multicloud/azure/rds_sqlserver.go
  pkg/multicloud/azure/redis.go
Labels: size/M, area/region

#13700 Automated cherry pick of #13699: fix(region): sync owner id
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/enterprise_redis.go
  pkg/multicloud/azure/rds_managed_sqlserver.go
  pkg/multicloud/azure/rds_sqlserver.go
  pkg/multicloud/azure/redis.go
Labels: size/M

#13701 Automated cherry pick of #13699: fix(region): sync owner id
  pkg/compute/models/dbinstances.go
  pkg/compute/models/elasticcache_instances.go
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/enterprise_redis.go
  pkg/multicloud/azure/rds_managed_sqlserver.go
  pkg/multicloud/azure/rds_sqlserver.go
  pkg/multicloud/azure/redis.go
Labels: size/M

#13696 fix(region): cloudpods error
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/shell/secgroup.go
Labels: size/M, area/region

#13697 Automated cherry pick of #13696: fix(region): cloudpods error
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/shell/secgroup.go
Labels: size/M

#13698 Automated cherry pick of #13696: fix(region): cloudpods error
  pkg/multicloud/cloudpods/cloudpods.go
  pkg/multicloud/cloudpods/shell/secgroup.go
Labels: size/M

#13702 fix(region): sync with storagecachedimage status
  pkg/compute/models/storagecaches.go
  pkg/compute/tasks/cloudregion_sync_images_task.go
Labels: size/M, area/region

#13703 Automated cherry pick of #13702: fix(region): sync with storagecachedimage status
  pkg/compute/models/storagecaches.go
  pkg/compute/tasks/cloudregion_sync_images_task.go
Labels: size/M

#13704 Automated cherry pick of #13702: fix(region): sync with storagecachedimage status
  pkg/compute/models/storagecaches.go
  pkg/compute/tasks/cloudregion_sync_images_task.go
Labels: size/M

#13711 fix: host deploy mkdir permission
  pkg/hostman/guestfs/fsdriver/base.go
Labels: size/XS

#13713 Automated cherry pick of #13711: fix: host deploy mkdir permission
  pkg/hostman/guestfs/fsdriver/base.go
Labels: size/XS

#13714 Automated cherry pick of #13711: fix: host deploy mkdir permission
  pkg/hostman/guestfs/fsdriver/base.go
Labels: size/XS

#13708 fix(region): google gcp and label
  pkg/cloudprovider/resourcetags.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/google/securitygroup.go
Labels: size/S, area/region

#13709 Automated cherry pick of #13708: fix(region): google gcp and label
  pkg/cloudprovider/resourcetags.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/google/securitygroup.go
Labels: size/S

#13715 fix(region): sku init
  pkg/compute/models/skus.go
Labels: size/XS, area/region

#13716 Automated cherry pick of #13715: fix(region): sku init
  pkg/compute/models/skus.go
Labels: size/XS

#13717 Automated cherry pick of #13715: fix(region): sku init
  pkg/compute/models/skus.go
Labels: size/XS

#13710 Automated cherry pick of #13708: fix(region): google gcp and label
  pkg/cloudprovider/resourcetags.go
  pkg/multicloud/google/instance.go
  pkg/multicloud/google/securitygroup.go
Labels: size/S

#13718 fix(region): host schedtags with topology
  pkg/apis/compute/vpc.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/XS, area/region

#13719 Automated cherry pick of #13718: fix(region): host schedtags with topology
  pkg/apis/compute/vpc.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/XS

#13720 Automated cherry pick of #13718: fix(region): host schedtags with topology
  pkg/apis/compute/vpc.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/XS

#13725 fix(region): use original project to recovery from instance backup
  pkg/compute/tasks/instance_backup_recovery_task.go
Labels: size/XS, area/region

#13726 Automated cherry pick of #13725: fix(region): use original project to recovery from instance backup
  pkg/compute/tasks/instance_backup_recovery_task.go
Labels: size/XS

#13730 fix(region): use ServerCreateInput as instanceBackup.ServerConfig
  pkg/compute/models/instance_backup.go
Labels: size/M, area/region

#13731 Automated cherry pick of #13730: fix(region): use ServerCreateInput as instanceBackup.ServerConfig
  pkg/compute/models/instance_backup.go
Labels: size/M

#13734 fix(region): get project id correctly when recovery guest
  pkg/compute/models/instance_backup.go
  pkg/compute/tasks/instance_backup_recovery_task.go
Labels: size/XS, area/region

#13735 Automated cherry pick of #13734: fix(region): get project id correctly when recovery guest
  pkg/compute/models/instance_backup.go
  pkg/compute/tasks/instance_backup_recovery_task.go
Labels: size/XS

#13727 fix(region): sku name
  pkg/compute/models/skus.go
Labels: size/S, area/region

#13728 Automated cherry pick of #13727: fix(region): sku name
  pkg/compute/models/skus.go
Labels: size/S

#13729 Automated cherry pick of #13727: fix(region): sku name
  pkg/compute/models/skus.go
Labels: size/S

#13721 fix(host): fix guest nicStat Metric in host
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/S, area/host
