Repository yunionio/cloudpods, pull requests merged in 2023-04, with the labels that each got.

#16322 fix(cloudmon): add slb key
  pkg/apis/compute/loadbalancer.go
Labels: size/XS

#16323 Automated cherry pick of #16322: fix(cloudmon): add slb key
  pkg/apis/compute/loadbalancer.go
Labels: size/XS

#16324 fix: minor fixes 20230403
  pkg/util/atexit/const.go
Labels: size/XS

#16325 Automated cherry pick of #16324: fix: minor fixes 20230403
  pkg/util/atexit/const.go
Labels: size/XS

#16326 Automated cherry pick of #16324: fix: minor fixes 20230403
  pkg/util/atexit/const.go
Labels: size/XS

#16314 fix(region): fixModelartsStatus
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/M, area/region

#16327 fix: host remove netif also remove baremnetal server netif
  pkg/compute/models/hosts.go
Labels: size/M

#16328 Automated cherry pick of #16327: fix: host remove netif also remove baremnetal server netif
  pkg/compute/models/hosts.go
Labels: size/M

#16329 Automated cherry pick of #16327: fix: host remove netif also remove baremnetal server netif
  pkg/compute/models/hosts.go
Labels: size/M

#16330 Automated cherry pick of #16327: fix: host remove netif also remove baremnetal server netif
  pkg/compute/models/hosts.go
Labels: size/M

#16331 fix(monitor): eip fields are missed in details
  pkg/monitor/models/modelset.go
Labels: size/S, area/monitor

#16332 Automated cherry pick of #16331: fix(monitor): eip fields are missed in details
  pkg/monitor/models/modelset.go
Labels: size/S

#16333 Automated cherry pick of #16331: fix(monitor): eip fields are missed in details
  pkg/monitor/models/modelset.go
Labels: size/S

#16335 fix(region): sync esxi disk access path
  pkg/compute/models/disks.go
Labels: size/XS, area/region

#16336 Automated cherry pick of #16335: fix(region): sync esxi disk access path
  pkg/compute/models/disks.go
Labels: size/XS

#16337 Automated cherry pick of #16335: fix(region): sync esxi disk access path
  pkg/compute/models/disks.go
Labels: size/XS

#16341 fix(region): fix modelarts createFailed
  go.mod
  go.sum
  pkg/compute/tasks/modelarts_pool_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/L, area/region

#16345 Automated cherry pick of #16341: fix(region): fix modelarts createFailed
  go.mod
  go.sum
  pkg/compute/tasks/modelarts_pool_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
Labels: size/L

#16346 fix: auth context with service name
  pkg/mcclient/auth/auth.go
Labels: size/XS

#16347 Automated cherry pick of #16346: fix: auth context with service name
  pkg/mcclient/auth/auth.go
Labels: size/XS

#16343 fix: send email queue to cc
  pkg/apis/notify/emailqueue.go
  pkg/mcclient/options/notify/emailqueues.go
  pkg/notify/models/emailqueue.go
  pkg/notify/sender/email.go
Labels: size/M

#16344 Automated cherry pick of #16343: fix: send email queue to cc
  pkg/apis/notify/emailqueue.go
  pkg/mcclient/options/notify/emailqueues.go
  pkg/notify/models/emailqueue.go
  pkg/notify/sender/email.go
Labels: size/M

#16340 fix: distinct field with subquery
  pkg/cloudcommon/db/modelbase.go
Labels: size/XS

#16342 Automated cherry pick of #16340: fix: distinct field with subquery
  pkg/cloudcommon/db/modelbase.go
Labels: size/XS

#16350 fix: async setup brvpc mtu 3.9
  pkg/hostman/hostinfo/hostovn.go
Labels: size/S

#16351 fix: allow async setup brvpc mtu
  pkg/util/ovnutils/ovnutils.go
Labels: size/S

#16352 Automated cherry pick of #16351: fix: allow async setup brvpc mtu
  pkg/util/ovnutils/ovnutils.go
Labels: size/S

#16348 fix: allow set project-id auto-crate-project of cloudaccount
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/initdb.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/L

#16349 Automated cherry pick of #16348: fix: allow set project-id auto-crate-project of cloudaccount
  pkg/apis/compute/cloudaccount.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/initdb.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/L

#16353 fix(cloudmon): esxi disk usage
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/esxi.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/monitor.go
Labels: size/L, area/cloudmon

#16356 Automated cherry pick of #16353: fix(cloudmon): esxi disk usage
  pkg/cloudmon/providerdriver/esxi.go
  pkg/multicloud/esxi/monitor.go
Labels: size/L

#16355 fix(region): addModelartsCreateFailedReason
  pkg/cloudprovider/cloudprovider.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
Labels: lgtm, size/S, area/region

#16360 fix(cloudmon): bingo metric
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/base.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/monitor.go
Labels: size/M, area/cloudmon

#16361 Automated cherry pick of #16360: fix(cloudmon): bingo metric
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/base.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/monitor.go
Labels: size/M

#16362 Automated cherry pick of #16360: fix(cloudmon): bingo metric
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudprovider/metrics.go
  pkg/multicloud/bingocloud/monitor.go
Labels: size/M

#16367 fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
Labels: size/S, area/region

#16368 Automated cherry pick of #16367: fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
Labels: size/S

#16369 Automated cherry pick of #16367: fix(region): vender update
  pkg/multicloud/aliyun/provider/provider.go
Labels: size/XS

#16365 Automated cherry pick of #16311: fix(region): support fast sync cloud resources
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/cloudproviderregion.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#16366 Automated cherry pick of #16311: fix(region): support fast sync cloud resources
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
  pkg/apis/compute/cloudproviderregion.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
Labels: size/S

#16358 fix(baremetal): panic occured when using SSD as raid PD
  pkg/baremetal/utils/disktool/disktool.go
Labels: size/XS, area/baremetal

#16359 Automated cherry pick of #16358: fix(baremetal): panic occured when using SSD as raid PD
  pkg/baremetal/utils/disktool/disktool.go
Labels: size/XS

#16363 Automated cherry pick of #16358: fix(baremetal): panic occured when using SSD as raid PD
  pkg/baremetal/utils/disktool/disktool.go
Labels: size/XS

#16371 fix(region): azure china user create
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/clouduser.go
Labels: size/M, area/region

#16372 Automated cherry pick of #16371: fix(region): azure china user create
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/clouduser.go
Labels: size/M

#16373 Automated cherry pick of #16371: fix(region): azure china user create
  pkg/multicloud/azure/azure.go
  pkg/multicloud/azure/cloudgroup.go
  pkg/multicloud/azure/clouduser.go
Labels: size/S

#16374 fix(region): openstack keypair
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
Labels: size/S, area/region

#16375 Automated cherry pick of #16374: fix(region): openstack keypair
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
Labels: size/S

#16376 Automated cherry pick of #16374: fix(region): openstack keypair
  pkg/multicloud/openstack/openstack.go
Labels: size/XS

#16370 fix(region): modelarts delete deff failed,timeout
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/resources.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
  pkg/multicloud/hcso/hcso.go
  pkg/multicloud/hcso/modelarts.go
  pkg/multicloud/hcso/shell/modelarts.go
  pkg/multicloud/huawei/modelarts_pool.go
  pkg/multicloud/huawei/shell/modelarts_pool.go
  pkg/multicloud/region_base.go
Labels: lgtm, size/L

#16377 fix(region): not set default data when batch creating disks
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/compute/disks.go
Labels: size/S, area/region, area/climc

#16378 Automated cherry pick of #16377: fix(region): not set default data when batch creating disks
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/compute/disks.go
Labels: size/S

#16379 Automated cherry pick of #16377: fix(region): not set default data when batch creating disks
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/compute/disks.go
Labels: size/S

#16381 fix(webconsole): avoid panic when send stats request
  pkg/webconsole/service/service.go
Labels: size/XS, area/webconsole

#16382 Automated cherry pick of #16381: fix(webconsole): avoid panic when send stats request
  pkg/webconsole/service/service.go
Labels: size/XS

#16383 Automated cherry pick of #16381: fix(webconsole): avoid panic when send stats request
  pkg/webconsole/service/service.go
Labels: size/XS

#16384 fix(region): vendor update for openstack nic
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/instancenic.go
Labels: size/S, area/region

#16385 Automated cherry pick of #16384: fix(region): vendor update for openstack nic
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/instancenic.go
Labels: size/S

#16386 Automated cherry pick of #16384: fix(region): vendor update for openstack nic
  pkg/multicloud/openstack/instancenic.go
Labels: size/S

#16398 fix(devtool): panic occurred cause of nil ctx
  pkg/apigateway/handler/syslog_webservices.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/devtool/service/service.go
Labels: size/S, area/devtool

#16399 Automated cherry pick of #16398: fix(devtool): panic occurred cause of nil ctx
  pkg/apigateway/handler/syslog_webservices.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/devtool/service/service.go
Labels: size/S

#16400 Automated cherry pick of #16398: fix(devtool): panic occurred cause of nil ctx
  pkg/apigateway/handler/syslog_webservices.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/devtool/service/service.go
Labels: size/S

#16395 fix(region): remove useless server sku
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
Labels: size/M, area/region

#16396 Automated cherry pick of #16395: fix(region): remove useless server sku
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
Labels: size/M

#16397 Automated cherry pick of #16395: fix(region): remove useless server sku
  pkg/compute/models/guests.go
  pkg/compute/models/skus.go
Labels: size/M

#16394 fix: backport opslog clickhouse partition expression to 3.9
  pkg/cloudcommon/db/opslog.go
Labels: size/XS

#16406 fix: lbagent ovn options shoule not in common
  pkg/lbagent/options.go
  pkg/util/ovnutils/ovnutils.go
Labels: size/XS

#16407 Automated cherry pick of #16406: fix: lbagent ovn options shoule not in common
  pkg/lbagent/options.go
  pkg/util/ovnutils/ovnutils.go
Labels: size/XS

#16403 fix(region): optimized cloudprovider list
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudprovidercapacities.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
Labels: size/L

#16404 Automated cherry pick of #16403: fix(region): optimized cloudprovider list
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudprovidercapacities.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
Labels: size/L

#16405 Automated cherry pick of #16403: fix(region): optimized cloudprovider list
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudprovidercapacities.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
Labels: size/L

#16411 fix(keystone): avoid panic when sync scope reosurce
  pkg/keystone/cronjobs/project_resources.go
Labels: size/XS, area/keystone

#16413 Automated cherry pick of #16411: fix(keystone): avoid panic when sync scope reosurce
  pkg/keystone/cronjobs/project_resources.go
Labels: size/XS

#16412 Automated cherry pick of #16411: fix(keystone): avoid panic when sync scope reosurce
  pkg/keystone/cronjobs/project_resources.go
Labels: size/XS

#16409 Automated cherry pick of #16408: fix(common): show exception with remote addr and duration
  pkg/appsrv/appsrv.go
Labels: size/S

#16410 Automated cherry pick of #16408: fix(common): show exception with remote addr and duration
  pkg/appsrv/appsrv.go
Labels: size/S

#16414 fix(common): log time with time zone
  go.mod
  go.sum
  pkg/cloudcommon/options/options.go
  vendor/modules.txt
  vendor/yunion.io/x/log/formatter.go
Labels: size/S, area/common

#16415 Automated cherry pick of #16414: fix(common): log time with time zone
  go.mod
  go.sum
  pkg/cloudcommon/options/options.go
  vendor/modules.txt
  vendor/yunion.io/x/log/formatter.go
Labels: size/S

#16416 Automated cherry pick of #16414: fix(common): log time with time zone
  go.mod
  go.sum
  pkg/cloudcommon/options/options.go
  vendor/modules.txt
  vendor/yunion.io/x/log/formatter.go
Labels: size/S

#16417 fix(common): log time zone and format
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
  pkg/httperrors/httperrors.go
Labels: size/M, area/common

#16418 Automated cherry pick of #16417: fix(common): log time zone and format
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
  pkg/httperrors/httperrors.go
Labels: size/M

#16419 Automated cherry pick of #16417: fix(common): log time zone and format
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
  pkg/httperrors/httperrors.go
Labels: size/M

#16420 Automated cherry pick of #16417: fix(common): log time zone and format
  pkg/cloudcommon/options/options.go
  pkg/httperrors/httperrors.go
Labels: size/S

#16401 feature(region): add resource order
  cmd/climc/shell/compute/cloudregions.go
  cmd/climc/shell/compute/instance_snapshots.go
  cmd/climc/shell/compute/snapshot_policy.go
  cmd/climc/shell/compute/snapshots.go
  cmd/climc/shell/compute/zones.go
  pkg/apis/compute/backup.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/elasticips_const.go
  pkg/apis/compute/geo_input.go
  pkg/apis/compute/globalvpc.go
  pkg/apis/compute/input.go
  pkg/apis/compute/instance_backup.go
  pkg/apis/compute/instance_group.go
  pkg/apis/compute/instance_snapshot.go
  pkg/apis/compute/inter_vpc_network.go
  pkg/apis/compute/net_tap_services.go
  pkg/apis/compute/network.go
  pkg/apis/compute/sku_const.go
  pkg/apis/compute/snapshot.go
  pkg/apis/compute/vpcs_const.go
  pkg/apis/compute/wire.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/diskbackups.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/globalvpcs.go
  pkg/compute/models/groups.go
  pkg/compute/models/guests.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/inter_vpc_network.go
  pkg/compute/models/net_tap_services.go
  pkg/compute/models/networks.go
  pkg/compute/models/schedtags.go
  pkg/compute/models/skus.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/compute/models/zones.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/compute/backup.go
  pkg/mcclient/options/compute/eips.go
  pkg/mcclient/options/compute/globalvpc.go
  pkg/mcclient/options/compute/instancegroup.go
  pkg/mcclient/options/compute/net_tap_services.go
  pkg/mcclient/options/compute/network.go
  pkg/mcclient/options/inter_vpc_network.go
  pkg/mcclient/options/serverskus.go
  pkg/mcclient/options/vpc.go
  pkg/mcclient/options/wire.go
Labels: lgtm, size/L, area/region

#16425 Automated cherry pick of #16424: fix(common): show request time with rfc3339
  pkg/httperrors/httperrors.go
  pkg/mcclient/modulebase/base.go
Labels: size/S

#16426 Automated cherry pick of #16424: fix(common): show request time with rfc3339
  pkg/httperrors/httperrors.go
  pkg/mcclient/modulebase/base.go
Labels: size/S

#16427 Automated cherry pick of #16424: fix(common): show request time with rfc3339
  pkg/httperrors/httperrors.go
  pkg/mcclient/modulebase/base.go
Labels: size/S

#16429 fix: only request error show time
  pkg/mcclient/modulebase/base.go
Labels: size/XS

#16430 Automated cherry pick of #16429: fix: only request error show time
  pkg/mcclient/modulebase/base.go
Labels: size/XS

#16431 Automated cherry pick of #16429: fix: only request error show time
  pkg/mcclient/modulebase/base.go
Labels: size/XS

#16432 Automated cherry pick of #16429: fix: only request error show time
  pkg/mcclient/modulebase/base.go
Labels: size/XS

#16437 fix: clickhouse parttion expression of divide inconstent 3.9
  pkg/cloudevent/models/cloudevents.go
  pkg/logger/models/baremetalevents.go
Labels: size/XS

#16439 Automated cherry pick of #16437: fix: clickhouse parttion expression of divide inconstent 3.9
  pkg/cloudevent/models/cloudevents.go
  pkg/logger/models/baremetalevents.go
Labels: size/XS

#16451 fix(excelutils): 添加千位分隔常量
  pkg/util/excelutils/const.go
Labels: lgtm, size/XS

#16452 Automated cherry pick of #16451: fix(excelutils): 添加千位分隔常量
  pkg/util/excelutils/const.go
Labels: size/XS

#16441 fix(region): sync purge vpc
  pkg/compute/models/vpcs.go
Labels: size/XS, area/region

#16442 Automated cherry pick of #16441: fix(region): sync purge vpc
  pkg/compute/models/vpcs.go
Labels: size/XS

#16443 Automated cherry pick of #16441: fix(region): sync purge vpc
  pkg/compute/models/vpcs.go
Labels: size/XS

#16444 fix(region): support import private k8s
  pkg/compute/models/kube_clusters.go
Labels: size/M, area/region

#16446 Automated cherry pick of #16444: fix(region): support import private k8s
  pkg/compute/models/kube_clusters.go
Labels: size/M

#16440 fix(glance): support esxi glance debug on macos
  pkg/util/iproute2/address_linux.go
  pkg/util/iproute2/address_others.go
  pkg/util/iproute2/route_linux.go
  pkg/util/iproute2/route_others.go
  pkg/util/netutils2/netutils_others.go
  pkg/util/procutils/remote_readdir.go
  pkg/util/procutils/remote_stat.go
  pkg/util/qemuimg/qemuimg.go
  pkg/util/qemutils/qemutils.go
Labels: size/L

#16449 Automated cherry pick of #16440: fix(glance): support esxi glance debug on macos
  pkg/util/iproute2/address_linux.go
  pkg/util/iproute2/address_others.go
  pkg/util/iproute2/route_linux.go
  pkg/util/iproute2/route_others.go
  pkg/util/netutils2/netutils_others.go
  pkg/util/procutils/remote_readdir.go
  pkg/util/procutils/remote_stat.go
  pkg/util/qemuimg/qemuimg.go
  pkg/util/qemutils/qemutils.go
Labels: size/L

#16447 fix(host): set default live migrate bandwidth unlimited
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#16448 Automated cherry pick of #16447: fix(host): set default live migrate bandwidth unlimited
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#16434 feat(region): set kvm storage instance capability
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/options/options.go
Labels: size/S, area/region

#16435 Automated cherry pick of #16434: feat(region): set kvm storage instance capability
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/options/options.go
Labels: size/S

#16436 Automated cherry pick of #16434: feat(region): set kvm storage instance capability
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/options/options.go
Labels: size/S

#16456 fix(region): change modelarts validateDeleteCondition
  pkg/compute/models/modelarts_pools.go
Labels: size/XS

#16458 fix(monitor): wrong tag filter when get metric measurement
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/XS, area/monitor

#16459 Automated cherry pick of #16458: fix(monitor): wrong tag filter when get metric measurement
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/XS

#16460 Automated cherry pick of #16458: fix(monitor): wrong tag filter when get metric measurement
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/XS

#16461 fix(region): fixModelarts
  build/docker/Dockerfile.esxi-agent
  go.mod
  go.sum
  pkg/compute/models/modelarts_pools.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/ovf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/std_json.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: lgtm, size/L, area/region

#16462 Automated cherry pick of #16461: fix(region): fixModelarts
  build/docker/Dockerfile.esxi-agent
  go.mod
  go.sum
  pkg/compute/models/modelarts_pools.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/ovf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/std_json.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: size/L

#16457 Automated cherry pick of #16447: fix(host): set default live migrate bandwidth unlimited
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#16467 fix: update vendor 20230413
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/region.go
  vendor/yunion.io/x/jsonutils/Makefile
  vendor/yunion.io/x/jsonutils/jsonpointer.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/marshal_session.go
  vendor/yunion.io/x/jsonutils/parse_session.go
  vendor/yunion.io/x/jsonutils/std_json.go
  vendor/yunion.io/x/jsonutils/string.go
  vendor/yunion.io/x/jsonutils/unmarshal.go
  vendor/yunion.io/x/jsonutils/unmarshal_session.go
  vendor/yunion.io/x/jsonutils/write.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
Labels: size/XL

#16469 Automated cherry pick of #16467: fix: update vendor 20230413
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/unmarshal.go
Labels: size/S

#16471 fix(host): update cpudesc on cpu hotpluged
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#16472 Automated cherry pick of #16471: fix(host): update cpudesc on cpu hotpluged
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#16476 fix: issue模板改进 20230414
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-request.md
Labels: size/S

#16463 fix: avoid panic when sync vmware host
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
Labels: size/S, area/region

#16481 Automated cherry pick of #16463: fix: avoid panic when sync vmware host
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hosts.go
Labels: size/S

#16742 fix(vendor): update vendor for v3.10
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go
  vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/std_json.go
Labels: size/L, area/util

#16809 fix(notify): fix receiver create bug
  pkg/notify/models/receiver.go
Labels: lgtm, size/XS

#16811 Automated cherry pick of #16809: fix(notify): fix receiver create bug
  pkg/notify/models/receiver.go
Labels: size/XS

#16791 fix(cloudmon): support skip pull azure memory and disk usage metric
  go.mod
  go.sum
  pkg/cloudmon/options/options.go
  pkg/cloudmon/providerdriver/base.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/monitor.go
Labels: size/L, area/cloudmon

#16807 Automated cherry pick of #16791: fix(cloudmon): support skip pull azure memory and disk usage metric
  go.mod
  go.sum
  pkg/cloudmon/options/options.go
  pkg/cloudmon/providerdriver/base.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/monitor.go
Labels: size/L

#16808 Automated cherry pick of #16791: fix(cloudmon): support skip pull azure memory and disk usage metric
  pkg/cloudmon/options/options.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudprovider/metrics.go
  pkg/multicloud/azure/monitor.go
Labels: size/L

#16814 fix(monitor): disable query signature defaultly
  pkg/monitor/options/options.go
Labels: size/XS, area/monitor

#16815 Automated cherry pick of #16814: fix(monitor): disable query signature defaultly
  pkg/monitor/options/options.go
Labels: size/XS

#16816 Automated cherry pick of #16814: fix(monitor): disable query signature defaultly
  pkg/monitor/options/options.go
Labels: size/XS

#16818 fix(region): proxmox host ip
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/M, area/region

#16819 Automated cherry pick of #16818: fix(region): proxmox host ip
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/M

#16828 fix(region): vendor update for aws region
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
Labels: size/M, area/region

#16829 Automated cherry pick of #16828: fix(region): vendor update for aws region
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
Labels: size/M

#16830 Automated cherry pick of #16828: fix(region): vendor update for aws region
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/multicloud/aws/latitude_and_longitude.go
  pkg/multicloud/aws/region.go
Labels: size/M

#16820 fix(host): fix machine type before generate cpu desc
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#16821 Automated cherry pick of #16820: fix(host): fix machine type before generate cpu desc
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#16825 fix(region): log with account disconnect reason
  pkg/compute/models/cloudaccounts.go
Labels: size/XS, area/region

#16826 Automated cherry pick of #16825: fix(region): log with account disconnect reason
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#16827 Automated cherry pick of #16825: fix(region): log with account disconnect reason
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#16833 fix(notify): add subcontact fail details
  pkg/notify/sender/dingtalk.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/workwx.go
Labels: lgtm, size/S

#16835 fix(host): arm node failed get numa architecture use ghw lib
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/modules.txt
Labels: size/M

#16836 Automated cherry pick of #16835: fix(host): arm node failed get numa architecture use ghw lib
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/modules.txt
Labels: size/M

#16842 fix(cloudmon): h3c rds monitor
  pkg/cloudmon/providerdriver/h3c.go
Labels: size/M, area/cloudmon

#16843 Automated cherry pick of #16842: fix(cloudmon): h3c rds monitor
  pkg/cloudmon/providerdriver/h3c.go
Labels: size/M

#16848 fix(region): check disk purge get host error is sql.ErrNoRows
  pkg/compute/tasks/disk_delete_task.go
Labels: size/XS

#16849 Automated cherry pick of #16848: fix(region): check disk purge get host error is sql.ErrNoRows
  pkg/compute/tasks/disk_delete_task.go
Labels: size/XS

#16852 fix(notify): fix email verify empty error
  pkg/notify/tasks/verification_send_task.go
Labels: size/XS

#16853 Automated cherry pick of #16852: fix(notify): fix email verify empty error
  pkg/notify/tasks/verification_send_task.go
Labels: size/XS

#16857 fix(region): handle probe-isolated-device error
  pkg/compute/hostdrivers/kvm.go
Labels: size/XS, area/region
