Repository yunionio/cloudpods, pull requests merged in 2023-01, with the labels that each got.

#15680 Automated cherry pick of #15679: fix(region): sriov vfio-pci driver manual deploy nic
  pkg/compute/models/guestnetworks.go
Labels: size/XS

#15681 Automated cherry pick of #15664: Automated cherry pick of #15618: fix(host): use drive backup sync backup disks
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/ha_guest_start_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#15679 fix(region): sriov vfio-pci driver manual deploy nic
  pkg/compute/models/guestnetworks.go
Labels: size/XS

#15618 fix(host): use drive backup sync backup disks
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/ha_guest_start_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#15664 Automated cherry pick of #15618: fix(host): use drive backup sync backup disks
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/ha_guest_start_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#15607 fix(notify): add some template and notification
  build/notify/root/opt/yunion/share/local-templates/content@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/USER_LOCK copy.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/WORK_BLOCK.tmpl
  pkg/apihelper/apihelper.go
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/compute/models/cloudaccounts.go
  pkg/keystone/models/passwords.go
  pkg/keystone/service/service.go
  pkg/notify/models/topic.go
Labels: size/L

#15669 Automated cherry pick of #15607: fix(notify): add some template and notification
  build/notify/root/opt/yunion/share/local-templates/content@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/USER_LOCK copy.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/WORK_BLOCK.tmpl
  pkg/apihelper/apihelper.go
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/compute/models/cloudaccounts.go
  pkg/keystone/models/passwords.go
  pkg/keystone/service/service.go
  pkg/notify/models/topic.go
Labels: size/L

#15670 Automated cherry pick of #15607: fix(notify): add some template and notification
  build/notify/root/opt/yunion/share/local-templates/content@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@cn/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SYNC_ACCOUNT_STATUS.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/WORK_BLOCK.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/NET_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/USER_LOCK copy.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/WORK_BLOCK.tmpl
  pkg/apihelper/apihelper.go
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/compute/models/cloudaccounts.go
  pkg/keystone/models/passwords.go
  pkg/keystone/service/service.go
  pkg/notify/models/topic.go
Labels: size/L

#15682 feature: list results carry extra total stats
  Makefile
  go.mod
  go.sum
  pkg/apis/list.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
  pkg/mcclient/modulebase/base.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/printutils/printjson.go
  vendor/yunion.io/x/pkg/util/printutils/struct.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: size/L

#15683 Automated cherry pick of #15682: feature: list results carry extra total stats
  Makefile
  go.mod
  go.sum
  pkg/apis/list.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
  pkg/mcclient/modulebase/base.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/printutils/printjson.go
  vendor/yunion.io/x/pkg/util/printutils/struct.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: size/L

#15686 fix: get user ids by role ids in scope
  pkg/mcclient/modules/identity/mod_roleassignments.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/M

#15684 fix: make cloudaccount options visbile in list
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#15685 Automated cherry pick of #15684: fix: make cloudaccount options visbile in list
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#15687 Automated cherry pick of #15686: fix: get user ids by role ids in scope
  pkg/mcclient/modules/identity/mod_roleassignments.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/M

#15694 fix(scheduler): do migrate checking when hypervisor is not esxi
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/M, area/scheduler

#15695 Automated cherry pick of #15694: fix(scheduler): do migrate checking when hypervisor is not esxi
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/M

#15696 Automated cherry pick of #15694: fix(scheduler): do migrate checking when hypervisor is not esxi
  pkg/scheduler/algorithm/predicates/guest/migrate_predicate.go
Labels: size/M

#15692 fix(region): aws lb optimized
  go.mod
  go.sum
  pkg/apis/compute/loadbalancer_const.go
  pkg/apis/compute/loadbalancerlistener.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/nutanix.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/loadbalancer_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
Labels: size/XXL, area/region

#15697 fix(keystone): project-show by name with not found error
  pkg/cloudcommon/db/fetch.go
Labels: size/XS, area/keystone

#15698 Automated cherry pick of #15697: fix(keystone): project-show by name with not found error
  pkg/cloudcommon/db/fetch.go
Labels: size/XS

#15693 Automated cherry pick of #15692: fix(region): aws lb optimized
  go.mod
  go.sum
  pkg/apis/compute/loadbalancer_const.go
  pkg/apis/compute/loadbalancerlistener.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/esxi.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/nutanix.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/ucloud.go
  pkg/compute/regiondrivers/zstack.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/loadbalancer_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
Labels: size/XXL

#15689 Automated cherry pick of #15688: fix(region): redis sync error optimized
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/M

#15699 fix(keystone): avoid panic
  pkg/cloudcommon/db/fetch.go
Labels: size/XS, area/keystone

#15700 Automated cherry pick of #15699: fix(keystone): avoid panic
  pkg/cloudcommon/db/fetch.go
Labels: size/XS

#15701 fix(region): vender update
  go.mod
  go.sum
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guestsecgroups.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/host_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/region.go
Labels: size/M, area/region

#15702 Automated cherry pick of #15701: fix(region): vender update
  go.mod
  go.sum
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guestsecgroups.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/host_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/region.go
Labels: size/M

#15704 Automated cherry pick of #15701: fix(region): vender update
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guestsecgroups.go
  pkg/multicloud/google/securitygroup.go
  pkg/multicloud/host_base.go
  pkg/multicloud/qcloud/region.go
Labels: size/M

#15690 feat(host): sriov nic monitor
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#15691 Automated cherry pick of #15690: feat(host): sriov nic monitor
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#15705 fix(notify): update MYSQL_OUT_OF_SYNC template
  build/notify/root/opt/yunion/share/local-templates/content@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/MYSQL_OUT_OF_SYNC.tmpl
Labels: size/M, area/notify

#15706 Automated cherry pick of #15705: fix(notify): update MYSQL_OUT_OF_SYNC template
  build/notify/root/opt/yunion/share/local-templates/content@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/MYSQL_OUT_OF_SYNC.tmpl
Labels: size/M

#15707 Automated cherry pick of #15705: fix(notify): update MYSQL_OUT_OF_SYNC template
  build/notify/root/opt/yunion/share/local-templates/content@cn/MYSQL_OUT_OF_SYNC.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/MYSQL_OUT_OF_SYNC.tmpl
Labels: size/M

#15710 fix: init shceduler schedinfo project and domain
  pkg/scheduler/api/sched.go
Labels: size/XS

#15711 Automated cherry pick of #15710: fix: init shceduler schedinfo project and domain
  pkg/scheduler/api/sched.go
Labels: size/XS

#15713 Automated cherry pick of #15710: fix: init shceduler schedinfo project and domain
  pkg/scheduler/api/sched.go
Labels: size/XS

#14958 fix(worker): policy and task worker count configurable
  cmd/climc/shell/identity/policies.go
  pkg/appsrv/workers.go
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/options/options.go
  pkg/cloudcommon/policy/global.go
  pkg/cloudcommon/policy/policy.go
  pkg/compute/service/service.go
Labels: size/M

#15716 Automated cherry pick of #14958: fix(worker): policy and task worker count configurable
  cmd/climc/shell/identity/policies.go
  pkg/appsrv/workers.go
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/options/options.go
  pkg/cloudcommon/policy/global.go
  pkg/cloudcommon/policy/policy.go
  pkg/compute/service/service.go
Labels: size/M

#15715 Automated cherry pick of #14958: fix(worker): policy and task worker count configurable
  cmd/climc/shell/identity/policies.go
  pkg/appsrv/workers.go
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/options/options.go
  pkg/cloudcommon/policy/global.go
  pkg/cloudcommon/policy/policy.go
  pkg/compute/service/service.go
Labels: size/M

#15714 Automated cherry pick of #14958: fix(worker): policy and task worker count configurable
  cmd/climc/shell/identity/policies.go
  pkg/appsrv/workers.go
  pkg/cloudcommon/app/auth.go
  pkg/cloudcommon/db/taskman/worker.go
  pkg/cloudcommon/options/options.go
  pkg/cloudcommon/policy/global.go
  pkg/cloudcommon/policy/policy.go
  pkg/compute/service/service.go
Labels: size/M

#15717 fix: need more args in CustomizedTotalCount
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
Labels: size/XS

#15718 Automated cherry pick of #15717: fix: need more args in CustomizedTotalCount
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/guests.go
Labels: size/XS

#15709 fix(region): account sync status
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/tasks/cloud_account_sync_task.go
Labels: size/S, area/region

#15719 Automated cherry pick of #15709: fix(region): account sync status
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/tasks/cloud_account_sync_task.go
Labels: size/S

#15720 Automated cherry pick of #15709: fix(region): account sync status
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/tasks/cloud_account_sync_task.go
Labels: size/S

#15721 fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
Labels: size/M, area/region

#15722 Automated cherry pick of #15721: fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
Labels: size/M

#15723 Automated cherry pick of #15721: fix(region): vender update
  pkg/multicloud/aliyun/instance.go
  pkg/multicloud/bingocloud/instance.go
Labels: size/M

#15725 fix(region): vmware migrate
  go.mod
  go.sum
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_live_migrate_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
Labels: size/L, area/region

#15726 Automated cherry pick of #15725: fix(region): vmware migrate
  go.mod
  go.sum
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_live_migrate_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
Labels: size/L

#15729 fix(region): optimzed zone-list speed
  pkg/compute/models/zones.go
Labels: size/L, area/region

#15731 Automated cherry pick of #15729: fix(region): optimzed zone-list speed
  pkg/compute/models/zones.go
Labels: size/L

#15730 Automated cherry pick of #15729: fix(region): optimzed zone-list speed
  pkg/compute/models/zones.go
Labels: size/L

#15736 Automated cherry pick of #15727: fix(excelutils): add excel chart func
  pkg/util/excelutils/const.go
  pkg/util/excelutils/excelutils.go
Labels: size/L

#15732 feat(host): kvm vcpus bind cpuset on numa nodes and cpu dies
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
Labels: size/L

#15733 Automated cherry pick of #15732: feat(host): kvm vcpus bind cpuset on numa nodes and cpu dies
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
Labels: size/L

#15734 fix: simplify and accelerate query of notification
  pkg/notify/models/notification.go
  pkg/notify/models/receiver_notification.go
Labels: size/M, area/notify

#15735 Automated cherry pick of #15734: fix: simplify and accelerate query of notification
  pkg/notify/models/notification.go
  pkg/notify/models/receiver_notification.go
Labels: size/M

#15744 Automated cherry pick of #15725: fix(region): vmware migrate
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/multicloud/esxi/vdisk.go
  pkg/multicloud/esxi/virtualmachine.go
Labels: size/L

#15742 fix(host-deployer): windows 2008 Out-File IOException
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/S

#15743 Automated cherry pick of #15742: fix(host-deployer): windows 2008 Out-File IOException
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/S

#15745 Automated cherry pick of #15742: fix(host-deployer): windows 2008 Out-File IOException
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/S

#15737 fix(region): hostname validate
  pkg/compute/models/hostnameresource.go
Labels: size/XS, area/region

#15738 Automated cherry pick of #15737: fix(region): hostname validate
  pkg/compute/models/hostnameresource.go
Labels: size/XS

#15739 Automated cherry pick of #15737: fix(region): hostname validate
  pkg/compute/models/hostnameresource.go
Labels: size/XS

#15749 feat(region): bind network ip macs
  cmd/climc/shell/compute/network_ip_mac.go
  pkg/apis/compute/network.go
  pkg/compute/models/guests.go
  pkg/compute/models/initdb.go
  pkg/compute/models/network_ip_mac.go
  pkg/compute/service/handlers.go
  pkg/mcclient/modules/compute/mod_network_ip_macs.go
  pkg/mcclient/options/network.go
Labels: size/L

#15752 Automated cherry pick of #15750: fix(region): vender update
  pkg/compute/models/elasticips.go
  pkg/compute/models/natgateways.go
  pkg/multicloud/huawei/natgateway.go
  pkg/multicloud/openstack/instance.go
Labels: size/M

#15747 fix(region): qcloud lb backend create
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_backend_create_task.go
Labels: size/M, area/region

#15748 Automated cherry pick of #15747: fix(region): qcloud lb backend create
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_backend_create_task.go
Labels: size/M

#15763 fix(region): network_ip_mac update check
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/network_ip_mac.go
  pkg/util/logclient/consts.go
Labels: size/M

#15765 Automated cherry pick of #15763: fix(region): network_ip_mac update check
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/network_ip_mac.go
  pkg/util/logclient/consts.go
Labels: size/M

#15761 Automated cherry pick of #15760: Automated cherry pick of #15759: fix(region): auto switch to backup on host down
  pkg/apis/input.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/host_health.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#15756 fix(region): network_ip_macs allow update ip and mac
  pkg/compute/models/network_ip_mac.go
Labels: size/XS

#15757 Automated cherry pick of #15756: fix(region): network_ip_macs allow update ip and mac
  pkg/compute/models/network_ip_mac.go
Labels: size/XS

#15754 fix(host): isolated_deivce hotplug check addr
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#15755 Automated cherry pick of #15754: fix(host): isolated_deivce hotplug check addr
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#15758 fix cherrypick script
  scripts/cherry_pick_pull.sh
Labels: size/XS

#15768 fix(region): vender update for qcloud lb listener
  go.mod
  go.sum
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/loadbalancerlisteners.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/L, area/region

#15769 Automated cherry pick of #15768: fix(region): vender update for qcloud lb listener
  go.mod
  go.sum
  pkg/apis/compute/loadbalancer_const.go
  pkg/compute/models/loadbalancerlisteners.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/L

#15774 fix(cloudmon): cloudpods load
  cmd/cloudevent/main.go
  cmd/cloudmon/main.go
Labels: size/XS, area/cloudmon

#15775 Automated cherry pick of #15774: fix(cloudmon): cloudpods load
  cmd/cloudevent/main.go
  cmd/cloudmon/main.go
Labels: size/XS

#15771 fix(common): service exception
  pkg/appsrv/appparams.go
  pkg/appsrv/appsrv.go
  pkg/compute/service/service.go
Labels: size/M, area/common

#15772 Automated cherry pick of #15771: fix(common): service exception
  pkg/appsrv/appparams.go
  pkg/appsrv/appsrv.go
  pkg/compute/service/service.go
Labels: size/M

#15773 fix(region): qga set password status on failed
  pkg/apis/compute/guest_const.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
Labels: size/XS

#15776 Automated cherry pick of #15773: fix(region): qga set password status on failed
  pkg/apis/compute/guest_const.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
Labels: size/XS

#15783 fix(region): vender update for vmware timeout
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/manager.go
Labels: size/S, area/esxiagent

#15784 Automated cherry pick of #15783: fix(region): vender update for vmware timeout
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/manager.go
Labels: size/S

#15780 fix(notify): Add topic result
  pkg/compute/models/guest_actions.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
  pkg/notify/models/topic.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/M

#15785 Automated cherry pick of #15780: fix(notify): Add topic result
  pkg/compute/models/guest_actions.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
  pkg/notify/models/topic.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/M

#15790 Automated cherry pick of #15780: fix(notify): Add topic result
  pkg/compute/models/guest_actions.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
  pkg/notify/models/topic.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/M

#15787 fix(region): optimized capability
  pkg/compute/models/capabilities.go
Labels: size/XS, area/region

#15788 Automated cherry pick of #15787: fix(region): optimized capability
  pkg/compute/models/capabilities.go
Labels: size/XS

#15789 Automated cherry pick of #15787: fix(region): optimized capability
  pkg/compute/models/capabilities.go
Labels: size/XS

#15791 fix(notify): send msg with custom brand
  pkg/notify/models/event_template.go
  pkg/notify/models/template.go
Labels: size/S, area/notify

#15793 Automated cherry pick of #15791: fix(notify): send msg with custom brand
  pkg/notify/models/event_template.go
  pkg/notify/models/template.go
Labels: size/S

#15795 Automated cherry pick of #15794: fix(region): update guest status on backup guest start complete
  pkg/compute/tasks/guest_backup_tasks.go
Labels: size/XS

#15796 Automated cherry pick of #15794: fix(region): update guest status on backup guest start complete
  pkg/compute/tasks/guest_backup_tasks.go
Labels: size/XS

#15740 fix(region): unified name sync options
  pkg/compute/models/cachedimages.go
  pkg/compute/models/cdn_domains.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elastic_search.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/filesystem.go
  pkg/compute/models/guests.go
  pkg/compute/models/inter_vpc_network.go
  pkg/compute/models/ipv6_gateways.go
  pkg/compute/models/kafka.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/modelarts_pools.go
  pkg/compute/models/mongodb.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/networks.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/tablestores.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/waf_ipset_caches.go
  pkg/compute/models/waf_regexset_caches.go
  pkg/compute/options/namesync.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/L, area/region

#15741 Automated cherry pick of #15740: fix(region): unified name sync options
  pkg/compute/models/cachedimages.go
  pkg/compute/models/cdn_domains.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/elastic_search.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/filesystem.go
  pkg/compute/models/guests.go
  pkg/compute/models/inter_vpc_network.go
  pkg/compute/models/ipv6_gateways.go
  pkg/compute/models/kafka.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/modelarts_pools.go
  pkg/compute/models/mongodb.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/networks.go
  pkg/compute/models/secgroupcache.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/tablestores.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/waf_ipset_caches.go
  pkg/compute/models/waf_regexset_caches.go
  pkg/compute/options/namesync.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/L

#15799 fix(notify): 对服务异常添加消息通知
  build/notify/root/opt/yunion/share/local-templates/content@cn/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/SERVICE_ABNORMAL.tmpl
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudid/service/service.go
  pkg/cloudmon/service/service.go
  pkg/cloudnet/service/service.go
  pkg/cloudproxy/service/service.go
  pkg/cloutpost/service/service.go
  pkg/compute/service/service.go
  pkg/keystone/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/vpcagent/service/service.go
  pkg/yunionconf/service/service.go
Labels: size/L

#15808 Automated cherry pick of #15799: fix(notify): 对服务异常添加消息通知
  build/notify/root/opt/yunion/share/local-templates/content@cn/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/SERVICE_ABNORMAL.tmpl
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudid/service/service.go
  pkg/cloudmon/service/service.go
  pkg/cloudnet/service/service.go
  pkg/cloudproxy/service/service.go
  pkg/cloutpost/service/service.go
  pkg/compute/service/service.go
  pkg/keystone/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/vpcagent/service/service.go
  pkg/yunionconf/service/service.go
Labels: size/L

#15809 Automated cherry pick of #15799: fix(notify): 对服务异常添加消息通知
  build/notify/root/opt/yunion/share/local-templates/content@cn/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SERVICE_ABNORMAL.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/SERVICE_ABNORMAL.tmpl
  pkg/apis/notify/const.go
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudid/service/service.go
  pkg/cloudmon/service/service.go
  pkg/cloudnet/service/service.go
  pkg/cloudproxy/service/service.go
  pkg/cloutpost/service/service.go
  pkg/compute/service/service.go
  pkg/keystone/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/yunionconf/service/service.go
Labels: size/L

#15770 fix(notify): 对所有通知默认加入系统管理员接收人
  pkg/notify/models/initdb.go
  pkg/notify/models/subscriber.go
Labels: size/M

#15777 Automated cherry pick of #15770: fix(notify): 对所有通知默认加入系统管理员接收人
  pkg/notify/models/initdb.go
  pkg/notify/models/subscriber.go
Labels: size/M

#15810 fix(region): rescue mode data is nil
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: size/S

#15805 fix(region): vmware migrate vnc
  pkg/compute/guestdrivers/esxi.go
Labels: size/S, area/region

#15806 Automated cherry pick of #15805: fix(region): vmware migrate vnc
  pkg/compute/guestdrivers/esxi.go
Labels: size/S

#15807 Automated cherry pick of #15805: fix(region): vmware migrate vnc
  pkg/compute/guestdrivers/esxi.go
Labels: size/S

#15797 fix: notify sync receivers from keystone
  pkg/notify/models/receiver.go
  pkg/notify/options/options.go
  pkg/notify/service/service.go
Labels: size/L

#15798 Automated cherry pick of #15797: fix: notify sync receivers from keystone
  pkg/notify/models/receiver.go
  pkg/notify/options/options.go
  pkg/notify/service/service.go
Labels: size/L

#15811 fix(keystone): serviceAbnormal token fix
  pkg/keystone/service/service.go
Labels: lgtm, size/XS

#15814 Automated cherry pick of #15811: fix(keystone): serviceAbnormal token fix
  pkg/keystone/service/service.go
Labels: size/XS

#15817 Automated cherry pick of #15816: fix(notify): fix topic enable bug
  pkg/notify/models/topic.go
Labels: size/S

#15816 fix(notify): fix topic enable bug
  pkg/notify/models/topic.go
Labels: size/S

#15800 fix(mcclient): 避免休眠后再次启动后admin token失效, 导致用户登录失败
  pkg/mcclient/auth/auth.go
Labels: size/XS, area/apigateway

#15802 Automated cherry pick of #15800: fix(mcclient): 避免休眠后再次启动后admin token失效, 导致用户登录失败
  pkg/mcclient/auth/auth.go
Labels: size/XS

#15828 Automated cherry pick of #15826: fix(notify): add server_panic topic
  build/notify/root/opt/yunion/share/local-templates/content@cn/SERVER_PANICKED_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/SERVER_PANICKED_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/SERVER_PANICKED_FAILED.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/SERVER_PANICKED_FAILED.tmpl
  pkg/apis/notify/event.go
  pkg/cloudcommon/notifyclient/events.go
  pkg/compute/models/guest_actions.go
  pkg/notify/models/notification.go
  pkg/notify/models/robot.go
  pkg/notify/models/topic.go
Labels: size/M

#15822 fix: clean pending usage when dry run validate_create_data
  pkg/cloudcommon/db/db_dispatcher.go
Labels: lgtm, size/S

#15819 feat(climc): add action of k8s-cluster-deploy
  pkg/mcclient/options/k8s/cluster.go
Labels: size/XS, area/climc

#15821 Automated cherry pick of #15819: feat(climc): add action of k8s-cluster-deploy
  pkg/mcclient/options/k8s/cluster.go
Labels: size/XS

#15830 fix: parameter get or create rpc
  pkg/apigateway/handler/rpc.go
  pkg/mcclient/modules/yunionconf/mod_parameters.go
Labels: lgtm

#15832 fix: prepare esxi host network revisit
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccount_vmware.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/networks.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/util/logclient/consts_i18n.go
Labels: size/XXL

#15833 Automated cherry pick of #15832: fix: prepare esxi host network revisit
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccount_vmware.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/networks.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/compute/tasks/cloud_account_sync_vmware_net.go
  pkg/util/logclient/consts_i18n.go
Labels: size/XXL

#15834 fix: webconsole ssh user/pass prompt backspace hanlding
  pkg/webconsole/command/ssh_command.go
Labels: size/S, area/webconsole

#15836 Automated cherry pick of #15834: fix: webconsole ssh user/pass prompt backspace hanlding
  pkg/webconsole/command/ssh_command.go
Labels: size/S

#15835 Automated cherry pick of #15834: fix: webconsole ssh user/pass prompt backspace hanlding
  pkg/webconsole/command/ssh_command.go
Labels: size/S

#15837 fix: disable metadata server monitor for SR-IOV
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guests.go
Labels: size/S

#15838 Automated cherry pick of #15837: fix: disable metadata server monitor for SR-IOV
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guests.go
Labels: size/S

#15840 fix(host): host metrics convert bytes to bits after diffed
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/L

#15846 Automated cherry pick of #15840: fix(host): host metrics convert bytes to bits after diffed
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/L

#15842 fix(region): clirc with region
  go.mod
  go.sum
  pkg/compute/models/cloudproviders.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
Labels: size/M, area/region

#15843 Automated cherry pick of #15842: fix(region): clirc with region
  go.mod
  go.sum
  pkg/compute/models/cloudproviders.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
Labels: size/M

#15844 fix: cloudmon/lbagent api request with app name
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/options/options.go
  pkg/cloudmon/resources/resources.go
  pkg/lbagent/service.go
Labels: size/L

#15845 Automated cherry pick of #15844: fix: cloudmon/lbagent api request with app name
  pkg/cloudcommon/consts/consts.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/options/options.go
  pkg/cloudmon/resources/resources.go
  pkg/lbagent/service.go
Labels: size/L

#15847 fix(region): azure resource project id
  pkg/multicloud/azure/azure.go
Labels: size/XS, area/region

#15848 fix(region): vm created with public ip
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS, area/region

#15850 Automated cherry pick of #15848: fix(region): vm created with public ip
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#15855 fix(region): codegen
  pkg/apis/compute/loadbalanceracl.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
Labels: size/L, area/region

#15856 Automated cherry pick of #15855: fix(region): codegen
  pkg/apis/compute/loadbalanceracl.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
Labels: size/L

#15853 fix(host): panic on report diskio
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#15854 Automated cherry pick of #15853: fix(host): panic on report diskio
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#15857 fix(codegen): update apis generated by models
  pkg/apis/compute/zz_generated.model.go
Labels: size/S, area/util

#15858 Automated cherry pick of #15857: fix(codegen): update apis generated by models
  pkg/apis/compute/zz_generated.model.go
Labels: size/S

#15851 fix(cloudevent): default disable cloudevent sync
  pkg/cloudevent/options/options.go
Labels: size/XS, area/cloudevent

#15852 Automated cherry pick of #15851: fix(cloudevent): default disable cloudevent sync
  pkg/cloudevent/options/options.go
Labels: size/XS

#15859 feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/S

#15860 Automated cherry pick of #15859: feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/S

#15861 Automated cherry pick of #15859: feat(build,test): 新增 dry_run 模式以便夜间测试
  scripts/docker_push.sh
Labels: size/S

#15865 fix: vmemsize error prompt
  pkg/compute/models/guest_actions.go
Labels: size/XS

#15867 Automated cherry pick of #15865: fix: vmemsize error prompt
  pkg/compute/models/guest_actions.go
Labels: size/XS

#15866 Automated cherry pick of #15865: fix: vmemsize error prompt
  pkg/compute/models/guest_actions.go
Labels: size/XS
