Repository yunionio/cloudpods, pull requests merged in 2023-02, with the labels that each got.

#15879 fix(region): lb listener
  go.mod
  go.sum
  pkg/apis/compute/loadbalancerlistener.go
  pkg/compute/models/loadbalancercachedacls.go
  pkg/compute/models/loadbalancercachedcertificates.go
  pkg/compute/models/loadbalancerlisteners.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/huawei.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/regiondrivers/openstack.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/tasks/loadbalancer_listener_sync_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/fakeregion.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalanceracl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerhttplistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerhttpslistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancertcplistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerudplistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/loadbalancerhttplistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/loadbalancerhttpslistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/loadbalancertcplistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/loadbalancerudplistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/fakeregion.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/no_lb_region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
Labels: size/XXL, area/region

#15881 fix(cloudmon): project tags for metric
  pkg/apis/compute/guests.go
  pkg/cloudmon/resources/resources.go
  pkg/util/influxdb/metrics.go
Labels: size/M, area/cloudmon

#15883 Automated cherry pick of #15881: fix(cloudmon): project tags for metric
  pkg/apis/compute/guests.go
  pkg/cloudmon/resources/resources.go
  pkg/util/influxdb/metrics.go
Labels: size/M

#15885 fix(region): dns recordset details
  pkg/apis/compute/dnsrecordsets.go
  pkg/compute/models/dns_recordsets.go
Labels: size/XS, area/region

#15887 Automated cherry pick of #15885: fix(region): dns recordset details
  pkg/apis/compute/dnsrecordsets.go
  pkg/compute/models/dns_recordsets.go
Labels: size/XS

#15896 fix(region): fake server generate
  pkg/apis/compute/api.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M, area/region

#15897 Automated cherry pick of #15896: fix(region): fake server generate
  pkg/apis/compute/api.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#15898 Automated cherry pick of #15896: fix(region): fake server generate
  pkg/apis/compute/api.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#15899 fix(host-metrics): bytes sent overflow
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/S

#15900 Automated cherry pick of #15899: fix(host-metrics): bytes sent overflow
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/S

#15901 fix: update OWNERS 20230205
  OWNERS
Labels: size/XS

#15902 fix(region): cdn domain config
  go.mod
  go.sum
  pkg/compute/models/cdn_domains.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/bingo.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_type.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/node.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/utils.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cdn_domain_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cdn.go
Labels: size/XXL, area/region

#15903 Automated cherry pick of #15902: fix(region): cdn domain config
  go.mod
  go.sum
  pkg/compute/models/cdn_domains.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/bingo.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_type.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/node.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/utils.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cdn_domain_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cdn.go
Labels: size/XXL

#15904 Automated cherry pick of #15902: fix(region): cdn domain config
  pkg/cloudprovider/cdn.go
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cdn_domains.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/cluster.go
  pkg/multicloud/bingocloud/disk.go
  pkg/multicloud/bingocloud/eip.go
  pkg/multicloud/bingocloud/host.go
  pkg/multicloud/bingocloud/image.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/bingocloud/instancenic.go
  pkg/multicloud/bingocloud/monitor.go
  pkg/multicloud/bingocloud/network.go
  pkg/multicloud/bingocloud/node.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/bingocloud/secgroup.go
  pkg/multicloud/bingocloud/storage.go
  pkg/multicloud/bingocloud/vpc.go
  pkg/multicloud/bingocloud/wire.go
  pkg/multicloud/bingocloud/zone.go
  pkg/multicloud/cdn_domain_base.go
  pkg/multicloud/qcloud/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_type.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/utils.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cdn_domain_base.go
Labels: size/XXL

#15905 Automated cherry pick of #15902: fix(region): cdn domain config
  pkg/cloudprovider/cdn.go
  pkg/cloudprovider/resources.go
  pkg/cloudprovider/securitygroup.go
  pkg/compute/models/cdn_domains.go
  pkg/multicloud/aliyun/cdn.go
  pkg/multicloud/cdn_domain_base.go
  pkg/multicloud/qcloud/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cdn_domain_base.go
Labels: size/XL

#15907 fix: lbagent containerize issues
  build/docker/Dockerfile.lbagent
  build/docker/Dockerfile.lbagent-base
  pkg/compute/models/loadbalanceragents.go
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
  pkg/lbagent/api.go
  pkg/lbagent/haproxy.go
  pkg/lbagent/options.go
  pkg/lbagent/service.go
Labels: size/L

#15908 Automated cherry pick of #15907: fix: lbagent containerize issues
  build/docker/Dockerfile.lbagent
  build/docker/Dockerfile.lbagent-base
  pkg/compute/models/loadbalanceragents.go
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
  pkg/lbagent/api.go
  pkg/lbagent/haproxy.go
  pkg/lbagent/options.go
  pkg/lbagent/service.go
Labels: size/L

#15909 fix(region): update kube cluster to kubeserver
  pkg/compute/models/kube_clusters.go
Labels: size/S, area/region

#15911 Automated cherry pick of #15909: fix(region): update kube cluster to kubeserver
  pkg/compute/models/kube_clusters.go
Labels: size/S

#15912 Automated cherry pick of #15909: fix(region): update kube cluster to kubeserver
  pkg/compute/models/kube_clusters.go
Labels: size/S

#15913 fix: tablespec add sync method
  go.mod
  go.sum
  pkg/cloudcommon/db/tablespec.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/S

#15914 Automated cherry pick of #15913: fix: tablespec add sync method
  go.mod
  go.sum
  pkg/cloudcommon/db/tablespec.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/S

#15917 fix: add test for FilePutContent
  pkg/util/fileutils2/fileutils_test.go
Labels: size/M

#15920 feature: project admin user
  pkg/apis/identity/project.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/projects.go
  pkg/keystone/options/options.go
Labels: size/L, area/keystone

#15921 Automated cherry pick of #15920: feature: project admin user
  pkg/apis/identity/project.go
  pkg/keystone/models/assignments.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/projects.go
  pkg/keystone/options/options.go
Labels: size/L

#15922 fix(region): change cdn to virtual resource
  go.mod
  go.sum
  pkg/apis/compute/cdn.go
  pkg/compute/models/cdn_domains.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cdn.go
Labels: size/M, area/region

#15923 Automated cherry pick of #15922: fix(region): change cdn to virtual resource
  go.mod
  go.sum
  pkg/apis/compute/cdn.go
  pkg/compute/models/cdn_domains.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cdn.go
Labels: size/M

#15925 fix(host,baremetal): deploy content action not marshaled
  pkg/baremetal/manager.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/hostdeployer/apis/utils.go
Labels: size/M

#15926 Automated cherry pick of #15925: fix(host,baremetal): deploy content action not marshaled
  pkg/baremetal/manager.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/hostdeployer/apis/utils.go
Labels: size/M

#15927 Automated cherry pick of #15925: fix(host,baremetal): deploy content action not marshaled
  pkg/baremetal/manager.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/hostdeployer/apis/utils.go
Labels: size/M

#15928 fix(build): lbagent-base image
  build/docker/Dockerfile.lbagent
  build/docker/Dockerfile.lbagent-base
  build/docker/Makefile
Labels: size/S

#15929 Automated cherry pick of #15928: fix(build): lbagent-base image
  build/docker/Dockerfile.lbagent
  build/docker/Dockerfile.lbagent-base
  build/docker/Makefile
Labels: size/S

#15930 fix(region): start LoadBalancerBackendSyncTask when needed
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/loadbalancerbackends.go
Labels: size/S, area/region

#15932 Automated cherry pick of #15930: fix(region): start LoadBalancerBackendSyncTask when needed
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/loadbalancerbackends.go
Labels: size/S

#15936 fix(baremetal): duplicate argument task-worker-count
  pkg/baremetal/options/options.go
  pkg/baremetal/tasks/worker.go
Labels: size/M, area/baremetal

#15937 Automated cherry pick of #15936: fix(baremetal): duplicate argument task-worker-count
  pkg/baremetal/options/options.go
  pkg/baremetal/tasks/worker.go
Labels: size/M

#15938 Automated cherry pick of #15936: fix(baremetal): duplicate argument task-worker-count
  pkg/baremetal/options/options.go
  pkg/baremetal/tasks/worker.go
Labels: size/M

#15939 fix(cloudmon): huawei read only check
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
Labels: size/S, area/cloudmon

#15940 Automated cherry pick of #15939: fix(cloudmon): huawei read only check
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
Labels: size/S

#15941 Automated cherry pick of #15939: fix(cloudmon): huawei read only check
  pkg/multicloud/huawei/huawei.go
Labels: size/XS

#15942 fix(region): aws s3 upload failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
Labels: size/S

#15943 Automated cherry pick of #15942: fix(region): aws s3 upload failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
Labels: size/S

#15944 Automated cherry pick of #15942: fix(region): aws s3 upload failed
  pkg/multicloud/aws/aws.go
  pkg/multicloud/huawei/huawei.go
Labels: size/XS

#15948 fix(host-deployer): revert linux efi check
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#15934 Automated cherry pick of #15933: fix: usage filter by policy tags revisit2
  pkg/compute/usages/handler.go
  pkg/util/rbacutils/results.go
  pkg/util/tagutils/tag_test.go
  pkg/util/tagutils/tagset.go
  pkg/util/tagutils/tagset_test.go
  pkg/util/tagutils/tagsetlist.go
  pkg/util/tagutils/tagsetlist_test.go
Labels: size/L

#15962 fix(region): guest change disk storage
  pkg/compute/models/guestdisks.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/XS

#15963 Automated cherry pick of #15962: fix(region): guest change disk storage
  pkg/compute/models/guestdisks.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/XS

#15964 Automated cherry pick of #15962: fix(region): guest change disk storage
  pkg/compute/models/guestdisks.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/XS

#15958 fix(region): kvm convert to esxi
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestman/esxi.go
  pkg/hostman/guestman/libvirt.go
Labels: size/S

#15959 Automated cherry pick of #15958: fix(region): kvm convert to esxi
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestman/esxi.go
  pkg/hostman/guestman/libvirt.go
Labels: size/S

#15960 Automated cherry pick of #15958: fix(region): kvm convert to esxi
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: size/S

#15966 feat(mcclient): allow set default authenticate source
  pkg/mcclient/auth/auth.go
Labels: size/S, area/util, area/common

#15967 Automated cherry pick of #15966: feat(mcclient): allow set default authenticate source
  pkg/mcclient/auth/auth.go
Labels: size/S

#15968 Automated cherry pick of #15966: feat(mcclient): allow set default authenticate source
  pkg/mcclient/auth/auth.go
Labels: size/S

#15970 fix(region): gcp image sync
  go.mod
  go.sum
  pkg/compute/models/cloudimages.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storagecache.go
Labels: size/S, area/region

#15971 Automated cherry pick of #15970: fix(region): gcp image sync
  go.mod
  go.sum
  pkg/compute/models/cloudimages.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storagecache.go
Labels: size/S

#15961 fix(notify): 添加消息来源
  pkg/notify/tasks/notifications_send_task.go
Labels: lgtm, size/XS

#15969 Automated cherry pick of #15961: fix(notify): 添加消息来源
  pkg/notify/tasks/notifications_send_task.go
Labels: size/XS

#15952 fix(baremetal): only do status probe job when host_type is hypervisor
  pkg/baremetal/manager.go
Labels: size/XS, area/baremetal

#15953 Automated cherry pick of #15952: fix(baremetal): only do status probe job when host_type is hypervisor
  pkg/baremetal/manager.go
Labels: size/XS

#15954 Automated cherry pick of #15952: fix(baremetal): only do status probe job when host_type is hypervisor
  pkg/baremetal/manager.go
Labels: size/XS

#15973 feat(monitor): add DisableQuerySignatureCheck option
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/options/options.go
Labels: size/S, area/monitor

#15974 Automated cherry pick of #15973: feat(monitor): add DisableQuerySignatureCheck option
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/options/options.go
Labels: size/S

#15975 Automated cherry pick of #15973: feat(monitor): add DisableQuerySignatureCheck option
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/options/options.go
Labels: size/S

#15972 Automated cherry pick of #15970: fix(region): gcp image sync
  pkg/compute/models/cloudimages.go
  pkg/multicloud/google/storagecache.go
Labels: size/XS

#15976 fix(region): esxi to kvm clean sched desc disk.storage
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: size/XS

#15977 Automated cherry pick of #15976: fix(region): esxi to kvm clean sched desc disk.storage
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: size/XS

#15978 Automated cherry pick of #15976: fix(region): esxi to kvm clean sched desc disk.storage
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
Labels: size/XS

#15915 feat(region,host): support ovs offload.
  pkg/apis/compute/isolated_device.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nic.go
  pkg/hostman/options/options.go
Labels: size/L

#15924 Automated cherry pick of #15915: feat(region,host): support ovs offload.
  pkg/apis/compute/isolated_device.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nic.go
  pkg/hostman/options/options.go
Labels: size/L

#15945 fix(region): clean storage db
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
Labels: size/M, area/region

#15946 Automated cherry pick of #15945: fix(region): clean storage db
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
Labels: size/M

#15980 fix(region): vender update for gcp storage
  go.mod
  go.sum
  pkg/compute/models/cloudprovider_quotas.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storage.go
Labels: size/M, area/region

#15982 Automated cherry pick of #15980: fix(region): vender update for gcp storage
  pkg/apis/compute/cloudregions_const.go
  pkg/apis/compute/regiondata.go
  pkg/compute/models/cloudprovider_quotas.go
  pkg/multicloud/google/latitude_and_longitude.go
  pkg/multicloud/google/storage.go
Labels: size/M

#15981 Automated cherry pick of #15980: fix(region): vender update for gcp storage
  go.mod
  go.sum
  pkg/compute/models/cloudprovider_quotas.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storage.go
Labels: size/M

#15918 fix: hostman setup tuned-adm profile virtual-host
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#15989 Automated cherry pick of #15918: fix: hostman setup tuned-adm profile virtual-host
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#15990 Automated cherry pick of #15894: build(deps): bump github.com/Masterminds/goutils from 1.1.0 to 1.1.1
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: size/M

#15992 Automated cherry pick of #15947: build(deps): bump github.com/apache/thrift from 0.12.0 to 0.13.0
  go.mod
  go.sum
  vendor/github.com/apache/thrift/NOTICE
  vendor/github.com/apache/thrift/lib/go/thrift/application_exception.go
  vendor/github.com/apache/thrift/lib/go/thrift/binary_protocol.go
  vendor/github.com/apache/thrift/lib/go/thrift/client.go
  vendor/github.com/apache/thrift/lib/go/thrift/framed_transport.go
  vendor/github.com/apache/thrift/lib/go/thrift/header_context.go
  vendor/github.com/apache/thrift/lib/go/thrift/header_protocol.go
  vendor/github.com/apache/thrift/lib/go/thrift/header_transport.go
  vendor/github.com/apache/thrift/lib/go/thrift/json_protocol.go
  vendor/github.com/apache/thrift/lib/go/thrift/pointerize.go
  vendor/github.com/apache/thrift/lib/go/thrift/protocol.go
  vendor/github.com/apache/thrift/lib/go/thrift/simple_json_protocol.go
  vendor/github.com/apache/thrift/lib/go/thrift/simple_server.go
  vendor/github.com/apache/thrift/lib/go/thrift/socket.go
  vendor/modules.txt
Labels: size/XXL

#15985 fix: 1. allow remove current user from current project. 2. reset recovery-questions when resetting MFA
  pkg/keystone/models/assignments.go
  pkg/keystone/models/users.go
Labels: size/S

#15986 Automated cherry pick of #15985: fix: 1. allow remove current user from current project. 2. reset recovery-questions when resetting MFA
  pkg/keystone/models/assignments.go
  pkg/keystone/models/users.go
Labels: size/S

#15987 Automated cherry pick of #15985: fix: 1. allow remove current user from current project. 2. reset recovery-questions when resetting MFA
  pkg/keystone/models/assignments.go
  pkg/keystone/models/users.go
Labels: size/S

#15997 Automated cherry pick of #15995: fix: sms login not verify captchar
  pkg/apigateway/handler/auth.go
Labels: size/XS

#15995 fix: sms login not verify captchar
  pkg/apigateway/handler/auth.go
Labels: size/XS

#15996 Automated cherry pick of #15995: fix: sms login not verify captchar
  pkg/apigateway/handler/auth.go
Labels: size/XS

#16003 fix(region): esxi to kvm nic driver fix
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#16004 Automated cherry pick of #16003: fix(region): esxi to kvm nic driver fix
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#16005 Automated cherry pick of #16003: fix(region): esxi to kvm nic driver fix
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/XS

#16006 fix(cloudmon): apsara monitor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/monitor.go
Labels: size/M, area/cloudmon

#16007 Automated cherry pick of #16006: fix(cloudmon): apsara monitor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/monitor.go
Labels: size/M

#16008 Automated cherry pick of #16006: fix(cloudmon): apsara monitor
  pkg/multicloud/apsara/apsara.go
  pkg/multicloud/apsara/monitor.go
Labels: size/M

#16009 fix(esxi-agent): disk temp files recycle
  pkg/esxi/agent.go
Labels: size/XS

#16010 Automated cherry pick of #16009: fix(esxi-agent): disk temp files recycle
  pkg/esxi/agent.go
Labels: size/XS

#16011 Automated cherry pick of #16009: fix(esxi-agent): disk temp files recycle
  pkg/esxi/agent.go
Labels: size/XS

#16012 fix: gen policy extra override policy
  pkg/keystone/locale/genpolicy.go
Labels: size/S

#16013 Automated cherry pick of #16012: fix: gen policy extra override policy
  pkg/keystone/locale/genpolicy.go
Labels: size/S

#16014 Automated cherry pick of #16012: fix: gen policy extra override policy
  pkg/keystone/locale/genpolicy.go
Labels: size/S

#16016 fix(baremetal): update baremetal base image to support ice module
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
Labels: size/XS, area/baremetal

#16018 Automated cherry pick of #16016: fix(baremetal): update baremetal base image to support ice module
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
Labels: size/XS

#16025 fix(region): aliyun lb tag sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancer.go
Labels: size/S, area/region

#16026 Automated cherry pick of #16025: fix(region): aliyun lb tag sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancer.go
Labels: size/S

#16020 feature: add webhook example server scripts
  scripts/webhook.py
Labels: size/M

#16028 fix: ovn options missing eip and brmapped
  pkg/hostman/options/options.go
  pkg/util/ovnutils/options.go
Labels: size/XS

#16029 Automated cherry pick of #16028: fix: ovn options missing eip and brmapped
  pkg/hostman/options/options.go
  pkg/util/ovnutils/options.go
Labels: size/XS

#15839 Feature/implement bingocloud
  pkg/compute/guestdrivers/bingocloud.go
  pkg/compute/regiondrivers/bingocloud.go
Labels: lgtm, size/M

#15993 Automated cherry pick of #15839: Feature/implement bingocloud
  pkg/compute/guestdrivers/bingocloud.go
  pkg/compute/regiondrivers/bingocloud.go
Labels: size/M

#16042 fix: set eipid after successful eip association
  pkg/compute/models/groups.go
  pkg/compute/models/guest_sshable.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/S

#16043 Automated cherry pick of #16042: fix: set eipid after successful eip association
  pkg/compute/models/groups.go
  pkg/compute/models/guest_sshable.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/S

#16044 Automated cherry pick of #16042: fix: set eipid after successful eip association
  pkg/compute/models/groups.go
  pkg/compute/models/guest_sshable.go
  pkg/compute/regiondrivers/kvm.go
Labels: size/S

#16039 fix: apihelper sync ignore instancegroups without guets
  pkg/vpcagent/models/modelset.go
Labels: size/S

#16040 Automated cherry pick of #16039: fix: apihelper sync ignore instancegroups without guets
  pkg/vpcagent/models/modelset.go
Labels: size/S

#16041 Automated cherry pick of #16039: fix: apihelper sync ignore instancegroups without guets
  pkg/vpcagent/models/modelset.go
Labels: size/S

#16055 fix(host): resume suspend guest
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#16056 Automated cherry pick of #16055: fix(host): resume suspend guest
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#16057 Automated cherry pick of #16055: fix(host): resume suspend guest
  pkg/hostman/guestman/guesttasks.go
Labels: size/M

#16053 Automated cherry pick of #16052: fix: monitor delete resource panic
  pkg/monitor/models/monitor_resource.go
Labels: size/XS

#16046 fix(climc): add list monitorresource cmd
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S, area/monitor

#16047 Automated cherry pick of #16046: fix(climc): add list monitorresource cmd
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S

#16048 Automated cherry pick of #16046: fix(climc): add list monitorresource cmd
  cmd/climc/shell/monitor/monitor_resource.go
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S

#16049 fix(region): azure rebuild root error
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/instance.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: size/M, area/region

#16051 Automated cherry pick of #16049: fix(region): azure rebuild root error
  go.mod
  go.sum
  pkg/multicloud/azure/instance.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/query.go
Labels: size/M

#16059 fix(notify):fix topic of ChecksumTestFailed Result
  pkg/notify/models/topic.go
Labels: size/XS

#16060 Automated cherry pick of #16059: fix(notify):fix topic of ChecksumTestFailed Result
  pkg/notify/models/topic.go
Labels: size/XS

#16061 Automated cherry pick of #16059: fix(notify):fix topic of ChecksumTestFailed Result
  pkg/notify/models/topic.go
Labels: size/XS

#16069 fix(region): guest change storage
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#16070 Automated cherry pick of #16069: fix(region): guest change storage
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#16071 Automated cherry pick of #16069: fix(region): guest change storage
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#16063 feat(region): vga gpus
  pkg/compute/models/capabilities.go
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
Labels: size/M

#16065 Automated cherry pick of #16063: feat(region): vga gpus
  pkg/compute/models/capabilities.go
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
Labels: size/M

#16066 fix(region): vmware template image size
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/template.go
Labels: size/S, area/region

#16067 Automated cherry pick of #16066: fix(region): vmware template image size
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/template.go
Labels: size/S

#16068 Automated cherry pick of #16066: fix(region): vmware template image size
  pkg/multicloud/esxi/template.go
Labels: size/XS

#16072 fix(monitor): query resources according by listing region resources
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/L, area/monitor

#16074 Automated cherry pick of #16072: fix(monitor): query resources according by listing region resources
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/L

#16073 Automated cherry pick of #16072: fix(monitor): query resources according by listing region resources
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/L
