Repository yunionio/cloudpods, pull requests merged in 2023-06, with the labels that each got.

#17225 fix(apigateway): add handler for user to get self topic subscriptions
  pkg/apigateway/handler/auth.go
Labels: lgtm, size/S

#17222 feat(climc): add service option for action-show command
  cmd/climc/shell/logger/actions.go
Labels: size/XS, area/climc

#17223 Automated cherry pick of #17222: feat(climc): add service option for action-show command
  cmd/climc/shell/logger/actions.go
Labels: size/XS

#17202 fix: allow LDAP sync extra tags
  cmd/climc/shell/identity/users.go
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/ldap/sync.go
  pkg/mcclient/options/identity/users.go
Labels: size/L

#17203 Automated cherry pick of #17202: fix: allow LDAP sync extra tags
  cmd/climc/shell/identity/users.go
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/ldap/sync.go
  pkg/mcclient/options/identity/users.go
Labels: size/L

#17206 Automated cherry pick of #17205: fix(host): nics get sys conf quiet
  pkg/util/sysutils/kvm.go
  pkg/util/sysutils/nics.go
Labels: size/S

#17231 fix(region): support aliyun k8s op
  go.mod
  go.sum
  pkg/compute/regiondrivers/managedvirtual.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_node.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_node_pools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
Labels: size/L, area/region

#17240 fix(host): don't sync status on resume from postmigrate
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
Labels: size/S

#17241 Automated cherry pick of #17240: fix(host): don't sync status on resume from postmigrate
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
Labels: size/S

#17242 Automated cherry pick of #17240: fix(host): don't sync status on resume from postmigrate
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
Labels: size/S

#17229 fix(webconsole): ssh exit
  pkg/webconsole/server/ssh_server.go
Labels: size/M, area/webconsole

#17183 fix(region): snapshot policy create and update
  pkg/apis/compute/snapshot.go
  pkg/apis/compute/snapshotpolicy.go
  pkg/compute/models/snapshotpolicy.go
Labels: size/L, area/region

#17329 fix(region): listitemfilter ignore empty slice
  pkg/cloudcommon/db/archs.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcresource.go
Labels: size/S

#17330 Automated cherry pick of #17329: fix(region): listitemfilter ignore empty slice
  pkg/cloudcommon/db/archs.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcresource.go
Labels: size/S

#17326 fix(baremetal): panic occured when fetch powerMetrics
  pkg/baremetal/cronjobs.go
  pkg/baremetal/manager.go
Labels: size/S, area/baremetal

#17327 Automated cherry pick of #17326: fix(baremetal): panic occured when fetch powerMetrics
  pkg/baremetal/cronjobs.go
  pkg/baremetal/manager.go
Labels: size/S

#17328 Automated cherry pick of #17326: fix(baremetal): panic occured when fetch powerMetrics
  pkg/baremetal/cronjobs.go
  pkg/baremetal/manager.go
Labels: size/S

#17323 fix(host-deployer): ubuntu like uos detect
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#17324 Automated cherry pick of #17323: fix(host-deployer): ubuntu like uos detect
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#17340 fix: detailed pending usage error
  pkg/compute/tasks/pending_usage.go
Labels: size/XS

#17341 Automated cherry pick of #17340: fix: detailed pending usage error
  pkg/compute/tasks/pending_usage.go
Labels: size/XS

#17342 Automated cherry pick of #17340: fix: detailed pending usage error
  pkg/compute/tasks/pending_usage.go
Labels: size/XS

#17339 fix: project organization details
  cmd/climc/shell/identity/organizations.go
  pkg/apis/identity/organization.go
  pkg/apis/identity/project.go
  pkg/cloudcommon/db/cache.go
  pkg/keystone/models/organizations.go
  pkg/keystone/models/projects.go
  pkg/keystone/tasks/organization_sync_task.go
  pkg/mcclient/modules/identity/mod_organizations.go
Labels: size/L

#17338 Automated cherry pick of #17337: fix(region): remove capabilites debug query
  pkg/compute/models/capabilities.go
Labels: size/XS

#17337 fix(region): remove capabilites debug query
  pkg/compute/models/capabilities.go
Labels: size/XS

#17332 fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/S, area/region

#17333 Automated cherry pick of #17332: fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/S

#17349 fix(region): cloudaccount filter
  pkg/compute/models/cloudaccounts.go
Labels: size/XS, area/region

#17350 Automated cherry pick of #17349: fix(region): cloudaccount filter
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#17345 fix: add process timeout option default_process_timeout_seconds
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#17346 Automated cherry pick of #17345: fix: add process timeout option default_process_timeout_seconds
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#17347 Automated cherry pick of #17345: fix: add process timeout option default_process_timeout_seconds
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#17351 fix(notify): add topic_type for get subscription
  pkg/notify/models/receiver.go
Labels: size/XS

#17354 fix: force no paging limit for list
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS

#17355 Automated cherry pick of #17354: fix: force no paging limit for list
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS

#17356 fix: organization node no details
  pkg/keystone/models/organization_nodes.go
Labels: size/XS

#17357 fix: delete organization alse delete cache
  cmd/climc/shell/identity/organizations.go
  pkg/cloudcommon/db/cache.go
  pkg/keystone/models/organizations.go
Labels: size/M

#17358 fix: more organization cmds
  cmd/climc/shell/identity/organization_nodes.go
  cmd/climc/shell/identity/organizations.go
  pkg/mcclient/options/identity/organization.go
  pkg/mcclient/options/identity/organization_nodes.go
Labels: size/M

#17364 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_cluster.go
Labels: size/S, area/region

#17366 fix(region): avoid aliyun elastic cache cycle sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/elasticcache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/utils.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/elasticcache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/utils.go
Labels: size/L, area/region

#17367 Automated cherry pick of #17366: fix(region): avoid aliyun elastic cache cycle sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/elasticcache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/utils.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/elasticcache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/utils.go
Labels: size/L

#17368 Automated cherry pick of #17366: fix(region): avoid aliyun elastic cache cycle sync
  pkg/multicloud/aliyun/elasticcache_instance.go
  pkg/multicloud/aliyun/utils.go
  pkg/multicloud/apsara/elasticcache_instance.go
  pkg/multicloud/apsara/utils.go
Labels: size/L

#17370 fix(region): sync zstack vm ip
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/instancenic.go
Labels: size/S, area/region

#17371 Automated cherry pick of #17370: fix(region): sync zstack vm ip
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/instancenic.go
Labels: size/S

#17372 Automated cherry pick of #17370: fix(region): sync zstack vm ip
  pkg/multicloud/zstack/instancenic.go
Labels: size/XS

#17373 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_node_pools.go
Labels: size/S, area/region

#17374 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_cluster.go
Labels: size/S

#17377 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/snapshot.go
Labels: size/S, area/region

#17378 Automated cherry pick of #17377: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/snapshot.go
Labels: size/S

#17379 Automated cherry pick of #17377: fix(region): vendor update
  pkg/multicloud/openstack/snapshot.go
Labels: size/S

#17361 fix(notify): add getSubscriberFunc more details
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
Labels: size/M

#17369 Automated cherry pick of #17361: fix(notify): add getSubscriberFunc more details
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
Labels: size/M

#17386 fix(host): add some logs for dhcp relay
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/XS, area/host

#17387 Automated cherry pick of #17386: fix(host): add some logs for dhcp relay
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/XS

#17401 fix: bucket short descption
  pkg/compute/models/buckets.go
Labels: size/XS

#17402 Automated cherry pick of #17401: fix: bucket short descption
  pkg/compute/models/buckets.go
Labels: size/XS

#17404 fix(region): cached image info sync
  pkg/compute/models/cloudimages.go
Labels: size/M, area/region

#17405 Automated cherry pick of #17404: fix(region): cached image info sync
  pkg/compute/models/cloudimages.go
Labels: size/M

#17406 fix(image): optimized iso format check
  pkg/util/fileutils2/fileutils.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/S, area/image

#17407 Automated cherry pick of #17406: fix(image): optimized iso format check
  pkg/util/fileutils2/fileutils.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/S

#17410 fix(region): pve create
  go.mod
  go.sum
  pkg/apis/webconsole/consts.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/hostdrivers/baremetal.go
  pkg/compute/hostdrivers/esxi.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/proxmox.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guestcdrom.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/compute/tasks/storage_cache_image_task.go
  pkg/mcclient/options/compute/servers.go
  pkg/webconsole/handlers.go
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/proxmox.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/storagecache.go
Labels: size/XXL, area/region

#17411 Automated cherry pick of #17410: fix(region): pve create
  go.mod
  go.sum
  pkg/apis/webconsole/consts.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/hostdrivers/baremetal.go
  pkg/compute/hostdrivers/esxi.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/proxmox.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guestcdrom.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/compute/tasks/storage_cache_image_task.go
  pkg/mcclient/options/compute/servers.go
  pkg/webconsole/handlers.go
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/proxmox.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/storagecache.go
Labels: size/XXL

#17420 fix(vpcagent): fetch data from region server defaultly
  pkg/vpcagent/options/options.go
Labels: size/XS, area/vpcagent

#17421 Automated cherry pick of #17420: fix(vpcagent): fetch data from region server defaultly
  pkg/vpcagent/options/options.go
Labels: size/XS

#17416 fix(host): log storage offline reason
  pkg/compute/models/storages.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/util/cephutils/ceph.go
Labels: size/S, area/host

#17417 Automated cherry pick of #17416: fix(host): log storage offline reason
  pkg/compute/models/storages.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/util/cephutils/ceph.go
Labels: size/S

#17414 fix(region): vendor update
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/github.com/jaypipes/ghw/pkg/util/util.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: lgtm, area/region, size/XL

#17415 Automated cherry pick of #17414: fix(region): vendor update
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/github.com/jaypipes/ghw/pkg/util/util.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/service.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/XL

#17395 fix(notify): add more details for emailqueue
  pkg/apis/notify/emailqueue.go
  pkg/notify/models/emailqueue.go
Labels: size/XS

#17403 Automated cherry pick of #17395: fix(notify): add more details for emailqueue
  pkg/apis/notify/emailqueue.go
  pkg/notify/models/emailqueue.go
Labels: size/XS

#17425 fix: more event show subcmd
  cmd/climc/shell/events/events.go
Labels: size/S

#17426 Automated cherry pick of #17425: fix: more event show subcmd
  cmd/climc/shell/events/events.go
Labels: size/S

#17384 fix(region): get guestdisks count filter deleted guests
  pkg/compute/models/disks.go
Labels: size/XS

#17385 Automated cherry pick of #17384: fix(region): get guestdisks count filter deleted guests
  pkg/compute/models/disks.go
Labels: size/XS
