Repository yunionio/cloudpods, pull requests merged in 2023-08, with the labels that each got.

#17683 fix(region): vpc purge
  pkg/compute/models/purge.go
Labels: size/XS, area/region

#17684 Automated cherry pick of #17683: fix(region): vpc purge
  pkg/compute/models/purge.go
Labels: size/XS

#17685 fix(cloudmon): cloudaccout update
  pkg/apis/compute/guests.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudmon/resources/resources.go
Labels: size/S, area/cloudmon

#17687 Automated cherry pick of #17685: fix(cloudmon): cloudaccout update
  pkg/apis/compute/guests.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudmon/resources/resources.go
Labels: size/S

#17686 Automated cherry pick of #17685: fix(cloudmon): cloudaccout update
  pkg/apis/compute/guests.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudmon/resources/resources.go
Labels: size/S

#17690 fix(cloudmon): avoid panic
  pkg/cloudmon/resources/resources.go
Labels: size/XS, area/cloudmon

#17692 Automated cherry pick of #17690: fix(cloudmon): avoid panic
  pkg/cloudmon/resources/resources.go
Labels: size/XS

#17691 Automated cherry pick of #17690: fix(cloudmon): avoid panic
  pkg/cloudmon/resources/resources.go
Labels: size/XS

#17693 fix(notify): optimized event query
  pkg/notify/models/event.go
Labels: size/S

#17694 Automated cherry pick of #17693: fix(notify): optimized event query
  pkg/notify/models/event.go
Labels: size/S

#17697 Automated cherry pick of #17695: fix(monitor): fix montior alert startTimeFormat
  pkg/monitor/alerting/eval_context.go
Labels: size/XS

#17695 fix(monitor): fix montior alert startTimeFormat
  pkg/monitor/alerting/eval_context.go
Labels: size/XS

#17696 Automated cherry pick of #17695: fix(monitor): fix montior alert startTimeFormat
  pkg/monitor/alerting/eval_context.go
Labels: size/XS

#17698 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
Labels: size/M, area/region

#17699 Automated cherry pick of #17698: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
Labels: size/M

#17700 feat(climc): k8s-cluster-set-kubeconfig
  cmd/climc/shell/k8s/clusters.go
Labels: size/S, area/climc

#17701 Automated cherry pick of #17700: feat(climc): k8s-cluster-set-kubeconfig
  cmd/climc/shell/k8s/clusters.go
Labels: size/S

#17706 Automated cherry pick of #17705: fix(region): esxi storage info
  pkg/compute/guestdrivers/esxi.go
Labels: size/S

#17711 fix: set vcpu vendor_id based on host cpu vendor_id
  pkg/hostman/guestman/arch/x86.go
Labels: lgtm, size/XS

#17712 Automated cherry pick of #17711: fix: set vcpu vendor_id based on host cpu vendor_id
  pkg/hostman/guestman/arch/x86.go
Labels: size/XS

#17713 fix: set vcpu vendor_id based on host cpu vendor_id for release/3.9
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/S

#17714 fix(monitor): remove cloudaccount_balance unit
  pkg/apis/monitor/metric.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/commonalert.go
Labels: size/S, area/monitor

#17715 Automated cherry pick of #17714: fix(monitor): remove cloudaccount_balance unit
  pkg/apis/monitor/metric.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/commonalert.go
Labels: size/S

#17719 fix(climc): avoid panic
  cmd/climc/promputils/executor.go
Labels: size/XS, area/climc

#17721 Automated cherry pick of #17719: fix(climc): avoid panic
  cmd/climc/promputils/executor.go
Labels: size/XS

#17717 fix: watermark
  pkg/apis/identity/consts.go
Labels: size/XS, area/keystone

#17726 Automated cherry pick of #17610: fix(notify): addNotifyGroup
  pkg/apis/notify/config.go
  pkg/apis/notify/topic.go
  pkg/notify/models/config.go
  pkg/notify/models/emailqueue.go
  pkg/notify/models/initdb.go
  pkg/notify/models/notification.go
  pkg/notify/models/notification_group.go
  pkg/notify/models/topic.go
  pkg/notify/sender/email.go
  pkg/notify/service/handlers.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/L

#17610 fix(notify): addNotifyGroup
  pkg/apis/notify/config.go
  pkg/apis/notify/topic.go
  pkg/notify/models/config.go
  pkg/notify/models/emailqueue.go
  pkg/notify/models/initdb.go
  pkg/notify/models/notification.go
  pkg/notify/models/notification_group.go
  pkg/notify/models/topic.go
  pkg/notify/sender/email.go
  pkg/notify/service/handlers.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/L

#17727 fix: allow host access_mac nullable
  pkg/compute/models/hosts.go
Labels: size/XS

#17728 Automated cherry pick of #17727: fix: allow host access_mac nullable
  pkg/compute/models/hosts.go
Labels: size/XS

#17729 Automated cherry pick of #17727: fix: allow host access_mac nullable
  pkg/compute/models/hosts.go
Labels: size/XS

#17722 feat(region): support baidu cloud
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/misc/feature.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/baidu.go
  pkg/compute/hostdrivers/baidu.go
  pkg/compute/regiondrivers/baidu.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/baidu/baidu.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/baidu/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/baidu/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/baidu/signer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/latitud_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/latitud_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/loader/loader.go
Labels: size/XXL, area/region

#17731 fix(notify): add option to use template for webhook
  pkg/apis/notify/config.go
  pkg/apis/notify/robot.go
  pkg/mcclient/options/notify/robot.go
  pkg/notify/models/notification.go
  pkg/notify/models/robot.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/L

#17732 Automated cherry pick of #17731: fix(notify): add option to use template for webhook
  pkg/apis/notify/config.go
  pkg/apis/notify/robot.go
  pkg/mcclient/options/notify/robot.go
  pkg/notify/models/notification.go
  pkg/notify/models/robot.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/L

#17740 fix: auto build docker image
  .github/workflows/docker.yml
  .github/workflows/docker_apigateway.yml
  .github/workflows/docker_climc.yml
  .github/workflows/docker_glance.yml
  .github/workflows/docker_host.yml
  .github/workflows/docker_keystone.yml
  .github/workflows/docker_notify.yml
  .github/workflows/docker_region.yml
  .github/workflows/docker_webconsole.yml
Labels: size/XL

#17741 Automated cherry pick of #17740: fix: auto build docker image
  .github/workflows/docker.yml
  .github/workflows/docker_apigateway.yml
  .github/workflows/docker_climc.yml
  .github/workflows/docker_glance.yml
  .github/workflows/docker_host.yml
  .github/workflows/docker_keystone.yml
  .github/workflows/docker_notify.yml
  .github/workflows/docker_region.yml
  .github/workflows/docker_webconsole.yml
Labels: size/XL

#17742 feat(region): support china union cloud
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/misc/feature.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/cucloud.go
  pkg/compute/hostdrivers/cucloud.go
  pkg/compute/regiondrivers/cucloud.go
  pkg/mcclient/options/cloudaccounts.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cucloud/cucloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cucloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cucloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/loader/loader.go
Labels: size/XL

#17745 fix(common): project metadata
  pkg/apis/output.go
  pkg/cloudcommon/db/project.go
Labels: size/S, area/region

#17746 Automated cherry pick of #17745: fix(common): project metadata
  pkg/apis/output.go
  pkg/cloudcommon/db/project.go
Labels: size/S

#17749 feat(climc): add k8s-machine-post-prepare-resource command
  cmd/climc/shell/k8s/machines.go
Labels: size/XS, area/climc

#17750 Automated cherry pick of #17749: feat(climc): add k8s-machine-post-prepare-resource command
  cmd/climc/shell/k8s/machines.go
Labels: size/XS

#17751 fix(region): clean dirty cached images
  pkg/compute/models/cachedimages.go
Labels: size/S

#17752 Automated cherry pick of #17751: fix(region): clean dirty cached images
  pkg/compute/models/cachedimages.go
Labels: size/S

#17663 fix(keystone): displays the reason why user cannot be deleted
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/users.go
Labels: size/M, area/keystone

#17664 Automated cherry pick of #17663: fix(keystone): displays the reason why user cannot be deleted
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/users.go
Labels: size/M

#17754 fix: support unbind organization node
  pkg/keystone/models/organization_nodes.go
  pkg/keystone/tasks/organization_bind_task.go
Labels: size/M

#17762 fix: github workflow
  .github/workflows/docker_apigateway.yml
  .github/workflows/docker_climc.yml
  .github/workflows/docker_glance.yml
  .github/workflows/docker_host.yml
  .github/workflows/docker_keystone.yml
  .github/workflows/docker_notify.yml
  .github/workflows/docker_region.yml
  .github/workflows/docker_webconsole.yml
Labels: size/M

#17757 fix: pending delete identity projects
  pkg/apis/identity/input.go
  pkg/apis/identity/organization.go
  pkg/cloudcommon/db/enabledbase.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/pending_deleted.go
  pkg/cloudcommon/db/rolecache.go
  pkg/cloudcommon/db/standalone.go
  pkg/cloudcommon/db/statusbase.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/tenantcacheitem.go
  pkg/cloudcommon/db/tenantcachesync.go
  pkg/cloudcommon/db/usercache.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/organization_nodes.go
  pkg/keystone/models/organizations.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/roles.go
  pkg/keystone/models/users.go
Labels: size/XL

#17755 fix(baremetal-agent): update base image
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
Labels: size/XS, area/baremetal

#17756 Automated cherry pick of #17755: fix(baremetal-agent): update base image
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
Labels: size/XS

#17786 fix(region): avoid purge normal region
  pkg/compute/models/purge.go
Labels: size/XS, area/region

#17787 Automated cherry pick of #17786: fix(region): avoid purge normal region
  pkg/compute/models/purge.go
Labels: size/XS

#17789 fix: docker push
  .github/workflows/docker_apigateway.yml
  .github/workflows/docker_climc.yml
  .github/workflows/docker_cloudmon.yml
  .github/workflows/docker_esxi_agent.yml
  .github/workflows/docker_glance.yml
  .github/workflows/docker_host.yml
  .github/workflows/docker_keystone.yml
  .github/workflows/docker_logger.yml
  .github/workflows/docker_notify.yml
  .github/workflows/docker_region.yml
  .github/workflows/docker_scheduler.yml
  .github/workflows/docker_webconsole.yml
  scripts/docker_push.sh
Labels: size/M

#17790 Automated cherry pick of #17789: fix: docker push
  .github/workflows/docker_apigateway.yml
  .github/workflows/docker_climc.yml
  .github/workflows/docker_cloudmon.yml
  .github/workflows/docker_esxi_agent.yml
  .github/workflows/docker_glance.yml
  .github/workflows/docker_host.yml
  .github/workflows/docker_keystone.yml
  .github/workflows/docker_logger.yml
  .github/workflows/docker_notify.yml
  .github/workflows/docker_region.yml
  .github/workflows/docker_scheduler.yml
  .github/workflows/docker_webconsole.yml
  scripts/docker_push.sh
Labels: size/M

#17769 fix(logger): add translate
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/XS, area/logger

#17770 Automated cherry pick of #17769: fix(logger): add translate
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#17791 fix(region): avoid sync esxi panic
  pkg/compute/models/hosts.go
  pkg/compute/models/netinterfaces.go
Labels: size/XS, area/region

#17792 fix(climc): 'zone-list --region' is ignored
  pkg/mcclient/options/compute/zone.go
Labels: size/XS, area/climc

#17793 Automated cherry pick of #17792: fix(climc): 'zone-list --region' is ignored
  pkg/mcclient/options/compute/zone.go
Labels: size/XS

#17794 feat(climc): support k8s-cluster-create command getting input from file
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S, area/climc

#17795 Automated cherry pick of #17794: feat(climc): support k8s-cluster-create command getting input from file
  pkg/mcclient/options/k8s/cluster.go
Labels: size/S

#17776 Fix/lvm disk deploy
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/L

#17777 Automated cherry pick of #17776: Fix/lvm disk deploy
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/lvmutils.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/L

#17796 fix(region): support eip sync tags
  go.mod
  go.sum
  pkg/apis/compute/elasticip.go
  pkg/compute/models/elasticips.go
  pkg/compute/tasks/eip_remote_update_task.go
  pkg/compute/tasks/natgateway_remote_update_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/natgateway.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/resource_tag.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/utils.go
Labels: area/region, size/XL

#17797 Automated cherry pick of #17796: fix(region): support eip sync tags
  go.mod
  go.sum
  pkg/apis/compute/elasticip.go
  pkg/compute/models/elasticips.go
  pkg/compute/tasks/eip_remote_update_task.go
  pkg/compute/tasks/natgateway_remote_update_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/natgateway.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/resource_tag.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/utils.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
Labels: size/XL

#17801 fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/tasks/eip_allocate_task.go
  pkg/mcclient/cloudpods/eip.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/region.go
Labels: size/L, area/region

#17802 Automated cherry pick of #17801: fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/tasks/eip_allocate_task.go
  pkg/mcclient/cloudpods/eip.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/region.go
Labels: size/L

#17805 fix(host): gpu probe miss 3d type gpu
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/XS

#17807 Automated cherry pick of #17805: fix(host): gpu probe miss 3d type gpu
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/XS

#17806 Automated cherry pick of #17805: fix(host): gpu probe miss 3d type gpu
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/XS

#17808 Automated cherry pick of #17775: fix: windows 2012 no dns
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/XS

#17775 fix: windows 2012 no dns
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/XS

#17809 Automated cherry pick of #17775: fix: windows 2012 no dns
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/XS

#17811 fix: external project priority
  cmd/climc/shell/compute/external_projects.go
  go.mod
  go.sum
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/external_projects.go
  pkg/mcclient/options/compute/external_projects.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/project.go
Labels: size/M, area/region

#17773 Automated cherry pick of #17772: fix(region): cloud account sync log
  pkg/compute/models/cloudprovider_quotas.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
Labels: size/L

#17814 fix(logger): distinct field for action log
  pkg/logger/models/actionlog.go
Labels: size/XS, area/logger

#17815 Automated cherry pick of #17814: fix(logger): distinct field for action log
  pkg/logger/models/actionlog.go
Labels: size/XS

#17816 Automated cherry pick of #17814: fix(logger): distinct field for action log
  pkg/logger/models/actionlog.go
Labels: size/XS

#17819 fix(logger): distinct for kind
  pkg/logger/models/actionlog.go
Labels: size/XS, area/logger

#17820 Automated cherry pick of #17819: fix(logger): distinct for kind
  pkg/logger/models/actionlog.go
Labels: size/XS

#17821 Automated cherry pick of #17819: fix(logger): distinct for kind
  pkg/logger/models/actionlog.go
Labels: size/XS

#17823 fix(region): disable prepaid delete check
  pkg/compute/options/options.go
Labels: size/XS, area/region

#17837 fix(webconsole): fix #17822
  pkg/webconsole/options/options.go
  pkg/webconsole/session/remote_console.go
Labels: size/XS, area/webconsole

#17839 Automated cherry pick of #17837: fix(webconsole): fix #17822
  pkg/webconsole/options/options.go
  pkg/webconsole/session/remote_console.go
Labels: size/XS

#17840 fix: add index to server skus
  pkg/compute/models/server_skus.go
Labels: size/XS

#17841 Automated cherry pick of #17840: fix: add index to server skus
  pkg/compute/models/server_skus.go
Labels: size/XS

#17842 Automated cherry pick of #17840: fix: add index to server skus
  pkg/compute/models/skus.go
Labels: size/XS

#17832 fix(region): storage extra info
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/storage.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/storages.go
Labels: size/M, area/region

#17833 Automated cherry pick of #17832: fix(region): storage extra info
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/storage.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/storages.go
Labels: size/M

#17834 Automated cherry pick of #17832: fix(region): storage extra info
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/storage.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/storages.go
Labels: size/M

#17828 fix(region): guest sync log
  pkg/compute/models/cloudsync.go
Labels: size/S, area/region

#17829 Automated cherry pick of #17828: fix(region): guest sync log
  pkg/compute/models/cloudsync.go
Labels: size/S

#17825 fix(logger): export limit
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/S, area/logger

#17826 Automated cherry pick of #17825: fix(logger): export limit
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/S

#17843 fix: cachedimage add index
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storages.go
Labels: size/XS

#17845 Automated cherry pick of #17843: fix: cachedimage add index
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storages.go
Labels: size/XS

#17844 Automated cherry pick of #17843: fix: cachedimage add index
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storages.go
Labels: size/XS

#17849 update vendor 20230824 3.10
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/index.go
Labels: size/S

#17818 fix: vmware host wire recode
  Makefile
  go.mod
  go.sum
  pkg/apis/compute/host.go
  pkg/apis/compute/network.go
  pkg/apis/compute/vpc.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/baremetalagents.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/hostresource.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/cloudpods/host.go
  pkg/scheduler/cache/candidate/base.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/hostnetifs.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/classic_host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/node.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/compact_ips.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/datacenter.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/fakeregion.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/fakevpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/hostnic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/manager.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/mobase.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/net_topology_pro.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/tags.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/hypervisor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/host.go
  vendor/yunion.io/x/sqlchemy/index.go
Labels: size/XXL

#17855 Automated cherry pick of #17825: fix(logger): export limit
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/S

#17846 fix: debian 12 OS initialization
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/M

#17848 Automated cherry pick of #17846: fix: debian 12 OS initialization
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/M

#17847 Automated cherry pick of #17846: fix: debian 12 OS initialization
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
Labels: size/M

#17803 fix(region): support project mapping
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
Labels: size/M

#17804 Automated cherry pick of #17803: fix(region): support project mapping
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
Labels: size/M

#17856 fix(region): skip resource by tags
  pkg/compute/models/hosts.go
Labels: needs-backport, size/S, area/region

#17857 Automated cherry pick of #17856: fix(region): skip resource by tags
  pkg/compute/models/hosts.go
Labels: size/S

#17860 Automated cherry pick of #17856: fix(region): skip resource by tags
  pkg/compute/models/hosts.go
Labels: size/S

#17862 Automated cherry pick of #17861: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/zone.go
Labels: size/S

#17863 Automated cherry pick of #17861: fix(region): vendor update
  pkg/multicloud/qcloud/zone.go
Labels: size/XS

#17852 fix(region,host): support limit guest nic traffic
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_sync_nic_traffics_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL, request-merge

#17853 Automated cherry pick of #17852: fix(region,host): support limit guest nic traffic
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/guests.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_sync_nic_traffics_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL

#17866 fix(region): hostname length
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostnameresource.go
Labels: size/XS, area/region

#17867 Automated cherry pick of #17866: fix(region): hostname length
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostnameresource.go
Labels: size/XS

#17871 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/tag_base.go
Labels: size/M, area/region

#17872 Automated cherry pick of #17871: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/tag_base.go
Labels: size/M

#17864 fix: vpcagent sync wire should ignore external id
  pkg/apihelper/reflect.go
Labels: size/XS

#17859 fix: designate ip addresses when batch creating guests
  pkg/apis/compute/api.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/db/caller.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/db_joint_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/helper.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/baremetal_convert_hypervisor_task.go
  pkg/compute/tasks/disk_backup_recovery_task.go
  pkg/compute/tasks/disk_batch_create_task.go
  pkg/compute/tasks/guest_backup_tasks.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/compute/tasks/instance_backup_recovery_task.go
  pkg/compute/tasks/instance_snapshot_and_clone_task.go
  pkg/compute/tasks/schedule.go
  pkg/hostman/guestfs/fsdriver/userdata.go
Labels: size/XXL

#17882 fix(region-dns): resolve * dns
  pkg/compute/models/dnsrecords.go
Labels: size/XS, area/region-dns

#17886 fix(region-dns): resolve cname
  pkg/dns/dns.go
Labels: size/XS, area/region-dns

#17888 fix(notify): support list group_key,group_list
  pkg/notify/models/topic.go
Labels: size/XS

#17889 Automated cherry pick of #17888: fix(notify): support list group_key,group_list
  pkg/notify/models/topic.go
Labels: size/XS

#17884 fix(region): esxi name and tag sync
  go.mod
  go.sum
  pkg/compute/guestdrivers/esxi.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M, area/region

#17890 fix(region): avoid esxi vm delete failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
Labels: size/M, area/region

#17891 Automated cherry pick of #17890: fix(region): avoid esxi vm delete failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
Labels: size/M

#17873 fix(region): real delete sku
  pkg/compute/models/cloudimages.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/server_skus.go
Labels: size/S, area/region

#17874 Automated cherry pick of #17873: fix(region): real delete sku
  pkg/compute/models/cloudimages.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/server_skus.go
Labels: size/S

#17875 fix: user show nil map panic
  pkg/keystone/models/users.go
Labels: size/XS

#17876 Automated cherry pick of #17875: fix: user show nil map panic
  pkg/keystone/models/users.go
Labels: size/XS

#17897 fix(region): 云账号首次同步时并发同步sku及资源
  pkg/compute/models/cloudregions.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/purge.go
  pkg/compute/models/skuresource.go
  pkg/compute/tasks/cloud_account_sync_skus_task.go
  pkg/compute/tasks/cloud_region_sync_skus_task.go
Labels: size/M, area/region

#17898 Automated cherry pick of #17897: fix(region): 云账号首次同步时并发同步sku及资源
  pkg/compute/models/cloudregions.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/purge.go
  pkg/compute/models/skuresource.go
  pkg/compute/tasks/cloud_account_sync_skus_task.go
  pkg/compute/tasks/cloud_region_sync_skus_task.go
Labels: size/M

#17895 fix(cloudmon): skip part of service system metric collect
  pkg/apis/const.go
  pkg/cloudmon/misc/system.go
Labels: size/S, area/cloudmon

#17896 Automated cherry pick of #17895: fix(cloudmon): skip part of service system metric collect
  pkg/apis/const.go
  pkg/cloudmon/misc/system.go
Labels: size/S

#17899 fix(region): private zone check vpc
  pkg/compute/models/dnszones.go
Labels: size/XS, area/region

#17900 Automated cherry pick of #17899: fix(region): private zone check vpc
  pkg/compute/models/dnszones.go
Labels: size/XS
