Repository yunionio/cloudpods, pull requests merged in 2023-11, with the labels that each got.

#18501 fix: cleanup nbd
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/nbd/nbdman.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/util/xfsutils/doc.go
  pkg/util/xfsutils/lock.go
  pkg/util/xfsutils/xfsutils.go
Labels: size/L

#18527 Automated cherry pick of #18501: [WIP]fix: xfs zerofree (experimental)
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/nbd/nbdman.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/util/xfsutils/doc.go
  pkg/util/xfsutils/lock.go
  pkg/util/xfsutils/xfsutils.go
Labels: size/L

#18528 Automated cherry pick of #18501: [WIP]fix: xfs zerofree (experimental)
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/nbd/nbdman.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/util/xfsutils/doc.go
  pkg/util/xfsutils/lock.go
  pkg/util/xfsutils/xfsutils.go
Labels: size/L

#18522 fix(region): volcengine vm save image
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/storage.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
Labels: size/M, area/region

#18523 Automated cherry pick of #18522: fix(region): volcengine vm save image
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/storage.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
Labels: size/M

#18524 fix(region): skip vm eip not found error log
  pkg/compute/models/cloudsync.go
Labels: size/XS, area/region

#18525 Automated cherry pick of #18524: fix(region): skip vm eip not found error log
  pkg/compute/models/cloudsync.go
Labels: size/XS

#18526 Automated cherry pick of #18524: fix(region): skip vm eip not found error log
  pkg/compute/models/cloudsync.go
Labels: size/XS

#18530 Automated cherry pick of #18529: fix(host): live migrate pass disk num queues
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#18531 Automated cherry pick of #18529: fix(host): live migrate pass disk num queues
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#18532 update vendor
  pkg/scheduledtask/models/timer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
Labels: size/L

#18533 Automated cherry pick of #18532: update vendor
  pkg/scheduledtask/models/timer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
Labels: size/L

#18534 fix(region): vendor update
  go.mod
  go.sum
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/instance.go
Labels: size/M, area/region

#18535 Automated cherry pick of #18534: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/webconsole/consts.go
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/instance.go
Labels: size/L

#18538 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/objects.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/storagecache.go
Labels: size/L

#18539 Automated cherry pick of #18538: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/objects.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/storagecache.go
Labels: size/L

#18540 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
Labels: size/M, area/region

#18541 Automated cherry pick of #18540: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/pkg/util/netutils/netutils.go
Labels: size/M

#18544 Automated cherry pick of #18543: fix(region): volc bucket storage class
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/bucket.go
Labels: size/S

#18546 fix(host-deployer): clean nbd mount on host-deployer start
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/nbdman.go
Labels: size/M

#18547 Automated cherry pick of #18546: fix(host-deployer): clean nbd mount on host-deployer start
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/nbdman.go
Labels: size/M

#18548 Automated cherry pick of #18546: fix(host-deployer): clean nbd mount on host-deployer start
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/nbd/nbdman.go
Labels: size/M

#18550 Automated cherry pick of #18549: fix(region): esxi vm resize disk online
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/hostdrivers/esxi.go
Labels: size/S

#18553 fix(region,host): support traffic limit in change config
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/guest_sync_nic_traffics_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#18554 Automated cherry pick of #18553: fix(region,host): support traffic limit in change config
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/guest_sync_nic_traffics_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#18555 Automated cherry pick of #18554: Automated cherry pick of #18553: fix(region,host): support traffic limit in change config
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/guest_sync_nic_traffics_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#18557 fix(region): volcengine monitor
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/volc.go
  pkg/compute/guestdrivers/managedvirtual.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
Labels: size/L

#18558 Automated cherry pick of #18557: fix(region): volcengine monitor
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/volc.go
  pkg/compute/guestdrivers/managedvirtual.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
Labels: size/L

#18559 fix: host fail to migrate interface routes
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/macutils.go
Labels: size/M

#18560 Automated cherry pick of #18559: fix: host fail to migrate interface routes
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/macutils.go
Labels: size/M

#18561 Automated cherry pick of #18559: fix: host fail to migrate interface routes
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/macutils.go
Labels: size/M

#18562 Automated cherry pick of #18559: fix: host fail to migrate interface routes
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/macutils.go
Labels: size/M

#18565 fix: qemu disk set serial as disk_id
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#18566 Automated cherry pick of #18565: fix: qemu disk set serial as disk_id
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#18567 Automated cherry pick of #18565: fix: qemu disk set serial as disk_id
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#18568 Automated cherry pick of #18565: fix: qemu disk set serial as disk_id
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#18573 Automated cherry pick of #18571: fix(host): live migrate ensure disk storate type
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#18576 fix(host-deployer): detach nbd device do not block main thread
  pkg/hostman/diskutils/nbd/nbdman.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#18577 Automated cherry pick of #18576: fix(host-deployer): detach nbd device do not block main thread
  pkg/hostman/diskutils/nbd/nbdman.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#18578 Automated cherry pick of #18576: fix(host-deployer): detach nbd device do not block main thread
  pkg/hostman/diskutils/nbd/nbdman.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#18580 fix(host): sync guest machine type on live migrate
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#18581 Automated cherry pick of #18580: fix(host): sync guest machine type on live migrate
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#18582 Automated cherry pick of #18580: fix(host): sync guest machine type on live migrate
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/M

#18584 fix(host-deployer): use sync.lock on nbd connect/disconnect
  pkg/hostman/diskutils/nbd/driver.go
Labels: size/M

#18585 Automated cherry pick of #18584: fix(host-deployer): use sync.lock on nbd connect/disconnect
  pkg/hostman/diskutils/nbd/driver.go
Labels: size/M

#18586 Automated cherry pick of #18584: fix(host-deployer): use sync.lock on nbd connect/disconnect
  pkg/hostman/diskutils/nbd/driver.go
Labels: size/M

#18590 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/consts.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/subaccount.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/sslcertificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/organizations.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/baidu/baidu.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cucloud/cucloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/sslcertificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/jdcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/certificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qingcloud/qingcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/ucloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
Labels: area/region, size/XL

#18591 Automated cherry pick of #18590: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/consts.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/subaccount.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/sslcertificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/organizations.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/baidu/baidu.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cucloud/cucloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/sslcertificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/jdcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/certificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qingcloud/qingcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/ucloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
Labels: size/XL

#18595 Automated cherry pick of #18594: fix(region): clean invalid skus
  pkg/compute/models/server_skus.go
Labels: size/M

#18596 Automated cherry pick of #18594: fix(region): clean invalid skus
  pkg/compute/models/server_skus.go
Labels: size/M

#18602 Automated cherry pick of #18599: fix(host): ignore error when add bridge ip address route
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S

#18601 Automated cherry pick of #18599: fix(host): ignore error when add bridge ip address route
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S

#18600 Automated cherry pick of #18599: fix(host): ignore error when add bridge ip address route
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S

#18603 fix(webconsole): pve vnc support
  go.mod
  go.sum
  pkg/webconsole/server/server.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/M, area/region

#18604 Automated cherry pick of #18603: fix(webconsole): pve vnc support
  go.mod
  go.sum
  pkg/webconsole/server/server.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/M

#18605 Automated cherry pick of #18603: fix(webconsole): pve vnc support
  go.mod
  go.sum
  pkg/webconsole/server/server.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/M

#18608 feat(keystone_usage): support project count
  pkg/keystone/models/usages.go
Labels: size/S

#18611 Automated cherry pick of #18608: feat(keystone_usage): support project count
  pkg/keystone/models/usages.go
Labels: size/S

#18606 fix(region): avoid panic when sync aliyun redis
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/S, area/region

#18607 Automated cherry pick of #18606: fix(region): avoid panic when sync aliyun redis
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/elasticcache_instance.go
Labels: size/S

#18613 fix(region): pve cdrom with host info
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/models/cachedimages.go
Labels: size/M, area/region

#18614 Automated cherry pick of #18613: fix(region): pve cdrom with host info
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/models/cachedimages.go
Labels: size/M

#18615 Automated cherry pick of #18613: fix(region): pve cdrom with host info
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/models/cachedimages.go
Labels: size/M

#18619 Automated cherry pick of #18618: fix(keystone): fix usage empty projectTags
  pkg/keystone/models/usages.go
Labels: size/M

#18570 feat(region): qcloud&aliyun&huawei add sslcertificate resource sync
  go.mod
  go.sum
  pkg/apis/compute/sslcertificate.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/sslcertificate.go
  pkg/compute/service/handlers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/sslcertificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/sslcertificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/certificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/region.go
Labels: size/XL

#18620 fix(region): qcloud secgroup rule priority
  pkg/compute/regiondrivers/qcloud.go
Labels: size/XS, area/region

#18621 Automated cherry pick of #18620: fix(region): qcloud secgroup rule priority
  pkg/compute/regiondrivers/qcloud.go
Labels: size/XS

#18623 Automated cherry pick of #18622: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/S

#18624 Automated cherry pick of #18622: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/S

#18622 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
Labels: size/L

#18626 fix(common): support report bug
  cmd/climc/shell/yunionconf/bugreport.go
  pkg/baremetal/tasks/worker.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/db/taskman/localtaskworker.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudcommon/workmanager/manager.go
  pkg/cloudproxy/agent/worker/worker.go
  pkg/compute/models/syncworkers.go
  pkg/mcclient/modules/yunionconf/mod_bugreport.go
  pkg/util/atexit/atexit.go
  pkg/yunionconf/models/parameters.go
  pkg/yunionconf/service/handlers.go
Labels: size/L

#18628 Automated cherry pick of #18626: fix(common): support report bug
  cmd/climc/shell/yunionconf/bugreport.go
  pkg/baremetal/tasks/worker.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/db/taskman/localtaskworker.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudcommon/workmanager/manager.go
  pkg/cloudproxy/agent/worker/worker.go
  pkg/compute/models/syncworkers.go
  pkg/mcclient/modules/yunionconf/mod_bugreport.go
  pkg/util/atexit/atexit.go
  pkg/yunionconf/models/parameters.go
  pkg/yunionconf/service/handlers.go
Labels: size/L

#18629 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/image.go
Labels: size/XS

#18630 Automated cherry pick of #18629: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/image.go
Labels: size/XS

#18625 fix: cloudprovider external id
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/XL

#18627 Automated cherry pick of #18625: fix: cloudprovider external id
  pkg/apis/compute/cloudprovider.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
Labels: size/XL

#18631 fix(cloudmon): collect metric with project tags
  pkg/apis/compute/bucket.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/elasticip.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/apis/compute/kube_cluster.go
  pkg/apis/compute/loadbalancer.go
  pkg/apis/compute/modelarts_pool.go
  pkg/apis/compute/storage.go
  pkg/apis/output.go
  pkg/cloudmon/resources/resources.go
Labels: size/L, area/cloudmon

#18632 Automated cherry pick of #18631: fix(cloudmon): collect metric with project tags
  pkg/apis/compute/bucket.go
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/elasticip.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/apis/compute/kube_cluster.go
  pkg/apis/compute/loadbalancer.go
  pkg/apis/compute/modelarts_pool.go
  pkg/apis/compute/storage.go
  pkg/apis/output.go
  pkg/cloudmon/resources/resources.go
Labels: size/L

#18636 fix(region): change config check traffic limit params
  pkg/compute/models/guest_actions.go
Labels: size/XS

#18637 Automated cherry pick of #18636: fix(region): change config check traffic limit params
  pkg/compute/models/guest_actions.go
Labels: size/XS

#18638 Automated cherry pick of #18636: fix(region): change config check traffic limit params
  pkg/compute/models/guest_actions.go
Labels: size/XS

#18633 fix(region): esxi disk storage
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/L, area/region

#18635 Automated cherry pick of #18633: fix(region): esxi disk storage
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/L

#18639 fix(region,host): sriov nic hotplug and metrics fix
  pkg/apis/compute/guestnetwork.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#18640 Automated cherry pick of #18639: fix(region,host): sriov nic hotplug and metrics fix
  pkg/apis/compute/guestnetwork.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#18641 Automated cherry pick of #18639: fix(region,host): sriov nic hotplug and metrics fix
  pkg/apis/compute/guestnetwork.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M

#18647 fix(region): esxi support preallocation vdisk
  go.mod
  go.sum
  pkg/apis/compute/api.go
  pkg/apis/compute/disk_const.go
  pkg/apis/compute/guest_disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/disks.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/mcclient/cloudpods/disk.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/disk_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/disk_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/disk.go
Labels: size/L, area/region

#18648 Automated cherry pick of #18647: fix(region): esxi support preallocation vdisk
  go.mod
  go.sum
  pkg/apis/compute/api.go
  pkg/apis/compute/disk_const.go
  pkg/apis/compute/guest_disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/disks.go
  pkg/compute/models/storages.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/mcclient/cloudpods/disk.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/disk_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/disk_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/disk.go
Labels: size/L

#18651 fix(region): vm gpu notes
  pkg/compute/models/guests.go
Labels: size/XS, area/region

#18652 Automated cherry pick of #18651: fix(region): vm gpu notes
  pkg/compute/models/guests.go
Labels: size/XS

#18653 fix(yunionconf): allow disable bug report
  cmd/climc/shell/yunionconf/bugreport.go
  pkg/mcclient/modules/yunionconf/mod_bugreport.go
  pkg/yunionconf/models/parameters.go
  pkg/yunionconf/service/handlers.go
Labels: size/M, area/yunionconf

#18654 Automated cherry pick of #18653: fix(yunionconf): allow disable bug report
  cmd/climc/shell/yunionconf/bugreport.go
  pkg/mcclient/modules/yunionconf/mod_bugreport.go
  pkg/yunionconf/models/parameters.go
  pkg/yunionconf/service/handlers.go
Labels: size/M

#18644 fix: extend gpu pci class codes
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/M

#18645 Automated cherry pick of #18644: fix: extend gpu pci class codes
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/M

#18649 Automated cherry pick of #18644: fix: extend gpu pci class codes
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/M

#18650 fix: extend gpu pci class codes to [0380] at release/3.9
  pkg/baremetal/tasks/baseprepare.go
  pkg/hostman/guestman/qemu/qemu.go
  pkg/hostman/isolated_device/gpu.go
Labels: size/M

#18634 chore: unnecessary use of fmt.Sprintf d
  pkg/cloudcommon/db/lockman/lockman_test.go
  pkg/cloudcommon/validators/validators_cert.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/tasks/scaling_group_delete_task.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/lbagent/models/haproxy.go
  pkg/mcclient/session.go
  pkg/scheduler/algorithm/predicates/baremetal/cdrom_boot_predicate.go
  pkg/scheduler/handler/ping.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#18658 Automated cherry pick of #18634: chore: unnecessary use of fmt.Sprintf d
  pkg/cloudcommon/db/lockman/lockman_test.go
  pkg/cloudcommon/validators/validators_cert.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/tasks/scaling_group_delete_task.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/lbagent/models/haproxy.go
  pkg/mcclient/session.go
  pkg/scheduler/algorithm/predicates/baremetal/cdrom_boot_predicate.go
  pkg/scheduler/handler/ping.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#18659 Automated cherry pick of #18634: chore: unnecessary use of fmt.Sprintf d
  pkg/cloudcommon/db/lockman/lockman_test.go
  pkg/cloudcommon/validators/validators_cert.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/tasks/scaling_group_delete_task.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvmhelper.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/lbagent/models/haproxy.go
  pkg/mcclient/session.go
  pkg/scheduler/algorithm/predicates/baremetal/cdrom_boot_predicate.go
  pkg/scheduler/handler/ping.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#18655 fix(host): catch init error
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/M, area/host

#18656 Automated cherry pick of #18655: fix(host): catch init error
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/M

#18657 Automated cherry pick of #18655: fix(host): catch init error
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/M

#18660 Automated cherry pick of #18655: fix(host): catch init error
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
Labels: size/S

#18661 fix(region): order by os dist
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S, area/region

#18662 Automated cherry pick of #18661: fix(region): order by os dist
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#18668 Automated cherry pick of #18661: fix(region): order by os dist
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#18665 fix(regin): instance snapshot create guest fill os arch
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#18667 Automated cherry pick of #18665: fix(regin): instance snapshot create guest fill os arch
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#18666 Automated cherry pick of #18665: fix(regin): instance snapshot create guest fill os arch
  pkg/compute/models/instance_snapshots.go
Labels: size/XS

#18672 fix(host): setup routes from start to end
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S, area/host

#18673 Automated cherry pick of #18672: fix(host): setup routes from start to end
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S

#18674 Automated cherry pick of #18672: fix(host): setup routes from start to end
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S

#18675 Automated cherry pick of #18672: fix(host): setup routes from start to end
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
Labels: size/S

#18663 fix(keystone): fix usage for projectNum
  pkg/keystone/models/usages.go
Labels: size/XS

#18664 Automated cherry pick of #18663: fix(keystone): fix usage for projectNum
  pkg/keystone/models/usages.go
Labels: size/XS

#18676 feat(region): support oracle cloud
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/misc/feature.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/oracle.go
  pkg/compute/hostdrivers/oracle.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/regiondrivers/oracle.go
  pkg/mcclient/options/cloudaccounts.go
  vendor/github.com/oracle/oci-go-sdk/LICENSE.txt
  vendor/github.com/oracle/oci-go-sdk/NOTICE.txt
  vendor/github.com/oracle/oci-go-sdk/common/client.go
  vendor/github.com/oracle/oci-go-sdk/common/common.go
  vendor/github.com/oracle/oci-go-sdk/common/configuration.go
  vendor/github.com/oracle/oci-go-sdk/common/errors.go
  vendor/github.com/oracle/oci-go-sdk/common/helpers.go
  vendor/github.com/oracle/oci-go-sdk/common/http.go
  vendor/github.com/oracle/oci-go-sdk/common/http_signer.go
  vendor/github.com/oracle/oci-go-sdk/common/log.go
  vendor/github.com/oracle/oci-go-sdk/common/retry.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/loader/loader.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/oracle.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/region.go
Labels: size/XXL

#18679 Automated cherry pick of #18676: feat(region): support oracle cloud
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/misc/feature.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/oracle.go
  pkg/compute/hostdrivers/oracle.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/regiondrivers/oracle.go
  pkg/mcclient/options/cloudaccounts.go
  vendor/github.com/oracle/oci-go-sdk/LICENSE.txt
  vendor/github.com/oracle/oci-go-sdk/NOTICE.txt
  vendor/github.com/oracle/oci-go-sdk/common/client.go
  vendor/github.com/oracle/oci-go-sdk/common/common.go
  vendor/github.com/oracle/oci-go-sdk/common/configuration.go
  vendor/github.com/oracle/oci-go-sdk/common/errors.go
  vendor/github.com/oracle/oci-go-sdk/common/helpers.go
  vendor/github.com/oracle/oci-go-sdk/common/http.go
  vendor/github.com/oracle/oci-go-sdk/common/http_signer.go
  vendor/github.com/oracle/oci-go-sdk/common/log.go
  vendor/github.com/oracle/oci-go-sdk/common/retry.go
  vendor/github.com/oracle/oci-go-sdk/common/version.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/loader/loader.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/oracle.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/region.go
Labels: size/XXL

#18669 fix(host): sync sriov nic bw on change config
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#18670 Automated cherry pick of #18669: fix(host): sync sriov nic bw on change config
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#18671 Automated cherry pick of #18669: fix(host): sync sriov nic bw on change config
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#18677 feat(region,climc): add set-os-info api
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M, area/region, area/climc

#18678 Automated cherry pick of #18677: feat(region,climc): add set-os-info api
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#18680 Automated cherry pick of #18677: feat(region,climc): add set-os-info api
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#18693 fix: organization node weight not effective
  pkg/keystone/models/organization_nodes.go
Labels: size/XS

#18694 Automated cherry pick of #18693: fix: organization node weight not effective
  pkg/keystone/models/organization_nodes.go
Labels: size/XS

#18687 fix: host set nil metadata
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#18688 Automated cherry pick of #18687: fix: host set nil metadata
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#18689 Automated cherry pick of #18687: fix: host set nil metadata
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#18682 fix: make host dhcp lease options global
  pkg/hostman/options/options.go
Labels: size/XS

#18683 Automated cherry pick of #18682: fix: make host dhcp lease options global
  pkg/hostman/options/options.go
Labels: size/XS

#18684 Automated cherry pick of #18682: fix: make host dhcp lease options global
  pkg/hostman/options/options.go
Labels: size/XS

#18685 Automated cherry pick of #18682: fix: make host dhcp lease options global
  pkg/hostman/options/options.go
Labels: size/XS

#18686 Automated cherry pick of #18682: fix: make host dhcp lease options global
  pkg/hostman/options/options.go
Labels: size/XS

#18681 fix: windows GPU vm should set hypervisor=off 3.9
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/S

#18690 fix: windows GPU vm should set hypervisor=off
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#18691 Automated cherry pick of #18690: fix: windows GPU vm should set hypervisor=off
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#18692 Automated cherry pick of #18690: fix: windows GPU vm should set hypervisor=off
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#18695 fix: update lb cluster with patch params
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/loadbalancerclusters.go
Labels: size/M

#18697 Automated cherry pick of #18695: fix: update lb cluster with patch params
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/loadbalancerclusters.go
Labels: size/M

#18696 Automated cherry pick of #18695: fix: update lb cluster with patch params
  pkg/cloudcommon/db/standalone_anon.go
  pkg/compute/models/loadbalancerclusters.go
Labels: size/M

#18698 fix(region): fix db_dispatcher duplicate notify
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/notify_hook.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/hosts.go
Labels: size/M

#18699 Automated cherry pick of #18698: fix(region): fix db_dispatcher duplicate notify
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/notify_hook.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/hosts.go
Labels: size/M

#18700 Automated cherry pick of #18698: fix(region): fix db_dispatcher duplicate notify
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/notify_hook.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/hosts.go
Labels: size/M

#18701 update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/M

#18702 Automated cherry pick of #18701: update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/M

#18706 fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/wires.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/boot-disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/oracle.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/security-group-rule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/security-group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/tag.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/zone.go
Labels: size/XXL, area/region

#18710 Automated cherry pick of #18704: fix(region): rds skip notImplementedErr
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/M

#18711 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/dnszone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/dns_domain_record.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/cdn.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
Labels: area/region, size/XL

#18712 Automated cherry pick of #18711: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
Labels: size/S

#18713 Automated cherry pick of #18711: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer.go
Labels: size/S
