Repository yunionio/cloudpods, pull requests merged in 2023-09, with the labels that each got.

#17877 fix: storage usaged capacity by medium_type revisit
  pkg/compute/models/storages.go
  pkg/compute/usages/handler.go
Labels: size/S

#17878 Automated cherry pick of #17877: fix: storage usaged capacity by medium_type revisit
  pkg/compute/models/storages.go
  pkg/compute/usages/handler.go
Labels: size/S

#17688 fix(region): auto remove cloudprovider
  pkg/compute/models/cloudaccounts.go
Labels: needs-backport, size/M, area/region

#17881 Automated cherry pick of #17688: fix(region): auto remove cloudprovider
  pkg/compute/models/cloudaccounts.go
Labels: size/M

#17892 feat(region): support set server as daemon on create
  pkg/apis/compute/api.go
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#17893 Automated cherry pick of #17892: feat(region): support set server as daemon on create
  pkg/apis/compute/api.go
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#17901 fix(region): support skip sync vpc and secgorup
  pkg/compute/models/cloudsync.go
Labels: size/XS, area/region

#17902 Automated cherry pick of #17901: fix(region): support skip sync vpc and secgorup
  pkg/compute/models/cloudsync.go
Labels: size/XS

#17879 feat(region,host): vgpu support, refector host registor
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/isolated_device.go
  pkg/apis/compute/isolated_device_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nic.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/sriov_base.go
  pkg/hostman/isolated_device/sriov_vgpu.go
  pkg/hostman/options/options.go
  pkg/mcclient/modules/compute/mod_isolatedevices.go
Labels: size/XXL

#17880 Manual Cherrypick of #17879: vgpu support, refector host registor
  cmd/climc/shell/compute/hosts.go
  pkg/apis/compute/host.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/isolated_device.go
  pkg/apis/compute/isolated_device_const.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nic.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/sriov_base.go
  pkg/hostman/isolated_device/sriov_vgpu.go
  pkg/hostman/options/options.go
  pkg/mcclient/modules/compute/mod_isolatedevices.go
Labels: size/XXL

#17914 fix(region-dns): dns query for *.example.com
  pkg/compute/models/dnsrecords.go
Labels: size/S, area/region, area/region-dns

#17915 Automated cherry pick of #17914: fix(region-dns): dns query for *.example.com
  pkg/compute/models/dnsrecords.go
Labels: size/S

#17919 fix(region): support sync cloudprovider
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#17920 Automated cherry pick of #17919: fix(region): support sync cloudprovider
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#17922 fix: struct sub field tag
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: size/XS

#17923 Automated cherry pick of #17922: fix: struct sub field tag
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: size/XS

#17924 Automated cherry pick of #17922: fix: struct sub field tag
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/roles.go
Labels: size/XS

#17927 fix(docker buildx cross platform docker image fix): 跨平台编译docker镜像明确指定架构
  scripts/docker_push.sh
Labels: size/XS

#17928 Automated cherry pick of #17927: fix(docker buildx cross platform docker image fix): 跨平台编译docker镜像明确指定架构
  scripts/docker_push.sh
Labels: size/XS

#17929 Automated cherry pick of #17927: fix(docker buildx cross platform docker image fix): 跨平台编译docker镜像明确指定架构
  scripts/docker_push.sh
Labels: size/XS

#17925 fix(apigateway): add GetSpecificMethods to resource manager
  cmd/climc/shell/k8s/container_registry.go
  pkg/apigateway/handler/resource.go
  pkg/mcclient/modulebase/base.go
  pkg/mcclient/modulebase/modules.go
  pkg/mcclient/modules/k8s/container_registry.go
Labels: size/S, area/climc, area/apigateway

#17926 Automated cherry pick of #17925: fix(apigateway): add GetSpecificMethods to resource manager
  cmd/climc/shell/k8s/container_registry.go
  pkg/apigateway/handler/resource.go
  pkg/mcclient/modulebase/base.go
  pkg/mcclient/modulebase/modules.go
  pkg/mcclient/modules/k8s/container_registry.go
Labels: size/S

#17930 hotfix: typo
  scripts/docker_push.sh
Labels: size/XS

#17931 Automated cherry pick of #17930: hotfix: typo
  scripts/docker_push.sh
Labels: size/XS

#17932 Automated cherry pick of #17930: hotfix: typo
  scripts/docker_push.sh
Labels: size/XS

#17894 Hotfix/qj vmware wire external
  cmd/climc/shell/identity/users.go
  go.mod
  go.sum
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/hostnetworks.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
  pkg/compute/models/wires.go
  pkg/keystone/models/identitybase.go
  pkg/keystone/models/users.go
  pkg/mcclient/options/identity/users.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/tags.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qingcloud/qingcloud.go
Labels: size/XL

#17933 fix(region): storagecache sync
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storages.go
Labels: size/M, area/region

#17934 Automated cherry pick of #17933: fix(region): storagecache sync
  pkg/compute/models/cloudsync.go
  pkg/compute/models/storages.go
Labels: size/M

#17936 feat(climc): download container registry image directly
  cmd/climc/shell/k8s/container_registry.go
  pkg/mcclient/modules/k8s/container_registry.go
Labels: size/M, area/climc

#17937 Automated cherry pick of #17936: feat(climc): download container registry image directly
  cmd/climc/shell/k8s/container_registry.go
  pkg/mcclient/modules/k8s/container_registry.go
Labels: size/M

#17940 fix(cloudcommon): compatible with cases when data is nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS, area/keystone, area/util

#17941 Automated cherry pick of #17940: fix(cloudcommon): compatible with cases when data is nil
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/XS

#17944 fix(region): project mapping support inputProject
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17946 Automated cherry pick of #17944: fix(region): project mapping support inputProject
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17950 fix: util func to convert id or name of tenants to ids
  pkg/cloudcommon/db/tenantcache.go
Labels: size/S

#17947 fix: allow remvoe server extra options of specific value
  cmd/climc/shell/compute/servers.go
Labels: size/XS

#17943 fix: panic when syncing user external resources
  pkg/keystone/models/users.go
Labels: size/S

#17945 Automated cherry pick of #17943: fix: panic when syncing user external resources
  pkg/keystone/models/users.go
Labels: size/S

#17939 Automated cherry pick of #17938: fix: support user data scripts
  go.mod
  go.sum
  pkg/apigateway/handler/doc.go
  pkg/apis/compute/regiondata.go
  pkg/baremetal/manager.go
  pkg/cloudcommon/userdata/userdata.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/elasticcache_backup_delete_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/userdata.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/hostdeployer/Readme.md
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/storageman/storage_agent.go
  pkg/util/qemuimg/consts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/errors.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
Labels: size/XL

#17953 fix(notify): ignore EventId in send
  pkg/notify/models/event.go
Labels: size/XS

#17957 fix(notify): add group_times for subscriber
  pkg/apis/notify/config.go
  pkg/apis/notify/subscriber.go
  pkg/mcclient/options/notify/subscription.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver_notification.go
  pkg/notify/models/subscriber.go
  pkg/notify/models/topic.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/L

#17959 Automated cherry pick of #17957: fix(notify): add group_times for subscriber
  pkg/apis/notify/config.go
  pkg/apis/notify/subscriber.go
  pkg/mcclient/options/notify/subscription.go
  pkg/notify/models/notification.go
  pkg/notify/models/receiver_notification.go
  pkg/notify/models/subscriber.go
  pkg/notify/models/topic.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/L

#17935 fix(region): set public for keypair
  cmd/climc/shell/compute/keypairs.go
  pkg/apis/compute/input.go
  pkg/apis/compute/keypair.go
  pkg/cloudcommon/db/sharablebase.go
  pkg/cloudcommon/db/sharedresource.go
  pkg/compute/models/keypairs.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/keypairs.go
Labels: area/region, do-not-merge/work-in-progress, size/XL

#17963 fix: some kernel params tune by default
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#17964 Automated cherry pick of #17963: fix: some kernel params tune by default
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#17965 Automated cherry pick of #17963: fix: some kernel params tune by default
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#17966 Automated cherry pick of #17963: fix: some kernel params tune by default
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#17974 fix(host): set migrate bandwidth nolimit
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#17975 Automated cherry pick of #17974: fix(host): set migrate bandwidth nolimit
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#17976 Automated cherry pick of #17974: fix(host): set migrate bandwidth nolimit
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#17970 fix(region): avoid panic
  pkg/compute/models/guests.go
Labels: size/S, area/region

#17971 Automated cherry pick of #17970: fix(region): avoid panic
  pkg/compute/models/guests.go
Labels: size/S

#17955 fix(host): host register skip infiniband nic
  pkg/util/sysutils/nics.go
Labels: size/XS

#17960 fix: error returned by host storage sync was overwritten
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#17961 Automated cherry pick of #17960: fix: error returned by host storage sync was overwritten
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#17962 fix: avoid missing vlan config error
  pkg/util/netutils2/vlan_config.go
Labels: size/S

#17978 Automated cherry pick of #17977: fix: allow vm turn on selinux
  pkg/cloudcommon/consts/deployer.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#17979 fix: vmware sync os info may override os distribution and ip
  go.mod
  go.sum
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/h3c.go
  pkg/compute/guestdrivers/hcs.go
  pkg/compute/guestdrivers/hcsop.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/huaweistack.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/nutanix.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/L

#17983 fix(region): support aws gp3 throughput
  go.mod
  go.sum
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/storages.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
Labels: size/L, area/region

#17986 fix(region): batch sku sync
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/elasticcache_skus.go
  pkg/compute/models/server_skus.go
  pkg/compute/options/options.go
Labels: size/M, area/region

#17992 feat(climc): add k8s-cluster-list options
  pkg/mcclient/options/k8s/cluster.go
Labels: size/XS, area/climc

#17993 Automated cherry pick of #17992: feat(climc): add k8s-cluster-list options
  pkg/mcclient/options/k8s/cluster.go
Labels: size/XS

#17988 fix(region): check nvidia vgpu count and conflict with other gpus
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/M

#17989 Automated cherry pick of #17988: fix(region): check nvidia vgpu count and conflict with other gpus
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/M

#17985 fix(region): clean tenantcache metadata
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/tenantcacheitem.go
  pkg/cloudcommon/db/tenantcachesync.go
Labels: size/S, area/region

#17994 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
Labels: size/S, area/region

#17995 Automated cherry pick of #17994: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
Labels: size/S

#17996 fix(region): external project
  pkg/cloudcommon/db/keystonecache.go
  pkg/cloudcommon/db/tenantcache.go
  pkg/cloudcommon/db/tenantcacheitem.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/external_projects.go
Labels: size/M

#18004 fix(logclient): add i18n maps for translation
  pkg/util/logclient/consts_i18n.go
Labels: size/S

#18005 Automated cherry pick of #18004: fix(logclient): add i18n maps for translation
  pkg/util/logclient/consts_i18n.go
Labels: size/S

#18006 Automated cherry pick of #18004: fix(logclient): add i18n maps for translation
  pkg/util/logclient/consts_i18n.go
Labels: size/S

#18002 Automated cherry pick of #18001: chore: update host-deployer base image
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#18007 fix(region): update status failed
  pkg/cloudcommon/db/statusbase.go
Labels: size/XS, area/region

#18008 Automated cherry pick of #18007: fix(region): update status failed
  pkg/cloudcommon/db/statusbase.go
Labels: size/XS

#18010 fix(region): esxi image sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M, area/region

#18011 Automated cherry pick of #18010: fix(region): esxi image sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M

#18000 fix(logger): add system account field
  cmd/climc/shell/logger/actions.go
  pkg/apis/logger/input.go
  pkg/cloudcommon/db/opslog.go
  pkg/keystone/tokens/token.go
  pkg/logger/models/actionlog.go
  pkg/mcclient/token.go
  pkg/mcclient/token2.go
  pkg/mcclient/token3.go
  pkg/mcclient/tokensimple.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
  pkg/util/logclient/logclient.go
Labels: size/L

#18014 fix(region): remove useless code
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/buckets.go
  pkg/compute/models/scaling_policy.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/roles.go
  pkg/keystone/models/services.go
  pkg/monitor/models/alert.go
  pkg/monitor/subscriptionmodel/subcription.go
Labels: size/L, area/region

#18015 Automated cherry pick of #18014: fix(region): remove useless code
  pkg/cloudcommon/db/infraresource.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/cloudcommon/db/sharablevirtual.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/buckets.go
  pkg/compute/models/scaling_policy.go
  pkg/keystone/models/domains.go
  pkg/keystone/models/groups.go
  pkg/keystone/models/identity_provider.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/roles.go
  pkg/keystone/models/services.go
  pkg/monitor/models/alert.go
  pkg/monitor/subscriptionmodel/subcription.go
Labels: size/L

#18016 feat(region): support update description
  go.mod
  go.sum
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/cloudpods/instance.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eks_node_group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/internetgateway.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancercert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/routetable.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/saml_provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/tag_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/vpc_peering_connection.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/classic_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/dbinstance_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/rds_mysql.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/instance.go
Labels: size/L

#18020 fix(host): nvidia vgpu hotplug
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/nvme.go
  pkg/hostman/isolated_device/pci_device.go
  pkg/hostman/isolated_device/sriov_base.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#18021 Automated cherry pick of #18020: fix(host): nvidia vgpu hotplug
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/nvme.go
  pkg/hostman/isolated_device/pci_device.go
  pkg/hostman/isolated_device/sriov_base.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#18025 update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
Labels: size/M

#18030 fix(region): fix empty zone for qcloud
  pkg/multicloud/qcloud/qcloud.go
Labels: size/XS

#18032 fix(region): select available storage
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
Labels: size/S, area/region

#18033 Automated cherry pick of #18032: fix(region): select available storage
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
Labels: size/S

#18034 Automated cherry pick of #18032: fix(region): select available storage
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
Labels: size/S

#18028 fix(region): update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#18029 Automated cherry pick of #18028: fix(region): update vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#18036 Automated cherry pick of #17465: fix(region,host): qga command timeout
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/monitor/qga/qga.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#18024 fix: validate get metadata privileges
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/metadata_test.go
  pkg/cloudcommon/db/virtualresource.go
Labels: size/M

#18031 Automated cherry pick of #18024: fix: validate get metadata privileges
  pkg/cloudcommon/db/metadata.go
  pkg/cloudcommon/db/metadata_test.go
  pkg/cloudcommon/db/virtualresource.go
Labels: size/M

#18037 fix(region): avoid deadlock when delete account
  pkg/compute/models/purge.go
Labels: size/M, area/region

#18038 Automated cherry pick of #18037: fix(region): avoid deadlock when delete account
  pkg/compute/models/purge.go
Labels: size/M

#18039 fix(region): skip sync vm disk error
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/natstable.go
  pkg/compute/models/vpcs.go
Labels: size/M, area/region

#18040 Automated cherry pick of #18039: fix(region): skip sync vm disk error
  pkg/compute/models/disks.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/natstable.go
  pkg/compute/models/vpcs.go
Labels: size/M

#18046 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/enterpriseprojects.go
Labels: size/S, area/region

#18047 Automated cherry pick of #18046: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/enterpriseprojects.go
Labels: size/S

#18048 fix(region): dns record log
  pkg/compute/tasks/dns_record_delete_task.go
Labels: size/S, area/region

#18049 Automated cherry pick of #18048: fix(region): dns record log
  pkg/compute/tasks/dns_record_delete_task.go
Labels: size/S

#18054 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/storage.go
Labels: size/S, area/region

#18056 fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/waf_rule_groups.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/resourcedirectory.go
Labels: size/L, area/region

#18058 fix: skip get metadata check if usercred is nil
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#18059 Automated cherry pick of #18058: fix: skip get metadata check if usercred is nil
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#18064 Automated cherry pick of #18063: Hotfix/qj server network sub ips3
  pkg/compute/models/networkaddresses.go
Labels: size/XS

#18086 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
Labels: size/S, area/region

#18087 Automated cherry pick of #18086: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
Labels: size/S

#18083 fix(region): kube cluster version
  pkg/compute/models/kube_clusters.go
Labels: size/XS, area/region

#18084 Automated cherry pick of #18083: fix(region): kube cluster version
  pkg/compute/models/kube_clusters.go
Labels: size/XS

#18110 fix(region): server sku cpu arch filter
  pkg/apis/compute/sku_const.go
  pkg/compute/models/server_skus.go
  pkg/mcclient/options/serverskus.go
Labels: size/M, area/region

#18111 Automated cherry pick of #18110: fix(region): server sku cpu arch filter
  pkg/apis/compute/sku_const.go
  pkg/compute/models/server_skus.go
  pkg/mcclient/options/serverskus.go
Labels: size/M

#18112 Automated cherry pick of #18110: fix(region): server sku cpu arch filter
  pkg/apis/compute/sku_const.go
  pkg/compute/models/server_skus.go
  pkg/mcclient/options/serverskus.go
Labels: size/M

#18102 fix(region): guest vnc error
  pkg/compute/guestdrivers/kvm.go
Labels: size/XS, area/region

#18103 Automated cherry pick of #18102: fix(region): guest vnc error
  pkg/compute/guestdrivers/kvm.go
Labels: size/XS

#18104 Automated cherry pick of #18102: fix(region): guest vnc error
  pkg/compute/guestdrivers/kvm.go
Labels: size/XS

#18107 fix(region): fix #18106 remove change chonfig stop charing restrict
  pkg/compute/models/guest_actions.go
Labels: size/XS, area/region

#18108 Automated cherry pick of #18107: fix(region): fix #18106 remove change chonfig stop charing restrict
  pkg/compute/models/guest_actions.go
Labels: size/XS

#18109 Automated cherry pick of #18107: fix(region): fix #18106 remove change chonfig stop charing restrict
  pkg/compute/models/guest_actions.go
Labels: size/XS

#18100 Automated cherry pick of #18099: fix(region): avoid deadlock for delete account
  pkg/compute/models/disks.go
  pkg/compute/models/dnszones.go
  pkg/compute/models/purge.go
Labels: size/L

#18117 fix(region): cloudpods userdata
  pkg/compute/guestdrivers/cloudpods.go
  pkg/compute/models/server_skus.go
Labels: size/XS, area/region

#18118 Automated cherry pick of #18117: fix(region): cloudpods userdata
  pkg/compute/guestdrivers/cloudpods.go
  pkg/compute/models/server_skus.go
Labels: size/XS

#18119 Automated cherry pick of #18117: fix(region): cloudpods userdata
  pkg/compute/guestdrivers/cloudpods.go
  pkg/compute/models/server_skus.go
Labels: size/XS

#18121 fix(esxi-agent): vmware hostname
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#18122 Automated cherry pick of #18121: fix(esxi-agent): vmware hostname
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#18123 Automated cherry pick of #18121: fix(esxi-agent): vmware hostname
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#18074 Automated cherry pick of #18073: feat(region): host list filter by host storage type
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/M

#18075 Automated cherry pick of #18073: feat(region): host list filter by host storage type
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/M

#17858 feat(region,host,host-deployer): add qga set network
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest_sync_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/monitor/qmp.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: lgtm, area/region, area/host, size/XL, area/host-deployer

#18085 Manual Cherrypick of #17858: add qga set network
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest_sync_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/monitor/qmp.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL

#18088 Automated cherry pick of #17858: feat(region,host,host-deployer): add qga set network
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest_sync_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/monitor/qmp.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL

#18076 fix(region,host): guest save image restart not work
  pkg/compute/tasks/disk_save_task.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/XS

#18077 Automated cherry pick of #18076: fix(region,host): guest save image restart not work
  pkg/compute/tasks/disk_save_task.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/XS

#18078 Automated cherry pick of #18076: fix(region,host): guest save image restart not work
  pkg/compute/tasks/disk_save_task.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/XS

#18079 Automated cherry pick of #18076: fix(region,host): guest save image restart not work
  pkg/compute/tasks/disk_save_task.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/XS

#18065 fix(region,host): cancel migrate sync guest status
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/M

#18066 Automated cherry pick of #18065: fix(region,host): cancel migrate sync guest status
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/M

#18068 Automated cherry pick of #18065: fix(region,host): cancel migrate sync guest status
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#18080 Fix/host delete validate
  pkg/compute/models/hosts.go
Labels: size/S

#18081 Automated cherry pick of #18080: Fix/host delete validate
  pkg/compute/models/hosts.go
Labels: size/S

#18096 Fix/backup guest prelaunch
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/M

#18097 Automated cherry pick of #18096: Fix/backup guest prelaunch
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/M

#18098 Automated cherry pick of #18096: Fix/backup guest prelaunch
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/M

#18124 fix: charset mismatch in tenant cache convert_ids
  pkg/cloudcommon/db/tenantcache.go
Labels: size/XS

#18125 Automated cherry pick of #18124: fix: charset mismatch in tenant cache convert_ids
  pkg/cloudcommon/db/tenantcache.go
Labels: size/XS

#18126 fix(region): hide agent status
  pkg/compute/models/baremetalagents.go
Labels: size/XS, area/baremetal, area/region

#18127 Automated cherry pick of #18126: fix(region): hide agent status
  pkg/compute/models/baremetalagents.go
Labels: size/XS

#18132 fix(region): aws disk type
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/disk.go
Labels: size/S, area/region

#18133 Automated cherry pick of #18132: fix(region): aws disk type
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/disk.go
Labels: size/S

#18114 fix(region): network update detail error
  pkg/compute/models/networks.go
Labels: size/XS, area/region

#18115 Automated cherry pick of #18114: fix(region): network update detail error
  pkg/compute/models/networks.go
Labels: size/XS
