Repository yunionio/cloudpods, pull requests merged in 2023-07, with the labels that each got.

#17430 fix(region): fix server list type and ip from metadata
  pkg/compute/models/guests.go
Labels: lgtm, size/L

#17434 Automated cherry pick of #17430: fix(region): fix server list type and ip from metadata
  pkg/compute/models/guests.go
Labels: size/L

#17435 fix(region): support skip sync resource
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/L, area/region

#17437 Automated cherry pick of #17435: fix(region): support skip sync resource
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/L

#17122 fix(notify): remove topic_tbl.advance_days
  build/notify/root/opt/yunion/share/local-templates/content@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PASSWORD_EXPIRE_SOON.tmpl
  cmd/climc/shell/notify/notification.go
  pkg/compute/models/billingresource.go
  pkg/compute/options/options.go
  pkg/keystone/models/passwords.go
  pkg/keystone/options/options.go
  pkg/notify/models/notification.go
  pkg/notify/models/topic.go
Labels: lgtm, size/L

#17440 Automated cherry pick of #17122: fix(notify): remove topic_tbl.advance_days
  build/notify/root/opt/yunion/share/local-templates/content@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/content@en/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@cn/PASSWORD_EXPIRE_SOON.tmpl
  build/notify/root/opt/yunion/share/local-templates/title@en/PASSWORD_EXPIRE_SOON.tmpl
  cmd/climc/shell/notify/notification.go
  pkg/apis/notify/template.go
  pkg/compute/models/billingresource.go
  pkg/compute/options/options.go
  pkg/keystone/models/passwords.go
  pkg/keystone/options/options.go
  pkg/notify/models/notification.go
  pkg/notify/models/topic.go
Labels: size/XL

#17443 fix: add bind/unbind actions
  pkg/cloudcommon/db/opslog_const.go
Labels: size/XS

#17260 feat(climc): add container registry cmd for k8s service
  cmd/climc/shell/k8s/container_registry.go
  cmd/climc/shell/k8s/k8s.go
  pkg/mcclient/modules/k8s/container_registry.go
  pkg/mcclient/options/k8s/container_registry.go
Labels: size/L, area/climc

#17447 Automated cherry pick of #17260: feat(climc): add container registry cmd for k8s service
  cmd/climc/shell/k8s/container_registry.go
  cmd/climc/shell/k8s/k8s.go
  pkg/mcclient/modules/k8s/container_registry.go
  pkg/mcclient/options/k8s/container_registry.go
Labels: size/L

#17448 fix: allow set executor connection timeout
  go.mod
  go.sum
  pkg/cloudcommon/options/options.go
  pkg/hostman/host_health/service.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/image/service/service.go
  pkg/lbagent/service.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/executor/LICENSE
  vendor/yunion.io/x/executor/client/client.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
Labels: size/L

#17449 Automated cherry pick of #17448: fix: allow set executor connection timeout
  go.mod
  go.sum
  pkg/cloudcommon/options/options.go
  pkg/hostman/host_health/service.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/image/service/service.go
  pkg/lbagent/service.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/executor/LICENSE
  vendor/yunion.io/x/executor/client/client.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
Labels: size/L

#17446 Automated cherry pick of #17445: fix(webconsole): show exit msg for webconsole
  pkg/webconsole/server/ssh_server.go
Labels: size/XS

#17445 fix(webconsole): show exit msg for webconsole
  pkg/webconsole/server/ssh_server.go
Labels: size/XS, area/webconsole

#17455 fix(region): support aliyun pl0 storage
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/models/server_skus.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/L, area/region

#17459 fix: increase handler time if force_no_paging is on
  pkg/apigateway/handler/dispatcher.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/modelbase.go
Labels: size/S

#17460 Automated cherry pick of #17459: fix: increase handler time if force_no_paging is on
  pkg/apigateway/handler/dispatcher.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/modelbase.go
Labels: size/S

#17462 fix(host): lvm disk create from template
  pkg/hostman/storageman/disk_lvm.go
Labels: size/S

#17463 Automated cherry pick of #17462: fix(host): lvm disk create from template
  pkg/hostman/storageman/disk_lvm.go
Labels: size/S

#17472 fix(esxi-agent): reset password log
  pkg/hostman/storageman/storage_agent.go
Labels: size/S

#17473 Automated cherry pick of #17472: fix(esxi-agent): reset password log
  pkg/hostman/storageman/storage_agent.go
Labels: size/S

#17469 fix(region): default username
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/guestdrivers.go
Labels: size/S, area/region

#17470 Automated cherry pick of #17469: fix(region): default username
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/guestdrivers.go
Labels: size/S

#17471 Automated cherry pick of #17469: fix(region): default username
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/guestdrivers.go
Labels: size/S

#17486 fix: remove class lock in task
  pkg/cloudcommon/db/taskman/tasks.go
Labels: lgtm, size/S

#17487 Automated cherry pick of #17486: fix: remove class lock in task
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/S

#17482 feat(notify): add more config for webhook
  pkg/apis/notify/config.go
  pkg/apis/notify/robot.go
  pkg/mcclient/options/notify/robot.go
  pkg/notify/models/robot.go
  pkg/notify/sender/webhook.go
  pkg/notify/tasks/notifications_send_task.go
Labels: lgtm, size/M

#17488 Automated cherry pick of #17482: feat(notify): add more config for webhook
  pkg/apis/notify/config.go
  pkg/apis/notify/robot.go
  pkg/mcclient/options/notify/robot.go
  pkg/notify/models/robot.go
  pkg/notify/sender/webhook.go
  pkg/notify/tasks/notifications_send_task.go
Labels: size/M

#17483 fix: organization add node and level
  pkg/apis/identity/organization.go
  pkg/keystone/models/organizations.go
Labels: lgtm, size/S

#17494 fix(region): aliyun eip bgp pro
  go.mod
  go.sum
  pkg/apis/compute/elasticip.go
  pkg/mcclient/options/compute/eips.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sync.go
  vendor/yunion.io/x/sqlchemy/index.go
Labels: size/M, area/region

#17495 Automated cherry pick of #17494: fix(region): aliyun eip bgp pro
  go.mod
  go.sum
  pkg/apis/compute/elasticip.go
  pkg/mcclient/options/compute/eips.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/region.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sync.go
  vendor/yunion.io/x/sqlchemy/index.go
Labels: size/M

#17465 fix(region,host): qga command timeout
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/monitor/qga/qga.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#17476 fix(region): reset esxi osinfo
  pkg/compute/guestdrivers/esxi.go
Labels: size/M, area/region

#17478 Automated cherry pick of #17476: fix(region): reset esxi osinfo
  pkg/compute/guestdrivers/esxi.go
Labels: size/M

#17477 Automated cherry pick of #17476: fix(region): reset esxi osinfo
  pkg/compute/guestdrivers/esxi.go
Labels: size/M

#17479 fix(region): esxi vm migrate for search ivm
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/guests.go
Labels: size/M, area/region

#17480 Automated cherry pick of #17479: fix(region): esxi vm migrate for search ivm
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/guests.go
Labels: size/M

#17508 fix(host): qemu arm add qga params
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/XS

#17506 fix(region): account update for skip sync resources
  pkg/compute/models/cloudaccounts.go
Labels: size/S, area/region

#17507 Automated cherry pick of #17506: fix(region): account update for skip sync resources
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17505 fix fillStorage get storage cause scheduler panic
  pkg/scheduler/cache/candidate/base.go
Labels: size/XS

#17512 Automated cherry pick of #17505: fix fillStorage get storage cause scheduler panic
  pkg/scheduler/cache/candidate/base.go
Labels: size/XS

#17513 fix(climc): add port for ssh
  pkg/mcclient/options/compute/servers.go
Labels: size/XS, area/climc

#17515 Automated cherry pick of #17513: fix(climc): add port for ssh
  pkg/mcclient/options/compute/servers.go
Labels: size/XS

#17514 Automated cherry pick of #17513: fix(climc): add port for ssh
  pkg/mcclient/options/compute/servers.go
Labels: size/XS

#17517 fix(region): clean skip sync resources
  pkg/compute/models/cloudaccounts.go
Labels: size/XS, area/region

#17518 Automated cherry pick of #17517: fix(region): clean skip sync resources
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#17509 fix(region,scheduler): ovs offload support vpc network
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/isolated_device/nic.go
  pkg/scheduler/algorithm/predicates/network_predicate.go
Labels: size/M

#17519 fix(region): support filter by cloud_env for servertemplate
  pkg/compute/models/guest_template.go
Labels: size/S, area/region

#17520 Automated cherry pick of #17519: fix(region): support filter by cloud_env for servertemplate
  pkg/compute/models/guest_template.go
Labels: size/S

#17525 20230714 make mod
  go.mod
  go.sum
  pkg/mcclient/options/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/client/modules/manager_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/manager_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/nutanix.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/proxmox.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/parse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/parse.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sync.go
  vendor/yunion.io/x/sqlchemy/index.go
Labels: size/L

#17526 Automated cherry pick of #17525: 20230714 make mod
  go.mod
  go.sum
  pkg/mcclient/options/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/client/modules/manager_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/manager_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/nutanix.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/proxmox.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/parse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/parse.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sync.go
  vendor/yunion.io/x/sqlchemy/index.go
Labels: size/L

#17493 feat(climc): upload helm chart to a repository
  cmd/climc/shell/k8s/repos.go
  pkg/mcclient/modules/k8s/helm.go
  pkg/mcclient/options/k8s/repo.go
Labels: size/L, area/climc

#17511 Automated cherry pick of #17493: feat(climc): upload helm chart to a repository
  cmd/climc/shell/k8s/repos.go
  pkg/mcclient/modules/k8s/helm.go
  pkg/mcclient/options/k8s/repo.go
Labels: size/L

#17521 fix: lbcluster reference count
  pkg/apis/compute/loadbalancercluster.go
  pkg/compute/models/loadbalancerclusters.go
Labels: size/M

#17522 Automated cherry pick of #17521: fix: lbcluster reference count
  pkg/apis/compute/loadbalancercluster.go
  pkg/compute/models/loadbalancerclusters.go
Labels: size/M

#17524 Automated cherry pick of #17521: fix: lbcluster reference count
  pkg/apis/compute/loadbalancercluster.go
  pkg/compute/models/loadbalancerclusters.go
Labels: size/M

#17527 fix(host): find python path on guestman init
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
Labels: size/M

#17528 Automated cherry pick of #17527: fix(host): find python path on guestman init
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
Labels: size/M

#17550 fix(region): esxi disk with vmdk format
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS, area/region

#17551 Automated cherry pick of #17550: fix(region): esxi disk with vmdk format
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS

#17554 Automated cherry pick of #17547: fix(host): telegraf ignore hugetlbfs
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#17547 fix(host): telegraf ignore hugetlbfs
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#17534 fix(region): server eip bgp type
  pkg/compute/models/elasticips.go
Labels: size/XS, area/region

#17535 Automated cherry pick of #17534: fix(region): server eip bgp type
  pkg/compute/models/elasticips.go
Labels: size/XS

#17453 fix(common): add resource translate
  pkg/cloudcommon/consts/resource_translate.go
Labels: size/XL

#17549 Automated cherry pick of #17548: fix(region): skip sync resource when account created
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17564 fix(region): esxi add vmdk disk
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS, area/region

#17566 Automated cherry pick of #17564: fix(region): esxi add vmdk disk
  pkg/compute/guestdrivers/esxi.go
Labels: size/XS

#17561 fix: node description update
  pkg/apis/identity/organization.go
  pkg/keystone/models/organization_nodes.go
  pkg/keystone/models/organizations.go
Labels: size/M

#17567 fix: disable application profiling by default
  pkg/apis/identity/consts.go
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlers.go
  pkg/appsrv/send.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#17568 Automated cherry pick of #17567: fix: disable application profiling by default
  pkg/apis/identity/consts.go
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlers.go
  pkg/appsrv/send.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#17574 fix(monitor): return error if metric is nil
  pkg/monitor/controller/balancer/balancer.go
  pkg/monitor/controller/balancer/cpu.go
Labels: size/S, area/monitor

#17575 Automated cherry pick of #17574: fix(monitor): return error if metric is nil
  pkg/monitor/controller/balancer/balancer.go
  pkg/monitor/controller/balancer/cpu.go
Labels: size/S

#17576 Automated cherry pick of #17574: fix(monitor): return error if metric is nil
  pkg/monitor/controller/balancer/balancer.go
  pkg/monitor/controller/balancer/cpu.go
Labels: size/S

#17580 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M, area/region

#17581 Automated cherry pick of #17580: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M

#17584 feat(climc): support download helm chart
  cmd/climc/shell/k8s/repos.go
  pkg/mcclient/modules/k8s/helm.go
Labels: size/M, area/climc

#17585 Automated cherry pick of #17584: feat(climc): support download helm chart
  cmd/climc/shell/k8s/repos.go
  pkg/mcclient/modules/k8s/helm.go
Labels: size/M

#17559 fix(region): server sku update attribute
  pkg/compute/models/server_skus.go
Labels: size/L, area/region

#17560 Automated cherry pick of #17559: fix(region): server sku update attribute
  pkg/compute/models/server_skus.go
Labels: size/L

#17582 fix(region): qga ping don't report error on host return error
  pkg/compute/models/qemu_guest_agent.go
Labels: size/XS

#17583 Automated cherry pick of #17582: fix(region): qga ping don't report error on host return error
  pkg/compute/models/qemu_guest_agent.go
Labels: size/XS

#17579 fix: update organization node may clear description
  pkg/keystone/models/organization_nodes.go
  pkg/mcclient/options/identity/organization_nodes.go
Labels: size/S

#17587 feat(climc): support download container image
  cmd/climc/shell/k8s/container_registry.go
  pkg/mcclient/modules/k8s/container_registry.go
Labels: size/M, area/climc

#17588 Automated cherry pick of #17587: feat(climc): support download container image
  cmd/climc/shell/k8s/container_registry.go
  pkg/mcclient/modules/k8s/container_registry.go
Labels: size/M

#17592 feat(region): aws redis create
  cmd/climc/shell/compute/elasticache_skus.go
  cmd/climc/shell/compute/elasticcache.go
  go.mod
  go.sum
  pkg/apis/compute/api.go
  pkg/compute/regiondrivers/aws.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/mcclient/options/compute/elasticache.go
  pkg/mcclient/options/elasticcache.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/api.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/doc.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/errors.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/service.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/waiters.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_instancetype.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_memcached.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_parameter.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/XXL

#17589 fix: update vmware credential with host
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#17590 Automated cherry pick of #17589: fix: update vmware credential with host
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#17591 feat(region): allow auto create project for provider
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/S

#17605 Automated cherry pick of #17591: feat(region): allow auto create project for provider
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/S

#17602 fix(region): usage for nic
  pkg/compute/models/wires.go
Labels: size/XS, area/region

#17603 Automated cherry pick of #17602: fix(region): usage for nic
  pkg/compute/models/wires.go
Labels: size/XS

#17604 Automated cherry pick of #17602: fix(region): usage for nic
  pkg/compute/models/wires.go
Labels: size/XS

#17597 fix(webconsole): ssh command record
  pkg/webconsole/handlers.go
  pkg/webconsole/server/ssh_server.go
  pkg/webconsole/session/ssh_session.go
Labels: size/S, area/webconsole

#17606 fix(region): set scheduler failed brand unknown
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
Labels: size/S, area/region

#17607 Automated cherry pick of #17606: fix(region): set scheduler failed brand unknown
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
Labels: size/S

#17608 Automated cherry pick of #17606: fix(region): set scheduler failed brand unknown
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
Labels: size/S

#17615 fix(webconsole): msg write
  cmd/climc/shell/compute/webconsole.go
  pkg/webconsole/server/ssh_server.go
  pkg/webconsole/session/ssh_session.go
Labels: size/M, area/webconsole

#17616 Automated cherry pick of #17615: fix(webconsole): msg write
  cmd/climc/shell/compute/webconsole.go
  pkg/webconsole/server/ssh_server.go
  pkg/webconsole/session/ssh_session.go
Labels: size/M

#17617 fix(host): try reloading telegraf by restarting docker
  pkg/hostman/system_service/telegraf.go
Labels: lgtm, size/M, area/host

#17618 Automated cherry pick of #17617: fix(host): try reloading telegraf by restarting docker
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#17619 Automated cherry pick of #17617: fix(host): try reloading telegraf by restarting docker
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#17620 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnshostedzone.go
Labels: size/S, area/region

#17621 Automated cherry pick of #17620: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnshostedzone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#17622 Automated cherry pick of #17620: fix(region): vendor update
  go.sum
  pkg/multicloud/aws/dnshostedzone.go
Labels: size/XS

#17624 Automated cherry pick of #17623: fix(region): auto create project for provider BUG FIX
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17623 fix(region): auto create project for provider BUG FIX
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17625 fix(region): fix autoCreateProjectForProvider bug
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#17629 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/networkinterfaces.go
Labels: size/M, area/region

#17630 Automated cherry pick of #17629: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/networkinterfaces.go
Labels: size/M

#17631 Automated cherry pick of #17629: fix(region): vendor update
  pkg/multicloud/aliyun/networkinterfaces.go
  pkg/multicloud/aliyun/shell/networkinterface.go
Labels: size/M

#17627 fix(notify): alert send
  pkg/mcclient/options/notify/robot.go
  pkg/notify/models/config.go
  pkg/notify/models/emailqueue.go
  pkg/notify/models/notification.go
  pkg/notify/models/plugindriver.go
  pkg/notify/models/robot.go
  pkg/notify/models/template.go
  pkg/notify/sender/dingtalk.go
  pkg/notify/sender/dingtalk_robot.go
  pkg/notify/sender/email.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/feishu_robot.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/utils.go
  pkg/notify/sender/webconsole.go
  pkg/notify/sender/webhook.go
  pkg/notify/sender/websocket.go
  pkg/notify/sender/workwx.go
  pkg/notify/sender/workwx_robot.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/subcontact_pull_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/L

#17634 Automated cherry pick of #17627: fix(notify): alert send
  pkg/mcclient/options/notify/robot.go
  pkg/notify/models/config.go
  pkg/notify/models/emailqueue.go
  pkg/notify/models/notification.go
  pkg/notify/models/plugindriver.go
  pkg/notify/models/robot.go
  pkg/notify/models/template.go
  pkg/notify/sender/dingtalk.go
  pkg/notify/sender/dingtalk_robot.go
  pkg/notify/sender/email.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/feishu_robot.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/utils.go
  pkg/notify/sender/webconsole.go
  pkg/notify/sender/webhook.go
  pkg/notify/sender/websocket.go
  pkg/notify/sender/workwx.go
  pkg/notify/sender/workwx_robot.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/subcontact_pull_task.go
  pkg/notify/tasks/topic_message_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/XL

#17644 fix(region): balance currency
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/cloudpods/provider/provider.go
  pkg/mcclient/options/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/L, area/region

#17645 Automated cherry pick of #17644: fix(region): balance currency
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/cloudpods/provider/provider.go
  pkg/mcclient/options/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/L

#17642 Automated cherry pick of #17641: fix(scheduler): auto allocation network selection is not working
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
Labels: size/XS

#17643 Automated cherry pick of #17641: fix(scheduler): auto allocation network selection is not working
  pkg/scheduler/algorithm/predicates/network_schedtag_predicate.go
Labels: size/XS

#17635 fix(host-deployer): detect image arch incorrect
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#17636 Automated cherry pick of #17635: fix(host-deployer): detect image arch incorrect
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#17638 Automated cherry pick of #17635: fix(host-deployer): detect image arch incorrect
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#17637 fix(region): purge account
  cmd/climc/shell/compute/cloudregions.go
  cmd/climc/shell/compute/dbinstance_skus.go
  cmd/climc/shell/compute/elasticache_skus.go
  cmd/climc/shell/compute/elasticcache.go
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/nas_sku.go
  cmd/climc/shell/compute/nat_sku.go
  cmd/climc/shell/compute/skus.go
  cmd/climc/shell/compute/zones.go
  pkg/apis/compute/cloudregion.go
  pkg/apis/compute/zone.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstance_databases.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/networkinterfaces.go
  pkg/compute/models/purge.go
  pkg/compute/models/storages.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_delete_task.go
  pkg/compute/tasks/dbinstance_account_delete_task.go
  pkg/compute/tasks/dbinstance_database_delete_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/compute/tasks/vpc_delete_task.go
  pkg/mcclient/options/compute/region.go
  pkg/mcclient/options/compute/zone.go
Labels: size/XXL, area/region

#17647 Automated cherry pick of #17637: fix(region): purge account
  cmd/climc/shell/compute/cloudregions.go
  cmd/climc/shell/compute/dbinstance_skus.go
  cmd/climc/shell/compute/elasticcache.go
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/nas_sku.go
  cmd/climc/shell/compute/nat_sku.go
  cmd/climc/shell/compute/skus.go
  cmd/climc/shell/compute/zones.go
  pkg/apis/compute/cloudregion.go
  pkg/apis/compute/zone.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/dbinstance_accounts.go
  pkg/compute/models/dbinstance_databases.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/disks.go
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/natgateways.go
  pkg/compute/models/networkinterfaces.go
  pkg/compute/models/purge.go
  pkg/compute/models/storages.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/zones.go
  pkg/compute/tasks/cloud_account_delete_task.go
  pkg/compute/tasks/dbinstance_account_delete_task.go
  pkg/compute/tasks/dbinstance_database_delete_task.go
  pkg/compute/tasks/dbinstance_delete_task.go
  pkg/compute/tasks/natdentry_delete_task.go
  pkg/compute/tasks/natsentry_delete_task.go
  pkg/compute/tasks/vpc_delete_task.go
  pkg/mcclient/options/compute/region.go
  pkg/mcclient/options/compute/zone.go
Labels: size/XXL

#17660 Automated cherry pick of #17659: feat(cloudmon): upload meter currency of the cloudaccount
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/identity/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/cloudmon/resources/resources.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/cloudpods/sku.go
  pkg/mcclient/modules/compute/mod_cloudaccounts.go
Labels: size/M

#17659 feat(cloudmon): upload meter currency of the cloudaccount
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/cloudmon/resources/resources.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/cloudpods/sku.go
  pkg/mcclient/modules/compute/mod_cloudaccounts.go
Labels: size/M, area/cloudmon

#17661 fix(region): server sku update
  pkg/compute/models/server_skus.go
Labels: size/XS, area/region

#17662 Automated cherry pick of #17661: fix(region): server sku update
  pkg/compute/models/server_skus.go
Labels: size/XS

#17657 fix(region): ecs sync options
  pkg/compute/options/options.go
Labels: size/XS, area/region

#17658 Automated cherry pick of #17657: fix(region): ecs sync options
  pkg/compute/options/options.go
Labels: size/XS

#17655 fix(keystone): enable cloud shell
  pkg/apis/identity/consts.go
Labels: size/XS, area/keystone

#17656 Automated cherry pick of #17655: fix(keystone): enable cloud shell
  pkg/apis/identity/consts.go
Labels: size/XS

#17653 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/securitygroup.go
Labels: size/S, area/region

#17654 Automated cherry pick of #17653: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/securitygroup.go
Labels: size/S

#17665 fix(region): acl name
  pkg/compute/models/loadbalancercachedacls.go
Labels: size/XS, area/region

#17667 Automated cherry pick of #17665: fix(region): acl name
  pkg/compute/models/loadbalancercachedacls.go
Labels: size/XS

#17666 Automated cherry pick of #17665: fix(region): acl name
  pkg/compute/models/loadbalancercachedacls.go
Labels: size/XS

#17632 fix(host): storages bind mount should before host register
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nfs.go
Labels: size/M

#17633 Automated cherry pick of #17632: fix(host): storages bind mount should before host register
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_nfs.go
Labels: size/M

#17650 fix(notify): drop event notification default receiver
  pkg/notify/models/notification.go
Labels: size/XS

#17651 Automated cherry pick of #17650: fix(notify): drop event notification default receiver
  pkg/notify/models/notification.go
Labels: size/XS

#17649 fix(region): optimized cloud-account-list
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
Labels: size/L, area/region

#17652 Automated cherry pick of #17649: fix(region): optimized cloud-account-list
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudaccounts.go
Labels: size/L

#17679 fix(region): vendor update
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/service/pricing/api.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/doc.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/errors.go
  vendor/github.com/aws/aws-sdk-go/service/pricing/service.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_invoke.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/product.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/sku.go
Labels: size/XXL, area/region

#17680 Automated cherry pick of #17679: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
Labels: size/S

#17677 fix(region): account details
  pkg/compute/models/cloudaccounts.go
Labels: size/S, area/region

#17678 Automated cherry pick of #17677: fix(region): account details
  pkg/compute/models/cloudaccounts.go
Labels: size/S

#17681 fix(webconsole,climc): cloud shell within docker compose environment
  build/climc/root/opt/climc-entrypoint.sh
  build/climc/root/opt/yunion/scripts/motd/climc.sh
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
  build/docker/Dockerfile.webconsole
  build/docker/Makefile
  build/docker/climc-entrypoint.sh
  cmd/climc/shell/compute/sshkeypairs.go
  pkg/mcclient/modules/webconsole/mod_webconsole.go
  pkg/mcclient/options/webconsole.go
  pkg/webconsole/command/climc_ssh_command.go
  pkg/webconsole/command/socat_command.go
  pkg/webconsole/handlers.go
  pkg/webconsole/helper/doc.go
  pkg/webconsole/helper/helper.go
  pkg/webconsole/session/session.go
  pkg/webconsole/session/ssh_session.go
Labels: area/webconsole, size/XL, area/climc, area/apigateway

#17682 Automated cherry pick of #17681: fix(webconsole,climc): cloud shell within docker compose environment
  build/climc/root/opt/climc-entrypoint.sh
  build/climc/root/opt/yunion/scripts/motd/climc.sh
  build/docker/Dockerfile.climc
  build/docker/Dockerfile.climc-base
  build/docker/Dockerfile.webconsole
  build/docker/Makefile
  build/docker/climc-entrypoint.sh
  cmd/climc/shell/compute/sshkeypairs.go
  pkg/mcclient/modules/webconsole/mod_webconsole.go
  pkg/mcclient/options/webconsole.go
  pkg/webconsole/command/climc_ssh_command.go
  pkg/webconsole/command/socat_command.go
  pkg/webconsole/handlers.go
  pkg/webconsole/helper/doc.go
  pkg/webconsole/helper/helper.go
  pkg/webconsole/session/session.go
  pkg/webconsole/session/ssh_session.go
Labels: size/XL

#17675 Automated cherry pick of #17674: fix(host): add gpu device when driver isn't bind
  pkg/hostman/isolated_device/gpu.go
Labels: size/XS

#17676 Automated cherry pick of #17674: fix(host): add gpu device when driver isn't bind
  pkg/hostman/isolated_device/gpu.go
Labels: size/XS

#17672 fix(region): optional local system disk size
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/options/options.go
Labels: size/XS, area/region
