Repository yunionio/cloudpods, pull requests merged in 2023-10, with the labels that each got.

#18180 fix: add apis for logininfo
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_logininfo.go
Labels: size/L

#18181 Automated cherry pick of #18180: fix: add apis for logininfo
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_logininfo.go
Labels: size/L

#18182 Automated cherry pick of #18180: fix: add apis for logininfo
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_logininfo.go
Labels: size/L

#18184 fix: host nics api
  cmd/climc/shell/compute/hosts.go
  pkg/compute/models/host_nics.go
Labels: size/M

#18185 Automated cherry pick of #18184: fix: host nics api
  cmd/climc/shell/compute/hosts.go
  pkg/compute/models/host_nics.go
Labels: size/M

#18186 Automated cherry pick of #18184: fix: host nics api
  cmd/climc/shell/compute/hosts.go
  pkg/compute/models/host_nics.go
Labels: size/M

#18187 fix: rebuild root support deploy params
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/L

#18188 Automated cherry pick of #18187: fix: rebuild root support deploy params
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/L

#18189 Automated cherry pick of #18187: fix: rebuild root support deploy params
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_batch_create_task.go
  pkg/compute/tasks/guest_rebuild_root_task.go
Labels: size/L

#18191 feat(actions): add issue actions
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-comment.yml
  .github/workflows/issue-open.yml
  .github/workflows/issues.yml
Labels: size/L

#18194 fix(actions): support /keep-state command
  .github/workflows/issue-comment.yml
Labels: area/util

#18183 feature: SUSE guest support
  build/docker/Dockerfile.host-deployer
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/suse.go
  pkg/hostman/guestfs/fsdriver/userdata.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/util/btrfsutils/btrfsutils.go
  pkg/util/btrfsutils/btrfsutils_test.go
  pkg/util/btrfsutils/doc.go
Labels: size/XL

#18190 Automated cherry pick of #18183: feature: SUSE guest support
  build/docker/Dockerfile.host-deployer
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/suse.go
  pkg/hostman/guestfs/fsdriver/userdata.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestfs/kvmpart/localfs.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/util/btrfsutils/btrfsutils.go
  pkg/util/btrfsutils/btrfsutils_test.go
  pkg/util/btrfsutils/doc.go
Labels: size/XL

#18199 feature: invalidate auth token
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/usrext.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/oauth2/oauth2.go
  pkg/keystone/driver/oidc/oidc.go
  pkg/keystone/driver/saml/saml.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/tokencache.go
  pkg/keystone/models/users.go
  pkg/keystone/service/handlers.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/invalidate.go
  pkg/keystone/tokens/payloads.go
  pkg/mcclient/auth/auth.go
  pkg/mcclient/mcclient.go
Labels: size/XL

#18200 Automated cherry pick of #18199: feature: invalidate auth token
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/usrext.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/oauth2/oauth2.go
  pkg/keystone/driver/oidc/oidc.go
  pkg/keystone/driver/saml/saml.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/tokencache.go
  pkg/keystone/models/users.go
  pkg/keystone/service/handlers.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/invalidate.go
  pkg/keystone/tokens/payloads.go
  pkg/mcclient/auth/auth.go
  pkg/mcclient/mcclient.go
Labels: size/XL

#18201 Automated cherry pick of #18199: feature: invalidate auth token
  pkg/apigateway/handler/auth.go
  pkg/apis/identity/usrext.go
  pkg/keystone/driver/cas/cas.go
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/oauth2/oauth2.go
  pkg/keystone/driver/oidc/oidc.go
  pkg/keystone/driver/saml/saml.go
  pkg/keystone/driver/sql/sql.go
  pkg/keystone/models/credentials.go
  pkg/keystone/models/tokencache.go
  pkg/keystone/models/users.go
  pkg/keystone/service/handlers.go
  pkg/keystone/service/service.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/invalidate.go
  pkg/keystone/tokens/payloads.go
  pkg/mcclient/auth/auth.go
  pkg/mcclient/mcclient.go
Labels: size/XL

#18204 fix: async refresh revoked tokens
  pkg/mcclient/auth/auth.go
Labels: size/XS

#18205 Automated cherry pick of #18204: fix: async refresh revoked tokens
  pkg/mcclient/auth/auth.go
Labels: size/XS

#18206 Automated cherry pick of #18204: fix: async refresh revoked tokens
  pkg/mcclient/auth/auth.go
Labels: size/XS

#18207 feat(region,glance): from cloudaccount to enable vmdk target format
  pkg/compute/models/cloudaccounts.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#18208 Automated cherry pick of #18207: feat(region,glance): from cloudaccount to enable vmdk target format
  pkg/compute/models/cloudaccounts.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#18209 Automated cherry pick of #18207: feat(region,glance): from cloudaccount to enable vmdk target format
  pkg/compute/models/cloudaccounts.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#18210 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
Labels: size/L, area/region

#18212 Automated cherry pick of #18210: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
Labels: size/L

#18219 feat: support policy and cors for bucket
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/storageaccount.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/auth.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/authV2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/authV4.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/callback.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_part.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_resume.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/conf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/convert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/doc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/extension.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/http.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/log.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/mime.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_header.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_part.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_response.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary_createSignedUrl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary_signedUrl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_part.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/transfer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/type.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/util.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/shell.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/XXL

#18220 Automated cherry pick of #18219: feat: support policy and cors for bucket
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/storageaccount.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/auth.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/authV2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/authV4.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/callback.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_part.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/client_resume.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/conf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/convert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/doc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/extension.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/http.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/log.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/mime.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_header.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_part.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/model_response.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary_createSignedUrl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/temporary_signedUrl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_object.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_other.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/trait_part.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/transfer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/type.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/obs/util.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/shell.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/XXL

#18217 fix(region): avoid panic when create aws vm
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/M

#18228 Automated cherry pick of #18226: fix: missing invalid token response
  pkg/keystone/tokens/invalidate.go
Labels: size/S

#18227 Automated cherry pick of #18226: fix: missing invalid token response
  pkg/keystone/tokens/invalidate.go
Labels: size/S

#18226 fix: missing invalid token response
  pkg/keystone/tokens/invalidate.go
Labels: size/S

#18229 fix: unauthorized error should return 401
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/token.go
Labels: size/M

#18231 Automated cherry pick of #18229: fix: unauthorized error should return 401
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/token.go
Labels: size/M

#18230 Automated cherry pick of #18229: fix: unauthorized error should return 401
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/token.go
Labels: size/M

#18232 fix: handle old style auth token
  pkg/apis/identity/consts.go
  pkg/keystone/cache/cache.go
  pkg/keystone/models/tokencache.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/invalidate.go
  pkg/keystone/tokens/token.go
  pkg/keystone/tokens/verify.go
Labels: size/L

#18233 Automated cherry pick of #18232: fix: handle old style auth token
  pkg/apis/identity/consts.go
  pkg/keystone/cache/cache.go
  pkg/keystone/models/tokencache.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/invalidate.go
  pkg/keystone/tokens/token.go
  pkg/keystone/tokens/verify.go
Labels: size/L

#18234 Automated cherry pick of #18232: fix: handle old style auth token
  pkg/apis/identity/consts.go
  pkg/keystone/cache/cache.go
  pkg/keystone/models/tokencache.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/errors.go
  pkg/keystone/tokens/handlers.go
  pkg/keystone/tokens/invalidate.go
  pkg/keystone/tokens/token.go
  pkg/keystone/tokens/verify.go
Labels: size/L

#18235 fix(host-deployer): deploy qga conf ensure /etc/sysconfig dir
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#18236 Automated cherry pick of #18235: fix(host-deployer): deploy qga conf ensure /etc/sysconfig dir
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#18237 Automated cherry pick of #18235: fix(host-deployer): deploy qga conf ensure /etc/sysconfig dir
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#18238 Automated cherry pick of #18235: fix(host-deployer): deploy qga conf ensure /etc/sysconfig dir
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#18239 fix(host): host sysinfo metadata double quota
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#18240 Automated cherry pick of #18239: fix(host): host sysinfo metadata double quota
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#18241 Automated cherry pick of #18239: fix(host): host sysinfo metadata double quota
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#18243 fix: allow specify desktop linux os that not allow root login
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/guestfs/fsdriver/fangde.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/neokylin.go
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/M

#18246 fix(monitor): select host that isn't in source hosts as target
  pkg/monitor/controller/balancer/balancer.go
  pkg/monitor/controller/balancer/cpu.go
  pkg/monitor/controller/balancer/mem.go
Labels: size/M, area/monitor

#18247 Automated cherry pick of #18246: fix(monitor): select host that isn't in source hosts as target
  pkg/monitor/controller/balancer/balancer.go
  pkg/monitor/controller/balancer/cpu.go
  pkg/monitor/controller/balancer/mem.go
Labels: size/M

#18251 Automated cherry pick of #18250: fix: guest start params revisit
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_start_task.go
Labels: size/M

#18252 Automated cherry pick of #18250: fix: guest start params revisit
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/guest_start_task.go
Labels: size/M

#18261 fix(region): wait vm deleted
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS, area/region

#18256 Automated cherry pick of #18254: feat(region): filter server ip_addrs by REGEXP
  go.mod
  go.sum
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/filter.go
Labels: size/M

#18262 Automated cherry pick of #18261: fix(region): wait vm deleted
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#18254 feat(region): filter server ip_addrs by REGEXP
  go.mod
  go.sum
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/filter.go
Labels: size/M, area/region

#18263 Automated cherry pick of #18261: fix(region): wait vm deleted
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS

#18264 fix(region): dns record cname check
  pkg/apis/compute/dnsrecord.go
  pkg/apis/compute/dnsrecordsets.go
  pkg/apis/compute/input.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/models/dnsrecords.go
Labels: size/L, area/region

#18265 Automated cherry pick of #18264: fix(region): dns record cname check
  pkg/apis/compute/dnsrecord.go
  pkg/apis/compute/dnsrecordsets.go
  pkg/apis/compute/input.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/models/dnsrecords.go
Labels: size/L

#18269 fix(host-deployer): update host-deployer base image
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#18271 fix(host): check qga connect is closed
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#18272 Automated cherry pick of #18271: fix(host): check qga connect is closed
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#18273 Automated cherry pick of #18271: fix(host): check qga connect is closed
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#18274 Automated cherry pick of #18271: fix(host): check qga connect is closed
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#18275 fix(region): use project sshkeypair to ssh vm
  pkg/compute/sshkeys/handler.go
  pkg/webconsole/helper/helper.go
Labels: size/XS, area/region

#18277 Automated cherry pick of #18275: fix(region): use project sshkeypair to ssh vm
  pkg/compute/sshkeys/handler.go
  pkg/webconsole/helper/helper.go
Labels: size/XS

#18267 feat(notify): support db_dispatcher notify
  pkg/apis/notify/template.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/notify_hook.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/hosts.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
Labels: size/M

#18279 Automated cherry pick of #18267: feat(notify): support db_dispatcher notify
  pkg/apis/notify/template.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/notify_hook.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/hosts.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
Labels: size/M

#18280 Automated cherry pick of #18267: feat(notify): support db_dispatcher notify
  pkg/apis/notify/template.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/notify_hook.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/compute/models/hosts.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
Labels: size/M

#18216 fix(region): history usage
  cmd/climc/shell/compute/usages.go
  pkg/compute/service/handlers.go
  pkg/compute/usages/handler.go
  pkg/compute/usages/history.go
  pkg/mcclient/modules/compute/mod_usages.go
Labels: size/L, area/region

#18260 Automated cherry pick of #18216: fix(region): history usage
  cmd/climc/shell/compute/usages.go
  pkg/compute/service/handlers.go
  pkg/compute/usages/handler.go
  pkg/compute/usages/history.go
  pkg/mcclient/modules/compute/mod_usages.go
Labels: size/L

#18281 fix: update vendor 20231012 for sqlchemy
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
Labels: size/M

#18287 Automated cherry pick of #18281: fix: update vendor 20231012 for sqlchemy
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/const.go
  vendor/yunion.io/x/sqlchemy/filter.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: size/L

#18283 Automated cherry pick of #18281: fix: update vendor 20231012 for sqlchemy
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
Labels: size/M

#18282 Automated cherry pick of #18281: fix: update vendor 20231012 for sqlchemy
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/sqlchemy/backends/mysql/sync.go
Labels: size/M

#18290 Automated cherry pick of #18278: fix(region): aws userdata error fix
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudgroup.go
Labels: size/S

#18292 fix(region): remove ctyun useless env paramenter
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/provider/provider.go
Labels: size/S, area/region

#18293 Automated cherry pick of #18292: fix(region): remove ctyun useless env paramenter
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/provider/provider.go
Labels: size/S

#18301 fix(region): avoid ctyun signature verification failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
Labels: area/region

#18302 Automated cherry pick of #18301: fix(region): avoid ctyun signature verification failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
Labels: size/S

#18303 Automated cherry pick of #18301: fix(region): avoid ctyun signature verification failed
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
Labels: size/S

#18305 Automated cherry pick of #18304: fix(region): classify invalid access key error
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
Labels: size/S

#18306 Automated cherry pick of #18304: fix(region): classify invalid access key error
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
Labels: size/S

#18295 fix: climc server-logininfo action
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
Labels: size/XS

#18296 Automated cherry pick of #18295: fix: climc server-logininfo action
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
Labels: size/XS

#18297 Automated cherry pick of #18295: fix: climc server-logininfo action
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
Labels: size/XS

#18308 fix: update vendor for edito retry
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/shellutils/edit.go
Labels: size/M

#18309 Automated cherry pick of #18308: fix: update vendor for edito retry
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/shellutils/edit.go
Labels: size/M

#18310 Automated cherry pick of #18308: fix: update vendor for edito retry
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/shellutils/edit.go
Labels: size/M

#18311 Automated cherry pick of #18308: fix: update vendor for edito retry
  go.mod
  go.sum
  pkg/util/shellutils/edit.go
  vendor/modules.txt
Labels: size/M

#18285 Automated cherry pick of #18284: fix(keystone): policy result
  pkg/util/rbacutils/results.go
Labels: size/S

#18286 Automated cherry pick of #18284: fix(keystone): policy result
  pkg/util/rbacutils/results.go
Labels: size/S

#18288 fix(region): show network details with dns
  pkg/apis/compute/network.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/netinterfaces.go
  pkg/compute/models/networks.go
Labels: size/S, area/region

#18289 Automated cherry pick of #18288: fix(region): show network details with dns
  pkg/apis/compute/network.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/netinterfaces.go
  pkg/compute/models/networks.go
Labels: size/S

#18312 Automated cherry pick of #17334: fix(common): remove service default policy
  pkg/cloudid/policy/defaults.go
  pkg/compute/policy/defaults.go
  pkg/image/policy/defaults.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/options/options.go
  pkg/logger/policy/defaults.go
  pkg/notify/policy/defaults.go
  pkg/yunionconf/policy/defaults.go
Labels: size/XXL

#17334 fix(common): remove service default policy
  pkg/cloudid/policy/defaults.go
  pkg/compute/policy/defaults.go
  pkg/image/policy/defaults.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/options/options.go
  pkg/logger/policy/defaults.go
  pkg/notify/policy/defaults.go
  pkg/yunionconf/policy/defaults.go
Labels: size/XXL

#18315 fix(README): stale image links
  README-CN.md
  README.md
Labels: size/L

#18316 fix(common): distinguish system and user log by is_system_account
  pkg/keystone/models/default_admin.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/tokensimple.go
Labels: size/S, area/region

#18317 Automated cherry pick of #18316: fix(common): distinguish system and user log by is_system_account
  pkg/keystone/models/default_admin.go
  pkg/keystone/tokens/token.go
  pkg/mcclient/tokensimple.go
Labels: size/S

#18320 fix(notify): fix role subscriber groupTimes
  pkg/notify/models/subscriber.go
Labels: size/S

#18325 fix(scheduler): isolated device predicate miss sriov nic
  pkg/scheduler/algorithm/predicates/isolated_device_predicate.go
Labels: size/S

#18326 Automated cherry pick of #18325: fix(scheduler): isolated device predicate miss sriov nic
  pkg/scheduler/algorithm/predicates/isolated_device_predicate.go
Labels: size/S

#18327 Automated cherry pick of #18325: fix(scheduler): isolated device predicate miss sriov nic
  pkg/scheduler/algorithm/predicates/isolated_device_predicate.go
Labels: size/S

#18323 Automated cherry pick of #18320: fix(notify): fix role subscriber groupTimes
  pkg/notify/models/subscriber.go
Labels: size/S

#18324 Automated cherry pick of #18320: fix(notify): fix role subscriber groupTimes
  pkg/notify/models/subscriber.go
Labels: size/S

#18299 fix(region): standardization stage name
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/tasks/baremetal_convert_hypervisor_task.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/compute/tasks/guest_attach_disk_task.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_detach_all_disks_task.go
  pkg/compute/tasks/guest_save_instance_image_task.go
  pkg/compute/tasks/guest_sync_task.go
Labels: size/M, area/region

#18338 fix(climc): 避免climc交互模式下--help自动退出
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/S, area/climc

#18339 Automated cherry pick of #18338: fix(climc): 避免climc交互模式下--help自动退出
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/S

#18340 Automated cherry pick of #18338: fix(climc): 避免climc交互模式下--help自动退出
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/structarg/structarg.go
Labels: size/S

#18342 fix: unable to recognize anolis os
  pkg/hostman/guestfs/fsdriver/anolis.go
Labels: size/XS

#18344 Automated cherry pick of #18342: fix: unable to recognize anolis os
  pkg/hostman/guestfs/fsdriver/anolis.go
Labels: size/XS

#18345 Automated cherry pick of #18342: fix: unable to recognize anolis os
  pkg/hostman/guestfs/fsdriver/anolis.go
Labels: size/XS

#18351 fix: docgengo
  cmd/climc/shell/compute/network_ip_mac.go
  cmd/host-health/main.go
  cmd/scheduledtask/main.go
  pkg/apis/identity/organization_test.go
  pkg/apis/websocket/const.go
  pkg/cloudcommon/consts/resource_translate.go
  pkg/compute/guestdrivers/volcengine.go
  pkg/compute/hostdrivers/volcengine.go
  pkg/compute/models/network_ip_mac.go
  pkg/compute/regiondrivers/volcengine.go
  pkg/devtool/utils/gen_telegraf_conf.go
  pkg/devtool/utils/gen_telegraf_conf_test.go
  pkg/hostman/host_health/service.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/sriov_base.go
  pkg/hostman/isolated_device/sriov_vgpu.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_nvme.go
  pkg/hostman/storageman/imagecache_lvm.go
  pkg/hostman/storageman/imagecachemanager_lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_nvme.go
  pkg/keystone/cache/doc.go
  pkg/keystone/driver/oauth2/bingoiam/sync.go
  pkg/mcclient/modules/compute/mod_network_ip_macs.go
  pkg/mcclient/modules/websocket/doc.go
  pkg/mcclient/modules/websocket/managers.go
  pkg/mcclient/modules/websocket/register.go
  pkg/notify/sender/smsdriver/const.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/analysor_test.go
  pkg/scheduler/data_manager/cloudaccount/cloudaccount.go
  pkg/scheduler/data_manager/cloudaccount/doc.go
  pkg/scheduler/data_manager/cloudprovider/cloudprovider.go
  pkg/scheduler/data_manager/cloudprovider/doc.go
  pkg/scheduler/data_manager/cloudregion/cloudregion.go
  pkg/scheduler/data_manager/cloudregion/doc.go
  pkg/scheduler/data_manager/common/common.go
  pkg/scheduler/data_manager/common/doc.go
  pkg/scheduler/data_manager/netinterface/doc.go
  pkg/scheduler/data_manager/netinterface/netinterface.go
  pkg/scheduler/data_manager/network/doc.go
  pkg/scheduler/data_manager/network/network.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/doc.go
  pkg/scheduler/data_manager/schedtag/schedtag.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/data_manager/wire/doc.go
  pkg/scheduler/data_manager/wire/wire.go
  pkg/scheduler/data_manager/zone/doc.go
  pkg/scheduler/data_manager/zone/zone.go
  pkg/util/yunionmeta/doc.go
  pkg/webconsole/helper/doc.go
  scripts/gencopyright.sh
Labels: size/XL

#18355 Automated cherry pick of #18352: fix: missing project mapping body
  pkg/apis/compute/project_mappings.go
Labels: size/XS

#18353 Automated cherry pick of #18352: fix: missing project mapping body
  pkg/apis/compute/project_mappings.go
Labels: size/XS

#18352 fix: missing project mapping body
  pkg/apis/compute/project_mappings.go
Labels: size/XS

#18337 Automated cherry pick of #17955: fix(host): host register skip infiniband nic
  pkg/util/sysutils/nics.go
Labels: size/XS

#18329 fix(host-deployer): change netdev prefix to "en" on nics has differen…
  pkg/baremetal/agent.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
Labels: size/M

#18330 Automated cherry pick of #18329: fix(host-deployer): change netdev prefix to "en" on nics has differen…
  pkg/baremetal/agent.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
Labels: size/M

#18331 Automated cherry pick of #18329: fix(host-deployer): change netdev prefix to "en" on nics has differen…
  pkg/baremetal/agent.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
Labels: size/M

#18318 fix: allow vmware network associate with multiple wires
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/apis/compute/wire.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/network_additional_wires.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wireresource.go
  pkg/compute/models/wires.go
  pkg/compute/service/handlers.go
  pkg/mcclient/options/compute/network.go
  pkg/scheduler/cache/candidate/base.go
  pkg/util/netutils2/compact_ips.go
  pkg/util/netutils2/compact_ips_test.go
  pkg/util/netutils2/iface.go
Labels: size/XL

#18341 Automated cherry pick of #18318: fix: allow vmware network associate with multiple wires
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/apis/compute/wire.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/network_additional_wires.go
  pkg/compute/models/networks.go
  pkg/compute/models/purge.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wireresource.go
  pkg/compute/models/wires.go
  pkg/compute/service/handlers.go
  pkg/mcclient/options/compute/network.go
  pkg/scheduler/cache/candidate/base.go
  pkg/util/netutils2/compact_ips.go
  pkg/util/netutils2/compact_ips_test.go
  pkg/util/netutils2/iface.go
Labels: size/XL

#18360 fix(region): aws lb sync panic
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
Labels: size/S, area/region

#18361 Automated cherry pick of #18360: fix(region): aws lb sync panic
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
Labels: size/S

#18362 fix: fail to fetch admin ssh keypair
  pkg/compute/sshkeys/handler.go
Labels: size/S

#18363 Automated cherry pick of #18362: fix: fail to fetch admin ssh keypair
  pkg/compute/sshkeys/handler.go
Labels: size/S

#18364 Automated cherry pick of #18362: fix: fail to fetch admin ssh keypair
  pkg/compute/sshkeys/handler.go
Labels: size/S

#18366 Automated cherry pick of #18365: fix: auto convert missing subformat images
  pkg/image/models/images.go
Labels: size/XS

#18367 Automated cherry pick of #18365: fix: auto convert missing subformat images
  pkg/image/models/images.go
Labels: size/XS

#18369 Automated cherry pick of #18207: feat(region,glance): from cloudaccount to enable vmdk target format
  pkg/compute/models/cloudaccounts.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#18371 fix(scheduler): improve scheduler prefer and avoid tags strategy
  pkg/scheduler/core/context.go
  pkg/scheduler/core/types.go
Labels: size/M, area/scheduler

#18372 Automated cherry pick of #18371: fix(scheduler): improve scheduler prefer and avoid tags strategy
  pkg/scheduler/core/context.go
  pkg/scheduler/core/types.go
Labels: size/M

#18373 Automated cherry pick of #18371: fix(scheduler): improve scheduler prefer and avoid tags strategy
  pkg/scheduler/core/context.go
  pkg/scheduler/core/types.go
Labels: size/M

#18374 Automated cherry pick of #18371: fix(scheduler): improve scheduler prefer and avoid tags strategy
  pkg/scheduler/core/context.go
  pkg/scheduler/core/types.go
Labels: size/M

#18377 feat(region,host): cloudpods convert to kvm guest
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guest_import_api.go
  pkg/apis/compute/guests.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_convert.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_cloudpods_to_kvm_task.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestman/guest_create_from_remote.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/guesthelper.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/XL

#18378 Automated cherry pick of #18377: feat(region,host): cloudpods convert to kvm guest
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guest_import_api.go
  pkg/apis/compute/guests.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_convert.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_cloudpods_to_kvm_task.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestman/guest_create_from_remote.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/guesthelper.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/XL

#18379 Automated cherry pick of #18377: feat(region,host): cloudpods convert to kvm guest
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guest_import_api.go
  pkg/apis/compute/guests.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_convert.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_convert_cloudpods_to_kvm_task.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestman/guest_create_from_remote.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthandlers/guestimport.go
  pkg/hostman/guestman/guesthelper.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/XL

#18381 fix: vpcagent sync error
  go.mod
  go.sum
  pkg/apihelper/db.go
  pkg/apihelper/reflect.go
  pkg/compute/models/hosts.go
  pkg/compute/models/network_additional_wires.go
  pkg/compute/models/wires.go
  pkg/vpcagent/models/modelset.go
  pkg/webconsole/helper/helper.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
Labels: size/M

#18382 Automated cherry pick of #18381: fix: vpcagent sync error
  go.mod
  go.sum
  pkg/apihelper/db.go
  pkg/apihelper/reflect.go
  pkg/compute/models/hosts.go
  pkg/compute/models/network_additional_wires.go
  pkg/compute/models/wires.go
  pkg/vpcagent/models/modelset.go
  pkg/webconsole/helper/helper.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
Labels: size/M

#18356 Automated cherry pick of #18161: feat(scheduledTask): support cycle_hour
  cmd/climc/shell/scheduledtask/scheduledtask.go
  pkg/apis/compute/scaling_const.go
  pkg/apis/compute/scaling_trigger.go
  pkg/apis/scheduledtask/scheduled_task.go
  pkg/apis/scheduledtask/scheduled_task_const.go
  pkg/compute/models/timer.go
  pkg/notify/models/event_template.go
  pkg/scheduledtask/models/scheduled_tasks.go
  pkg/scheduledtask/models/timer.go
Labels: size/M

#18161 feat(scheduledTask): support cycle_hour
  cmd/climc/shell/scheduledtask/scheduledtask.go
  pkg/apis/compute/scaling_const.go
  pkg/apis/compute/scaling_trigger.go
  pkg/apis/scheduledtask/scheduled_task.go
  pkg/apis/scheduledtask/scheduled_task_const.go
  pkg/compute/models/timer.go
  pkg/notify/models/event_template.go
  pkg/scheduledtask/models/scheduled_tasks.go
  pkg/scheduledtask/models/timer.go
Labels: size/M

#18389 fix(apigateway): baremetal usage
  pkg/apigateway/report/report.go
Labels: size/M, area/apigateway

#18390 Automated cherry pick of #18389: fix(apigateway): baremetal usage
  pkg/apigateway/report/report.go
Labels: size/M

#18391 Automated cherry pick of #18389: fix(apigateway): baremetal usage
  pkg/apigateway/report/report.go
Labels: size/M

#18383 fix(region,host): live migrate disk driver determines the migration mode
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#18384 Automated cherry pick of #18383: fix(region,host): live migrate disk driver determines the migration mode
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#18388 Automated cherry pick of #18384: Automated cherry pick of #18383: fix(region,host): live migrate disk driver determines the migration mode
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#18395 Automated cherry pick of #18393: fix(host-deployer): deploy qga conf according hypervisor
  pkg/baremetal/manager.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_base.go
Labels: size/S

#18393 fix(host-deployer): deploy qga conf according hypervisor
  pkg/baremetal/manager.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_base.go
Labels: size/S

#18394 Automated cherry pick of #18393: fix(host-deployer): deploy qga conf according hypervisor
  pkg/baremetal/manager.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_base.go
Labels: size/S

#18400 fix(region): aws eip not found error
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/doc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/doc.go
Labels: size/L, area/region

#18402 Automated cherry pick of #18400: fix(region): aws eip not found error
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eip.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/column.go
Labels: size/S

#18403 fix(scheduler): fetch host storages directly
  pkg/compute/models/hosts.go
  pkg/compute/models/hoststorages.go
  pkg/scheduler/cache/candidate/base.go
Labels: size/S, area/scheduler

#18404 Automated cherry pick of #18403: fix(scheduler): fetch host storages directly
  pkg/compute/models/hosts.go
  pkg/compute/models/hoststorages.go
  pkg/scheduler/cache/candidate/base.go
Labels: size/S
