Repository yunionio/cloudpods, pull requests merged in 2023-12, with the labels that each got.

#18845 Automated cherry pick of #18843: feat(ci): use github action to check PR
  .github/workflows/ci-pr-build-test.yml
Labels: size/M

#18848 Automated cherry pick of #18843: feat(ci): use github action to check PR
  .github/workflows/ci-pr-build-test.yml
Labels: size/M

#18849 Automated cherry pick of #18843: feat(ci): use github action to check PR
  .github/workflows/ci-pr-build-test.yml
Labels: size/M

#18850 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/certificate.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/storage.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/columninfo.go
  vendor/yunion.io/x/sqlchemy/reflect.go
Labels: size/M

#18846 Automated cherry pick of #18844: fix(baremetal): disable probe access mac by redfish driver
  pkg/baremetal/tasks/ipmiprobe.go
Labels: size/XS

#18853 Automated cherry pick of #18852: fix: force assign ip address when sync vm vnics
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/options/options.go
Labels: size/M

#18854 fix: reserve ping probed ip with expiration
  pkg/cloudmon/misc/pinger.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/service.go
  pkg/compute/models/networks.go
  pkg/compute/models/reservedips.go
Labels: size/L

#18855 Automated cherry pick of #18854: fix: reserve ping probed ip with expiration
  pkg/cloudmon/misc/pinger.go
  pkg/cloudmon/options/options.go
  pkg/cloudmon/service/service.go
  pkg/compute/models/networks.go
  pkg/compute/models/reservedips.go
Labels: size/L

#18857 Manual cherrypick of #18856
  build/docker/Dockerfile.host-deployer
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#18862 Automated cherry pick of #18860: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/instancenic.go
Labels: size/M

#18863 fix(host-deployer,host): mv deploy driver option to common options
  pkg/cloudcommon/options/options.go
  pkg/hostman/hostdeployer/deployserver/options.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#18865 Automated cherry pick of #18864: Automated cherry pick of #18863: fix(host-deployer,host): mv deploy driver option to common options
  pkg/cloudcommon/options/options.go
  pkg/hostman/hostdeployer/deployserver/options.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#18870 Automated cherry pick of #18780: feat(host): use IsolatedDeviceModels as GPU whitelist
  pkg/cloudcommon/options/options.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/pci_device.go
Labels: size/L

#18868 Automated cherry pick of #18867: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/eip.go
Labels: size/S

#18869 Automated cherry pick of #18867: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/eip.go
Labels: size/S

#18874 fix(host-deployer): qemu deployer without kvm support
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#18876 Automated cherry pick of #18874: fix(host-deployer): qemu deployer without kvm support
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/S

#18882 fix: show update oc cmd
  scripts/docker_push.sh
Labels: size/M

#18883 Automated cherry pick of #18882: fix: show update oc cmd
  scripts/docker_push.sh
Labels: size/M

#18881 Automated cherry pick of #18880: fix(region): avoid cloudmon no cloudprovider sync
  pkg/cloudmon/resources/resources.go
Labels: size/XS

#18887 fix: clickhouse mapping table use the same name as origin
  pkg/cloudcommon/db/modelbase.go
Labels: size/XS

#18888 Automated cherry pick of #18887: fix: clickhouse mapping table use the same name as origin
  pkg/cloudcommon/db/modelbase.go
Labels: size/XS

#18889 fix: add index for token_cache_tbl to accelerate invalid token query
  pkg/keystone/models/tokencache.go
Labels: size/XS

#18890 Automated cherry pick of #18889: fix: add index for token_cache_tbl to accelerate invalid token query
  pkg/keystone/models/tokencache.go
Labels: size/XS

#18891 Automated cherry pick of #18889: fix: add index for token_cache_tbl to accelerate invalid token query
  pkg/keystone/models/tokencache.go
Labels: size/XS

#18897 fix(monitor): update vendor to support victoriametrics topk func
  go.mod
  go.sum
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/converter.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/tranlator.go
  vendor/modules.txt
Labels: size/M, area/monitor

#18898 Automated cherry pick of #18897: fix(monitor): update vendor to support victoriametrics topk func
  go.mod
  go.sum
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/converter.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/tranlator.go
  vendor/modules.txt
Labels: size/M

#18899 Automated cherry pick of #18897: fix(monitor): update vendor to support victoriametrics topk func
  go.mod
  go.sum
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/converter.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/tranlator.go
  vendor/modules.txt
Labels: size/M

#18902 fix(util): fixed yunion.io/x/sqlchemy version
  Makefile
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
Labels: size/S, area/util

#18903 fix(webconsole): optimized guacd error log
  pkg/webconsole/guac/tunnel.go
  pkg/webconsole/server/rdp_server.go
Labels: size/M, area/webconsole

#18904 Automated cherry pick of #18903: fix(webconsole): optimized guacd error log
  pkg/webconsole/guac/tunnel.go
  pkg/webconsole/server/rdp_server.go
Labels: size/M

#18905 fix(keystone): remove deleted project metadata
  pkg/keystone/models/domains.go
  pkg/keystone/models/identitybase.go
Labels: size/XS, area/keystone

#18906 Automated cherry pick of #18905: fix(keystone): remove deleted project metadata
  pkg/keystone/models/domains.go
  pkg/keystone/models/identitybase.go
Labels: size/XS

#18892 fix: esxi hotadd cpu limit
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/S

#18893 Automated cherry pick of #18892: fix: esxi hotadd cpu limit
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
Labels: size/S

#18908 fix(monitor): map interval to step
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/S, area/monitor

#18910 Automated cherry pick of #18908: fix(monitor): map interval to step
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/S

#18912 fix: guacd docker file mkdir required dir
  build/docker/Dockerfile.guacd
Labels: size/XS

#18921 Automated cherry pick of #18920: fix(webconsole): rdp 用户隔离上传文件
  pkg/webconsole/guac/guac.go
  pkg/webconsole/server/rdp_server.go
Labels: size/S

#18918 Automated cherry pick of #18917: Automated cherry pick of #18916: Fix/host deployer
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/M

#18922 fix(region): cloudpods uefi and generate name
  go.mod
  go.sum
  pkg/mcclient/cloudpods/image.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/images.go
Labels: size/S, area/region

#18923 Automated cherry pick of #18922: fix(region): cloudpods uefi and generate name
  go.mod
  go.sum
  pkg/mcclient/cloudpods/image.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/images.go
Labels: size/S

#18930 Automated cherry pick of #18926: feat(monitor): make simple-query API adapting victoriametrics and add monitor-unifiedmonitor-query command
  cmd/climc/shell/monitor/unifiedmonitor.go
  pkg/apis/monitor/types.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/apis/monitor/unifiedmonitor_query_input.go
  pkg/apis/monitor/unifiedmonitor_query_input_test.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/modules/monitor/mod_unifiedmonitor.go
  pkg/mcclient/options/monitor/simplequery.go
  pkg/mcclient/options/monitor/unifiedmonitor.go
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/reducer_test.go
  pkg/monitor/alerting/conditions/suggestrulereducer.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/query_signature.go
  pkg/monitor/models/query_signature_test.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/subscriptionmodel/subcription.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/query.go
  pkg/monitor/tsdb/driver/influxdb/query_test.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/models.go
  pkg/monitor/tsdb/time_range.go
  pkg/monitor/validators/validators.go
Labels: size/XXL

#18931 Automated cherry pick of #18926: feat(monitor): make simple-query API adapting victoriametrics and add monitor-unifiedmonitor-query command
  cmd/climc/shell/monitor/unifiedmonitor.go
  pkg/apis/monitor/types.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/apis/monitor/unifiedmonitor_query_input.go
  pkg/apis/monitor/unifiedmonitor_query_input_test.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/modules/monitor/mod_unifiedmonitor.go
  pkg/mcclient/options/monitor/simplequery.go
  pkg/mcclient/options/monitor/unifiedmonitor.go
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/reducer_test.go
  pkg/monitor/alerting/conditions/suggestrulereducer.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/query_signature.go
  pkg/monitor/models/query_signature_test.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/subscriptionmodel/subcription.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/query.go
  pkg/monitor/tsdb/driver/influxdb/query_test.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/models.go
  pkg/monitor/tsdb/time_range.go
  pkg/monitor/validators/validators.go
Labels: size/XXL

#18927 fix: no default fallback dns server
  pkg/apis/compute/network_const.go
  pkg/compute/models/networks.go
  pkg/compute/options/options.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/S

#18928 Automated cherry pick of #18927: fix: no default fallback dns server
  pkg/apis/compute/network_const.go
  pkg/compute/models/networks.go
  pkg/compute/options/options.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/S

#18939 fix(monitor): not add scope to query resource from region service
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/M, area/monitor

#18941 Automated cherry pick of #18939: fix(monitor): not add scope to query resource from region service
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/metricquery/interfaces.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/M

#18943 fix(region): optimized sync code
  pkg/compute/models/cloudregions.go
  pkg/compute/models/loadbalancers.go
Labels: size/M

#18944 Automated cherry pick of #18943: fix(region): optimized sync code
  pkg/compute/models/cloudregions.go
  pkg/compute/models/loadbalancers.go
Labels: size/M

#18946 fix(region): support volc balance and gcp api retry
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
Labels: size/M, area/region

#18947 Automated cherry pick of #18946: fix(region): support volc balance and gcp api retry
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
Labels: size/M

#18948 Automated cherry pick of #18946: fix(region): support volc balance and gcp api retry
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
Labels: size/S

#18932 fix: host add a local config file
  pkg/hostman/options/options.go
Labels: size/S

#18936 Automated cherry pick of #18932: fix: host add a local config file
  pkg/hostman/options/options.go
Labels: size/S

#18933 Automated cherry pick of #18932: fix: host add a local config file
  pkg/hostman/options/options.go
Labels: size/S

#18934 Automated cherry pick of #18932: fix: host add a local config file
  pkg/hostman/options/options.go
Labels: size/S

#18935 Automated cherry pick of #18932: fix: host add a local config file
  pkg/hostman/options/options.go
Labels: size/S

#18955 fix: log metric collection action
  pkg/cloudmon/misc/pinger.go
  pkg/cloudmon/resources/resources.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#18956 Automated cherry pick of #18955: fix: log metric collection action
  pkg/cloudmon/misc/pinger.go
  pkg/cloudmon/resources/resources.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/L

#18951 fix: ignore vm virtual ip changes
  pkg/apis/compute/guestnetwork.go
Labels: size/XS

#18952 Automated cherry pick of #18951: fix: ignore vm virtual ip changes
  pkg/apis/compute/guestnetwork.go
Labels: size/XS

#18953 Automated cherry pick of #18951: fix: ignore vm virtual ip changes
  pkg/apis/compute/guestnetwork.go
Labels: size/XS

#18965 fix(host-deployer): run guest on host and ignore no config file
  pkg/cloudcommon/options/options.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/L

#18966 Automated cherry pick of #18965: fix(host-deployer): run guest on host and ignore no config file
  pkg/cloudcommon/options/options.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/L

#18969 fix(region): vendor update for gcp rebuild-root sys disk size and password login
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/S, area/region

#18970 Automated cherry pick of #18969: fix(region): vendor update for gcp rebuild-root sys disk size and password login
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/S

#18971 Automated cherry pick of #18969: fix(region): vendor update for gcp rebuild-root sys disk size and password login
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/S

#18975 fix(monitor): consider whether the target host is in source host of mem balancer
  pkg/monitor/controller/balancer/cpu.go
  pkg/monitor/controller/balancer/mem.go
Labels: size/S, area/monitor

#18976 Automated cherry pick of #18975: fix(monitor): consider whether the target host is in source host of m…
  pkg/monitor/controller/balancer/cpu.go
  pkg/monitor/controller/balancer/mem.go
Labels: size/S

#18977 Automated cherry pick of #18975: fix(monitor): consider whether the target host is in source host of mem balancer
  pkg/monitor/controller/balancer/cpu.go
  pkg/monitor/controller/balancer/mem.go
Labels: size/S

#18983 Automated cherry pick of #18908: fix(monitor): map interval to step
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/S

#18981 fix(monitor): fetch measurements from victoriametrics
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertresource.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/L, area/monitor

#18982 Automated cherry pick of #18981: fix(monitor): fetch measurements from victoriametrics
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertresource.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/L

#18984 Automated cherry pick of #18981: fix(monitor): fetch measurements from victoriametrics
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/alertresource.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/metric.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/L

#18974 fix(region): gen ssl api
  pkg/apis/compute/zz_generated.model.go
Labels: size/S

#18987 fix(region): set status available for kvm secgroup rule after created
  pkg/compute/models/secgrouprules.go
Labels: size/XS, area/region

#18988 Automated cherry pick of #18987: fix(region): set status available for kvm secgroup rule after created
  pkg/compute/models/secgrouprules.go
Labels: size/XS

#18985 fix: backup storage capacity_mb field optional
  pkg/compute/models/backup_storage.go
Labels: size/XS

#18986 Automated cherry pick of #18985: fix: backup storage capacity_mb field optional
  pkg/compute/models/backup_storage.go
Labels: size/XS

#18980 feat(region,host): lvm support backport to release/3.9
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/storages.go
  pkg/compute/storagedrivers/clvm.go
  pkg/compute/storagedrivers/local.go
  pkg/compute/tasks/disk_create_task.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_clvm.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/imagecache_lvm.go
  pkg/hostman/storageman/imagecachemanager_lvm.go
  pkg/hostman/storageman/lvmutils/doc.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_agent.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_clvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/XXL

#18949 feat(region,host): clvm support
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/storagedrivers/clvm.go
  pkg/compute/storagedrivers/local.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_clvm.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/imagecachemanager_lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_clvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/XL

#18979 Automated cherry pick of #18978: Automated cherry pick of #18949: feat(region,host): clvm support
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/storagedrivers/clvm.go
  pkg/compute/storagedrivers/local.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_clvm.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/imagecachemanager_lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_clvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/XL

#18978 Automated cherry pick of #18949: feat(region,host): clvm support
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/storagedrivers/clvm.go
  pkg/compute/storagedrivers/local.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/disk_clvm.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/imagecachemanager_lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_clvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/XL

#18989 fix(region): avoid duplicate rule name for gcp
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
Labels: size/L, area/region

#18990 Automated cherry pick of #18989: fix(region): avoid duplicate rule name for gcp
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
Labels: size/L

#18991 Automated cherry pick of #18989: fix(region): avoid duplicate rule name for gcp
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
Labels: size/M

#18992 fix(region): remove useless snapshot policy code
  pkg/compute/models/disks.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/L, area/region

#18993 Automated cherry pick of #18992: fix(region): remove useless snapshot policy code
  pkg/compute/models/disks.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/L

#18999 fix(host-deployer): udpate yunionos, reduce yunionos memsize
  build/docker/Dockerfile.host-deployer
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#19000 Automated cherry pick of #18999: fix(host-deployer): udpate yunionos, reduce yunionos memsize
  build/docker/Dockerfile.host-deployer
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#19001 Automated cherry pick of #18999: fix(host-deployer): udpate yunionos, reduce yunionos memsize
  build/docker/Dockerfile.host-deployer
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#18997 fix: refine webconsole ssh api
  cmd/climc/shell/compute/webconsole.go
  pkg/cloudcommon/db/fetch.go
  pkg/mcclient/options/webconsole.go
  pkg/webconsole/helper/helper.go
  pkg/webconsole/server/ssh_server.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/service/service.go
  pkg/webconsole/session/remote_console_rdp.go
  pkg/webconsole/session/resolve_sshinfo.go
  pkg/webconsole/session/ssh_session.go
Labels: size/L

#18998 Automated cherry pick of #18997: fix: refine webconsole ssh api
  cmd/climc/shell/compute/webconsole.go
  pkg/cloudcommon/db/fetch.go
  pkg/mcclient/options/webconsole.go
  pkg/webconsole/helper/helper.go
  pkg/webconsole/server/ssh_server.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/service/service.go
  pkg/webconsole/session/remote_console_rdp.go
  pkg/webconsole/session/resolve_sshinfo.go
  pkg/webconsole/session/ssh_session.go
Labels: size/L

#19003 fix(cloudcommon): service config informer doesn't start watching
  pkg/cloudcommon/options/manager.go
  pkg/cloudcommon/options/options.go
Labels: area/util, area/common

#19005 Automated cherry pick of #19003: fix(cloudcommon): service config informer doesn't start watching
  pkg/cloudcommon/options/manager.go
  pkg/cloudcommon/options/options.go
Labels: size/XS

#19004 Automated cherry pick of #19003: fix(cloudcommon): service config informer doesn't start watching
  pkg/cloudcommon/options/manager.go
  pkg/cloudcommon/options/options.go
Labels: size/XS

#19007 fix(scheduler): reload cloudprovider's hosts when syncing finished
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/hosts.go
  pkg/scheduler/cache/candidate/builder.go
  pkg/scheduler/data_manager/candidate_manager.go
  pkg/scheduler/data_manager/cloudprovider/cloudprovider.go
  pkg/scheduler/data_manager/common/cache_manager.go
  pkg/scheduler/data_manager/common/common.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/service/service.go
Labels: size/L, area/region, area/scheduler

#19010 Automated cherry pick of #19007: fix(scheduler): reload cloudprovider's hosts when syncing finished
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/hosts.go
  pkg/scheduler/cache/candidate/builder.go
  pkg/scheduler/data_manager/candidate_manager.go
  pkg/scheduler/data_manager/cloudprovider/cloudprovider.go
  pkg/scheduler/data_manager/common/cache_manager.go
  pkg/scheduler/data_manager/common/common.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/service/service.go
Labels: size/L

#19011 Automated cherry pick of #19007: fix(scheduler): reload cloudprovider's hosts when syncing finished
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/hosts.go
  pkg/scheduler/cache/candidate/builder.go
  pkg/scheduler/data_manager/candidate_manager.go
  pkg/scheduler/data_manager/cloudprovider/cloudprovider.go
  pkg/scheduler/data_manager/common/cache_manager.go
  pkg/scheduler/data_manager/common/common.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/service/service.go
Labels: size/L

#19012 fix: webconsole display information control
  cmd/climc/shell/compute/webconsole.go
  pkg/apis/identity/consts.go
  pkg/apis/webconsole/types.go
  pkg/webconsole/options/options.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/display_info.go
  pkg/webconsole/session/remote_console.go
  pkg/webconsole/session/remote_console_rdp.go
  pkg/webconsole/session/resolve_sshinfo.go
  pkg/webconsole/session/session.go
  pkg/webconsole/session/ssh_session.go
Labels: size/L

#19013 Automated cherry pick of #19012: fix: webconsole display information control
  cmd/climc/shell/compute/webconsole.go
  pkg/apis/identity/consts.go
  pkg/apis/webconsole/types.go
  pkg/webconsole/options/options.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/display_info.go
  pkg/webconsole/session/remote_console.go
  pkg/webconsole/session/remote_console_rdp.go
  pkg/webconsole/session/resolve_sshinfo.go
  pkg/webconsole/session/session.go
  pkg/webconsole/session/ssh_session.go
Labels: size/L

#19014 fix: show update commands all at a time
  scripts/docker_push.sh
Labels: size/S

#19015 fix(region): do not clean up the running vm in the recycle bin
  pkg/compute/models/guests.go
Labels: size/XS

#19016 Automated cherry pick of #19015: fix(region): do not clean up the running vm in the recycle bin
  pkg/compute/models/guests.go
Labels: size/XS

#19023 Automated cherry pick of #19021: feat(region): add ip_addr for rds.GetShortDesc
  pkg/compute/models/dbinstances.go
Labels: size/S

#19022 Automated cherry pick of #19021: feat(region): add ip_addr for rds.GetShortDesc
  pkg/compute/models/dbinstances.go
Labels: size/S

#19021 feat(region): add ip_addr for rds.GetShortDesc
  pkg/compute/models/dbinstances.go
Labels: size/S

#19027 fix(region): The latest api of Huawei cloud elb and eip is applicable
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_invoke.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_balances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_acl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_cert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_listener_rule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
Labels: area/region, size/XL

#19028 Automated cherry pick of #19027: fix(region): The latest api of Huawei cloud elb and eip is applicable
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_invoke.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_balances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_acl.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_cert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/loadbalancer_listener_rule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool_sku.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/sslcertificate.go
Labels: size/XL

#19037 fix(host): usb device hotplug
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/usb.go
Labels: size/S

#19039 Automated cherry pick of #19037: fix(host): usb device hotplug
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/isolated_device/usb.go
Labels: size/S

#19031 fix(host-deployer): pass config files to deploy vm
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/localdeploy.go
Labels: size/S

#19032 Automated cherry pick of #19031: fix(host-deployer): pass config files to deploy vm
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/localdeploy.go
Labels: size/S

#19033 fix: disable pvpanic dev
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#19035 Automated cherry pick of #19033: fix: disable pvpanic dev
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#19036 Automated cherry pick of #19033: fix: disable pvpanic dev
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#19029 fix: climc add lb-event and dbinstance-event
  cmd/climc/shell/events/events.go
Labels: size/S

#19041 Automated cherry pick of #18975: fix(monitor): consider whether the target host is in source host of mem balancer
  pkg/monitor/controller/balancer/cpu.go
  pkg/monitor/controller/balancer/mem.go
Labels: size/S

#19042 fix(region): snapshot policy sync external id
  pkg/compute/models/snapshotpolicy.go
Labels: size/XS

#19043 Automated cherry pick of #19042: fix(region): snapshot policy sync external id
  pkg/compute/models/snapshotpolicy.go
Labels: size/XS

#19046 fix(docker): update dockerfile for ansible-base
  build/docker/Dockerfile.ansibleserver-base
  build/docker/Makefile
Labels: size/S

#19047 Automated cherry pick of #19046: fix(docker): update dockerfile for ansible-base
  build/docker/Dockerfile.ansibleserver-base
  build/docker/Makefile
Labels: size/S

#19048 Automated cherry pick of #19046: fix(docker): update dockerfile for ansible-base
  build/docker/Dockerfile.ansibleserver-base
  build/docker/Makefile
Labels: size/S

#19049 fix(region): add log for skiped pending deleted vm
  pkg/compute/models/guests.go
Labels: size/XS, area/region

#19050 Automated cherry pick of #19049: fix(region): add log for skiped pending deleted vm
  pkg/compute/models/guests.go
Labels: size/XS

#19051 fix(region): avoid rds vcpu count is zero
  pkg/compute/models/dbinstances.go
Labels: size/S, area/region

#19052 Automated cherry pick of #19051: fix(region): avoid rds vcpu count is zero
  pkg/compute/models/dbinstances.go
Labels: size/S

#19053 fix(region): ignore empty certificate error for ssl sync
  go.mod
  go.sum
  pkg/compute/models/sslcertificate.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_keypairs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_quotas.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/quota.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/sslcertificate.go
Labels: size/L, area/region

#19054 Automated cherry pick of #19053: fix(region): ignore empty certificate error for ssl sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_keypairs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/client/modules/mod_quotas.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/quota.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/sslcertificate.go
Labels: size/L

#19061 fix(region): vendor update for volcengine network and aws dnsrecords sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnsrecord.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/network.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/S, area/region

#19062 Automated cherry pick of #19061: fix(region): vendor update for volcengine network and aws dnsrecords sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnsrecord.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/network.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/S

#19063 Automated cherry pick of #19061: fix(region): vendor update for volcengine network and aws dnsrecords sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnsrecord.go
Labels: size/S

#19057 fix: webconsole ssh open forward failure
  pkg/webconsole/session/resolve_sshinfo.go
Labels: size/S

#19059 Automated cherry pick of #19057: fix: webconsole ssh open forward failure
  pkg/webconsole/session/resolve_sshinfo.go
Labels: size/S

#19056 feat(baremetal-agent): support using tftp to download kernel and initrd
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
  pkg/apis/identity/consts.go
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/baremetal/utils/grub/grub.go
Labels: size/M

#19064 Automated cherry pick of #19056: feat(baremetal-agent): support using tftp to download kernel and initrd
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
  pkg/apis/identity/consts.go
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/baremetal/utils/grub/grub.go
Labels: size/M

#19065 Automated cherry pick of #19056: feat(baremetal-agent): support using tftp to download kernel and initrd
  build/docker/Dockerfile.baremetal-agent
  build/docker/Dockerfile.baremetal-base
  build/docker/Makefile
  pkg/apis/identity/consts.go
  pkg/baremetal/manager.go
  pkg/baremetal/options/options.go
  pkg/baremetal/utils/grub/grub.go
Labels: size/M

#19072 fix(region): remove debug sql query
  pkg/compute/models/guest_queries.go
  pkg/compute/models/keypairs.go
Labels: size/XS, area/region

#19073 Automated cherry pick of #19072: fix(region): remove debug sql query
  pkg/compute/models/guest_queries.go
  pkg/compute/models/keypairs.go
Labels: size/XS

#19074 fix(region): add disk preallocation for guest info
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_queries.go
Labels: size/M, area/region

#19075 Automated cherry pick of #19074: fix(region): add disk preallocation for guest info
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_queries.go
Labels: size/M

#19076 fix(region): optimized disk list
  pkg/compute/models/disks.go
Labels: size/S, area/region

#19077 Automated cherry pick of #19076: fix(region): optimized disk list
  pkg/compute/models/disks.go
Labels: size/S

#19078 Automated cherry pick of #19076: fix(region): optimized disk list
  pkg/compute/models/disks.go
Labels: size/S

#19082 fix(host-deployer): check executor is enabled on init qemu driver
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#19083 Automated cherry pick of #19082: fix(host-deployer): check executor is enabled on init qemu driver
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#19084 Automated cherry pick of #19082: fix(host-deployer): check executor is enabled on init qemu driver
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#19080 fix(region): avoid for-loop sync volcengine disks
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/storage.go
Labels: size/M, area/region

#19081 Automated cherry pick of #19080: fix(region): avoid for-loop sync volcengine disks
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/storage.go
Labels: size/M
