Repository yunionio/cloudpods, pull requests merged in 2023-03, with the labels that each got.

#16075 fix: allow add esxi as onecloud lb backend
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#16076 Automated cherry pick of #16075: fix: allow add esxi as onecloud lb backend
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#16077 fix: better prompt info for user failed auth due to invalid idp status
  pkg/apigateway/handler/auth.go
  pkg/httperrors/consts.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
Labels: size/M

#16079 Automated cherry pick of #16077: fix: better prompt info for user failed auth due to invalid idp status
  pkg/apigateway/handler/auth.go
  pkg/httperrors/consts.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
Labels: size/M

#16078 Automated cherry pick of #16077: fix: better prompt info for user failed auth due to invalid idp status
  pkg/apigateway/handler/auth.go
  pkg/httperrors/consts.go
  pkg/keystone/tokens/auth.go
  pkg/keystone/tokens/handlers.go
Labels: size/M

#16085 fix(monitor): skip check series options
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/M, area/monitor

#16087 Automated cherry pick of #16085: fix(monitor): skip check series options
  pkg/apis/monitor/unifiedmonitor_const.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/M

#16062 fix(notify): bugFix
  pkg/apis/notify/config.go
  pkg/notify/models/config.go
  pkg/notify/models/plugindriver.go
  pkg/notify/sender/dingtalk.go
  pkg/notify/sender/dingtalk_robot.go
  pkg/notify/sender/email.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/feishu_robot.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/webconsole.go
  pkg/notify/sender/webhook.go
  pkg/notify/sender/websocket.go
  pkg/notify/sender/workwx.go
  pkg/notify/sender/workwx_robot.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/subcontact_pull_task.go
Labels: lgtm, size/L

#16080 Automated cherry pick of #16062: fix(notify): bugFix
  pkg/apis/notify/config.go
  pkg/notify/models/config.go
  pkg/notify/models/plugindriver.go
  pkg/notify/sender/dingtalk.go
  pkg/notify/sender/dingtalk_robot.go
  pkg/notify/sender/email.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/feishu_robot.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/webconsole.go
  pkg/notify/sender/webhook.go
  pkg/notify/sender/websocket.go
  pkg/notify/sender/workwx.go
  pkg/notify/sender/workwx_robot.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/subcontact_pull_task.go
Labels: size/L

#16081 fix(notify): addMissingActionTranslate
  pkg/notify/models/event_template.go
Labels: lgtm, size/S

#16082 Automated cherry pick of #16081: fix(notify): addMissingActionTranslate
  pkg/notify/models/event_template.go
Labels: size/S

#16083 Automated cherry pick of #16081: fix(notify): addMissingActionTranslate
  pkg/notify/models/event_template.go
Labels: size/S

#16092 Automated cherry pick of #16088: fix(monitor): rewrite slimit and soffset logic
  pkg/monitor/models/unifiedmonitor.go
Labels: size/M

#16104 fix: three member policy system violation check
  pkg/cloudcommon/db/modelbase.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/options/options.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/logclient.go
Labels: size/M

#16106 Automated cherry pick of #16104: fix: three member policy system violation check
  pkg/cloudcommon/db/modelbase.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/options/options.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/logclient.go
Labels: size/M

#16105 Automated cherry pick of #16104: fix: three member policy system violation check
  pkg/cloudcommon/db/modelbase.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/options/options.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/logclient.go
Labels: size/M

#16114 fix(notify):fixInitSubscriberData
  pkg/notify/models/subscriber.go
Labels: lgtm, size/XS

#16115 Automated cherry pick of #16114: fix(notify):fixInitSubscriberData
  pkg/notify/models/subscriber.go
Labels: size/XS

#16112 fix(host): start daemon guest on guest not running
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#16113 Automated cherry pick of #16112: fix(host): start daemon guest on guest not running
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#16109 Automated cherry pick of #16108: fix(keystone): filter users by role assignment domain
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/users.go
Labels: size/M

#16108 fix(keystone): filter users by role assignment domain
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/users.go
Labels: size/M, area/keystone

#16103 fix(host): load existing guests desc
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/pci_test.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/L

#16111 Automated cherry pick of #16103: fix(host): load existing guests desc
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/pci_test.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/L

#16101 fix(host): dest guest load pci addresses on live migrate
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#16102 Automated cherry pick of #16101: fix(host): dest guest load pci addresses on live migrate
  pkg/compute/models/guest_actions.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/M

#16093 fix(host): check shared file storage mount point
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/S

#16095 Automated cherry pick of #16093: fix(host): check shared file storage mount point
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/S

#16096 fix(region): openstack compute api version
  go.mod
  go.sum
  pkg/compute/models/guest_actions.go
  pkg/compute/options/options.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
Labels: size/S, area/region

#16097 Automated cherry pick of #16096: fix(region): openstack compute api version
  go.mod
  go.sum
  pkg/compute/models/guest_actions.go
  pkg/compute/options/options.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/openstack.go
Labels: size/S

#16098 Automated cherry pick of #16096: fix(region): openstack compute api version
  pkg/compute/models/guest_actions.go
  pkg/compute/options/options.go
  pkg/multicloud/openstack/openstack.go
Labels: size/S

#16120 Automated cherry pick of #16118: fix(cloudmon): support collect history metric
  pkg/cloudmon/options/options.go
  pkg/cloudmon/resources/resources.go
  pkg/cloudmon/service/service.go
Labels: size/M

#16121 Automated cherry pick of #16118: fix(cloudmon): support collect history metric
  pkg/cloudmon/options/options.go
  pkg/cloudmon/resources/resources.go
  pkg/cloudmon/service/service.go
Labels: size/M

#16122 fix(region): set disk default cache mode none
  pkg/compute/options/options.go
Labels: size/XS

#16123 Automated cherry pick of #16122: fix(region): set disk default cache mode none
  pkg/compute/options/options.go
Labels: size/XS

#16126 fix: hostman StartService()
  cmd/host/main.go
  pkg/hostman/host_services.go
Labels: size/S

#16127 Automated cherry pick of #16126: fix: hostman StartService()
  cmd/host/main.go
  pkg/hostman/host_services.go
Labels: size/S

#16136 fix(mcclient): add FetchKeypairBySession method
  pkg/mcclient/modules/compute/mod_sshkeypairs.go
Labels: size/S, area/climc

#16137 Automated cherry pick of #16136: fix(mcclient): add FetchKeypairBySession method
  pkg/mcclient/modules/compute/mod_sshkeypairs.go
Labels: size/S

#16138 Automated cherry pick of #16136: fix(mcclient): add FetchKeypairBySession method
  pkg/mcclient/modules/compute/mod_sshkeypairs.go
Labels: size/S

#16134 fix(notify): alert notification
  pkg/notify/models/notification.go
Labels: size/XS

#16135 Automated cherry pick of #16134: fix(notify): alert notification
  pkg/notify/models/notification.go
Labels: size/XS

#16132 fix(keystone): support user filter by role project
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/users.go
Labels: size/S, area/keystone

#16133 Automated cherry pick of #16132: fix(keystone): support user filter by role project
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/users.go
Labels: size/S

#16147 chore: update host and lbagent base image
  build/docker/Dockerfile.host
  build/docker/Dockerfile.lbagent
  build/docker/Dockerfile.lbagent-base
Labels: size/XS

#16149 chore: update ovsdb go mod vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/ovsdb/schema/ovn_nb/schema.go
  vendor/yunion.io/x/ovsdb/types/ovn-nb.ovsschema
  vendor/yunion.io/x/ovsdb/types/ovn-sb.ovsschema
  vendor/yunion.io/x/ovsdb/types/vswitch.ovsschema
Labels: size/XL

#16150 Automated cherry pick of #16149: chore: update ovsdb go mod vendor
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/ovsdb/schema/ovn_nb/schema.go
  vendor/yunion.io/x/ovsdb/types/ovn-nb.ovsschema
  vendor/yunion.io/x/ovsdb/types/ovn-sb.ovsschema
  vendor/yunion.io/x/ovsdb/types/vswitch.ovsschema
Labels: size/XL

#16144 fix(cloudmon): add HCSO base monitor
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/huaweistack.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/monitor.go
Labels: lgtm

#16146 Automated cherry pick of #16144: fix(cloudmon): add HCSO base monitor
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/huaweistack.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/monitor.go
Labels: size/L

#16141 fix(region): vpc name sync
  pkg/compute/models/vpcs.go
Labels: size/XS, area/region

#16148 Automated cherry pick of #16147: chore: update host and lbagent base image
  build/docker/Dockerfile.host
  build/docker/Dockerfile.lbagent
  build/docker/Dockerfile.lbagent-base
Labels: size/XS

#16152 fix(monitor): balancer pair ignored error
  pkg/monitor/controller/balancer/balancer.go
Labels: size/XS, area/monitor

#16153 Automated cherry pick of #16152: fix(monitor): balancer pair ignored error
  pkg/monitor/controller/balancer/balancer.go
Labels: size/XS

#16155 fix(host): tls live migrate disable mulitfd
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#16157 Automated cherry pick of #16155: fix(host): tls live migrate disable mulitfd
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#16156 Automated cherry pick of #16155: fix(host): tls live migrate disable mulitfd
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#16171 fix: zero clean disk add logs
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#16172 Automated cherry pick of #16171: fix: zero clean disk add logs
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#16161 fix(baremetal): not update hypervisor host's status
  pkg/baremetal/cronjobs.go
  pkg/baremetal/manager.go
Labels: size/S, area/baremetal

#16162 Automated cherry pick of #16161: fix(baremetal): not update hypervisor host's status
  pkg/baremetal/cronjobs.go
  pkg/baremetal/manager.go
Labels: size/S

#16167 fix(region): lb project id
  pkg/apis/compute/loadbalancerbackend.go
  pkg/apis/compute/loadbalancerbackendgroup.go
  pkg/apis/compute/loadbalancerlistener.go
  pkg/apis/compute/loadbalancerlistenerrule.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
Labels: size/M, area/region

#16168 Automated cherry pick of #16167: fix(region): lb project id
  pkg/apis/compute/loadbalancerbackend.go
  pkg/apis/compute/loadbalancerbackendgroup.go
  pkg/apis/compute/loadbalancerlistener.go
  pkg/apis/compute/loadbalancerlistenerrule.go
  pkg/compute/models/loadbalancerbackendgroups.go
  pkg/compute/models/loadbalancerbackends.go
  pkg/compute/models/loadbalancerlistenerrules.go
  pkg/compute/models/loadbalancerlisteners.go
Labels: size/M

#16129 fix: logclient request add service name context
  pkg/util/logclient/logclient.go
Labels: size/XS

#16130 Automated cherry pick of #16129: fix: logclient request add service name context
  pkg/util/logclient/logclient.go
Labels: size/XS

#16177 fix(scheduler): storage failed reason isn't showed in forecast result
  pkg/scheduler/algorithm/predicates/guest/storage_predicate.go
Labels: size/XS, area/scheduler

#16178 Automated cherry pick of #16177: fix(scheduler): storage failed reason isn't showed in forecast result
  pkg/scheduler/algorithm/predicates/guest/storage_predicate.go
Labels: size/XS

#16179 Automated cherry pick of #16177: fix(scheduler): storage failed reason isn't showed in forecast result
  pkg/scheduler/algorithm/predicates/guest/storage_predicate.go
Labels: size/XS

#16175 fix(notify): attachment name
  pkg/notify/sender/email.go
Labels: size/XS, area/notify

#16176 Automated cherry pick of #16175: fix(notify): attachment name
  pkg/notify/sender/email.go
Labels: size/XS

#16158 fix(region): apsara projects sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/organization.go
Labels: size/S, area/region

#16159 Automated cherry pick of #16158: fix(region): apsara projects sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/organization.go
Labels: size/S

#16160 Automated cherry pick of #16158: fix(region): apsara projects sync
  pkg/multicloud/apsara/organization.go
Labels: size/S

#16131 Automated cherry pick of #16129: fix: logclient request add service name context
  pkg/util/logclient/logclient.go
Labels: size/XS

#16125 Automated cherry pick of #16124: feature: allow network update wire_id
  cmd/climc/shell/compute/network_ip_mac.go
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/mcclient/options/compute/network.go
Labels: size/L

#16124 feature: allow network update wire_id
  cmd/climc/shell/compute/network_ip_mac.go
  cmd/climc/shell/compute/networks.go
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/mcclient/options/compute/network.go
Labels: size/L

#16169 fix(nofiy): mobileAndEmailBug
  pkg/notify/models/config.go
  pkg/notify/models/notification.go
  pkg/notify/models/plugindriver.go
  pkg/notify/models/receiver.go
  pkg/notify/models/template.go
  pkg/notify/sender/dingtalk.go
  pkg/notify/sender/dingtalk_robot.go
  pkg/notify/sender/email.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/feishu_robot.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/smsdriver/huawei.go
  pkg/notify/sender/webconsole.go
  pkg/notify/sender/webhook.go
  pkg/notify/sender/websocket.go
  pkg/notify/sender/workwx.go
  pkg/notify/sender/workwx_robot.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/verification_send_task.go
Labels: lgtm, size/L

#16183 fix(cloudmon): hcso monitor make mod
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/monitor.go
Labels: size/S

#16185 Automated cherry pick of #16183: fix(cloudmon): hcso monitor make mod
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/monitor.go
Labels: size/S

#16186 fix(region): add h3c
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/h3c.go
  pkg/compute/hostdrivers/h3c.go
  pkg/compute/regiondrivers/h3c.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
Labels: size/L, area/region

#16187 Automated cherry pick of #16186: fix(region): add h3c
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/h3c.go
  pkg/compute/hostdrivers/h3c.go
  pkg/compute/regiondrivers/h3c.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
Labels: size/L

#16196 feature: compose guest image with existing images
  cmd/climc/shell/image/imageguest.go
  pkg/apis/image/guestimage.go
  pkg/image/models/image_guest.go
  pkg/image/models/image_guest_joint.go
  pkg/image/models/images.go
  pkg/image/tasks/guest_image_delete_task.go
Labels: size/L

#16197 Automated cherry pick of #16196: feature: compose guest image with existing images
  cmd/climc/shell/image/imageguest.go
  pkg/apis/image/guestimage.go
  pkg/image/models/image_guest.go
  pkg/image/models/image_guest_joint.go
  pkg/image/models/images.go
  pkg/image/tasks/guest_image_delete_task.go
Labels: size/L

#16198 Automated cherry pick of #16196: feature: compose guest image with existing images
  cmd/climc/shell/image/imageguest.go
  pkg/apis/image/guestimage.go
  pkg/image/models/image_guest.go
  pkg/image/models/image_guest_joint.go
  pkg/image/models/images.go
  pkg/image/tasks/guest_image_delete_task.go
Labels: size/L

#16193 fix: refine dashboard policy
  pkg/keystone/locale/predefined_policies.go
Labels: size/XS

#16195 Automated cherry pick of #16193: fix: refine dashboard policy
  pkg/keystone/locale/predefined_policies.go
Labels: size/XS

#16194 Automated cherry pick of #16193: fix: refine dashboard policy
  pkg/keystone/locale/predefined_policies.go
Labels: size/XS

#16190 fix: storecli missing lv device name
  pkg/baremetal/utils/raid/megactl/storcli.go
Labels: size/S

#16191 Automated cherry pick of #16190: fix: storecli missing lv device name
  pkg/baremetal/utils/raid/megactl/storcli.go
Labels: size/S

#16192 Automated cherry pick of #16190: fix: storecli missing lv device name
  pkg/baremetal/utils/raid/megactl/storcli.go
Labels: size/S

#16200 fix(host): set medium type on storage create
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#16201 Automated cherry pick of #16200: fix(host): set medium type on storage create
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#16202 fix: prevent duplicate table sync
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/M

#16204 Automated cherry pick of #16202: fix: prevent duplicate table sync
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/M

#16203 Automated cherry pick of #16202: fix: prevent duplicate table sync
  pkg/cloudcommon/db/models.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/M

#16205 fix: add vm integrity check notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/CHECKSUM_TEST_FAILED.tmpl
  pkg/apis/notify/const.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
Labels: size/S

#16206 Automated cherry pick of #16205: fix: add vm integrity check notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/CHECKSUM_TEST_FAILED.tmpl
  pkg/apis/notify/const.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
Labels: size/S

#16207 Automated cherry pick of #16205: fix: add vm integrity check notify
  build/notify/root/opt/yunion/share/local-templates/content@cn/CHECKSUM_TEST_FAILED.tmpl
  pkg/apis/notify/const.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
Labels: size/S

#16212 fix: minor fixes 20230313
  pkg/cloudcommon/notifyclient/notify.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/XS

#16213 Automated cherry pick of #16212: fix: minor fixes 20230313
  pkg/cloudcommon/notifyclient/notify.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/XS

#16214 Automated cherry pick of #16212: fix: minor fixes 20230313
  pkg/cloudcommon/notifyclient/notify.go
  pkg/util/zeroclean/zeroclean.go
Labels: size/XS

#16209 fix(region): aws dns zone name
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnshostedzone.go
Labels: size/S, area/region

#16211 Automated cherry pick of #16209: fix(region): aws dns zone name
  pkg/multicloud/aws/dnshostedzone.go
Labels: size/XS

#16210 Automated cherry pick of #16209: fix(region): aws dns zone name
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnshostedzone.go
Labels: size/S

#16216 fix(notify): aliyunSmsdriver
  pkg/apis/notify/config.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/smsdriver/aliyun.go
  pkg/notify/sender/smsdriver/huawei.go
  pkg/notify/tasks/verification_send_task.go
Labels: lgtm, size/M

#16218 Automated cherry pick of #16216: fix(notify): aliyunSmsdriver
  pkg/apis/notify/config.go
  pkg/notify/sender/mobile.go
  pkg/notify/sender/smsdriver/aliyun.go
  pkg/notify/sender/smsdriver/huawei.go
  pkg/notify/tasks/verification_send_task.go
Labels: size/M

#16189 fix(region,host): host health misc fix
  build/docker/Dockerfile.host-health
  cmd/host-health/main.go
  pkg/cloudmon/misc/pinger.go
  pkg/cloudmon/misc/pingutils.go
  pkg/compute/models/host_health.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/host_services.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
Labels: size/XL

#16217 Automated cherry pick of #16189: fix(region,host): host health misc fix
  build/docker/Dockerfile.host-health
  cmd/host-health/main.go
  pkg/cloudmon/misc/pinger.go
  pkg/cloudmon/misc/pingutils.go
  pkg/compute/models/host_health.go
  pkg/compute/models/hosts.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/host_services.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
Labels: size/XL

#16222 fix(host-health): simplify host health main.go
  cmd/host-health/main.go
  pkg/hostman/host_health/service.go
Labels: size/L

#16228 fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/account.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/bingo.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/quotas.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/region.go
Labels: size/L, area/region

#16230 Automated cherry pick of #16228: fix(region): vender update
  pkg/cloudprovider/consts.go
  pkg/multicloud/aliyun/disk.go
  pkg/multicloud/apsara/disk.go
  pkg/multicloud/bingocloud/account.go
  pkg/multicloud/bingocloud/bingo.go
  pkg/multicloud/bingocloud/disk.go
  pkg/multicloud/bingocloud/instance.go
  pkg/multicloud/bingocloud/provider/provider.go
  pkg/multicloud/bingocloud/quotas.go
  pkg/multicloud/bingocloud/region.go
  pkg/multicloud/bingocloud/secgroup.go
  pkg/multicloud/bingocloud/storage.go
Labels: size/L

#16229 Automated cherry pick of #16228: fix(region): vender update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/account.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/bingo.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/instance_snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/quotas.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/region.go
Labels: size/L

#16231 fix(host): download sparse file truncate first
  cmd/climc/shell/compute/disks.go
  pkg/hostman/downloader/downloader.go
  pkg/hostman/storageman/remotefile/remotefile.go
Labels: lgtm, size/S

#16233 Automated cherry pick of #16231: fix(host): download sparse file truncate first
  cmd/climc/shell/compute/disks.go
  pkg/hostman/downloader/downloader.go
  pkg/hostman/storageman/remotefile/remotefile.go
Labels: size/S

#16225 fix: fail to create vm with guest_image
  pkg/apis/compute/guest_image.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#16226 Automated cherry pick of #16225: fix: fail to create vm with guest_image
  pkg/apis/compute/guest_image.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#16227 Automated cherry pick of #16225: fix: fail to create vm with guest_image
  pkg/apis/compute/guest_image.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/M

#16220 feat：support for setting custom resource-id
  pkg/cloudcommon/db/standalone_anon.go
Labels: size/XS

#16221 Automated cherry pick of #16220: feat：support for setting custom resource-id
  pkg/cloudcommon/db/standalone_anon.go
Labels: size/XS

#16235 fix(notify): fixEmailQueueBug
  pkg/notify/sender/email.go
Labels: size/M

#16236 Automated cherry pick of #16235: fix(notify): fixEmailQueueBug
  pkg/notify/sender/email.go
Labels: size/M

#16237 fix(readme): update ocboot checkout branch to 3.9
  README-CN.md
  README.md
Labels: size/XS

#16238 fix(monitor): set wrong resType when query
  pkg/monitor/alerting/conditions/query.go
Labels: size/XS, area/monitor

#16239 Automated cherry pick of #16238: fix(monitor): set wrong resType when query
  pkg/monitor/alerting/conditions/query.go
Labels: size/XS

#16240 Automated cherry pick of #16238: fix(monitor): set wrong resType when query
  pkg/monitor/alerting/conditions/query.go
Labels: size/XS

#16241 fix: cloud account options visiable @release/3.9
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#16243 fix(host): kvm detect and iommu probe
  pkg/hostman/isolated_device/gpu.go
  pkg/util/sysutils/kvm.go
Labels: size/M

#16244 Automated cherry pick of #16243: fix(host): kvm detect and iommu probe
  pkg/hostman/isolated_device/gpu.go
  pkg/util/sysutils/kvm.go
Labels: size/M

#16245 Automated cherry pick of #16243: fix(host): kvm detect and iommu probe
  pkg/hostman/isolated_device/gpu.go
  pkg/util/sysutils/kvm.go
Labels: size/M

#16246 fix: avoid dup sync table revisit
  pkg/cloudcommon/db/models.go
Labels: size/S

#16247 Automated cherry pick of #16246: fix: avoid dup sync table revisit
  pkg/cloudcommon/db/models.go
Labels: size/S

#16248 Automated cherry pick of #16246: fix: avoid dup sync table revisit
  pkg/cloudcommon/db/models.go
Labels: size/S

#16258 fix(vpcagent): import ovn package in vpcagent service.go
  cmd/vpcagent/main.go
  pkg/vpcagent/service/service.go
Labels: size/XS

#16259 Automated cherry pick of #16258: fix(vpcagent): import ovn package in vpcagent service.go
  cmd/vpcagent/main.go
  pkg/vpcagent/service/service.go
Labels: size/XS

#16255 fix(region): get catalog data by region id
  pkg/mcclient/token3.go
Labels: size/XS

#16256 Automated cherry pick of #16255: fix(region): get catalog data by region id
  pkg/mcclient/token3.go
Labels: size/XS

#16257 Automated cherry pick of #16255: fix(region): get catalog data by region id
  pkg/mcclient/token3.go
Labels: size/XS

#16251 fix(region): not sync update netinterface wire_id when merge wires at
  pkg/compute/models/wire_id_change_handler.go
  pkg/compute/models/wires.go
Labels: size/S

#16250 Automated cherry pick of #16249: fix(region): not sync update netinterface wire_id when merge wires
  cmd/climc/shell/compute/cloudaccounts.go
  pkg/compute/models/cloudaccount_vmware.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/wire_id_change_handler.go
  pkg/compute/models/wires.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#16249 fix(region): not sync update netinterface wire_id when merge wires
  cmd/climc/shell/compute/cloudaccounts.go
  pkg/compute/models/cloudaccount_vmware.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/wire_id_change_handler.go
  pkg/compute/models/wires.go
  pkg/compute/tasks/cloud_account_sync_task.go
  pkg/mcclient/options/cloudaccounts.go
Labels: size/M

#16261 fix(region): addModelartsDeleteLoaclTask
  pkg/compute/models/modelarts_pools.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
Labels: size/L

#16263 Automated cherry pick of #16261: fix(region): addModelartsDeleteLoaclTask
  pkg/compute/models/modelarts_pools.go
  pkg/compute/tasks/modelarts_pool_create_task.go
  pkg/compute/tasks/modelarts_pool_delete_task.go
Labels: size/L

#16266 update contact qrcode
  README-CN.md
  README.md
Labels: size/XS

#16269 feat(monitor): add extral server tags
  pkg/apis/monitor/alertquery_const.go
Labels: size/XS, area/monitor

#16270 Automated cherry pick of #16269: feat(monitor): add extral server tags
  pkg/apis/monitor/alertquery_const.go
Labels: size/XS

#16271 Automated cherry pick of #16269: feat(monitor): add extral server tags
  pkg/apis/monitor/alertquery_const.go
Labels: size/XS

#16275 fix(notify): fix notify email double send
  pkg/notify/sender/email.go
Labels: size/S

#16276 Automated cherry pick of #16275: fix(notify): fix notify email double send
  pkg/notify/sender/email.go
Labels: size/S

#16268 fix(region): check JdAccountConnect
  pkg/multicloud/jdcloud/balance.go
Labels: size/XS

#16273 fix(region): hcs url
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/ctyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcs/hcs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/balance.go
Labels: size/S, area/region

#16277 fix(cloudmon): add apsara eip metric
  go.mod
  go.sum
  pkg/apis/compute/elasticip.go
  pkg/cloudmon/providerdriver/apsara.go
  pkg/cloudmon/providerdriver/base.go
  pkg/cloudmon/providerdriver/driver.go
  pkg/cloudmon/resources/resources.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/monitor.go
Labels: size/XL, area/cloudmon
