Repository yunionio/cloudpods, pull requests merged in 2023-05, with the labels that each got.

#16925 fix: vm desc missing cdrom config
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/jsonutils/json_pointer_trace.go
  vendor/yunion.io/x/jsonutils/jsonpointer.go
  vendor/yunion.io/x/jsonutils/marshal.go
  vendor/yunion.io/x/jsonutils/marshal_session.go
Labels: size/L

#16937 fix(region): aws redis tags
  go.mod
  go.sum
  pkg/compute/models/elasticcache_instances.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/pkg/utils/utils.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/insert_batch.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/L, area/region

#16938 Automated cherry pick of #16937: fix(region): aws redis tags
  go.mod
  go.sum
  pkg/compute/models/elasticcache_instances.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/utils/utils.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/mysql.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/sqlite.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/insert_batch.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/L

#16933 fix(monitor): truncated JSONObject of alert model
  pkg/monitor/models/alert.go
Labels: size/XS, area/monitor

#16935 Automated cherry pick of #16933: fix(monitor): truncated JSONObject of alert model
  pkg/monitor/models/alert.go
Labels: size/XS

#16934 Automated cherry pick of #16933: fix(monitor): truncated JSONObject of alert model
  pkg/monitor/models/alert.go
Labels: size/XS

#16908 fix(region): get cdrom details
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#16928 Automated cherry pick of #16908: fix(region): get cdrom details
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_insert_iso_task.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#16936 feat(climc): create k8s cluster v1.22.9
  pkg/mcclient/options/k8s/cluster.go
Labels: size/XS, area/climc

#16943 Automated cherry pick of #16936: feat(climc): create k8s cluster v1.22.9
  pkg/mcclient/options/k8s/cluster.go
Labels: size/XS

#16946 fix(region): vendor update for aws redis tag
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/elasticache_instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
Labels: area/region

#16930 fix(region): optimized guest and cachedimage list speed
  pkg/apis/compute/cachedimage.go
  pkg/apis/compute/host.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
Labels: size/L, area/region

#16931 Automated cherry pick of #16930: fix(region): optimized guest and cachedimage list speed
  pkg/apis/compute/cachedimage.go
  pkg/apis/compute/host.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
Labels: size/L

#16932 Automated cherry pick of #16930: fix(region): optimized guest and cachedimage list speed
  pkg/apis/compute/cachedimage.go
  pkg/apis/compute/host.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
Labels: size/L

#16940 fix(region): cloudpods secgroup rule
  pkg/mcclient/cloudpods/secgroup.go
Labels: size/XS, area/region

#16941 Automated cherry pick of #16940: fix(region): cloudpods secgroup rule
  pkg/mcclient/cloudpods/secgroup.go
Labels: size/XS

#16944 fix(region): allow query capabilities
  pkg/compute/policy/defaults.go
Labels: size/XS, area/region

#16945 Automated cherry pick of #16944: fix(region): allow query capabilities
  pkg/compute/policy/defaults.go
Labels: size/XS

#16950 fix(region,host): migrate with out chain snapshots
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#16951 Automated cherry pick of #16950: fix(region,host): migrate with out chain snapshots
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#16952 Automated cherry pick of #16951: Automated cherry pick of #16950: fix(region,host): migrate with out chain snapshots
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#16953 fix(region): skip empty resource metric pull
  pkg/cloudmon/resources/resources.go
Labels: size/M, area/region

#16954 Automated cherry pick of #16953: fix(region): skip empty resource metric pull
  pkg/cloudmon/resources/resources.go
Labels: size/M

#16972 Automated cherry pick of #16948: fix(region): host status
  pkg/compute/models/hostresource.go
Labels: size/XS

#16966 fix: domain tag filter not working
  pkg/compute/usages/handler.go
  pkg/keystone/models/domains.go
Labels: lgtm, size/M

#16967 Automated cherry pick of #16966: fix: domain tag filter not working
  pkg/compute/usages/handler.go
  pkg/keystone/models/domains.go
Labels: size/M

#16968 Automated cherry pick of #16966: fix: domain tag filter not working
  pkg/compute/usages/handler.go
  pkg/keystone/models/domains.go
Labels: size/M

#16957 fix(host): don't return error on disk snap chain params miss
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/XS

#16958 Automated cherry pick of #16957: fix(host): don't return error on disk snap chain params miss
  pkg/hostman/guestman/guesthandlers/guesthandler.go
Labels: size/XS

#16962 fix(glance): support filter image by os archs
  pkg/apis/image/image.go
  pkg/apis/list.go
  pkg/cloudcommon/db/archs.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/mcclient/options/glance/image.go
Labels: size/M, area/image, area/docs

#16963 Automated cherry pick of #16962: fix(glance): support filter image by os archs
  pkg/apis/image/image.go
  pkg/apis/list.go
  pkg/cloudcommon/db/archs.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/mcclient/options/glance/image.go
Labels: size/M

#16964 Automated cherry pick of #16962: fix(glance): support filter image by os archs
  pkg/apis/image/image.go
  pkg/apis/list.go
  pkg/cloudcommon/db/archs.go
  pkg/image/models/image_guest.go
  pkg/image/models/images.go
  pkg/mcclient/options/glance/image.go
Labels: size/M

#16969 fix: three member policy adjustment 20230507
  pkg/keystone/locale/predefined_yaml.go
Labels: size/XS

#16970 Automated cherry pick of #16969: fix: three member policy adjustment 20230507
  pkg/keystone/locale/predefined_yaml.go
Labels: size/XS

#16971 Automated cherry pick of #16969: fix: three member policy adjustment 20230507
  pkg/keystone/locale/predefined_yaml.go
Labels: size/XS

#16983 fix: usage handler nil check revisit
  pkg/compute/usages/handler.go
Labels: size/S

#16984 Automated cherry pick of #16983: fix: usage handler nil check revisit
  pkg/compute/usages/handler.go
Labels: size/S

#16985 Automated cherry pick of #16983: fix: usage handler nil check revisit
  pkg/compute/usages/handler.go
Labels: size/S

#16979 fix(region): elastic cache purge
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/elasticcache_delete_task.go
Labels: size/L, area/region

#16981 Automated cherry pick of #16979: fix(region): elastic cache purge
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/purge.go
  pkg/compute/tasks/elasticcache_delete_task.go
Labels: size/L

#16974 fix(host): hide kvm only gpu guests
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#16977 Automated cherry pick of #16974: fix(host): hide kvm only gpu guests
  pkg/hostman/guestman/arch/arch.go
  pkg/hostman/guestman/arch/x86.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/S

#16208 fix(webconsole): websocket ssh
  cmd/climc/shell/compute/webconsole.go
  pkg/apis/webconsole/consts.go
  pkg/mcclient/options/webconsole.go
  pkg/webconsole/command/command.go
  pkg/webconsole/command/ssh_command.go
  pkg/webconsole/handlers.go
  pkg/webconsole/options/options.go
  pkg/webconsole/server/server.go
  pkg/webconsole/server/ssh_server.go
  pkg/webconsole/server/tty_server.go
  pkg/webconsole/service/service.go
  pkg/webconsole/session/remote_console.go
  pkg/webconsole/session/session.go
  pkg/webconsole/session/ssh_session.go
Labels: area/webconsole, size/XL

#16973 fix(region): optimized vpc-list
  pkg/apis/compute/vpc.go
  pkg/apis/compute/wire.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/L, area/region

#16975 Automated cherry pick of #16973: fix(region): optimized vpc-list
  pkg/apis/compute/vpc.go
  pkg/apis/compute/wire.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/L

#16976 Automated cherry pick of #16973: fix(region): optimized vpc-list
  pkg/apis/compute/vpc.go
  pkg/apis/compute/wire.go
  pkg/compute/models/cloudregions.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/wires.go
Labels: size/L

#16996 Automated cherry pick of #16994: fix(monitor): adjust query timeout to 5 mins
  pkg/monitor/models/unifiedmonitor.go
Labels: size/XS

#17002 fix(region): add cronjob to cleaning snapshot
  pkg/compute/models/snapshots.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: lgtm, size/M, area/region

#17006 Automated cherry pick of #17002: fix(region): add cronjob to cleaning snapshot
  pkg/compute/models/snapshots.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/M

#16988 fix(host): check running guest kvm off option
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#16989 Automated cherry pick of #16988: fix(host): check running guest kvm off option
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS

#16998 fix(region): show host info when cache image
  pkg/compute/hostdrivers/kvm.go
Labels: size/XS, area/region

#16999 Automated cherry pick of #16998: fix(region): show host info when cache image
  pkg/compute/hostdrivers/kvm.go
Labels: size/XS

#17008 fix(region): add cleanSnapshotDate option
  pkg/compute/models/snapshots.go
  pkg/compute/options/options.go
Labels: size/XS

#17012 Automated cherry pick of #17008: fix(region): add cleanSnapshotDate option
  pkg/compute/models/snapshots.go
  pkg/compute/options/options.go
Labels: size/XS

#17013 Automated cherry pick of #17011: fix(notify): fix notify webconsole
  pkg/notify/models/receiver.go
Labels: size/XS

#16915 fix(host): update desc metadata on guest sync meta
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#17016 fix(host): guest name has space
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/XS

#17017 Automated cherry pick of #17016: fix(host): guest name has space
  pkg/hostman/guestman/qemu/qemu.go
Labels: size/XS

#17028 fix(region): optimized sku sync
  pkg/cloudcommon/db/metadata.go
  pkg/cloudid/models/cloudaccount.go
  pkg/compute/models/cloudimages.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/nas_skus.go
  pkg/compute/models/nat_skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/waf_rule_groups.go
  pkg/mcclient/modules/compute/mod_skus.go
Labels: size/L, area/region

#17030 Automated cherry pick of #17028: fix(region): optimized sku sync
  pkg/cloudcommon/db/metadata.go
  pkg/cloudid/models/cloudaccount.go
  pkg/compute/models/cloudimages.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/nas_skus.go
  pkg/compute/models/nat_skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/waf_rule_groups.go
  pkg/mcclient/modules/compute/mod_skus.go
Labels: size/L

#17029 Automated cherry pick of #17028: fix(region): optimized sku sync
  pkg/cloudcommon/db/metadata.go
  pkg/cloudid/models/cloudaccount.go
  pkg/compute/models/cloudimages.go
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/nas_skus.go
  pkg/compute/models/nat_skus.go
  pkg/compute/models/skus_tools.go
  pkg/compute/models/waf_rule_groups.go
  pkg/mcclient/modules/compute/mod_skus.go
Labels: size/L

#17031 fix(host): check disk pci device is nil on init disks addrs
  pkg/hostman/guestman/pci.go
Labels: size/XS

#17032 Automated cherry pick of #17031: fix(host): check disk pci device is nil on init disks addrs
  pkg/hostman/guestman/pci.go
Labels: size/XS

#17026 fix(host): guest sync update cdrom bootindex
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
Labels: lgtm, size/S

#17027 Automated cherry pick of #17026: fix(host): guest sync update cdrom bootindex
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/S

#16990 fix(region): optimized snapshot list
  pkg/compute/models/purge.go
  pkg/compute/models/snapshots.go
Labels: size/L, area/region

#17014 Automated cherry pick of #16990: fix(region): optimized snapshot list
  pkg/compute/models/purge.go
  pkg/compute/models/snapshots.go
Labels: size/L

#17033 fix: options of the maximal number of roles of a user in project
  pkg/apis/identity/consts.go
  pkg/keystone/models/assignments.go
  pkg/keystone/options/options.go
Labels: size/S

#17034 Automated cherry pick of #17033: fix: options of the maximal number of roles of a user in project
  pkg/apis/identity/consts.go
  pkg/keystone/models/assignments.go
  pkg/keystone/options/options.go
Labels: size/S

#17044 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/sqlchemy/reflect.go
Labels: size/M, area/region

#17045 Automated cherry pick of #17044: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/sqlchemy/reflect.go
Labels: size/M

#17050 fix(region): secgroup rule sync with lock
  pkg/compute/models/secgroups.go
Labels: size/XS, area/region

#17051 Automated cherry pick of #17050: fix(region): secgroup rule sync with lock
  pkg/compute/models/secgroups.go
Labels: size/XS

#17047 fix: prevent policy violate when assigning policy to roles
  pkg/cloudcommon/app/options.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
  pkg/keystone/service/handlers.go
Labels: size/L

#17048 Automated cherry pick of #17047: fix: prevent policy violate when assigning policy to roles
  pkg/cloudcommon/app/options.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
  pkg/keystone/service/handlers.go
Labels: size/L

#17049 Automated cherry pick of #17047: fix: prevent policy violate when assigning policy to roles
  pkg/cloudcommon/app/options.go
  pkg/keystone/models/policies.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
  pkg/keystone/service/handlers.go
Labels: size/L

#17041 fix(notify): add some template translate
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/utils.go
Labels: lgtm, size/M, area/notify

#17046 Automated cherry pick of #17041: fix(notify): add some template translate
  pkg/notify/models/event_template.go
  pkg/notify/models/topic.go
  pkg/notify/sender/feishu.go
  pkg/notify/sender/utils.go
Labels: size/M

#17056 Automated cherry pick of #17055: fix(excelutils): 取消负数标红
  pkg/util/excelutils/const.go
Labels: size/XS

#17055 fix(excelutils): 取消负数标红
  pkg/util/excelutils/const.go
Labels: lgtm, size/XS

#17052 fix(region): guest restart network task params
  pkg/apis/compute/guestnetwork.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/host_taps.go
  pkg/compute/tasks/guest_restart_network_task.go
  pkg/compute/tasks/guest_sync_task.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/L

#17053 Automated cherry pick of #17052: fix(region): guest restart network task params
  pkg/apis/compute/guestnetwork.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/host_taps.go
  pkg/compute/tasks/guest_restart_network_task.go
  pkg/compute/tasks/guest_sync_task.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/L

#17069 fix(host): support arm host tcg qemu
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pci.go
Labels: size/XS

#17070 Automated cherry pick of #17069: fix(host): support arm host tcg qemu
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pci.go
Labels: size/XS

#17066 fix: disable policy update when enable three member system
  pkg/keystone/models/policies.go
Labels: size/S

#17067 Automated cherry pick of #17066: fix: disable policy update when enable three member system
  pkg/keystone/models/policies.go
Labels: size/S

#17072 fix(host): fix arm topo lib ghw
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/modules.txt
Labels: size/M

#17073 Automated cherry pick of #17072: fix(host): fix arm topo lib ghw
  go.mod
  go.sum
  vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go
  vendor/modules.txt
Labels: size/M

#17060 fix(notify): add func to get recevier subscription
  cmd/climc/main.go
  cmd/climc/shell/notify/common.go
  cmd/climc/shell/notify/config.go
  cmd/climc/shell/notify/emailqueues.go
  cmd/climc/shell/notify/notification.go
  cmd/climc/shell/notify/receiver.go
  cmd/climc/shell/notify/robot.go
  cmd/climc/shell/notify/subscription.go
  cmd/climc/shell/notify/template.go
  pkg/mcclient/options/notify/receiver.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
Labels: size/M, area/notify

#17074 Automated cherry pick of #17060: fix(notify): add func to get recevier subscription
  cmd/climc/main.go
  cmd/climc/shell/notify/common.go
  cmd/climc/shell/notify/config.go
  cmd/climc/shell/notify/emailqueues.go
  cmd/climc/shell/notify/notification.go
  cmd/climc/shell/notify/receiver.go
  cmd/climc/shell/notify/robot.go
  cmd/climc/shell/notify/subscription.go
  cmd/climc/shell/notify/template.go
  pkg/mcclient/options/notify/receiver.go
  pkg/notify/models/receiver.go
  pkg/notify/models/subscriber.go
Labels: size/M

#17085 fix(notify): fix feishu getAccessTokenFailed err
  pkg/notify/sender/feishu.go
Labels: size/XS, area/notify

#17086 Automated cherry pick of #17085: fix(notify): fix feishu getAccessTokenFailed err
  pkg/notify/sender/feishu.go
Labels: size/XS

#17057 fix(region): snapshot code tidy
  pkg/compute/models/snapshots.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: lgtm, size/S, area/region

#17058 Automated cherry pick of #17057: fix(region): snapshot code tidy
  pkg/compute/models/snapshots.go
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/S

#17080 fix(region): validate delete region
  pkg/compute/models/cloudregions.go
Labels: size/XS, area/region

#17081 Automated cherry pick of #17080: fix(region): validate delete region
  pkg/compute/models/cloudregions.go
Labels: size/XS

#17082 Automated cherry pick of #17080: fix(region): validate delete region
  pkg/compute/models/cloudregions.go
Labels: size/XS

#17075 fix(region): disable ping debug
  pkg/compute/models/host_health.go
  pkg/hostman/host_health/health_manager.go
Labels: size/XS, area/region

#17076 Automated cherry pick of #17075: fix(region): disable ping debug
  pkg/compute/models/host_health.go
  pkg/hostman/host_health/health_manager.go
Labels: size/XS

#17087 fix: allow bootstrap role policy assignment without violation check
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
Labels: size/M

#17088 Automated cherry pick of #17087: fix: allow bootstrap role policy assignment without violation check
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
Labels: size/M

#17089 Automated cherry pick of #17087: fix: allow bootstrap role policy assignment without violation check
  pkg/keystone/models/rolepolicies.go
  pkg/keystone/models/roles.go
Labels: size/M

#17090 fix(region): openstack disk reset
  pkg/apis/compute/disk.go
  pkg/compute/hostdrivers/aliyun.go
  pkg/compute/hostdrivers/aws.go
  pkg/compute/hostdrivers/azure.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/ctyun.go
  pkg/compute/hostdrivers/google.go
  pkg/compute/hostdrivers/h3c.go
  pkg/compute/hostdrivers/hcs.go
  pkg/compute/hostdrivers/hcsop.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/huawei_stack.go
  pkg/compute/hostdrivers/incloudsphere.go
  pkg/compute/hostdrivers/jdcloud.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/ucloud.go
  pkg/compute/hostdrivers/zstack.go
  pkg/compute/models/disks.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/L, area/region

#17091 Automated cherry pick of #17090: fix(region): openstack disk reset
  pkg/apis/compute/disk.go
  pkg/compute/hostdrivers/aliyun.go
  pkg/compute/hostdrivers/aws.go
  pkg/compute/hostdrivers/azure.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/ctyun.go
  pkg/compute/hostdrivers/google.go
  pkg/compute/hostdrivers/h3c.go
  pkg/compute/hostdrivers/hcs.go
  pkg/compute/hostdrivers/hcsop.go
  pkg/compute/hostdrivers/huawei.go
  pkg/compute/hostdrivers/huawei_stack.go
  pkg/compute/hostdrivers/incloudsphere.go
  pkg/compute/hostdrivers/jdcloud.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/ucloud.go
  pkg/compute/hostdrivers/zstack.go
  pkg/compute/models/disks.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/L

#17077 fix(apigateway): image upload with properties
  pkg/apigateway/handler/imageutils.go
  pkg/mcclient/modules/image/mod_images.go
Labels: size/M, area/apigateway

#17078 Automated cherry pick of #17077: fix(apigateway): image upload with properties
  pkg/apigateway/handler/imageutils.go
  pkg/mcclient/modules/image/mod_images.go
Labels: size/M

#17079 Automated cherry pick of #17077: fix(apigateway): image upload with properties
  pkg/apigateway/handler/imageutils.go
  pkg/mcclient/modules/image/mod_images.go
Labels: size/M

#17096 fix(climc): notify v2
  cmd/climc/shell/notify/common.go
  cmd/climc/shell/notify/config.go
  cmd/climc/shell/notify/emailqueues.go
  cmd/climc/shell/notify/notification.go
  cmd/climc/shell/notify/receiver.go
  cmd/climc/shell/notify/robot.go
  cmd/climc/shell/notify/subscription.go
  cmd/climc/shell/notify/template.go
Labels: size/S, area/climc

#17097 Automated cherry pick of #17096: fix(climc): notify v2
  cmd/climc/shell/notify/common.go
  cmd/climc/shell/notify/config.go
  cmd/climc/shell/notify/emailqueues.go
  cmd/climc/shell/notify/notification.go
  cmd/climc/shell/notify/receiver.go
  cmd/climc/shell/notify/robot.go
  cmd/climc/shell/notify/subscription.go
  cmd/climc/shell/notify/template.go
Labels: size/S

#17098 fix(keystone): user pwd expired notify bug fix
  pkg/keystone/models/passwords.go
  pkg/keystone/service/service.go
Labels: lgtm, size/XS, area/keystone

#17100 Automated cherry pick of #17098: fix(keystone): user pwd expired notify bug fix
  pkg/keystone/models/passwords.go
  pkg/keystone/service/service.go
Labels: size/XS

#17108 fxi(scheduledtask): skip task when scheduledtask.labels is empty
  pkg/scheduledtask/models/scheduled_tasks.go
Labels: lgtm, size/S

#17109 Automated cherry pick of #17108: fxi(scheduledtask): skip task when scheduledtask.labels is empty
  pkg/scheduledtask/models/scheduled_tasks.go
Labels: size/S

#17104 fix(baremetal): skip running sysinit.sh when arch is aarch64
  pkg/baremetal/tasks/baseprepare.go
Labels: size/S, area/baremetal

#17103 fix(region): support kube cluster create
  cmd/climc/shell/compute/kube_clusters.go
  cmd/climc/shell/compute/kube_node_pools.go
  go.mod
  go.sum
  pkg/apis/compute/kube_cluster.go
  pkg/apis/compute/kube_node_pools.go
  pkg/cloudcommon/validators/validators.go
  pkg/compute/models/kube_clusters.go
  pkg/compute/models/kube_node_pools.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/kube_cluster_create_task.go
  pkg/compute/tasks/kube_node_pool_create_task.go
  pkg/compute/tasks/kube_node_pool_delete_task.go
  pkg/compute/tasks/kube_node_pool_syncstatus_task.go
  pkg/mcclient/options/compute/kube_cluster.go
  pkg/mcclient/options/compute/kube_node_pool.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/waitstatus.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/kube_node_pools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_invoke.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eks_node_group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_role.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/kube_node_pools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/kube_clusters.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/kube_node_pools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/region_base.go
  vendor/yunion.io/x/sqlchemy/delete_batch.go
  vendor/yunion.io/x/sqlchemy/update_batch.go
Labels: size/XXL

#17115 Automated cherry pick of #17114: fix(host): don't init pcie to pci bridge on pci extend disabled
  pkg/hostman/guestman/pci.go
Labels: size/XS

#17101 fix(host): pciroot not assigned in switch case
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#17102 Automated cherry pick of #17101: fix(host): pciroot not assigned in switch case
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#17116 fix: lbagent fail to start due to empty prioty and interface
  pkg/lbagent/register.go
  pkg/util/ovnutils/ovnutils.go
Labels: size/S

#17092 fix(host): record live migrate resume task
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/S

#17093 Automated cherry pick of #17092: fix(host): record live migrate resume task
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/S

#17084 Automated cherry pick of #17083: feat(bingocloud): add bingoiam for oauth2
  cmd/climc/shell/misc/feature.go
  pkg/apis/identity/config.go
  pkg/keystone/driver/oauth2/bingoiam/bingoiam.go
  pkg/keystone/driver/oauth2/bingoiam/doc.go
  pkg/keystone/driver/oauth2/bingoiam/factory.go
  pkg/keystone/driver/oauth2/bingoiam/sync.go
  pkg/keystone/driver/oauth2/oauth2.go
  pkg/keystone/driver/oauth2/types.go
  pkg/keystone/service/drivers.go
Labels: size/XL

#17125 fix(region): index order
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/disks.go
Labels: size/XS, area/region

#17126 Automated cherry pick of #17125: fix(region): index order
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/disks.go
Labels: size/XS

#17127 Automated cherry pick of #17125: fix(region): index order
  pkg/compute/models/dbinstance_skus.go
  pkg/compute/models/disks.go
Labels: size/XS

#17120 fix(cloudid): cache policy for cloud
  cmd/climc/shell/cloudid/cloudpolicy.go
  cmd/climc/shell/cloudid/cloudpolicycache.go
  pkg/apis/cloudid/cloudpolicy.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/cloudpolicycaches.go
  pkg/cloudid/tasks/cloudpolicy_cache_task.go
  pkg/mcclient/options/cloudid/cloudpolicy.go
  pkg/mcclient/options/cloudid/cloudpolicycache.go
Labels: size/L, area/cloudid

#17133 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
Labels: size/S, area/region

#17139 fix(region): add CloudKubeClusterId option in KubeNodePoolListInput
  pkg/apis/compute/kube_node_pools.go
  pkg/compute/models/kube_node_pools.go
  pkg/mcclient/options/compute/kube_node_pool.go
Labels: size/XS, area/region

#17140 fix(region): support aws assign public ip with network
  cmd/climc/shell/compute/networks.go
  go.mod
  go.sum
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/network_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/wire.go
Labels: size/L, area/region

#17141 Automated cherry pick of #17140: fix(region): support aws assign public ip with network
  cmd/climc/shell/compute/networks.go
  go.mod
  go.sum
  pkg/apis/compute/network.go
  pkg/compute/models/networks.go
  pkg/compute/models/regiondrivers.go
  pkg/compute/regiondrivers/base.go
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/network_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/wire.go
Labels: size/L

#17129 fix(host): hotplug pcie device use pcie root port
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/L

#17130 Automated cherry pick of #17129: fix(host): hotplug pcie device use pcie root port
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/L

#17137 fix(region): support shutdown mode
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
Labels: size/M, area/region

#17138 Automated cherry pick of #17137: fix(region): support shutdown mode
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guests.go
Labels: size/M

#17094 fix(host): compatible host no l3 cache
  pkg/hostman/guestman/guesthelper.go
Labels: size/S

#17121 Automated cherry pick of #17094: fix(host): compatible host no l3 cache
  pkg/hostman/guestman/guesthelper.go
Labels: size/S

#17148 fix(region): support save cloud image to glance
  cmd/climc/shell/image/images.go
  go.mod
  go.sum
  pkg/apis/compute/guests.go
  pkg/apis/const.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/options/options.go
  pkg/image/models/images.go
  pkg/image/tasks/image_copy_from_url_task.go
  pkg/mcclient/modules/image/mod_images.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/images.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/network.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ramimage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/task.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/bingocloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ecloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/image_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/jdcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nutanix/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/openstack/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/disk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/remotefile/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/storagecache.go
Labels: size/L, area/region, area/image

#17147 Automated cherry pick of #17146: feat(climc): make cloud-provider-clirc supports output format
  cmd/climc/shell/compute/cloudproviders.go
  cmd/climc/shell/helper.go
Labels: size/S

#17150 fix(host): arm cdrom hotplug
  pkg/hostman/guestman/arch/arm.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#17151 Automated cherry pick of #17150: fix(host): arm cdrom hotplug
  pkg/hostman/guestman/arch/arm.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#17154 fix(region): image export
  pkg/compute/guestdrivers/managedvirtual.go
Labels: size/XS, area/region

#17153 fix(region): node pool keypair
  go.mod
  go.sum
  pkg/apis/compute/kube_node_pools.go
  pkg/compute/models/kube_node_pools.go
  pkg/mcclient/options/compute/kube_node_pool.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/kube_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/eks.go
Labels: size/M, area/region

#17156 fix(keystone): fix refreshScopeResourceCount timeout
  pkg/keystone/cronjobs/project_resources.go
Labels: size/XS

#17158 Automated cherry pick of #17156: fix(keystone): fix refreshScopeResourceCount timeout
  pkg/keystone/cronjobs/project_resources.go
Labels: size/XS

#17159 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ramimage.go
Labels: size/S, area/region

#16810 fix(notify): reset notifications
  cmd/climc/shell/notify/notification.go
  pkg/apis/notify/template.go
  pkg/notify/models/event_template.go
  pkg/notify/models/notification.go
  pkg/notify/models/notification_logs.go
  pkg/notify/models/receiver.go
  pkg/notify/models/topic.go
  pkg/notify/tasks/notifications_send_task.go
  pkg/notify/tasks/topic_message_send_task.go
Labels: lgtm, size/XXL

#17162 fix(region): node pool keypair
  pkg/compute/regiondrivers/managedvirtual.go
  pkg/compute/tasks/guest_save_image_task.go
Labels: size/XS, area/region

#17163 fix(region): node pool instance min count
  pkg/compute/models/kube_node_pools.go
Labels: size/S, area/region

#17160 fix(host): get pci controller type
  pkg/hostman/guestman/qemu-kvmhelper.go
Labels: size/XS
