Repository yunionio/cloudpods, pull requests merged in 2024-09, with the labels that each got.

#21131 fix: migrate ipv6 routes from physical interface to bridge
  cmd/climc/shell/compute/networks.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/netutils_linux.go
Labels: lgtm, size/L

#21132 Automated cherry pick of #21131: fix: migrate ipv6 routes from physical interface to bridge
  cmd/climc/shell/compute/networks.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/netutils_linux.go
Labels: size/L

#21133 Automated cherry pick of #21131: fix: migrate ipv6 routes from physical interface to bridge
  cmd/climc/shell/compute/networks.go
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/util/netutils2/netutils_linux.go
Labels: size/L

#21129 fix(region): allow guest create on cannot detect image props
  pkg/compute/models/guests.go
Labels: size/XS

#21134 fix: update vendor for dameng TEXT_EQUAL
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/saml_provider.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/errors.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/conditions.go
Labels: size/L

#21135 Automated cherry pick of #21134: fix: update vendor for dameng TEXT_EQUAL
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/saml_provider.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/errors.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/conditions.go
Labels: size/L

#21136 Automated cherry pick of #21134: fix: update vendor for dameng TEXT_EQUAL
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/saml_provider.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/errors.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/conditions.go
Labels: size/L

#21137 fix(host): duplicated port allocation
  pkg/hostman/guestman/portmapping.go
Labels: size/S, area/host

#21138 Automated cherry pick of #21129: fix(region): allow guest create on cannot detect image props
  pkg/compute/models/guests.go
Labels: size/XS

#21139 Automated cherry pick of #21129: fix(region): allow guest create on cannot detect image props
  pkg/compute/models/guests.go
Labels: size/XS

#21140 optimize(host): wrap updateOrCreateHost error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S, area/host

#21141 Automated cherry pick of #21140: optimize(host): wrap updateOrCreateHost error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#21142 Automated cherry pick of #21140: optimize(host): wrap updateOrCreateHost error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#21126 fix(region): sync worker hashring
  pkg/compute/models/syncworkers.go
Labels: size/S

#21127 Automated cherry pick of #21126: fix(region): sync worker hashring
  pkg/compute/models/syncworkers.go
Labels: size/S

#21128 Automated cherry pick of #21126: fix(region): sync worker hashring
  pkg/compute/models/syncworkers.go
Labels: size/S

#21144 fix: telegraf config file format error
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#21145 Automated cherry pick of #21144: fix: telegraf config file format error
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#21146 Automated cherry pick of #21144: fix: telegraf config file format error
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#21147 Automated cherry pick of #21144: fix: telegraf config file format error
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#21148 Automated cherry pick of #21144: fix: telegraf config file format error
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#21151 fix(climc): hostlocal server type for network-create
  pkg/mcclient/options/compute/network.go
Labels: size/XS, area/climc

#21163 fix(region): allow contailer host update numa cpu allocate with guests running
  pkg/compute/models/hosts.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: lgtm, size/S

#21152 fix(host): rbd save image use /opt/cloud temp dir
  pkg/hostman/storageman/storage_rbd.go
Labels: lgtm, size/S

#21153 Automated cherry pick of #21152: fix(host): rbd save image use /opt/cloud temp dir
  pkg/hostman/storageman/storage_rbd.go
Labels: size/S

#21154 Automated cherry pick of #21152: fix(host): rbd save image use /opt/cloud temp dir
  pkg/hostman/storageman/storage_rbd.go
Labels: size/S

#21155 Automated cherry pick of #21152: fix(host): rbd save image use /opt/cloud temp dir
  pkg/hostman/storageman/storage_rbd.go
Labels: size/S

#21159 fix(region): disk update disk type
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
Labels: size/XS

#21160 Automated cherry pick of #21159: fix(region): disk update disk type
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
Labels: size/XS

#21161 Automated cherry pick of #21159: fix(region): disk update disk type
  cmd/climc/shell/compute/disks.go
  pkg/compute/models/disks.go
Labels: size/XS

#21166 fix: change bandwidth without sync to host
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
Labels: lgtm, size/S

#21165 feat(region,host): set container resources limit
  cmd/climc/shell/compute/containers.go
  pkg/apis/compute/container.go
  pkg/apis/container.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/models/containers.go
  pkg/compute/models/pod_driver.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/podhandlers/podhandlers.go
  pkg/mcclient/options/compute/containers.go
Labels: size/L, area/region, area/host

#21169 fix(monitor): support or filter of query
  go.mod
  go.sum
  vendor/github.com/influxdata/promql/v2/printer.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M, area/monitor

#21170 Automated cherry pick of #21169: fix(monitor): support or filter of query
  go.mod
  go.sum
  vendor/github.com/influxdata/promql/v2/printer.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M

#21171 Automated cherry pick of #21169: fix(monitor): support or filter of query
  go.mod
  go.sum
  vendor/github.com/influxdata/promql/v2/printer.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M

#21164 fix: support apigateway for cloudpods
  pkg/mcclient/cloudpods/cloudpods.go
Labels: size/XS

#21175 feature: allow generate name with a randome string
  pkg/cloudcommon/db/namevalidator.go
  pkg/util/stringutils2/namepattern.go
  pkg/util/stringutils2/namepattern_test.go
Labels: size/M

#21176 fix(host-deployer): update host-deployer-docker base
  build/docker/Dockerfile.host-deployer
Labels: lgtm, size/XS

#21177 Automated cherry pick of #21176: fix(host-deployer): update host-deployer-docker base
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#21178 Automated cherry pick of #21176: fix(host-deployer): update host-deployer-docker base
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#21179 fix(region,host): validate and umount container's backup tar file
  pkg/compute/models/diskbackups.go
  pkg/hostman/guestman/pod.go
Labels: size/M, area/region, area/host

#21172 fix(cloudid): cloud policy sync
  go.mod
  go.sum
  pkg/cloudid/drivers/base.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/tasks/cloudaccount_sync_resources_task.go
  pkg/cloudid/tasks/cloudprovider_sync_resources_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_role.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/pkg/util/cloudinit/cloudconfig.go
Labels: size/L

#21173 Automated cherry pick of #21172: fix(cloudid): cloud policy sync
  go.mod
  go.sum
  pkg/cloudid/drivers/base.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/tasks/cloudaccount_sync_resources_task.go
  pkg/cloudid/tasks/cloudprovider_sync_resources_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_role.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/pkg/util/cloudinit/cloudconfig.go
Labels: size/L

#21174 Automated cherry pick of #21172: fix(cloudid): cloud policy sync
  go.mod
  go.sum
  pkg/cloudid/drivers/base.go
  pkg/cloudid/models/cloudaccount.go
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/cloudpolicy.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/saml/providers/aws/driver.go
  pkg/cloudid/saml/providers/awscn/driver.go
  pkg/cloudid/tasks/cloudaccount_sync_resources_task.go
  pkg/cloudid/tasks/cloudprovider_sync_resources_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_role.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/pkg/util/cloudinit/cloudconfig.go
Labels: size/L

#21181 feat(region,host): ignore not exist files when disk backup
  pkg/apis/compute/backup.go
  pkg/hostman/guestman/pod.go
  pkg/mcclient/options/compute/backup.go
Labels: size/M, area/region, area/host, area/climc

#21180 optimize(apigateway): use climc ssh for cloud shell
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/M, area/webconsole, area/apigateway

#21185 Automated cherry pick of #21180: optimize(apigateway): use climc ssh for cloud shell
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/M

#21186 Automated cherry pick of #21180: optimize(apigateway): use climc ssh for cloud shell
  build/docker/Dockerfile.webconsole
  build/docker/Dockerfile.webconsole-base
  build/docker/Makefile
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/L

#21190 fix: climc server-detach-network --force
  cmd/climc/shell/compute/servernetworks.go
Labels: size/XS

#21191 Automated cherry pick of #21190: fix: climc server-detach-network --force
  cmd/climc/shell/compute/servernetworks.go
Labels: size/XS

#21192 Automated cherry pick of #21190: fix: climc server-detach-network --force
  cmd/climc/shell/compute/servernetworks.go
Labels: size/XS

#21196 feat(apigateway): report k3s environment
  pkg/apigateway/report/report.go
Labels: size/S, area/apigateway

#21197 Automated cherry pick of #21196: feat(apigateway): report k3s environment
  pkg/apigateway/report/report.go
Labels: size/S

#21198 Automated cherry pick of #21196: feat(apigateway): report k3s environment
  pkg/apigateway/report/report.go
Labels: size/S

#21193 fix(log): add offline export i18n
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#21194 Automated cherry pick of #21193: fix(log): add offline export i18n
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#21195 Automated cherry pick of #21193: fix(log): add offline export i18n
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#21199 fix(region): sync remove guest whith network address
  pkg/compute/models/purge.go
Labels: size/XS

#21200 Automated cherry pick of #21199: fix(region): sync remove guest whith network address
  pkg/compute/models/purge.go
Labels: size/XS

#21206 optimized(monitor): keep 2 precision of reduced value
  pkg/monitor/models/commonalert.go
Labels: size/S, area/monitor

#21207 Automated cherry pick of #21206: optimized(monitor): keep 2 precision of reduced value
  pkg/monitor/models/commonalert.go
Labels: size/S

#21208 Automated cherry pick of #21206: optimized(monitor): keep 2 precision of reduced value
  pkg/monitor/models/commonalert.go
Labels: size/S

#21209 Automated cherry pick of #21206: optimized(monitor): keep 2 precision of reduced value
  pkg/monitor/models/commonalert.go
Labels: size/S

#21210 fix(climc): monitor-alert-test-run prints result error
  cmd/climc/shell/monitor/alert.go
  pkg/mcclient/modules/monitor/alert.go
Labels: size/S, area/climc

#21211 Automated cherry pick of #21210: fix(climc): monitor-alert-test-run prints result error
  cmd/climc/shell/monitor/alert.go
  pkg/mcclient/modules/monitor/alert.go
Labels: size/S

#21213 Automated cherry pick of #21210: fix(climc): monitor-alert-test-run prints result error
  cmd/climc/shell/monitor/alert.go
  pkg/mcclient/modules/monitor/alert.go
Labels: size/S

#21214 fix(moniotr): filter dirty resource alerts
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S, area/monitor

#21215 Automated cherry pick of #21214: fix(moniotr): filter dirty resource alerts
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S

#21216 Automated cherry pick of #21214: fix(moniotr): filter dirty resource alerts
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S

#21217 Automated cherry pick of #21214: fix(moniotr): filter dirty resource alerts
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S

#21202 feat(host): add enable_container_cni_portmap option
  pkg/hostman/guestman/pod.go
  pkg/hostman/options/options.go
Labels: size/M, area/host

#21218 feat(monitor): filter monitor_resource_alert by ip
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S, area/monitor

#21219 Automated cherry pick of #21218: feat(monitor): filter monitor_resource_alert by ip
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S

#21220 Automated cherry pick of #21218: feat(monitor): filter monitor_resource_alert by ip
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S

#21221 Automated cherry pick of #21218: feat(monitor): filter monitor_resource_alert by ip
  pkg/mcclient/modules/monitor/mod_monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource_alert.go
  pkg/monitor/models/monitor_resource_alert.go
Labels: size/S

#21222 feat(host,region): add disable_no_new_privs option for container
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/mcclient/options/compute/containers.go
Labels: size/XS, area/region, area/host, area/climc

#21079 1、裸金属删除时，GuestUndeployTask会出现无法调用任务完成方法OnGuestUndeployComplete，导致任务卡住的情况
  pkg/baremetal/manager.go
Labels: size/XS

#21275 fix(region): mount cephfs for pod
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/compute/container_drivers/volume_mount/cephfs.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/containers.go
  pkg/compute/models/filesystem.go
  pkg/hostman/container/volume_mount/cephfs.go
  pkg/mcclient/options/compute/containers.go
Labels: size/L

#21284 feat(region,host): commit container to image repository
  build/docker/Dockerfile.host
  build/docker/multi-arch/Dockerfile.host
  cmd/climc/shell/compute/containers.go
  pkg/apis/compute/container.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/models/containers.go
  pkg/compute/models/pod_driver.go
  pkg/compute/tasks/container_commit_task.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
  pkg/hostman/guestman/podhandlers/podhandlers.go
  pkg/mcclient/options/compute/containers.go
  pkg/util/pod/image/image.go
  pkg/util/pod/nerdctl/doc.go
  pkg/util/pod/nerdctl/nerdctl.go
Labels: size/XL

#21287 fix(region): filter cloudproviders by regional network zone
  pkg/compute/models/cloudproviders.go
Labels: size/S

#21289 Automated cherry pick of #21287: fix(region): filter cloudproviders by regional network zone
  pkg/compute/models/cloudproviders.go
Labels: size/S

#21290 Automated cherry pick of #21287: fix(region): filter cloudproviders by regional network zone
  pkg/compute/models/cloudproviders.go
Labels: size/S

#21285 fix(host): container custom cpufreq
  pkg/hostman/guestman/pod.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
Labels: lgtm, size/L

#21291 feat(host): pod volume metrics
  pkg/hostman/container/volume_mount/disk.go
  pkg/hostman/container/volume_mount/interface.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
  pkg/hostman/hostmetrics/container_metrics.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/monitor/dbinit/metric_dbinit.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_aix.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_aix_cgo.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_aix_nocgo.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_darwin.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_darwin_cgo.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_darwin_nocgo.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_fallback.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_freebsd.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_freebsd_386.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_freebsd_amd64.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_freebsd_arm.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_freebsd_arm64.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_linux.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_openbsd.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_openbsd_386.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_openbsd_amd64.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_openbsd_arm.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_openbsd_arm64.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_solaris.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_unix.go
  vendor/github.com/shirou/gopsutil/v3/disk/disk_windows.go
  vendor/github.com/shirou/gopsutil/v3/disk/iostat_darwin.c
  vendor/github.com/shirou/gopsutil/v3/disk/iostat_darwin.h
  vendor/modules.txt
Labels: size/XXL, area/host, area/monitor

#21292 fix(region): vendor update for cephfs http
  cmd/climc/shell/misc/feature.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cephfs/client.go
Labels: size/S

#21294 fix(webconsole): close session when ssh session closed
  pkg/webconsole/server/ssh_server.go
Labels: size/XS

#21297 Automated cherry pick of #21294: fix(webconsole): close session when ssh session closed
  pkg/webconsole/server/ssh_server.go
Labels: size/XS

#21296 Automated cherry pick of #21294: fix(webconsole): close session when ssh session closed
  pkg/webconsole/server/ssh_server.go
Labels: size/XS

#21298 fix(host): wrap cephfs umount error
  pkg/hostman/container/volume_mount/cephfs.go
Labels: size/S, area/host

#21299 fix(host): remove cephfs dir
  pkg/hostman/container/volume_mount/cephfs.go
Labels: size/XS

#21302 fix(host): set container namespace options
  pkg/hostman/guestman/pod.go
Labels: size/S

#21305 fix(host): pod volume usage panic
  pkg/hostman/guestman/pod_helper.go
Labels: size/XS, area/host

#21307 fix(host): wrap lsof error when doing umount
  pkg/util/mountutils/mount.go
Labels: size/S, area/host

#21308 fix(host): check qga is init on check qga runing
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#21309 Automated cherry pick of #21308: fix(host): check qga is init on check qga runing
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#21310 Automated cherry pick of #21308: fix(host): check qga is init on check qga runing
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#21311 Automated cherry pick of #21308: fix(host): check qga is init on check qga runing
  pkg/hostman/guestman/guestman.go
Labels: size/XS

#20996 fix(region,host): lvm snapshot delete and create from backup
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#21312 Automated cherry pick of #20996: fix(region,host): lvm snapshot delete and create from backup
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#21313 Automated cherry pick of #21312: Automated cherry pick of #20996: fix(region,host): lvm snapshot delete and create from backup
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#21314 Automated cherry pick of #21313: Automated cherry pick of #21312: Automated cherry pick of #20996: fix(region,host): lvm snapshot delete and create from backup
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#21316 Automated cherry pick of #21313: Automated cherry pick of #21312: Automated cherry pick of #20996: fix(region,host): lvm snapshot delete and create from backup
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/snapshot_delete_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/isolated_device/gpu.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
  pkg/hostman/storageman/storagehelper.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/L

#21321 fix(region): add hypervisor props on isolated device capabilites
  pkg/apis/compute/isolated_device_const.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/isolated_devices.go
Labels: size/M

#21324 Automated cherry pick of #21323: fix(region): make parseDeviceInfo error clear
  pkg/compute/models/isolated_devices.go
Labels: size/XS

#21325 Automated cherry pick of #21323: fix(region): make parseDeviceInfo error clear
  pkg/compute/models/isolated_devices.go
Labels: size/XS

#21326 Automated cherry pick of #21323: fix(region): make parseDeviceInfo error clear
  pkg/compute/models/isolated_devices.go
Labels: size/XS

#21323 fix(region): make parseDeviceInfo error clear
  pkg/compute/models/isolated_devices.go
Labels: size/XS, area/region

#21330 Automated cherry pick of #21327: fix: host report ovs kmod version and ksm status
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/lbagent/service.go
Labels: size/M

#21329 Automated cherry pick of #21327: fix: host report ovs kmod version and ksm status
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/lbagent/service.go
Labels: size/M

#21328 Automated cherry pick of #21327: fix: host report ovs kmod version and ksm status
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/lbagent/service.go
Labels: size/M

#21327 fix: host report ovs kmod version and ksm status
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/lbagent/service.go
Labels: size/M

#21322 fix(host): cephfs usage
  pkg/hostman/container/volume_mount/cephfs.go
Labels: size/XS

#21335 fix(host): refact qga connection ops
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/L

#21336 Automated cherry pick of #21335: fix(host): refact qga connection ops
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/L

#21337 Automated cherry pick of #21335: fix(host): refact qga connection ops
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/L

#21338 Automated cherry pick of #21335: fix(host): refact qga connection ops
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/L

#21331 fix(host): rename cephfs id
  pkg/hostman/container/volume_mount/cephfs.go
Labels: size/XS

#21333 fix(region,host): set timeout to 1s when stopping container
  pkg/compute/tasks/pod_stop_task.go
  pkg/hostman/guestman/pod.go
Labels: size/XS, area/region, area/host
