Repository yunionio/cloudpods, pull requests merged in 2024-08, with the labels that each got.

#20940 Automated cherry pick of #20847: feat(monitor): add inodes_used_percent metric
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#20946 fix(region,scheduler): sub pending usage on select cpu numa pin
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/manager/task_queue.go
  pkg/scheduler/models/pending_usage.go
Labels: lgtm, size/L

#20947 Automated cherry pick of #20946: fix(region,scheduler): sub pending usage on select cpu numa pin
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/manager/task_queue.go
  pkg/scheduler/models/pending_usage.go
Labels: size/L

#20948 Automated cherry pick of #20946: fix(region,scheduler): sub pending usage on select cpu numa pin
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_stop_task.go
  pkg/scheduler/api/sched.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/manager/task_queue.go
  pkg/scheduler/models/pending_usage.go
Labels: size/L

#20949 feat(host): cpuset for container of pod
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/runtime.go
Labels: lgtm, size/S, area/host

#20955 fix(host): too much qga ping logs
  pkg/hostman/monitor/qga/qga.go
Labels: lgtm, size/XS

#20956 Automated cherry pick of #20955: fix(host): too much qga ping logs
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#20957 Automated cherry pick of #20955: fix(host): too much qga ping logs
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#20958 Automated cherry pick of #20955: fix(host): too much qga ping logs
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#20959 Automated cherry pick of #20955: fix(host): too much qga ping logs
  pkg/hostman/monitor/qga/qga.go
Labels: size/XS

#20961 fix(host-deployer): add cpu mem hotplug udev rules
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: lgtm, size/S

#20962 Automated cherry pick of #20961: fix(host-deployer): add cpu mem hotplug udev rules
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#20963 Automated cherry pick of #20961: fix(host-deployer): add cpu mem hotplug udev rules
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#20964 feat(region): select isolated_device by most unused device_path count
  pkg/compute/models/isolated_devices.go
Labels: lgtm, size/S, area/region

#20965 feat(region,host): inject host ips as container environment variables
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/pod.go
Labels: size/M, area/region, area/host

#20941 fix(region): show status info with list api
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guests.go
Labels: size/M, area/region

#20942 Automated cherry pick of #20941: fix(region): show status info with list api
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guests.go
Labels: size/M

#20943 Automated cherry pick of #20941: fix(region): show status info with list api
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guests.go
Labels: size/M

#20944 Automated cherry pick of #20941: fix(region): show status info with list api
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guests.go
Labels: size/M

#20927 fix(region): send notify when vpc or network created
  pkg/cloudcommon/db/infraresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S, area/region

#20928 Automated cherry pick of #20927: fix(region): send notify when vpc or network created
  pkg/cloudcommon/db/infraresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S

#20929 Automated cherry pick of #20927: fix(region): send notify when vpc or network created
  pkg/cloudcommon/db/infraresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S

#20930 Automated cherry pick of #20927: fix(region): send notify when vpc or network created
  pkg/cloudcommon/db/infraresource.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
Labels: size/S

#20973 fix(region): vendor update for lb backend sync
  go.mod
  go.sum
  pkg/compute/models/loadbalancerbackends.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: lgtm, size/M

#20974 Automated cherry pick of #20973: fix(region): vendor update for lb backend sync
  go.mod
  go.sum
  pkg/compute/models/loadbalancerbackends.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/M

#20975 Automated cherry pick of #20973: fix(region): vendor update for lb backend sync
  go.mod
  go.sum
  pkg/compute/models/loadbalancerbackends.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/proxmox/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
Labels: size/L

#20976 Automated cherry pick of #20961: fix(host-deployer): add cpu mem hotplug udev rules
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#20980 Fix/contaier alloc cpuset optimize sync isolated device
  pkg/compute/models/guests.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/runtime.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: lgtm, size/L

#20950 fix(host): clean image cache check local reference
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/imagecache_clean.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
Labels: lgtm, size/L

#20951 Automated cherry pick of #20950: fix(host): clean image cache check local reference
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/imagecache_clean.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
Labels: size/L

#20952 Automated cherry pick of #20950: fix(host): clean image cache check local reference
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/imagecache_clean.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
Labels: size/L

#20953 Automated cherry pick of #20950: fix(host): clean image cache check local reference
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/imagecache_clean.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
Labels: size/L

#20983 fix(region): validate guestdisk cache/io mode on upadte
  pkg/compute/models/guestdisks.go
Labels: lgtm, size/S

#20984 Automated cherry pick of #20983: fix(region): validate guestdisk cache/io mode on upadte
  pkg/compute/models/guestdisks.go
Labels: size/S

#20985 Automated cherry pick of #20983: fix(region): validate guestdisk cache/io mode on upadte
  pkg/compute/models/guestdisks.go
Labels: size/S

#20986 Automated cherry pick of #20983: fix(region): validate guestdisk cache/io mode on upadte
  pkg/compute/models/guestdisks.go
Labels: size/S

#20804 fix(region): auto clean invalid cached images
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/cachedimages.go
Labels: lgtm, size/L

#20815 Automated cherry pick of #20804: fix(region): auto clean invalid cached images
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/cachedimages.go
Labels: size/L

#20816 Automated cherry pick of #20804: fix(region): auto clean invalid cached images
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/cachedimages.go
Labels: size/L

#20817 Automated cherry pick of #20804: fix(region): auto clean invalid cached images
  pkg/cloudcommon/db/fetch.go
  pkg/compute/models/cachedimages.go
Labels: size/L

#20988 fix(host): isolated device probe closure reference for range val
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#20989 Automated cherry pick of #20941: fix(region): show status info with list api
  pkg/cloudcommon/db/virtualresource.go
  pkg/compute/models/guests.go
Labels: size/M

#20987 feat(host): support vastaitech gpu for container
  pkg/apis/compute/container.go
  pkg/apis/compute/isolated_device_const.go
  pkg/compute/models/guestdisks.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/container_device.go
  pkg/hostman/isolated_device/container_device/base_dev.go
  pkg/hostman/isolated_device/container_device/cph_amd_gpu.go
  pkg/hostman/isolated_device/container_device/cph_amd_gpu_test.go
  pkg/hostman/isolated_device/container_device/vastaitech_gpu.go
Labels: size/L, area/host

#21002 fix(host): unmount target busy device of container
  pkg/hostman/container/storage/storage.go
Labels: area/host

#21016 fix(region): sync kvm secgroup status
  pkg/compute/models/secgroups.go
Labels: size/XS

#21017 Automated cherry pick of #21016: fix(region): sync kvm secgroup status
  pkg/compute/models/secgroups.go
Labels: size/XS

#21019 Automated cherry pick of #21016: fix(region): sync kvm secgroup status
  pkg/compute/models/secgroups.go
Labels: size/XS

#21018 Automated cherry pick of #21016: fix(region): sync kvm secgroup status
  pkg/compute/models/secgroups.go
Labels: size/XS

#21012 fix: allow enable auto alloc for host-local net
  pkg/compute/models/networks.go
Labels: lgtm, size/XS

#21024 fix(readme): TLS certificates typo
  README-CN.md
  README.md
Labels: size/XS

#21029 fix: support keylike search
  pkg/apis/metadata.go
  pkg/cloudcommon/db/metadata.go
Labels: lgtm, size/XS

#21030 Automated cherry pick of #21029: fix: support keylike search
  pkg/apis/metadata.go
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#21031 Automated cherry pick of #21029: fix: support keylike search
  pkg/apis/metadata.go
  pkg/cloudcommon/db/metadata.go
Labels: size/XS

#21033 fix: filter islated devices capability info by zone
  pkg/compute/models/capabilities.go
Labels: lgtm, size/XS

#21034 Automated cherry pick of #21033: fix: filter islated devices capability info by zone
  pkg/compute/models/capabilities.go
Labels: size/XS

#21035 Automated cherry pick of #21033: fix: filter islated devices capability info by zone
  pkg/compute/models/capabilities.go
Labels: size/XS

#21036 Automated cherry pick of #21033: fix: filter islated devices capability info by zone
  pkg/compute/models/capabilities.go
Labels: size/XS

#21032 fix: register metadatas for identity and glance
  pkg/mcclient/modules/compute/mod_metadatas.go
Labels: size/XS

#21025 fix(host): ignore nil host_port of portmapping error
  pkg/hostman/guestman/portmapping.go
  pkg/util/netutils2/getport/getport.go
Labels: size/S, area/host

#21011 feat(region,host): startup probe of container
  cmd/climc/shell/events/events.go
  pkg/apis/compute/container.go
  pkg/apis/compute/guests.go
  pkg/apis/container.go
  pkg/apis/container_probe.go
  pkg/compute/models/containers.go
  pkg/compute/models/guest_queries.go
  pkg/hostman/container/prober/doc.go
  pkg/hostman/container/prober/prober.go
  pkg/hostman/container/prober/prober_manager.go
  pkg/hostman/container/prober/results/doc.go
  pkg/hostman/container/prober/results/results_manager.go
  pkg/hostman/container/prober/worker.go
  pkg/hostman/container/status/doc.go
  pkg/hostman/container/status/status_manager.go
  pkg/hostman/guestman/container/doc.go
  pkg/hostman/guestman/container/runtime.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/hostinfo/container.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/exec/doc.go
  pkg/util/exec/exec.go
  pkg/util/ioutils/doc.go
  pkg/util/ioutils/ioutils.go
  pkg/util/probe/doc.go
  pkg/util/probe/exec/doc.go
  pkg/util/probe/exec/errors.go
  pkg/util/probe/exec/exec.go
  pkg/util/probe/exec/exec_test.go
  pkg/util/probe/probe.go
  pkg/util/probe/tcp/doc.go
  pkg/util/probe/tcp/tcp.go
  pkg/util/probe/tcp/tcp_test.go
Labels: size/XXL, area/region, area/host

#21038 feat(host): start and stop container in worker
  pkg/hostman/container/status/status_manager.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/podhandlers/podhandlers.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/runtime.go
Labels: size/L, area/host

#21039 fix(region,host,host-deployer): deploy guest ssh port add lock
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestman/guesthelper.go
Labels: lgtm, size/S

#21040 Automated cherry pick of #21039: fix(region,host,host-deployer): deploy guest ssh port add lock
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestman/guesthelper.go
Labels: size/S

#21041 Automated cherry pick of #21039: fix(region,host,host-deployer): deploy guest ssh port add lock
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestman/guesthelper.go
Labels: size/S

#21026 fix(region): try recover image cache on guest migrate
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: lgtm, size/L

#21027 Automated cherry pick of #21026: fix(region): try recover image cache on guest migrate
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: size/L

#21028 Automated cherry pick of #21026: fix(region): try recover image cache on guest migrate
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: size/L

#21051 feat(host): set cgroup pids.max of container
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/util/pod/cgroup.go
Labels: size/S, area/host

#21046 fix(cloudmon): 避免cloudmon任务堆积导致大量请求
  pkg/cloudmon/resources/resources.go
Labels: size/S

#21047 Automated cherry pick of #21046: fix(cloudmon): 避免cloudmon任务堆积导致大量请求
  pkg/cloudmon/resources/resources.go
Labels: size/S

#21048 Automated cherry pick of #21046: fix(cloudmon): 避免cloudmon任务堆积导致大量请求
  pkg/cloudmon/resources/resources.go
Labels: size/S

#21049 Automated cherry pick of #21046: fix(cloudmon): 避免cloudmon任务堆积导致大量请求
  pkg/cloudmon/resources/resources.go
Labels: size/S

#21042 fix(host): migrate slave addresses and routes from physical nic to bridge
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/util/iproute2/address_linux.go
  pkg/util/iproute2/route_linux.go
  pkg/util/netutils2/bonding.go
  pkg/util/netutils2/netutils_linux.go
  pkg/util/netutils2/netutils_others.go
  pkg/util/netutils2/netutils_test.go
Labels: size/L

#21043 Automated cherry pick of #21042: fix(host): migrate slave addresses and routes from physical nic to bridge
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/util/iproute2/address_linux.go
  pkg/util/iproute2/route_linux.go
  pkg/util/netutils2/bonding.go
  pkg/util/netutils2/netutils_linux.go
  pkg/util/netutils2/netutils_others.go
  pkg/util/netutils2/netutils_test.go
Labels: size/L

#21044 Automated cherry pick of #21042: fix(host): migrate slave addresses and routes from physical nic to bridge
  pkg/hostman/hostinfo/hostbridge/hostbridge.go
  pkg/hostman/hostinfo/hostinfohelper.go
  pkg/util/iproute2/address_linux.go
  pkg/util/iproute2/route_linux.go
  pkg/util/netutils2/bonding.go
  pkg/util/netutils2/netutils_linux.go
  pkg/util/netutils2/netutils_others.go
  pkg/util/netutils2/netutils_test.go
Labels: size/L

#21057 fix(climc): add VALID_CONTAINER_DEVICE_TYPES for isolated device parser
  pkg/cloudcommon/cmdline/parser.go
Labels: size/XS, area/climc

#21074 Automated cherry pick of #21073: optimze(baremetal): dhcp prefix hints
  pkg/baremetal/pxe/dhcp.go
Labels: size/XS

#21075 Automated cherry pick of #21073: optimze(baremetal): dhcp prefix hints
  pkg/baremetal/pxe/dhcp.go
Labels: size/XS

#21072 feat(monitor): result reducer for query result
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/reducer.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/options/monitor/unifiedmonitor.go
  pkg/mcclient/options/monitor/unifiedmonitor_test.go
  pkg/monitor/alerting/conditions/commonalertreducer.go
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/suggestrulereducer.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/validators/validators.go
Labels: size/L, area/monitor

#21076 Automated cherry pick of #21072: feat(monitor): result reducer for query result
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/reducer.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/options/monitor/unifiedmonitor.go
  pkg/mcclient/options/monitor/unifiedmonitor_test.go
  pkg/monitor/alerting/conditions/commonalertreducer.go
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/suggestrulereducer.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/validators/validators.go
Labels: size/L

#21077 Automated cherry pick of #21072: feat(monitor): result reducer for query result
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/reducer.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/mcclient/options/monitor/unifiedmonitor.go
  pkg/mcclient/options/monitor/unifiedmonitor_test.go
  pkg/monitor/alerting/conditions/commonalertreducer.go
  pkg/monitor/alerting/conditions/mathreducer.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/conditions/reducer.go
  pkg/monitor/alerting/conditions/suggestrulereducer.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/validators/validators.go
Labels: size/L

#21080 fix(monitor): container host alerting is not working
  pkg/hostman/hostinfo/hostconsts/hostconsts.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource_sync.go
Labels: size/S, area/monitor

#21081 fix(region): set container probe_failed status when exited
  pkg/compute/models/containers.go
Labels: size/XS, area/region

#21083 Automated cherry pick of #19260: fix(region): dns record update with enabled params
  pkg/compute/tasks/dns_record_update_task.go
Labels: size/XS

#21082 fix: extend query with metadata field
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S

#21085 Automated cherry pick of #21082: fix: extend query with metadata field
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S

#21084 Automated cherry pick of #21082: fix: extend query with metadata field
  pkg/cloudcommon/db/metadataresource.go
Labels: size/S

#21045 feat(host): start dirty shutdown pod and container
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/options/options.go
Labels: size/L, area/host

#21090 fix: host save host_local net confs in file
  pkg/hostman/hostinfo/finalize_network.go
  pkg/hostman/options/options.go
Labels: size/S

#21086 fix(region): set security group domain id
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: lgtm, size/XS

#21092 Automated cherry pick of #21086: fix(region): set security group domain id
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#21093 Automated cherry pick of #21086: fix(region): set security group domain id
  pkg/compute/regiondrivers/google.go
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#21094 fix(host): nbd worker count add options
  pkg/cloudcommon/options/options.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: lgtm, size/S

#21095 Automated cherry pick of #21094: fix(host): nbd worker count add options
  pkg/cloudcommon/options/options.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#21096 Automated cherry pick of #21094: fix(host): nbd worker count add options
  pkg/cloudcommon/options/options.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#21097 Automated cherry pick of #21094: fix(host): nbd worker count add options
  pkg/cloudcommon/options/options.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/S

#21098 fix(monitor): only show MEAN and SUM aggregators
  pkg/apis/monitor/unifiedmonitor_query.go
Labels: size/XS, area/monitor

#21099 Automated cherry pick of #21098: fix(monitor): only show MEAN and SUM aggregators
  pkg/apis/monitor/unifiedmonitor_query.go
Labels: size/XS

#21100 Automated cherry pick of #21098: fix(monitor): only show MEAN and SUM aggregators
  pkg/apis/monitor/unifiedmonitor_query.go
Labels: size/XS

#21101 Automated cherry pick of #21098: fix(monitor): only show MEAN and SUM aggregators
  pkg/apis/monitor/unifiedmonitor_query.go
Labels: size/XS

#21102 fix(region): sync aliyun gtm and aws traffic policy address
  go.mod
  go.sum
  pkg/compute/models/dnsrecords.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/dns_domain_record.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/gtm.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/gtm3.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/private_zone_record.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dns_traffic_policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnsrecord.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/dnspod_record.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: lgtm, size/L

#21103 Automated cherry pick of #21102: fix(region): sync aliyun gtm and aws traffic policy address
  go.mod
  go.sum
  pkg/compute/models/dnsrecords.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/dns_domain_record.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/gtm.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/gtm3.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/private_zone_record.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/aws_request.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dns_traffic_policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dnsrecord.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/dnspod_record.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
  vendor/yunion.io/x/sqlchemy/query.go
Labels: size/L

#21105 fix(monitor): skipCheckSeries when aggregator is sum
  pkg/monitor/alerting/conditions/metricquery.go
Labels: size/S

#21106 Automated cherry pick of #21105: fix(monitor): skipCheckSeries when aggregator is sum
  pkg/monitor/alerting/conditions/metricquery.go
Labels: size/S

#21107 Automated cherry pick of #21105: fix(monitor): skipCheckSeries when aggregator is sum
  pkg/monitor/alerting/conditions/metricquery.go
Labels: size/S

#21111 fix(climc): host-ssh is not working
  cmd/climc/shell/compute/hosts.go
Labels: size/XS, area/climc

#21112 Automated cherry pick of #21111: fix(climc): host-ssh is not working
  cmd/climc/shell/compute/hosts.go
Labels: size/XS

#21114 Automated cherry pick of #21111: fix(climc): host-ssh is not working
  cmd/climc/shell/compute/hosts.go
Labels: size/XS

#21115 fix(monitor): delete default group by and mean aggregator
  go.mod
  go.sum
  pkg/monitor/models/unifiedmonitor.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M, area/monitor

#21116 Automated cherry pick of #21115: fix(monitor): delete default group by and mean aggregator
  go.mod
  go.sum
  pkg/monitor/models/unifiedmonitor.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M

#21117 Automated cherry pick of #21115: fix(monitor): delete default group by and mean aggregator
  go.mod
  go.sum
  pkg/monitor/models/unifiedmonitor.go
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M
