Repository yunionio/cloudpods, pull requests merged in 2024-06, with the labels that each got.

#20435 Automated cherry pick of #20433: fix(keystone): avoid panic
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#20434 Automated cherry pick of #20433: fix(keystone): avoid panic
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#20433 fix(keystone): avoid panic
  pkg/keystone/models/identity_provider.go
Labels: size/XS

#20429 feat(monitor): remove precision of float when using max or min function
  pkg/monitor/alerting/conditions/reducer.go
Labels: size/S, area/monitor

#20430 Automated cherry pick of #20429: feat(monitor): remove precision of float when using max or min function
  pkg/monitor/alerting/conditions/reducer.go
Labels: size/S

#20431 Automated cherry pick of #20429: feat(monitor): remove precision of float when using max or min function
  pkg/monitor/alerting/conditions/reducer.go
Labels: size/S

#20432 Automated cherry pick of #20429: feat(monitor): remove precision of float when using max or min function
  pkg/monitor/alerting/conditions/reducer.go
Labels: size/S

#20439 fix(host): bind mount regular file when backing up volume mount of pod
  pkg/hostman/guestman/pod.go
Labels: size/S, area/host

#20440 fix(host): delete container snapshot panic
  pkg/hostman/guestman/guestman.go
Labels: size/S, area/host

#20441 fix: missing goarch env
  scripts/docker_push.sh
Labels: lgtm, size/XS

#20442 Automated cherry pick of #20441: fix: missing goarch env
  scripts/docker_push.sh
Labels: size/XS

#20445 fix(region): sync waf ssl and cc list
  go.mod
  go.sum
  pkg/compute/models/waf_instances.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/waf_domain.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/waf_v2_domains.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/waf.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
Labels: size/L

#20446 Automated cherry pick of #20445: fix(region): sync waf ssl and cc list
  go.mod
  go.sum
  pkg/compute/models/waf_instances.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/waf_domain.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/waf_v2_domains.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/waf.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
Labels: size/L

#20447 Automated cherry pick of #20445: fix(region): sync waf ssl and cc list
  go.mod
  go.sum
  pkg/compute/models/waf_instances.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/waf_domain.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/waf_v2_domains.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/waf.go
  vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
Labels: size/L

#20453 fix(keystone): enable user
  cmd/climc/shell/identity/projects.go
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/users.go
  pkg/mcclient/modules/identity/mod_users.go
Labels: size/M

#20454 Automated cherry pick of #20453: fix(keystone): enable user
  cmd/climc/shell/identity/projects.go
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/users.go
  pkg/mcclient/modules/identity/mod_users.go
Labels: size/M

#20455 Automated cherry pick of #20453: fix(keystone): enable user
  cmd/climc/shell/identity/projects.go
  cmd/climc/shell/identity/users.go
  pkg/apis/identity/input.go
  pkg/keystone/models/projects.go
  pkg/keystone/models/users.go
  pkg/mcclient/modules/identity/mod_users.go
Labels: size/M

#20448 fix(host-deployer): split guest dns by comma
  pkg/util/netutils2/netutils.go
Labels: size/XS

#20449 Automated cherry pick of #20448: fix(host-deployer): split guest dns by comma
  pkg/util/netutils2/netutils.go
Labels: size/XS

#20450 Automated cherry pick of #20448: fix(host-deployer): split guest dns by comma
  pkg/util/netutils2/netutils.go
Labels: size/XS

#20451 Automated cherry pick of #20448: fix(host-deployer): split guest dns by comma
  pkg/util/netutils2/netutils.go
Labels: size/XS

#20452 Automated cherry pick of #20448: fix(host-deployer): split guest dns by comma
  pkg/util/netutils2/netutils.go
Labels: size/XS

#20459 feat(region,climc): support backup_id option for disk-rebuild command
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/compute/disks.go
Labels: size/S, area/region, area/climc

#20456 fix(host-deployer): deploy telegraf systemd service type simple
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/userdata.go
Labels: size/S

#20458 Automated cherry pick of #20456: fix(host-deployer): deploy telegraf systemd service type simple
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/userdata.go
Labels: size/S

#20436 fix(keystone): avoid sync remove disabled ldap user
  pkg/keystone/driver/ldap/info.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/options/options.go
Labels: size/S

#20437 Automated cherry pick of #20436: fix(keystone): avoid sync remove disabled ldap user
  pkg/keystone/driver/ldap/info.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/options/options.go
Labels: size/S

#20438 Automated cherry pick of #20436: fix(keystone): avoid sync remove disabled ldap user
  pkg/keystone/driver/ldap/info.go
  pkg/keystone/driver/ldap/sync.go
  pkg/keystone/options/options.go
Labels: size/S

#20460 fix: disable webconsole watermark by default
  pkg/webconsole/options/options.go
Labels: size/XS

#20461 Automated cherry pick of #20460: fix: disable webconsole watermark by default
  pkg/webconsole/options/options.go
Labels: size/XS

#20462 Automated cherry pick of #20460: fix: disable webconsole watermark by default
  pkg/webconsole/options/options.go
Labels: size/XS

#20465 fix(region): sync cloudpods host storage driver
  go.mod
  go.sum
  pkg/compute/models/hosts.go
  pkg/mcclient/cloudpods/host.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/mongodb_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/host_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/mongodb.go
Labels: size/S

#20466 Automated cherry pick of #20465: fix(region): sync cloudpods host storage driver
  go.mod
  go.sum
  pkg/compute/models/hosts.go
  pkg/mcclient/cloudpods/host.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/mongodb_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/host_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/mongodb.go
Labels: size/S

#20464 fix(region): mongodb processing status
  pkg/apis/compute/mongodb_const.go
  pkg/multicloud/qcloud/mongodb.go
Labels: size/XS

#20467 fix(keystone): show user group info for user
  pkg/apis/identity/user.go
  pkg/keystone/models/users.go
Labels: size/M

#20468 Automated cherry pick of #20467: fix(keystone): show user group info for user
  pkg/apis/identity/user.go
  pkg/keystone/models/users.go
Labels: size/M

#20469 Automated cherry pick of #20467: fix(keystone): show user group info for user
  pkg/apis/identity/user.go
  pkg/keystone/models/users.go
Labels: size/M

#20475 fix(baremetal-agent): avoid dead lock
  pkg/baremetal/manager.go
Labels: size/XS

#20476 Automated cherry pick of #20475: fix(baremetal-agent): avoid dead lock
  pkg/baremetal/manager.go
Labels: size/XS

#20477 Automated cherry pick of #20475: fix(baremetal-agent): avoid dead lock
  pkg/baremetal/manager.go
Labels: size/XS

#20478 Automated cherry pick of #20475: fix(baremetal-agent): avoid dead lock
  pkg/baremetal/manager.go
Labels: size/XS

#20471 fix(region): update cachedimage limit
  pkg/compute/hostdrivers/bingocloud.go
  pkg/compute/hostdrivers/cloudpods-baremetal.go
  pkg/compute/hostdrivers/cloudpods-esxi.go
  pkg/compute/hostdrivers/cloudpods-kvm.go
  pkg/compute/hostdrivers/incloudsphere.go
  pkg/compute/hostdrivers/nutanix.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/proxmox.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/remotefile.go
  pkg/compute/hostdrivers/volcengine.go
Labels: size/S

#20472 Automated cherry pick of #20471: fix(region): update cachedimage limit
  pkg/compute/hostdrivers/bingocloud.go
  pkg/compute/hostdrivers/cloudpods-baremetal.go
  pkg/compute/hostdrivers/cloudpods-esxi.go
  pkg/compute/hostdrivers/cloudpods-kvm.go
  pkg/compute/hostdrivers/incloudsphere.go
  pkg/compute/hostdrivers/nutanix.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/proxmox.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/remotefile.go
  pkg/compute/hostdrivers/volcengine.go
Labels: size/S

#20473 Automated cherry pick of #20471: fix(region): update cachedimage limit
  pkg/compute/hostdrivers/bingocloud.go
  pkg/compute/hostdrivers/cloudpods.go
  pkg/compute/hostdrivers/incloudsphere.go
  pkg/compute/hostdrivers/nutanix.go
  pkg/compute/hostdrivers/openstack.go
  pkg/compute/hostdrivers/proxmox.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/remotefile.go
  pkg/compute/hostdrivers/volcengine.go
Labels: size/S

#20470 feat(region,baremetal,climc): support baremetal root disk matcher
  pkg/apis/compute/api.go
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L, area/baremetal, area/region, area/climc

#20474 Automated cherry pick of #20470: feat(region,baremetal,climc): support baremetal root disk matcher
  pkg/apis/compute/api.go
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20479 Automated cherry pick of #20470: feat(region,baremetal,climc): support baremetal root disk matcher
  pkg/apis/compute/api.go
  pkg/baremetal/manager.go
  pkg/baremetal/utils/disktool/disktool.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/models/guests.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20481 fix: disk rebuild with parameters
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
Labels: size/M, area/region

#20483 fix(region): cloudpods baremetal rebuild root
  pkg/compute/guestdrivers/cloudpods-baremetals.go
Labels: size/S

#20484 Automated cherry pick of #20483: fix(region): cloudpods baremetal rebuild root
  pkg/compute/guestdrivers/cloudpods-baremetals.go
Labels: size/S

#20495 fix: disk backup details missing components
  pkg/apis/compute/backup.go
Labels: size/XS

#20488 fix(region): container is not started when pod's flavor changed
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_config_task.go
Labels: size/S, area/region

#20489 Automated cherry pick of #20488: fix(region): container is not started when pod's flavor changed
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_config_task.go
Labels: size/S

#20499 Automated cherry pick of #20495: fix: disk backup details missing components
  pkg/apis/compute/backup.go
Labels: size/XS

#20498 Automated cherry pick of #20495: fix: disk backup details missing components
  pkg/apis/compute/backup.go
Labels: size/XS

#20497 Automated cherry pick of #20495: fix: disk backup details missing components
  pkg/apis/compute/backup.go
Labels: size/XS

#20496 Automated cherry pick of #20495: fix: disk backup details missing components
  pkg/apis/compute/backup.go
Labels: size/XS

#20500 fix(host-deployer): extend volume before extend filesystem
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/XS

#20504 Automated cherry pick of #20500: fix(host-deployer): extend volume before extend filesystem
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/XS

#20503 Automated cherry pick of #20500: fix(host-deployer): extend volume before extend filesystem
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/XS

#20502 Automated cherry pick of #20500: fix(host-deployer): extend volume before extend filesystem
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/XS

#20501 Automated cherry pick of #20500: fix(host-deployer): extend volume before extend filesystem
  pkg/hostman/guestfs/fsdriver/winscripts.go
Labels: size/XS

#20505 fix(host): parse qga command and args
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/S

#20506 Automated cherry pick of #20505: fix(host): parse qga command and args
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/S

#20507 Automated cherry pick of #20505: fix(host): parse qga command and args
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/S

#20508 Automated cherry pick of #20505: fix(host): parse qga command and args
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/S

#20490 Automated cherry pick of #20488: fix(region): container is not started when pod's flavor changed
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/virtualization.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_config_task.go
Labels: size/S

#20485 fix(region): reset password for cloudpods baremetal
  pkg/compute/guestdrivers/cloudpods-baremetals.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/S

#20486 Automated cherry pick of #20485: fix(region): reset password for cloudpods baremetal
  pkg/compute/guestdrivers/cloudpods-baremetals.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/S

#20509 fix(notify): fix mobile validate
  pkg/apis/notify/config.go
  pkg/notify/sender/smsdriver/aliyun.go
  pkg/notify/sender/smsdriver/huawei.go
Labels: size/S

#20510 Automated cherry pick of #20509: fix(notify): fix mobile validate
  pkg/apis/notify/config.go
  pkg/notify/sender/smsdriver/aliyun.go
  pkg/notify/sender/smsdriver/huawei.go
Labels: size/S

#20511 Automated cherry pick of #20509: fix(notify): fix mobile validate
  pkg/apis/notify/config.go
  pkg/notify/sender/smsdriver/aliyun.go
  pkg/notify/sender/smsdriver/huawei.go
Labels: size/S

#20512 Automated cherry pick of #20509: fix(notify): fix mobile validate
  pkg/apis/notify/config.go
  pkg/notify/sender/smsdriver/aliyun.go
  pkg/notify/sender/smsdriver/huawei.go
Labels: size/S

#20516 feat(region): guestnetwork port mappings
  pkg/apis/compute/api.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/pod.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/models/guests.go
  pkg/compute/models/networks.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/portmapping.go
  pkg/mcclient/options/compute/server_pod.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L, area/region, area/host, area/climc

#20515 feat(climc): migrate pod port_mappings to guest network
  cmd/climc/shell/compute/server_pod.go
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/pod.go
  pkg/compute/models/guestnetworks.go
  pkg/mcclient/options/compute/server_pod.go
Labels: size/L, area/region, area/climc

#20518 feat(climc): update port_mappings of server network
  cmd/climc/shell/compute/servernetworks.go
  pkg/cloudcommon/cmdline/parser.go
Labels: size/S, area/climc

#20513 feat(host): container log
  cmd/climc/shell/compute/containers.go
  pkg/apis/compute/pod.go
  pkg/appsrv/appsrv.go
  pkg/appsrv/response.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/podhandlers/podhandlers.go
  pkg/mcclient/modules/compute/mod_containers.go
  pkg/mcclient/options/compute/containers.go
  pkg/util/flushwriter/doc.go
  pkg/util/flushwriter/writer.go
  pkg/util/pod/logs/constants.go
  pkg/util/pod/logs/doc.go
  pkg/util/pod/logs/logs.go
  pkg/util/pod/logs/tail.go
  pkg/util/pod/stream/doc.go
  pkg/util/pod/stream/stream.go
Labels: area/host, size/XL, area/climc

#20519 fix(notify): add mobile verify
  pkg/notify/models/config.go
  pkg/notify/sender/mobile.go
Labels: size/M

#20520 Automated cherry pick of #20519: fix(notify): add mobile verify
  pkg/notify/models/config.go
  pkg/notify/sender/mobile.go
Labels: size/M

#20521 Automated cherry pick of #20519: fix(notify): add mobile verify
  pkg/notify/models/config.go
  pkg/notify/sender/mobile.go
Labels: size/M

#20522 Automated cherry pick of #20519: fix(notify): add mobile verify
  pkg/notify/models/config.go
  pkg/notify/sender/mobile.go
Labels: size/M

#20524 fix(region): support sangfor
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/sangfor.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/sangfor.go
  pkg/compute/models/guest_actions.go
  pkg/compute/regiondrivers/sangfor.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
Labels: size/L

#20525 Automated cherry pick of #20524: fix(region): support sangfor
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/sangfor.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/compute/hostdrivers/sangfor.go
  pkg/compute/models/guest_actions.go
  pkg/compute/regiondrivers/sangfor.go
  pkg/compute/tasks/guest_create_disk_task.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
Labels: size/L

#20534 fix: update model api
  pkg/apis/compute/guestnetwork.go
  pkg/apis/compute/zz_generated.model.go
  pkg/apis/notify/zz_generated.model.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestnetworks.go
Labels: size/L

#20539 fix(host): inject port_mapping environment from nic
  pkg/hostman/guestman/pod.go
Labels: size/L, area/host

#20530 fix: enable image cache cleanup by default
  pkg/hostman/options/options.go
Labels: size/XS

#20531 Automated cherry pick of #20530: fix: enable image cache cleanup by default
  pkg/hostman/options/options.go
Labels: size/XS

#20532 Automated cherry pick of #20530: fix: enable image cache cleanup by default
  pkg/hostman/options/options.go
Labels: size/XS

#20544 feat(region): add container info into server details
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
Labels: size/S, area/region

#20517 fix: task table columns nullable
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/XS

#20536 fix(region,host): isolated device batch sync
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#20535 fix(region): insert iso sync guest status
  pkg/compute/tasks/storage_cache_image_task.go
Labels: size/S

#20543 Automated cherry pick of #20535: fix(region): insert iso sync guest status
  pkg/compute/tasks/storage_cache_image_task.go
Labels: size/S

#20542 Automated cherry pick of #20540: Automated cherry pick of #20535: fix(region): insert iso sync guest status
  pkg/compute/tasks/storage_cache_image_task.go
Labels: size/S

#20540 Automated cherry pick of #20535: fix(region): insert iso sync guest status
  pkg/compute/tasks/storage_cache_image_task.go
Labels: size/S

#20538 Automated cherry pick of #20536: fix(region,host): isolated device batch sync
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#20537 Automated cherry pick of #20536: fix(region,host): isolated device batch sync
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/L

#20492 fix(region): convert to esxi fill network params
  pkg/compute/models/guest_convert.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/M

#20493 Automated cherry pick of #20492: fix(region): convert to esxi fill network params
  pkg/compute/models/guest_convert.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/M

#20494 Automated cherry pick of #20492: fix(region): convert to esxi fill network params
  pkg/compute/models/guest_convert.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/compute/tasks/guest_delete_task.go
Labels: size/M

#20547 fix: cleanup compute options 20240615
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/compute/dbinstance_accounts.go
  cmd/climc/shell/compute/dbinstance_databases.go
  cmd/climc/shell/compute/dbinstance_skus.go
  cmd/climc/shell/compute/elasticcache.go
  cmd/climc/shell/compute/networkaddresses.go
  cmd/climc/shell/compute/routetable_association.go
  cmd/climc/shell/compute/routetable_routeset.go
  cmd/climc/shell/compute/routetables.go
  cmd/climc/shell/compute/schedtagresources.go
  cmd/climc/shell/compute/schedtags.go
  cmd/climc/shell/compute/secgroups.go
  cmd/climc/shell/compute/skus.go
  cmd/climc/shell/compute/vpc_peering_connection.go
  cmd/climc/shell/compute/vpcs.go
  pkg/apis/compute/zz_generated.model.go
  pkg/mcclient/options/compute/cloudaccounts.go
  pkg/mcclient/options/compute/dbinstance_account.go
  pkg/mcclient/options/compute/dbinstance_database.go
  pkg/mcclient/options/compute/dbinstance_skus.go
  pkg/mcclient/options/compute/elasticcache.go
  pkg/mcclient/options/compute/networkaddress.go
  pkg/mcclient/options/compute/routetable_association.go
  pkg/mcclient/options/compute/routetable_routeset.go
  pkg/mcclient/options/compute/routetables.go
  pkg/mcclient/options/compute/schedtags.go
  pkg/mcclient/options/compute/secgroup.go
  pkg/mcclient/options/compute/serverskus.go
  pkg/mcclient/options/compute/vpc.go
  pkg/mcclient/options/compute/vpc_peering_connection.go
Labels: size/L

#20549 Automated cherry pick of #20547: fix: cleanup compute options 20240615
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/compute/dbinstance_accounts.go
  cmd/climc/shell/compute/dbinstance_databases.go
  cmd/climc/shell/compute/dbinstance_skus.go
  cmd/climc/shell/compute/elasticcache.go
  cmd/climc/shell/compute/networkaddresses.go
  cmd/climc/shell/compute/routetable_association.go
  cmd/climc/shell/compute/routetable_routeset.go
  cmd/climc/shell/compute/routetables.go
  cmd/climc/shell/compute/schedtagresources.go
  cmd/climc/shell/compute/schedtags.go
  cmd/climc/shell/compute/secgroups.go
  cmd/climc/shell/compute/skus.go
  cmd/climc/shell/compute/vpc_peering_connection.go
  cmd/climc/shell/compute/vpcs.go
  pkg/apis/notify/zz_generated.model.go
  pkg/mcclient/options/compute/cloudaccounts.go
  pkg/mcclient/options/compute/dbinstance_account.go
  pkg/mcclient/options/compute/dbinstance_database.go
  pkg/mcclient/options/compute/dbinstance_skus.go
  pkg/mcclient/options/compute/elasticcache.go
  pkg/mcclient/options/compute/networkaddress.go
  pkg/mcclient/options/compute/routetable_association.go
  pkg/mcclient/options/compute/routetable_routeset.go
  pkg/mcclient/options/compute/routetables.go
  pkg/mcclient/options/compute/schedtags.go
  pkg/mcclient/options/compute/secgroup.go
  pkg/mcclient/options/compute/serverskus.go
  pkg/mcclient/options/compute/vpc.go
  pkg/mcclient/options/compute/vpc_peering_connection.go
Labels: size/L

#20552 feat(webconsole): add server name as prefix of instance name for cont…
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: area/webconsole, area/apigateway

#20553 fix(region): qcloud permission
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#20555 Automated cherry pick of #20553: fix(region): qcloud permission
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/mongodb_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/mongodb.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/S

#20562 fix(webconsole): sangfor vnc
  cmd/climc/shell/misc/feature.go
  pkg/apis/webconsole/consts.go
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
Labels: size/XS

#20563 Automated cherry pick of #20562: fix(webconsole): sangfor vnc
  cmd/climc/shell/misc/feature.go
  pkg/apis/webconsole/consts.go
  pkg/webconsole/server/server.go
  pkg/webconsole/session/remote_console.go
Labels: size/XS

#20556 fix(climc): add service choices for worker-list
  cmd/climc/shell/compute/workers.go
Labels: size/XS

#20557 Automated cherry pick of #20556: fix(climc): add service choices for worker-list
  cmd/climc/shell/compute/workers.go
Labels: size/XS

#20561 fix(region): cloudpods hypervisor
  pkg/compute/models/capabilities.go
  pkg/compute/models/hosts.go
  pkg/mcclient/cloudpods/host.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/M

#20564 Automated cherry pick of #20561: fix(region): cloudpods hypervisor
  pkg/compute/models/capabilities.go
  pkg/compute/models/hosts.go
  pkg/mcclient/cloudpods/host.go
  pkg/mcclient/cloudpods/instance.go
Labels: size/M

#20566 fix(region): account region id optional
  go.mod
  go.sum
  pkg/cloudevent/models/cloudproviders.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/modules/compute/mod_cloudaccounts.go
  pkg/mcclient/modules/compute/mod_cloudproviders.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/oracle.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/provider/provider.go
Labels: size/L

#20567 Automated cherry pick of #20566: fix(region): account region id optional
  go.mod
  go.sum
  pkg/cloudevent/models/cloudproviders.go
  pkg/compute/models/cloudaccounts.go
  pkg/compute/models/cloudaccounts_prepare.go
  pkg/compute/models/cloudproviders.go
  pkg/mcclient/modules/compute/mod_cloudaccounts.go
  pkg/mcclient/modules/compute/mod_cloudproviders.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cloudprovider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/apsara.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/apsara/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/bucket.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/hcso.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/oracle.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/oracle/provider/provider.go
Labels: size/L

#20558 fix(host-deployer): ignore fatal exit when host.conf not exists
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: lgtm, size/XS, area/host-deployer

#20559 Automated cherry pick of #20558: fix(host-deployer): ignore fatal exit when host.conf not exists
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/XS

#20560 Automated cherry pick of #20558: fix(host-deployer): ignore fatal exit when host.conf not exists
  pkg/hostman/hostdeployer/deployserver/options.go
Labels: size/XS

#20113 fix: add predefined log policy
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#20570 Automated cherry pick of #20113: fix: add predefined log policy
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#20571 Automated cherry pick of #20113: fix: add predefined log policy
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#20572 Automated cherry pick of #20113: fix: add predefined log policy
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#20573 Automated cherry pick of #20113: fix: add predefined log policy
  pkg/keystone/locale/genpolicy.go
  pkg/keystone/locale/predefined_policies.go
  pkg/keystone/locale/predefined_yaml.go
Labels: size/M

#20574 feat(log): add i18n consts for itsm service
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/S, area/logger

#20575 Automated cherry pick of #20574: feat(log): add i18n consts for itsm service
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/S

#20576 Automated cherry pick of #20574: feat(log): add i18n consts for itsm service
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/S

#20577 Automated cherry pick of #20574: feat(log): add i18n consts for itsm service
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/M

#20578 Automated cherry pick of #20574: feat(log): add i18n consts for itsm service
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
Labels: size/M

#20580 feat(monitor): add reducer of AlertRecordRule
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/rule.go
Labels: size/XS, area/monitor

#20581 Automated cherry pick of #20580: feat(monitor): add reducer of AlertRecordRule
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/rule.go
Labels: size/XS

#20582 Automated cherry pick of #20580: feat(monitor): add reducer of AlertRecordRule
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/alerting/rule.go
Labels: size/XS

#20583 fix: webconsole adb shell choose access ip
  pkg/util/netutils2/netutils.go
  pkg/webconsole/command/adb_command.go
  pkg/webconsole/service/handlers.go
Labels: size/L

#20584 fix(region): allow kvm vmware reuse network address
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_convert.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/L

#20585 Automated cherry pick of #20584: fix(region): allow kvm vmware reuse network address
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_convert.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/L

#20586 Automated cherry pick of #20584: fix(region): allow kvm vmware reuse network address
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_convert.go
  pkg/compute/models/networks.go
  pkg/compute/models/vpcs.go
  pkg/compute/tasks/guest_convert_esxi_to_kvm_task.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
Labels: size/L

#20587 fix: clone dashboard parameters
  cmd/climc/shell/yunionconf/parameters.go
  pkg/apis/yunionconf/consts.go
  pkg/apis/yunionconf/input.go
  pkg/yunionconf/models/parameters.go
Labels: size/L

#20588 Automated cherry pick of #20587: fix: clone dashboard parameters
  cmd/climc/shell/yunionconf/parameters.go
  pkg/apis/yunionconf/consts.go
  pkg/apis/yunionconf/input.go
  pkg/yunionconf/models/parameters.go
Labels: size/L

#20589 Automated cherry pick of #20587: fix: clone dashboard parameters
  cmd/climc/shell/yunionconf/parameters.go
  pkg/apis/yunionconf/consts.go
  pkg/apis/yunionconf/input.go
  pkg/yunionconf/models/parameters.go
Labels: size/L

#20591 fix(region): auto rename when change resource owner with same name
  pkg/apis/identity/consts.go
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
Labels: size/M

#20592 Automated cherry pick of #20591: fix(region): auto rename when change resource owner with same name
  pkg/apis/identity/consts.go
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
Labels: size/M

#20593 Automated cherry pick of #20591: fix(region): auto rename when change resource owner with same name
  pkg/apis/identity/consts.go
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/db/virtualresource.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
Labels: size/M

#20599 fix(logger): add rejected action i18n translation
  pkg/util/logclient/consts_i18n.go
Labels: size/XS, area/logger

#20601 Automated cherry pick of #20599: fix(logger): add rejected action i18n translation
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#20600 Automated cherry pick of #20599: fix(logger): add rejected action i18n translation
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#20602 Automated cherry pick of #20599: fix(logger): add rejected action i18n translation
  pkg/util/logclient/consts_i18n.go
Labels: size/XS

#20615 fix(apigateway): compose environment without k8s service
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/S, area/apigateway

#20616 Automated cherry pick of #20615: fix(apigateway): compose environment without k8s service
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/S

#20617 Automated cherry pick of #20615: fix(apigateway): compose environment without k8s service
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/S

#20618 fix(monitor): add difference tags for each series
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/models.go
Labels: size/M, area/monitor

#20619 Automated cherry pick of #20618: fix(monitor): add difference tags for each series
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/models.go
Labels: size/M

#20620 Automated cherry pick of #20618: fix(monitor): add difference tags for each series
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/result_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/models.go
Labels: size/M

#20622 fix(region): natgateway api upgrade
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/natgateway.go
  vendor/yunion.io/x/sqlchemy/table.go
Labels: size/M, area/region
