Repository yunionio/cloudpods, pull requests merged in 2024-07, with the labels that each got.

#20694 fix(region): security group rule create
  go.mod
  go.sum
  pkg/compute/tasks/security_group_rule_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/securitygroup.go
Labels: size/S

#20695 Automated cherry pick of #20694: fix(region): security group rule create
  go.mod
  go.sum
  pkg/compute/tasks/security_group_rule_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/securitygroup.go
Labels: size/S

#20696 Automated cherry pick of #20694: fix(region): security group rule create
  go.mod
  go.sum
  pkg/compute/tasks/security_group_rule_create_task.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/securitygroup.go
Labels: size/S

#20697 fix(region,host): migrate converted servers
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#20698 Automated cherry pick of #20697: fix(region,host): migrate converted servers
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#20699 Automated cherry pick of #20697: fix(region,host): migrate converted servers
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/storageman/storage_local.go
Labels: size/S

#20700 fix(scheduler): optimize get guests by hosts ids
  pkg/scheduler/cache/candidate/common.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/S

#20701 Automated cherry pick of #20700: fix(scheduler): optimize get guests by hosts ids
  pkg/scheduler/cache/candidate/common.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/S

#20702 Automated cherry pick of #20700: fix(scheduler): optimize get guests by hosts ids
  pkg/scheduler/cache/candidate/common.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/S

#20706 Automated cherry pick of #20703: fix: normalize sftp errors
  pkg/httperrors/fserror.go
  pkg/httperrors/fserror_test.go
  pkg/webconsole/server/sftp_server.go
Labels: size/L

#20722 fix(region): 简化清理未使用的安全组
  cmd/climc/shell/compute/secgroups.go
  pkg/compute/models/secgroups.go
  pkg/compute/options/options.go
  pkg/mcclient/options/compute/secgroup.go
Labels: lgtm, size/M

#20723 Automated cherry pick of #20722: fix(region): 简化清理未使用的安全组
  cmd/climc/shell/compute/secgroups.go
  pkg/compute/models/secgroups.go
  pkg/compute/options/options.go
  pkg/mcclient/options/compute/secgroup.go
Labels: size/M

#20724 Automated cherry pick of #20722: fix(region): 简化清理未使用的安全组
  cmd/climc/shell/compute/secgroups.go
  pkg/compute/models/secgroups.go
  pkg/compute/options/options.go
  pkg/mcclient/options/compute/secgroup.go
Labels: size/M

#20708 fix(region): avoid delete lb failed
  pkg/compute/regiondrivers/managedvirtual.go
Labels: lgtm, size/XS

#20709 Automated cherry pick of #20708: fix(region): avoid delete lb failed
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#20710 Automated cherry pick of #20708: fix(region): avoid delete lb failed
  pkg/compute/regiondrivers/managedvirtual.go
Labels: size/XS

#20735 fix(region): gcp global eip and lb
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globaleip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_components.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_listenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalregion.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/loadbalancer_components.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/resourcebase.go
Labels: size/XXL

#20736 Automated cherry pick of #20735: fix(region): gcp global eip and lb
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globaleip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_backendgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_components.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_listenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalregion.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/google.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/loadbalancer.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/loadbalancer_components.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/resourcebase.go
Labels: size/XXL

#20716 fix(region,host): lvm snapshot reset and backup
  pkg/compute/tasks/disk_reset_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehelper.go
Labels: lgtm, size/L

#20717 Automated cherry pick of #20716: fix(region,host): lvm snapshot reset and backup
  pkg/compute/tasks/disk_reset_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehelper.go
Labels: size/L

#20718 Automated cherry pick of #20717: Automated cherry pick of #20716: fix(region,host): lvm snapshot reset and backup
  pkg/compute/tasks/disk_reset_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehelper.go
Labels: size/L

#20721 Automated cherry pick of #20718: Automated cherry pick of #20717: Automated cherry pick of #20716: fix(region,host): lvm snapshot reset and backup
  pkg/compute/tasks/disk_reset_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehelper.go
Labels: size/L

#20720 Automated cherry pick of #20718: Automated cherry pick of #20717: Automated cherry pick of #20716: fix(region,host): lvm snapshot reset and backup
  pkg/compute/tasks/disk_reset_task.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storagehelper.go
Labels: size/L

#20730 fix(region): 补充部分翻译
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/apigateway/handler/misc.go
  pkg/apihelper/apihelper.go
  pkg/appsrv/appsrv.go
  pkg/cloudcommon/db/history_data_clean.go
  pkg/compute/hostdrivers/jdcloud.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/volcengine.go
Labels: lgtm, size/XXL

#20748 Automated cherry pick of #20730: fix(region): 补充部分翻译
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/apigateway/handler/misc.go
  pkg/apihelper/apihelper.go
  pkg/appsrv/appsrv.go
  pkg/compute/hostdrivers/jdcloud.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/volcengine.go
Labels: size/XXL

#20749 Automated cherry pick of #20730: fix(region): 补充部分翻译
  locales/locales.go
  locales/zh-CN/messages.gotext.json
  pkg/apigateway/handler/misc.go
  pkg/apihelper/apihelper.go
  pkg/appsrv/appsrv.go
  pkg/compute/hostdrivers/jdcloud.go
  pkg/compute/hostdrivers/qcloud.go
  pkg/compute/hostdrivers/volcengine.go
Labels: size/XXL

#20738 fix: fail to perform host remove netif
  pkg/compute/models/netinterfaces.go
Labels: lgtm, size/XS

#20739 Automated cherry pick of #20738: fix: fail to perform host remove netif
  pkg/compute/models/netinterfaces.go
Labels: size/XS

#20740 Automated cherry pick of #20738: fix: fail to perform host remove netif
  pkg/compute/models/netinterfaces.go
Labels: size/XS

#20726 fix(climc): auto enable storage when switch s3 on
  cmd/climc/shell/misc/feature.go
Labels: size/S

#20727 Automated cherry pick of #20726: fix(climc): auto enable storage when switch s3 on
  cmd/climc/shell/misc/feature.go
Labels: size/S

#20728 Automated cherry pick of #20726: fix(climc): auto enable storage when switch s3 on
  cmd/climc/shell/misc/feature.go
Labels: size/S

#20750 fix(scheduler): 修复cloudpods宿主机网络调度问题
  pkg/scheduler/cache/candidate/base.go
Labels: lgtm, size/XS

#20751 Automated cherry pick of #20750: fix(scheduler): 修复cloudpods宿主机网络调度问题
  pkg/scheduler/cache/candidate/base.go
Labels: size/XS

#20756 fix: server update nic sub ips
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/networkaddresses.go
  pkg/mcclient/options/compute/servers.go
Labels: lgtm, size/L

#20757 Automated cherry pick of #20756: fix: server update nic sub ips
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/networkaddresses.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20758 Automated cherry pick of #20756: fix: server update nic sub ips
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/compute/models/networkaddresses.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20752 fix: turn on ethtool gso by default
  pkg/hostman/options/options.go
Labels: lgtm, size/XS

#20753 Automated cherry pick of #20752: fix: turn on ethtool gso by default
  pkg/hostman/options/options.go
Labels: size/XS

#20754 Automated cherry pick of #20752: fix: turn on ethtool gso by default
  pkg/hostman/options/options.go
Labels: size/XS

#20743 fix(notify): avoid panic when mobile not set
  pkg/notify/sender/mobile.go
Labels: lgtm, size/S

#20745 Automated cherry pick of #20743: fix(notify): avoid panic when mobile not set
  pkg/notify/sender/mobile.go
Labels: size/S

#20731 fix(region): enable create cloudpods vm with iso image
  pkg/cloudcommon/db/fetch.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/mcclient/cloudpods/image.go
Labels: lgtm, size/S

#20746 Automated cherry pick of #20731: fix(region): enable create cloudpods vm with iso image
  pkg/cloudcommon/db/fetch.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/hostdrivers/managedvirtual.go
  pkg/mcclient/cloudpods/image.go
Labels: size/S

#20732 fix(region): 避免非OneCloud区域capability依然返回OneCloud相关字段
  pkg/compute/models/capabilities.go
  pkg/compute/models/cloudaccounts.go
Labels: lgtm, size/M

#20733 Automated cherry pick of #20732: fix(region): 避免非OneCloud区域capability依然返回OneCloud相关字段
  pkg/compute/models/capabilities.go
  pkg/compute/models/cloudaccounts.go
Labels: size/M

#20767 fix(scheduler,baremetal): match RAID and PCIE storages in range
  pkg/baremetal/utils/raid/drivers/drivers.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
Labels: size/L, area/baremetal, area/scheduler

#20768 Automated cherry pick of #20767: fix(scheduler,baremetal): match RAID and PCIE storages in range
  pkg/baremetal/utils/raid/drivers/drivers.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
Labels: size/L

#20769 Automated cherry pick of #20767: fix(scheduler,baremetal): match RAID and PCIE storages in range
  pkg/baremetal/utils/raid/drivers/drivers.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
Labels: size/L

#20770 Automated cherry pick of #20767: fix(scheduler,baremetal): match RAID and PCIE storages in range
  pkg/baremetal/utils/raid/drivers/drivers.go
  pkg/compute/baremetal/diskconfig.go
  pkg/compute/baremetal/diskconfig_test.go
Labels: size/L

#20773 fix(region): auto sync remove lb public ip
  pkg/compute/models/loadbalancers.go
Labels: size/XS

#20775 fix(region): show pretty cdrom info for server
  cmd/climc/shell/compute/cachedimages.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_queries.go
  pkg/mcclient/options/compute/cachedimage.go
Labels: lgtm, size/L

#20776 Automated cherry pick of #20775: fix(region): show pretty cdrom info for server
  cmd/climc/shell/compute/cachedimages.go
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_queries.go
  pkg/mcclient/options/compute/cachedimage.go
Labels: size/L

#20762 fix(host): disk reset with encryption
  pkg/hostman/storageman/disk_lvm.go
Labels: lgtm, size/M

#20765 Automated cherry pick of #20763: Automated cherry pick of #20762: fix(host): disk reset with encryption
  pkg/hostman/storageman/disk_lvm.go
Labels: size/M

#20764 Automated cherry pick of #20763: Automated cherry pick of #20762: fix(host): disk reset with encryption
  pkg/hostman/storageman/disk_lvm.go
Labels: size/M

#20763 Automated cherry pick of #20762: fix(host): disk reset with encryption
  pkg/hostman/storageman/disk_lvm.go
Labels: size/M

#20725 fix(region): optimized guest list speed
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
  pkg/mcclient/options/compute/servers.go
Labels: lgtm, size/L

#20759 Automated cherry pick of #20725: fix(region): optimized guest list speed
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20760 Automated cherry pick of #20725: fix(region): optimized guest list speed
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20761 Automated cherry pick of #20725: fix(region): optimized guest list speed
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
  pkg/compute/models/hostresource.go
  pkg/mcclient/options/compute/servers.go
Labels: size/L

#20771 fix(region): optimized host-list speed
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: lgtm, size/L

#20778 Automated cherry pick of #20771: fix(region): optimized host-list speed
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: size/L

#20779 Automated cherry pick of #20771: fix(region): optimized host-list speed
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
Labels: size/L

#20772 fix(baremetal): some tasks don't implement IServerBaseDeployTask interface
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
Labels: size/M, area/baremetal

#20784 Automated cherry pick of #20772: fix(baremetal): some tasks don't implement IServerBaseDeployTask interface
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
Labels: size/M

#20785 Automated cherry pick of #20772: fix(baremetal): some tasks don't implement IServerBaseDeployTask interface
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
Labels: size/M

#20786 Automated cherry pick of #20772: fix(baremetal): some tasks don't implement IServerBaseDeployTask interface
  pkg/baremetal/tasks/basedeploy.go
  pkg/baremetal/tasks/create.go
  pkg/baremetal/tasks/deploy.go
  pkg/baremetal/tasks/destroy.go
  pkg/baremetal/tasks/rebuild.go
  pkg/baremetal/tasks/reprepare.go
Labels: size/M

#20800 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globaleip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storage.go
Labels: lgtm, size/S

#20801 Automated cherry pick of #20800: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globaleip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/globalloadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storage.go
Labels: size/S

#20802 Automated cherry pick of #20800: fix(region): vendor update
  go.mod
  go.sum
  pkg/hostman/storageman/imagecachemanager_agent.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/mobase.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/storage.go
Labels: size/L

#20797 fix(notify): avoid empty email addr
  pkg/notify/sender/email.go
Labels: lgtm, size/XS

#20798 Automated cherry pick of #20797: fix(notify): avoid empty email addr
  pkg/notify/sender/email.go
Labels: size/XS

#20787 feat(region,baremetal): validate ipmi info
  cmd/climc/shell/compute/hosts.go
  pkg/apis/baremetal/baremetal.go
  pkg/baremetal/handler/handlers.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: lgtm, size/L, area/baremetal, area/region

#20788 Automated cherry pick of #20787: feat(region,baremetal): validate ipmi info
  cmd/climc/shell/compute/hosts.go
  pkg/apis/baremetal/baremetal.go
  pkg/baremetal/handler/handlers.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/L

#20789 Automated cherry pick of #20787: feat(region,baremetal): validate ipmi info
  cmd/climc/shell/compute/hosts.go
  pkg/apis/baremetal/baremetal.go
  pkg/baremetal/handler/handlers.go
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/L

#20774 feat(host): add interface and index tag of netio metrics
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: lgtm, size/S, area/host

#20780 Automated cherry pick of #20774: feat(host): add interface and index tag of netio metrics
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/S

#20782 Automated cherry pick of #20774: feat(host): add interface and index tag of netio metrics
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/S

#20781 Automated cherry pick of #20774: feat(host): add interface and index tag of netio metrics
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/S

#20811 Automated cherry pick of #20219: fix: ceph stats backward compatible with ceph 12.x
  pkg/util/cephutils/ceph.go
Labels: size/S

#20810 Automated cherry pick of #20219: fix: ceph stats backward compatible with ceph 12.x
  pkg/util/cephutils/ceph.go
Labels: size/S

#20791 fix(region): check user credential length when exec task
  pkg/cloudcommon/db/taskman/tasks.go
Labels: lgtm, size/S

#20792 Automated cherry pick of #20791: fix(region): check user credential length when exec task
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/S

#20793 Automated cherry pick of #20791: fix(region): check user credential length when exec task
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/S

#20814 Automated cherry pick of #20791: fix(region): check user credential length when exec task
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/S

#20803 fix: add telegram group info
  README-CN.md
  README.md
Labels: size/XS

#20806 fix: always add static routes for metadata server
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/netplan.go
  pkg/hostman/guestfs/fsdriver/netplan_test.go
  pkg/hostman/guestfs/fsdriver/suse.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/util/netutils2/netutils.go
  pkg/vpcagent/ovn/keeper.go
Labels: lgtm, size/M

#20807 Automated cherry pick of #20806: fix: always add static routes for metadata server
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/netplan.go
  pkg/hostman/guestfs/fsdriver/netplan_test.go
  pkg/hostman/guestfs/fsdriver/suse.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/util/netutils2/netutils.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/M

#20808 Automated cherry pick of #20806: fix: always add static routes for metadata server
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/netplan.go
  pkg/hostman/guestfs/fsdriver/netplan_test.go
  pkg/hostman/guestfs/fsdriver/suse.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/util/netutils2/netutils.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/M

#20809 Automated cherry pick of #20806: fix: always add static routes for metadata server
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/netplan.go
  pkg/hostman/guestfs/fsdriver/netplan_test.go
  pkg/hostman/guestfs/fsdriver/suse.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/util/netutils2/netutils.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/M

#20818 fix(cloudid): distinct field for cloudid resources
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/models/samluser.go
Labels: size/M

#20819 Automated cherry pick of #20818: fix(cloudid): distinct field for cloudid resources
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/models/samluser.go
Labels: size/M

#20820 Automated cherry pick of #20818: fix(cloudid): distinct field for cloudid resources
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/models/samluser.go
Labels: size/M

#20821 Automated cherry pick of #20818: fix(cloudid): distinct field for cloudid resources
  pkg/cloudid/models/cloudgroup.go
  pkg/cloudid/models/clouduser.go
  pkg/cloudid/models/samluser.go
Labels: size/M

#20822 fix(region): vendor update for qcloud lb backend sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: size/S

#20823 Automated cherry pick of #20822: fix(region): vendor update for qcloud lb backend sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: size/S

#20824 Automated cherry pick of #20822: fix(region): vendor update for qcloud lb backend sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: size/S

#20825 Automated cherry pick of #20822: fix(region): vendor update for qcloud lb backend sync
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Labels: size/S

#20837 fix(region): support baremetal server as lb backend
  pkg/compute/models/loadbalancerbackends.go
Labels: lgtm, size/XS

#20838 Automated cherry pick of #20837: fix(region): support baremetal server as lb backend
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#20839 Automated cherry pick of #20837: fix(region): support baremetal server as lb backend
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#20840 Automated cherry pick of #20837: fix(region): support baremetal server as lb backend
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#20827 fix(region): add storage name for snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: lgtm, size/XS

#20828 Automated cherry pick of #20827: fix(region): add storage name for snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/XS

#20829 Automated cherry pick of #20827: fix(region): add storage name for snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/XS

#20830 Automated cherry pick of #20827: fix(region): add storage name for snapshot
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/XS

#20833 feat(monitor): update influxql-to-metricsql@v0.0.7 to support percentile aggregator
  go.mod
  go.sum
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: lgtm, size/M, area/monitor

#20836 Automated cherry pick of #20833: feat(monitor): update influxql-to-metricsql@v0.0.7 to support percentile aggregator
  go.mod
  go.sum
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M

#20834 Automated cherry pick of #20833: feat(monitor): update influxql-to-metricsql@v0.0.7 to support percentile aggregator
  go.mod
  go.sum
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M

#20835 Automated cherry pick of #20833: feat(monitor): update influxql-to-metricsql@v0.0.7 to support percentile aggregator
  go.mod
  go.sum
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/M

#20842 fix(README): link installation content to cloudpods.org
  README-CN.md
  README.md
Labels: lgtm, size/S

#20859 fix(region): host nic info
  pkg/compute/models/guest_queries.go
  pkg/compute/models/hosts.go
Labels: lgtm, size/S

#20860 Automated cherry pick of #20859: fix(region): host nic info
  pkg/compute/models/guest_queries.go
  pkg/compute/models/hosts.go
Labels: size/XS

#20861 Automated cherry pick of #20859: fix(region): host nic info
  pkg/compute/models/guest_queries.go
  pkg/compute/models/hosts.go
Labels: size/XS

#20862 Automated cherry pick of #20859: fix(region): host nic info
  pkg/compute/models/guest_queries.go
  pkg/compute/models/hosts.go
Labels: size/XS

#20847 feat(monitor): add inodes_used_percent metric
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S, area/monitor

#20848 Automated cherry pick of #20847: feat(monitor): add inodes_used_percent metric
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#20849 Automated cherry pick of #20847: feat(monitor): add inodes_used_percent metric
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#20850 Automated cherry pick of #20847: feat(monitor): add inodes_used_percent metric
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#20865 feat(apigateway): report docker-compose-baremetal running environment
  pkg/apigateway/report/report.go
Labels: lgtm, size/S, area/apigateway

#20866 Automated cherry pick of #20865: feat(apigateway): report docker-compose-baremetal running environment
  pkg/apigateway/report/report.go
Labels: size/S

#20867 Automated cherry pick of #20865: feat(apigateway): report docker-compose-baremetal running environment
  pkg/apigateway/report/report.go
Labels: size/S

#20868 Automated cherry pick of #20865: feat(apigateway): report docker-compose-baremetal running environment
  pkg/apigateway/report/report.go
Labels: size/S

#20857 Manual cherrypick of #20852 to release/3.9
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
Labels: lgtm, size/M

#20858 Automated cherry pick of #20857: Manual cherrypick of #20852 to release/3.9
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/M

#20852 fix(region,host): slvm disk create use guest host lvm disk create from backup
  pkg/compute/models/disks.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/M

#20853 Automated cherry pick of #20852: fix(region,host): slvm disk create use guest host lvm disk create from backup
  pkg/compute/models/disks.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/M

#20854 Automated cherry pick of #20852: fix(region,host): slvm disk create use guest host lvm disk create from backup
  pkg/compute/models/disks.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/M

#20855 Automated cherry pick of #20852: fix(region,host): slvm disk create use guest host lvm disk create from backup
  pkg/compute/models/disks.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/M

#20885 Automated cherry pick of #20884: Automated cherry pick of #19012: fix: webconsole display information control
  cmd/climc/shell/compute/webconsole.go
  pkg/apis/webconsole/types.go
  pkg/webconsole/command/ssh_command.go
  pkg/webconsole/handlers.go
  pkg/webconsole/options/options.go
  pkg/webconsole/session/display_info.go
  pkg/webconsole/session/remote_console.go
  pkg/webconsole/session/resolve_sshinfo.go
  pkg/webconsole/session/session.go
Labels: size/L

#20884 Automated cherry pick of #19012: fix: webconsole display information control
  cmd/climc/shell/compute/webconsole.go
  pkg/apis/webconsole/types.go
  pkg/webconsole/handlers.go
  pkg/webconsole/options/options.go
  pkg/webconsole/session/display_info.go
  pkg/webconsole/session/remote_console.go
  pkg/webconsole/session/resolve_sshinfo.go
  pkg/webconsole/session/session.go
  pkg/webconsole/session/ssh_session.go
Labels: size/L

#20881 feat(webconsole): add secret_level property inside query data
  pkg/webconsole/session/display_info.go
Labels: size/XS, area/webconsole

#20882 Automated cherry pick of #20881: feat(webconsole): add secret_level property inside query data
  pkg/webconsole/session/display_info.go
Labels: size/XS

#20883 Automated cherry pick of #20881: feat(webconsole): add secret_level property inside query data
  pkg/webconsole/session/display_info.go
Labels: size/XS

#20886 Automated cherry pick of #20881: feat(webconsole): add secret_level property inside query data
  pkg/webconsole/session/display_info.go
Labels: size/XS

#20887 Automated cherry pick of #20881: feat(webconsole): add secret_level property inside query data
  pkg/webconsole/session/display_info.go
Labels: size/XS

#20876 fix(cloudid): cloudid resource sync worker
  pkg/cloudid/tasks/cloudaccount_sync_resources_task.go
  pkg/cloudid/tasks/cloudprovider_sync_resources_task.go
Labels: lgtm

#20813 feat(regin,host,host-deployer): qga deploy and fsdriver
  build/docker/Dockerfile.host-deployer
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
  pkg/compute/tasks/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest_qga_sync_os_info_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/utils.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger/doc.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/monitor/qga/part.go
  pkg/hostman/monitor/qga/qga.go
Labels: lgtm, size/XXL

#20863 Automated cherry pick of #20813: feat(regin,host,host-deployer): qga deploy and fsdriver
  build/docker/Dockerfile.host-deployer
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
  pkg/compute/tasks/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest_qga_sync_os_info_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/utils.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger/doc.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/monitor/qga/part.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/XXL

#20864 Automated cherry pick of #20863: Automated cherry pick of #20813: feat(regin,host,host-deployer): qga deploy and fsdriver
  build/docker/Dockerfile.host-deployer
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/models/qemu_guest_agent.go
  pkg/compute/tasks/guest_qga_reset_password_task.go
  pkg/compute/tasks/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest_qga_sync_os_info_task.go
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/base.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/utils.go
  pkg/hostman/guestfs/fsdriver/windows.go
  pkg/hostman/guestfs/sshpart/sshpart.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/host_services.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger/doc.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/monitor/qga/part.go
  pkg/hostman/monitor/qga/qga.go
Labels: size/XXL

#20889 fix(mointor): multiple duplicated message
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S, area/monitor

#20890 Automated cherry pick of #20889: fix(mointor): multiple duplicated message
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S

#20891 Automated cherry pick of #20889: fix(mointor): multiple duplicated message
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S

#20892 Automated cherry pick of #20889: fix(mointor): multiple duplicated message
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S

#20893 Automated cherry pick of #18180: fix: add apis for logininfo
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guests.go
  pkg/apis/compute/host.go
  pkg/compute/models/guest_logininfo.go
Labels: size/L

#20898 fix(keystone): change user mobile field character set to utf8
  pkg/keystone/models/users.go
Labels: lgtm, size/XS

#20899 Automated cherry pick of #20898: fix(keystone): change user mobile field character set to utf8
  pkg/keystone/models/users.go
Labels: size/XS

#20900 Automated cherry pick of #20898: fix(keystone): change user mobile field character set to utf8
  pkg/keystone/models/users.go
Labels: size/XS

#20901 Automated cherry pick of #20898: fix(keystone): change user mobile field character set to utf8
  pkg/keystone/models/users.go
Labels: size/XS
