Repository yunionio/cloudpods, pull requests merged in 2024-10, with the labels that each got.

#21342 Automated cherry pick of #21339: fix: cloud account filter revisit
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
Labels: size/S

#21341 Automated cherry pick of #21339: fix: cloud account filter revisit
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
Labels: size/S

#21340 Automated cherry pick of #21339: fix: cloud account filter revisit
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
Labels: size/S

#21339 fix: cloud account filter revisit
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudprovider.go
Labels: size/S

#21343 fix(region,scheduler): allow req cpu count zero on allocate cpunumapin
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/scheduler/algorithm/predicates/guest/memory_predicate.go
  pkg/scheduler/algorithm/priorities/guest/cpunumapin.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/M

#21345 Automated cherry pick of #21343: fix(region,scheduler): allow req cpu count zero on allocate cpunumapin
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/scheduler/algorithm/predicates/guest/memory_predicate.go
  pkg/scheduler/algorithm/priorities/guest/cpunumapin.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/M

#21344 Automated cherry pick of #21343: fix(region,scheduler): allow req cpu count zero on allocate cpunumapin
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/compute/tasks/guest_change_config_task.go
  pkg/scheduler/algorithm/predicates/guest/memory_predicate.go
  pkg/scheduler/algorithm/priorities/guest/cpunumapin.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/M

#21258 feat(region,host): start pod when container exited
  pkg/apis/compute/container.go
  pkg/apis/compute/pod.go
  pkg/apis/host/container.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/models/containers.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/container_sync_status_task.go
  pkg/hostman/container/status/status_manager.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod/pleg/doc.go
  pkg/hostman/guestman/pod/pleg/generic.go
  pkg/hostman/guestman/pod/pleg/pleg.go
  pkg/hostman/guestman/pod/runtime/cache.go
  pkg/hostman/guestman/pod/runtime/doc.go
  pkg/hostman/guestman/pod/runtime/helpers.go
  pkg/hostman/guestman/pod/runtime/labels.go
  pkg/hostman/guestman/pod/runtime/runtime.go
  pkg/hostman/guestman/pod/runtime/runtime_manager.go
  pkg/hostman/guestman/pod_sync_loop.go
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/modules/compute/mod_containers.go
  pkg/scheduler/cache/candidate/common.go
Labels: size/XXL

#21347 fix(region): container exited status checking
  pkg/compute/models/containers.go
  pkg/compute/tasks/pod_stop_task.go
Labels: size/XS, area/region

#21348 feat(host): restart pod and containers when crashed
  pkg/apis/host/container.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
  pkg/hostman/guestman/pod_sync_loop.go
  pkg/hostman/guestman/podhandlers/podhandlers.go
Labels: size/L, area/host

#21352 Automated cherry pick of #21346: fix: fix slice init length
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
Labels: size/XS

#21350 Automated cherry pick of #21346: fix: fix slice init length
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
Labels: size/XS

#21349 Automated cherry pick of #21346: fix: fix slice init length
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
Labels: size/XS

#21346 fix: fix slice init length
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/storageman/lvmutils/lvmutils.go
Labels: lgtm, size/XS

#21354 fix(host): ignore NotFound error when doing some operation to container
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
Labels: size/S, area/host

#21355 fix(host): reconnect qga on failed exec qga commands
  pkg/hostman/monitor/qga/qga.go
Labels: size/M

#21356 Automated cherry pick of #21355: fix(host): reconnect qga on failed exec qga commands
  pkg/hostman/monitor/qga/qga.go
Labels: size/M

#21357 Automated cherry pick of #21355: fix(host): reconnect qga on failed exec qga commands
  pkg/hostman/monitor/qga/qga.go
Labels: size/M

#21367 fix(region): check disk is deleted on delete snapshot
  pkg/compute/storagedrivers/base.go
Labels: size/S

#21372 Automated cherry pick of #21367: fix(region): check disk is deleted on delete snapshot
  pkg/compute/storagedrivers/base.go
Labels: size/S

#21371 Automated cherry pick of #21367: fix(region): check disk is deleted on delete snapshot
  pkg/compute/storagedrivers/base.go
Labels: size/S

#21368 Automated cherry pick of #21367: fix(region): check disk is deleted on delete snapshot
  pkg/compute/storagedrivers/base.go
Labels: size/S

#21369 Automated cherry pick of #21367: fix(region): check disk is deleted on delete snapshot
  pkg/compute/storagedrivers/base.go
Labels: size/S

#21370 Automated cherry pick of #21367: fix(region): check disk is deleted on delete snapshot
  pkg/compute/storagedrivers/base.go
Labels: size/S

#21378 feat(apigateway): add rpc methods of scheduler for apigateway
  pkg/mcclient/modules/scheduler/mod_scheduler.go
Labels: size/S, area/apigateway

#21379 Automated cherry pick of #21378: feat(apigateway): add rpc methods of scheduler for apigateway
  pkg/mcclient/modules/scheduler/mod_scheduler.go
Labels: size/S

#21380 Automated cherry pick of #21378: feat(apigateway): add rpc methods of scheduler for apigateway
  pkg/mcclient/modules/scheduler/mod_scheduler.go
Labels: size/S

#21377 fix(region): filesystem sharable
  pkg/apis/compute/filesystem.go
  pkg/compute/container_drivers/volume_mount/cephfs.go
  pkg/compute/models/filesystem.go
  pkg/hostman/container/volume_mount/cephfs.go
Labels: size/M

#21381 fix(common): compatible metadata mod find
  pkg/mcclient/modules/compute/mod_metadatas.go
  pkg/mcclient/options/compute/region.go
Labels: size/S

#21384 Automated cherry pick of #21381: fix(common): compatible metadata mod find
  pkg/mcclient/modules/compute/mod_metadatas.go
  pkg/mcclient/options/compute/region.go
Labels: size/S

#21385 Automated cherry pick of #21381: fix(common): compatible metadata mod find
  pkg/mcclient/modules/compute/mod_metadatas.go
  pkg/mcclient/options/compute/region.go
Labels: size/S

#21383 Automated cherry pick of #21381: fix(common): compatible metadata mod find
  pkg/mcclient/modules/compute/mod_metadatas.go
  pkg/mcclient/options/compute/region.go
Labels: size/S

#21386 fix(region): gcp security group check
  pkg/compute/models/vpcs.go
Labels: size/XS

#21387 Automated cherry pick of #21386: fix(region): gcp security group check
  pkg/compute/models/vpcs.go
Labels: size/XS

#21388 Automated cherry pick of #21386: fix(region): gcp security group check
  pkg/compute/models/vpcs.go
Labels: size/XS

#21389 Automated cherry pick of #21386: fix(region): gcp security group check
  pkg/compute/models/vpcs.go
Labels: size/XS

#21390 fix(region): storage conf update
  pkg/compute/models/storages.go
Labels: size/XS

#21391 Automated cherry pick of #21390: fix(region): storage conf update
  pkg/compute/models/storages.go
Labels: size/XS

#21392 Automated cherry pick of #21390: fix(region): storage conf update
  pkg/compute/models/storages.go
Labels: size/XS

#21393 Automated cherry pick of #21390: fix(region): storage conf update
  pkg/compute/models/storages.go
Labels: size/XS

#21394 支持拉取容器认证镜像和相关问题修复
  cmd/climc/shell/identity/credentials.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/apis/identity/aksk.go
  pkg/apis/identity/credential.go
  pkg/cloudcommon/db/statusbase.go
  pkg/compute/models/containers.go
  pkg/compute/tasks/container_create_task.go
  pkg/compute/tasks/pod_start_task.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
  pkg/hostman/guestman/pod_sync_loop.go
  pkg/mcclient/modules/identity/mod_credentials.go
  pkg/mcclient/options/compute/containers.go
Labels: size/L, area/region, area/host, area/climc, area/keystone

#21398 feat(region,host,host-deployer): container disk support resize
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/qemu_kvm/local_driver.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/runtime.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/storageman/disk_local.go
  pkg/util/losetup/losetup.go
Labels: lgtm, size/L

#21373 fix(host,glance): qemuimg convert optimize, allow write out of order and increase coroutines
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#21374 Automated cherry pick of #21373: fix(host,glance): qemuimg convert optimize, allow write out of order and increase coroutines
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#21375 Automated cherry pick of #21373: fix(host,glance): qemuimg convert optimize, allow write out of order and increase coroutines
  pkg/util/qemuimg/qemuimg.go
Labels: size/M

#21358 fix(host): set ssd disk default scheduler none
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/util/fileutils2/fileutils.go
Labels: size/L

#21363 Automated cherry pick of #21358: fix(host): set ssd disk default scheduler none
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/util/fileutils2/fileutils.go
Labels: size/L

#21364 Automated cherry pick of #21358: fix(host): set ssd disk default scheduler none
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/util/fileutils2/fileutils.go
Labels: size/L

#21399 fix(host-deployer): do not clean spool dir on save image
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#21400 Automated cherry pick of #21399: fix(host-deployer): do not clean spool dir on save image
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#21401 Automated cherry pick of #21399: fix(host-deployer): do not clean spool dir on save image
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/XS

#21402 fix(host-deployer): update host-deployer-base to 1.4.9
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#21406 Automated cherry pick of #21402: fix(host-deployer): update host-deployer-base to 1.4.9
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#21404 Automated cherry pick of #21402: fix(host-deployer): update host-deployer-base to 1.4.9
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#21403 Automated cherry pick of #21402: fix(host-deployer): update host-deployer-base to 1.4.9
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#21395 fix(region): fix default network on get desc
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#21397 Automated cherry pick of #21395: fix(region): fix default network on get desc
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#21396 Automated cherry pick of #21395: fix(region): fix default network on get desc
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guests.go
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/M

#21407 fix(webconsole): ssh randomly exited error
  go.mod
  go.sum
  pkg/webconsole/server/ssh_server.go
  vendor/github.com/LeeEirc/terminalparser/csi_func.go
  vendor/github.com/LeeEirc/terminalparser/screen.go
  vendor/modules.txt
Labels: size/L, area/webconsole

#21408 Automated cherry pick of #21407: fix(webconsole): ssh randomly exited error
  go.mod
  go.sum
  pkg/webconsole/server/ssh_server.go
  vendor/github.com/LeeEirc/terminalparser/csi_func.go
  vendor/github.com/LeeEirc/terminalparser/screen.go
  vendor/modules.txt
Labels: size/L

#21409 Automated cherry pick of #21407: fix(webconsole): ssh randomly exited error
  go.mod
  go.sum
  pkg/webconsole/server/ssh_server.go
  vendor/github.com/LeeEirc/terminalparser/csi_func.go
  vendor/github.com/LeeEirc/terminalparser/screen.go
  vendor/modules.txt
Labels: size/L

#21411 fix: webconsole adb connection string
  pkg/webconsole/command/adb_command.go
  pkg/webconsole/service/handlers.go
Labels: size/L

#21412 fix(scheduler): avoid_same_host 策略分数过高导致调度分配不均
  pkg/scheduler/algorithm/priorities/guest/avoid_same_host.go
Labels: size/XS, area/scheduler

#21413 Automated cherry pick of #21412: fix(scheduler): avoid_same_host 策略分数过高导致调度分配不均
  pkg/scheduler/algorithm/priorities/guest/avoid_same_host.go
Labels: size/XS

#21414 Automated cherry pick of #21412: fix(scheduler): avoid_same_host 策略分数过高导致调度分配不均
  pkg/scheduler/algorithm/priorities/guest/avoid_same_host.go
Labels: size/XS

#21415 Automated cherry pick of #21412: fix(scheduler): avoid_same_host 策略分数过高导致调度分配不均
  pkg/scheduler/algorithm/priorities/guest/avoid_same_host.go
Labels: size/XS

#21417 fix(region,host): fix crash_loop_back_off status when container stopped
  pkg/compute/tasks/guest_syncstatus_task.go
  pkg/hostman/guestman/pod.go
Labels: size/S, area/region, area/host

#21420 fix(region): add interface field length
  pkg/compute/models/hostwires.go
  pkg/compute/models/netinterfaces.go
Labels: lgtm, size/XS

#21421 Automated cherry pick of #21420: fix(region): add interface field length
  pkg/compute/models/hostwires.go
  pkg/compute/models/netinterfaces.go
Labels: size/XS

#21422 Automated cherry pick of #21420: fix(region): add interface field length
  pkg/compute/models/hostwires.go
  pkg/compute/models/netinterfaces.go
Labels: size/XS

#21424 Revert "fix(region): account probe lock"
  pkg/compute/models/cloudaccounts.go
  pkg/compute/options/options.go
Labels: size/S

#21425 Automated cherry pick of #21424: Revert "fix(region): account probe lock"
  pkg/compute/models/cloudaccounts.go
  pkg/compute/options/options.go
Labels: size/S

#21426 Automated cherry pick of #21424: Revert "fix(region): account probe lock"
  pkg/compute/models/cloudaccounts.go
  pkg/compute/options/options.go
Labels: size/S

#21428 Automated cherry pick of #21427: fix(region): support cloudpods secrule ops
  pkg/mcclient/cloudpods/secgroup.go
  pkg/mcclient/cloudpods/secgrouprules.go
Labels: size/S

#21429 Automated cherry pick of #21427: fix(region): support cloudpods secrule ops
  pkg/mcclient/cloudpods/secgroup.go
  pkg/mcclient/cloudpods/secgrouprules.go
Labels: size/S

#21430 fix(host): umount wrong path when detach loop device
  pkg/util/losetup/losetup.go
Labels: size/L, area/host

#21431 fix: more verbose task log
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/L

#21432 fix: host bond slave nic should use permaddr as mac
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/sysutils/nics.go
Labels: lgtm, size/S

#21433 Automated cherry pick of #21432: fix: host bond slave nic should use permaddr as mac
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/sysutils/nics.go
Labels: size/S

#21434 Automated cherry pick of #21432: fix: host bond slave nic should use permaddr as mac
  pkg/hostman/hostinfo/hostinfo.go
  pkg/util/sysutils/nics.go
Labels: size/S

#21442 fix(host): 删除 server 时再次尝试从 cri 获取 id
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod/runtime/runtime_manager.go
Labels: size/S, area/host

#21439 fix(region): vendor update
  go.mod
  go.sum
  pkg/mcclient/cloudpods/storagecache.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#21440 Automated cherry pick of #21439: fix(region): vendor update
  go.mod
  go.sum
  pkg/mcclient/cloudpods/storagecache.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#21441 Automated cherry pick of #21439: fix(region): vendor update
  go.mod
  go.sum
  pkg/mcclient/cloudpods/storagecache.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/waf.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/huawei.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#21451 fix(region,host): sync disk status to ready when rebuild_failed
  pkg/apis/compute/disk_const.go
  pkg/compute/regiondrivers/kvm.go
  pkg/compute/tasks/disk_create_task.go
  pkg/hostman/storageman/backup.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/storage_base.go
  pkg/util/pod/pod.go
Labels: size/M, area/region, area/host

#21453 fix(host): add lock when attach loop device
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/util/losetup/device.go
  pkg/util/losetup/losetup.go
  pkg/util/pod/pod.go
Labels: size/M, area/host

#21457 feat(host): set container start and stop worker count to 1 defaultly
  pkg/hostman/guestman/podhandlers/podhandlers.go
  pkg/hostman/options/options.go
Labels: size/XS, area/host

#21458 fix(host): adjust timeout for stopping container
  pkg/hostman/guestman/pod.go
  pkg/util/pod/pod.go
Labels: size/S, area/host

#21443 fix(region,host): ceph add enable messenger v2 options
  cmd/climc/shell/compute/storages.go
  pkg/apis/compute/storage.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/M

#21444 Automated cherry pick of #21443: fix(region,host): ceph add enable messenger v2 options
  cmd/climc/shell/compute/storages.go
  pkg/apis/compute/storage.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/M

#21445 Automated cherry pick of #21443: fix(region,host): ceph add enable messenger v2 options
  cmd/climc/shell/compute/storages.go
  pkg/apis/compute/storage.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/M

#21446 Automated cherry pick of #21443: fix(region,host): ceph add enable messenger v2 options
  cmd/climc/shell/compute/storages.go
  pkg/apis/compute/storage.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/M

#21459 fix(host): 重启时拉起容器 GuestStartWorker 出现排队
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod_sync_loop.go
  pkg/hostman/options/options.go
Labels: size/S, area/host

#21461 fix(cloudmon): cloudpods metric sync
  go.mod
  go.sum
  pkg/mcclient/cloudpods/cloudpods.go
  pkg/mcclient/cloudpods/instance.go
  pkg/mcclient/cloudpods/shell/monitor.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/M

#21462 Automated cherry pick of #21461: fix(cloudmon): cloudpods metric sync
  go.mod
  go.sum
  pkg/mcclient/cloudpods/cloudpods.go
  pkg/mcclient/cloudpods/instance.go
  pkg/mcclient/cloudpods/shell/monitor.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/M

#21464 Automated cherry pick of #21461: fix(cloudmon): cloudpods metric sync
  go.mod
  go.sum
  pkg/mcclient/cloudpods/cloudpods.go
  pkg/mcclient/cloudpods/instance.go
  pkg/mcclient/cloudpods/shell/monitor.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Labels: size/M

#21465 fix(host): 同步pod状态没有考虑容器被删除的情况
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
Labels: size/M, area/host

#21466 feat(climc): support webconsole-container-exec
  cmd/climc/shell/compute/webconsole.go
  pkg/mcclient/modules/webconsole/mod_webconsole.go
  pkg/mcclient/options/webconsole.go
  pkg/webconsole/service/handlers.go
Labels: size/M, area/webconsole, area/climc

#21467 feat(webconsole): disable command recording defaultly
  pkg/webconsole/options/options.go
  pkg/webconsole/recorder/recorder.go
Labels: size/XS, area/webconsole

#21469 Automated cherry pick of #21467: feat(webconsole): disable command recording defaultly
  pkg/webconsole/options/options.go
  pkg/webconsole/recorder/recorder.go
Labels: size/XS

#21468 Automated cherry pick of #21467: feat(webconsole): disable command recording defaultly
  pkg/webconsole/options/options.go
  pkg/webconsole/recorder/recorder.go
Labels: size/XS

#21473 fix(host): not set container_exited status when do server-syncstatus
  pkg/hostman/guestman/pod.go
Labels: size/XS, area/host

#21476 fix(region): purge manager quota
  pkg/compute/models/purge.go
Labels: size/S

#21477 Automated cherry pick of #21476: fix(region): purge manager quota
  pkg/compute/models/purge.go
Labels: size/S

#21478 Automated cherry pick of #21476: fix(region): purge manager quota
  pkg/compute/models/purge.go
Labels: size/S

#21475 fix(region): batch get isolated device spec
  pkg/compute/models/capabilities.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/models/specs.go
Labels: lgtm, size/L

#21479 fix(region): 避免翻页查询导致公有云实例被误清除
  pkg/compute/models/guests.go
Labels: size/S

#21480 Automated cherry pick of #21479: fix(region): 避免翻页查询导致公有云实例被误清除
  pkg/compute/models/guests.go
Labels: size/S

#21482 fix(region): cephfs set quota
  cmd/climc/shell/compute/filesystem.go
  go.mod
  go.sum
  pkg/apis/compute/filesystem.go
  pkg/compute/models/filesystem.go
  pkg/compute/models/resource_syncstatus.go
  pkg/compute/tasks/file_system_set_quota_task.go
  pkg/mcclient/options/compute/filesystem.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/mount_target.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cephfs/dirs.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/nas_base.go
Labels: size/L

#21484 feat(region,host): support container cpuset_clone_children
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/util/pod/cgroup.go
Labels: size/S, area/region, area/host

#21487 fix(region): file system set quota params
  pkg/compute/models/filesystem.go
Labels: size/XS

#21488 feat(host): 支持容器运行时做备份
  pkg/hostman/guestman/pod.go
Labels: size/M, area/host

#21491 Automated cherry pick of #21489: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ctyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ucloud/instance.go
Labels: size/M

#21492 fix(host): 修复 dirty shutdown 机制和 reconcile 的冲突问题
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_sync_loop.go
Labels: size/M, area/host

#21493 feature: kafka telegraf output options
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/hostman/system_service/telegraf.go
Labels: lgtm, size/M

#21494 Automated cherry pick of #21493: feature: kafka telegraf output options
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21495 Automated cherry pick of #21493: feature: kafka telegraf output options
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21496 Automated cherry pick of #21493: feature: kafka telegraf output options
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/options/options.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21497 fix(host): 容器卡在 probing 状态
  pkg/hostman/container/status/status_manager.go
  pkg/hostman/guestman/pod.go
Labels: size/S, area/host

#21498 fix: disk filter by storage host
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storageresource.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/disks.go
  pkg/mcclient/options/compute/network.go
Labels: size/M

#21500 Automated cherry pick of #21498: fix: disk filter by storage host
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storageresource.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/disks.go
  pkg/mcclient/options/compute/network.go
Labels: size/M

#21499 Automated cherry pick of #21498: fix: disk filter by storage host
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storageresource.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/disks.go
  pkg/mcclient/options/compute/network.go
Labels: size/M
