Repository yunionio/cloudpods, pull requests merged in 2024-11, with the labels that each got.

#21503 fix(host): 忽略 tar 打包出现文件变更的错误
  pkg/hostman/guestman/pod.go
Labels: size/S, area/host

#21507 fix(host): return expectedStatus when json file content is empty
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_sync_loop.go
Labels: size/XS, area/host

#21506 fix(region,scheduler,host): container numa aware
  pkg/apis/scheduler/api.go
  pkg/baremetal/tasks/baseprepare.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/tasks/guest_create_task.go
  pkg/compute/tasks/guest_live_migrate_task.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/hosthandler/handler.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/isolated_device/container_device/base_dev.go
  pkg/hostman/isolated_device/container_device/nvidia_mps.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/scheduler/cache/candidate/baremetals.go
  pkg/scheduler/cache/candidate/common.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/core/result.go
  pkg/scheduler/core/types.go
  pkg/scheduler/options/options.go
  pkg/scheduler/test/mock/core.go
  pkg/scheduler/test/prepare.go
Labels: size/XL

#21510 fix(region): not set PrimaryZone when no dns_domain configured
  pkg/dns/setup.go
Labels: size/XS, area/region-dns

#21511 Automated cherry pick of #21510: fix(region): not set PrimaryZone when no dns_domain configured
  pkg/dns/setup.go
Labels: size/S

#21513 Automated cherry pick of #21510: fix(region): not set PrimaryZone when no dns_domain configured
  pkg/dns/setup.go
Labels: size/XS

#21501 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/mongodb_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/mongodb.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#21514 fix(region): vendor update for disable esxi swap
  go.mod
  go.sum
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M

#21515 Automated cherry pick of #21514: fix(region): vendor update for disable esxi swap
  go.mod
  go.sum
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M

#21516 Automated cherry pick of #21514: fix(region): vendor update for disable esxi swap
  go.mod
  go.sum
  pkg/apis/compute/guests.go
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storagecache.go
Labels: size/M

#21520 fix(host): add default masked and read only paths
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/util/pod/pod.go
  pkg/util/pod/securitycontext.go
Labels: size/M, area/host

#21522 feat(monitor): add system and processes host metrics
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/M, area/monitor

#21523 Automated cherry pick of #21522: feat(monitor): add system and processes host metrics
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/M

#21525 fix(host): losetup --nooverlap option
  pkg/util/losetup/losetup.go
Labels: size/XS, area/host

#21502 feat(region,host,host-deployer,climc): support ext4 casefold feature disk
  pkg/apis/compute/api.go
  pkg/apis/compute/disk.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/models/containers.go
  pkg/compute/models/disks.go
  pkg/compute/models/storages.go
  pkg/hostman/container/volume_mount/disk.go
  pkg/hostman/diskutils/deploy_iface/deployer.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/diskutils/qemu_kvm/local_driver.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestman/guest_create_from_remote.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_nvme.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/mcclient/options/compute/containers.go
  pkg/mcclient/options/compute/servers.go
Labels: area/region, area/host, size/XL, area/climc, area/host-deployer

#21527 fix(monitor): add order index for monitor panel
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/alertdashboard.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/alertdashboard_panel.go
  pkg/monitor/models/alertpannel.go
  pkg/monitor/models/commonalert.go
Labels: size/L

#21529 Automated cherry pick of #21527: fix(monitor): add order index for monitor panel
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/alertdashboard.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/monitor/models/alertdashboard.go
  pkg/monitor/models/alertdashboard_panel.go
  pkg/monitor/models/alertpannel.go
  pkg/monitor/models/commonalert.go
Labels: size/L

#21530 fix(host): desc of container server is not update when sync-config
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/runtime.go
Labels: size/S, area/host

#21534 fix(region,host): server-stop 接口没有对处于 crash 状态的容器发关机请求
  pkg/compute/tasks/pod_stop_task.go
  pkg/hostman/guestman/pod.go
Labels: area/region, area/host

#21526 fix(region): mps device attach group by addr
  pkg/compute/guestdrivers/pod.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/isolated_devices.go
Labels: size/L

#21470 fix(region,host): storage add master host
  pkg/apis/compute/storage.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
  pkg/compute/service/service.go
  pkg/compute/storagedrivers/slvm.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#21471 Automated cherry pick of #21470: fix(region,host): storage add master host
  pkg/apis/compute/storage.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
  pkg/compute/service/service.go
  pkg/compute/storagedrivers/slvm.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#21472 Automated cherry pick of #21470: fix(region,host): storage add master host
  pkg/apis/compute/storage.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
  pkg/compute/service/service.go
  pkg/compute/storagedrivers/slvm.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/storageman/core.go
  pkg/hostman/storageman/storagehandler/storagehandler.go
Labels: size/L

#21531 fix(notify): show pretty notify error
  pkg/notify/models/notification.go
  pkg/notify/models/topic.go
  pkg/notify/service/handlers.go
Labels: size/M

#21532 Automated cherry pick of #21531: fix(notify): show pretty notify error
  pkg/notify/models/notification.go
  pkg/notify/models/topic.go
  pkg/notify/service/handlers.go
Labels: size/M

#21535 feat(region,host,climc): stop container forcely by kill parent process
  pkg/apis/compute/container.go
  pkg/apis/host/container.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/compute/models/containers.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/mcclient/options/compute/containers.go
  pkg/util/pod/pod.go
Labels: size/L, area/region, area/host, area/climc

#21539 fix(monitor): 修复报警恢复时包含其他资源的问题
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/template.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/monitor/alerting/conditions/helper.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/dingding.go
  pkg/monitor/alerting/notifiers/feishu.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/subscriptionmodel/subcription.go
  pkg/monitor/validators/validators.go
Labels: size/L, area/monitor

#21542 Automated cherry pick of #21539: fix(monitor): 修复报警恢复时包含其他资源的问题
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/template.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/monitor/alerting/conditions/helper.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/dingding.go
  pkg/monitor/alerting/notifiers/feishu.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/subscriptionmodel/subcription.go
  pkg/monitor/validators/validators.go
Labels: size/L

#21543 Automated cherry pick of #21539: fix(monitor): 修复报警恢复时包含其他资源的问题
  pkg/apis/monitor/alert.go
  pkg/apis/monitor/template.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/monitor/alerting/conditions/helper.go
  pkg/monitor/alerting/conditions/nodataquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/notifier.go
  pkg/monitor/alerting/notifiers/base.go
  pkg/monitor/alerting/notifiers/dingding.go
  pkg/monitor/alerting/notifiers/feishu.go
  pkg/monitor/alerting/notifiers/onecloud.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/monitor_resource.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/subscriptionmodel/subcription.go
  pkg/monitor/validators/validators.go
Labels: size/L

#21544 feat(region,climc): server-set-root-disk-matcher
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S, area/region, area/climc

#21545 Automated cherry pick of #21544: feat(region,climc): server-set-root-disk-matcher
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#21546 Automated cherry pick of #21544: feat(region,climc): server-set-root-disk-matcher
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#21547 Automated cherry pick of #21544: feat(region,climc): server-set-root-disk-matcher
  cmd/climc/shell/compute/servers.go
  pkg/compute/models/guest_actions.go
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#21536 fix(glance): image stream worker count
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: lgtm, size/XS

#21537 Automated cherry pick of #21536: fix(glance): image stream worker count
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/XS

#21538 Automated cherry pick of #21536: fix(glance): image stream worker count
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/XS

#21548 fix: telegraf kakfa ordered configuration
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21549 Automated cherry pick of #21548: fix: telegraf kakfa ordered configuration
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21550 Automated cherry pick of #21548: fix: telegraf kakfa ordered configuration
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21551 Automated cherry pick of #21548: fix: telegraf kakfa ordered configuration
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#21556 Automated cherry pick of #21554: fix(region): vendor update for gcp disk name length
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/S

#21555 Automated cherry pick of #21554: fix(region): vendor update for gcp disk name length
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/S

#21554 fix(region): vendor update for gcp disk name length
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/S

#21558 fix(region,host,hostdeployer): 支持添加 case_insensitive_paths
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/models/containers.go
  pkg/hostman/container/volume_mount/disk.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/mcclient/options/compute/containers.go
Labels: size/M, area/region, area/host, area/host-deployer

#21559 Automated cherry pick of #21552: fix: disable default dns domain cloud.onecloud.io
  pkg/apis/const.go
  pkg/compute/models/networks.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/M

#21560 Automated cherry pick of #21552: fix: disable default dns domain cloud.onecloud.io
  pkg/apis/const.go
  pkg/compute/models/networks.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/vpcagent/ovn/keeper.go
Labels: size/M

#21552 fix: disable default dns domain cloud.onecloud.io
  pkg/apis/const.go
  pkg/compute/models/networks.go
  pkg/hostman/guestfs/fsdriver/nicteaming.go
  pkg/hostman/hostdeployer/apis/utils.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver.go
  pkg/vpcagent/ovn/keeper.go
Labels: lgtm, size/M

#21564 fix(host): 修复 container force stop 报错问题
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_helper.go
  pkg/mcclient/options/compute/containers.go
  pkg/util/pod/pod.go
Labels: size/M, area/host

#21567 fix(monitor): add metric content for email template
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@cn/DEFAULT.email
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@en/DEFAULT.email
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S, area/monitor

#21568 Automated cherry pick of #21567: fix(monitor): add metric content for email template
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@cn/DEFAULT.email
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@en/DEFAULT.email
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S

#21569 Automated cherry pick of #21567: fix(monitor): add metric content for email template
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@cn/DEFAULT.email
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@en/DEFAULT.email
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S

#21570 Automated cherry pick of #21567: fix(monitor): add metric content for email template
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@cn/DEFAULT.email
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@en/DEFAULT.email
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/S

#21561 fix(region): filter unused snapshot
  cmd/climc/shell/compute/snapshots.go
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/XS

#21562 Automated cherry pick of #21561: fix(region): filter unused snapshot
  cmd/climc/shell/compute/snapshots.go
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/XS

#21563 Automated cherry pick of #21561: fix(region): filter unused snapshot
  cmd/climc/shell/compute/snapshots.go
  pkg/apis/compute/snapshot.go
  pkg/compute/models/snapshots.go
Labels: size/XS

#21576 fix(monitor): alert notification details
  cmd/climc/shell/monitor/alertnotification.go
  pkg/apis/monitor/alertjoint.go
  pkg/apis/monitor/alertnotification.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/options/monitor/alert.go
  pkg/monitor/models/alertjoint.go
  pkg/monitor/models/alertnotification.go
Labels: size/M, area/climc, area/monitor

#21577 Automated cherry pick of #21576: fix(monitor): alert notification details
  cmd/climc/shell/monitor/alertnotification.go
  pkg/apis/monitor/alertjoint.go
  pkg/apis/monitor/alertnotification.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/options/monitor/alert.go
  pkg/monitor/models/alertjoint.go
  pkg/monitor/models/alertnotification.go
Labels: size/M

#21578 Automated cherry pick of #21576: fix(monitor): alert notification details
  cmd/climc/shell/monitor/alertnotification.go
  pkg/apis/monitor/alertjoint.go
  pkg/apis/monitor/alertnotification.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/options/monitor/alert.go
  pkg/monitor/models/alertjoint.go
  pkg/monitor/models/alertnotification.go
Labels: size/M

#21579 Automated cherry pick of #21576: fix(monitor): alert notification details
  cmd/climc/shell/monitor/alertnotification.go
  pkg/apis/monitor/alertjoint.go
  pkg/apis/monitor/alertnotification.go
  pkg/mcclient/modules/monitor/alert.go
  pkg/mcclient/options/monitor/alert.go
  pkg/monitor/models/alertjoint.go
  pkg/monitor/models/alertnotification.go
Labels: size/M

#21572 fix(region): add actual capacity used usage
  pkg/compute/models/storages.go
  pkg/compute/usages/handler.go
Labels: lgtm, size/S

#21573 Automated cherry pick of #21572: fix(region): add actual capacity used usage
  pkg/compute/models/storages.go
  pkg/compute/usages/handler.go
Labels: size/S

#21575 Automated cherry pick of #21572: fix(region): add actual capacity used usage
  pkg/compute/models/storages.go
  pkg/compute/usages/handler.go
Labels: size/S

#21583 fix(host): remove pod with retry
  pkg/util/pod/pod.go
Labels: size/S, area/host

#21580 fix(scheduler): numa memory more balance on with prefer nodes
  pkg/compute/models/guests.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
  pkg/scheduler/cache/candidate/hosts.go
Labels: size/L

#21589 fix: integrate opentsdb
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
Labels: lgtm, size/M

#21588 feat(host): 支持容器相关gpu设备监控采集
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/metric_dbinit.go
  pkg/monitor/models/datasource.go
Labels: size/L, area/host

#21585 fix(region): allow disable default policy
  pkg/apigateway/service/policy.go
  pkg/apigateway/service/service.go
  pkg/apis/identity/consts.go
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/options/options.go
  pkg/cloudid/policy/defaults.go
  pkg/cloudid/service/service.go
  pkg/compute/policy/defaults.go
  pkg/compute/service/service.go
  pkg/image/policy/defaults.go
  pkg/image/service/service.go
  pkg/keystone/policy/defaults.go
  pkg/keystone/service/service.go
  pkg/logger/policy/defaults.go
  pkg/logger/service/service.go
  pkg/notify/policy/defaults.go
  pkg/notify/service/service.go
  pkg/yunionconf/policy/defaults.go
  pkg/yunionconf/service/service.go
Labels: size/L

#21586 Automated cherry pick of #21585: fix(region): allow disable default policy
  pkg/apigateway/service/policy.go
  pkg/apigateway/service/service.go
  pkg/apis/identity/consts.go
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/options/options.go
  pkg/cloudid/policy/defaults.go
  pkg/cloudid/service/service.go
  pkg/compute/policy/defaults.go
  pkg/compute/service/service.go
  pkg/image/policy/defaults.go
  pkg/image/service/service.go
  pkg/keystone/policy/defaults.go
  pkg/keystone/service/service.go
  pkg/logger/policy/defaults.go
  pkg/logger/service/service.go
  pkg/notify/policy/defaults.go
  pkg/notify/service/service.go
  pkg/yunionconf/policy/defaults.go
  pkg/yunionconf/service/service.go
Labels: size/L

#21587 Automated cherry pick of #21585: fix(region): allow disable default policy
  pkg/apigateway/service/policy.go
  pkg/apigateway/service/service.go
  pkg/apis/identity/consts.go
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/options/options.go
  pkg/cloudid/policy/defaults.go
  pkg/cloudid/service/service.go
  pkg/compute/policy/defaults.go
  pkg/compute/service/service.go
  pkg/image/policy/defaults.go
  pkg/image/service/service.go
  pkg/keystone/policy/defaults.go
  pkg/keystone/service/service.go
  pkg/logger/policy/defaults.go
  pkg/logger/service/service.go
  pkg/notify/policy/defaults.go
  pkg/notify/service/service.go
  pkg/yunionconf/policy/defaults.go
  pkg/yunionconf/service/service.go
Labels: size/L

#21590 feat(region,monitor): add IsolatedDeviceTypeCount of host details
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S, area/region, area/monitor

#21591 fix(host): add startPodLock for pod instance
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_sync_loop.go
Labels: size/S, area/host

#21592 fix(monitor): raw_name of group_by
  pkg/monitor/tsdb/models.go
Labels: size/XS, area/monitor

#21594 Automated cherry pick of #21592: fix(monitor): raw_name of group_by
  pkg/monitor/tsdb/models.go
Labels: size/XS

#21593 Automated cherry pick of #21592: fix(monitor): raw_name of group_by
  pkg/monitor/tsdb/models.go
Labels: size/XS

#21595 Automated cherry pick of #21592: fix(monitor): raw_name of group_by
  pkg/monitor/tsdb/models.go
Labels: size/XS

#21599 fix(region): remove dstack
  cmd/climc/shell/compute/usages.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/S

#21600 Automated cherry pick of #21599: fix(region): remove dstack
  cmd/climc/shell/compute/usages.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/S

#21601 Automated cherry pick of #21599: fix(region): remove dstack
  cmd/climc/shell/compute/usages.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/models/cloudaccounts.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/S

#21596 fix(region): shareable virtual resource query
  pkg/cloudcommon/db/sharablebase.go
Labels: size/S

#21597 Automated cherry pick of #21596: fix(region): shareable virtual resource query
  pkg/cloudcommon/db/sharablebase.go
Labels: size/S

#21598 Automated cherry pick of #21596: fix(region): shareable virtual resource query
  pkg/cloudcommon/db/sharablebase.go
Labels: size/S

#21602 fix(region): not sync status when attaching and detaching disk
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: size/XS, area/region

#21604 Automated cherry pick of #21602: fix(region): not sync status when attaching and detaching disk
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: size/XS

#21605 Automated cherry pick of #21602: fix(region): not sync status when attaching and detaching disk
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: size/XS

#21606 Automated cherry pick of #21602: fix(region): not sync status when attaching and detaching disk
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/tasks/guest_detach_disk_task.go
Labels: size/XS

#21612 fix: add opentsdb catalog
  pkg/compute/models/hosts.go
Labels: size/XS

#21614 fix(region,host,scheduler): isolated device balance with to reserve cpus
  pkg/apis/compute/host.go
  pkg/apis/compute/host_const.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/runtime.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/mcclient/options/compute/host.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/util/cgrouputils/cgrouputils.go
Labels: size/L

#21615 fix(region): 容器处于 probe_failed 时可能出现重复开机的情况
  pkg/compute/tasks/pod_start_task.go
Labels: size/XS, area/region

#21608 Automated cherry pick of #21607: fix(region): add lb backend group count and listener count for lb details
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancers.go
Labels: size/M

#21609 Automated cherry pick of #21607: fix(region): add lb backend group count and listener count for lb details
  pkg/apis/compute/loadbalancer.go
  pkg/compute/models/loadbalancers.go
Labels: size/M

#21616 fix: noop task support
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/db/taskman/noop_task.go
  pkg/util/logclient/consts.go
Labels: size/M

#21617 fix(region): ContainerBatchStopTask and ContainerBatchStartTask
  pkg/cloudcommon/db/taskman/subtasks.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/compute/models/containers.go
  pkg/compute/tasks/container_batch_start_task.go
  pkg/compute/tasks/container_batch_stop_task.go
  pkg/compute/tasks/pod_start_task.go
  pkg/compute/tasks/pod_stop_task.go
Labels: size/L, area/region

#21619 support telegraf linux_sysctl_fs
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S, area/host, area/monitor

#21620 Automated cherry pick of #21619: support telegraf linux_sysctl_fs
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#21621 Automated cherry pick of #21619: support telegraf linux_sysctl_fs
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#21622 Automated cherry pick of #21619: support telegraf linux_sysctl_fs
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/S

#21624 fix(monitor): inject ResType
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
Labels: size/XS, area/monitor

#21626 Automated cherry pick of #21624: fix(monitor): inject ResType
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
Labels: size/XS

#21625 Automated cherry pick of #21624: fix(monitor): inject ResType
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
Labels: size/XS

#21627 Automated cherry pick of #21624: fix(monitor): inject ResType
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
Labels: size/XS

#21628 Automated cherry pick of #21624: fix(monitor): inject ResType
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
Labels: size/XS

#21629 fix(monitor): set default aggregator and group by for alert model
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/S, area/monitor

#21630 Automated cherry pick of #21629: fix(monitor): set default aggregator and group by for alert model
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/S

#21631 Automated cherry pick of #21629: fix(monitor): set default aggregator and group by for alert model
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/S

#21632 Automated cherry pick of #21629: fix(monitor): set default aggregator and group by for alert model
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/S

#21633 feat(monitor): support sorting reduced result
  pkg/apis/monitor/alert.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/L, area/monitor

#21635 Automated cherry pick of #21633: feat(monitor): support sorting reduced result
  pkg/apis/monitor/alert.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/L

#21637 Automated cherry pick of #21633: feat(monitor): support sorting reduced result
  pkg/apis/monitor/alert.go
  pkg/mcclient/modules/monitor/helper.go
  pkg/monitor/alerting/conditions/metricquery.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/unifiedmonitor.go
Labels: size/L

#21638 fix(region): vendor update for azure vm create
  go.mod
  go.sum
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/ucloud.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/host.go
Labels: size/M

#21640 Automated cherry pick of #21638: fix(region): vendor update for azure vm create
  go.mod
  go.sum
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/ucloud.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/host.go
Labels: size/M

#21641 Automated cherry pick of #21638: fix(region): vendor update for azure vm create
  go.mod
  go.sum
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/ucloud.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/host.go
Labels: size/M

#21639 Automated cherry pick of #21638: fix(region): vendor update for azure vm create
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/compute/regiondrivers/azure.go
  pkg/compute/regiondrivers/bingocloud.go
  pkg/compute/regiondrivers/ctyun.go
  pkg/compute/regiondrivers/qcloud.go
  pkg/compute/regiondrivers/ucloud.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/M

#21642 feat(host): add container net_failed status
  pkg/apis/compute/container.go
  pkg/hostman/container/prober/results/results_manager.go
  pkg/hostman/container/status/status_manager.go
Labels: size/M, area/host

#21643 fix(cloudid): vendor update for azure iam
  go.mod
  go.sum
  pkg/cloudid/drivers/azure.go
  pkg/cloudid/models/cloudgroup.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure_v2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudpolicy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/role.go
Labels: size/XL

#21644 Automated cherry pick of #21643: fix(cloudid): vendor update for azure iam
  go.mod
  go.sum
  pkg/cloudid/drivers/azure.go
  pkg/cloudid/models/cloudgroup.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure_v2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudpolicy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/role.go
Labels: size/XL

#21646 Automated cherry pick of #21643: fix(cloudid): vendor update for azure iam
  go.mod
  go.sum
  pkg/cloudid/drivers/azure.go
  pkg/cloudid/models/cloudgroup.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure_v2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudgroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/cloudpolicy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/role.go
Labels: size/XL

#21648 fix(host): import from libvirt parse live xml
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/guestman/libvirt.go
Labels: size/M

#21651 Automated cherry pick of #21648: fix(host): import from libvirt parse live xml
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/guestman/libvirt.go
Labels: size/M

#21650 Automated cherry pick of #21648: fix(host): import from libvirt parse live xml
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/guestman/libvirt.go
Labels: size/M

#21649 Automated cherry pick of #21648: fix(host): import from libvirt parse live xml
  pkg/hostman/diskutils/qemu_kvm/lvm.go
  pkg/hostman/guestman/libvirt.go
Labels: size/M

#21655 fix(region): avoid panic
  pkg/controller/autoscaling/controller.go
Labels: size/XS

#21657 Automated cherry pick of #21655: fix(region): avoid panic
  pkg/controller/autoscaling/controller.go
Labels: size/XS

#21656 Automated cherry pick of #21655: fix(region): avoid panic
  pkg/controller/autoscaling/controller.go
Labels: size/XS

#21658 Automated cherry pick of #21655: fix(region): avoid panic
  pkg/controller/autoscaling/controller.go
Labels: size/XS

#21659 fix(monitor): raw_name of influxdb query
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/L, area/monitor

#21660 Automated cherry pick of #21659: fix(monitor): raw_name of influxdb query
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/L

#21661 Automated cherry pick of #21659: fix(monitor): raw_name of influxdb query
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/L

#21662 Automated cherry pick of #21659: fix(monitor): raw_name of influxdb query
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/datasource.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/influxdb/response_parser.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/L

#21663 fix(region): support zettakit
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/zettakit.go
  pkg/compute/hostdrivers/zettakit.go
  pkg/compute/regiondrivers/zettakit.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
Labels: size/L

#21664 feat(monitor): list alertrecords by res_id
  pkg/apis/monitor/alertrecord.go
  pkg/mcclient/options/monitor/alertrecord.go
  pkg/monitor/models/alertrecord.go
Labels: size/M, area/monitor

#21666 Automated cherry pick of #21664: feat(monitor): list alertrecords by res_id
  pkg/apis/monitor/alertrecord.go
  pkg/mcclient/options/monitor/alertrecord.go
  pkg/monitor/models/alertrecord.go
Labels: size/M

#21668 Automated cherry pick of #21664: feat(monitor): list alertrecords by res_id
  pkg/apis/monitor/alertrecord.go
  pkg/mcclient/options/monitor/alertrecord.go
  pkg/monitor/models/alertrecord.go
Labels: size/M

#21665 Automated cherry pick of #21663: fix(region): support zettakit
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/zettakit.go
  pkg/compute/hostdrivers/zettakit.go
  pkg/compute/regiondrivers/zettakit.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
Labels: size/L

#21669 fix(monitor): set default query select and group by for alerting and panel
  pkg/monitor/models/alertpannel.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/M, area/monitor

#21670 Automated cherry pick of #21669: fix(monitor): set default query select and group by for alerting and panel
  pkg/monitor/models/alertpannel.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/M

#21671 Automated cherry pick of #21669: fix(monitor): set default query select and group by for alerting and panel
  pkg/monitor/models/alertpannel.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/M

#21672 Automated cherry pick of #21669: fix(monitor): set default query select and group by for alerting and panel
  pkg/monitor/models/alertpannel.go
  pkg/monitor/models/commonalert.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/influxdb/influxdb.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
  pkg/monitor/tsdb/query_endpoint.go
Labels: size/M

#21673 fix(region): optimized zettakit
  pkg/cloudmon/providerdriver/zettakit.go
  pkg/compute/regiondrivers/zettakit.go
Labels: size/M

#21674 Automated cherry pick of #21673: fix(region): optimized zettakit
  pkg/cloudmon/providerdriver/zettakit.go
  pkg/compute/regiondrivers/zettakit.go
Labels: size/M

#21683 optimized(host): use goroutine to start ContainerStatsProvider
  pkg/hostman/host_services.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/hostmetrics.go
Labels: size/M, area/host

#21684 fix(region): validate zettakit disk size
  pkg/compute/hostdrivers/zettakit.go
Labels: size/XS

#21685 Automated cherry pick of #21684: fix(region): validate zettakit disk size
  pkg/compute/hostdrivers/zettakit.go
Labels: size/XS

#21686 fix(region): support uis
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/uis.go
  pkg/compute/hostdrivers/uis.go
  pkg/compute/regiondrivers/uis.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
Labels: size/L

#21688 Automated cherry pick of #21686: fix(region): support uis
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/compute/guestdrivers/uis.go
  pkg/compute/hostdrivers/uis.go
  pkg/compute/regiondrivers/uis.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/servers.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
Labels: size/L

#21687 fix(host): generate ceph conf dup monHosts
  pkg/util/cephutils/ceph.go
Labels: lgtm, size/XS

#21689 Automated cherry pick of #21687: fix(host): generate ceph conf dup monHosts
  pkg/util/cephutils/ceph.go
Labels: size/XS

#21690 Automated cherry pick of #21687: fix(host): generate ceph conf dup monHosts
  pkg/util/cephutils/ceph.go
Labels: size/XS

#21691 Automated cherry pick of #21687: fix(host): generate ceph conf dup monHosts
  pkg/util/cephutils/ceph.go
Labels: size/XS

#21692 fix: complete monitor metrics
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/measurements/all.go
  pkg/monitor/dbinit/measurements/bond.go
  pkg/monitor/dbinit/measurements/cloudaccount.go
  pkg/monitor/dbinit/measurements/container.go
  pkg/monitor/dbinit/measurements/cpu.go
  pkg/monitor/dbinit/measurements/dcs.go
  pkg/monitor/dbinit/measurements/disk.go
  pkg/monitor/dbinit/measurements/diskio.go
  pkg/monitor/dbinit/measurements/doc.go
  pkg/monitor/dbinit/measurements/haproxy.go
  pkg/monitor/dbinit/measurements/internal.go
  pkg/monitor/dbinit/measurements/jenkins.go
  pkg/monitor/dbinit/measurements/k8s.go
  pkg/monitor/dbinit/measurements/kernel.go
  pkg/monitor/dbinit/measurements/kernel_vmstat.go
  pkg/monitor/dbinit/measurements/linux_sysctl_fs.go
  pkg/monitor/dbinit/measurements/measurement_test.go
  pkg/monitor/dbinit/measurements/mem.go
  pkg/monitor/dbinit/measurements/metrics.csv
  pkg/monitor/dbinit/measurements/mysql.go
  pkg/monitor/dbinit/measurements/net.go
  pkg/monitor/dbinit/measurements/netstat.go
  pkg/monitor/dbinit/measurements/ni_rsrc_mon.go
  pkg/monitor/dbinit/measurements/ntpq.go
  pkg/monitor/dbinit/measurements/nvidia.go
  pkg/monitor/dbinit/measurements/oss.go
  pkg/monitor/dbinit/measurements/ping.go
  pkg/monitor/dbinit/measurements/pod.go
  pkg/monitor/dbinit/measurements/process.go
  pkg/monitor/dbinit/measurements/rabbitmq.go
  pkg/monitor/dbinit/measurements/radeontop.go
  pkg/monitor/dbinit/measurements/rds.go
  pkg/monitor/dbinit/measurements/redis.go
  pkg/monitor/dbinit/measurements/sensor.go
  pkg/monitor/dbinit/measurements/smartctl.go
  pkg/monitor/dbinit/measurements/storage.go
  pkg/monitor/dbinit/measurements/swap.go
  pkg/monitor/dbinit/measurements/system.go
  pkg/monitor/dbinit/measurements/temp.go
  pkg/monitor/dbinit/measurements/types.go
  pkg/monitor/dbinit/measurements/vasmi.go
  pkg/monitor/dbinit/measurements/vm_guest.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: lgtm, size/XXL

#21695 Automated cherry pick of #21692: fix: complete monitor metrics
  pkg/hostman/guestfs/fsdriver/linux_init.go
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/measurements/all.go
  pkg/monitor/dbinit/measurements/bond.go
  pkg/monitor/dbinit/measurements/cloudaccount.go
  pkg/monitor/dbinit/measurements/cpu.go
  pkg/monitor/dbinit/measurements/dcs.go
  pkg/monitor/dbinit/measurements/disk.go
  pkg/monitor/dbinit/measurements/diskio.go
  pkg/monitor/dbinit/measurements/doc.go
  pkg/monitor/dbinit/measurements/haproxy.go
  pkg/monitor/dbinit/measurements/internal.go
  pkg/monitor/dbinit/measurements/jenkins.go
  pkg/monitor/dbinit/measurements/k8s.go
  pkg/monitor/dbinit/measurements/kernel.go
  pkg/monitor/dbinit/measurements/kernel_vmstat.go
  pkg/monitor/dbinit/measurements/linux_sysctl_fs.go
  pkg/monitor/dbinit/measurements/measurement_test.go
  pkg/monitor/dbinit/measurements/mem.go
  pkg/monitor/dbinit/measurements/metrics.csv
  pkg/monitor/dbinit/measurements/mysql.go
  pkg/monitor/dbinit/measurements/net.go
  pkg/monitor/dbinit/measurements/netstat.go
  pkg/monitor/dbinit/measurements/ni_rsrc_mon.go
  pkg/monitor/dbinit/measurements/ntpq.go
  pkg/monitor/dbinit/measurements/nvidia.go
  pkg/monitor/dbinit/measurements/oss.go
  pkg/monitor/dbinit/measurements/ping.go
  pkg/monitor/dbinit/measurements/process.go
  pkg/monitor/dbinit/measurements/rabbitmq.go
  pkg/monitor/dbinit/measurements/radeontop.go
  pkg/monitor/dbinit/measurements/rds.go
  pkg/monitor/dbinit/measurements/redis.go
  pkg/monitor/dbinit/measurements/sensor.go
  pkg/monitor/dbinit/measurements/smartctl.go
  pkg/monitor/dbinit/measurements/storage.go
  pkg/monitor/dbinit/measurements/swap.go
  pkg/monitor/dbinit/measurements/system.go
  pkg/monitor/dbinit/measurements/temp.go
  pkg/monitor/dbinit/measurements/types.go
  pkg/monitor/dbinit/measurements/vasmi.go
  pkg/monitor/dbinit/measurements/vm_guest.go
  pkg/monitor/dbinit/metric_dbinit.go
Labels: size/XXL
