Repository yunionio/cloudpods, pull requests merged in 2025-08, with the labels that each got.

#23120 fix(baremetal-agent): error occurred when removing logical volumes on the arm64 host
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/S, area/baremetal

#23122 Automated cherry pick of #23120: fix(baremetal-agent): error occurred when removing logical volumes on the arm64 host
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/S

#23123 Automated cherry pick of #23120: fix(baremetal-agent): error occurred when removing logical volumes on the arm64 host
  pkg/baremetal/utils/raid/megactl/megactl.go
Labels: size/S

#23128 Automated cherry pick of #23095: feat(region): fix ISO size display
  pkg/compute/models/guestcdrom.go
Labels: size/XS

#23129 Automated cherry pick of #23095: feat(region): fix ISO size display
  pkg/compute/models/guestcdrom.go
Labels: size/XS

#23124 fix(region): sync lb eip
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  pkg/compute/models/elasticips.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/eip.go
Labels: size/S

#23135 Automated cherry pick of #23134: fix(region): avoid update guest disable_delete attribute error when host id is empty
  pkg/compute/models/guests.go
Labels: size/S

#23134 fix(region): avoid update guest disable_delete attribute error when host id is empty
  pkg/compute/models/guests.go
Labels: size/S

#23137 fix(region): add change_config status for aigateway
  pkg/apis/const.go
  pkg/compute/models/ai_gateway.go
Labels: size/S

#23138 Automated cherry pick of #23137: fix(region): add change_config status for aigateway
  pkg/apis/const.go
  pkg/compute/models/ai_gateway.go
Labels: size/S

#23149 fix(region): dns zone registrar charset
  pkg/compute/models/dnszones.go
Labels: size/XS

#23150 Automated cherry pick of #23149: fix(region): dns zone registrar charset
  pkg/compute/models/dnszones.go
Labels: size/XS

#23142 fix(scheduler): add session usage timeout options
  pkg/scheduler/models/pending_usage.go
  pkg/scheduler/options/options.go
Labels: size/XS

#23146 Automated cherry pick of #23142: fix(scheduler): add session usage timeout options
  pkg/scheduler/models/pending_usage.go
  pkg/scheduler/options/options.go
Labels: size/XS

#23148 Automated cherry pick of #23142: fix(scheduler): add session usage timeout options
  pkg/scheduler/models/pending_usage.go
  pkg/scheduler/options/options.go
Labels: size/XS

#23154 Automated cherry pick of #23153: fix(region): optimized cached image list
  pkg/compute/models/cachedimages.go
  pkg/compute/tasks/security_group/security_group_create_task.go
Labels: size/M

#23155 Automated cherry pick of #23153: fix(region): optimized cached image list
  pkg/compute/models/cachedimages.go
  pkg/compute/tasks/security_group/security_group_create_task.go
Labels: size/M

#23156 Automated cherry pick of #23153: fix(region): optimized cached image list
  pkg/compute/models/cachedimages.go
  pkg/compute/tasks/security_group_create_task.go
Labels: size/M

#23152 feat(host): support single file to use post overlay
  pkg/hostman/container/volume_mount/disk/post_overlay.go
  pkg/hostman/container/volume_mount/disk/post_overlay_hostpath.go
  pkg/hostman/container/volume_mount/helper.go
Labels: size/L, area/host

#23159 Automated cherry pick of #23152: feat(host): support single file to use post overlay
  pkg/hostman/container/volume_mount/disk/post_overlay.go
  pkg/hostman/container/volume_mount/disk/post_overlay_hostpath.go
  pkg/hostman/container/volume_mount/helper.go
Labels: size/L

#23161 Automated cherry pick of #23160: fix: deploy gai.conf if both v4 and v6 present
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#23163 Automated cherry pick of #23160: fix: deploy gai.conf if both v4 and v6 present
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#23164 Automated cherry pick of #23160: fix: deploy gai.conf if both v4 and v6 present
  pkg/hostman/guestfs/fsdriver/linux.go
Labels: size/S

#23165 fix(keystone): upgrade ldap version
  cmd/ldapcli/shell/search.go
  go.mod
  go.sum
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/ldap/sync.go
  pkg/util/ldaputils/ldaputils.go
  vendor/github.com/go-asn1-ber/asn1-ber/LICENSE
  vendor/github.com/go-asn1-ber/asn1-ber/README.md
  vendor/github.com/go-asn1-ber/asn1-ber/ber.go
  vendor/github.com/go-asn1-ber/asn1-ber/content_int.go
  vendor/github.com/go-asn1-ber/asn1-ber/generalizedTime.go
  vendor/github.com/go-asn1-ber/asn1-ber/header.go
  vendor/github.com/go-asn1-ber/asn1-ber/identifier.go
  vendor/github.com/go-asn1-ber/asn1-ber/length.go
  vendor/github.com/go-asn1-ber/asn1-ber/real.go
  vendor/github.com/go-asn1-ber/asn1-ber/util.go
  vendor/github.com/go-ldap/ldap/v3/LICENSE
  vendor/github.com/go-ldap/ldap/v3/add.go
  vendor/github.com/go-ldap/ldap/v3/bind.go
  vendor/github.com/go-ldap/ldap/v3/client.go
  vendor/github.com/go-ldap/ldap/v3/compare.go
  vendor/github.com/go-ldap/ldap/v3/conn.go
  vendor/github.com/go-ldap/ldap/v3/control.go
  vendor/github.com/go-ldap/ldap/v3/debug.go
  vendor/github.com/go-ldap/ldap/v3/del.go
  vendor/github.com/go-ldap/ldap/v3/dn.go
  vendor/github.com/go-ldap/ldap/v3/doc.go
  vendor/github.com/go-ldap/ldap/v3/error.go
  vendor/github.com/go-ldap/ldap/v3/filter.go
  vendor/github.com/go-ldap/ldap/v3/ldap.go
  vendor/github.com/go-ldap/ldap/v3/moddn.go
  vendor/github.com/go-ldap/ldap/v3/modify.go
  vendor/github.com/go-ldap/ldap/v3/passwdmodify.go
  vendor/github.com/go-ldap/ldap/v3/request.go
  vendor/github.com/go-ldap/ldap/v3/search.go
  vendor/gopkg.in/asn1-ber.v1/.travis.yml
  vendor/gopkg.in/asn1-ber.v1/ber.go
  vendor/gopkg.in/ldap.v3/.gitignore
  vendor/gopkg.in/ldap.v3/.travis.yml
  vendor/gopkg.in/ldap.v3/CONTRIBUTING.md
  vendor/gopkg.in/ldap.v3/Makefile
  vendor/gopkg.in/ldap.v3/README.md
  vendor/gopkg.in/ldap.v3/client.go
  vendor/gopkg.in/ldap.v3/compare.go
  vendor/gopkg.in/ldap.v3/del.go
  vendor/gopkg.in/ldap.v3/moddn.go
  vendor/gopkg.in/ldap.v3/modify.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cdn.go
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: size/XXL

#23166 Automated cherry pick of #23165: fix(keystone): upgrade ldap version
  cmd/ldapcli/shell/search.go
  go.mod
  go.sum
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/ldap/sync.go
  pkg/util/ldaputils/ldaputils.go
  vendor/github.com/go-asn1-ber/asn1-ber/LICENSE
  vendor/github.com/go-asn1-ber/asn1-ber/README.md
  vendor/github.com/go-asn1-ber/asn1-ber/ber.go
  vendor/github.com/go-asn1-ber/asn1-ber/content_int.go
  vendor/github.com/go-asn1-ber/asn1-ber/generalizedTime.go
  vendor/github.com/go-asn1-ber/asn1-ber/header.go
  vendor/github.com/go-asn1-ber/asn1-ber/identifier.go
  vendor/github.com/go-asn1-ber/asn1-ber/length.go
  vendor/github.com/go-asn1-ber/asn1-ber/real.go
  vendor/github.com/go-asn1-ber/asn1-ber/util.go
  vendor/github.com/go-ldap/ldap/v3/LICENSE
  vendor/github.com/go-ldap/ldap/v3/add.go
  vendor/github.com/go-ldap/ldap/v3/bind.go
  vendor/github.com/go-ldap/ldap/v3/client.go
  vendor/github.com/go-ldap/ldap/v3/compare.go
  vendor/github.com/go-ldap/ldap/v3/conn.go
  vendor/github.com/go-ldap/ldap/v3/control.go
  vendor/github.com/go-ldap/ldap/v3/debug.go
  vendor/github.com/go-ldap/ldap/v3/del.go
  vendor/github.com/go-ldap/ldap/v3/dn.go
  vendor/github.com/go-ldap/ldap/v3/doc.go
  vendor/github.com/go-ldap/ldap/v3/error.go
  vendor/github.com/go-ldap/ldap/v3/filter.go
  vendor/github.com/go-ldap/ldap/v3/ldap.go
  vendor/github.com/go-ldap/ldap/v3/moddn.go
  vendor/github.com/go-ldap/ldap/v3/modify.go
  vendor/github.com/go-ldap/ldap/v3/passwdmodify.go
  vendor/github.com/go-ldap/ldap/v3/request.go
  vendor/github.com/go-ldap/ldap/v3/search.go
  vendor/gopkg.in/asn1-ber.v1/.travis.yml
  vendor/gopkg.in/asn1-ber.v1/ber.go
  vendor/gopkg.in/ldap.v3/.gitignore
  vendor/gopkg.in/ldap.v3/.travis.yml
  vendor/gopkg.in/ldap.v3/CONTRIBUTING.md
  vendor/gopkg.in/ldap.v3/Makefile
  vendor/gopkg.in/ldap.v3/README.md
  vendor/gopkg.in/ldap.v3/client.go
  vendor/gopkg.in/ldap.v3/compare.go
  vendor/gopkg.in/ldap.v3/del.go
  vendor/gopkg.in/ldap.v3/moddn.go
  vendor/gopkg.in/ldap.v3/modify.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/cdn.go
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: size/XXL

#23167 Automated cherry pick of #23165: fix(keystone): upgrade ldap version
  cmd/ldapcli/shell/search.go
  go.mod
  go.sum
  pkg/keystone/driver/ldap/ldap.go
  pkg/keystone/driver/ldap/sync.go
  pkg/util/ldaputils/ldaputils.go
  vendor/github.com/go-asn1-ber/asn1-ber/LICENSE
  vendor/github.com/go-asn1-ber/asn1-ber/README.md
  vendor/github.com/go-asn1-ber/asn1-ber/ber.go
  vendor/github.com/go-asn1-ber/asn1-ber/content_int.go
  vendor/github.com/go-asn1-ber/asn1-ber/generalizedTime.go
  vendor/github.com/go-asn1-ber/asn1-ber/header.go
  vendor/github.com/go-asn1-ber/asn1-ber/identifier.go
  vendor/github.com/go-asn1-ber/asn1-ber/length.go
  vendor/github.com/go-asn1-ber/asn1-ber/real.go
  vendor/github.com/go-asn1-ber/asn1-ber/util.go
  vendor/github.com/go-ldap/ldap/v3/LICENSE
  vendor/github.com/go-ldap/ldap/v3/add.go
  vendor/github.com/go-ldap/ldap/v3/bind.go
  vendor/github.com/go-ldap/ldap/v3/client.go
  vendor/github.com/go-ldap/ldap/v3/compare.go
  vendor/github.com/go-ldap/ldap/v3/conn.go
  vendor/github.com/go-ldap/ldap/v3/control.go
  vendor/github.com/go-ldap/ldap/v3/debug.go
  vendor/github.com/go-ldap/ldap/v3/del.go
  vendor/github.com/go-ldap/ldap/v3/dn.go
  vendor/github.com/go-ldap/ldap/v3/doc.go
  vendor/github.com/go-ldap/ldap/v3/error.go
  vendor/github.com/go-ldap/ldap/v3/filter.go
  vendor/github.com/go-ldap/ldap/v3/ldap.go
  vendor/github.com/go-ldap/ldap/v3/moddn.go
  vendor/github.com/go-ldap/ldap/v3/modify.go
  vendor/github.com/go-ldap/ldap/v3/passwdmodify.go
  vendor/github.com/go-ldap/ldap/v3/request.go
  vendor/github.com/go-ldap/ldap/v3/search.go
  vendor/gopkg.in/asn1-ber.v1/.travis.yml
  vendor/gopkg.in/asn1-ber.v1/ber.go
  vendor/gopkg.in/ldap.v3/.gitignore
  vendor/gopkg.in/ldap.v3/.travis.yml
  vendor/gopkg.in/ldap.v3/CONTRIBUTING.md
  vendor/gopkg.in/ldap.v3/Makefile
  vendor/gopkg.in/ldap.v3/README.md
  vendor/gopkg.in/ldap.v3/client.go
  vendor/gopkg.in/ldap.v3/compare.go
  vendor/gopkg.in/ldap.v3/del.go
  vendor/gopkg.in/ldap.v3/moddn.go
  vendor/gopkg.in/ldap.v3/modify.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: size/XXL

#23173 fix(keystone): show ldap url
  pkg/apis/identity/identityprovider.go
  pkg/keystone/models/identity_provider.go
Labels: size/M

#23158 fix(region,host): ipv6 change addr
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/tasks/guest/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest/guest_sync_task.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#23171 Automated cherry pick of #23158: fix(region,host): ipv6 change addr
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/tasks/guest/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest/guest_sync_task.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#23172 Automated cherry pick of #23158: fix(region,host): ipv6 change addr
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestnetworks.go
  pkg/compute/tasks/guest/guest_qga_restart_network_task.go
  pkg/compute/tasks/guest/guest_sync_task.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/monitor/qmp.go
Labels: size/L

#23188 Automated cherry pick of #23181: fix: guest ipv6 vip
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
Labels: size/M

#23187 Automated cherry pick of #23181: fix: guest ipv6 vip
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guests.go
Labels: size/M

#23189 Automated cherry pick of #21026: fix(region): try recover image cache on guest migrate
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/tasks/guest_live_migrate_task.go
Labels: size/L

#23178 feat(region,hostdeployer): add f2fs feature support
  pkg/apis/compute/disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/models/disks.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/storageman/disk_base.go
  pkg/mcclient/options/compute/disks.go
Labels: size/XL

#23183 Automated cherry pick of #23178: feat(region,hostdeployer): add f2fs feature support
  pkg/apis/compute/disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/models/disks.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/storageman/disk_base.go
  pkg/mcclient/options/compute/disks.go
Labels: size/XL

#23182 Automated cherry pick of #23178: feat(region,hostdeployer): add f2fs feature support
  pkg/apis/compute/disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/models/disks.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/storageman/disk_base.go
  pkg/mcclient/options/compute/disks.go
Labels: size/XL

#23184 Automated cherry pick of #23105: fix(host): update nic desc on nic changed
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/L

#23180 Automated cherry pick of #23105: fix(host): update nic desc on nic changed
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/L

#23198 Automated cherry pick of #23197: fix: too many recursive locks when batch create
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/S

#23201 Automated cherry pick of #23197: fix: too many recursive locks when batch create
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/S
