Repository yunionio/cloudpods, pull requests merged in 2025-01, with the labels that each got.

#21912 fix: backup storage support sign version
  go.mod
  go.sum
  pkg/apis/compute/backup.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/cloudaccounts.go
  pkg/hostman/storageman/backupstorage/object/factory.go
  pkg/hostman/storageman/backupstorage/object/object.go
  pkg/mcclient/options/compute/backup.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/zstack.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
Labels: size/L

#21914 Automated cherry pick of #21912: fix: backup storage support sign version
  go.mod
  go.sum
  pkg/apis/compute/backup.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/cloudaccounts.go
  pkg/hostman/storageman/backupstorage/object/factory.go
  pkg/hostman/storageman/backupstorage/object/object.go
  pkg/mcclient/options/compute/backup.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/volcengine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/zstack.go
  vendor/yunion.io/x/pkg/util/httputils/httputils.go
Labels: size/L

#21913 Automated cherry pick of #21912: fix: backup storage support sign version
  go.mod
  go.sum
  pkg/apis/compute/backup.go
  pkg/compute/models/backup_storage.go
  pkg/compute/models/cloudaccounts.go
  pkg/hostman/storageman/backupstorage/object/factory.go
  pkg/hostman/storageman/backupstorage/object/object.go
  pkg/mcclient/options/compute/backup.go
  pkg/mcclient/options/compute/cloudaccounts.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/buckets.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/shell.go
  vendor/yunion.io/x/executor/server/server.go
  vendor/yunion.io/x/s3cli/api-s3-datatypes.go
Labels: size/L

#21916 fix: container cp to tar support multiple dirs
  pkg/mcclient/modules/compute/mod_containers.go
  pkg/util/pod/stream/cp/cp.go
Labels: size/XS

#21918 fix(region): support skip sync host and storage info
  cmd/climc/shell/compute/hosts.go
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
  pkg/compute/options/options.go
  pkg/mcclient/options/compute/host.go
Labels: size/L

#21930 fix(region): fetch lb backend owner
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#21931 Automated cherry pick of #21930: fix(region): fetch lb backend owner
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#21932 Automated cherry pick of #21930: fix(region): fetch lb backend owner
  pkg/compute/models/loadbalancerbackends.go
Labels: size/XS

#21909 fix(region): record snapshot last attched host on delete disk
  pkg/compute/models/disks.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/disk_delete_task.go
Labels: size/M

#21927 Automated cherry pick of #21909: fix(region): record snapshot last attched host on delete disk
  pkg/compute/models/disks.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/disk_delete_task.go
Labels: size/M

#21926 Automated cherry pick of #21909: fix(region): record snapshot last attched host on delete disk
  pkg/compute/models/disks.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/disk_delete_task.go
Labels: size/M

#21924 Automated cherry pick of #21909: fix(region): record snapshot last attched host on delete disk
  pkg/compute/models/disks.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/disk_delete_task.go
Labels: size/M

#21925 Automated cherry pick of #21909: fix(region): record snapshot last attched host on delete disk
  pkg/compute/models/disks.go
  pkg/compute/storagedrivers/base.go
  pkg/compute/tasks/disk_delete_task.go
Labels: size/M

#21923 fix(region): not change container exited status to net_failed
  pkg/compute/models/containers.go
Labels: size/XS, area/region

#21921 fix: imporve task query speed
  pkg/cloudcommon/consts/db.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/taskman/subtasks.go
  pkg/cloudcommon/db/taskman/taskarchive.go
  pkg/cloudcommon/db/taskman/taskbase.go
  pkg/cloudcommon/db/taskman/taskobjs.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
Labels: size/XL

#21938 Automated cherry pick of #21937: fix(region): loadbalancer listener create input
  pkg/apis/compute/loadbalancerlistener.go
Labels: size/XS

#21939 Automated cherry pick of #21937: fix(region): loadbalancer listener create input
  pkg/apis/compute/loadbalancerlistener.go
Labels: size/XS

#21940 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/region.go
Labels: size/M

#21941 Automated cherry pick of #21940: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/region.go
Labels: size/M

#21943 fix: enable task archivers
  pkg/cloudevent/service/handlers.go
  pkg/cloudevent/service/service.go
  pkg/cloudid/service/handlers.go
  pkg/cloudid/service/service.go
  pkg/cloudir/service/service.go
  pkg/compute/service/handlers.go
  pkg/compute/service/service.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/devtool/service/handler.go
  pkg/devtool/service/service.go
  pkg/image/service/handlers.go
  pkg/image/service/service.go
  pkg/keystone/service/handlers.go
  pkg/keystone/service/service.go
  pkg/monitor/service/handlers.go
  pkg/monitor/service/service.go
  pkg/notify/service/service.go
Labels: size/L

#21942 feat(region,host,climc): support container post image overlay
  cmd/climc/shell/image/images.go
  pkg/apis/compute/container.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/apis/image/consts.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/container_drivers/volume_mount/disk_pov_host_path.go
  pkg/compute/container_drivers/volume_mount/disk_pov_image.go
  pkg/compute/models/container_drivers.go
  pkg/compute/models/containers.go
  pkg/compute/tasks/container_cache_images_task.go
  pkg/compute/tasks/container_volume_mount_task.go
  pkg/compute/tasks/storage_batch_cache_image_task.go
  pkg/hostman/container/volume_mount/disk/disk.go
  pkg/hostman/container/volume_mount/disk/post_overlay.go
  pkg/hostman/container/volume_mount/disk/post_overlay_hostpath.go
  pkg/hostman/container/volume_mount/disk/post_overlay_image.go
  pkg/hostman/container/volume_mount/interface.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/mcclient/options/compute/containers.go
Labels: area/region, area/host, size/XL, area/climc

#21952 feat(glance): upload tar as TGZ image
  pkg/util/fileutils2/fileutils.go
  pkg/util/qemuimg/qemuimg.go
Labels: size/S

#21944 fix(region): host list add hide cpu topo info option
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/S

#21946 Automated cherry pick of #21944: fix(region): host list add hide cpu topo info option
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/S

#21961 fix: cleanup inprocess task on service restart
  pkg/cloudcommon/db/taskman/taskarchive.go
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/XS

#21945 Automated cherry pick of #21944: fix(region): host list add hide cpu topo info option
  pkg/compute/models/hosts.go
  pkg/mcclient/options/compute/host.go
Labels: size/S

#21962 fix: image update input struct param
  pkg/apis/image/image.go
  pkg/image/models/images.go
Labels: size/M

#21964 Automated cherry pick of #21962: fix: image update input struct param
  pkg/apis/image/image.go
  pkg/image/models/images.go
Labels: size/M

#21963 Automated cherry pick of #21962: fix: image update input struct param
  pkg/apis/image/image.go
  pkg/image/models/images.go
Labels: size/M

#21966 fix(region): StartCacheImagesTask on container starting
  pkg/apis/compute/container.go
  pkg/apis/container.go
  pkg/compute/container_drivers/volume_mount/disk.go
  pkg/compute/tasks/container_create_task.go
  pkg/compute/tasks/container_start_task.go
  pkg/compute/tasks/container_volume_mount_task.go
Labels: size/L, area/region

#21971 fix(host): wrap qemu machine info error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS, area/host

#21972 Automated cherry pick of #21971: fix(host): wrap qemu machine info error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#21973 Automated cherry pick of #21971: fix(host): wrap qemu machine info error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#21974 Automated cherry pick of #21971: fix(host): wrap qemu machine info error
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#21979 fix(host): container exec probing
  pkg/compute/models/containers.go
  pkg/hostman/container/lifecycle/exec.go
  pkg/hostman/container/prober/prober.go
  pkg/hostman/container/volume_mount/disk/disk.go
  pkg/hostman/guestman/pod.go
  pkg/util/pod/pod.go
  pkg/util/probe/exec/exec.go
  pkg/util/probe/exec/exec_test.go
Labels: size/M, area/host

#21949 fix(region): snapshot policy with multi disks on guest
  pkg/compute/models/disks.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: lgtm, size/L

#21967 Automated cherry pick of #21949: fix(region): snapshot policy with multi disks on guest
  pkg/compute/models/disks.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: size/L

#21968 Automated cherry pick of #21949: fix(region): snapshot policy with multi disks on guest
  pkg/compute/models/disks.go
  pkg/compute/models/snapshots.go
  pkg/compute/tasks/disk_clean_overdued_snapshots.go
  pkg/compute/tasks/guest_disk_snapshot_task.go
  pkg/compute/tasks/snapshot_create_task.go
Labels: size/L

#21980 fix(region): export excel float
  pkg/util/excelutils/excelutils.go
Labels: size/XS

#21981 Automated cherry pick of #21980: fix(region): export excel float
  pkg/util/excelutils/excelutils.go
Labels: size/XS

#21982 fix(host): cephfs mount
  pkg/hostman/container/volume_mount/cephfs.go
Labels: size/XS, do-not-merge/work-in-progress

#21989 fix(apigateway): add scopedpolicybindings api
  pkg/apigateway/handler/auth.go
Labels: size/S

#21988 fix(host): netmask updated of hostlocal network
  pkg/hostman/hostinfo/finalize_network.go
Labels: size/M, area/host

#21984 fix(host): skip detect device that is not GPU class
  pkg/hostman/isolated_device/gpu.go
Labels: size/S, area/host

#21985 Automated cherry pick of #21984: fix(host): skip detect device that is not GPU class
  pkg/hostman/isolated_device/gpu.go
Labels: size/S

#21986 Automated cherry pick of #21984: fix(host): skip detect device that is not GPU class
  pkg/hostman/isolated_device/gpu.go
Labels: size/S

#21987 fix: add summary statistics switch
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: lgtm, size/S

#21991 Automated cherry pick of #21987: fix: add summary statistics switch
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/compute/models/guests.go
Labels: size/S

#21992 Automated cherry pick of #21987: fix: add summary statistics switch
  pkg/cloudcommon/db/db_dispatcher.go
Labels: size/S

#21958 fix(host): handle error not mounted
  pkg/util/mountutils/mount.go
Labels: size/XS, area/host

#21998 fix(apigateway): set scope policy binding project id query
  pkg/apigateway/handler/auth.go
Labels: size/S

#21999 Automated cherry pick of #21998: fix(apigateway): set scope policy binding project id query
  pkg/apigateway/handler/auth.go
Labels: size/M

#21993 fix: is_classic is missing from network details
  pkg/compute/models/networks.go
Labels: size/XS

#21995 Automated cherry pick of #21993: fix: is_classic is missing from network details
  pkg/compute/models/networks.go
Labels: size/XS

#21994 Automated cherry pick of #21993: fix: is_classic is missing from network details
  pkg/compute/models/networks.go
Labels: size/XS

#22009 fix(apigateway): set GOMAXPROCS to 2 when executing climc
  pkg/mcclient/modules/webconsole/mod_webconsole.go
Labels: size/XS, area/apigateway

#22010 fix(host): cephfs mount
  pkg/hostman/container/volume_mount/cephfs.go
  pkg/util/mountutils/mount.go
Labels: lgtm, size/M

#22012 fix(climc): apigateway endpoint type
  cmd/climc/entry/climc.go
Labels: size/XS

#22013 Automated cherry pick of #22012: fix(climc): apigateway endpoint type
  cmd/climc/entry/climc.go
Labels: size/XS

#22017 fix(glance): query vmware account brand
  pkg/image/service/service.go
Labels: lgtm, size/XS, area/image

#22019 Automated cherry pick of #22017: fix(glance): query vmware account brand
  pkg/image/service/service.go
Labels: size/XS

#22018 Automated cherry pick of #22017: fix(glance): query vmware account brand
  pkg/image/service/service.go
Labels: size/XS

#22014 fix: support server change ipv6 address
  go.mod
  go.sum
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
  pkg/compute/models/guest_actions.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/region.go
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: lgtm, size/L

#22016 Automated cherry pick of #22014: fix: support server change ipv6 address
  go.mod
  go.sum
  pkg/cloudcommon/cmdline/parser.go
  pkg/cloudcommon/cmdline/parser_test.go
  pkg/compute/models/guest_actions.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/region.go
  vendor/yunion.io/x/pkg/utils/tags.go
Labels: size/L

#22005 feat(region,host): hostpinger add cpu usage percent report
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
Labels: size/S

#22007 Automated cherry pick of #22005: feat(region,host): hostpinger add cpu usage percent report
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
Labels: size/S

#22006 Automated cherry pick of #22005: feat(region,host): hostpinger add cpu usage percent report
  pkg/apis/compute/host.go
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
Labels: size/S

#22023 fix(host): get cri id from pod sandbox
  pkg/hostman/guestman/pod.go
Labels: size/S, area/host

#22028 customized(monitor): check whether the measurement field exists in victoriametrics
  pkg/monitor/models/metric.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/M, area/monitor

#22029 Automated cherry pick of #22028: customized(monitor): check whether the measurement field exists in victoriametrics
  pkg/monitor/models/metric.go
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/M

#22011 feat(region,host): support resgid and resuid for container volume mount
  pkg/apis/compute/disk.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/compute/models/containers.go
  pkg/compute/models/disks.go
  pkg/hostman/container/storage/storage.go
  pkg/hostman/container/volume_mount/disk/disk.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/storageman/disk_base.go
Labels: size/L, area/region, area/host, area/host-deployer

#22025 fix: prevent access from anonymous user release/3.8
  pkg/util/rbacutils/policy.go
  pkg/util/rbacutils/rbac.go
Labels: size/M

#22026 Automated cherry pick of #22025: fix: prevent access from anonymous user release/3.8
  pkg/util/rbacutils/policy.go
  pkg/util/rbacutils/rbac.go
Labels: size/M

#22027 fix: allow host public_ip domain name
  pkg/compute/models/hosts.go
Labels: lgtm, size/XS

#21950 feat(host): container nvidia gpu metrics
  pkg/hostman/guestman/pod.go
  pkg/hostman/hostinfo/container.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/container_cph_amd_gpu_metrics.go
  pkg/hostman/hostmetrics/container_metrics.go
  pkg/hostman/hostmetrics/container_nvidia_gpu_metrics.go
  pkg/hostman/hostmetrics/container_vastaitech_gpu_metrics.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/hostman/isolated_device/container_device/nvidia_gpu.go
  pkg/hostman/isolated_device/container_device/nvidia_mps.go
  pkg/hostman/system_service/telegraf.go
  pkg/monitor/dbinit/measurements/all.go
  pkg/monitor/dbinit/measurements/pod.go
Labels: lgtm, size/XXL

#22036 fix(host): wrong order of ResUid and ResGid
  pkg/hostman/container/volume_mount/disk/disk.go
Labels: size/XS, area/host

#22002 fix(region): remove delete expired snapshot after auto snapshots
  pkg/compute/models/disks.go
Labels: size/XS

#22003 Automated cherry pick of #22002: fix(region): remove delete expired snapshot after auto snapshots
  pkg/compute/models/disks.go
Labels: size/XS

#22001 fix(region,host): slvm snapshot delete and instance snapshot purge
  cmd/climc/shell/compute/instance_snapshots.go
  pkg/compute/models/instance_snapshots.go
  pkg/hostman/storageman/disk_slvm.go
Labels: size/M

#22020 Automated cherry pick of #22001: fix(region,host): slvm snapshot delete and instance snapshot purge
  cmd/climc/shell/compute/instance_snapshots.go
  pkg/compute/models/instance_snapshots.go
  pkg/hostman/storageman/disk_slvm.go
Labels: size/M

#22021 Automated cherry pick of #22001: fix(region,host): slvm snapshot delete and instance snapshot purge
  cmd/climc/shell/compute/instance_snapshots.go
  pkg/compute/models/instance_snapshots.go
  pkg/hostman/storageman/disk_slvm.go
Labels: size/M

#22022 Automated cherry pick of #22001: fix(region,host): slvm snapshot delete and instance snapshot purge
  cmd/climc/shell/compute/instance_snapshots.go
  pkg/compute/models/instance_snapshots.go
  pkg/hostman/storageman/disk_slvm.go
Labels: size/M

#22037 fix(glance): donot umount s3fs on glance exit
  pkg/image/service/service.go
  pkg/util/procutils/cmdsetenv_others.go
Labels: size/S

#22038 Automated cherry pick of #22037: fix(glance): donot umount s3fs on glance exit
  pkg/image/service/service.go
  pkg/util/procutils/cmdsetenv.go
Labels: size/S

#22035 fix: notify empty receipients
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudcommon/notifyclient/notify_internal.go
Labels: size/M

#22043 Automated cherry pick of #22035: fix: notify empty receipients
  pkg/cloudcommon/notifyclient/notify.go
  pkg/cloudcommon/notifyclient/notify_internal.go
Labels: size/M

#22039 fix(host): support sata ahci controller
  cmd/climc/shell/compute/serverdisks.go
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#22040 Automated cherry pick of #22039: fix(host): support sata ahci controller
  cmd/climc/shell/compute/serverdisks.go
  pkg/hostman/guestman/desc/desc.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#22041 fix(region): hosts_tbl sys_info use longtext
  pkg/compute/models/hosts.go
Labels: size/XS

#22042 Automated cherry pick of #22041: fix(region): hosts_tbl sys_info use longtext
  pkg/compute/models/hosts.go
Labels: size/XS

#22034 fix: image support s3 parallel
  cmd/climc/shell/compute/hosts.go
  go.mod
  go.sum
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/image/drivers/s3/minio.go
  pkg/image/models/images.go
  pkg/image/models/storage.go
  pkg/image/options/options.go
  pkg/image/service/service.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/objectstore/shell.go
  vendor/yunion.io/x/pkg/util/qemuimgfmt/fmt.go
Labels: size/XL
