Repository yunionio/cloudpods, pull requests merged in 2025-03, with the labels that each got.

#22221 fix(region): call SetStatusFromHost when guests status uploaded
  pkg/compute/models/guest_actions.go
Labels: size/S, area/region

#22209 fix: disk copy to storage inherit classmeta
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/L

#22214 Automated cherry pick of #22209: fix: disk copy to storage inherit classmeta
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/L

#22215 Automated cherry pick of #22209: fix: disk copy to storage inherit classmeta
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/L

#22216 Automated cherry pick of #22209: fix: disk copy to storage inherit classmeta
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/L

#22217 Automated cherry pick of #22209: fix: disk copy to storage inherit classmeta
  pkg/apis/compute/guests.go
  pkg/compute/models/guest_actions.go
  pkg/compute/tasks/guest_change_disk_storage_task.go
Labels: size/M

#22218 fix: add summary-stats options
  pkg/apis/list.go
  pkg/mcclient/options/base.go
Labels: size/XS

#22220 Automated cherry pick of #22218: fix: add summary-stats options
  pkg/apis/list.go
  pkg/mcclient/options/base.go
Labels: size/XS

#22128 fix: glance always init s3 client
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/S

#22134 Automated cherry pick of #22128: fix: glance always init s3 client
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/S

#22223 Automated cherry pick of #22222: fix(host): not purge isolated device when detaching it
  cmd/climc/shell/compute/isolatedevices.go
  pkg/apis/compute/isolated_device.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/mcclient/options/compute/isolated_devices.go
Labels: size/S

#22224 Automated cherry pick of #22222: fix(host): not purge isolated device when detaching it
  cmd/climc/shell/compute/isolatedevices.go
  pkg/apis/compute/isolated_device.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/mcclient/options/compute/isolated_devices.go
Labels: size/S

#22225 fix(host): change timeout to 10s when stopping container
  pkg/util/pod/pod.go
Labels: size/XS, area/host

#22232 fix(host-deployer): set xfs default ftype 1
  pkg/hostman/diskutils/fsutils/fsutils.go
Labels: lgtm, size/XS

#22233 Automated cherry pick of #22232: fix(host-deployer): set xfs default ftype 1
  pkg/hostman/diskutils/fsutils/fsutils.go
Labels: size/XS

#22234 Automated cherry pick of #22232: fix(host-deployer): set xfs default ftype 1
  pkg/hostman/diskutils/fsutils/fsutils.go
Labels: size/XS

#22240 Hotfix/qj task clean job limit2
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/XS

#22227 fix(host): unmarshal cpuset use json parseString, disk change storage add encrypt support
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#22228 Automated cherry pick of #22227: fix(host): unmarshal cpuset use json parseString, disk change storage add encrypt support
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#22229 Automated cherry pick of #22228: Automated cherry pick of #22227: fix(host): unmarshal cpuset use json parseString, disk change storage add encrypt support
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#22230 Automated cherry pick of #22228: Automated cherry pick of #22227: fix(host): unmarshal cpuset use json parseString, disk change storage add encrypt support
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#22231 Automated cherry pick of #22228: Automated cherry pick of #22227: fix(host): unmarshal cpuset use json parseString, disk change storage add encrypt support
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/storageman/storage_base.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/hostman/storageman/storage_rbd.go
Labels: size/M

#22242 fix: auto truncate sql string
  go.mod
  go.sum
  pkg/cloudcommon/db/namevalidator.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ram_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/user.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/insert_batch.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#22244 Automated cherry pick of #22242: fix: auto truncate sql string
  go.mod
  go.sum
  pkg/cloudcommon/db/namevalidator.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ram_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/user.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/insert_batch.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#22243 Automated cherry pick of #22242: fix: auto truncate sql string
  go.mod
  go.sum
  pkg/cloudcommon/db/namevalidator.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ram_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/user.go
  vendor/yunion.io/x/sqlchemy/column.go
  vendor/yunion.io/x/sqlchemy/insert.go
  vendor/yunion.io/x/sqlchemy/insert_batch.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/L

#22237 fix(host): add check is mps device need update
  pkg/hostman/isolated_device/isolated_device.go
Labels: size/XS

#22076 feat(glance,region,host): auto cache glance images to ceph storages
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/image/models/image_ceph_cache_storages.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/L

#22246 Automated cherry pick of #22076: feat(glance,region,host): auto cache glance images to ceph storages
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/image/models/image_ceph_cache_storages.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/L

#22247 Automated cherry pick of #22076: feat(glance,region,host): auto cache glance images to ceph storages
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/image/models/image_ceph_cache_storages.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/L

#22248 Automated cherry pick of #22076: feat(glance,region,host): auto cache glance images to ceph storages
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/image/models/image_ceph_cache_storages.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/L

#22249 Automated cherry pick of #22246: Automated cherry pick of #22076: feat(glance,region,host): auto cache glance images to ceph storages
  pkg/apis/compute/storage.go
  pkg/apis/compute/storage_const.go
  pkg/compute/models/storages.go
  pkg/compute/storagedrivers/rbd.go
  pkg/hostman/storageman/imagecache_rbd.go
  pkg/hostman/storageman/storage_rbd.go
  pkg/image/models/image_ceph_cache_storages.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/mcclient/options/compute/storage.go
  pkg/util/cephutils/ceph.go
Labels: size/L

#22259 fix(webconsole,monitor): pprof handlers of gorilla mux
  pkg/appsrv/handlers.go
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/M, area/webconsole, area/monitor

#22260 Automated cherry pick of #22259: fix(webconsole,monitor): pprof handlers of gorilla mux
  pkg/appsrv/handlers.go
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/M

#22261 Automated cherry pick of #22259: fix(webconsole,monitor): pprof handlers of gorilla mux
  pkg/appsrv/handlers.go
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/M

#22262 Automated cherry pick of #22259: fix(webconsole,monitor): pprof handlers of gorilla mux
  pkg/appsrv/handlers.go
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/M

#22263 Automated cherry pick of #22262: Automated cherry pick of #22259: fix(webconsole,monitor): pprof handlers of gorilla mux
  pkg/appsrv/handlers.go
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/M

#22266 fix(host): add pod to probe manager when dirty marked
  pkg/hostman/guestman/pod.go
Labels: area/host

#22226 fix(monitor): add service metric monitor
  pkg/apis/monitor/metric.go
  pkg/cloudmon/misc/system.go
  pkg/monitor/dbinit/measurements/all.go
  pkg/monitor/dbinit/measurements/db_state.go
  pkg/monitor/dbinit/measurements/service.go
  pkg/monitor/dbinit/measurements/service_http_code.go
  pkg/monitor/dbinit/measurements/service_process_stats.go
Labels: size/L

#22250 fix(region): show dump info when worker stuck
  pkg/appsrv/workers.go
Labels: size/XS

#22251 Automated cherry pick of #22250: fix(region): show dump info when worker stuck
  pkg/appsrv/workers.go
Labels: size/XS

#22252 Automated cherry pick of #22250: fix(region): show dump info when worker stuck
  pkg/appsrv/workers.go
Labels: size/XS

#22269 fix(climc): service config bool value
  cmd/climc/shell/identity/services.go
Labels: size/XS

#22270 Automated cherry pick of #22269: fix(climc): service config bool value
  cmd/climc/shell/identity/services.go
Labels: size/XS

#22271 Automated cherry pick of #22269: fix(climc): service config bool value
  cmd/climc/shell/identity/services.go
Labels: size/XS

#22268 fix(notify): support create topic
  cmd/climc/shell/notify/notify_action.go
  cmd/climc/shell/notify/notify_resource.go
  cmd/climc/shell/notify/topic.go
  pkg/apis/notify/event.go
  pkg/apis/notify/notify_action.go
  pkg/apis/notify/notify_resource.go
  pkg/apis/notify/topic.go
  pkg/cloudcommon/notifyclient/notify.go
  pkg/mcclient/modules/notify/mod_notify.go
  pkg/mcclient/options/notify/topic.go
  pkg/notify/models/initdb.go
  pkg/notify/models/notify_action.go
  pkg/notify/models/notify_resource.go
  pkg/notify/models/topic.go
  pkg/notify/models/topic_action.go
  pkg/notify/models/topic_resource.go
  pkg/notify/service/handlers.go
Labels: size/XL

#22274 Automated cherry pick of #22273: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/zstack/provider/provider.go
Labels: size/M

#22277 fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/waf.go
Labels: size/S

#22278 Automated cherry pick of #22277: fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/waf.go
Labels: size/S

#22279 Automated cherry pick of #22277: fix(region): vendor update
  go.mod
  go.sum
  pkg/compute/models/cloudsync.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/waf.go
Labels: size/S

#22256 fix(region,host): hotplug mem adaptation for guests no memdev
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#22257 Automated cherry pick of #22256: fix(host): hotplug mem adaptation for guests no memdev
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/M

#22258 Automated cherry pick of #22256: fix(host): hotplug mem adaptation for guests no memdev
  pkg/compute/guestdrivers/kvm.go
  pkg/hostman/guestman/desc/pci.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guesthelper.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/L

#22276 feature: active cache image
  pkg/apis/compute/cachedimage.go
  pkg/apis/compute/cachedimages_const.go
  pkg/apis/compute/host.go
  pkg/apis/compute/storagecache.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/cachedimages.go
  pkg/compute/models/hostresource.go
  pkg/compute/models/storagecachedimages.go
  pkg/compute/models/storagecacheresource.go
  pkg/compute/models/storagecaches.go
  pkg/compute/tasks/storage/storage_uncache_image_task.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecachemanager_local.go
  pkg/hostman/storageman/imagecachemanager_lvm.go
  pkg/hostman/storageman/imagecachemanager_rbd.go
  pkg/image/drivers/s3/minio.go
  pkg/util/tagutils/filters.go
Labels: size/XL

#22290 fix: use host service status storing online/offline status
  pkg/compute/models/guests.go
Labels: size/XS

#22287 feat(monitor): support listing monitor_resource by alert_state
  pkg/apis/monitor/monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S, area/monitor

#22288 Automated cherry pick of #22287: feat(monitor): support listing monitor_resource by alert_state
  pkg/apis/monitor/monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S

#22289 Automated cherry pick of #22287: feat(monitor): support listing monitor_resource by alert_state
  pkg/apis/monitor/monitor_resource.go
  pkg/mcclient/options/monitor/monitor_resource.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource.go
Labels: size/S

#22294 fix(webconsole): disable 3des cipher suites
  pkg/appsrv/appsrv.go
  pkg/webconsole/service/service.go
Labels: size/S, area/webconsole

#22295 Automated cherry pick of #22294: fix(webconsole): disable 3des cipher suites
  pkg/appsrv/appsrv.go
  pkg/webconsole/service/service.go
Labels: size/S

#22296 Automated cherry pick of #22294: fix(webconsole): disable 3des cipher suites
  pkg/appsrv/appsrv.go
  pkg/webconsole/service/service.go
Labels: size/S

#22284 Automated cherry pick of #22283: fix(host): virtio nic add fdb record on has sriov nic
  pkg/hostman/hostinfo/hostbridge/linux_bridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: size/S

#22285 Automated cherry pick of #22283: fix(host): virtio nic add fdb record on has sriov nic
  pkg/hostman/hostinfo/hostbridge/linux_bridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: size/S

#22286 Automated cherry pick of #22283: fix(host): virtio nic add fdb record on has sriov nic
  pkg/hostman/hostinfo/hostbridge/linux_bridge.go
  pkg/hostman/hostinfo/hostbridge/ovs.go
Labels: size/S

#22291 fix(region): vendor update
  go.mod
  go.sum
  pkg/cloudmon/resources/resources.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure_v2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/reservation.go
Labels: size/L

#22292 Automated cherry pick of #22291: fix(region): vendor update
  go.mod
  go.sum
  pkg/cloudmon/resources/resources.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure_v2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/reservation.go
Labels: size/L

#22293 Automated cherry pick of #22291: fix(region): vendor update
  go.mod
  go.sum
  pkg/cloudmon/resources/resources.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/azure_v2.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/azure/reservation.go
Labels: size/L

#22297 fix(monitor): optimized alert list
  pkg/monitor/models/alertrecord.go
Labels: size/M

#22298 Automated cherry pick of #22297: fix(monitor): optimized alert list
  pkg/monitor/models/alertrecord.go
Labels: size/M

#22299 Automated cherry pick of #22297: fix(monitor): optimized alert list
  pkg/monitor/models/alertrecord.go
Labels: size/M

#22304 optimized(keystone): local sql auth by password
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: size/M, area/keystone

#22305 Automated cherry pick of #22304: optimized(keystone): local sql auth by password
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: size/M

#22306 Automated cherry pick of #22304: optimized(keystone): local sql auth by password
  pkg/keystone/models/passwords.go
  pkg/keystone/models/users.go
Labels: size/M

#22301 fix(region): add post delete hook
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/S

#22302 Automated cherry pick of #22301: fix(region): add post delete hook
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/S

#22303 Automated cherry pick of #22301: fix(region): add post delete hook
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/interface.go
  pkg/cloudcommon/db/modelbase.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/S

#22308 fix(region): support isolated device for cloudpods
  pkg/mcclient/cloudpods/host.go
  pkg/mcclient/cloudpods/instance.go
  pkg/mcclient/cloudpods/isolated_devices.go
Labels: size/L

#22280 fix: fail to delete sub images of composed guest image
  pkg/apis/image/consts.go
  pkg/image/models/image_guest.go
  pkg/image/models/image_guest_joint.go
  pkg/image/models/initdb.go
  pkg/image/tasks/guest_image_delete_task.go
Labels: size/L

#22281 Automated cherry pick of #22280: fix: fail to delete sub images of composed guest image
  pkg/apis/image/consts.go
  pkg/image/models/image_guest.go
  pkg/image/models/image_guest_joint.go
  pkg/image/models/initdb.go
  pkg/image/tasks/guest_image_delete_task.go
Labels: size/L

#22282 Automated cherry pick of #22280: fix: fail to delete sub images of composed guest image
  pkg/apis/image/consts.go
  pkg/image/models/image_guest.go
  pkg/image/models/image_guest_joint.go
  pkg/image/models/initdb.go
  pkg/image/tasks/guest_image_delete_task.go
Labels: size/L

#22309 feature: archived task show
  cmd/climc/shell/misc/tasks.go
  pkg/apis/list.go
  pkg/apis/notify/emailqueue.go
  pkg/apis/tasks.go
  pkg/cloudcommon/db/baselog.go
  pkg/cloudcommon/db/taskman/handler.go
  pkg/cloudcommon/db/taskman/taskarchive.go
  pkg/cloudcommon/db/taskman/tasks.go
  pkg/cloudevent/service/handlers.go
  pkg/cloudid/service/handlers.go
  pkg/compute/service/handlers.go
  pkg/devtool/service/handler.go
  pkg/image/service/handlers.go
  pkg/keystone/service/handlers.go
  pkg/mcclient/modules/compute/mod_tasks.go
  pkg/mcclient/modules/devtool/mod_tasks.go
  pkg/mcclient/modules/identity/mod_tasks.go
  pkg/mcclient/modules/image/mod_tasks.go
  pkg/mcclient/modules/k8s/tasks.go
  pkg/mcclient/modules/notify/mod_tasks.go
  pkg/mcclient/modules/tasks/mod_tasks.go
  pkg/monitor/service/handlers.go
  pkg/notify/models/emailqueue.go
  pkg/notify/service/handlers.go
Labels: size/L

#22310 fix(region): change config status
  pkg/compute/guestdrivers/baidu.go
  pkg/compute/guestdrivers/cas.go
  pkg/compute/guestdrivers/cloudpods-baremetals.go
  pkg/compute/guestdrivers/cloudpods-esxi.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/guestdrivers/sangfor.go
  pkg/compute/guestdrivers/uis.go
  pkg/compute/guestdrivers/zettakit.go
Labels: size/S

#22311 fix(region): add isolated device sync log
  pkg/compute/models/cloudsync.go
Labels: size/XS

#22313 fix: batch cache image
  pkg/compute/models/cachedimages.go
  pkg/compute/models/storagecaches.go
Labels: size/M

#22317 fix: host cache image directly from object storage
  go.mod
  go.sum
  pkg/hostman/container/prober/prober.go
  pkg/hostman/guestman/pod/pleg/generic.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostinfo/hostpinger/hostpinger.go
  pkg/hostman/storageman/remotefile/remotefile.go
  pkg/hostman/storageman/remotefile/s3remotefile.go
  pkg/image/drivers/s3/minio.go
  pkg/image/models/images.go
  pkg/image/service/service.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/L

#22318 feat(host): pod HostIPC
  cmd/create_steam.go
  pkg/apis/compute/pod.go
  pkg/hostman/guestman/pod.go
Labels: size/L, area/host

#22325 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ram_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_account.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_backup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_database.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/tag_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/user.go
Labels: size/XXL

#22326 Automated cherry pick of #22325: fix(region): vendor update
  go.mod
  go.sum
  pkg/image/models/images.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ram_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_account.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_backup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_database.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/tag_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/user.go
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/XXL

#22327 Automated cherry pick of #22325: fix(region): vendor update
  go.mod
  go.sum
  pkg/image/models/images.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/ram_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/iam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/clouduser.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_account.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_backup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_database.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/tag_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/wire.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/cam_user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/volcengine/user.go
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/XXL

#22319 optmized(monitor): query alertrecord by res_id
  pkg/monitor/models/alertrecord.go
Labels: size/S, area/monitor

#22321 Automated cherry pick of #22319: optmized(monitor): query alertrecord by res_id
  pkg/monitor/models/alertrecord.go
Labels: size/S

#22329 fix(monitor): wrong TriggerTime
  pkg/monitor/models/alertrecord.go
Labels: size/S, area/monitor

#22330 Automated cherry pick of #22329: fix(monitor): wrong TriggerTime
  pkg/monitor/models/alertrecord.go
Labels: size/S

#22331 Automated cherry pick of #22329: fix(monitor): wrong TriggerTime
  pkg/monitor/models/alertrecord.go
Labels: size/S

#22333 Automated cherry pick of #22332: fix(monitor): wrong index of details
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/models/alertrecord.go
Labels: size/M

#22334 Automated cherry pick of #22332: fix(monitor): wrong index of details
  pkg/apis/monitor/alertrecord.go
  pkg/monitor/models/alertrecord.go
Labels: size/M

#22323 fix(host): skip vastaitech Null line
  pkg/hostman/hostmetrics/container_vastaitech_gpu_metrics.go
Labels: size/XS

#22335 fix(scheduler,monitor): tls 3des
  pkg/monitor/service/handlers.go
  pkg/scheduler/service/service.go
Labels: size/S, area/scheduler, area/monitor

#22336 Automated cherry pick of #22335: fix(scheduler,monitor): tls 3des
  pkg/monitor/service/handlers.go
  pkg/scheduler/service/service.go
Labels: size/S

#22337 Automated cherry pick of #22335: fix(scheduler,monitor): tls 3des
  pkg/monitor/service/handlers.go
  pkg/scheduler/service/service.go
Labels: size/S

#22338 fix: update vendor 20250325
  go.mod
  go.sum
  pkg/image/models/images.go
  pkg/monitor/dbinit/measurements/metrics.csv
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/M

#22339 Automated cherry pick of #22338: fix: update vendor 20250325
  go.mod
  go.sum
  pkg/image/models/images.go
  pkg/monitor/dbinit/measurements/metrics.csv
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/M

#22340 Automated cherry pick of #22338: fix: update vendor 20250325
  go.mod
  go.sum
  pkg/image/models/images.go
  pkg/monitor/dbinit/measurements/metrics.csv
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Labels: size/M

#22342 fix(monitor): vm_net add bytes and packages measurements
  pkg/monitor/dbinit/measurements/vm_guest.go
Labels: size/S

#22343 Automated cherry pick of #22342: fix(monitor): vm_net add bytes and packages measurements
  pkg/monitor/dbinit/measurements/vm_guest.go
Labels: size/S

#22344 Automated cherry pick of #22342: fix(monitor): vm_net add bytes and packages measurements
  pkg/monitor/dbinit/measurements/vm_guest.go
Labels: size/S

#22324 fix(region): guestdisk list add auto_reset column
  pkg/apis/compute/disk.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
Labels: size/S

#22345 Automated cherry pick of #22324: fix(region): guestdisk list add auto_reset column
  pkg/apis/compute/disk.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
Labels: size/S

#22346 Automated cherry pick of #22324: fix(region): guestdisk list add auto_reset column
  pkg/apis/compute/disk.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
Labels: size/S

#22347 Automated cherry pick of #22324: fix(region): guestdisk list add auto_reset column
  pkg/apis/compute/disk.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
Labels: size/S

#22348 Automated cherry pick of #22324: fix(region): guestdisk list add auto_reset column
  pkg/apis/compute/disk.go
  pkg/apis/compute/guest_disk.go
  pkg/apis/compute/guests.go
  pkg/compute/models/disks.go
  pkg/compute/models/guest_queries.go
  pkg/compute/models/guestdisks.go
Labels: size/S

#22341 fix: protect appsrv default handlers
  pkg/apis/identity/consts.go
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlers.go
  pkg/appsrv/whitelist_filter.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/changes.go
  pkg/cloudcommon/options/options.go
Labels: size/M

#22241 feat(region,host): support apparmor for container
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/mcclient/options/compute/containers.go
Labels: size/S, area/region, area/host, area/climc

#22353 fix: add numa_node to isolated_devices
  pkg/mcclient/modules/compute/mod_isolatedevices.go
Labels: size/XS

#22354 fix: supplement fields of archived tasks
  cmd/climc/shell/misc/tasks.go
  pkg/apis/tasks.go
  pkg/cloudcommon/db/taskman/taskarchive.go
Labels: size/L

#22351 fix(region): isolated device share
  cmd/climc/shell/compute/isolatedevices.go
  cmd/climc/shell/compute/networks.go
  go.mod
  go.sum
  pkg/apis/compute/isolated_device.go
  pkg/compute/models/capabilities.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/mcclient/cloudpods/isolated_devices.go
  pkg/mcclient/options/baseprojects.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
Labels: size/L
