Repository yunionio/cloudpods, pull requests merged in 2025-04, with the labels that each got.

#22360 fix(region): capabilities query usable isolated device
  pkg/compute/models/capabilities.go
Labels: size/XS

#22361 fix: disable ping to hostlocal network
  pkg/cloudmon/misc/pinger.go
Labels: lgtm, size/S

#22356 fix: set db connection keepalive options
  pkg/cloudcommon/database.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#22357 Automated cherry pick of #22356: fix: set db connection keepalive options
  pkg/cloudcommon/database.go
  pkg/cloudcommon/options/options.go
Labels: size/S

#22363 fix: hide image location
  go.mod
  go.sum
  pkg/appsrv/appsrv.go
  pkg/image/models/images.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/trace/trace.go
Labels: size/M

#22364 Automated cherry pick of #22363: fix: hide image location
  go.mod
  go.sum
  pkg/appsrv/appsrv.go
  pkg/image/models/images.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/trace/trace.go
Labels: size/M

#22365 fix: container final status
  pkg/apis/compute/container.go
Labels: size/S

#22366 fix(cloudmon): add host access ip tag for metric
  pkg/apis/compute/guests.go
Labels: size/XS

#22375 fix(monitor): check measurement field
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/M, area/monitor

#22376 Automated cherry pick of #22375: fix(monitor): check measurement field
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/M

#22372 fix(region): add gpu unused usage
  pkg/compute/models/isolated_devices.go
  pkg/compute/usages/handler.go
Labels: size/M

#22373 Automated cherry pick of #22372: fix(region): add gpu unused usage
  pkg/compute/models/isolated_devices.go
  pkg/compute/usages/handler.go
Labels: size/M

#22377 fix(monitor): system metric
  pkg/apis/monitor/metric.go
  pkg/monitor/dbinit/measurements/db_state.go
  pkg/monitor/dbinit/measurements/service.go
  pkg/monitor/dbinit/measurements/service_http_code.go
  pkg/monitor/dbinit/measurements/service_process_stats.go
Labels: size/S

#22383 Automated cherry pick of #22378: fix(host-deployer): add tencentos support
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/tencentos.go
Labels: size/M

#22378 fix(host-deployer): add tencentos support
  pkg/hostman/guestfs/fsdriver/drivers.go
  pkg/hostman/guestfs/fsdriver/tencentos.go
Labels: size/M

#22381 fix(ansbileserver): update docker file
  build/docker/Dockerfile.ansibleserver
  build/docker/Dockerfile.ansibleserver-base
  build/docker/Dockerfile.file-repo
  build/docker/Makefile
Labels: size/M

#22382 Automated cherry pick of #22381: fix(ansbileserver): update docker file
  build/docker/Dockerfile.ansibleserver
  build/docker/Dockerfile.ansibleserver-base
  build/docker/Dockerfile.file-repo
  build/docker/Makefile
Labels: size/M

#22391 Automated cherry pick of #22390: fix(region): update gpu used usage
  pkg/compute/models/isolated_devices.go
  pkg/compute/usages/handler.go
Labels: size/S

#22388 fix: update file repo docker script
  build/docker/Dockerfile.file-repo
  build/docker/Makefile
Labels: size/XS

#22389 Automated cherry pick of #22388: fix: update file repo docker script
  build/docker/Dockerfile.file-repo
  build/docker/Makefile
Labels: size/XS

#22392 fix(region): export metadata
  pkg/cloudcommon/db/metadataresource.go
Labels: size/XS

#22393 Automated cherry pick of #22392: fix(region): export metadata
  pkg/cloudcommon/db/metadataresource.go
Labels: size/XS

#22394 fix(ansibleserver): show pretty error for ansible playbook
  pkg/util/ansiblev2/playbook_session.go
Labels: size/M

#22395 Automated cherry pick of #22394: fix(ansibleserver): show pretty error for ansible playbook
  pkg/util/ansiblev2/playbook_session.go
Labels: size/M

#22396 fix(webconsole): require rdp input password
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console_rdp.go
Labels: size/XS

#22397 Automated cherry pick of #22396: fix(webconsole): require rdp input password
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console_rdp.go
Labels: size/XS

#22374 fix(region): add custom total count
  pkg/cloudcommon/db/statusinfrasresource.go
Labels: size/S

#22398 Automated cherry pick of #22374: fix(region): add custom total count
  pkg/cloudcommon/db/statusinfrasresource.go
Labels: size/S

#22403 feat(host): support container always_restart
  cmd/container-examples/create_steam.go
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_sync_loop.go
Labels: size/L, area/host

#22400 fix: backend proxy worker count
  pkg/apigateway/app/app.go
  pkg/apigateway/handler/backendproxy.go
  pkg/apigateway/options/options.go
Labels: size/S

#22387 fix: disk rebuild allow set size
  pkg/apis/compute/disk.go
  pkg/compute/models/disks.go
  pkg/mcclient/options/compute/disks.go
Labels: size/S

#22379 fix: notify default policy not effective
  pkg/cloudcommon/policy/defaults.go
  pkg/notify/models/subscriber.go
  pkg/notify/service/handlers.go
Labels: size/S

#22369 fix(host): ignore errors on reconfigure vfio nic bandwidth
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#22370 Automated cherry pick of #22369: fix(host): ignore errors on reconfigure vfio nic bandwidth
  pkg/hostman/guestman/qemu-kvm.go
Labels: size/XS

#22404 fix: handler support worker manager callback
  pkg/appsrv/appsrv.go
  pkg/appsrv/handlerinfo.go
Labels: size/M

#22410 fix(keystone): password history check default 1
  pkg/keystone/options/options.go
Labels: size/XS

#22411 Automated cherry pick of #22410: fix(keystone): password history check default 1
  pkg/keystone/options/options.go
Labels: size/XS

#22406 fix(climc): keystone pprof profile
  cmd/climc/shell/misc/pprof.go
Labels: size/XS

#22407 Automated cherry pick of #22406: fix(climc): keystone pprof profile
  cmd/climc/shell/misc/pprof.go
Labels: size/XS

#22413 feat(region,host): primary container supported
  pkg/apis/container.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_sync_loop.go
Labels: size/M, area/region, area/host

#22416 fix(monitor): support victoria metrics bottom query
  go.mod
  go.sum
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/S, area/monitor

#22417 Automated cherry pick of #22416: fix(monitor): support victoria metrics bottom query
  go.mod
  go.sum
  vendor/github.com/zexi/influxql-to-metricsql/converter/translator/promql.go
  vendor/modules.txt
Labels: size/S

#22414 fix: action show climc support fields
  cmd/climc/shell/logger/actions.go
Labels: size/XS

#22420 Automated cherry pick of #22399: fix(host-health): check etcd client is reconnecting
  pkg/hostman/host_health/health_manager.go
  pkg/hostman/host_health/service.go
  scripts/docker_push.sh
Labels: size/M

#22422 fix(region): check status when container exec command
  pkg/compute/models/containers.go
Labels: area/region

#22423 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#22424 Automated cherry pick of #22423: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/jsonutils/jsonutils.go
Labels: size/M

#22427 fix(scheduler): disable prometheus metrics handler
  pkg/scheduler/service/service.go
Labels: size/XS, area/scheduler

#22428 Automated cherry pick of #22427: fix(scheduler): disable prometheus metrics handler
  pkg/scheduler/service/service.go
Labels: size/XS

#22429 fix(scheduler): unused prometheus pkg
  pkg/scheduler/service/service.go
Labels: size/XS

#22433 fix(monitor): getTagValues no data
  pkg/monitor/models/datasource.go
Labels: size/XS, area/monitor

#22434 Automated cherry pick of #22433: fix(monitor): getTagValues no data
  pkg/monitor/models/datasource.go
Labels: size/XS

#22432 feat(host): container add nvidia gpu share device type
  pkg/apis/compute/container.go
  pkg/apis/compute/isolated_device_const.go
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/hostinfo/container.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostmetrics/container_nvidia_gpu_metrics.go
  pkg/hostman/hostmetrics/hostmetrics.go
  pkg/hostman/isolated_device/container_device.go
  pkg/hostman/isolated_device/container_device/base_dev.go
  pkg/hostman/isolated_device/container_device/nvidia_gpu.go
  pkg/hostman/isolated_device/container_device/nvidia_gpu_share.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
  pkg/hostman/options/options.go
  pkg/scheduler/algorithm/predicates/isolated_device_predicate.go
Labels: size/L

#22368 fix(monitor): telegraf config add host_ip tag
  pkg/devtool/utils/influxdb_url.go
Labels: size/XS

#22405 Automated cherry pick of #22368: fix(monitor): telegraf config add host_ip tag
  pkg/apis/compute/host.go
  pkg/compute/models/hostresource.go
  pkg/devtool/utils/influxdb_url.go
Labels: size/XS

#22438 fix(monitor): remove host type query filter
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/monitor_resource_sync.go
Labels: size/XS, area/monitor

#22419 fix: webconsole referer whitelist
  pkg/webconsole/options/options.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/session.go
Labels: size/S

#22441 fix: permission check for credential object
  pkg/cloudcommon/db/rbac.go
  pkg/compute/models/containers.go
  pkg/keystone/models/credentials.go
  pkg/keystone/options/options.go
Labels: size/S

#22421 Automated cherry pick of #22419: fix: webconsole referer whitelist
  pkg/webconsole/options/options.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/session.go
Labels: size/S

#22425 fix(host): lvm disk create from esxi
  pkg/hostman/guestfs/core.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_slvm.go
Labels: size/M

#22442 fix: start sync status
  pkg/apis/const.go
  pkg/compute/models/guest_actions.go
Labels: size/XS

#22443 Automated cherry pick of #22442: fix: start sync status
  pkg/apis/const.go
  pkg/compute/models/guest_actions.go
Labels: size/XS

#22445 fix: optimize filterByOwner query speed
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/cloudcommon/db/project.go
Labels: size/M

#22446 Automated cherry pick of #22445: fix: optimize filterByOwner query speed
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/cloudcommon/db/project.go
Labels: size/M

#22447 fix: task restart cancel with message
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/M

#22448 fix(region,host): isolated device add field render_path
  pkg/apis/compute/zz_generated.model.go
  pkg/compute/models/isolated_devices.go
  pkg/hostman/isolated_device/container_device/base_dev.go
  pkg/hostman/isolated_device/container_device/nvidia_gpu_share.go
  pkg/hostman/isolated_device/isolated_device.go
  pkg/hostman/isolated_device/nvidia_vgpu.go
Labels: size/M

#22449 feat: container env ref
  cmd/container-examples/create_steam.go
  pkg/apis/compute/container.go
  pkg/apis/container.go
  pkg/apis/host/container.go
  pkg/compute/container_drivers/device/isolated_device.go
  pkg/hostman/container/device/isolated_device.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/pod_sync_loop.go
  pkg/hostman/isolated_device/container_device/nvidia_gpu.go
Labels: size/L, area/host

#22453 fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/bucket.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/loadbalancer.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/prometheus/doc.go
  vendor/yunion.io/x/pkg/util/prometheus/gin_handler.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/column.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/sync.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/column.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/dameng.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/column.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/column.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/queryfield.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/subquery.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/XXL

#22454 Automated cherry pick of #22453: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/bucket.go
  pkg/apis/compute/dbinstance.go
  pkg/apis/compute/elasticcache.go
  pkg/apis/compute/loadbalancer.go
  vendor/modules.txt
  vendor/yunion.io/x/pkg/util/prometheus/doc.go
  vendor/yunion.io/x/pkg/util/prometheus/gin_handler.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/clickhouse.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/column.go
  vendor/yunion.io/x/sqlchemy/backends/clickhouse/sync.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/column.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/dameng.go
  vendor/yunion.io/x/sqlchemy/backends/mysql/column.go
  vendor/yunion.io/x/sqlchemy/backends/sqlite/column.go
  vendor/yunion.io/x/sqlchemy/conditions.go
  vendor/yunion.io/x/sqlchemy/functions.go
  vendor/yunion.io/x/sqlchemy/querydefs.go
  vendor/yunion.io/x/sqlchemy/queryfield.go
  vendor/yunion.io/x/sqlchemy/rawquery.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/subquery.go
  vendor/yunion.io/x/sqlchemy/table.go
  vendor/yunion.io/x/sqlchemy/union.go
Labels: size/XXL

#22456 fix(region): optimized policy query
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/cloudcommon/db/project.go
Labels: size/L

#22457 Automated cherry pick of #22456: fix(region): optimized policy query
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/metadataresource.go
  pkg/cloudcommon/db/project.go
Labels: size/L

#22464 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/monitor.go
Labels: size/M

#22467 fix(region): vendor update
  .github/pull_request_template.md
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/mobase.go
Labels: size/M

#22468 Automated cherry pick of #22467: fix(region): vendor update
  .github/pull_request_template.md
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/mobase.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/monitor.go
Labels: size/M

#22470 fix: container backup ignoring tar errors
  pkg/hostman/guestman/pod.go
Labels: size/XS

#22451 fix: cloudmon default options
  pkg/cloudmon/options/options.go
Labels: size/XS

#22460 fix(host): umount dev shm dir after container stopped
  pkg/compute/tasks/container/container_delete_task.go
  pkg/mcclient/modules/compute/mod_isolatedevices.go
Labels: size/S, area/host

#22452 fix: task cleanup worker
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/M

#22474 fix: update README for DeepWiki
  README-CN.md
  README.md
Labels: size/XS
