Repository yunionio/cloudpods, pull requests merged in 2025-02, with the labels that each got.

#22044 fix: backup ignore file removed warning
  pkg/hostman/guestman/pod.go
Labels: size/S

#22048 fix(region): avoid panic
  pkg/controller/autoscaling/health_check.go
Labels: size/XS

#22049 Automated cherry pick of #22048: fix(region): avoid panic
  pkg/controller/autoscaling/health_check.go
Labels: size/XS

#22050 Automated cherry pick of #22048: fix(region): avoid panic
  pkg/controller/autoscaling/health_check.go
Labels: size/XS

#22045 fix(host): return error when setting container status
  pkg/hostman/container/status/status_manager.go
Labels: size/XS, area/host

#22004 Scheduler performance optimized
  pkg/scheduler/algorithm/predicates/cloudregion_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/host_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/algorithm/predicates/zone_schedtag_predicate.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/options/options.go
Labels: size/L

#22030 Automated cherry pick of #22004: Scheduler performance optimized
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/scheduler/algorithm/predicates/cloudregion_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/algorithm/predicates/zone_schedtag_predicate.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/options/options.go
Labels: size/L

#22031 Automated cherry pick of #22004: Scheduler performance optimized
  pkg/scheduler/algorithm/predicates/cloudregion_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/algorithm/predicates/zone_schedtag_predicate.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/options/options.go
Labels: size/L

#22032 Automated cherry pick of #22004: Scheduler performance optimized
  pkg/scheduler/algorithm/predicates/cloudregion_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/algorithm/predicates/zone_schedtag_predicate.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/options/options.go
Labels: size/L

#22033 Automated cherry pick of #22004: Scheduler performance optimized
  pkg/scheduler/algorithm/predicates/cloudregion_schedtag_predicate.go
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/schedtag_helper.go
  pkg/scheduler/algorithm/predicates/zone_schedtag_predicate.go
  pkg/scheduler/core/analysor.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/data_manager/schedtag/cache.go
  pkg/scheduler/data_manager/schedtag/sync.go
  pkg/scheduler/manager/manager.go
  pkg/scheduler/options/options.go
Labels: size/L

#22046 fix: image cache use specific workers
  cmd/climc/shell/compute/hosts.go
  pkg/ansibleserver/models/ansibleplaybook_instance.go
  pkg/cloudcommon/agent/storagecache.go
  pkg/cloudcommon/workmanager/manager.go
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/system_service/telegraf.go
Labels: lgtm, size/M

#22047 Automated cherry pick of #22046: fix: image cache use specific workers
  cmd/climc/shell/compute/hosts.go
  pkg/ansibleserver/models/ansibleplaybook_instance.go
  pkg/cloudcommon/agent/storagecache.go
  pkg/cloudcommon/workmanager/manager.go
  pkg/compute/models/hosts.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/system_service/telegraf.go
Labels: size/M

#22051 fix: task fetch duplicated id error
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/namevalidator.go
  pkg/cloudcommon/db/taskman/tasks.go
Labels: size/M

#22052 Automated cherry pick of #22051: fix: task fetch duplicated id error
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/fetch.go
  pkg/cloudcommon/db/namevalidator.go
Labels: size/M

#22054 fix(region): avoid panic
  pkg/compute/models/capabilities.go
  pkg/compute/models/zones.go
Labels: size/M

#22059 fix(region): resize cloud_auto disk
  pkg/compute/hostdrivers/aliyun.go
Labels: size/XS

#22060 Automated cherry pick of #22059: fix(region): resize cloud_auto disk
  pkg/compute/hostdrivers/aliyun.go
Labels: size/XS

#22056 fix(host): add amd gpu memutil metrics collect
  pkg/hostman/hostmetrics/container_cph_amd_gpu_metrics.go
  pkg/hostman/hostmetrics/container_metrics.go
Labels: size/M

#22057 fix(host): check image desc is empty
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecachemanager_local.go
Labels: size/S

#22058 Automated cherry pick of #22057: fix(host): check image desc is empty
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecachemanager_local.go
Labels: size/XS

#22064 Automated cherry pick of #22063: fix: separate backup worker
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/S

#22063 fix: separate backup worker
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
Labels: size/S

#22061 fix(region): aliyun disk resize
  pkg/compute/guestdrivers/aliyun.go
Labels: size/XS

#22062 Automated cherry pick of #22061: fix(region): aliyun disk resize
  pkg/compute/guestdrivers/aliyun.go
Labels: size/XS

#22066 fix(region): avoid panic
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
Labels: size/M

#22067 Automated cherry pick of #22066: fix(region): avoid panic
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/cloudproviders.go
  pkg/compute/models/cloudregions.go
Labels: size/M

#22065 fix(host): amd gpu memutil convert to a percentage
  pkg/hostman/hostmetrics/container_cph_amd_gpu_metrics.go
Labels: size/XS

#22068 fix(webconsole): avoid high cpu load
  pkg/webconsole/guac/tunnel.go
Labels: size/XS

#22069 Automated cherry pick of #22068: fix(webconsole): avoid high cpu load
  pkg/webconsole/guac/tunnel.go
Labels: size/XS

#22071 fix(host): ignore tar warning message error
  pkg/hostman/guestman/pod.go
Labels: size/XS, area/host

#22073 Automated cherry pick of #21738: fix(host,host-image): use nbd export images
  Makefile
  build/docker/Dockerfile.host-image
  pkg/hostimage/host_image_service.go
  pkg/hostimage/image.go
  pkg/hostimage/nbd.go
  pkg/hostman/guestman/guest_create_from_remote.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_clvm.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_nas.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/util/netutils2/http.go
  scripts/docker_push.sh
Labels: size/XXL

#22074 Automated cherry pick of #22073: Automated cherry pick of #21738: fix(host,host-image): use nbd export images
  Makefile
  build/docker/Dockerfile.host-image
  pkg/hostimage/host_image_service.go
  pkg/hostimage/image.go
  pkg/hostimage/nbd.go
  pkg/hostman/guestman/guest_create_from_remote.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_clvm.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_nas.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/storage_local.go
  pkg/hostman/storageman/storage_lvm.go
  pkg/util/netutils2/http.go
  scripts/docker_push.sh
Labels: size/XXL

#22072 fix(monitor): not split resource when notifying
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@cn/DEFAULT.email
  build/monitor/root/opt/yunion/share/notify_templates/monitor/content@en/DEFAULT.email
  pkg/apis/monitor/template.go
  pkg/cloudcommon/notifyclient/notify_internal.go
  pkg/monitor/alerting/eval_context.go
  pkg/monitor/alerting/notifiers/onecloud.go
Labels: size/M, area/monitor

#22082 fix(region): 跳过esxi存储找不到的关联宿主机
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/tag_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/template.go
Labels: size/S

#22083 Automated cherry pick of #22082: fix(region): 跳过esxi存储找不到的关联宿主机
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/tag_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/storage.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/template.go
  vendor/yunion.io/x/pkg/util/qemuimgfmt/fmt.go
Labels: size/M

#22088 fix(host): chown for pod volume
  pkg/hostman/container/volume_mount/helper.go
Labels: size/XS, area/host

#22095 fix(lbagent): telegraf configuration panic
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#22096 Automated cherry pick of #22095: fix(lbagent): telegraf configuration panic
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#22097 Automated cherry pick of #22095: fix(lbagent): telegraf configuration panic
  pkg/hostman/system_service/telegraf.go
Labels: size/XS

#22098 fix(region): skip sync server status time range
  pkg/compute/options/options.go
Labels: size/S

#22099 Automated cherry pick of #22098: fix(region): skip sync server status time range
  pkg/compute/options/options.go
Labels: size/S

#22100 Automated cherry pick of #22098: fix(region): skip sync server status time range
  pkg/compute/options/options.go
Labels: size/S

#22077 fix(monitor): cdf
  cmd/climc/shell/monitor/unifiedmonitor.go
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/mcclient/options/monitor/simplequery.go
  pkg/monitor/models/unifiedmonitor.go
  pkg/monitor/tsdb/driver/victoriametrics/client.go
Labels: size/L

#22092 fix(region): support change vm billing type
  cmd/climc/shell/compute/servers.go
  go.mod
  go.sum
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_billing_type_task.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/billing_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/instance.go
Labels: size/L

#22103 Automated cherry pick of #22092: fix(region): support change vm billing type
  cmd/climc/shell/compute/servers.go
  go.mod
  go.sum
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_billing_type_task.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/billing_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/instance.go
Labels: size/L

#22104 Automated cherry pick of #22092: fix(region): support change vm billing type
  cmd/climc/shell/compute/servers.go
  go.mod
  go.sum
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/billingresource.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/tasks/guest_change_billing_type_task.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
  pkg/util/logclient/consts_i18n.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/resources.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/billing_base.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/hcso/modelarts.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/modelarts_pool.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/instance.go
Labels: size/L

#22085 fix(host): update host-base to v0.7.0
  build/docker/Dockerfile.host
  build/docker/multi-arch/Dockerfile.host
  pkg/apigateway/service/service.go
  pkg/baremetal/service/service.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/cronman/cronman_test.go
  pkg/cloudevent/service/service.go
  pkg/cloudid/service/service.go
  pkg/cloudmon/service/service.go
  pkg/compute/service/service.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/esxi/agent.go
  pkg/hostman/host_services.go
  pkg/image/service/service.go
  pkg/keystone/service/service.go
  pkg/logger/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/service/service.go
  pkg/scheduledtask/service/service.go
  pkg/webconsole/service/service.go
Labels: size/M

#22108 Automated cherry pick of #22085: fix(host): update host-base to v0.7.0
  build/docker/Dockerfile.host
  build/docker/multi-arch/Dockerfile.host
  pkg/apigateway/service/service.go
  pkg/baremetal/service/service.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/cronman/cronman_test.go
  pkg/cloudevent/service/service.go
  pkg/cloudid/service/service.go
  pkg/cloudmon/service/service.go
  pkg/compute/service/service.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/esxi/agent.go
  pkg/hostman/host_services.go
  pkg/image/service/service.go
  pkg/keystone/service/service.go
  pkg/logger/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/service/service.go
  pkg/scheduledtask/service/service.go
  pkg/webconsole/service/service.go
Labels: size/M

#22109 Automated cherry pick of #22108: Automated cherry pick of #22085: fix(host): update host-base to v0.7.0
  build/docker/Dockerfile.host
  build/docker/multi-arch/Dockerfile.host
  pkg/apigateway/service/service.go
  pkg/baremetal/service/service.go
  pkg/cloudcommon/cronman/cronman.go
  pkg/cloudcommon/cronman/cronman_test.go
  pkg/cloudevent/service/service.go
  pkg/cloudid/service/service.go
  pkg/cloudmon/service/service.go
  pkg/compute/service/service.go
  pkg/devtool/models/devtoolcronjob.go
  pkg/esxi/agent.go
  pkg/hostman/host_services.go
  pkg/image/service/service.go
  pkg/keystone/service/service.go
  pkg/logger/service/service.go
  pkg/monitor/service/service.go
  pkg/notify/service/service.go
  pkg/scheduledtask/service/service.go
  pkg/webconsole/service/service.go
Labels: size/M

#22117 fix(region): avoid panic
  pkg/compute/tasks/security_group_rule_update_task.go
Labels: size/XS

#22118 Automated cherry pick of #22117: fix(region): avoid panic
  pkg/compute/tasks/security_group_rule_update_task.go
Labels: size/XS

#22119 Automated cherry pick of #22117: fix(region): avoid panic
  pkg/compute/tasks/security_group_rule_update_task.go
Labels: size/XS

#22114 fix(monitor): split tags and cloud_tags
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/datasource.go
Labels: size/S, area/monitor

#22121 Automated cherry pick of #22114: fix(monitor): split tags and cloud_tags
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/datasource.go
Labels: size/S

#22122 Automated cherry pick of #22114: fix(monitor): split tags and cloud_tags
  pkg/apis/monitor/unifiedmonitor_query.go
  pkg/monitor/alerting/conditions/query.go
  pkg/monitor/models/datasource.go
Labels: size/S

#22110 fix: monitor query close response http client
  pkg/monitor/tsdb/driver/victoriametrics/client.go
Labels: size/S

#22111 Automated cherry pick of #22110: fix: monitor query close response http client
  pkg/monitor/tsdb/driver/victoriametrics/client.go
Labels: size/S

#22113 fix: separate default admin secgroup id for kvm and pod
  pkg/compute/models/guest_secgroups.go
  pkg/compute/models/guests.go
  pkg/compute/models/secgroups.go
  pkg/compute/options/options.go
Labels: size/M

#22138 Automated cherry pick of #21412: fix(scheduler): avoid_same_host 策略分数过高导致调度分配不均
  pkg/scheduler/algorithm/priorities/guest/avoid_same_host.go
Labels: size/XS

#22139 Automated cherry pick of #21412: fix(scheduler): avoid_same_host 策略分数过高导致调度分配不均
  pkg/scheduler/algorithm/priorities/guest/avoid_same_host.go
Labels: size/XS

#22125 fix(climc): support create vm with tags
  pkg/mcclient/options/compute/servers.go
Labels: lgtm, size/S

#22126 Automated cherry pick of #22125: fix(climc): support create vm with tags
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#22127 Automated cherry pick of #22125: fix(climc): support create vm with tags
  pkg/mcclient/options/compute/servers.go
Labels: size/S

#22130 fix(scheduler): 尽早发现子网ip不足引起的调度失败
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/models/pending_usage.go
Labels: size/M, area/scheduler

#22131 Automated cherry pick of #22130: fix(scheduler): 尽早发现子网ip不足引起的调度失败
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/models/pending_usage.go
Labels: size/M

#22132 Automated cherry pick of #22130: fix(scheduler): 尽早发现子网ip不足引起的调度失败
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/models/pending_usage.go
Labels: size/M

#22133 Automated cherry pick of #22130: fix(scheduler): 尽早发现子网ip不足引起的调度失败
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/models/pending_usage.go
Labels: size/M

#22135 Automated cherry pick of #22130: fix(scheduler): 尽早发现子网ip不足引起的调度失败
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/models/pending_usage.go
Labels: size/M

#22136 Automated cherry pick of #22135: Automated cherry pick of #22130: fix(scheduler): 尽早发现子网ip不足引起的调度失败
  pkg/scheduler/algorithm/predicates/network_predicate.go
  pkg/scheduler/cache/candidate/base.go
  pkg/scheduler/cache/candidate/hosts.go
  pkg/scheduler/models/pending_usage.go
Labels: size/M

#22144 feat(host): untar TGZ image when image cached
  pkg/hostman/storageman/imagecache_local.go
  pkg/hostman/storageman/imagecachemanager_local.go
Labels: size/S, area/host

#22146 Automated cherry pick of #22143: fix(monitor): always skip_check_series for metric-measurement api
  pkg/monitor/models/datasource.go
Labels: size/XS

#22153 fix(climc): show ip column of action-show command
  cmd/climc/shell/logger/actions.go
  pkg/mcclient/modules/logger/mod_actions.go
Labels: size/XS, area/climc

#22154 Automated cherry pick of #22153: fix(climc): show ip column of action-show command
  cmd/climc/shell/logger/actions.go
  pkg/mcclient/modules/logger/mod_actions.go
Labels: size/XS

#22155 Automated cherry pick of #22153: fix(climc): show ip column of action-show command
  cmd/climc/shell/logger/actions.go
  pkg/mcclient/modules/logger/mod_actions.go
Labels: size/XS

#22140 fix(host): add check default mem dev exist on hotplug
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#22141 Automated cherry pick of #22140: fix(host): add check default mem dev exist on hotplug
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#22142 Automated cherry pick of #22140: fix(host): add check default mem dev exist on hotplug
  pkg/hostman/guestman/guesttasks.go
Labels: size/XS

#22147 fix(host): check has vga use desc dev_type instead of host dev object
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
Labels: size/XS

#22148 Automated cherry pick of #22147: fix(host): check has vga use desc dev_type instead of host dev object
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
Labels: size/XS

#22149 Automated cherry pick of #22147: fix(host): check has vga use desc dev_type instead of host dev object
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pci.go
Labels: size/XS

#22105 fix(region): lvm disk path add dev prefix
  pkg/apis/compute/storage_const.go
  pkg/compute/models/disks.go
Labels: size/S

#22151 Automated cherry pick of #22105: fix(region): lvm disk path add dev prefix
  pkg/apis/compute/storage_const.go
  pkg/compute/models/disks.go
Labels: size/S

#22124 fix(region): update storage type and dev-type fied
  pkg/compute/models/isolated_devices.go
Labels: size/XS

#22161 fix(region): 允许不同账号dns zone重名
  pkg/compute/models/dnszones.go
Labels: size/S

#22162 Automated cherry pick of #22161: fix(region): 允许不同账号dns zone重名
  pkg/compute/models/dnszones.go
Labels: size/S

#22163 Automated cherry pick of #22161: fix(region): 允许不同账号dns zone重名
  pkg/compute/models/dnszones.go
Labels: size/S

#22165 fix: disable server TLS 1.0, 1.x and 1.2 SHA1
  pkg/appsrv/appsrv.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/M

#22169 Automated cherry pick of #22165: fix: disable server TLS 1.0, 1.x and 1.2 SHA1
  pkg/appsrv/appsrv.go
  pkg/cloudcommon/app/app.go
  pkg/cloudcommon/options/options.go
Labels: size/M

#22156 fix: remove default values from cmtbound columns
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#22157 Automated cherry pick of #22156: fix: remove default values from cmtbound columns
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#22158 Automated cherry pick of #22156: fix: remove default values from cmtbound columns
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#22159 Automated cherry pick of #22156: fix: remove default values from cmtbound columns
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#22160 Automated cherry pick of #22156: fix: remove default values from cmtbound columns
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#22166 Automated cherry pick of #22156: fix: remove default values from cmtbound columns
  pkg/compute/models/hosts.go
  pkg/compute/models/storages.go
Labels: size/S

#22175 fix(monitor,webconsole): enable app profiling
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/XS, area/webconsole, area/monitor

#22176 Automated cherry pick of #22175: fix(monitor,webconsole): enable app profiling
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/XS

#22177 Automated cherry pick of #22175: fix(monitor,webconsole): enable app profiling
  pkg/monitor/service/handlers.go
  pkg/webconsole/service/service.go
Labels: size/XS

#22171 fix(region): allow create disk when vm running
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/cloudpods.go
  pkg/compute/guestdrivers/ctyun.go
  pkg/compute/guestdrivers/ecloud.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/h3c.go
  pkg/compute/guestdrivers/hcs.go
  pkg/compute/guestdrivers/hcsop.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/huaweistack.go
  pkg/compute/guestdrivers/incloudsphere.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/nutanix.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/guestdrivers/volcengine.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
Labels: size/M

#22172 Automated cherry pick of #22171: fix(region): allow create disk when vm running
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/cloudpods.go
  pkg/compute/guestdrivers/ctyun.go
  pkg/compute/guestdrivers/ecloud.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/h3c.go
  pkg/compute/guestdrivers/hcs.go
  pkg/compute/guestdrivers/hcsop.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/huaweistack.go
  pkg/compute/guestdrivers/incloudsphere.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/nutanix.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/guestdrivers/volcengine.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
Labels: size/M

#22173 Automated cherry pick of #22171: fix(region): allow create disk when vm running
  pkg/apis/compute/guests.go
  pkg/compute/guestdrivers/aliyun.go
  pkg/compute/guestdrivers/aws.go
  pkg/compute/guestdrivers/azure.go
  pkg/compute/guestdrivers/baremetals.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/cloudpods-kvm.go
  pkg/compute/guestdrivers/ctyun.go
  pkg/compute/guestdrivers/ecloud.go
  pkg/compute/guestdrivers/esxi.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/guestdrivers/h3c.go
  pkg/compute/guestdrivers/hcs.go
  pkg/compute/guestdrivers/hcsop.go
  pkg/compute/guestdrivers/huawei.go
  pkg/compute/guestdrivers/huaweistack.go
  pkg/compute/guestdrivers/incloudsphere.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/guestdrivers/nutanix.go
  pkg/compute/guestdrivers/openstack.go
  pkg/compute/guestdrivers/proxmox.go
  pkg/compute/guestdrivers/qcloud.go
  pkg/compute/guestdrivers/ucloud.go
  pkg/compute/guestdrivers/volcengine.go
  pkg/compute/guestdrivers/zstack.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
Labels: size/M

#22180 fix(notify): avoid panic when clean task
  pkg/notify/service/handlers.go
Labels: size/XS

#22181 fix(region): fix typo
  pkg/apis/compute/cloudaccount.go
Labels: size/XS

#22182 Automated cherry pick of #22181: fix(region): fix typo
  pkg/apis/compute/cloudaccount.go
Labels: size/XS

#22184 fix(region): fast sync image
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guest_actions.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/consts.go
Labels: size/L

#22185 Automated cherry pick of #22184: fix(region): fast sync image
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guest_actions.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/consts.go
Labels: size/L

#22186 Automated cherry pick of #22184: fix(region): fast sync image
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount.go
  pkg/apis/monitor/zz_generated.model.go
  pkg/compute/models/cloudsync.go
  pkg/compute/models/guest_actions.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/consts.go
Labels: size/L

#22205 fix(mcclient): recover panic when invoking container exec
  pkg/mcclient/modules/compute/mod_containers.go
  pkg/mcclient/options/compute/containers.go
Labels: size/M, area/climc, area/apigateway

#22202 fix(esxi-agent): vendor update
  go.mod
  go.sum
  pkg/hostman/storageman/storage_agent.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/cephfs/client.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#22203 Automated cherry pick of #22202: fix(esxi-agent): vendor update
  go.mod
  go.sum
  pkg/hostman/storageman/storage_agent.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#22204 Automated cherry pick of #22202: fix(esxi-agent): vendor update
  go.mod
  go.sum
  pkg/hostman/storageman/storage_agent.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/devtools.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/vdisk.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
Labels: size/M

#22196 Automated cherry pick of #22195: feat(region,host): add guest disk auto reset on shutdown support
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/models/disks.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/storages.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/options/options.go
  pkg/util/procutils/executor.go
  pkg/util/procutils/procutils.go
Labels: size/M

#22198 Automated cherry pick of #22195: feat(region,host): add guest disk auto reset on shutdown support
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/models/disks.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/storages.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/options/options.go
  pkg/util/procutils/executor.go
  pkg/util/procutils/procutils.go
Labels: size/M

#22199 Automated cherry pick of #22195: feat(region,host): add guest disk auto reset on shutdown support
  cmd/climc/shell/compute/disks.go
  pkg/apis/compute/api.go
  pkg/apis/compute/guest_disk.go
  pkg/cloudcommon/cmdline/parser.go
  pkg/compute/models/disks.go
  pkg/compute/models/guestdisks.go
  pkg/compute/models/storages.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/qemu/generate.go
  pkg/hostman/options/options.go
  pkg/util/procutils/executor.go
  pkg/util/procutils/procutils.go
Labels: size/M

#22190 Automated cherry pick of #22189: fix(host): shared lvm activte with auto activation option
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/XS

#22191 Automated cherry pick of #22189: fix(host): shared lvm activte with auto activation option
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/XS

#22192 Automated cherry pick of #22189: fix(host): shared lvm activte with auto activation option
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/XS

#22193 Automated cherry pick of #22189: fix(host): shared lvm activte with auto activation option
  pkg/hostman/storageman/lvmutils/lvmutils.go
  pkg/hostman/storageman/storage_slvm.go
Labels: size/XS

#22201 fix(host,monitor): container memory metrics
  pkg/hostman/hostmetrics/container_metrics.go
  pkg/monitor/dbinit/measurements/container.go
  pkg/monitor/dbinit/measurements/pod.go
  pkg/util/pod/stats/cri_stats_provider.go
Labels: size/M, area/host, area/monitor

#22206 Fix/deploy guest add cpu vendor
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestman/guestman.go
Labels: lgtm, size/S

#22207 Automated cherry pick of #22206: Fix/deploy guest add cpu vendor
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestman/guestman.go
Labels: size/S

#22208 Automated cherry pick of #22206: Fix/deploy guest add cpu vendor
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/guestman/guestman.go
Labels: size/S

#22187 feat(region,host): using BaremetalUploadAllGuestsStatusTask when host online
  pkg/apis/compute/container.go
  pkg/apis/compute/host.go
  pkg/compute/hostdrivers/base.go
  pkg/compute/hostdrivers/kvm.go
  pkg/compute/models/containers.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hostdrivers.go
  pkg/compute/models/hosts.go
  pkg/compute/tasks/baremetal_sync_status_task.go
  pkg/compute/tasks/baremetal_upload_all_guests_status_task.go
  pkg/compute/tasks/container_sync_status_task.go
  pkg/compute/tasks/guest_syncstatus_task.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/guestman/runtime.go
  pkg/hostman/hostutils/hostutils.go
  pkg/mcclient/options/compute/containers.go
Labels: area/region, area/host, size/XL
