Repository yunionio/cloudpods, pull requests merged in 2025-09, with the labels that each got.

#23205 feat(host): add SdnFetchDataFromComputeService option
  pkg/hostman/options/options.go
Labels: size/XS, area/host

#23206 Automated cherry pick of #23205: feat(host): add SdnFetchDataFromComputeService option
  pkg/hostman/options/options.go
Labels: size/XS

#23222 fix: network filter by ipv6 address
  go.mod
  go.sum
  pkg/compute/models/networks.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metric.md
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/alb.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/albservergroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/albservergroupserver.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance_gloable_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancercert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/mfa.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/functions.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/XXL

#23226 Automated cherry pick of #23222: fix: network filter by ipv6 address
  go.mod
  go.sum
  pkg/compute/models/networks.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancercert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/functions.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/L

#23223 Automated cherry pick of #23222: fix: network filter by ipv6 address
  go.mod
  go.sum
  pkg/compute/models/networks.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/objectstore.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/alb.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/albservergroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/albservergroupserver.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancercert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/sqlchemy/backends.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/functions.go
  vendor/yunion.io/x/sqlchemy/backends_base.go
  vendor/yunion.io/x/sqlchemy/functions.go
Labels: size/XL

#23219 fix: image s3 direct download option
  pkg/image/models/images.go
  pkg/image/options/options.go
Labels: size/XS

#23220 Automated cherry pick of #23219: fix: image s3 direct download option
  pkg/image/models/images.go
  pkg/image/options/options.go
Labels: size/XS

#23221 Automated cherry pick of #23219: fix: image s3 direct download option
  pkg/image/models/images.go
  pkg/image/options/options.go
Labels: size/XS

#23212 fix(host): live migrate compat ipv6
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu/generate.go
Labels: size/XS

#23227 Automated cherry pick of #23210: fix(region): distinct cloudprovider fields
  pkg/compute/models/access_groups.go
  pkg/compute/models/ai_gateway.go
  pkg/compute/models/app.go
  pkg/compute/models/buckets.go
  pkg/compute/models/cdn_domains.go
  pkg/compute/models/cloudprovider_quotas.go
  pkg/compute/models/cloudproviderregions.go
  pkg/compute/models/dbinstance_backups.go
  pkg/compute/models/dbinstances.go
  pkg/compute/models/diskbackups.go
  pkg/compute/models/dnszones.go
  pkg/compute/models/elastic_search.go
  pkg/compute/models/elasticcache_instances.go
  pkg/compute/models/elasticips.go
  pkg/compute/models/external_projects.go
  pkg/compute/models/filesystem.go
  pkg/compute/models/hosts.go
  pkg/compute/models/instance_backup.go
  pkg/compute/models/instance_snapshots.go
  pkg/compute/models/inter_vpc_network.go
  pkg/compute/models/kafka.go
  pkg/compute/models/kube_clusters.go
  pkg/compute/models/loadbalancer_health_checks.go
  pkg/compute/models/loadbalanceracls.go
  pkg/compute/models/loadbalancercertificates.go
  pkg/compute/models/loadbalancers.go
  pkg/compute/models/managedresource.go
  pkg/compute/models/miscresources.go
  pkg/compute/models/modelarts_pool_sku.go
  pkg/compute/models/modelarts_pools.go
  pkg/compute/models/mongodb.go
  pkg/compute/models/mount_targets.go
  pkg/compute/models/networkinterfaces.go
  pkg/compute/models/secgrouprules.go
  pkg/compute/models/secgroups.go
  pkg/compute/models/snapshotpolicy.go
  pkg/compute/models/snapshots.go
  pkg/compute/models/sslcertificate.go
  pkg/compute/models/storagecacheresource.go
  pkg/compute/models/storagecaches.go
  pkg/compute/models/storages.go
  pkg/compute/models/tablestores.go
  pkg/compute/models/vpcresource.go
  pkg/compute/models/vpcs.go
  pkg/compute/models/waf_instances.go
  pkg/compute/models/waf_ipsets.go
  pkg/compute/models/waf_regexsets.go
  pkg/compute/models/waf_rule_groups.go
  pkg/compute/models/wireresource.go
  pkg/compute/models/wires.go
Labels: size/L

#23228 fix(region): add kafka and mongodb capability
  pkg/compute/models/capabilities.go
Labels: size/S

#23232 Automated cherry pick of #23231: fix(region): add disk change billing type log
  pkg/compute/tasks/guest/guest_create_disk_task.go
Labels: size/S

#23231 fix(region): add disk change billing type log
  pkg/compute/tasks/guest/guest_create_disk_task.go
Labels: size/S

#23235 fix(region): sync prepaid disk expired time
  pkg/compute/tasks/guest/guest_create_disk_task.go
Labels: size/XS

#23244 Automated cherry pick of #23243: fix(region): support retention server by tag
  pkg/compute/models/hosts.go
  pkg/compute/options/options.go
Labels: size/M

#23245 fix(region): support retention server by tags
  pkg/compute/models/hosts.go
  pkg/compute/options/options.go
Labels: size/S

#23248 Automated cherry pick of #23247: fix(region): retention server by tag
  pkg/compute/models/hosts.go
Labels: size/XS

#23254 fix(region): sync cloudpods host storage info
  pkg/mcclient/cloudpods/host.go
Labels: size/XS

#23256 fix(region): sync cloudpods baremetal isolated device
  pkg/mcclient/cloudpods/isolated_devices.go
Labels: size/XS

#23257 Automated cherry pick of #23256: fix(region): sync cloudpods baremetal isolated device
  pkg/mcclient/cloudpods/isolated_devices.go
Labels: size/XS

#23263 fix(region): sync cloudpods ipmi ip addr
  pkg/mcclient/cloudpods/host.go
Labels: size/XS

#23266 Automated cherry pick of #23265: fix(climc): monitor-alertrecords-total-alert command
  cmd/climc/shell/monitor/alertrecord.go
  pkg/mcclient/options/monitor/alertrecord.go
Labels: size/XS

#23267 Automated cherry pick of #23265: fix(climc): monitor-alertrecords-total-alert command
  cmd/climc/shell/monitor/alertrecord.go
  pkg/mcclient/options/monitor/alertrecord.go
Labels: size/XS

#23270 Automated cherry pick of #23268: fix(region): support hyperdisk for gcp
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/hostdrivers/google.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/metrics.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/elastic_search_instance_types.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/mongodb.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/esxi/virtualmachine.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/rds_mysql.go
Labels: size/L

#23269 Automated cherry pick of #23268: fix(region): support hyperdisk for gcp
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/google.go
  pkg/compute/hostdrivers/google.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/instance.go
Labels: size/L

#23249 fix: image self check status
  pkg/image/models/image_subs.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#23251 Automated cherry pick of #23249: fix: image self check status
  pkg/image/models/image_subs.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#23252 Automated cherry pick of #23249: fix: image self check status
  pkg/image/models/image_subs.go
  pkg/image/models/images.go
  pkg/image/options/options.go
  pkg/image/service/service.go
Labels: size/M

#23259 Automated cherry pick of #23258: fix: ipv6 ra should be sent periodically
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/runtime.go
  pkg/hostman/guestman/types/interface.go
  pkg/hostman/hostinfo/hostdhcp/dhcpserver6.go
  pkg/hostman/hostinfo/hostdhcp/icmp6handlers.go
  pkg/hostman/hostinfo/hostinfo.go
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
Labels: size/L

#23273 Automated cherry pick of #23271: fix(region): update cloudprovider external id
  pkg/compute/models/cloudaccounts.go
Labels: size/XS

#23274 fix(monitor): fetch total alert resources from monitor_resource_alert
  pkg/monitor/models/alertrecord.go
  pkg/monitor/models/monitor_resource_alert.go
  pkg/monitor/models/monitorscoperesource.go
Labels: size/M, area/monitor

#23294 Automated cherry pick of #23292: feat(host): hide host files mounted to container
  pkg/hostman/container/snapshot_service/snapshot_service.go
  pkg/hostman/container/volume_mount/interface.go
  pkg/hostman/container/volume_mount/text.go
  pkg/hostman/guestman/pod.go
Labels: size/M

#23050 Automated cherry pick of #23046: fix(region): virtual isolated device balance on guest start
  cmd/climc/shell/compute/hosts.go
  cmd/climc/shell/compute/servers.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host.go
  pkg/apis/compute/isolated_device_const.go
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/pod.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/hosts.go
  pkg/compute/models/isolated_devices.go
  pkg/compute/tasks/guest/pod_start_task.go
  pkg/hostman/options/options.go
  pkg/mcclient/options/compute/host.go
Labels: size/L

#23300 fix(climc): sku create params
  pkg/mcclient/options/compute/serverskus.go
Labels: size/XS

#23316 Automated cherry pick of #23314: fix(cloudmon): alert metric with tenant id
  pkg/apis/monitor/alertrecord.go
Labels: size/S

#23315 Automated cherry pick of #23314: fix(cloudmon): alert metric with tenant id
  pkg/apis/monitor/alertrecord.go
Labels: size/S

#23314 fix(cloudmon): alert metric with tenant id
  pkg/apis/monitor/alertrecord.go
Labels: size/S

#23319 Automated cherry pick of #23317: fix(region): remove debug sql
  pkg/compute/models/networks.go
Labels: size/XS

#23318 Automated cherry pick of #23317: fix(region): remove debug sql
  pkg/compute/models/networks.go
Labels: size/XS

#23310 fix(monitor): diffTagKeys are empty when only one series in results
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/XS, area/monitor

#23313 Automated cherry pick of #23310: fix(monitor): diffTagKeys are empty when only one series in results
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/XS

#23312 Automated cherry pick of #23310: fix(monitor): diffTagKeys are empty when only one series in results
  pkg/monitor/tsdb/driver/victoriametrics/vm.go
Labels: size/XS

#23323 Automated cherry pick of #23322: fix(notify): optimized workwx access token expired time
  pkg/apis/notify/config.go
  pkg/notify/sender/workwx.go
Labels: size/M

#23324 Automated cherry pick of #23322: fix(notify): optimized workwx access token expired time
  pkg/apis/notify/config.go
  pkg/notify/sender/workwx.go
Labels: size/M

#23325 fix(region): disk reset webhook
  pkg/cloudcommon/notifyclient/events.go
  pkg/compute/tasks/disk/disk_reset_task.go
  pkg/notify/models/topic.go
Labels: size/XS

#23337 fix: check os_arch when server rebuilding root
  pkg/apis/const.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#23338 Automated cherry pick of #23337: fix: check os_arch when server rebuilding root
  pkg/apis/const.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#23339 Automated cherry pick of #23338: Automated cherry pick of #23337: fix: check os_arch when server rebuilding root
  pkg/apis/const.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#23340 Automated cherry pick of #23338: Automated cherry pick of #23337: fix: check os_arch when server rebuilding root
  pkg/apis/const.go
  pkg/compute/models/guest_actions.go
Labels: size/S

#23333 fix(host,host-deployer): support lvm disk resize
  pkg/esxi/handler/handlers.go
  pkg/hostman/diskutils/deploy_iface/deployer.go
  pkg/hostman/diskutils/fsutils/driver/doc.go
  pkg/hostman/diskutils/fsutils/driver/driver.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/fsutils/growpart.go
  pkg/hostman/diskutils/fsutils/lvm.go
  pkg/hostman/diskutils/fsutils/manager.go
  pkg/hostman/diskutils/fsutils/resizefs.go
  pkg/hostman/diskutils/interface.go
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/diskutils/qemu_kvm/local_driver.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestfs/fsdriver/utils.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/localdeploy.go
  pkg/hostman/monitor/qga/fsdriver.go
  pkg/hostman/monitor/qga/part.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/storageman/disk_agent.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_nas.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storagehelper.go
Labels: size/XXL

#23334 Automated cherry pick of #23333: fix(host,host-deployer): support lvm disk resize
  pkg/esxi/handler/handlers.go
  pkg/hostman/diskutils/deploy_iface/deployer.go
  pkg/hostman/diskutils/fsutils/driver/doc.go
  pkg/hostman/diskutils/fsutils/driver/driver.go
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/diskutils/fsutils/growpart.go
  pkg/hostman/diskutils/fsutils/lvm.go
  pkg/hostman/diskutils/fsutils/manager.go
  pkg/hostman/diskutils/fsutils/resizefs.go
  pkg/hostman/diskutils/interface.go
  pkg/hostman/diskutils/kvm.go
  pkg/hostman/diskutils/libguestfs/driver.go
  pkg/hostman/diskutils/nbd/driver.go
  pkg/hostman/diskutils/qemu_kvm/driver.go
  pkg/hostman/diskutils/qemu_kvm/local_driver.go
  pkg/hostman/diskutils/vddk.go
  pkg/hostman/guestfs/kvmpart/kvmpart.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/pod.go
  pkg/hostman/hostdeployer/apis/deploy.pb.go
  pkg/hostman/hostdeployer/apis/deploy.proto
  pkg/hostman/hostdeployer/apis/deploy_grpc.pb.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
  pkg/hostman/hostdeployer/deployserver/localdeploy.go
  pkg/hostman/monitor/qga/fsdriver.go
  pkg/hostman/monitor/qga/qga.go
  pkg/hostman/storageman/disk_agent.go
  pkg/hostman/storageman/disk_base.go
  pkg/hostman/storageman/disk_local.go
  pkg/hostman/storageman/disk_lvm.go
  pkg/hostman/storageman/disk_nas.go
  pkg/hostman/storageman/disk_rbd.go
  pkg/hostman/storageman/disk_slvm.go
  pkg/hostman/storageman/diskhandlers/diskhandler.go
  pkg/hostman/storageman/storagehelper.go
Labels: size/XXL

#23305 fix(region): rds backup sync
  pkg/compute/models/dbinstance_backups.go
Labels: size/XS

#23331 Automated cherry pick of #23327: fix(scheduler): watch serversku
  pkg/scheduler/data_manager/sku/sku.go
  pkg/scheduler/service/service.go
Labels: size/L

#23328 Automated cherry pick of #23327: fix(scheduler): watch serversku
  pkg/scheduler/data_manager/sku/sku.go
  pkg/scheduler/service/service.go
Labels: size/L

#23327 fix(scheduler): watch serversku
  pkg/scheduler/data_manager/sku/sku.go
  pkg/scheduler/service/service.go
Labels: size/L, area/scheduler

#23336 fix: linux sshd_config support
  pkg/hostman/guestfs/core.go
  pkg/hostman/guestfs/fsdriver/android.go
  pkg/hostman/guestfs/fsdriver/esxi.go
  pkg/hostman/guestfs/fsdriver/interface.go
  pkg/hostman/guestfs/fsdriver/linux.go
  pkg/hostman/guestfs/fsdriver/macos.go
  pkg/hostman/guestfs/fsdriver/sshd_config.go
  pkg/hostman/guestfs/fsdriver/sshd_config_test.go
  pkg/hostman/guestfs/fsdriver/windows.go
Labels: size/L

#23346 fix: host backup task worker limit
  pkg/hostman/hostutils/hostutils.go
  pkg/hostman/options/options.go
Labels: size/XS

#23350 fix(region): add expired release notify hour options
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/XS

#23352 Automated cherry pick of #23350: fix(region): add expired release notify hour options
  pkg/compute/options/options.go
  pkg/compute/service/service.go
Labels: size/XS

#23365 Automated cherry pick of #23363: fix: network filter by ip error for dameng
  Makefile
  go.mod
  go.sum
  pkg/compute/models/networks.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudregions_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/dbinstance_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/regiondata.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/alb.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/albservergroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/albservergroupserver.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/dbinstance_cluster.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerbackend.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancercert.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistener.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/loadbalancerlistenerrule.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aws/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/google/latitude_and_longitude.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/loadbalancer_backend.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/sync.go
  vendor/yunion.io/x/sqlchemy/reflect.go
  vendor/yunion.io/x/sqlchemy/update.go
Labels: size/XL

#23371 Automated cherry pick of #23370: fix: auto cleanup obsolete password records
  pkg/keystone/models/initdb.go
  pkg/keystone/models/passwords.go
  pkg/keystone/options/options.go
  pkg/keystone/service/service.go
Labels: size/L

#23364 Automated cherry pick of #23363: fix: network filter by ip error for dameng
  pkg/compute/models/networks.go
Labels: size/S

#23363 fix: network filter by ip error for dameng
  pkg/compute/models/networks.go
Labels: size/S

#23360 fix(host): clear the rootfs of container before starting
  pkg/hostman/guestman/pod.go
Labels: size/XS, area/host

#23361 Automated cherry pick of #23360: fix(host): clear the rootfs of container before starting
  pkg/hostman/guestman/pod.go
Labels: size/XS

#23362 Automated cherry pick of #23360: fix(host): clear the rootfs of container before starting
  pkg/hostman/guestman/pod.go
Labels: size/XS

#23357 fix(host-deployer): loop dev resize diskfs umounted and f2fs support
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestman/pod_helper.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/S

#23359 Automated cherry pick of #23358: Automated cherry pick of #23357: fix(host-deployer): loop dev resize diskfs umounted and f2fs support
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/guestman/pod_helper.go
  pkg/hostman/hostdeployer/deployserver/deployserver.go
Labels: size/S

#23382 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
Labels: size/M

#23383 Automated cherry pick of #23382: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
Labels: size/M

#23384 Automated cherry pick of #23382: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
Labels: size/M

#23385 Automated cherry pick of #23382: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/aliyun/aliyun.go
  vendor/yunion.io/x/sqlchemy/ascii.go
  vendor/yunion.io/x/sqlchemy/backends/dameng/conditions.go
Labels: size/M

#23389 Automated cherry pick of #23388: fix(region): support cnware
  cmd/climc/shell/compute/cloudaccounts.go
  cmd/climc/shell/compute/usages.go
  cmd/climc/shell/misc/feature.go
  go.mod
  go.sum
  pkg/apis/compute/cloudaccount_const.go
  pkg/apis/compute/guest_const.go
  pkg/apis/compute/host_const.go
  pkg/apis/compute/storage_const.go
  pkg/apis/webconsole/consts.go
  pkg/cloudmon/providerdriver/cnware.go
  pkg/compute/guestdrivers/cnware.go
  pkg/compute/hostdrivers/cnware.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guest_template.go
  pkg/compute/regiondrivers/cnware.go
  pkg/mcclient/options/base.go
  pkg/mcclient/options/compute/cloudaccounts.go
  pkg/mcclient/options/compute/servers.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/cloudaccount_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/guest_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/host_const.go
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
Labels: size/XL

#23397 fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/ksyun.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/secgroup_rules.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/wire.go
Labels: size/XXL

#23398 Automated cherry pick of #23397: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/ksyun.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/secgroup_rules.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/wire.go
Labels: size/XXL

#23399 Automated cherry pick of #23397: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/compute/models/guests.go
  pkg/compute/regiondrivers/ksyun.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancenic.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/provider/provider.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/secgroup_rules.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storagecache.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/wire.go
Labels: size/XXL

#23401 fix(host): unmount post overlay dir without accquire cached image
  pkg/hostman/container/volume_mount/disk/disk.go
  pkg/hostman/container/volume_mount/disk/overlay.go
  pkg/hostman/container/volume_mount/disk/post_overlay_image.go
  pkg/hostman/storageman/imagecachemanager_base.go
  pkg/hostman/storageman/imagecachemanager_local.go
Labels: size/M, area/host

#23402 Automated cherry pick of #23401: fix(host): unmount post overlay dir without accquire cached image
  pkg/hostman/container/volume_mount/disk/disk.go
  pkg/hostman/container/volume_mount/disk/overlay.go
  pkg/hostman/container/volume_mount/disk/post_overlay_image.go
  pkg/hostman/storageman/imagecachemanager_base.go
  pkg/hostman/storageman/imagecachemanager_local.go
Labels: size/M

#23386 fix(host-deployer): allow growpart on primary partition
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#23393 Automated cherry pick of #23386: fix(host-deployer): allow growpart on primary partition
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#23394 Automated cherry pick of #23386: fix(host-deployer): allow growpart on primary partition
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#23395 Automated cherry pick of #23394: Automated cherry pick of #23386: fix(host-deployer): allow growpart on primary partition
  pkg/hostman/diskutils/fsutils/fsutils.go
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/S

#23374 fix(region,host): guest add vnc screen dump support
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/compute/serverscreendumps.go
  pkg/apis/compute/guest_image.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guestscreendump.go
  pkg/compute/service/handlers.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/image/drivers/s3/minio.go
  pkg/mcclient/modules/compute/mod_screendump.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL, request-merge

#23379 Automated cherry pick of #23374: fix(region,host): guest add vnc screen dump support
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/compute/serverscreendumps.go
  pkg/apis/compute/guest_image.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guestscreendump.go
  pkg/compute/service/handlers.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/image/drivers/s3/minio.go
  pkg/mcclient/modules/compute/mod_screendump.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL

#23377 Automated cherry pick of #23374: fix(region,host): guest add vnc screen dump support
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/compute/serverscreendumps.go
  pkg/apis/compute/guest_image.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guestscreendump.go
  pkg/compute/service/handlers.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/image/drivers/s3/minio.go
  pkg/mcclient/modules/compute/mod_screendump.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL

#23378 Automated cherry pick of #23377: Automated cherry pick of #23374: fix(region,host): guest add vnc screen dump support
  cmd/climc/shell/compute/servers.go
  cmd/climc/shell/compute/serverscreendumps.go
  pkg/apis/compute/guest_image.go
  pkg/cloudcommon/db/db_dispatcher.go
  pkg/cloudcommon/db/opslog_const.go
  pkg/cloudcommon/options/options.go
  pkg/compute/guestdrivers/base.go
  pkg/compute/guestdrivers/kvm.go
  pkg/compute/models/guest_actions.go
  pkg/compute/models/guestdrivers.go
  pkg/compute/models/guestscreendump.go
  pkg/compute/service/handlers.go
  pkg/hostman/guestman/guest-agent.go
  pkg/hostman/guestman/guesthandlers/guesthandler.go
  pkg/hostman/guestman/guestman.go
  pkg/hostman/guestman/guesttasks.go
  pkg/hostman/guestman/qemu-kvm.go
  pkg/hostman/host_services.go
  pkg/hostman/monitor/hmp.go
  pkg/hostman/monitor/monitor.go
  pkg/hostman/monitor/qmp.go
  pkg/image/drivers/s3/minio.go
  pkg/mcclient/modules/compute/mod_screendump.go
  pkg/mcclient/options/compute/servers.go
  pkg/util/logclient/consts.go
Labels: size/XL

#23404 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
Labels: size/S

#23405 Automated cherry pick of #23404: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
Labels: size/S

#23406 Automated cherry pick of #23404: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
Labels: size/S

#23407 Automated cherry pick of #23404: fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/huawei/bucket.go
Labels: size/S

#23412 Automated cherry pick of #23411: fix(host-deployer): update host-deployer-base to 1.4.11
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#23414 Automated cherry pick of #23413: Automated cherry pick of #23411: fix(host-deployer): update host-deployer-base to 1.4.11
  build/docker/Dockerfile.host-deployer
Labels: size/XS

#23415 fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/apis/webconsole/consts.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancetype.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
Labels: size/L

#23416 Automated cherry pick of #23415: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/apis/webconsole/consts.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancetype.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
Labels: size/L

#23417 Automated cherry pick of #23415: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/apis/webconsole/consts.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancetype.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
Labels: size/L

#23418 Automated cherry pick of #23415: fix(region): vendor update
  go.mod
  go.sum
  pkg/apis/compute/storage_const.go
  pkg/apis/webconsole/consts.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/webconsole/service/handlers.go
  pkg/webconsole/session/remote_console.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancetype.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
Labels: size/L

#23433 Automated cherry pick of #23432: fix(cloudevent): options changed with etcd
  pkg/apis/cloudevent/cloudevent_const.go
  pkg/cloudevent/options/options.go
  pkg/cloudevent/service/service.go
Labels: size/S

#23428 Automated cherry pick of #23425: fix: backup task worker count in host configmap
  pkg/hostman/options/options.go
Labels: size/XS

#23422 Automated cherry pick of #23419: fix(region,baremetal): ipv6 baremetal register support
  pkg/baremetal/handler/handlers.go
  pkg/baremetal/manager.go
  pkg/baremetal/tasks/bm_register.go
  pkg/baremetal/tasks/cdrom.go
  pkg/cloudcommon/agent/agent.go
  pkg/compute/misc/handler.go
  pkg/compute/models/baremetalagents.go
  pkg/compute/models/hosts.go
  pkg/compute/models/networks.go
Labels: size/L

#23440 Automated cherry pick of #23435: fix: disable password history unique check by default
  pkg/keystone/options/options.go
Labels: size/XS

#23439 Automated cherry pick of #23435: fix: disable password history unique check by default
  pkg/keystone/options/options.go
Labels: size/XS

#23438 Automated cherry pick of #23435: fix: disable password history unique check by default
  pkg/keystone/options/options.go
Labels: size/XS

#23447 fix: hostman master nic may be nil
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#23448 Automated cherry pick of #23447: fix: hostman master nic may be nil
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#23450 Automated cherry pick of #23447: fix: hostman master nic may be nil
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#23451 Automated cherry pick of #23447: fix: hostman master nic may be nil
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#23453 Automated cherry pick of #23447: fix: hostman master nic may be nil
  pkg/hostman/hostinfo/hostinfo.go
Labels: size/XS

#23456 Automated cherry pick of #23455: fix(region): host order by virt cpu
  pkg/compute/models/hosts.go
Labels: size/XS

#23457 Automated cherry pick of #23455: fix(region): host order by virt cpu
  pkg/compute/models/hosts.go
Labels: size/XS

#23458 Automated cherry pick of #23455: fix(region): host order by virt cpu
  pkg/compute/models/hosts.go
Labels: size/XS

#23452 fix(region): vendor update
  go.mod
  go.sum
  pkg/cloudmon/providerdriver/ksyun.go
  pkg/compute/guestdrivers/ksyun.go
  pkg/compute/guestdrivers/managedvirtual.go
  pkg/compute/models/guests.go
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/apis/compute/storage_const.go
  vendor/yunion.io/x/cloudmux/pkg/cloudprovider/instance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_account.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_backup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/dbinstance_database.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/disks.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/eip.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/group.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/host.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/image.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instances.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/instancetype.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/keypair.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/ksyun.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/network.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/policy.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/project.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/region.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/secgroup_rules.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/securitygroup.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/tag.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/user.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/vpc.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/zone.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/monitor.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/qcloud/qcloud.go
Labels: size/XL

#23462 fix(cloudmon): metric sync
  pkg/cloudmon/providerdriver/ctyun.go
  pkg/cloudmon/providerdriver/qcloud.go
  pkg/cloudmon/providerdriver/volc.go
Labels: size/S

#23465 fix(region): vendor update
  go.mod
  go.sum
  vendor/modules.txt
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/snapshot.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/storages.go
  vendor/yunion.io/x/cloudmux/pkg/multicloud/ksyun/zone.go
Labels: size/M
